jenkins-infra/jenkins.io

content/_partials/navbar.html.haml, content/css/style.css, content/donate.adoc
Realistically this page should have always been on the website, but I believe
that it was added to the wiki due to the painful editing/authorship experience
we previously experienced with the site
Fixes WEBSITE-59
=> Move the donation page from the wiki into the static site

content/_layouts/post.html.haml, content/_partials/feedburner.html.haml
When I brought this over from Drupal, I had omitted any references to the feed;
time to bring it back
=> Link the feedburner-based RSS feed

content/css/style.css
This was driving me nuts, every list was being spaced out way too far as a
result of the `p` element's styling
The image below, left is production and right is with this change
=> Kill the unnecessary margin in our lists

content/_partials/navbar.html.haml, content/conduct.adoc
This is taken from this wiki page
(https://wiki.jenkins-ci.org/display/JENKINS/Code+of+Conduct) and was approved
in today's project meeting
(http://meetings.jenkins-ci.org/jenkins-meeting/2016/jenkins-meeting.2016-01-06-19.01.html)
This being added to the site should make it easier to find, and make it more
clearly an official policy for the project
=> Add an official-ish version of the approved Code of Conduct

content/solutions/pipeline.html.haml
This is still a bit basic, and mostly riffed from
https://wiki.jenkins-ci.org/display/JENKINS/Pipeline+as+Code but I'm starting
to see commonalities in Solutions pages.
=> Add a Solutions page for Pipeline as Code

content/_layouts/frame.html.haml, content/blogs.html.haml
Now it's easy to open GitHub and to see latest changes in the page.
Example:
@reviewbybees @rtyler
=> Added "Page history" links to pages containing GitHub link

LICENSE.adoc, content/_layouts/frame.html.haml, content/css/style.css
I completely forgot about this until now. MIT license is the license of the
Jenkins core repo, so I believe that to be sufficient. Whereas CC-BY-SA 4.0 I
believe is the appropriate content license
=> Introduce code and content licensing for the site

build.gradle
Womp womp
Starting process 'command '/usr/lib/jvm/java-7-openjdk-amd64/bin/java''. Working directory: /home/tyler/source/github/jenkins-infra/jenkins.io Command: /usr/lib/jvm/java-7-openjdk-amd64/bin/java -Dfile.encoding=utf-8 -Duser.country=US -Duser.language=en -Duser.variant -cp /home/tyler/.gradle/caches/modules-2/files-2.1/org.jruby/jruby-complete/1.7.23/98150edb47ccc36917c1ef475d694b91a3356245/jruby-complete-1.7.23.jar org.jruby.Main -S gem install /home/tyler/.gradle/caches/modules-2/files-2.1/rubygems/awestruct/0.5.7/c443be2604157f2cb542caaa158a2015618cabd8/awestruct-0.5.7.gem --ignore-dependencies --install-dir=/home/tyler/source/github/jenkins-infra/jenkins.io/build/tmp/asciidoctor --no-user-install --wrappers --no-document --local
Successfully started process 'command …
=> Pin to awestruct 0.5.6 since 0.5.7 introduces a Ruby 2.0 dependency

content/_layouts/post.html.haml
Posts only have a date, not a time, so show only the former. Keeps the unambiguous ISO 8601 format.
---
This also gets rid of some weirdness on pages like the changelog:
> Published on by kohsuke
If there's no date, it's likely there's no need for displaying the author either.
=> Only show date (in ISO-8601), only show author if date is set

content/content/event-calendar/index.html, content/stable-rc/index.html, content/welcome/index.html
None of these are interpreted any more and in fact they leek to the http response as is.
`content/welcome/index.html` seems outright unused on the first glance. I am not sure how `content/content/event-calendar/index.html` was supposed to work but it looks like XSS vulnerability back in PHP days.
=> Remove last remnants of php

content/2.0.html.haml
As reported by a few people on Twitter.
Ping @daniel-beck
Ping @jenkinsci/eastern-hemisphere :)
=> Fix broken wiki link on the 2.0 landing page.

content/blog/2016/2016-03-02-toulousejam-hackergarten.adoc
```
could not parse /blog/2016/2016-03-02-toulousejam-hackergarten.adoc
While processing file
An error occurred: (<unknown>): mapping values are not allowed here at
line 3 column 29
```
=> Missing quotes around title containing :

content/_ext/adoctoc.rb, content/_ext/pipeline.rb
Instead of requiring one big giant document, this allows us to create a series of chapters inside a single directory and then still have a cohesive table of contents on a "summary" page.
=> Introduce an awestruct extension for generation of tables of contents

content/doc/book/architecting-for-manageability.adoc, content/doc/book/architecting-for-scale.adoc
2 links still included whose content needs to be migrated to jenkins.io:
* Full list of exposed metrics by the Metrics Plugin - https://documentation.cloudbees.com/docs/cje-user-guide/monitoring-sect-reference.html#monitoring-sect-reference-metrics 
* Basic and advanced usages of Metrics Plugin metrics: https://documentation.cloudbees.com/docs/cje-user-guide/monitoring-sect-getting-started.html[here].
=> Cookbook cleanup: Architecting for Manageability and Architecting for Scale

content/redirect/find-jenkins-logs.adoc
This is the first such redirect which can be used in the the security token
screen in Jenkins 2.0 to help users find the security token
See also jenkinsci/jenkins#2115
=> Add the /redirect/ URL namespace for providing permanent links we can embed them

content/doc/index.html.haml
=> Are these meant to be anchors?

build.gradle
I'm not sure yet why this happens but on OS X 10.10+ with homebrew
eventmachine 1.2.0 consistently produces:
```
Building native extensions.  This could take a while...
ERROR:  Error installing
/Users/mmccaskill/.gradle/caches/modules-2/files-2.1/rubygems/eventmachine/1.2.0/66dac1bde48b857e23888a487fbbe452ebfd87b5/eventmachine-1.2.0.gem:
ERROR: Failed to build gem native extension.
java -cp
:/Users/mmccaskill/.gradle/caches/modules-2/files-2.1/org.jruby/jruby-complete/9.0.5.0/a5f1d5e8945a08ac9da8f7f528c513c60445eaeb/jruby-complete-9.0.5.0.jar
org.jruby.Main -r ./siteconf20160315-27388-17mrn1t.rb extconf.rb
NotImplementedError: C extensions are not supported
<top> at
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/mkmf.rb:1
require at org/jruby/RubyKernel.java:937
(root) at …
```
=> Limit eventmachine to 1.0.x series

content/doc/book/architecting-for-scale.adoc
These images use deprecated terminology and it is better to just omit them for
now.
In general, we will need to find a better way to manage and update images than
what we have right now.
Fixes WEBSITE-131
=> Remove dead and outdated images from the "Scale" chapter.

content/doc/index.html.haml, content/doc/pipeline/steps/ansible.adoc, content/doc/pipeline/steps/credentials-binding.adoc, content/doc/pipeline/steps/deployment-notification.adoc, content/doc/pipeline/steps/docker-workflow.adoc, content/doc/pipeline/steps/email-ext.adoc, content/doc/pipeline/steps/hipchat.adoc, content/doc/pipeline/steps/htmlpublisher.adoc, content/doc/pipeline/steps/index.html.haml, content/doc/pipeline/steps/integrity-plugin.adoc, content/doc/pipeline/steps/jira.adoc, content/doc/pipeline/steps/p4.adoc, content/doc/pipeline/steps/parallel-test-executor.adoc, content/doc/pipeline/steps/pipeline-utility-steps.adoc, content/doc/pipeline/steps/ssh-agent.adoc, content/doc/pipeline/steps/teamconcert.adoc, content/doc/pipeline/steps/workflow-basic-steps.adoc, content/doc/pipeline/steps/workflow-cps.adoc, content/doc/pipeline/steps/workflow-multibranch.adoc, content/doc/pipeline/steps/workflow-scm-step.adoc, content/doc/pipeline/steps/workflow-support.adoc
Static files for the pipeline-compatible steps.  They've been slightly tweaked so there's at least a better description for each of the steps.  These are all the plugins that I know are pipeline compatible at the moment.  More can be added as they're found.
The index page is a listing of all the plugins with their steps & a short description.  This way, the user will know what plugin they'll have to install.
=> WEBSITE-129 - Add pipeline steps reference documentation.

content/_partials/carousel.html.haml
This commit also brings back the dynamic versions to the carousel
This fixes a small regression introduced in #156
=> Correct Haml indentation error

content/_partials/downloadlist.html.haml, content/css/jenkins.css
Apparently the same result but not.
```
.btn-group{:style=>'margin-top: 1.3125rem;'}
```
It is recommendalbe to avoid this kind of things.
@reviewbybees
=> Right vertical positioning in div.popover-content

content/_ext/activenav.rb, content/_ext/pipeline.rb, content/_layouts/default.html.haml, content/_layouts/solution.html.haml, content/_partials/toptoolbar.html.haml, content/conduct.adoc, content/doc/index.html.haml, content/node/index.html.haml, content/press.adoc, content/security.adoc
This has been annoying me, so I fixed it over the weekend.
=> Make it more clear/obvious to the browser which page in the topnav they're on

content/security.adoc
Security page should be using https for everything it can.
There is an argument for updating all the old blogs / changelogs etc, but that is a bigger PR (mechanical work though).
=> Switch to https for issues / feedburner links on security page

content/hangout.adoc, content/redirect/hangout.adoc
This commit also adds a redirect permalink under jenkins.io/redirect/hangout
which can/should use more in the future.
[WEBSITE-167](https://issues.jenkins-ci.org/browse/WEBSITE-167)
=> Add a jenkins.io/hangout redirect URL

content/doc/book/securing-jenkins.adoc
... to at least provide a navigability from http://jenkins.io/
More fuller treatment of the content requires a bigger work and it
shouldn't be on the critical path for communication.
=> Importing the top-level security content in jenkins.io

content/_partials/downloadlist.html.haml
I'll be truthful - I didn't test this - I ran the gradle assembly job a few times and it aborted every time with nonsensical errors.
I assume there is a test deployment somewhere - but I wasn't able to find it.
=> Get rid of the space between the version and the .war

content/_partials/downloadlist.html.haml
This reverts commit bff124d4cdd3f8598ca584411c1e37518a6739a6 from #233.
As explained there:
> That space was actually important, because it's not referring to the file name. Just the version of Jenkins, and the way it's packaged. Think *2.0 rpm*. `.war` doesn't lend itself to leaving off the leading period, unfortunately.
CC @rtyler @bwalding
=> Revert "OMG Whitespace"

content/blog/2016/2016-05-11-security-update.md
There are likely a lot more plugins broken, but some information is better than none.
Or perhaps this should link to a wiki page?
=> Add an initial list of known plugins affected by SECURITY-170.

content/_partials/toptoolbar.html.haml, content/css/jenkins.css, content/projects/gsoc.adoc, content/projects/index.adoc, content/projects/jam.adoc
There are a couple initiatives within the Jenkins project which are are not
quite "core" or "plugins" in the traditional sense that we have had in the
project. These projects generally expand the horizons of Jenkins in a social or
technology aspect and as such I think require some escalated visibility inside
of the jenkins.io site structure.
=> Introduce /projects/ pages to give a more discoverable home to some of our projects

content/projects/blueocean.adoc
Text had said "Watch the the mailing lists and repos to keep on top of the latest activity. 
Some parts you will see are in stages of design, others are already implemented." Proposal is to remove redundant "the"
=> Redundant "the" in first para of tour section

content/_layouts/frame.html.haml, content/_partials/legacy/navbar.html.haml, content/changelog-stable/index.html
See also https://github.com/jenkins-infra/rating/pull/8
=> Reference ci.jenkins.io rather than ci.jenkins-ci.org

content/doc/pipeline/index.adoc
Downstream of https://github.com/jenkinsci/workflow-cps-plugin/pull/35. Similar to https://github.com/jenkinsci/pipeline-plugin/issues/401; someone seems to have copied & pasted a bunch of documentation, so now we have two copies to maintain.
@reviewbybees esp. @kohsuke, @abayer
=> [JENKINS-29922] Documentation update

content/solutions/pipeline.adoc
Old CloudBees documentation link is replaced with new CloudBees Network link.
The old link was still working but it was leading to the first chapter of the Cookbook.
The new link leads directly to the "Continuous Delivery with Jenkins Pipeline" chapter.
=> Link in the Pipeline Use-case is fixed

build.gradle, scripts/fetch-external-resources
Automatically create pipeline step documentation.  This goes out to the PipelineStepsDoc job, and grabs the last successful build artifact for use in the documentation section of the website.  This contains the most recent pipeline step information for the plugins in the Jenkins maven repository.
=> [INFRA-607] Pipeline steps documentation update

content/doc/book/pipeline-as-code.adoc
Link to "Pipeline plugin" had an extra colon that was causing it to 404 to the user
=> Fix broken link

content/_ext/solutionpage.rb
This fixes an issue @alyssat noticed with our /s/ruby type URLs no longer
working (404)
=> Support solution page short-links for anything not .html.haml

content/index.html.haml
Jenkins World is over, and the previous jumbotron was "2.0 is here" which is a bit outdated.  So we can live without it until the next special event comes along.
=> Remove Jenkins World jumbotron from the home page.

content/changelog-stable/index.html
Style is annoying but intended to be temporary to inform those who
may directly access the changelog and not see the link in the popup.
---
I also removed the 'upcoming changes' link (but kept the hidden div, IIRC the JavaScript needs it to not mess up displaying votes), since we're never populating that for LTS.
> ![screen shot](https://cloud.githubusercontent.com/assets/1831569/19063472/7b793628-8a03-11e6-9947-c26fea2bd1c3.png)
@oleg-nenashev @olivergondza @rtyler Please review.
=> Add link to upgrade guide from changelog.

content/doc/book/hardware-recommendations.adoc
I put the really long url and [link text] on a single line so that they would render correctly. Don't know if adoc has a way to do this on multiple lines.
=> fix "Seven Habits of ..." link text due to line wrap in source

Gemfile, STYLEGUIDE.adoc, build.gradle, content/_ext/pipeline.rb, content/blog/2016/2016-09-19-blueocean-beta-declarative-pipeline-pipeline-editor.adoc, content/css/jenkins.css, lib/asciidoctor/extensions/pipeline-block.rb
In use, a documentation and/or blog post author might write:
```asciidoc
[pipeline]
----
// Script //
node {
stage('Build') {
checkout scm
// Install dependencies
sh 'npm install'
}
}
// Declarative //
pipeline {
agent docker: 'node:6.3'
stages {
stage('Build') {
sh 'npm install'
}
}
}
----
````
In practice, this renders with preference to Declarative Pipeline, such as this example from @i386's most recent Declarative Pipeline blog post:
In the case when only Declarative or Script is available, that will be shown by default.
=> Add the [pipeline] block for nicely enumerating either/or/both Declarative and Pipeline Script

content/_ext/handbook.rb, content/_ext/pipeline.rb
To create a new structure, add another extension instance in
`content/_ext/pipeline.rb`, e.g.:
extension Awestruct::IBeams::HandbookExtension(:devbook, full_path_to_book_dir)
=> Add support for multiple handbook type structures on `site`

content/doc/book/index.html.haml
The current outline looks just ridiculously bad, and it also wastes a lot of vertical space. This fixes that.
=> Don't use headers for the outline

content/doc/book/getting-started/installing.adoc
We should use `brew install jenkins` instead of `brew cask install jenkins`. Jenkins is installed by `brew` not `brew cask`.
=> fix: brew install in OS X

STYLEGUIDE.adoc
And this is why hard line wraps at a specific line length are stupid. It makes additions impossible to diff. Let's please not do that anymore.
=> Require American English, mention sentence case for titles

STYLEGUIDE.adoc, lib/asciidoctor/extensions/javadoc-link.rb
- support for short name and full name
- for full names, supports anchors
=> Add inline macro for Javadoc links

content/_layouts/chapter.html.haml, content/_layouts/section.html.haml
I find it a bit confusing to be on a chapter "index" page and have the
right-arrow navigation link take me to the next chapter. This change makes the
right-arrow link take the reader to the first section.
On the last section in the chapter, the right-arrow becomes the next chapter.
The left-arrow link will always be the previous section (if in the sections) or
the previous chapter (if in the chapter).
This should make it clearer how a reader should navigate through chapters and
sections by just clicking right-arrow, right-arrow, right-arrow
=> Update the handbook navigation to make the "next" link point to the next section or chapter

content/projects/jam/suggest.html.haml
This was requested by our Events Officer (@alyssat) and I finally got around to
it :)
It's pretty basic for a first revision, depending on how JAM organizers feel
about the page we may see additional changes in short order
=> Implement a simple JAM topic suggestion page

content/_ext/handbook.rb, content/doc/book/index.html.haml
Usage:
Add `summary` to the front matter of a chapter or section for the handbook.
Looks like this (content change is not part of the PR -- except the font size change, nothing should change in presentation in this PR):
> ![screen shot 2016-12-05 at 16 57 55](https://cloud.githubusercontent.com/assets/1831569/20891780/1796bc36-bb0c-11e6-85f3-82523b2c2405.png)
=> Add ability to define summaries for handbook chapters and sections

content/doc/book/pipeline/shared-libraries.adoc
Fixes [JENKINS-38868](https://issues.jenkins-ci.org/browse/JENKINS-38868)
=> When describing classes in a Pipeline Shared Library that have "data" they must be serializable

content/doc/book/pipeline/shared-libraries.adoc
This should help explain behavior seen and reported in tickets like [JENKINS-39565](https://issues.jenkins-ci.org/browse/JENKINS-39565)
=> Clarify what global variables really are and how they behave in Shared Libraries

content/doc/book/glossary/index.adoc
For reference, some of these terms were cleared up (but not all) during the
Jenkins 2 preparation by @orrc:
* jenkinsci/jenkins#2101
* jenkinsci/jenkins#2137
I don't expect this to be the complete glossary, but enough to make it easy to
refer to common terms from other chapters
=> Add many more terms to the glossary for reference by other chapters in the user handbook

content/_partials/downloadlist.html.haml
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>
=> [WEBSITE-275] Fix LTS docker link to point to the LTS docker image

content/doc/book/pipeline/index.adoc
Corrected misspelling of "used" and remove oddly placed full stop from the "Stage" term definition of https://jenkins.io/doc/book/pipeline/.
Minor corrections, but given they were featured on a prominent page from jenkins.io, I thought it worth adding this fairly small PR - let me know if you don't normally accept single edits like this.
=> Correct misspelling in "Pipeline" book topic

content/blog/2017/2017-01-12-declarative-pipeline-beta-2.adoc
cc @HRMPW @michaelneale @i386 @rtyler 
fwiw, I put the 12th as the date 'cos I expected a two day delay to going live, but if @rtyler wants to take it live sooner, that's fine by me. =)
=> Blog post on Declarative beta 2 (0.8.1 release)

content/doc/book/managing/security.adoc
duplicate `is` used in security doc.
=> Fix minor typo

content/blog/2017/2017-01-17-Jenkins-is-upgrading-to-Java-8.adoc
Now the CI build does run on Windows too, and is back to green, it's time to act on the plan I think.
@olivergondza @kohsuke @daniel-beck @oleg-nenashev @rtyler @slide @orrc @jtnord @jglick
=> Upgrade to Java 8 - announce the plan

content/doc/pipeline/steps/index.html.haml
=> Remove unnecessary ToC layout for the pipeline steps index.

CONTRIBUTING.adoc
CONTRIBUTING.adoc linked to localhost:8000 when describing where the site is hosted, but the gradle run task starts it on 4242
=> corrects the port used in the gradle run task description

content/doc/pipeline/tour/hello-world.adoc
With the previous version, you get a syntax error when starting the build:
```
WorkflowScript: 2: Expected an agent @ line 2, column 5.
agent { docker:'maven:3.3.3' }
^
WorkflowScript: 2: No agent type specified. Must be one of [docker, dockerfile, label, any, none] @ line 2, column 5.
agent { docker:'maven:3.3.3' }
^
2 errors
```
=> hello-world: fix syntax for docker agents

content/_layouts/section.html.haml
=> Remove errant quotation mark in section navigation.

CONTRIBUTING.adoc, build.gradle, content/_config/site.yml
Running `./gradlew assemble` takes ~forever, so it's nice to run in awestruct dev mode, which will only compile pages that you access (and re-compile if they're changed).
=> Fix broken Gradle dev task for on-the-fly page generation

content/projects/gsoc.adoc
The restructuring is required to simplify the layout and to allow referencing particular projects. Tables are also PITA. The new structure also seems to be better:
=> [WEBSTITE-306] - Restructure the page

content/blog/2017/2017-02-06-scm-api-2-take2.adoc
The post currently shows Mercurial 2.0.0 as the recommended version of Mercurial. The newest available version is 1.58, so maybe we should change to reflect that.
=> Change Mercurial version from 2.0.0 to 1.58

content/doc/book/pipeline/syntax.adoc
The tools section doesn't support `java`, it supports `jdk`.
@abayer
=> Changed tools to support jdk instead of java

content/doc/book/pipeline/index.adoc
There are two links in this page which are broken in the same way. They're both missing pipeline in their paths. 
https://jenkins.io/doc/book/syntax/
https://jenkins.io/doc/book/Jenkinsfile/
These should both get changed to 
https://jenkins.io/doc/book/pipeline/syntax/
https://jenkins.io/doc/book/pipeline/Jenkinsfile/
=> Link fix for https://issues.jenkins-ci.org/browse/WEBSITE-310

content/doc/book/pipeline/index.adoc
I meant to catch this in 602, but my eyes were playing tricks on me. The Jenkinsfile link is pointing to https://jenkins.io/doc/book/pipeline/Jenkinsfile/ . Note the uppercase J - that breaks the link. Changing it to a lowercase j fixes it.
=> Correct Jenkinsfile to lowercase j

content/_layouts/simplepage.html.haml
Example use case: `sections_from` and `simplepage` are weird to combine when it's only one section per document, e.g. in https://jenkins.io/doc/upgrade-guide/2.19/ where I had to improvise with a general title to not have redundancy.
Some documents may not even be able to not have weird redundancy there, as the actual page title is also needed in the `sections_from` list. Looking at you, all Pipeline step pages.
(FWIW I needed to put `notitle: whatever` into the front matter for this to work, `:notitle:` didn't, including on at least some pages that already set that -- what's up with that?)
=> Allow simplepage to have notitle

content/project/governance.adoc
Preparation to migrate https://wiki.jenkins-ci.org/display/JENKINS/Governance+Document to the site. (Not yet linked from any footer/menu items.)
This change (and the corresponding removal of the wiki page's contents) may be subject to approval by the governance meeting, not sure.
=> Add governance document

content/donate.adoc
Incorporate a few minor changes from https://wiki.jenkins-ci.org/display/JENKINS/Donation (notably, those pages appear to have never had identical content…) in preparation for removal of the wiki page.
=> Update /donate page so it can replace the Donation wiki page

Jenkinsfile
The following warnings are still in the build and I'm not sure how to fix them:
* `no callouts refer to list item`
* `skipping reference to missing attribute`
So these are excluded (for now).
All other warnings, Both asciidoctor and awestruct, will fail the build.
Depends on #614, #618, #620.
=> Parse Gradle build log for warnings and fail if found

Jenkinsfile
… because the Gradle build for https://github.com/jenkins-infra/jenkins.io/pull/621 actually failed.
=> Set pipefail

Jenkinsfile, content/blog/2017/2017-02-07-declarative-maven-project.adoc, content/doc/book/pipeline/jenkinsfile.adoc, content/doc/book/pipeline/syntax.adoc, lib/asciidoctor/extensions/pipeline-block.rb
> ![screen shot](https://cloud.githubusercontent.com/assets/1831569/22809145/7f2adf96-ef30-11e6-81ba-674916ac0379.png)
The regex pattern is a bit limited in what it can recognize, hence weirdness like `// <1> // <2>`, but I didn't want take the time to understand https://github.com/asciidoctor/asciidoctor/blob/76ac457a1d777d7186db624cad67f2366c2186ee/lib/asciidoctor.rb#L747...L748 and we don't need most of the supported syntaxes anyway.
`/* <1> */` isn't even supported by real AsciiDoctor, so I just rewrote those.
As callouts are now being registered correctly, these warnings are no longer excluded from failing the build.
=> [FIX WEBSITE-312] Callouts for [pipeline] blocks

content/doc/book/pipeline/syntax.adoc
Using `:` after the key in both forms of the `docker` block are incorrect.
I copy-pasted the fixed versions into Jenkins and they worked as expected.
=> Fix syntax in Declarative `docker` examples.

content/doc/book/pipeline/jenkinsfile.adoc
=> Fix a few minor syntax and formatting errors in 'Using a Jenkinsfile'.

content/participate/index.html.haml
=> Add security team to 'Code' section on /participate

content/_layouts/documentation.html.haml, content/doc/upgrade-guide.html.haml, content/doc/upgrade-guide/2.19.adoc, content/doc/upgrade-guide/2.32.adoc, content/doc/upgrade-guide/2.7.adoc
This getting hidden was an omission. This commit also changes the Upgrade
Guides's layout to be documentation for better navigation in and out of the
upgrade guides
Fixes WEBSITE-305
=> Incorporate LTS Upgrade Guides back into the documentation structure

content/doc/pipeline/tour/tests-and-artifacts.adoc
Added a missing 'are' into tests-and-artifacts.adoc.
=> add missing word in tests-and-artifacts.adoc

content/doc/pipeline/steps/index.html.haml
Because this sort order makes no sense:
> ![screen shot](https://cloud.githubusercontent.com/assets/1831569/22913902/e71b35fc-f26d-11e6-811d-4b2f61d73700.png)
Even better with all the https://github.com/jenkins-infra/pipeline-steps-doc-generator/pull/5 goodness.
=> Sort pipeline steps documentation case-insensitively

Jenkinsfile, content/_config/site.yml
PR build should ideally be `production` profile to demonstrate this doesn't break things again.
More build logs can't really hurt. 50 builds is one day.
=> Keep more builds, and use development profile again

content/_layouts/frame.html.haml, content/_layouts/pipelinesteps.html.haml, content/changelog-stable/index.html, scripts/fetch-external-resources
* `changelog` is now uneditable, as it's sourced from jenkinsci/jenkins
* `changelog-stable` is still editable, as it's stored in this repo
* Generated Pipeline steps are uneditable
* New layout for generated Pipeline steps to centralize their styling.
Somewhat unrelated:
* Make changelogs from `post` into `simplepage`, no need to tweet or left-align those
=> Add option to not offer link to edit page on GitHub

content/changelog-stable/index.html
* Switch from wiki to site URL when reference to security advisory is present
* Add reference to advisory (on the site, obviously) when it was missing
* Remove individual list entries for security fixes, those were often incomplete anyway
I also checked that all (core) security advisories are now referenced -- the old changelog process (autogenerated and stored on cucumber) resulted in versions with no listed security fixes, and no reference to the advisory. So while these old changelogs are probably frequently incomplete, at least we now reference all the advisories.
=> Reference security advisories in LTS changelog

content/sites/default/files/.htaccess
First line is Drupal-specific: https://www.drupal.org/files/sa-2006-006/advisory.txt
The rest is useless as well I think.
=> Get rid of obsolete .htaccess with illegal rules

Jenkinsfile
Supports https://github.com/jenkins-infra/jenkins-infra/pull/688 to prevent problems like https://github.com/jenkins-infra/jenkins.io/pull/664 which caused Internal Server Errors
=> Fail the build if illegal .htaccess content was found

content/changelog-stable/index.html.haml, content/changelog/index.html.haml
Now we can amend the changelog whenever we like (Saturdays? Monday before LTS release? \*gasp\*) and don't have to care about when the actual release happens.
Actual diff: https://github.com/jenkins-infra/jenkins.io/pull/673/files?w=1
CC @oleg-nenashev @olivergondza
=> Do not show changelog entries for unreleased versions

content/_layouts/redirect.html.haml
Add infrastructure for localizable redirects based on browser language. Can be used to implement en/ja wiki switch in redirect URLs for https://github.com/jenkinsci/jenkins/pull/2756
One minor issue: The clickable link and its label are not localized, only the JS redirect is. I just didn't care enough to clean this up.
=> Add localized redirect capability

content/changelog.css
This messed up the title bar on the changelog pages compared to other URLs:
Compare:
https://jenkins.io/changelog/
https://jenkins.io/events/
=> Reset changelog style reset

content/mailing-lists.adoc
Generating pages...
asciidoctor: WARNING: mailing-lists.adoc: line 13: section title out of sequence: expected level 2, got level 3
asciidoctor: WARNING: mailing-lists.adoc: line 24: section title out of sequence: expected level 2, got level 3
asciidoctor: WARNING: mailing-lists.adoc: line 35: section title out of sequence: expected level 2, got level 3
asciidoctor: WARNING: mailing-lists.adoc: line 42: section title out of sequence: expected level 2, got level 3
asciidoctor: WARNING: mailing-lists.adoc: line 49: section title out of sequence: expected level 2, got level 3
asciidoctor: WARNING: mailing-lists.adoc: line 56: section title out of sequence: expected level 2, got level 3
asciidoctor: WARNING: mailing-lists.adoc: line 65: section title out of sequence: expected level 2, got …
=> Fix warnings about wrong header sequence

content/_partials/changelog-stable.html, content/_partials/changelog-weekly.html, content/changelog-old.html, content/changelog-stable.html.haml, content/changelog.html.haml, content/css/jenkins.css
Right now, linking to anchors (typically elements with ID) results in scroll positions with the link target hidden behind the top navigation bar. Examples:
https://jenkins.io/security/#team
https://jenkins.io/changelog-stable/#v1.625.3
This PR fixes that behavior by offsetting the effective position of the anchor by the height of the header to the top without changing how the page looks.
I couldn't get it to work for `a[name]` (different offset was needed and I didn't find out why), so rewriting the changelog to use header tags with ID as well. That's the bulk of this PR. This slightly changes the presentation, as headers in changelogs will no longer be link colored and get underlined on hover, but black with no underline (which IMO is an improvement)
=> Offset the header height for anchor elements

Jenkinsfile
If I'm guessing right, this PR build should fail while #685 isn't merged.
=> Redirect stderr to stdout and exclude user handbook warnings

build.gradle, content/_layouts/documentation.html.haml, content/_layouts/post.html.haml, content/_layouts/project.html.haml, content/_layouts/simplepage.html.haml, content/_partials/scriptlinks.html.haml, content/_partials/toptoolbar.html.haml
Similar to GitHub documentation rendering, shows anchor link to the header on hover.
> ![screen shot](https://cloud.githubusercontent.com/assets/1831569/23166801/4d2cfd4c-f842-11e6-8af0-2515722e9471.png)
This is limited to `.content .body`, which means the current `documentation` layout is not supported. Unclear to me why that's not `class="row body"` like e.g. `simplepage`. Adaptation also needs to think about the side bar, to not make those headers clickable (or maybe we do want that? Not sure).
=> Add anchor links to headers

content/css/jenkins.css
https://github.com/jenkins-infra/jenkins.io/pull/682#issuecomment-281479747 mentions some weird behavior with combining anchor links and the margin for headers to offset the navigation bar height.
This addresses the problem by not showing the anchor links when the header itself is hovered, only the area to its right. To make it not too difficult to find however, the area is enlarged at the same time (shown below as focus border).
> ![screen shot](https://cloud.githubusercontent.com/assets/1831569/23239615/a26b1a4c-f968-11e6-9644-f0df38624e8a.png)
=> Only show anchor links when they're hovered, not titles

build.gradle, content/_config/site.yml
* `project.ext` is only needed for the initial definition of a new property, after that it's redundant.
* I set a different `--url` and checked the output with and without it, in neither case did the new base URL actually show up anywhere.
* The `hasProperty` check looked at the task, not the project, so could never be true.
* Make `production` work even when there's a `development` profile through redundant base URL definition. (Should check PR build output just to be safe.)
=> Fix profiles

content/_partials/changelog-stable.html, content/_partials/changelog-weekly.html
I skipped the `/changelog-old`, but its security fix entries were pretty crappy to begin with.
=> Add 'security' class to old changelog entries

content/events.html.haml
Followup to @oleg-nenashev's #689 in which a short label was used, but the workaround for long labels applied anyway.
=> Don't use smaller text for short label

content/_data/changelogs/lts.yml
After merging #694's removal of `chomp` due to obvious problems, we need periods at the end of all messages.
=> Add missing periods

content/css/jenkins.css
Still not great (it's sometimes a bit wasteful now), but less easily broken.
New:
> ![screen shot 2017-02-26 at 15 23 07](https://cloud.githubusercontent.com/assets/1831569/23340516/da4ac5f8-fc37-11e6-9b39-e6f5433250fe.png)
Old:
> ![screen shot 2017-02-26 at 15 23 21](https://cloud.githubusercontent.com/assets/1831569/23340517/dbb8112a-fc37-11e6-8041-c6a5e621c7d5.png)
Example of some documentation page showing how this would look:
> ![screen shot](https://cloud.githubusercontent.com/assets/1831569/23340530/1da47812-fc38-11e6-8406-e3e1d28d6f00.png)
> ![screen shot](https://cloud.githubusercontent.com/assets/1831569/23340539/3d368a6c-fc38-11e6-9bdb-482bd582c2f7.png)
=> Wider table of contents

content/doc/book/pipeline/syntax.adoc
When testing out the multibranch pipeline build i also used the currently documented 'pollScm' trigger, which led to an error with a message telling me the correct naming 'pollSCM' with capitalized SCM letters.
```
WorkflowScript: 14: Invalid trigger type "pollScm". Valid trigger types: [upstream, cron, pollSCM] @ line 14, column 3.
pollScm('H/2 8-18 * * 1-5')
^
1 error
at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:310)
at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1085)
at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:603)
at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:581)
at …
```
=> Fix pollSCM trigger description and example in pipeline syntax description

content/events.html.haml, content/projects/gsoc.adoc, content/projects/gsoc/gsoc2017.adoc, content/projects/gsoc/students.adoc
The project application has been rejected, so let's cleanup the content
CC @rtyler @batmat @chtist66 @rsandell
=> [GSoC2017] - Shutdown the website.

content/doc/book/pipeline/syntax.adoc
https doesn't appear to work when trying to access http://groovy-lang.org/
=> Fix Groovy syntax page link

content/_data/changelogs/lts.yml, content/_partials/changelog-weekly.html
It was a missing fix, since I didn't notice there is a Jenkins JIRA issue for it.
This PR updates the Weekly release entry and also adds the missing entry for the Stable release
https://issues.jenkins-ci.org/browse/JENKINS-24453
CC @daniel-beck and @olivergondza
=> [JENKINS-24453] - Noting fix in Jenkins 2.34 and 2.32.1

scripts/release.rss.groovy
Depends on https://github.com/jenkins-infra/backend-update-center2/pull/118
Untested.
---
Also fixes a typo. I doubt that one is intentional…?
=> Reference plugins site URL in releases.rss

content/_data/changelogs/weekly.yml
* NEW: https://github.com/jenkinsci/jenkins/pull/2765
* NEW: https://github.com/jenkinsci/jenkins/pull/2778
* NEW: https://github.com/jenkinsci/jenkins/pull/2780
* NEW: https://github.com/jenkinsci/jenkins/pull/2683
* NEW: https://github.com/jenkinsci/jenkins/pull/2773
* UPD: https://github.com/jenkinsci/jenkins/pull/2772 (CC @stephenc)
@daniel-beck
=> Noting changes towards 2.50

build.gradle
See prawnpdf/prawn-templates#14
=> Pin our prawn gem dependency (used to render PDFs) to 2.1.0

content/_data/changelogs/weekly.yml
Minor change implemented on request in #2683 which potentially has large user impact.
=> Case sensitive search by default in 2.50 changelog

content/blog/2016/2016-07-18-pipline-notifications.adoc, content/blog/2017/2017-02-15-declarative-notifications.adoc
The workflow-support-plugin [intends][0] to make checking for `currentBuild.result == null` redundant in future.
However, this will have a knock-on effect for pipelines that only check for `null` and not additionally for `'SUCCESS'`.  As noted in that PR comment, there are a number of pipelines in the wild that would be affected — including one which copy-pasted from the Jenkins blog at some point.
In future, if `currentBuild.result` returns `'SUCCESS'` where it previously returned `null`, the code `buildStatus ?: 'SUCCESSFUL'` as used in these blog posts would break — the `if` statement would fall through to the `else` branch.
This change fixes the example code to be future-proof by using the [correct `Result` constant][1].
[0]:https://github.com/jenkinsci/workflow-support-plugin/pull/31# …
=> Fix erroneous use of 'SUCCESS' in Pipeline examples in blog posts.

content/doc/book/pipeline/syntax.adoc
Following the syntax in the tutorials as is throws this error:
`java.lang.IllegalArgumentException: Could not instantiate {time=1, unit=HOUR} for TimeoutStep(time: int, unit?: TimeUnit[NANOSECONDS, MICROSECONDS, MILLISECONDS, SECONDS, MINUTES, HOURS, DAYS]): java.lang.IllegalArgumentException: No enum constant java.util.concurrent.TimeUnit.HOUR`
Changing it to `HOURS` works as the documentation describes.
=> HOUR is invalid time unit.

content/doc/book/pipeline/jenkinsfile.adoc
The original Jenkinsfile sample causes the following error:
```
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
WorkflowScript: 6: Expected a step @ line 6, column 20.
when { currentBuild.result == 'SUCCESS' } // <1>
^
WorkflowScript: 6: Unknown conditional null. Valid conditionals are: branch, environment, expression @ line 6, column 20.
when { currentBuild.result == 'SUCCESS' } // <1>
```
=> Fix wrong when directive usage in `Using a Jenkinsfile` doc

content/doc/book/pipeline/syntax.adoc
[JENKINS-41118](https://issues.jenkins-ci.org/browse/JENKINS-41118) - Declarative PR [#123](https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/123)
Also adding `node` `agent` type (which is just an alias for `label`,
but hey) and the `reuseNode` option for `docker` and `dockerfile`,
which we should have added earlier but forgot. Whoops.
The Declarative PR will be merged shortly, with the 1.1 release of Declarative planned for later this month. I'll remove the WIP tag when the release is done.
cc @bitwiseman @rtyler
=> JENKINS-41118 - add customWorkspace docs

content/doc/pipeline/tour/hello-world.adoc, content/doc/pipeline/tour/running-multiple-steps.adoc
I found a few small errors when going through the tour, which I fixed.
I also updated the post-build examples to work as expected — fixed a syntax error, used `echo` rather than `sh`, and ensured that failed builds are marked as such, rather than appearing successful. I  also added the "changed" post-build behaviour to the Scripted example.
Various scenarios in Declarative and Scripted were tested in Jenkins and worked as expected.
=> Small fixes for Pipeline tour

content/_data/changelogs/weekly.yml
Forgot this since squashed merges with overly long titles don't show the PR number, which is how I find relevant changelog entries.
@oleg-nenashev
=> [JENKINS-42724] Add changelog entry

build.gradle
The upstream issues have been fixed \o/
This reverts commit 829374d3f352b3f31c69488d140c2ca833dc13a8.
=> Revert "Pin our prawn gem dependency (used to render PDFs) to 2.1.0"

content/doc/book/blueocean/getting-started.adoc
Currently plugin link is pointing to: https://plugins.jenkins.io/blue-ocean, it will throw 404, the right url is: https://plugins.jenkins.io/blueocean
=> Fix blue ocean plugin link

content/events.html.haml
This makes it such that the page doesn't get any anchor-js anchors
@daniel-beck whatcha think?
=> Switch the Events page away from a simplepage

content/_layouts/frame.html.haml
From @brody "open graph is fine with the relative URL but twitter needs
absolute... short answer, Yes."
Closes #803
=> Ensure that og:image meta tags generate a full URL rather than absolute

content/_layouts/simplepage.html.haml, content/security/advisories.html.haml
Bootstrap gets grumpy when DOM elements are improperly contained in its grid
system. For example, outer DOM elements were "containers" but then stuff inside
them was all splashed about. Like with XML, the only solution is more containers.
Fixes WEBSITE-347
=> Tidy up the rendering of the security related pages

content/_data/changelogs/weekly.yml
Also clean up some older entries:
- Use `<code>` rather than `<tt>` for code/file paths/similar
- Don't use any special highlighting for version numbers
- Don't use both top-level `issue` and `pull` _and_ `references`, the presentation is currently weird.
> ![screen shot](https://cloud.githubusercontent.com/assets/1831569/24829976/d194ca66-1c7c-11e7-92bf-e03e471e74a4.png)
----
@oleg-nenashev Could we standardize on the above for future changelog entries?
=> Add changelog for 2.54 with new CLI and Java 8 requirement

content/security/advisory/2017-04-10.adoc
Minor: `<tt>` currently appears literally on the page, rather than being `monospaced`.
=> Fix code formatting syntax for Grails plugin entry.

content/blog/2017/2017-04-10-security-advisory.adoc, content/security/advisory/2017-04-10.adoc
Specifically, the authorization strategies aren't fixing vulnerabilities, just making it less easy to configure Jenkins in a typically undesired way (giving non-admins permission to run scripts).
=> Clarify it's not just vulnerabilities

content/doc/book/managing/cli.adoc
Presumes https://github.com/jenkinsci/jenkins/pull/2795 is merged.
@reviewbybees
=> [JENKINS-41745] Updating CLI documentation for non-Remoting modes

content/security/advisory/2017-04-10.adoc
internal links on pages do not work outside the wiki
=> changed links to point to the Job DSL wiki

content/doc/book/managing/cli.adoc
Not sure whether this should be fixed a different way, but for now should fix the layout breakage in https://jenkins.io/doc/book/managing/cli/#common-problems-with-the-remoting-based-client
=> Don't break CLI page layout

content/security/index.adoc
Old link: https://freenode.net/faq.shtml#userregistration
Corrected link for convince: https://freenode.net/kb/answer/registration
=> fix dead link to register nickname on IRC

content/doc/book/managing/cli.adoc
Integrating testing of the new `-http` mode of `jenkins-cli.jar` turned up a problem with an nginx reverse proxy that enabled `proxy_request_buffering`. While we cannot provide exhaustive guides to proxy configuration here, we can at least remind readers to check these settings.
@reviewbybees
=> Noting that buffering should be disabled in reverse proxies

content/doc/book/managing/cli.adoc
The [wiki mentions this property](https://wiki.jenkins-ci.org/display/JENKINS/Jenkins+SSH) but it is newly relevant since this is the first time the CLI is paying attention to the SSH endpoint.
@reviewbybees
=> Noting org.jenkinsci.main.modules.sshd.SSHD.hostName

content/doc/pipeline/tour/tests-and-artifacts.adoc
Example code is missing a character.
=> Missing 'w' for gradle wrapper

content/_data/changelogs/weekly.yml
It was not apparent when we updated our hosts and lost the connections to workers... so as we figured it out (and lost some time doing so), we thought it should have been more visible from the changelog.
=> Revise message for 2.54 (stress java8 on agents)

content/blog/2017/04/2017-04-12-welcome-to-blue-ocean-dashboard.adoc
If you look [here](https://jenkins.io/blog/2017/04/12/welcome-to-blue-ocean-dashboard/), the link in the post is broken. It looks like the date is wrong. Here is the [correct link](https://jenkins.io/blog/2017/04/11/welcome-to-blue-ocean-pipeline-activity/) that should be present.
=> Fixed link to pipeline activity blog post

content/mailing-lists.adoc
Irrelevant emails will not be posted. That means: not only spam, but also emails clearly targeting -users ML and not following the advice already in bold for long...
=> Clarify the policy about first-posters on -dev

content/download.html.haml
'registry.hub.docker.com' redirects now to 'hub.docker.com'.
This change also fixes a wrong redirect:
https://hub.docker.com/r/jenkinsci/jenkins/ would go to the home page.
=> Fix links to Docker Hub

content/_data/changelogs/weekly.yml
As discussed in today's governance meeting, we're cutting 2.60 early. This will allow us to pick this release as the next LTS baseline in two weeks (assuming no major regressions) while not blocking further development of major changes whose inclusion would likely disqualify any release from becoming LTS baseline.
Meeting log with further details and discussion: http://meetings.jenkins-ci.org/jenkins-meeting/2017/jenkins-meeting.2017-05-10-18.00.log.html#l-223
> ![screen shot](https://cloud.githubusercontent.com/assets/1831569/25919749/f3ec62a6-35cf-11e7-8790-49c8d510d177.png)
=> Add changelog for 2.60

content/changelog-stable.html.haml, content/changelog.html.haml
Pro: Otherwise, the "improve this page" link is pretty useless on the changelog pages for users who don't know how this works.
Con: URL may change and make the then-outdated comment extra confusing.
@rtyler WDYT?
=> Add comments directing people to actual changelog entries

content/_data/changelogs/lts.yml, content/_data/changelogs/weekly.yml, content/_partials/changes.html.haml
Previously, if both 'references' and top-level 'issue' and/or 'pull'
were set, both were displayed in independent sets of parentheses.
Now, if 'references' is defined, everything in it is shown and nothing
else. Only if 'references' doesn't exist, a top-level 'issue' is shown
and only if neither exists will a top-level 'pull' be shown.
----
This has been slightly weird for a while, now it's cleaned up (well, mostly -- cleaner would be to wrap all in references, but for now I still favor the shorter top-level `pull`/`issue` elements for the 90% case).
Now with more flexibility: There's both an issue and a PR, but for some reason we only want to show the latter? Just do the following, as now `references` take precedence over other top-level elements if both exist:
issue: 12345
references: …
=> Clean up how 'references' work in the changelog.

content/security/advisory/2017-04-10.adoc
ref: https://github.com/jenkinsci/matrix-auth-plugin/blob/master/src/main/java/hudson/security/GlobalMatrixAuthorizationStrategy.java#L464
There is no reason to have two dots in `hudson.security.GlobalMatrixAuthorizationStrategy..dangerousPermissions`
please review @daniel-beck
=> Fix property GlobalMatrixAuthorizationStrategy.dangerousPermissions

content/_layouts/developer.html.haml
**ON HOLD** Currently there's an issue with the content-type that the report files are served with.
Output generated by https://github.com/jenkins-infra/core-taglibs-report-generator
=> [INFRA-897] Add link to core taglib documentation

content/_partials/rss-changes.xml.haml, content/changelog-stable/rss.xml.haml, content/changelog/rss.xml.haml
Turns out https://validator.w3.org/feed/ exists, and leaving off `isPermaLink` for the `guid` was an error (I read the spec wrong).
The other (the feed URL) is improving compatibility per https://validator.w3.org/feed/docs/warning/MissingAtomSelfLink.html
=> Minor fixes and improvements to changelog feed output

content/_partials/rss-changes.xml.haml, content/changelog-stable/rss.xml.haml, content/changelog/rss.xml.haml
Because https://jenkins.io/changelog/rss.xml should not yet show 2.64.
Real diff: https://github.com/jenkins-infra/jenkins.io/pull/926/files?w=1
=> Do not show unreleased changes in RSS feed

content/blog/2017/04/2017-04-20-secure-jenkins-on-azure.adoc
I've replaced the links to the Azure QuickStart templates with a link to the Azure Marketplace. That offer will be kept up to date and it's much simpler to use and deploy.
=> Update the 'Securing a Jenkins instance on Azure' blog post

.gitignore, content/_layouts/developer.html.haml, scripts/fetch-external-resources
Using a temporary URL while waiting for https://ci.jenkins.io/job/Infra/job/backend-extension-indexer/job/master/1/ to finish. Then, URL will be `https://ci.jenkins.io/job/Infra/job/backend-extension-indexer/job/master/lastSuccessfulBuild/artifact/*.adoc/*zip*/extension-indexer.zip`
Had to add `mkdirs_p` because Git cannot do empty directories, but missing directory failed the build.
Replaces https://wiki.jenkins-ci.org/display/JENKINS/Extension+points
=> Add generated extensions index

content/_layouts/developer.html.haml, content/_layouts/documentation.html.haml, content/doc/developer/_book.yml, content/doc/developer/blueocean-plugin-development/index.adoc, content/doc/developer/building/index.adoc, content/doc/developer/development-environment/index.adoc, content/doc/developer/javadoc.html.haml, content/doc/developer/plugin-development/index.adoc
- Restructure left navigation bar for developer docs
- add new page for links to Javadoc
- Move Blue Ocean doc up in the list to plugin dev.
---
> ![screen shot](https://user-images.githubusercontent.com/1831569/27003204-968db098-4df2-11e7-8daf-930d9482ad90.png)
=> Minor improvements to developer docs structure

content/blog/2017/02/2017-02-01-pipeline-scalability-best-practice.adoc
As opposed to the kind of hacky native groovy libraries people were sometimes using, this reflects the proper shared libraries feature, which *does* get CPS-transformed.
=> Amend pipeline scalability guidance to reflect the more common shared libraries

content/_data/events/shenzhen_jam_june2017.adoc
There is a "Shenzen" event file as well.  And my osx file system is crying because it doesn't know which one is real.
=> Remove out of date event

content/doc/book/pipeline/syntax.adoc
[JENKINS-42693](https://issues.jenkins-ci.org/browse/JENKINS-42693) - [PR 136](https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/136)
Planned for next Declarative release (`1.2` if there isn't a `1.1.x` release beforehand).
I'm not sure about the formatting - how do we want to handle/display
multiple options for agent types?
cc @rtyler @bitwiseman
=> [JENKINS-42693] Add 'additionalBuildArgs' dockerfile option

content/blog/2016/2016-04-07-pipeline-for-runs-on-hardware.adoc, content/blog/2016/2016-06-16-parallel-test-executor-plugin.adoc, content/doc/book/pipeline-as-code.adoc, content/pipeline/getting-started-pipelines.adoc
The junit and archiveArtifacts steps have human friendly names now.  We should show those, not the `step([])` syntax.
@oleg-nenashev
=> Updated junit and archiveArtifact step examples

content/_data/changelogs/lts.yml, content/_data/changelogs/weekly.yml, content/changelog-stable/index.html.haml, content/changelog/index.html.haml, content/doc/upgrade-guide/2.60.adoc, content/doc/upgrade-guide/2.60/windows.adoc
Only the changelog for now, upgrade guide will follow.
> ![screen shot](https://user-images.githubusercontent.com/1831569/27007086-be09bfdc-4e46-11e7-94dc-add2104032de.png)
Also add the `banner` entry to support highlighting very notable changes, such as the Java 8 requirement here, mirroring https://jenkins.io/changelog-stable/#v1.625.1
---
@oleg-nenashev @olivergondza 
PTAL @jglick Is the advice on SSH Slaves 1.17 (https://github.com/jenkinsci/ssh-slaves-plugin/pull/43) and Pipeline: Groovy still correct?
=> Add changelog for 2.60.1

content/_data/changelogs/lts.yml
Addressing a comment by @jglick late.
=> Mention that SSH Slaves 1.20 is recommended in Java 8 note

content/doc/book/pipeline/syntax.adoc
Added some documentation for `skipStagesAfterUnstable` ([JENKINS-42039](https://issues.jenkins-ci.org/browse/JENKINS-42039)), which was implemented in [this PR](https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/115).
=> Added documentation for skipStagesAfterUnstable (JENKINS-42039)

content/doc/book/pipeline/syntax.adoc
This makes the main sections and directives appear in the toc
for easier searching.
=> Set pipeline syntax toc to depth 3

content/_ext/pipeline.rb
Some feed readers have difficulty coping with a big giant atom feed, so this
should be a good middle-ground
Fixes WEBSITE-369
=> Lower the number of items in the atom feed to 20

CONTRIBUTING.adoc
Otherwise you end up with generated site with lots of js files missing and looking not very good. Observed that while making changes. Tested this on a fresh clone of the repo.
See this IRC log also:
```
18:17 <vkotovv> danielbeck: one more stupid question: looks like JS is not working for my debug server, take a look here: http://imgur.com/a/bI91o
18:17 <vkotovv> why is that so?
18:19 <danielbeck> vkotovv no idea, similar problem here. I think it started when we merged a "modern web framework" change a month or so ago
18:19 <danielbeck> vkotovv could be related to the active profile and which is the site.base_url, but maybe not
18:19 <vkotovv> too bad, cant test some changes..
18:20 <danielbeck> vkotovv `./gradlew cC`, then `(cd build/_site && python -m SimpleHTTPServer 4242)` -- takes …
```
=> Added prepareJavaScripts gradle task instructions to contribution guide

content/blog/2017/07/2017-07-13-speaker-blog-rosetta-stone.adoc
We need to use double backticks in this case as per guide: http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#formatted-text.
Otherwise it breaks further formatting.
=> Fix text formatting in Rosetta Stone's blog post

content/_layouts/developerguide.html.haml
The main navigation to the developer no longer goes through the sidebar with chapters, so make the guides appear separate from that.
=> Make the How-To Guides look like they're not part of the book

content/doc/developer/tutorial/extend.adoc, content/doc/developer/tutorial/run.adoc
* Fix Java syntax error related to getName
* Consistently use the "side panel" spelling
* Keep the `xmlns:st` in the first Jelly snippet as it's needed later
* Rephrase to indicate Jenkins startup takes a bit of time and include console output that shows it's done
* Add trailing slash when mentioning the 'work' directory name
=> Tutorial fixes

content/blog/2017/07/2017-07-13-speaker-blog-rosetta-stone.adoc
Follow-up to #994. For some reason, double backtick syntax did not work. Need to test such cases before creating PRs. I've tested this one now.
Not sure why double backtick syntax is not working. Maybe asciidoctor version is different? Some more info:
- https://github.com/asciidoctor/asciidoctor/issues/714
- https://github.com/asciidoctor/asciidoctor/issues/718
=> Again fixing monospace formatting in Rosetta Stone blog post

content/blog/2017/07/2017-07-17-speaker-blog-care.adoc
=> Fixed formatting in Care.com guest post

content/download/index.html.haml
Finally, there is a recipe for pre-packaged support to install Jenkins Weeklies in OpenIndiana Hipster. Link to the distribution's package repository details from the Download page.
=> Link to OpenIndiana in Weekly download list

content/download/index.html.haml
Also try to fix the different-looking font for the "gear icon" text.
Follows up on #1027 and #1029.
=> downloads: Rephrase 3rd-party gear tooltip

content/blog/2017/07/2017-07-27-standardizing-builds-with-shared-libraries.adoc
=> Fixed a typo in 2017-07-27-standardizing-builds-with-shared-libraries blog post

content/doc/index.adoc
jenkins >=2.60.1 requires java 8 (on both master and slaves)
=> jenkins now requires java 8

content/doc/book/pipeline/shared-libraries.adoc
[JENKINS-45828](https://issues.jenkins-ci.org/browse/JENKINS-45828)
This is already clear for things under `src`, but it's not made clear
that this is needed for an explicit class declaration in `vars` as well.
=> [JENKINS-45828] Clarify that steps/this needs to be passed to classes

content/doc/book/managing/script-approval.adoc
Untested, because Docker.
Referring to this section in the sidebar of the plugin page:
> ![screen shot](https://user-images.githubusercontent.com/1831569/29126099-bef2b074-7d1d-11e7-9de1-7aa9a88bf9c7.png)
=> Rephrase warning to reference plugin page instead

content/doc/index.adoc
I follow the instruction in "Guided Tour",
However, `java -jar jenkins.war` cause following error, because another application was binding 8080 port.
```
8 12, 2017 2:40:42 午後 org.eclipse.jetty.util.log.JavaUtilLog warn
警告: FAILED ServerConnector@5778826f{HTTP/1.1}{0.0.0.0:8080}: java.net.BindException: アドレスは既に使用中です
java.net.BindException: アドレスは既に使用中です
```
If we have `--httpPort=8080` explicitly in the instruction, user can quickly reach the solution of using another port.
=> specify port option explicitly

content/_data/changelogs/weekly.yml
We're two days late with the release due to https://github.com/jenkinsci/jenkins/pull/2982
Also an end of sentence period was missing
=> Update 2.74 changelog

content/doc/book/pipeline/development.adoc
Relative links to other documents require a trailing #, otherwise it becomes an anchor link.
=> fixed relative links on pipeline/development

content/doc/book/pipeline/syntax.adoc
This is fairly inconsistent with other option examples, but the usage isn't extremely clear except through the snippet generator. It would be nice to have `enableIndexTriggers()` and `disableIndexTriggers()`, but not sure if there's a clean way to do that through DataBoundConstructor (and obviously out of scope of this).
=> Add overrideIndexTriggers to declarative options

content/doc/upgrade-guide/2.73.adoc
I have added the Work Directory section as we discussed with @daniel-beck yesterday
@reviewbybees @daniel-beck
=> [JENKINS-44108] - Mention Work Directories in Jenkins 2.73.1 upgrade guide

content/doc/book/pipeline/docker.adoc
When I try example in
https://jenkins.io/doc/book/pipeline/docker/#running-sidecar-containers
--link fails since mysql:5 instance exit immediately without envionment variable
MYSQL_ROOT_PASSWORD, MYSQL_ALLOW_EMPTY_PASSWORD or
MYSQL_RANDOM_ROOT_PASSWORD.
It took me a while to solve the error, and I thought it is more convenient if there is
a working example.
Thanks,
=> fix example to make sidecar instance persistent within build

content/_layouts/frame.html.haml
OpenGraph spec indicated og:url is the canonical URL : http://ogp.me/ns/ogp.me.ttl
Canonical URL RFC specify a relative IRI may be used http://www.rfcreader.com/#rfc6596_line70
However, use of absolute absolute URL is recommended (to avoid multiple domain issues) : 
* https://support.google.com/webmasters/answer/139066?hl=en
* https://yoast.com/rel-canonical/
=> Use absolute URL for the OpenGraph canonical URL

content/doc/pipeline/tour/post.adoc
With the old example code a compilation error occurred. Something like `unexpected token catch`
=> Fix scripted example for post by moving catch+finally next to try

content/doc/upgrade-guide/2.73.adoc
The Jetty changelog is the worst. Still linking to it though. Because I hate our users.
=> [JENKINS-46968] Add note on dropped TLS <1.2 support

scripts/docker-env, scripts/groovy, scripts/node, scripts/ruby
While still supporting o.g. installations.
Closes #1129
=> Support fancier bind mounts on later versions of docker

content/doc/book/pipeline/shared-libraries.adoc, content/doc/book/pipeline/syntax.adoc
[JENKINS-41334](https://issues.jenkins-ci.org/browse/JENKINS-41334)
https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/152 has been merged, albeit not yet released, so here's a first draft of documentation for parallel stages.
=> [JENKINS-41334] Add parallel stages documentation

content/doc/book/pipeline/syntax.adoc
[JENKINS-47106](https://issues.jenkins-ci.org/browse/JENKINS-47106)
Declarative PR introducing this is https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/199. This change will be in Declarative 1.2.1, which will probably be released as soon as that is merged.
=> [JENKINS-47106] Add docs for alwaysDoDockerPull option

content/redirect/csrf-protection.adoc
It is required for the help message in [JENKINS-47372](https://issues.jenkins-ci.org/browse/JENKINS-47372). Downstream PR is underway.
@wadeck @daniel-beck @reviewbybees
=> [JENKINS-47372] - Add CSRF Protection Page redirect

content/doc/book/managing/cli.adoc
See [JENKINS-47279](https://issues.jenkins-ci.org/browse/JENKINS-47279).
I've updated the relevant [wiki article](https://wiki.jenkins.io/display/JENKINS/Running+Jenkins+behind+Apache#RunningJenkinsbehindApache-ProxyingCLIcommandsusingtheHTTP(S)transportwithJenkins>=2.54) with this information, but @jglick mentioned that it would be a good idea to add a warning to the documentation as well.  
@reviewbybees
=> [JENKINS-47279] Add warning for HTTP mode CLI with Apache reverse proxies

content/blog/2017/10/2017-10-06-hacktoberfest.adoc
The blog currently says 'fore', this seems like a typo which should be 'for'
=> Fix 'For' typo in Hacktoberfest Blog Post

scripts/docker-env
#1142 did not work at all for me.
First of all, it seemed to be backwards. I am guessing you meant to use this new flag when you _are_ using Docker 17.*. I am using 1.12.6 and so cannot use it.
Second, the regexp match did not work for me in Bash 4.4.7 unless I deleted the double quotes. As of Bash 3 they are said to be unnecessary. Seems like some metacharacters gets disabled when you quote the regexp??
Also the matches are unanchored, so the trailing `.*` does nothing.
@reviewbybees
=> Fixing docker-env

content/_data/events/Toulouse_jam_june2017.adoc, content/_partials/events.html.haml, content/events.html.haml
@rtyler @daniel-beck 
The previously when an event had a bad header it would produce pages of errors.
With this change the error output is reduced to one page and the broken file is named:
```
While processing file /Users/bitwiseman/github/infra/jenkins.io/content/events.html.haml
An error occurred: No `date` specified: albuquerque-jam-nov16
/Users/bitwiseman/github/infra/jenkins.io/content/events.html.haml:64:in `block (2 levels) in singleton class'
/Users/bitwiseman/github/infra/jenkins.io/content/events.html.haml:62:in `each'
/Users/bitwiseman/github/infra/jenkins.io/content/events.html.haml:62:in `block in singleton class'
...
```
=> Added better error reporting in events

content/css/jenkins.css, content/doc/tutorials/using-jenkins-to-build-a-java-maven-project.adoc
* Essentially, add [.boxshadow] above an image reference from now on to generate a box-shadow around it.
* I tested out this new CSS feature on the already-published 'Using Jenkins to build a Java/Maven' project.
* Also, tidied up some Asciidoc syntax in the tutorial.
See https://issues.jenkins-ci.org/browse/WEBSITE-416 for more information.
=> [WEBSITE-416] Add 'boxshadow' to 'jenkins.css' + implement in published tutorial.

content/doc/book/pipeline/docker.adoc
I'm using mysql sidecar container to run test.
I took some time to find out the need to wait for the service startup.
I think it would be helpful if the example include it.
Thanks,
=> wait for mysql service to start in sidecar container example

content/_layouts/documentation.html.haml, content/_layouts/pipelinesteps.html.haml, content/doc/pipeline/steps/index.html.haml
The link to the Pipeline Reference page (from the Pipeline Syntax page) has existed for a while. However, these pages should have reciprocal links.
=> Add reciprocal link between Pipeline Syntax and Pipeline Reference pages

content/doc/book/pipeline/syntax.adoc
Only reference guide for this is various stack overflow posts and the (no longer maintained) pipeline model definition [wiki](https://github.com/jenkinsci/pipeline-model-definition-plugin/wiki/Trigger-runs#other-available-triggers).
=> Add documentation for upstream trigger syntax

content/doc/developer/plugin-development/pipeline-integration.adoc
origin: https://github.com/jenkinsci/pipeline-plugin/blob/master/DEVGUIDE.md
It should simplify new plugin developers path and also simplify reading experience as of adoc provides much more for structured text
If it will be merged - cross ref should be posted on old place to save some old links for some time
=> move pipeline developer guide from repo to adoc and site

content/doc/book/pipeline/syntax.adoc
* To reduce wording maintenance when more triggers are added.
* This pull request stems from a comment I wrote in [PR 1203](https://github.com/jenkins-infra/jenkins.io/pull/1203).
=> Minor wording improvement on the Pipeline Syntax page.

CONTRIBUTING.adoc
Following on from @bitwiseman 's comment on [PR 1191](https://github.com/jenkins-infra/jenkins.io/pull/1191), I reworded the **Guided Tour** section for consistency.
(While the commits below say that the rhetoric has been removed, it's actually just been changed/improved.)
=> Contributing guidelines minor tweak

content/doc/book/managing/cli.adoc
In order to document a bit the new authentication part in the CLI, three new troubleshooting cases were added.
See [JENKINS-27026](https://issues.jenkins-ci.org/browse/JENKINS-27026).
@reviewbybees @jglick
=> [JENKINS-27026] Add paragraphs about the CLI authentication

content/doc/book/pipeline/syntax.adoc
As indicated on https://twitter.com/rompic/status/929752635493756928, the example cron expressions were:
* H 4/* 0 0 1-5
which is invalid syntax. Hence, this is changed to:
* H */4 * * 1-5
which is valid syntax. Read more about this here https://help.ubuntu.com/community/CronHowto.
=> Fix cron examples.

content/doc/tutorials/building-a-java-app-with-maven.adoc, content/doc/tutorials/building-a-node-js-and-react-app-with-npm.adoc, content/doc/tutorials/creating-a-pipeline-in-blue-ocean.adoc
* Also, expand wrap-up section to correlate outcomes of this tutorial
with the original Node.js and React one.
Essentially:
* The back arrow does not need to be used when it takes you back to the main Pipeline editor (i.e. not the Pipeline stage editor area). Therefore, the optional bits are now marked as such.
* Steps were missing to click the relevant build rows from the main Blue Ocean UI (i.e. to see build details in progress). These steps are now indicated - since their omission may confuse newbies to Blue Ocean.
* In the Wrapping Up section, I explained the difference between the placement of the 'environment' directive in this tutorial compared to the earlier Node.js and React one. I left it with a rhetorical question since readers should be in a position to work out how to make …
=> Add important clarifications throughout the 'Create Pipeline in Blue Ocean' tutorial.

content/doc/tutorials/building-a-java-app-with-maven.adoc, content/doc/tutorials/building-a-node-js-and-react-app-with-npm.adoc, content/doc/tutorials/creating-a-pipeline-in-blue-ocean.adoc
In the meantime, the old URLs will be redirected correctly - thanks to GitHub's built in functionality to automatically redirect repositories moved between accounts/organisations.
=> Amend tutorial repository URLs after moving them from 'gilesgas' to 'jenkins-docs'

content/doc/index.adoc, content/doc/tutorials/_run-jenkins-in-docker.adoc, content/doc/tutorials/building-a-java-app-with-maven.adoc, content/doc/tutorials/building-a-multibranch-pipeline-project.adoc, content/doc/tutorials/building-a-node-js-and-react-app-with-npm.adoc, content/doc/tutorials/creating-a-pipeline-in-blue-ocean.adoc
May convert the replicated content into an inclusion if more tutorials crop up with the same content re-used.
See https://issues.jenkins-ci.org/browse/WEBSITE-442 for details.
=> [WEBSITE-442] Rework skipping the 'Run Jenkins in Docker' instructions in tutorials

content/doc/book/pipeline/shared-libraries.adoc
@jglick @rtyler 
From discussion on IRC and testing, it looks like this is the current behavior of `class` declarations. 
Is this correct behavior or should the class declaration automatically instantiate a new global variable?
=> Updated to correctly describe class behavior

content/_data/events/st_petersburg_russia_jam_dec2017.adoc
It is not organized by JAM organizers, but it is fully about Jenkins && orgs participate in it.
CC @MaxArbuckle
=> Add St. Petersburg JUG meetup on Dec 04.

content/doc/book/pipeline/syntax.adoc
This is to make it clearer that the conditions are also applicable to stages too.
=> Clarify post and condition descriptions on the Pipeline Syntax page

Jenkinsfile
Turns out we weren't catching warnings because they were going to the error stream and never being found by grep.
=> Enforce warnings as build failures

content/_data/changelogs/weekly.yml, content/changelog/index.html.haml
First commit's PR build output:
> ![screen shot](https://user-images.githubusercontent.com/1831569/34127305-e7051c60-e43c-11e7-8f4a-47e8c891eb14.png)
=> Add 2.96 changelog even when not being distributed

content/changelog/index.html.haml
This reverts commit ad22772448c9190aafca6df3238657d90d1d4de6.
Apparently I cannot Ruby, so we now have two changelog entries for 2.96 😢
=> Revert "Add 2.96 changelog even when not being distributed"

Jenkinsfile, Makefile, scripts/asciidoctor-pdf, scripts/awestruct
`depends` and `assets` run only when required by file changes.  Using flag files for both. 
Also moved warning filtering from Jenkinsfile to scripts which make calls.  This will result in clearer output when errors occur.
=> More makefile tweaks

content/doc/book/pipeline/syntax.adoc
Some links from the declarative pipeline plugin repository or JIRA: 
* https://github.com/jenkinsci/pipeline-model-definition-plugin/blob/1e1452409af43d15356d6591002317bd8b0c4216/pipeline-model-definition/src/test/resources/fromAlternateDockerfile.groovy
* Auto documentation: https://github.com/jenkinsci/pipeline-model-definition-plugin/blob/7080fce379ced865e73947b6d9e44a46af6b9c03/pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/agent/impl/DockerPipelineFromDockerfile/help-filename.html
=> adding "filename" option on dockerfile + example

content/doc/book/pipeline/shared-libraries.adoc
There is a missing return this in the example for Zot.groovy. Without this, the issue in the issue arises. This clarifies the example to make sure the user knows that `return this` is needed
=> Fix JENKINS-48527

Jenkinsfile
I'm sick of hearing complaints about having to run `make update` in order to
help keep the site's dependencies up to date, so I'm just going to revert this
@bitwiseman
=> Disable the dependency checks

content/doc/tutorials/build-a-python-app-with-pyinstaller.adoc
Whoops! This wouldn't have affected readers running through the tutorial in its entirety, but it would have affected people copying and pasting the last complete Pipeline code towards the end of the page.
=> Add missing 'stage {' to the complete Pipeline code towards end of Python tutorial

content/doc/book/pipeline/shared-libraries.adoc
A recommendation I made in #611. For example, look at https://github.com/cloudbeers/multibranch-demo/pull/22 + https://github.com/cloudbeers/multibranch-demo-lib/commit/335dc32bb9f73ca06b843b426904c6a36c05f438. And lots of Groovy weirdness just disappears when closure scopes go away, as the commit sequence in https://github.com/cloudbeers/multibranch-demo/pull/26 demonstrates.
@reviewbybees esp. @abayer & @raul-arabaolaza
=> Recommend simple Map-based functions rather than the builder pattern

content/doc/book/pipeline/syntax.adoc
[JENKINS-44461](https://issues.jenkins-ci.org/browse/JENKINS-44461)
See https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/232 - this'll be added in Declarative 1.2.6.
=> [JENKINS-44461] Add documentation for new when->beforeAgent field

content/blog/2018/01/2018-01-13-jep-200.adoc
Otherwise developers will likely see a bloodbath of dependencies if they use recent Parent POMs and old cores.
@reviewbybees @jglick
=> [JEP-200] - Suggest running Maven with suppressed enforcer for testing JEP

content/_data/changelogs/weekly.yml
We are getting more regression reports after 2.103, so IMHO it makes sense to keep the banner in this release as well.
@reviewbybees @jglick @daniel-beck
=> Add JEP-200 warning to the 2.103 changelog banner

content/doc/book/pipeline/development.adoc
- added information about Jenkins Editor plugin at https://marketplace.eclipse.org/content/jenkins-editor 
- the plugin is OSS and has Apache 2.0 License and is hosted at https://github.com/de-jcup/eclipse-jenkins-editor
=> Added information about Eclipse Plugin

content/_layouts/advisory.html.haml, content/security/advisory/2018-01-22.adoc, scripts/fetch-external-resources
Some restrictions apply:
* Still needs to be tested with 'no fix available' (implemented but untested), core security updates (half implemented) etc. -- basically every advisory that isn't the latest one, which I developped this with. Can be done as needed, or we just don't convert those advisories to 'data'.
* ~~PR build should fail because of an unnecessary escape sequence in the new JSON file (`\/` around character \~565700 for an 'experimental' note that shouldn't be there in the first place).~~
Future improvements:
* The update center serves 'dirty' display names ("Jenkins Foo Plug-in" instead of "Foo"), so sorting even by display name is a mess. Either needs to add support for cleaning display names in the update site, or just bite the bullet and do it in update center so it doesn't …
=> Use metadata for most security advisory sections

content/_data/changelogs/weekly.yml
~~Might not be complete yet.~~
Missed https://github.com/jenkinsci/jenkins/pull/3272 because https://github.com/jenkinsci/jenkins/compare/jenkins-2.104...master doesn't include it when searching for ` (#` *or* `pull request #`.
One of the reasons I hate unnecessary squash merges.
=> Add changelog for 2.105

content/doc/book/pipeline/shared-libraries.adoc
The typo is for a folder name (vars) that must be named precisely for a shared pipeline library to be loaded correctly.
I happened to have been using this section of the documentation when creating my shared library.  As a result, my library would load because I was using the incorrect folder name listed here.
=> Fixed typo in folder name (shared-libraries.adoc).

content/_layouts/developerbook.html.haml
I'm pretty sure it wasn't necessary before, but it's in #571
and so apparently has always been in there.
=> Somehow this class is needed to make active links bold.

content/chat.adoc
[INFRA-1493](https://issues.jenkins-ci.org/browse/INFRA-1493)
As discovered during the Jenkins contributor meetup today, the current status could prevent people from logging in so added a quick explanation to help people know how to still access `#jenkins` under spam attacks.
Rendered using `make run`:
@orrc @daniel-beck @rsandell
=> [INFRA-1493] Add more explanation about IRC and the +r to help people rejected with non-registered nicks

content/doc/developer/testing/index.adoc
_Live from the post-FOSDEM hackathon in Brussels…_
Trying to move old testing documentation from the wiki to the website, expand the content, bring it up to date, and include the content from @jglick's sessions at the Jenkins World hackhouse.
I've tried to go into a bit more depth with the setup instructions and examples, along with Pipeline examples, and tested that the various code samples work as expected.
If this looks reasonable, hopefully we can merge this soon-ish, to at least have _something_ on the website — even if there are lots of empty sections, like most documentation — and iterate from there.
Feel free to comment, and suggest new sections to be added.
Unfortunately, it doesn't look like I can mention `@jenkinsci/code-reviewers` here.
=> WIP: Move testing documentation to jenkins.io

content/security/advisory/2018-02-05.adoc
Also add link anchors that are plugin IDs
---
Output is basically the same except for very minor formatting changes, and that some of the plugins have the *Plugin* or *Plug-In* suffix due to uncontrolled display name messes.
=> Change 2018-02-05 advisory into new format with metadata

content/_ext/activenav.rb, content/_ext/atom.xml.haml, content/_layouts/advisory.html.haml, content/_layouts/frame.html.haml, content/_layouts/pipelinesteps.html.haml, content/_layouts/post.html.haml, content/_partials/author.html.haml, content/_partials/blogcardlist.html.haml, content/changelog-stable/rss.xml.haml, content/changelog/rss.xml.haml, content/doc/developer/book.html.haml, content/doc/developer/guides.html.haml, content/index.html.haml, content/node/index.html.haml, content/participate/index.html.haml, content/security/advisories.html.haml
This change runs most of the links generated by haml through the expand link method to create absolute paths.  This will make the demo sites much more useful.  
Example:  
Click on any blog link on this:
http://bitwiseman.github.io/jenkins.io/master/node/
vs
Click on any blog link on this:
http://bitwiseman.github.io/jenkins.io/expand_link/node/
NOTE: in the site output this changes links to longer form, `/node` to `http://bitwiseman.github.io/jenkins.io/expand_link/node`
=> Use expand link instead of absolute paths

CONTRIBUTING.adoc, Makefile, scripts/user-site-deploy.sh
Instead of nuking the working directory every publish,
create a worktree under build/_gh-pages.
This stops strange editor behavior and allows users
to publish changes without committing them.
=> Improve user-site behavior

content/doc/book/pipeline/syntax.adoc
A backtick without spaces is not treated as a monospace.
Previous output:
=> Fix backtick syntax

content/_layouts/advisory.html.haml, content/security/advisory/2017-11-08.adoc, content/security/advisory/2018-02-05.adoc
Implement on 2017-11-08 advisory.
Unrelated change:
Add link to blog post on 2018-02-05
=> Add support for data-based 'core' security advisories

content/_layouts/advisory.html.haml, content/security/advisory/2017-11-08.adoc
Implement for 2017-11-08 advisory.
2018-01-22 and 2018-02-05 show that there's still support for
descriptions in content.
---
Not sure yet whether this is great long term (and writing it will be annoying due to data not getting updated live), but it gives greater flexibility in formatting advisories.
=> Add support for issue title and description in data

content/security/advisories.html.haml
**Work in progress**
Sort of downstream from https://github.com/jenkins-infra/backend-update-center2/pull/187 (typically too complex/long display names otherwise)
Also sort of downstream from https://github.com/jenkins-infra/jenkins.io/pull/1382 as otherwise we cannot include core security updates adequately.
Screen shot:
> ![screen shot](https://user-images.githubusercontent.com/1831569/36080944-4821fb7c-0f98-11e8-8edd-59690c3f36e0.png)
@oleg-nenashev @Wadeck @orrc @batmat WDYT?
=> Additional details on the advisories index page

content/_layouts/advisory.html.haml
Otherwise, the page data (well, `page.issues`) is empty after loading the advisory once.
=> Don't modify page.issues when loading an advisory

content/_layouts/advisory.html.haml, content/security/advisories.html.haml
Also adds *Plugin* suffix on the advisory page. This is to prevent confusion in the current situation that calls e.g. "JUnit" a "Jenkins deliverable".
---
Tested locally with a slightly modified Feb 5 advisory:
> ![screen shot](https://user-images.githubusercontent.com/1831569/36233832-3506c32c-11e8-11e8-83bb-38595e016993.png)
> ![screen shot](https://user-images.githubusercontent.com/1831569/36233826-2a8c59fc-11e8-11e8-9b13-ed9ac3631bf6.png)
=> Add support for plugins not currently published

content/doc/book/pipeline/docker.adoc
This adds some documentation pertaining to the second argument that `docker.build()` accepts.
=> Adding .build() examples to explain passing arguments

content/doc/index.adoc
This will allow images to render correctly at the link's target subsection of the Installing Jenkins page.
=> Correct link.

content/projects/gsoc/gsoc2018-project-ideas.adoc
It wasn't obvious for some readers that Jenkins Configuration as Code is a plugin. It is mentioned in description but I updated also the section title
=> Clarify JCasC as a Plugin in a section title

content/_layouts/advisory.html.haml
> ![screen shot](https://user-images.githubusercontent.com/1831569/36439981-c8adba88-166e-11e8-90c8-6eaf090abebc.png)
I don't really like how this looks, but it gets the job done. Not sure whether it's useful to have a full 'security section only' breadcrumb navigation, e.g.
> [Security](https://jenkins.io/security) » Advisories
(for the list)
and
> [Security](https://jenkins.io/security) » [Advisories](https://jenkins.io/security/advisories) » Security Advisory 2018-02-14
(for each advisory)
=> Add link back to advisories index

content/_layouts/advisory.html.haml
=> When not specifying a last affected version, all are.

content/_layouts/advisory.html.haml, content/security/advisories.html.haml
Otherwise https://jenkins.io/security/advisory/2018-02-26/ looks weird.
=> Use title of depublished plugin if available

content/security/advisory/2018-02-26.adoc
I don't understand why, but the monospace formatting didn't get applied with `+`.
=> Fix code formatting in advisory

content/_data/events/2018-03-20-dallas.adoc
Just noticed it while working on #1433 
@jenkins-infra/copy-editors @abayer
=> Fix typo in the March’s DFW JAM announcement

content/doc/pipeline/tour/hello-world.adoc
Change lines like `agent { docker 'node:6.3' }` to lines like `agent { docker { image 'node:6.3' } }`.
=> corrects syntax of agent sections

content/redirect/serialization-of-anonymous-classes.adoc
Placeholder for messages produced by https://github.com/jenkinsci/remoting/pull/259, as suggested in https://github.com/jenkinsci/jenkins/pull/3332#issuecomment-371144549. I may change the link target to a wiki page or a blog post or something later—just wanted a redirect in place so that the code PRs would have something better to point to.
@reviewbybees @oleg-nenashev @daniel-beck @rysteboe
=> [JENKINS-49994] Set up a redirect for messages about serialization of anonymous classes

content/_data/changelogs/lts.yml, content/doc/upgrade-guide/2.107.adoc
I added *all* "developer" entries, might be a bit much. I plan to cull the minor ones. `Jenkins#getInstance` stays though, possibly others.
> ![changelog](https://user-images.githubusercontent.com/1831569/36984763-efc9add0-2095-11e8-955b-486694df5d0b.png)
---
Please see the sources for some items I wasn't sure are notable enough. Feedback would be appreciated.
> ![upgrade guide](https://user-images.githubusercontent.com/1831569/36984773-f3b8e9f6-2095-11e8-8968-1744e9ae6353.png)
=> Add upgrade guide and changelog for 2.107.1

content/redirect/cli.adoc
The [wiki page](https://wiki.jenkins.io/display/JENKINS/Jenkins+CLI) actually says
> More up-to-date information is available in the Jenkins documentation at https://jenkins.io/doc/book/managing/cli/
so why not go there directly?
Shown from `/cli/` in the product:
```html
<p>You can access various features in Jenkins through a command-line tool. See <a href="https://jenkins.io/redirect/cli">the documentation</a> for more details of this feature.To get started, download <a href="/jnlpJars/jenkins-cli.jar">jenkins-cli.jar</a>, and run it as follows:</p>
```
@reviewbybees
=> Updated CLI redirect

content/doc/upgrade-guide/2.107.adoc
Follow-up to @rtyler's request at the governance meeting.  I have reviewed the recently reported issues, and I do not see new&&confirmed regressions excepting the JEP-200 plugin fallout. So I just added other regression-alike issues which should be ignored + a paragraph about JEP-200
@daniel-beck
=> Update the list of known issues in 2.107.1

content/redirect/serialization-of-anonymous-classes.adoc
Amending #1439 with a [wiki page](https://wiki.jenkins.io/display/JENKINS/Serialization+of+anonymous+classes) I created with advice. CC @daniel-beck @oleg-nenashev
=> Better redirect target for serialization-of-anonymous-classes

content/projects/gsoc.adoc
I will announce it in the ML later.
IMHO there is no need to add them to the events list
=> [GSoC 2018] - Add extra office hours timeslots to the list

content/security/advisory/2018-03-26.adoc
Plugins that have been removed from publication don't get automatic titles, so provide them explicitly.
=> Forgot to put alt titles for depublished plugins

content/doc/book/pipeline/syntax.adoc
[JENKINS-49226](https://issues.jenkins-ci.org/browse/JENKINS-49226)
Downstream of https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/243
Not ready to merge until Declarative 1.2.8 is released.
=> [JENKINS-49226] Documentation for new equals condition

content/doc/book/pipeline/syntax.adoc
[JENKINS-49558](https://issues.jenkins-ci.org/browse/JENKINS-49558)
Downstream of https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/246
Not released yet, so don't merge yet. =)
=> [JENKINS-49558] Add doc for newContainerPerStage Declarative option

content/doc/book/pipeline/syntax.adoc
[JENKINS-41060](https://issues.jenkins-ci.org/browse/JENKINS-41060)
Downstream of https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/248
Not merged or released yet, so don't merge here 'til I get rid of the work in progress label.
=> [JENKINS-41060] Add new fixed and regression post conditions

content/doc/book/pipeline/getting-started.adoc, content/doc/book/pipeline/syntax.adoc
[JENKINS-49893](https://issues.jenkins-ci.org/browse/JENKINS-49893)
Downstream of https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/250
Planned for Declarative 1.2.8, coming real soon now.
=> [JENKINS-49893] Declarative Directive Generator docs

content/doc/book/pipeline/syntax.adoc
[JENKINS-48523](https://issues.jenkins-ci.org/browse/JENKINS-48523)
`tag` and `changeRequest`.
Also adding documentation for `changeset` and `changelog` that was missing.
Downstream of jenkinsci/pipeline-model-definition-plugin#240
Not ready to merge until Declarative 1.2.8 is released.
=> [JENKINS-48523] Documentation for new when conditions 

scripts/crushinator.sh
@rtyler @oleg-nenashev 
Crushinator script generates this output: 
```
$ ./scripts/crushinator.sh "content/images/post-images/Screen Shot 2016-11-08 at 4.23.34 PM.png"
./scripts/crushinator.sh: line 6: [: too many arguments
Could not find file: content/images/post-images/Screen
Could not find file: Shot
Could not find file: 2016-11-09
Could not find file: at
Could not find file: 3.36.27
Could not find file: PM.png
Could not find file: content/images/post-images/Screen
Could not find file: Shot
Could not find file: 2016-11-09
Could not find file: at
Could not find file: 3.36.27
Could not find file: PM.png_pngcrush_201804091329
CPU time decode 0.000000, encode 0.000000, other 0.000460, total 0.000460 sec
usage: mv [-f | -i | -n] [-v] source target
mv [-f | -i | -n] [-v] source ... directory …
```
=> Make crushinate safe for files with spaces

content/security/advisory/2018-01-22.adoc
I messed up the migration in https://github.com/jenkins-infra/jenkins.io/commit/37a0b47b644d76ee32e8458ac0935e9731317c8b and introduced mistakes:
- Metadata for SECURITY-675 and SECUIRTY-695 were switched (severity is the only one shown).
- Link targets to CVSS vectors for multiple issues were wrong, but labels were correct.
=> Fix data errors introduced in format migration

content/doc/book/pipeline/jenkinsfile.adoc
In the Jenkinsfile documentation the word `essense` should be spelled `essence`.
=> Typo: replace essense with essence.

content/doc/book/architecting-for-scale.adoc
(Partly) documenting the new behaviour introduced in https://github.com/jenkinsci/jenkins/pull/3364 [as requested by @daniel-beck](https://github.com/jenkinsci/jenkins/pull/3364#issuecomment-383288998)
_NOT documentating the other workspaces location customization switch on purpose: people should generally not have workspaces on `master` anyway since this would mean builds are run there._
https://issues.jenkins-ci.org/browse/JENKINS-50164
=> [JENKINS-50164] Document builds location configuration

content/_data/changelogs/weekly.yml
The test for this change fails for KK, so to unblock the release he's going to release the previous commit.
=> Remove JENKINS-9104 fix from release to unblock it

content/blog/2018/03/2018-03-15-jep-200-lts.adoc
Follow-up to https://groups.google.com/forum/#!topic/jenkinsci-dev/AUdrTLmezgU . There was no votes against the change, so I propose to go forward and update the docs.
Also Wiki update: https://wiki.jenkins.io/pages/viewpreviousversions.action?pageId=138446089
@jglick @reviewbybees
=> [JEP-200] - Update maintenance guidelines to reflect the May 01 change

content/doc/pipeline/tour/hello-world.adoc
The `link:` addition is required, otherwise AsciiDoctor doesn't know that this
supposed to be rendered as a marked up link in the footnotes.
Let this serve as a warning to the otherwise lazy no-link:-adding asciidoc
authors out there :smiling_imp:
Fixes WEBSITE-482
=> Tidy up this footnote

content/projects/gsoc/2018/code-coverage-api-plugin.adoc
Adding chat channel and repository address in Code Coverage API Plugin project page.
=> [GSoC 2018] - update Code Coverage API Plugin page

content/security/advisories.html.haml, content/security/advisory/2018-03-26.adoc
- Don't list plugins twice if they have different properties
- Fix wrong word choice in 2018-03-26 advisory
=> Minor cleanup in security advisories

content/blog/2018/05/2018-05-09-security-advisory.adoc
Clarify that the security fix is unreleased, not the plugin.
=> Wording for today's security blog post

content/_data/changelogs/weekly.yml
PR builds don't run reliably, so we broke the site build in https://github.com/jenkins-infra/jenkins.io/pull/1569 😢
=> Fix changelog for 2.125

content/doc/book/pipeline/syntax.adoc
The current "link:" syntax results in a 404. Updated the link to use AsciiDoc cross-reference syntax, per https://asciidoctor.org/docs/asciidoc-writers-guide/#cross-references.
=> Fix xref to Declarative Directive Generator

content/_data/changelogs/lts.yml, content/doc/upgrade-guide/2.121.adoc
Untested as `make run` doesn't work for me right now.
=> Add changelog and upgrade guide for 2.121.1

content/_data/events/2018-06-18-java10-hackathon.adoc
https://issues.jenkins-ci.org/browse/WEBSITE-493
Had to play a bit with text, didn't look well otherwise. IIUC there is also no support of multi-day events, which may be a problem here since people may join at any day.
@jenkins-infra/copy-editors @bitwiseman
=> [WEBSITE-493] - Add Java 10+ hackathon to Events

content/blog/2018/06/2018-06-08-jenkins-java10-hackathon.adoc, content/blog/2018/06/2018-06-17-running-jenkins-with-java10-11.adoc
This article explains how to run Jenkins with Java 10 and 11 using Docker images and WAR files.
It also lists known issues and provides contributor guidelines.
Would be great to merge it soon so that it's available to Java 10 hackathon participants: https://jenkins.io/blog/2018/06/08/jenkins-java10-hackathon/
@jenkins-infra/copy-editors @bitwiseman @MarkEWaite @duemir
=> Add blogpost about Java 10 and 11 experimental support

content/doc/pipeline/tour/getting-started.adoc
There's no longer a "Get Docker" link on the homepage of www.docker.com. But there is on docs.docker.com. Changed link to point to the doc site.
=> Use "docs" site as Docker starting point

content/doc/administration/requirements/java.adoc, content/doc/administration/requirements/web-browsers.adoc, content/doc/book/installing/index.adoc, content/redirect/java-support.adoc
As a part of the Hackathon we decided to make the Java support policy more explicit. Here is a page created by @tracymiranda and me, the structure follows agreements we reached during the discussion on Thursday.
https://issues.jenkins-ci.org/browse/WEBSITE-496
@jenkins-infra/copy-editors @bitwiseman @daniel-beck
=> [WEBSITE-496] - Create Java Requirements and Web Browser compatibility pages

content/security/advisory/2018-06-25.adoc
It's not just in affected/fixed, but also in the list of top. Since there's no dedicated entry, and SECURITY-440 doesn't mention it, its presence is just confusing.
=> Remove confusing mention of Credentials Plugin

content/doc/developer/publishing/_chapter.yml
Has existed for a long time here, just was not listed:
https://jenkins.io/doc/developer/publishing/wiki-page/
=> Add wiki page link to the chapter

content/doc/developer/publishing/source-code-hosting.adoc
> ![screen shot](https://user-images.githubusercontent.com/1831569/41982608-2a0df65a-7a2c-11e8-96a3-01d65b5527d0.png)
(The screenshot still used a local data source, rather than the reports host, but due to CORS I cannot show a live example, or even try it, before this is merged.)
=> Add table showing actual GitHub permissions

content/_data/sigs/platform.adoc, content/_layouts/frame.html.haml, content/_layouts/sig.html.haml, content/_partials/toptoolbar.html.haml, content/sigs/index.html.haml, content/sigs/platform/index.adoc
This page offers a location for SiGs on jenkins.io. See https://github.com/jenkinsci/jep/tree/master/jep/4 . https://github.com/jenkinsci/jep/pull/135 and https://github.com/jenkinsci/jep/pull/136 are used as examples.
The PR is WiP, but ready for initial review:
* "Participate" link is converted to dropdown with beginner guidelines, SIGs and Adopt a plugin
* Draft landing SIG. There is some space reserved for right panel
*Draft pages for Platform and Cloud Native Jenkins SIGs
@tracymiranda @bitwiseman @carlossg @rtyler
=> [JEP-4] - Draft the SIGs list and SIG pages

content/doc/pipeline/tour/tests-and-artifacts.adoc
I would also like to modify the explanation to describe what `fingerprint: true` does on `archiveArtifacts` but I'm not sure myself.
=> Fixing scripted example try-finally blocks

scripts/fetch-external-resources
…since there are apparently some subtle differences in metacharacter escapes.
Prerequisite for https://github.com/jenkins-infra/update-center2/pull/217 to be merged acc. to @daniel-beck. I managed to reproduce the stated error by
```diff
diff --git a/scripts/fetch-external-resources b/scripts/fetch-external-resources
index b4902e5f..21e39f3a 100755
--- a/scripts/fetch-external-resources
+++ b/scripts/fetch-external-resources
@@ -39,7 +39,7 @@ RESOURCES = [
nil
],
[
-    'https://updates.jenkins.io/update-center.actual.json',
+    'https://ci.jenkins.io/job/Infra/job/update-center2/job/PR-217/2/artifact/output/latest/update-center.actual.json',
'content/_data/_generated/update_center.yml',
nil,
nil
```
After applying this patch, the error goes away, and the security advisories index page …
=> [INFRA-1666] If we are naming a file *.yml, convert from JSON first

content/doc/book/pipeline/jenkinsfile.adoc
The sample Jenkinsfile uses the step `sh 'make check || true'` but the caption for that sample had it quoted as `sh 'make || true'`. This change makes the caption match the text in the example Jenkinsfile.
=> Editing a caption so that it matches the example

content/node/index.html.haml
[WEBSITE-491](https://issues.jenkins-ci.org/browse/WEBSITE-491)
* Page 4 was never linked.
* The first skip section was always only 1 page (page 4)
* Both skip sections were shown side by side when on page 1
* It linked the first 3, but last 4 pages.
This fixes all of this, always showing the current page, the two pages before and after it, and the first and last three pages.
=> [WEBSITE-491] Fix pagination

content/_layouts/documentation.html.haml, content/doc/tutorials/build-a-multibranch-pipeline-project.adoc, content/doc/tutorials/index.adoc
Changed the name of the multibranch tutorial to reflect that it is not an "intro to multibranch projects" but will create the stup such that things like webhooks will trigger the multibranch which feels more complete than a basic intro
=> Changed the name of the multibranch tutorial

content/doc/book/pipeline/jenkinsfile.adoc
Added a not to clarify the "correct" way to use a withCredentials step so that you are not having the groovy interpreter replace the values and it is just an ENV variable instead
@Reviewbybees @jglick 
Could I get you to make sure this would be a good place and this is the correct information
=> Added a note around withCredentials

content/_layouts/sig.html.haml, content/sigs/cloud-native/index.adoc
@tracymiranda @oleg-nenashev 
Adds organizations to SIG pages
Also partially addresses Oleg's concerns about participant list length by splitting across two columns.
Waiting for update to https://github.com/jenkinsci/jep/pull/138 to specify how orgs sign up.
=> Add Organizations to SIGs

content/blog/2018/07/2018-07-30-introducing-cloud-native-sig.adoc
Fixed links to profiles. Also, link to GSOC SIG is not working - https://jenkins.io/sigs/gsoc. Is it not available now or just the link is wrong?
=> Fixed broken links in SIG blog post

content/_partials/toptoolbar.html.haml, content/projects/cloud-native/index.adoc, content/sigs/cloud-native/index.adoc, content/sigs/index.html.haml, content/sigs/platform/index.adoc
This is intendent to get top-level visibilty for Cloud Native
while we consider ways to reorganize sub-projects and SIGs.
=> Add pseudo project for Cloud Native Jenkins

content/doc/book/architecting-for-scale.adoc
=> Fix simple typo - Architecting for Scale

content/_partials/toptoolbar.html.haml
Since the addition of "Special Interest Groups" to the top nav bar, it has looked pretty bad:
The change reduces the number of top level items to fix the issue: 
1. Move use-cases under documentation
2. Rename Participate to Community
3. Moves Resources under Community
4. Move Special Interest Groups under Community
This is my first cut at this and I'm open to feedback.  However we should do something as it currently doesn't look great.
You can see this working at https://bitwiseman.github.io/jenkins.io/top-menu/
=> Reduce number of top menu items

content/sigs/cloud-native/index.adoc
PC Chan & Yuwei Zhou have joined SIG mailing list and requested Microsoft Azure be listed as the representative organization.
=> Add Microsoft Azure to Cloud Native SIG organization list

content/blog/2018/04/2018-04-06-jenkins-essentials.adoc, content/blog/2018/04/2018-04-27-essentials-versions-are-numbered.adoc, content/blog/2018/06/2018-06-26-jenkins-essentials-at-eclipsecon-france.adoc, content/blog/2018/07/2018-07-10-jenkins-essentials-on-aws.adoc, content/blog/2018/07/2018-07-20-devops-world-jenkins-world-2018-agenda-is-live.adoc, content/blog/2018/07/2018-07-25-contributor-summit.adoc, content/blog/2018/07/2018-07-30-introducing-cloud-native-sig.adoc
[JENKINS-53147](https://issues.jenkins-ci.org/browse/JENKINS-53147)
* Added just a note for older entries, as I guess we do want to somehow "rewrite history".
* For more recent ones in July+, I chose the "history rewriting" path, especially as it is often referring to upcoming Jenkins World, so we should start adjusting so that newcomers do not get confused by this and just know "Evergreen".
@jenkins-infra/copy-editors esp. @rtyler
=> [JENKINS-53147] Rebrand Essentials to Evergreen

content/solutions/python.adoc
"Improve this Page" has apparently moved, so I added a direct link and updated the geometric reference.
=> Adapt python doc-page to wrapper layout

content/blog/2018/09/2018-09-10-scaling-network-connections.adoc
Amending #1762 since someone pointed out to me that the link target was to https://issues.jenkins-ci.org/browse/27035 which is of course wrong, despite the linked text getting the `JENKINS-` prefix. Seems like a bug in the macro @oleg-nenashev?
=> jira macro not linking correctly

content/node/index.html.haml
The existing page linking logic only works for the general blogs list.
When looking at tags with multiple pages of results, the pagination
links back to the general blog pages instead of more tag results.
I recently tried to direct someone to a list of all the blog posts that have to do with pipeline and noticed that pagination within a tag wasn't working.  
If I go to https://jenkins.io/node/tags/jenkinsworld/  and then try to navigate to page 3 using the pagination it leads to https://jenkins.io/node/page/3.html instead of https://jenkins.io/node/tags/jenkinsworld/page/3.html . 
This change fixes this by using relative links to stay within the page
structure that it starts in.  It also adjusts the links generated depending
on if this the first page (which has a non-numbered url) or …
=> Fix pagination for tags

content/sigs/cloud-native/index.adoc
Adding @deepy to the SIG, because he actively contributes to the External Configuration Storage story.
@tracymiranda @bitwiseman @carlossg. Managing SIG participants in the current way is an uphill battle, there are already 36 members. I would propose so somehow embed the list from the Google Group or so.
=> Add @deepy to the list of SIG participants (JEP-213)

content/doc/book/hardware-recommendations.adoc
Just a missing `:doctitle:` at `content/doc/book/hardware-recommendations.adoc`file.
=> Add missing doctitle to content/doc/book/hardware-recommendations.adoc

content/blog/2018/06/2018-06-17-running-jenkins-with-java10-11.adoc
Adds warning to the blogpost and adds some updates to the text of the Java 10/11 running guidelines
=> Update guidelines to reference the new BlueOcean image and suggest Java 11 by default

content/doc/book/pipeline/syntax.adoc
Also add `args` to the example for `dockerfile` just to be safe. =)
=> Add `args` to list of common-to-multiple-agent-types options.

content/blog/2018/10/2018-10-01-hacktoberfest.adoc
There are some last-minute changes in the documentation.
- Hacktoberfest does not longer require labeling issues. Registration on the site is enough
- There is a good FAQ page
I also moved Quick Start to the top
@jenkins-infra/copy-editors @jenkins-infra/hacktoberfest
=> Hacktoberfest: amend FAQ to reflect the current status

content/doc/book/managing/cli.adoc
See [JENKINS-53792](https://issues.jenkins-ci.org/browse/JENKINS-53792).
Downstream of [jenkinsci/jenkins#3653](https://github.com/jenkinsci/jenkins/pull/3653): In a similar way that the environment variable `JENKINS_URL` allows to execute different CLI command without specifying the -s option continuously, environment variable such as `JENKINS_USER_ID` and `JENKINS_API_TOKEN` might help configuring easily the executions without specifying the `-auth` option in each executed command.
@Wadeck @oleg-nenashev @daniel-beck @reviewbybees
=> [JENKINS-53792] Add new environment variables for http authentication documentation

content/_data/changelogs/lts.yml, content/_data/changelogs/weekly.yml, content/doc/upgrade-guide/2.138.adoc
See https://groups.google.com/forum/#!topic/jenkins-platform-sig/XEChclxQMGM for the context.
CC @daniel-beck @olivergondza @imdurgadas
=> [JENKINS-53832,JENKINS-53924] - Reference the GNU C compat issues on RHEL5/ CentOS 5 in the changelog

content/index.html.haml
Sentry has provided a free account for use in Evergreen and other backend
projects
=> Add Sentry as a supporter

content/doc/book/pipeline/index.adoc
Replace "do/es" with "do". Is correct and also improves readability.
Question about: "Scripted Pipeline provides clearer visualization" ... "clearer" than what? Clearer than the Declarative Syntax?
As a newbie I'm looking for some reason to favor one syntax over the other.  Is this a reason to favor the Scripted syntax?
=> Language Nits

content/_data/changelogs/lts.yml, content/_data/changelogs/weekly.yml, content/blog/2018/10/2018-10-10-security-updates.adoc, content/doc/upgrade-guide/2.138.adoc
https://wiki.jenkins.io/display/JENKINS/Plugins+affected+by+2018-10-10+Stapler+security+hardening
=> Add reference to wiki page tracking affected plugins

content/projects/gsoc/mentors.adoc
Some minimal copy-edits, mostly copy-paste.
We will be improving guidelines later
@martinda @christ66
=> GSoC: Move Mentor Guidelines from the announcement blogpost to the mentors page

content/projects/gsoc/2019/index.adoc, content/projects/gsoc/2019/project-ideas.adoc, content/projects/gsoc/gsoc2018-project-ideas.adoc, content/projects/gsoc/index.adoc, content/projects/gsoc/mentors.adoc, content/projects/gsoc/proposing-project-ideas.adoc
This change does some initialization for GSoC 2019 pages. It does not rework project ideas to the new layout we discussed before, but it should be a good starting point for rework.
@martinda @jeffpearce @lloydchang
=> [WEBSITE-527] - Create base pages for GSoC 2019

content/project/governance.adoc
The accounts page has been moved to a new URL, and setting the link to the final URL will avoid a redirection
=> Point the accounts link to the final destination

content/doc/book/pipeline/shared-libraries.adoc
Remove unnecessary semicolons in /content/doc/book/pipeline/shared-libraries.adoc.
=> Remove unnecessary semicolons in shared-libraries.adoc

content/doc/book/managing/plugins.adoc
See [WEBSITE-531](https://issues.jenkins-ci.org/browse/WEBSITE-531)
New CLI commands for enabling and disabling plugins have been included in Jenkins:
- enable-plugin command was included in jenkins-2.136
- disable-plugin command was included in jenkins-2.151
Let's update the managing plugins contents referring those commands.
@reviewbybees
@jvz @MRamonLeon as developers
=> [WEBSITE-531] Add new CLI commands for enabling and disabling plugins

content/projects/gsoc/2019/index.adoc, content/projects/gsoc/index.adoc
I am still not sure that splitting the landing page and GSoC 2019 page was a good idea. Probably I will merge the pages and add a redirect in the next iteration.
@martinda @lloydchang @jeffpearce
=> [GSoC 2019] - Add links to office hours and schedule, cleanup the Org Admin mailing list

content/projects/evergreen/index.adoc
Fixing a small typo, full stop is missing in the Evergreen project description.
=> Add missing full stop on Evergreen description

content/_layouts/sig.html.haml, content/events.html.haml, content/sigs/index.html.haml, content/sigs/platform/index.adoc
@batmat @alecharp @MRamonLeon @MarkEWaite @jenkins-infra/copy-editors
=> [Platform SIG] - Add regular meetings, meeting notes, and page updates

content/_data/changelogs/lts.yml, content/_data/changelogs/weekly.yml, content/changelog-stable/index.html.haml, content/doc/upgrade-guide/2.138.adoc, content/doc/upgrade-guide/2.150.adoc
Public preliminary changelog and upgrade guides for 2.138.4 and 2.150.1 ([see announcement](https://groups.google.com/d/msg/jenkinsci-advisories/krQ9g3TOqWI/9Vkf1sf9BAAJ)).
----
> ![screen shot](https://user-images.githubusercontent.com/1831569/49245416-83a4bb80-f412-11e8-817d-51a2ef738ae4.png)
=> Add changelogs and upgrade guides for 2.138.4 and 2.150.1

content/projects/gsoc/roles-and-responsibilities.adoc
This fixes broken links in Roles and Responsibilities page
=> AsciiDoc relative links require closing [] to be clickable

content/doc/book/pipeline/syntax.adoc
some of the examples where missing `cron('` and a quotation mark at the end.
=> Fix cron syntax examples

content/css/jenkins.css
This PR targets the link underline showing when hovering over images in the sponsors block.
=> Fix sponsors underline showing on hover

content/security/advisory/2018-12-05.adoc
@orangetw wondered where their credit is, so reformat.
Really unsure how to credit additional reports, especially if they're much later than others, or incomplete, but not opposed to doing it this way, even if it looks a bit weird.
> ![screen shot](https://user-images.githubusercontent.com/1831569/49510802-a5c29180-f889-11e8-834b-29a69f5d6a2c.png)
=> List all SECURITY-595 reporters and contributors in credits section

content/index.html.haml
Another small fix, this time targeting the underlined trailing space from each sponsor link.
=> Fix underlined trailing space in sponsor links

content/blog/2018/06/2018-06-17-running-jenkins-with-java10-11.adoc, content/doc/administration/requirements/java.adoc
Updated to current support status (Java 10 not supported, for instance)
Added a warning link from the blog entry to the up to date solution page to drive users to the updated information.
cc @oleg-nenashev @MRamonLeon @alecharp 
Renders as:
=> Update to current Java requirements status

content/_layouts/project.html.haml, content/_layouts/sig.html.haml
@jenkins-infra/copy-editors  @bitwiseman 
Changes the SIG layout a bit. All links are moved to the `project` layout so that they can be actually reused on other project pages if needed. Logo size was also increased since we have more space now.
=> [SIGs] - Move the contacts to the main right panel

content/projects/index.adoc
@jenkins-infra/copy-editors @bitwiseman
Use the Jenkins GSoC Logo on the Jenkins Sub-Projects page, and update the paragraph for the current year.
=> Use GSoC Logo, update for current year

content/doc/book/pipeline/syntax.adoc
It requires a named parameter, and I gave a bad example. Fixed.
=> [JENKINS-54386] Fix example for preserveStashes.

content/hangout.adoc
The older Hangout seemed to be restricted to the CloudBees organization.
=> Use a new Google Hangout

content/changelog-old.html
Obtained from the `META-INF/MANIFEST.MF` file modification date inside the respective `.war` file from Artifactory. This is the date format `unzip -v` uses, and I didn't care enough to fix them.
=> Backfill old Hudson release dates

content/blog/2018/06/2018-06-17-running-jenkins-with-java10-11.adoc
The change makes the support status reference explicit. We will no longer need references in this blogpost, because all the new updates refer the Java support page.
CC @MRamonLeon @batmat @alecharp
=> [JEP-211] - Update the warning in the June 2018 blogpost

content/doc/developer/javadoc.html.haml
Rather than use a trailing hyperlink, reuse the opening phrase of the description sentence to also include a hyperlink to the javadoc.
Also fix a minor phrasing problem.  It was:
> This site collects and the Javadoc for the newest releases of all Jenkins plugins, if available.
=> Move Javadoc links into description text

content/projects/gsoc/proposing-project-ideas.adoc
Minor fix: Fixed the link to the list of org admins, and clarified the commenting process for proposals.
@lloydchang @jeffpearce @oleg-nenashev
=> Fix link to org admins. Clarify comment process.

content/projects/gsoc/2019/schedule.adoc
@oleg-nenashev @lloydchang @jeffpearce 
Added a disclaimer to the timeline that we published, spelling out that the official timeline is the one from Google.
=> Add disclaimer to the internal timeline

content/projects/gsoc/2019/index.adoc, content/projects/gsoc/2019/project-ideas.html.haml, content/projects/gsoc/2019/schedule.adoc, content/projects/gsoc/index.adoc, content/projects/gsoc/mentors.adoc, content/projects/gsoc/proposing-project-ideas.adoc, content/projects/gsoc/roles-and-responsibilities.adoc, content/projects/gsoc/students.adoc
I am working on a generic solution so that the links can be inherited from the SIG metadata. But this one shoild at least make contacts visible everywhere for now.
=> [GSoC 2019] - Add contact links to all 2019 pages

content/projects/gsoc/2019/application.md, content/projects/gsoc/index.adoc
Largely this is a copy-paste of the 2018 application with few edits in the text.
A lot can be improved there, but keep in mind that the most of the entries are at the lenght limit
=> [GSoC 2019] - Create a GSoC 2019 application draft

content/_layouts/gsocprojectidea.html.haml, content/projects/gsoc/2019/project-ideas/artifact-promotion-plugin-for-jenkins-pipeline.adoc, content/projects/gsoc/2019/project-ideas/ath-improvements.adoc, content/projects/gsoc/2019/project-ideas/automatic-spec-generator-for-jenkins-rest-api.adoc, content/projects/gsoc/2019/project-ideas/bitbucket-rest-plugin.adoc, content/projects/gsoc/2019/project-ideas/discard-builds-step-plugin.adoc, content/projects/gsoc/2019/project-ideas/docker-registries-polling-plugin.adoc, content/projects/gsoc/2019/project-ideas/eda-coverage-adapters.adoc, content/projects/gsoc/2019/project-ideas/eda-plugins.adoc, content/projects/gsoc/2019/project-ideas/ext-workspace-manager-cloud-features.adoc, content/projects/gsoc/2019/project-ideas/gitlab-support-for-multibranch-pipeline.adoc, content/projects/gsoc/2019/project-ideas/jenkins-rest-plugin.adoc, content/projects/gsoc/2019/project-ideas/working-hours-improvements.adoc
Just a proposal for review. We can embed Google Docs into the project idea draft pages so that the idea is shown in the Web UI. Not sure whether it is good or bad from the UX perspective, would appreciate feedback
=> [GSoC 2019] - Embed the draft google Docs in project idea pages

content/_layouts/simplepage.html.haml
There is a number of jenkins.io pages inheriting `simplepage` due to some reasons. E.g. we use it for GSoC where we generate content by YAML. Unfortunately these pages look really bad on smartphones due to the hardcoded margins. Some pages are really critical to be viewable from mobile phones:
* Jenkins Changelog
* Security advisories
* GSoC 2019 Project ideas (students navigate by phone)
Other templates like `project` or `documentation` do not have such margins. Originally the margins in `simplepage` were introduced by @rtyler for BlueOcean pages: https://github.com/jenkins-infra/jenkins.io/pull/266 , but BlueOcean pages do not longer use this layout anymore.
I propose to just remove margins. The layouts stay bad, but they definitely get somewhat better after the change
=> Remove simplepage margins to improve visualization on mobile screens

content/projects/blueocean/roadmap/index.html.haml, content/projects/evergreen/index.adoc, content/projects/infrastructure/index.adoc, content/projects/infrastructure/ircbot.adoc, content/projects/jam/index.adoc, content/projects/jam/suggest.html.haml, content/projects/jcasc/index.adoc, content/projects/jenkins-x/index.adoc, content/projects/remoting/index.adoc, content/sigs/chinese-localization/index.adoc, content/sigs/cloud-native/index.adoc, content/sigs/pipeline-authoring/index.adoc
This PR is an addition to #2014. Once both are integrated, it will be possible to add connect links to blogposts and project pages. Also, the contacts will show up on the landing pages now. This PR addresses all projects and SIGs except GSoC which is handled in #2014 
CC leaders of SIGs/Projects: @carlossg @jstrachan @rtyler @batmat @michaelneale @MarkEWaite @ewelinawilkosz @alyssat @LinuxSuRen @abayer
=> Add communication channel links to projects and SIGs

content/_layouts/gsocprojectidea.html.haml, content/projects/gsoc/2019/project-ideas/artifact-promotion-plugin-for-jenkins-pipeline.adoc, content/projects/gsoc/2019/project-ideas/automatic-spec-generator-for-jenkins-rest-api.adoc
Publish 2 project ideas as Google doc. In order to do that, I have added few flags
=> [GSoC 2019] - Support publishing GSoC projects as Google Docs

content/_data/changelogs/weekly.yml
To be merged ASAP due to the wrong description for 2.159 from #2031.
=> Fix changelog for 2.159 after emergency release

content/_layouts/gsocprojectidea.html.haml, content/projects/gsoc/2019/project-ideas.html.haml
There was some confusion whether skills mean “required skills” or “skills to study”.
I believe it rather means the second, and I propose to change the layout accordingly
=> [GSoC 2019] - Clarify what “Skills” mean

content/_layouts/gsocprojectidea.html.haml
As @kwhetstone suggested, added some organization-wide links to the project idea pages.
@jenkins-infra/gsoc @kwhetstone
=> [GSoC 2019] - Add /participate and newbie-friendly issues to the project ideas

content/security/advisory/2018-09-25.adoc, content/security/advisory/2018-10-10.adoc, content/security/advisory/2019-01-08.adoc, content/security/advisory/2019-01-16.adoc
Some 'CVE pending' are removed because I ended up not requesting CVEs due to low install counts of the affected plugins.
**DO NOT MERGE, I will merge this when ready.**
=> Add CVEs assigned so far in January 2019

content/projects/gsoc/2019/project-ideas/ext-workspace-manager-cloud-features.adoc
Just to follow-up on the SIG discussions we had. This project maps the Cloud Native SIG well, but it needs explicit +1 from @martinda before merging.
Also CC @carlossg
=> [GSoC 2019] - Link Ext Workspace Manager Cloud Features to the Cloud Native SIG

content/doc/book/pipeline/syntax.adoc
The previous version resulted in:
> Evaluating when before entering the stage’s `agent
=> Fix parsing

content/doc/book/pipeline/shared-libraries.adoc
👋I noticed that the formatting for this paragraph was a bit off on the website:
=> Fix shared library documentation formatting

content/blog/2019/02/2019-02-06-ssh-steps-for-jenkins-pipeline.adoc
=> Syntax highlighting typo in 2019-02-06-ssh-steps-for-jenkins-pipeline.

content/projects/gsoc/2019/application.md
=> [GSoC 2019] - Explicitly reference SIGs and sub-projects in the application

content/doc/book/pipeline/shared-libraries.adoc
Added some text to explain where and when user-provided documentation of shared libraries will be visible in the Jenkins UI.
=> Clarify Shared Library documentation re: user-provided docs

content/doc/book/pipeline/shared-libraries.adoc
Global variables are indeed useful outside of `script` blocks:
They enable one to define custom steps.
=> Clarify that global variables as steps

content/projects/jcasc/index.adoc
adding short info regarding Office Hours meeting so it can be announced with https://jenkins.io/event-calendar/
@oleg-nenashev please comment once you have time
=> Office Hours info added to JCasC project

content/doc/administration/requirements/java.adoc
See [[WEBSITE-623] Change jdk-tool-plugin by jdk tool in Java requirements page](https://issues.jenkins-ci.org/browse/WEBSITE-623)
The jdk-tool-plugin is a plugin to add an automatic installer for JDKs downloading them from Oracle web site based on a crawler that relies on the structure of the Oracle Web Site. 
It's not a recommended approach to use this way of installing JDKs, so the official documentation can't talk about this plugin as the main way of executing builds with different Java versions.
Just **change** the use of the **jdk-tool-plugin by jdk tool**, slight difference but important.
@jenkins-infra/java11-support
=> [WEBSITE-623] Change plugin:jdk-tool by jdk tool (it's not the same)

content/blog/2019/02/2019-02-06-ssh-steps-for-jenkins-pipeline.adoc, content/chat.adoc
* Use unambiguous Gitter room identifiers as they (also) appear on the UI.
* Remove some of the more specialized, or obsolete, chats. We don't need everything here, just those we can reasonable expect people to be interested in coming through the generic 'chat' page. Otherwise it's just too long of a list.
* Fix formatting based on errors printed during build
Also updates formatting of a blog post the build also complained about.
=> Update 'Chat' page

content/blog/2019/02/2019-02-21-credentials-masking.adoc
[WEBSITE-610](https://issues.jenkins-ci.org/browse/WEBSITE-610)
Does not address the part of the existing docs that's misleading (see Jira), but it's a start at least. I don't have the time to deal with the weird structure of the pipeline docs.
=> [WEBSITE-610] Add blog post on credentials masking

content/events.html.haml, content/projects/gsoc/index.adoc
I would like to add GSoC to the list of recurring [events](https://jenkins.io/events/).
=> Add GSoC to the list of events

Gemfile, scripts/ruby
According to https://www.ruby-lang.org/en/downloads/branches/ ,
ruby 2.3 is nearing EOL, so bump up version used for building docs at jenkins.io
=> Bump up to Ruby 2.6

content/blog/2018/06/2018-06-17-running-jenkins-with-java10-11.adoc, content/blog/2018/12/2018-12-14-java11-preview-availability.adoc, content/doc/administration/requirements/java.adoc, content/doc/administration/requirements/jenkins-on-java-11.adoc, content/doc/administration/requirements/upgrade-java-guidelines.adoc
[WEBSITE-497](https://issues.jenkins-ci.org/browse/WEBSITE-497)
With description to upgrade the JVM used to run Jenkins.
@jenkins-infra/java11-support-reviewer
=> [WEBSITE-497] Add documentation to run Jenkins on Java 11

content/css/jenkins.css
Reduces the size of the animated png that was added in https://github.com/jenkins-infra/jenkins.io/pull/2129 showing the "restart" stage functionality
=> Reduce the size of the "restart stage" animated png

content/doc/administration/requirements/upgrade-java-guidelines.adoc
Java 11 does not include Java Web Start.
Also corrects an incorrect attribution of the JDK 11 licensing problem.  Earlier it said that Jenkins 11 was the cause of the issue.  There is no Jenkins 11, only Java 11.
Navigation path for the user to reach this page is longer than I would like, but that would require larger changes than I can make at this time.
=> Make Java Web Start explanation more visible

content/doc/book/pipeline/running-pipelines.adoc
Originally it resulted in a section link within the same document instead of linking to a different document, effectively linking to itself.
=> Correcting multibranch link

content/projects/gsoc/2019/project-ideas/automatic-spec-generator-for-jenkins-rest-api.adoc
As discussed on https://github.com/jenkins-infra/jenkins.io/pull/2157
=> Revert Stapler from the list of useful skills outside of Jenkins.

CONTRIBUTING.adoc
The http://awestruct.org/ domain has expired. Linking [Awestruct's repository](https://github.com/awestruct/awestruct) in GitHub seems like the safest replacement.
=> Replaced broken link to Awestruct site with a link to its GitHub repo

content/doc/book/pipeline/syntax.adoc
As of at least jenkinsci/pipeline-model-definition-plugin/pull/322 (released in Pipeline: Declarative 1.3.7), but probably as early as jenkinsci/pipeline-model-definition-plugin/pull/313 (released in Pipeline: Declarative 1.3.5), failure conditions _are_ executed even if the result is set to FAILURE manually. I added a test confirming the behavior in https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/322/commits/3beec5b76ff0e4c901d6446f60b3774ace5c5536.
CC @abayer
=> Declarative Pipeline post failure conditions now run even if the result is set manually

content/_layouts/frame.html.haml
The current content renders like this when hovered:
Because the haml to html is:
```
<a href='https://github.com/jenkins-infra/jenkins.io/edit/master/content//index.html.haml' title='Edit /index.html.haml on GitHub'>
Improve this page
</a>
|
<a href='https://github.com/jenkins-infra/jenkins.io/commits/master/content//index.html.haml' title='View /index.html.haml history on GitHub'>
Page history
</a>
```
Browsers used to have some fairly interesting whitespace collapsing rules.  But, at this point the general rule is that whitespace will be part of your link if it's there.
here's a data url you can load in a browser to get a sense of the general behavior:
```
data:text/html,<title>test</title>pure inline: <a href="http://example.com"> a </a>b;<p>new blocks:<p><a href="http://example.com"> …
```
=> try to avoid anchoring trailing whitespace

content/participate/index.html.haml
The anchor text of links to the /chat page were only mentioning IRC, even though Gitter was included in its content; so I modified the corresponding links to add it
=> Added Gitter to "Participate and contribute". Only IRC was there.

content/participate/index.html.haml
In the "Participate and contribute" page, if the reader is not part of the "code-reviewers" or "copy-editors" GitHub teams, a "No results marched your search" message will be displayed when clicking the links. Without the note, it might be confusing for a newcomer.
=> Added note specifying that PRs listed for review only visible to those in the GitHub Teams

README.adoc
This change has already been made and merged in the CONTRIBUTING file ([see](https://github.com/jenkins-infra/jenkins.io/pull/2181)), so it seems the README file should follow the same path
=> Replaced broken link to Awestruct site with link to its GitHub (README)

content/security/advisory/2019-04-03.adoc
In previous advisories, we've always specified the latest known affected versions even for issues without a fix. This does not substantially change the content of the advisory in a way that would require an update notification, it may however limit confusion in the future once fixes are released.
This coupled with the statement that no fixes were available as the advisory was published should be good enough.
> ![Screen Shot](https://user-images.githubusercontent.com/1831569/55674642-92671780-58b7-11e9-945a-9c58098f55e9.png)
=> Add last confirmed version to 2019-04-03 advisory

content/projects/gsoc/2019/project-ideas/automatic-spec-generator-for-jenkins-rest-api.adoc
Since OpenAPI has a wider reach beyond Swagger spec, it's worth mentioning that OpenAPI is a skill that students would pick up.
Note: Swagger spec was donated to OpenAPI https://smartbear.com/news/news-releases/smartbear-launches-open-api-initiative-with-key-in/ .
=> Add Open API to skills list.

content/_data/changelogs/weekly.yml
Includes the fix for [JENKINS-57096](https://issues.jenkins-ci.org/browse/JENKINS-57096) in the changelog:
@jenkins-infra/java11-support-maintainer @daniel-beck
=> Update 2.175 changelog

content/doc/book/pipeline/syntax.adoc
[JENKINS-52850](https://issues.jenkins-ci.org/browse/JENKINS-52850)
* Add support for SSH with Private Key credentials in the `environment` block of declarative pipeline.
* Improve the current documentation for credentials helper.
=> [JENKINS-52850] Improve credentials helper section and add SSH support

content/doc/developer/publishing/releasing-experimental-updates.adoc
Consider this part of my apology for releasing git plugin 4.0.0-rc to the entire community when I had intended that it would only be released to the experimental update center.
=> Clarify developer use of Experimental Update Center

content/_data/changelogs/weekly.yml
It is no longer minor since we have 4 plugin regressions after https://github.com/jenkinsci/jenkins/pull/3980
CC @daniel-beck @batmat @jglick
=> Changelog - Noting JENKINS-47896 in 2.175

content/blog/2019/05/2019-05-05-telemetry-success.adoc
Release date is flexible. If released tomorrow (as currently indicated in the file name), we can even rephrase it to *Six months ago today*; otherwise next week should be fine.
=> Add blog post on Stapler telemetry

content/blog/2019/05/2019-05-11-docs-sig-announcement.adoc, content/events.html.haml, content/sigs/docs/index.adoc
Include links to existing documentation like:
* Using Jenkins
* Extending Jenkins
* Solution documentation
Include participants from the initial meeting and individuals that have expressed willingness to contribute to documentation.
Also adds the Docs SIG to the repeating events list and provides a blog entry for the Docs SIG.
=> Announce Docs SIG with SIG page and blog post

content/sigs/advocacy-and-outreach/index.adoc, content/sigs/chinese-localization/index.adoc, content/sigs/cloud-native/index.adoc, content/sigs/hw-and-eda/index.adoc, content/sigs/pipeline-authoring/index.adoc, content/sigs/platform/index.adoc
The 'Connect' links are intended to link to locations outside the page. They open a new browser tab when the link is clicked.
However, some of the special interest groups don't have a solo meeting URL that is external to the page.  Rather than remove the 'Meetings' link in the 'Connect' section for those pages, this change will resolve those links to the 'Meetings' heading inside the page.
* Advocacy and Outreach SIG links to external meeting notes
* Platform SIG links to external meeting notes
* Chinese localization SIG
* Cloud native SIG
* Hardware / EDA SIG
* Pipeline authoring SIG
=> Fix the meetings hyperlinks on the SIG pages

content/sigs/docs/index.adoc
I suggest that there is another logo chosen for the Docs SIG.
CC @MarkEWaite
=> Docs SIG should not use the Platform SIG logo

content/blog/2019/05/2019-05-11-docs-sig-announcement.adoc, content/sigs/docs/index.adoc, content/sigs/platform/index.adoc
Don't include a broken image reference, better to wait until a specific image is selected or provided.  That image should not be the same image as any other SIG and preferably would be unique to the Docs SIG.
=> Remove docs sig blog image

content/_data/solutions/android.yml, content/css/jenkins.css
* replace dead video link with a valid one
* make sure 'media-row' class is actually displayed as row and only wraps on small screens (currently displayed as column, see https://jenkins.io/solutions/docker/ )
=> Fix display of videos in solution sites

content/projects/evergreen/index.adoc, content/projects/gsoc/index.adoc, content/projects/jcasc/index.adoc, content/projects/jenkins-x/index.adoc, content/sigs/chinese-localization/index.adoc, content/sigs/gsoc/index.adoc, content/sigs/platform/index.adoc
Adds the `og:image` meta  tag to pages that have a unique logo.
Also fixes a minor typo in adoc syntax for GSoC.
=> [WEBSITE-520] add OpenGraph image to SIGs and projects

content/doc/book/pipeline/jenkinsfile.adoc
Credential masking is a reasonable attempt to prevent accidental disclosure of credentials.  It does not (and cannot) prevent those with malicious intent from disclosing credentials which their Pipeline is allowed to access.  If a Pipeline can use a credential, it has the values of the credential and can leak those values if it chooses to do so.
See [WEBSITE-610](https://issues.jenkins-ci.org/browse/WEBSITE-610) for more details
=> [WEBSITE-610] Clarify credential masking limitations

content/blog/2017/08/2017-08-07-intro-to-plugin-development.adoc
Blog post was written at a time when the javadoc for the Jenkins Test Harness was not being regularly published to a standard URL.  Use the standard URL now.
=> Fix hyperlinks to Jenkins test harness javadoc

content/sigs/docs/index.adoc
Twitter and Facebook shares will use the OpenGraph image as part of their post.  Images in social media posts increase user engagement.
=> Add opengraph image to Docs SIG

content/_layouts/frame.html.haml, content/projects/blueocean/roadmap/index.html.haml
Currrently bower assets contain both full and minified version of jQuery. Most pages load the full one, Blue Ocean roadmap loads both. This PR loads the minified version everywhere.
=> Use minified version of jQuery

scripts/release.rss.groovy
An old optimization of the update center build was to not retrieve the plugin name and other metadata included in the manifest file for releases older than 31 days.
This script reads the last 31 per-day batches of plugin releases from that file. However, if no releases have happened yet today, then this will include dates older than the cutoff for retrieval of the plugin name.
For that reason, the oldest entries in release-history.json may lack the data required to have a title, so they show up as "null", e.g. in https://twitter.com/jenkins_release/status/1132456704027717633
Before and after: https://gist.github.com/daniel-beck/ed818b4597751ee9b93e5e48c8a79fd3
This is expected to only remove the oldest entries in some situations.
=> Do not publish releases named 'null' in RSS

content/blog/2019/05/2019-05-30-becoming-contributor-newbie-tickets.adoc
The newbie-friendly bug query in the Jenkins CONTRIBUTING file is a
good choice.  Use it instead of the earlier URL.
=> Fix newbie-friendly query URL in blog post

content/doc/book/installing/index.adoc
Updated the resolution for the following common error -
Error -
The following packages have unmet dependencies:
jenkins : Depends: daemon but it is not installable
E: Unable to correct problems, you have held broken packages.
Solution Updated -
sudo add-apt-repository universe
=> Updated the Error resolution for Ubuntu 18.04 Server Version

content/blog/2019/05/2019-05-09-templating-engine.adoc
Use consistent heading levels to match with other blog posts.  The asciidoc warnings note that the original heading levels in the blog post were one level higher than is allowed.  They were also one level higher than those in other blog posts.  This change will make the blog post presentation consistent with other blog posts and remove the surprising message from the output.
=> Fix asciidoc heading warnings in blog post

content/_layouts/frame.html.haml, content/_partials/dropdown.html.haml, content/_partials/projectcarousel.html.haml, content/_partials/toptoolbar.html.haml, content/css/jenkins.css
* Change the dropdowns from <div>s to <button>s to make them work with keyboard, add CSS to make sure this change does not alter their appearance. Use JS to hide the dropdown outline when used with mouse.
* Add missing `alt`-text and `lang` values
* Mark the image on the frontpage as `presentation` as it doesn't contain information not included in the text
=> [WEBSITE-155] a11y: fix navigation by tab, add metadata

content/doc/book/installing/_docker.adoc
Change "automtically" to "automatically"
=> Fix simple typo - installing jenkins annotations

content/projects/gsoc/2019/role-strategy-performance.adoc
Update GSoC Role Strategy Project page to add links to demos and presentation slides.
@oleg-nenashev @runzexia @supun94
=> Update GSoC Role Strategy Project page

content/doc/developer/tutorial/create.adoc
Fix a small typo that changes the layout of
https://jenkins.io/doc/developer/tutorial/create/
=> Fix typo in Adoc syntax

content/doc/book/pipeline/syntax.adoc
The details on how to configure a Kubernetes agent in the Jenkinsfile is missing. I added a code block and a link to an example YAML as reference.
=> Add information about Kubernetes agent in the docs

content/_ext/pipeline.rb, content/_ext/validator.rb, content/doc/book/pipeline/syntax.adoc, content/doc/book/system-administration/security/build-authorization.adoc, content/images/jams/ToulouseJam/README.asciidoc
This PR
* fixes recent Asciidoc syntax typo that got merged in #2353
* adds validation for title/layout to make sure we catch front matter typos
* adds missing title/layout for the two pages that were missing those
For the Toulouse meetup README page (https://jenkins.io/images/jams/ToulouseJam/README/ ) deletion might make more sense than the fix, but I wouldn't dare :) @batmat looped
=> Add title / layout validation, fix syntax erors

content/_ext/validator.rb
See [WEBSITE-270](https://issues.jenkins-ci.org/browse/WEBSITE-270)
The PR does not fix the parsing problem as I couldn't find it (probably somewhere in Awestruct), but at least it corrects the wrongly parsed titles.
Note that the issue also impacts existing pages like
https://jenkins.io/doc/developer/extensions/workflow-cps/
=> [WEBSITE-270] allow colon in section titles

content/_partials/pagination.html.haml
This should not affect users at all, just makes the markup cleaner.
If a pagination link is not disabled, it should have no additional class. Currently a Ruby object is serialized to HTML, in the source of https://jenkins.io/node/ yo can see
```
<li class='47135220427120: 47135221800140: 47135222560800: 47135222767480: 47135223628660: 47135223869240: 47135224483480: 47135225221300: :change_frequency=&gt;"never", :lastmod=&gt;"2019-07-20", :layout=&gt;"default", :paginate_generated=&gt;true, :posts=&gt;[Awestruct::Page{ :priority=&gt;0.1, :section=&gt;"blog", :selected_tag=&gt;nil, :title=&gt;"Jenkins :url=&gt;"/node/page/2.html"} Awestruct::Page{ Blog", Community layout=&gt;post output_path=&gt;/blog/2019/04/03/security-advisory/index.html, …
```
=> Do not print ruby objects in HTML

content/doc/book/pipeline/docker.adoc
When using a Dockerfile in a sub-directory from root directory, the description says docker.build should end with the path where Dockerfile is found, but it should end with the path of folder to consider the build context for this command to succeed.
=> Corrected the description in section Building containers

content/_layouts/advisory.html.haml
This is the first advisory since I introduced this placeholder that depublished plugins, so this problem didn't show up before.
----
> ![Screenshot](https://user-images.githubusercontent.com/1831569/62702286-9e3e2400-b9e6-11e9-815e-53ae567840c3.png)
> ![Screenshot](https://user-images.githubusercontent.com/1831569/62702296-a4340500-b9e6-11e9-8a35-ad9c4d6aad15.png)
=> Fix PLUGIN_NAME in advisories

CONTRIBUTING.adoc
Markdown does not convert to links inside an adoc file.
=> Use adoc link markup in contributing file

content/doc/book/architecting-for-manageability.adoc, content/doc/book/architecting-for-scale.adoc, content/doc/book/installing/index.adoc, content/download/index.html.haml
Added hardware recommendations to:
-  Installation
- Downloads
- content/doc/book/architecting-for-manageability.adoc
- content/doc/book/architecting-for-scale.adoc
Couldn't get Cross references working so I went with external links
=> Added hardware recommendations to several pages

content/blog/2019/05/2019-05-09-templating-engine.adoc
Hey!  we've updated the documentation link for the Templating Engine Plugin - so i'd like to update this blog post to point to the correct site.
=> Update link to documentation in older blog post 

content/projects/index.adoc
subj. Just noticed some obsolete information
=> GSoC - Remove the 2018 project reference from the Projects page

content/_data/events/2019-08-23-jom-summer-projects-1.adoc, content/_data/events/2019-08-26-jom-summer-projects-2.adoc, content/_data/events/2019-10-25-hackathon-beijing.adoc, content/_data/events/2019-12-02-devops-world-jenkins-world-lisbon.adoc, content/_partials/events.html.haml, content/events.html.haml
Historically we had issues with events which did not explicitly specify locations, e.g. see the Beijing hackathon where the location is not visible on the front page. The header row was also pretty short in some cases to display enough information about an event.
In this change I suggest to explicitly add a 'location' metadata which gets displayed under the event title. We can also add some geolocation later if we want, but even the current state should be helpful for users.
=> Add event locations to website and metadata

content/css/jenkins.css
After #2405 the header reverted to default bootstrap color / font, which was not intentional. This PR makes sure the overrides from `jenkins.css` are actually used for the navbar.
@halkeye looped
=> Update styles for new navbar class

content/doc/book/pipeline/getting-started.adoc
[Documentation feedback](https://docs.google.com/spreadsheets/d/1nA8xVOkyKmZ8oTYSLdwjborT0w-BpBNNZT0nxR9deZ8/edit#gid=1087292709) on this page said:
> Update the Global Variable Reference links that point to localhost to point to a real page.
> The "Global Variable Reference" on this page point to "localhost:8080". Please fix or remove this link.
We can't point to a real page because the user needs to consult the content on their specific Jenkins server. Compromise by mentioning the assumption in more places.
=> Doc ref to localhost assumes a local server

content/doc/book/pipeline/getting-started.adoc, content/doc/book/pipeline/jenkinsfile.adoc, content/doc/book/scaling/index.adoc, content/doc/pipeline/tour/environment.adoc
[Reader feedback](https://docs.google.com/spreadsheets/d/1nA8xVOkyKmZ8oTYSLdwjborT0w-BpBNNZT0nxR9deZ8/edit#gid=1087292709) from the jenkins.io site requested that an example referencing an environment variable be included in the environment step description.
Comment was:
> It shows how to declare variables, but doesn't show how to use them. Do I need a $ before the variable or not?
This example shows how to use defined environment variables in declarative and scripted pipeline.  Verified behavior on Jenkins 2.176.2 with latest Pipeline plugin releases.
Also added exclusion to prevent running the example on Windows, since it uses an `sh` step and that was failing on my Windows agents.
=> Add example to environment docs

content/doc/book/pipeline/syntax.adoc
See [JENKINS-59115](https://issues.jenkins-ci.org/browse/JENKINS-59115).
Documentation for the `branch` when condition with comparator. Similar to:
- https://github.com/jenkins-infra/jenkins.io/pull/1430
Downstream of https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/351
=> [JENKINS-59115] Documentation for branch when condition with comparator

content/_config/site.yml
Since a bugfix in Awestruct the parallelization settings changed. The last few builds were slower (5min->9min) and had some unexpected failures. This PR will set the parallelization back from threads to processes.
=> Reset parallelism setting for site generation

content/doc/developer/security/xss-prevention.adoc
Propose a way to pass variable values from Java to JavaScript without being vulnerable to XSS.
<details>
Only the "Passing values to JavaScript" was added.
</details>
=> Improve the XSS prevention page

content/_data/authors/jochenafuerbacher.adoc, content/_data/authors/pch-maintainers.adoc, content/_data/authors/robinrschulz.adoc, content/_data/authors/stefanbrausch.adoc, content/_ext/authorlist.rb, content/_ext/authorship.rb, content/_layouts/post.html.haml, content/blog/2019/07/2019-07-15-pipeline-config-history-plugin.adoc
As a follow-up to External Workspace Storage blogposts for GSoC in #2365 and #2366, we need to support multiple authors. So I tried implementing it here. In parallel I have fixed the post from @Jochen-A-Fuerbacher @stefanbrausch @RobinRSchulz which had a hack to support multiple authors. CC @zbynek who was the author of the original logic.
Probably we need to rework the author.html.haml to avoid duplicate headers, but it can be done in a follow-up IMHO
Screenshots:
=> Add support of multiple authors to the blogposts + fix the Pipeline Config History post

content/sigs/docs/index.adoc
Meeting notes are kept in a separate file, along with meeting recordings on YouTube channel.
=> Remove meeting notes from Docs SIG page

content/blog/2019/08/2019-08-23-introducing-gitlab-branch-source-plugin.adoc
The top level heading is causing error message in console of CI builds. Even though  these errors have no impact on the generated site, they make the log harder to read.
=> Change level of section title (minor markup fix)

content/events/hacktoberfest.adoc
After the change:
Unfortunately I cannot do a better layout with just Asciidoc, e.g. I cannot add Grid. The default styles seem to override the configurations in Awestruct. https://issues.jenkins-ci.org/browse/WEBSITE-656 for better defaults
=> Hacktoberfest 2019 - Add keywords to the featured projects

content/events/hacktoberfest.adoc, content/index.html.haml
Adds a new entry after DevOps World - Jenkins World and CDF slides
=> Hacktoberfest 2019 - Add a Jumbotron slide

content/security/advisory/2019-09-25.adoc
Lowercase "codescan" in https://jenkins.io/security/advisory/2019-09-25/ doesn't look great.
=> Use friendly label for CodeScan plugin (no longer published)

content/_data/changelogs/lts.yml
> <img width="1652" alt="Screenshot 2019-09-25 at 16 51 03" src="https://user-images.githubusercontent.com/1831569/65612534-bb3daf00-dfb4-11e9-86f7-295189c4f626.png">
An attempt to minimize confusion (no blog post today).
=> Add banner for 2.176.4

content/events/hacktoberfest.adoc, content/sigs/docs/index.adoc
Adds Plugin documentation and Plugin site as SIG projects + adds the GitHub plugin documentation as a featured project.
Screenshots:
Hacktoberfest page:
=> [Docs SIG] - Add plugin docs and plugin site as SIG projects + Hacktoberfest featured project

content/_data/changelogs/lts.yml, content/_data/changelogs/weekly.yml
We declare security fixes to be "Important" when at least one (core) vulnerability is severity "High" or "Critical". This wasn't the case last week.
Keep the label for 2.190.1, since it includes also the August advisory, in which there was such an issue.
=> Security fixes aren't severe enough to make 'Important'

content/css/jenkins.css, content/events/index.html.haml
My proposition to solve https://issues.jenkins-ci.org/browse/WEBSITE-660
Events start as collapsed, displaying only a few lines; clicking toggles the full text.
I have not managed to add a nice css transition because the box height is not fixed.
By clicking an item's teaser you switch from this...
...To this!
=> Hacktoberfest - Make the event teaser collapsable

content/blog/2019/10/2019-10-01-hacktoberfest.adoc, content/events/hacktoberfest.adoc
Just to simplify the search for Hacktoberfest issues...
Right now we have around 80 Hacktoberfest issues and also 200+ newbie-friendly ones, so it should be helful for those ones who look for issues outside featured projects
=> Hacktoberfest 2019: Add Hacktoberfest issue queries and the experienced developers section

content/events/hacktoberfest.adoc
fixed link to gitlab plugin
I'm not sure that this minor change qualifies for Hacktoberfest, but I found a dead link ;)
=> fixed link to gitlab

content/participate/code.adoc, content/participate/index.html.haml
Just started reworking the /participate/code page so that it looks less terrible. Still a lot to improve, but at least the change allows improving the situation and creating follow-up newbie-friendly tickets for Hacktoberfest
Also removed the Security team referece from /participate and moved it under /code . I consider it as a temporary solution until /participate is reworked
https://issues.jenkins-ci.org/browse/WEBSITE-666
Before:
After:
=> [WEBSITE-666] - Hacktoberfest: Update the /participate/code page

CONTRIBUTING.adoc, content/artwork/index.html.haml
Resolves [WEBSITE-671](https://issues.jenkins-ci.org/browse/WEBSITE-671).
**Summary**
- Moved `Adding a Logo` info from the artwork page to `CONTRIBUTING.adoc`
- Refer to `CONTRIBUTING.adoc` in the artwork page
=> Move Adding a Logo guideline in Artwork page to contributing guidelines

content/doc/developer/publishing/_chapter.yml, content/doc/developer/publishing/documentation.adoc, content/doc/developer/publishing/preparation.adoc, content/doc/developer/publishing/requesting-hosting.adoc, content/doc/developer/publishing/wiki-page.adoc
See https://issues.jenkins-ci.org/browse/WEBSITE-654
Wiki documentation will be replaced by a link once these docs are deployed
CC @MarkEWaite @zbynek @tracymiranda
=> [WEBSITE-654] - Move the plugin documentation hosting info from Wiki to jenkins.io

content/_data/upgrades/2-73-1.adoc
The current URL resolves to "https:/projects/remoting/", which is kind of working in browser, but does not look good to me. Looks like relative URLs do not resolve properly in changelogs.
=> Fix invalid URL in 2.73.1 changelog (Hacktoberfest 2019)

content/css/jenkins.css
I've found the paragraph text of the current docs very hard to read—I'm nearsighted and the 14px font-size really forces me to get close to see what I'm reading. Upping the size to 16px (or 1rem) is pretty standard for readability purposes, and improves site accessibility for the visually impaired. I also changed to color to a warm gray to give the paragraph text contrast from the headlines so everything is easily distinguishable at first glance.
=> Update default body styles

CONTRIBUTING.adoc, content/_ext/asciidocrender.rb, content/_ext/pipeline.rb, content/_layouts/post.html.haml, content/blog/2018/01/2018-01-17-jenkins-world-cfp-open.adoc, content/blog/2018/02/2018-02-22-cheetah.adoc, content/blog/2018/04/2018-04-25-configuring-jenkins-pipeline-with-yaml-file.adoc, content/blog/2018/07/2018-07-13-jenkins-user-conference-china.adoc.adoc, content/blog/2018/08/2018-08-17-speaker-blog-brent-laster.adoc, content/blog/2018/09/2018-09-11-speaker-blog-warnings-plugin.adoc, content/blog/2018/09/2018-09-12-2018-community-survey.adoc, content/blog/2018/09/2018-09-14-kubernetes-and-secret-agents.adoc, content/blog/2018/11/2018-11-12-inspecting-binaries-with-jenkins.adoc, content/blog/2019/01/2019-01-08-mpl-modular-pipeline-library.adoc, content/blog/2019/02/2019-02-06-ssh-steps-for-jenkins-pipeline.adoc, content/blog/2019/02/2019-02-26-jenkins-alexa-voice-controlled-cicd.adoc, content/blog/2019/03/2019-03-01-devops-world-jenkins-world-cfp-open.adoc, content/blog/2019/05/2019-05-09-templating-engine.adoc, content/blog/2019/09/2019-09-10-introducing-the-jira-software-plugin-for-jenkins.adoc
The goal of [the ticket](https://issues.jenkins-ci.org/browse/WEBSITE-206) is to hide the initial NOTE from guest posts in the blog roll.
One way to do that would be to make the "summary" function smarter and detect parts of content that are not relevant. This PR proposes a simpler solution where the disclaimer is moved to the metadata and is only rendered in full view of the article, not in blog roll.
This approach requires changing the content of the articles, it's done for posts from the last two years.
=> [WEBSITE-206] Move guest post disclaimer to the front matter

content/event-calendar.html.haml
At least in my browse the calendar widget from Google no longer shares the direct ICS link, but instead has an "Add to Google" button :disappointed:
=> Add a direct link to the .ics URL

content/event-calendar.html.haml
Missed this by not locally rendering this page with my previous patch. Oops
=> Haml is a funny thing

content/security/reporting.adoc
This hasn't affected any Jenkins release for more than a year
=> escape-by-default XSS is no longer a vulnerability

content/doc/developer/publishing/documentation.adoc, content/doc/developer/publishing/wiki-page.adoc
See https://issues.jenkins-ci.org/browse/WEBSITE-670 . This PR includes some documentation for the migration process
CC @MarkEWaite @zbynek
=> [WEBSITE-670] - Document how to Migrate plugin from Wiki to GitHub

content/_partials/toptoolbar.html.haml
Before this change any new page being added while using `make run` would
cause no page reload to be possible until `make run` was ran again.
This isn't a full fix as new pages won't show up till it's run, but it
means that you can iterate on other pages until you are ready to restart
it
Fixes this error:
=> Stop crash when new files are added

content/security/advisory/2019-10-16.adoc
This is correct in https://github.com/CVEProject/cvelist/blob/e92196fd4eae5e899de8bed7812ce727c38e68bb/2019/10xxx/CVE-2019-10450.json#L37 but was wrong in this advisory.
Score was correct, at least.
=> Correct the description of SECURITY-1434

content/doc/developer/publishing/wiki-page.adoc
Follow-up to the https://jenkins-wiki-exporter.g4v.dev/ service created by @halkeye
=> Document the Jenkins Wiki Exporter service for plugins

content/doc/book/installing/_docker-for-tutorials.adoc
An error ('The source path is not a valid path') is thrown when trying to use just the %HOMEPATH% environment variable. Use %HOMEDRIVE%%HOMEPATH% for the full path to that directory in Windows.
=> Fix windows home path

content/_layouts/developerbook.html.haml
Adds sections to the developer book to make it easier to discover other pages, navigate to the next section and not get lost
Before:
After:
=> Add sections to navigation in developerbook

content/_data/upgrades/2-190-1.adoc
Discovered by @MarkEWaite: Broken formatting on https://jenkins.io/doc/upgrade-guide/2.190/#upgrading-to-jenkins-lts-2-190-1
=> Fix formatting

content/doc/book/pipeline/syntax.adoc
When setting up a 'when' condition in a stage with an 'input' I found that the default behaviour was for the 'input' to run before the 'when' condition.  This document states that the default is the 'when' before the 'input'
This edit changes that logic
=> Correct the wording about 'when' before 'input'

content/doc/book/pipeline/syntax.adoc
couple fixes in syntax.adoc
before:
after:
=> fix syntax.adoc

content/doc/developer/publishing/continuous-integration.adoc
The recommended configuration builds a matrix of Jenkins versions and JDK to build the plugin against and validate its support.
=> Update plugin build process recommendation

content/doc/book/pipeline-as-code.adoc
Just wanting to make it clear that one can use "Pipeline as Code" (PaC) concept outside the context of a Multibranch Pipeline or Organizational Folders job. This tripped me up as I was learning about PaC.
=> Mention "Use SCM" option in normal Pipeline jobs in pipeline-as-code.adoc 

content/doc/developer/plugin-development/dependency-management.adoc
Updating ('downdating'?) minimum `plugin-pom` that contains the `use-jenkins-bom` profile to 3.52 as per comments in [jenkinsci/plugin-pom#/229](https://github.com/jenkinsci/plugin-pom/pull/229#discussion_r344701162).
=> Correct min plugin-pom version for use-jenkins-bom profile

content/_layouts/frame.html.haml
This change replaces the obsolete "solutions" column in order to inject more meaningful information for users and contributors. Solutions are generally not maintained well, and I doubt we should keep it in spotlight. We have them in the navigation bar anyway
The footer has been also made shorter by this change
Before:
After:
=> Rework the jenkins.io footer links for better navigation

content/blog/2015/2015-11-01-adopt-a-plugin.md, content/blog/2015/2015-11-16-celebrating-hacksgiving.md, content/blog/2017/08/2017-08-23-pull-requests-and-more.adoc, content/blog/2019/04/2019-04-03-security-advisory.adoc, content/doc/developer/_book.yml, content/doc/developer/plugin-governance/_chapter.yml, content/doc/developer/plugin-governance/adopt-a-plugin.adoc, content/doc/developer/plugin-governance/index.adoc, content/participate/code.adoc, content/projects/gsoc/gsoc2018-project-ideas.adoc, content/projects/gsoc/proposing-project-ideas.adoc
First step in reworking the plugin adoption documentation.
See https://groups.google.com/forum/#!topic/jenkinsci-dev/UoEqG5AaWJU for the context
=> [WEBSITE-676] - Move "Adopt a plugin" from Wiki to jenkins.io

content/doc/index.adoc, content/solutions/index.html.haml
Just a stub page for the list of solutions. We can use this stub in order to reference all solution pages at once. Looks terrible at the moment, but better than nothing IMHO
=> Introduce a listing of solution pages

content/_layouts/frame.html.haml, content/project/index.adoc
For better transparency, it would be great to have a landing page which lists the current project structure and links to other related pages. This pull requests adds such page and also adds a link to it in the global jenkins.io footer
=> Add a page for Jenkins structure and governance

content/projects/infrastructure/index.adoc
This change splits the list of services to 3 categories: self-hosted, SaaS, and also sub-project/SIG services hosted by the project. Some links are fixed, and I have also added JIRA component IDs. But I did not add other services to the list yet, some of them are missing. 
P.S: Tables on jenkins.io are just ugly, we need to update CSS IMHO
Before:
After:
=> Jenkins Infra: Rework the services list

content/participate/design.adoc, content/participate/document.adoc, content/participate/help.adoc, content/participate/review-changes.adoc, content/participate/test.adoc
Not all pages are fully finished at the moment, and some pages need serious updates. This pull request does some minor cleanup, fixes labels for blogposts, and adds disclaimers for pages which have not been updated yet.
Sample:
CC @MarkEWaite @urwa
=> [WEBSITE-662] - Cleanup jenkins.io/participate pages and tags, add WIP warnings for pages which are not complete yet

CONTRIBUTING.adoc, content/doc/developer/publishing/wiki-page.adoc
Now we can use https://jenkins-wiki-exporter.jenkins.io/ for any Wiki page, so let's simplify the guidelines
Fixes https://issues.jenkins-ci.org/browse/INFRA-2337
CC @halkeye @zbynek @timja
=> [INFRA-2337] - Update Wiki export guidelines in CONTRIBUTING to reference Jenkins Wiki exporter

content/doc/administration/requirements/web-browsers.adoc
This change moves the document to jenkins.io. The policy is obsolete. https://groups.google.com/forum/#!topic/jenkinsci-dev/TV_pLEah9B4 was created to discuss the changes
=> Move the Browser compatibility policy from Wiki to GitHub

CONTRIBUTING.adoc, content/participate/index.html.haml
Submitting the PR to get feedback about the change feasibility. The idea is to have https://gitter.im/jenkinsci/newcomer-contributors linked from few places where we have the most of the newcomer traffic
=> Reference contributing assistance channels in jenkins.io/participate and CONTRIBUTING.adoc

content/participate/review-changes.adoc
Before:
* Links to not show the relevant content
* Links require authentication and GitHub org membership
Now:
* Anyone can see the pull requests in the links, they are more or less relevant
* More content
=> [WEBSITE-683] - Revamp the participate/review-changes page

.github/CODEOWNERS
Apparently it does not work due to whatever reason
=> Fix CODEOWNERS for GSoC entries

content/sigs/platform/index.adoc
* Old meeting notes are in the meeting notes file, not needed on the page
* Remove completed projects from ongoing projects list
* Minor phrasing improvement
=> Remove outdated info from Platform SIG page

content/chat.adoc
CC @timja , follow-up to the https://issues.jenkins-ci.org/browse/INFRA-2346 investigation.
BotBotMe is defunct, see https://lincolnloop.com/blog/saying-goodbye-botbotme/
=> Chat page: remove botbotme, link the project infrastructure

content/_ext/validator.rb, content/_layouts/frame.html.haml, content/template.html.haml
See https://issues.jenkins-ci.org/browse/WEBSITE-405 and https://gitter.im/jenkinsci/docs?at=5ddaf97ec52bc74c9685740f
To use this the plugin site can download `jenkins.io/template` instead of `jenkins.io/plugins`, the latter can be removed after the switch.
CC @timja @halkeye
=> [WEBSITE-405] Plugin site: configurable title, description and OG image

content/_partials/osx-brew-installer.html.haml
I've installed Jenkins for MacOS with https://jenkins.io/download/lts/macos/.
After `$ brew services start jenkins-lts` there was no information about access to the service.
Proposal:
Pick up No. 4 and 5 from https://jenkins.io/doc/pipeline/tour/getting-started/#download-and-run-jenkins for MacOS users
=> Add the instruction after Installation for MacOS

content/projects/gsoc/2020/project-ideas.html.haml, content/projects/gsoc/proposing-project-ideas.adoc, content/projects/gsoc/students.adoc
These are the changes I am proposing to the GSoC 2020 process. I think this makes things simpler.
* Provide a template for student proposals
* Simplify the idea proposal submission process
* In this simpler process, project ideas are submitted in the mailing list
* if they get a positive feedback, the champion creates pull-request
* we no longer track them in the google table like in 2019
* there are no "states", we simply review the idea proposal in the mailing list and in the pull-request
=> GSoC 2020 process simplifications for students and project ideas

content/projects/gsoc/2020/project-ideas.html.haml, content/projects/gsoc/proposing-project-ideas.adoc, content/projects/gsoc/students.adoc
This is to replace #2690 . I suggest we show what a template for a project idea looks like. Maybe this is overkill as people can read the adoc from github directly. Either way, I don't have a strong opinion.
I also fixed a couple of typos and made minor fixes.
=> Proposing a GSoC project idea template and small fixes

content/blog/2012/2012-09-24-jenkins-project-meeting-in-the-meat-space-call-for-agenda.md, content/project/governance-meeting/archives/2011.adoc, content/project/governance-meeting/archives/2012.adoc, content/project/governance-meeting/archives/2013.adoc, content/project/governance-meeting/archives/2014.adoc, content/project/governance-meeting/archives/2015.adoc, content/project/governance-meeting/archives/2016.adoc, content/project/governance-meeting/archives/2017.adoc, content/project/governance-meeting/archives/2018.adoc, content/project/governance-meeting/archives/2019.adoc, content/project/governance-meeting/index.adoc, content/project/governance.adoc, content/project/index.adoc
https://issues.jenkins-ci.org/browse/WEBSITE-700
=> [WEBSITE-700] - Move the Governance Meeting agenda to jenkins.io and Google Docs

content/doc/pipeline/tour/getting-started.adoc
When I tried to boot Jenkins with Java 13, I got the error message below.
Jenkins requires Java versions [8, 11]
When I tried to boot Jenkins with Java 11, there were no error messages.
But, the following documents are written only about Java 8. So I added Java 11 as well.
https://jenkins.io/doc/pipeline/tour/getting-started/
=> Modify the Java version.

content/doc/developer/publishing/documentation.adoc
The list of valid formats explains how to use the URL to load any branch or tag of a readme file.
See also https://issues.jenkins-ci.org/browse/WEBSITE-641
=> [WEBSITE-641] Specify valid formats for GitHub documentation

content/doc/book/installing/_docker-for-tutorials.adoc, content/doc/book/installing/_docker.adoc, content/doc/book/installing/_setup-wizard-for-tutorials.adoc
This improves the installation manual for Docker to use a separate Docker daemon rather than running Jenkins as the root user.
I've also updated the various uses of the `docker` CLI to use the longer form of commands to be more consistent.
@daniel-beck @jeffret-b @Wadeck
=> Update Docker install to use DinD

content/_layouts/documentation.html.haml
The 'Handbook' heading should be above the Handbook contents in the table of contents so that it matches with the tutorial section that precedes it and the resources section that follows it.
The tutorials header is easier to read as a single line rather than two lines.
=> [WEBSITE-706] Restore 'Handbook' heading to TOC

content/doc/administration/requirements/jenkins-on-java-11.adoc, content/doc/administration/requirements/upgrade-java-guidelines.adoc
Java 11 support has been available long enough that we can remove the February 2019 disclaimer.  Simpler to discuss the Java 11 support as a "given".
=> Remove Feb 2019 disclaimers on Java 11 LTS support

content/sigs/docs/index.adoc, content/sigs/platform/index.adoc
Consistent with other uses of embedded Google documents and easier for contirbutors to find them and help with them.
=> Embed Platform and Docs SIG meeting agendas

content/donate.adoc
This pull request updates the donations status, as discussed with the Jenkins Board and @tracymiranda in the Governance mailing list. See [INFRA-2396](https://issues.jenkins-ci.org/browse/INFRA-2396) for the EPIC which summarizes this discussion.
I will start the discussion in the dev list about the next steps. This is rather an immediate actions to turn off the broken documentation which may mislead users.
Changes summary:
=> [WEBSITE-702] - Update the donations status on the jenkins.io/donate page

content/doc/pipeline/tour/hello-world.adoc
the docker image name is "golang" and not "go" (https://hub.docker.com/_/golang)
=> fix golang image name in scripted pipeline example

content/blog/2020/01/2020-01-07-happy-new-year.adoc
Cleaning up text. Also, I have changed the link to Jenkins UX SIG so that it leads participants to the new page. Thanks @jphartley !
=> NY2020 Blog post - Link updates and copy-edits

content/projects/gsoc/2020/application.md
When Jenkins applies to Google for the Google Summer of Code project, we must list the organization under which we operate. Since we are transitioning to CDF, I thought we might want to list it.
@tracymiranda
=> Add CDF to the submission

content/doc/developer/cli/writing-cli-commands.adoc
Cause: noticed this typo in "How-To Guides" page in https://jenkins.io/doc/developer/guides/
=> Fix typo 'commannds' to 'commands'

content/blog/2017/08/2017-08-11-remoting-update.adoc
This update is needed, because the guidelines are linked from administrative monitors.
CC @jeffret-b @Wadeck @MarkEWaite
=> [JENKINS-60381] - Update the Remoting protocol deprecation announcement

content/press.adoc, content/projects/blueocean/about/index.adoc, content/projects/blueocean/contribute/index.adoc, content/projects/blueocean/index.html.haml
Blue Ocean overview consumes more than 50% of the page due to screenshots and embedded video. Taking the current status and https://groups.google.com/forum/#!msg/jenkinsci-dev/zO9VFNxhF-o/EpjdA8-jCgAJ from @jphartley, I believe we do not want to have this information on the page at all.
This change introduces a new "Overview" page inside the Blue Ocean Folder and moves all the content there. 
CC @i386 @slide @uhafner @rtyler @kohsuke (the page is within the governance space)
=> Remove Blue Ocean Information from the Press landing page

scripts/awestruct
Syntax problems reported as ERRORs don't break the build, but WARNINGs do. So the only way to detect ERROR (e.g. the one fixed in #2717) is to introduce a WARNING (as I did in the first commit of #2716).
This PR makes sure both are handled the same way.
=> Fail build on Asciidoctor errors

content/press.adoc
Press often misuses the trademark when writing about Jenkins (e.g. google for "Apache Jenkins"). Wishful thinking, but maybe an explicit trademark section will help a bit.
Also referenced CDF since it is not mentioned on the press page ATM
=> Press - Add explicit section about trademarks + reference CDF

content/projects/gsoc/2020/application.md
Jenkins X is no longer a sub-project of Jenkins, it graduated to a separate project under the CDF umbrella. As agreed with @MarckK, Jenkins X project plans to participate as a part of the Jenkins organization this year. Once we receive and publish project idea drafts, the text will need to be updated again to reference Jenkins X as a sister-project (or whatever it is called).
=> [GSoC 2020] - Application: Jenkins X is no longer a Jenkins sub-project

content/projects/gsoc/2020/project-ideas/winsw-yaml-config-support.adoc
I moved the description to Asciidoc and added `Quick start`, `Special requirements` and `Newbie-friendly issues`. I believe it is enough to get the project idea published as a final idea. 
CC @arnab1896 @slide
=> GSoC 2020 - Move the Windows services project idea to Asciidoc && publish it

content/doc/book/installing/_docker-for-tutorials.adoc, content/doc/tutorials/build-a-node-js-and-react-app-with-npm.adoc
Hi, I followed the [Build a Node.js and React app with npm tutorial](https://jenkins.io/doc/tutorials/build-a-node-js-and-react-app-with-npm/), and I got stuck in the delivering stage when trying to access localhost:3000 for the loaded React app.
This took me quite sometime to figure out that I have to expose the 3000 port when start up the docker:dind image.
This is a draft PR since the adoc is used for multiple tutorials and I'm not sure how to make it DRY.
Is there a mechanism in asciidoctor that let you include a doc with parameters?
=> Build a Node.js and React app with npm tutorial fix.

content/_data/authors/fcojfernandez.adoc, content/projects/gsoc/2020/project-ideas/git-plugin-caching.adoc, content/projects/gsoc/2020/project-ideas/git-plugin-performance.adoc
Proposes two project ideas for the git plugin, one for general performance improvements, the other for repository caching on agents.
I was surprised that all my edits to the adoc file were ignored when I viewed the page from `make run`. I applied the adoc changes to the Google docs so that reviewers can comment in either location.
=> Add GSoC 2020 project ideas for git plugin

content/_layouts/gsocprojectidea.html.haml
GSoC 2019 process was focused on Google Doc drafts, and YAML ones are not rendered correctly. This pull request fixes that and also adds a better notice for draft project ideas to clarify what they mean.
CC @MarkEWaite @sladyn98 whose ideas are affected
=> GSoC 2020 - Add support of publishing YAML project ideas as drafts + better draft notice

content/doc/developer/architecture/web.adoc
Cause: there cannot be "is" and "are" in one place.
=> Fix typo in web.adoc related to "to be" form

content/doc/developer/publishing/documentation.adoc
A table of contents helps with navigation of large documentation pages.  This pull request guides the author to create a table of contents that is automatically maintained.
=> Add table of contents example to plugin docs guide

content/doc/developer/tutorial/extend.adoc
**Cause:** grave accent expansion works incorrectly due to leading 's' character
**Picture:**
**Proposed solution:** delete leading 's' character to fix grave accent expansion
=> Fix grave accent expansion in extend.adoc

content/_partials/mailing-lists/jenkinsci-jam.adoc, content/mailing-lists/index.html.haml
Implements the proposal from https://groups.google.com/forum/#!msg/jenkinsci-dev/cviU5XUX8vQ/-c9uSe-PCgAJ
CC @alyssat
=> [WEBSITE-714] - Replace JAM and Event mailing lists by Advocacy&Outreach SIG

content/chat.adoc, content/mailing-lists/index.html.haml
We moved out of IRC in the case of the community channel. Jenkins Meeting included obsolete link
Depends on #2789 (because I messed up the branch)
=> Chats: Remove #jenkins-community, update #jenkins-meeting links

content/_ext/authorship.rb, content/projects/gsoc/2020/project-ideas.html.haml, content/projects/gsoc/2020/project-ideas/artifactory-rest-plugin.adoc, content/projects/gsoc/2020/project-ideas/automatic-spec-generator-for-jenkins-rest-api.adoc, content/projects/gsoc/2020/project-ideas/bitbucket-rest-plugin.adoc, content/projects/gsoc/2020/project-ideas/eda-coverage-adapters.adoc, content/projects/gsoc/2020/project-ideas/eda-plugins.adoc, content/projects/gsoc/2020/project-ideas/jenkins-rest-plugin.adoc, content/projects/gsoc/2020/project-ideas/pipeline-step-documentation-generator.adoc
As announced, I am not able to mentor in 2020. I am removing my name from the project ideas, and replacing with "TBD" on projects where I am the sole mentor. I also suggest a new mentor display method in authorship.rb: `display_user_no_fail`.
If you prefer, I can remove those project ideas from the list.
CC @jenkins-infra/gsoc
=> Withdrawing my name from GSoC projects

content/projects/gsoc/2020/project-ideas/winsw-yaml-config-support.adoc
Removing myself as mostly focus will be on overall progress of all projects while helping admins rather than mentoring a specific project
=> Remove arnab as mentor for Windows YAML project

content/_data/upgrades/2-204-2.adoc
AFAICT there is no changes requiring upgrade guidelines in https://issues.jenkins-ci.org/issues/?jql=labels%20%3D%202.204.2-fixed
=> Add upgrade guideline stub for Jenkins 2.204.2 LTS

content/events/index.html.haml, content/projects/infrastructure/index.adoc
Moved from 15:00 UTC to 16:30 UTC Dec 2019.
Olivier Vernin, can you confirm this update is correct?
=> Update infra meeting time

content/index.html.haml
Just because they do not sponsor us....
CC @jenkins-infra/board
=> Remove Azure and Rackspace from the sponsors list on the front page

content/_data/authors/XiongKezhi.adoc, content/doc/developer/tutorial/prepare.adoc
Move https://wiki.jenkins.io/display/JENKINS/Plugin+tutorial#Plugintutorial-SettingupaproductiveenvironmentwithyourIDE to https://jenkins.io/doc/developer/tutorial/prepare/ without any changes.
=> Add plugin tutorial with ide settings

content/projects/gsoc/2020/project-ideas/plugin-installation-manager-tool.adoc
@jenkins-infra/gsoc 
This is the proposal for further improvements to the plugin installation manager tool.  The Google doc draft was discussed on the plugin installation manager tool gitter channel and changes/suggestions have been merged in.  Pending review.
=> Create Plugin Installation Manager Tool GSoC proposal

content/_data/solutions/c.yml, content/_data/solutions/pipeline.yml, content/_data/upgrades/2-7-1.adoc, content/_partials/changelog-old.html, content/blog/2010/2010-02-08-incoming-more-translations.md, content/blog/2010/2010-02-11-spotlight-on-ita-software.md, content/blog/2010/2010-02-12-this-week-in-plugins.md, content/blog/2010/2010-02-17-getting-started-building-android-apps-with-hudson.md, content/blog/2010/2010-02-19-this-week-in-plugins.md, content/doc/developer/publishing/wiki-page.adoc
Removes the wiki page creation instructions from the developer document, since plugin creators cannot create a wiki page any longer.
Also includes the beginning of replacement of many references from jenkins.io to wiki.jenkins.io.  The pattern matching is not that hard, but it does accept that we're changing existing blog posts so that they point to current pages.
I'm also OK if the consensus is to not make these types of changes but rather to keep the wiki around long term.
=> Remove wiki page creation instructions

content/projects/gsoc/2020/project-ideas/automatic-spec-generator-for-jenkins-rest-api.adoc
A minor fix for the bullet list in the GSoC automatic spec generator idea.
CC @kwhetstone @jenkins-infra/gsoc
=> Fix the list in automatic spec generator idea

content/redirect/dns-multicast.adoc, content/redirect/udp-broadcast.adoc
These URLs are used in https://github.com/jenkinsci/jenkins/pull/4460 and that will be in 2.220.
I added a warning to the wiki page at https://wiki.jenkins.io/display/JENKINS/Auto-discovering+Jenkins+on+the+network and so that URL is probably the best target for these redirects while there's no LTS upgrade guide with more specific information.
=> Add redirect URLs for removed network discovery features

content/doc/book/managing/script-console.adoc
Imported and modernised from:
https://wiki.jenkins.io/display/JENKINS/Jenkins+Script+Console
Removed csrf work-arounds and just mentioned use API token, (I wasn't even able to get providing a CSRF token working using the docs on the wiki)
Not sure if we want the huge list of wiki scripts to stay around, there's plenty of other sources i.e. scriptler that are probably better.
=> Add script console section

content/_data/changelogs/weekly.yml
The JENKINS-60926 issue reference was missed for the remoting regression fix on the agent installer for Windows.
=> Include issue id in changelog references section

content/pipeline/getting-started-pipelines.adoc
Starting single quote missing in example script.
=> Fixed missing single quote in example.

content/_data/authors/jochenafuerbacher.adoc, content/_data/authors/robinrschulz.adoc, content/_data/authors/stefanbrausch.adoc
This PR corrects some typos in the blog authors descriptions of @stefanbrausch, @RobinRSchulz and me.
=> Fix typos in authors descriptions

content/projects/gsoc/mentors.adoc
http://localhost:4242/projects/gsoc/#orgadmin -> /projects/gsoc/#orgadmin
=> docs(mentors.adoc): fix link to contact Org Admins

content/projects/gsoc/2020/project-ideas/external-fingerprint-storage-for-jenkins.adoc
I have added the Quick Start guide to the project idea. Taking #2858 , we can now publish it even if it embeds a Google Doc
=> GSoC 2020 - Publish the External Fingerprint storage project idea

content/_data/changelogs/weekly.yml
Just improves the visibility a bit. CC @basil @jeffret-b 
https://github.com/jenkinsci/jenkins/pull/4460 also includes appropriate upgrade guidelines for LTS
=> Jenkins 2.220 changelog: Add a banner warning for Swarm Plugin users

content/_data/authors/nehagup.adoc, content/projects/gsoc/2020/project-ideas/jenkins-x-apps-consolidation.adoc, content/projects/gsoc/2020/project-ideas/jenkins-x-boot-apps.adoc
CC @MarckK @jstrachan @markyjackson-taulia . It redirects the conversations to Jenkins X channels. I also fixed visualization for @nehagup on the project ideas list while I was around. In mid-2019 the GSoC metadata was merged into `authors` on jenkins.io, and hence now we need to create author profiles to have a better visualization of users
=> GSoC 2020 - Fix JX chat links and add a profile for @nehagup 

content/projects/gsoc/2020/project-ideas/eda-coverage-adapters.adoc
I have reviewed an expanded the Google doc for this year, it is up to date. Also, I expanded the quick start guide to set more explicit expectations about the project
See https://docs.google.com/document/d/1pW9cSPTSekhMirHWKGnchmsDGsGLeN8MBEpMyN9HDEo
=> GSoC 2020 - Publish the EDA coverage project idea

content/sigs/ux/index.adoc
=> Add a Gitter channel reference to the UX SIG metadata

content/projects/gsoc/2020/project-ideas/pipeline-as-yaml-experiment.adoc
The project idea matches the criteria for publishing, so I doubt it makes sense to keep it in the draft state.
=> GSoC 2020 - Publish the Pipeline as YAML project idea

content/projects/gsoc/proposing-project-ideas.adoc
I decided to clarify that Google Docs are allowed when submitting project ideas, and provided additional information on how to format the `.adoc` project idea files.
This PR is not urgent.
=> Clarify use of Google Docs for GSoC projec ideas

content/_data/changelogs/weekly.yml
The 2.221 release **did not** include the following items which were listed in the original 2.221 changelog:
* New permission Overall/Manage - JEP-223, [PR-4501](https://github.com/jenkinsci/jenkins/pull/4501)
* Memory usage monitor in system info page - [PR-4499](https://github.com/jenkinsci/jenkins/pull/4499)
* Allow plugins to force an update of UpdateCenter - [PR-4488](https://github.com/jenkinsci/jenkins/pull/4488)
* Admin monitors sorted in global config page - [PR-4487](https://github.com/jenkinsci/jenkins/pull/4487)
* Tied job loading performance improvement - [PR-4497](https://github.com/jenkinsci/jenkins/pull/4497)
Thanks to @mikecirioli for detecting the mistake in my original changelog submission!
=> Remove incorrect entries from 2.221 changelog

content/events/index.html.haml, content/sigs/docs/index.adoc
Meeting every two weeks is not making the documentation work faster or slower.  We'll meet every 4 weeks and continue the same pace.  Special thanks to Gavin Mogan, Tim Jacomb, Zbynek Konecny, and Oleg Nenashev.
=> Docs SIG now meets every 4 weeks
