jenkins-infra/jenkins.io

- TYPES.adoc
Still a work in progress, but something we can start to discuss
See <https://issues.jenkins-ci.org/browse/WEBSITE-21>
> Start adding some content types for the new site

- ROADMAP.adoc
See also: https://issues.jenkins-ci.org/browse/WEBSITE-39
> Add a first cut at a roadmap

- content/_ext/pipeline.rb
- content/_ext/versionswitcher.rb
- content/solutions/docker.html.haml
> When operating in legacy mode, legacy pages should just redirect to home

- content/100k.adoc
> Move the /100k redirect into the site structure

- content/_ext/pipeline.rb
- content/template.atom.haml
The built-in awestruct template appears to be wrong in this regard
Proposed fix upstream: https://github.com/awestruct/awestruct/pull/503
> Ensure we're not generating invalid XML in our RSS feed

- content/_partials/download.html.haml
The destination pages are still a little wonky, I'll be addressing that next in a subsequent pull request
Fixes [WEBSITE-65](https://issues.jenkins-ci.org/browse/WEBSITE-65)
> Correct the download links in the legacy sidebar

- content/css/download.css
https://www.dropbox.com/s/sqrpfgtbe4fd0bx/Screenshot%202016-01-06%2020.03.02.png?dl=0
> To fix download tab under safari

- content/_partials/download.html.haml
> Use the correct, sphere with horns, icon for FreeBSD

- content/blog/2016/2016-01-07-official-code-of-conduct.adoc
cc @jenkins-infra/copy-editors
> Add a blog post introducing the official code of conduct

- content/blog/2015/2015-12-18-december-jam-world-tour-st-petersburg-russia.md
Continuing my experiments with a better template for meetup talk summaries.
> [SPb JAM] Edit the list of presentations, add more info

- content/_partials/blogs.html.haml
- content/blog/2012/2012-05-10-jenkins-user-conference-paris-summary.html
- content/blog/2014/2014-04-24-juc-agenda-posted.html
- content/blog/2014/2014-06-20-juc-boston-what-a-day.html
- content/blog/2014/2014-07-03-juc-berlin-summary.html
- content/blog/2014/2014-07-08-workflow-plugin-tutorial-writing-a-step-impl.html
- content/blog/2014/2014-08-12-jenkins-user-meet-up-in-london.html
- content/blog/2014/2014-08-12-official-jenkins-lts-docker-image.html
- content/blog/2014/2014-08-28-workflow-plugin-code-walk-through.md
- content/blog/2014/2014-09-02-jenkins-user-meet-up-in-paris.html
- content/blog/2014/2014-09-17-jenkins-workflow-summit-rsvp.html
- content/blog/2014/2014-12-03-workflow-plugin-is-1-0.md
- content/blog/2015/2015-01-27-office-hours-tomorrow-workflow-security-model-and-plugin-compatibility.html
- content/blog/2015/2015-05-18-juc-speaker-blog-series-andrew-bayer-juc-europe.html
- content/blog/2015/2015-08-10-upcoming-office-hour-on-workflow.md
- content/blog/2015/2015-08-20-upcoming-office-hour-on-kubernetes.md
- content/blog/2015/2015-09-03-jenkins-user-conference-west-day-1.html
- content/blog/2015/2015-09-29-gui-improvements-on-the-horizon.html
- content/blog/2015/2015-09-30-bay-area-jam.html
- content/blog/2015/2015-10-02-winners-of-docker-global-hack-day-3-are.html
- content/blog/2015/2015-10-28-jenkins-2-0-proposal-pipeline-as-code-front-and-center.md
- content/blog/2015/2015-12-02-hacksgiving-left-overs.md
- content/blog/2015/2015-12-03-pipeline-as-code-with-multibranch-workflows-in-jenkins.md
- content/blog/2015/2015-12-16-workflow-best-practices-and-examples-repo-on-github.md
- content/blog/2015/2015-12-21-december-jam-world-tour-toulouse-france.md
- content/solutions/docker.html.haml
Some minor updates, primarily to the beta site to help with some of @gusreiber's work
> Monday minor fixes

- content/blog/2016/2016-01-10-beautiful-jenkins-dashboard.adoc
I'd also remove the sentence "But I cannot do that with the existing built-in dashboards from Jenkins
plugins which are Jenkins-content specific." as I find it's redundant and a bit awkward...
> Copy editing for the dashing-js blog post.

- content/_data/authors/kj187.adoc
- content/blog/2016/2016-01-10-beautiful-jenkins-dashboard.adoc
I just updated my author profile and the author note with a link to my employer who gave me the inspiration and some time to build this awseome stuff.
> Dashing post update

- content/content/mailing-lists/index.md
Still many emails sent to dev instead of users ML. So adding bold text
here and there to try and lower that number.
> Make the ML choice hopefully more visible

- content/_partials/news.html.haml
- content/_partials/plugins.html.haml
- content/solutions/android.html.haml
- content/solutions/c.html.haml
- content/solutions/docker.html.haml
- content/solutions/java.html.haml
- content/solutions/pipeline.html.haml
- content/solutions/python.html.haml
See also [EVENTS-18](https://issues.jenkins-ci.org/browse/EVENTS-18)
> Solution page stubs

- content/blog/2015/2015-12-21-december-jam-world-tour-toulouse-france.md
Quality video for screen capture is not great. It's weirdly "vibrating",
we're currently investigating as to why (this is not our first recording,
but first time we have this issue...).
> Videos published, blog updated with links

- content/blog/2016/2016-02-06-scale14x-conference-report.adoc
Please take a look when able @jenkins-infra/copy-editors
> Add a conference report from SCaLE 14x

- CONTRIBUTING.adoc
- content/_ext/solutionpage.rb
- content/_partials/toptoolbar.html.haml
- content/solutions/embedded.html.haml
> [WEBSITE-95] - Embedded solutions page

- content/_ext/solutionpage.rb
- content/solutions/embedded.html.haml
Passing over to @oleg-nenashev to take a look at
> Clean up some of the phrasing on the embedded solutions page

- content/solutions/pipeline.html.haml
Thanks to @oleg-nenashev for catching this
> Clean up some layout glitches for the 'Continuous Delivery' page the new site

- content/blog/2015/2015-12-03-pipeline-as-code-with-multibranch-workflows-in-jenkins.md
Added a requirement to register GH webhook with Jenkins for branch indexing to work.
> Updated blog

- .gitignore
...because I'm using Intellij to write blog posts, as ridiculous as that sounds. =)
> Ignore intellij

- content/blog/2016/2016-02-19-january-2016-sf-jam.adoc
> Adding blog post on SF Jan 2016 JAM

- CONTRIBUTING.adoc
- build.gradle
I'm too lazy to remember these commands.
> Added targets that CONTRIBUTING.md talks about

- content/blog/2016/2016-02-24-jenkins-security-update.md
**DO NOT MERGE** before Wednesday afternoon (or whenever we publish the bits and advisory).
> Blog post for security update

- content/_partials/toptoolbar.html.haml
- content/css/jenkins.css
This set of changes really makes the site more useful and removes some experimental ideas that we have not yet executed on.
> Removing some experimental bits from the new site layout

- content/css/jenkins.css
This (IMO) makes the home page a bit cleaner and less visually "busy"
> Remove a home page gradients/box shadows

- content/2.0.html.haml
Unfortunately, the line breaks, but IMO not a major problem.
> Add Docker to preview downloads

- content/_data/authors/batmat.adoc
- content/blog/2016/2016-03-02-toulousejam-hackergarten.adoc
Planned for March, 9th.
http://www.meetup.com/fr-FR/Toulouse-Jenkins-Area-Meetup/events/228709190/
as a placeholder, (actual registration are handled in
http://www.meetup.com/fr-FR/Toulouse-Java-User-Group/events/228708579)
> New french article for hackergarten in Toulouse

- content/2.0.html.haml
This set of changes subsumes #111 with better formatted, linking and rebases it atop the latest `HEAD` which contained some of @daniel-beck's changes to the page.
> Tweaked 2.0 page to incorporate more updates/feedback

- content/_data/authors/fdechery.adoc
- content/blog/2016/2016-03-15-jenkins-certification.adoc
> Copy-edited version of @fdechery's guest post

- content/_layouts/post.html.haml
- content/_partials/blogcardlist.html.haml
- content/_partials/blogs.html.haml
- content/_partials/toptoolbar.html.haml
- content/node/index.html.haml
> Clean up the Jenkins blog home page layout

- content/_ext/atom.xml.haml
Fixes [WEBSITE-135](https://issues.jenkins-ci.org/browse/WEBSITE-135)
> Avoid including non "posts" in the news feed

- CONTRIBUTING.adoc
As requested by @oleg-nenashev 
Fixes [WEBSITE-137](https://issues.jenkins-ci.org/browse/WEBSITE-137)
> Add some more contributing details to help new doc contributors

- content/changelog-stable/index.html
Super exciting update :grin:
https://issues.jenkins-ci.org/issues/?jql=labels%20%3D%201.642.3-fixed
https://github.com/jenkinsci/jenkins/compare/jenkins-1.642.2...jenkins-1.642.3
> Add changelog for 1.642.3

- content/_layouts/post.html.haml
- content/_partials/featurelist.html.haml
- content/_partials/jumbotron.html.haml
- content/_partials/toptoolbar.html.haml
- content/css/jenkins.css
- content/index.html.haml
> [FIX WEBSITE-134]  widening but constraining horizontal events (1 line title/3 line teaser) (part 1)

- content/blog/2016/2016-03-18-jenkins-20-test-fest.adoc
Also adds the Jenkins 2.0 link
CC @omehegan
> Add JIRA open issue list query to the test fest blog post

- content/_layouts/refresh.html.haml
Fixes [WEBSITE-142](https://issues.jenkins-ci.org/browse/WEBSITE-142)
> Properly redirect in all browsers, and provide a clickable link too

- .gitignore
- build.gradle
- content/_config/site.yml
- content/doc/pipeline/index.adoc
Addressed some of the comments I left for @PaddyOH in #148.
This pull request subsumes that PR
> Modified Pipeline docs a bit

- content/css/jenkins.css
Removes the boxes in the box for the Getting Started section.
> Deboxify getting started box

- content/_partials/carousel.html.haml
- content/css/jenkins.css
> High z-index for cta download button

- content/css/jenkins.css
- content/index.html.haml
> update blog list on homepage to match new style, make full width

- content/css/jenkins.css
> Use header blue with footer and font weights to differentate headings

- content/_partials/carousel.html.haml
- content/css/jenkins.css
This download button was floating above the banner earlier.
Now it is fixed.
> Download button is now at the right place.

- content/_partials/downloadbanner.html.haml
Great catch by @kzantow
Fixes [WEBSITE-140](https://issues.jenkins-ci.org/browse/WEBSITE-140)
> Use the correct DOM element when figuring the target for popovers

- content/css/jenkins.css
> align jumbo child elements with block

- content/doc/pipeline/jenkinsfile.adoc
I dug this out of @PaddyOH's GitHub branches since I believe GitHub Desktop confused him about what was in a branch (this) versus what was already submitted as part of a pull request.
Either way, this should knock out [WEBSITE-128](https://issues.jenkins-ci.org/browse/WEBSITE-128)
> First draft of Getting started with Jenkinsfile

- content/_layouts/default.html.haml
- content/_partials/jumbotron.html.haml
- content/css/jenkins.css
- content/index.html.haml
Makes the jumbotron a bit wider on larger screens but reduces the button width. Updated some messaging.
> Update jumbotron and button

- README.adoc
Linking to the newly live site.
@reviewbybees
> Switching URLs to jenkins.io

- content/_config/site.yml
@reviewbybees, specially @rtyler
> Updated base_url

- content/_partials/downloadlist.html.haml
@reviewbybees, specially @rtyler
> Wrong markup for the download button label

- content/2.0.html.haml
Looks better if the screen shots are not as wide as the surrounding text, and centered.
> ![screen shot](https://cloud.githubusercontent.com/assets/1831569/14036558/5e0d26f0-f23a-11e5-9785-f68bb2859bff.png)
> Minor tweaks to 2.0 page images, remove 'More changes coming'

- content/2.0.html.haml
* Fix description for tabs
* Also resize and align that screenshot
> Fixes for 2.0 configuration section

- content/_partials/downloadlist.html.haml
- content/css/jenkins.css
> Overlapping of download button is prevented for mobile and download buttons are now aligned.

- content/_partials/toptoolbar.html.haml
- content/security.adoc
Fixes [WEBSITE-106](https://issues.jenkins-ci.org/browse/WEBSITE-106)
> Introduce a "Security" page which can be linked from the top-nav

- content/blog/2016/2016-03-30-usage-statistics-privacy-advisory.adoc
- content/blog/2016/2016-03-30-usage-statistics-privacy-advisory.md
> Expand the usage stats blog post a wee bit

- content/2.0.html.haml
The location of the reminder blocks may be a bit weird and require reworking.
> Update 2.0 page to 2.0-rc-1

- content/_layouts/frame.html.haml
- content/css/jenkins.css
#177 is a pull request from @arshdkhn1's master branch so it includes other unrelated changes. This picks those changes out and applies them on top of the latest HEAD of master
Closes #177
> Clean up narrow screen pull request

- content/css/jenkins.css
This is just a cherry-pick of a pre-existing change
Closes #190
> Prevent fork ribbon from overlapping with navigation

- STYLEGUIDE.adoc
- content/css/jenkins.css
- content/doc/index.html.haml
- content/doc/pipeline/index.adoc
- content/doc/pipeline/jenkinsfile.adoc
- content/pipeline/getting-started-pipelines.adoc
This incorporates some of @PaddyOH's changes from #193 with more formatting changes on top of them.
I cherry-picked only what I believed to still be relevant, as to avoid spending too much time dealing with conflict resolutions.
Closes #193
> Incorporate grammar and formatting edits into Pipeline documentation

- content/blog/2016/2016-04-11-gsoc2016-mentors-call.adoc
I've realised I have not created a PR for it yet
> First version of the GSoC Call for Mentors blogpost

- content/_layouts/frame.html.haml
- content/css/jenkins.css
For reference: https://issues.jenkins-ci.org/browse/WEBSITE-168
> Footer improvements [WEBSITE-168]

- CNAME
[WEBSITE-63](https://issues.jenkins-ci.org/browse/WEBSITE-63)
> Remove a file to test pull request integration

- content/blog/2016/2016-04-14-replay-with-pipeline.adoc
Original here: https://www.cloudbees.com/blog/replay-pipeline
> Cross-post @jglick's replay blog with a slightly modified title

- content/blog/2016/2016-04-11-gsoc2016-mentors-call.adoc
Kudos to @artkoshelev for reporting it
> [gsoc-mentors-call-post] Fix the link to mentor requirements

- content/_partials/toptoolbar.html.haml
It's wicked hard to figure out how to change your password for wiki and issues - this will make it a little easier.
> Link for Accounts site

- content/doc/pipeline/steps/docker-workflow.adoc
- content/doc/pipeline/steps/figlet-buildstep.adoc
- content/doc/pipeline/steps/gerrit-trigger.adoc
- content/doc/pipeline/steps/lockable-resources.adoc
- content/doc/pipeline/steps/p4.adoc
- content/doc/pipeline/steps/pipeline-build-step.adoc
- content/doc/pipeline/steps/pipeline-input-step.adoc
- content/doc/pipeline/steps/pipeline-stage-step.adoc
- content/doc/pipeline/steps/pipeline-utility-steps.adoc
- content/doc/pipeline/steps/sauce-ondemand.adoc
- content/doc/pipeline/steps/slack.adoc
- content/doc/pipeline/steps/workflow-basic-steps.adoc
- content/doc/pipeline/steps/workflow-durable-task-step.adoc
Holdover for the automated job.  There were a bunch of plugin updates for the 2.0 release.
> Additional pipeline documentation

- content/solutions/pipeline.html.haml
> Linking to Dockerized demos

- content/changelog-stable/index.html
> Add 1.651.2 to LTS changelog

- build.gradle
- scripts/release.rss.groovy
This should address [INFRA-663](https://issues.jenkins-ci.org/browse/INFRA-663)
> Incorporate release.rss generation into our build process

- content/_data/events/boston-jam-1.adoc
- content/_data/events/boulder-jam-1.adoc
- content/_data/events/dublin-jam-1.adoc
- content/_data/events/guadalajara-jam-2.adoc
- content/_data/events/jenkins-world-2016.adoc
- content/_data/events/juc-israel.adoc
- content/_data/events/london-jam-1.adoc
- content/_data/events/seattle-jam-1.adoc
- content/_data/events/spb-jam-3.adoc
- content/_data/events/washington-dc-jam-1.adoc
> Update he JAMs calendar

- CONTRIBUTING.adoc
- content/_layouts/post.html.haml
@rtyler emergency fix for Jenkins.io – many reports on twitter about not being able to read the blog post :(
> Remove the sidebar on posts until we can fix the CSS for real

- content/projects/gsoc.adoc
We've discussed at the public office hours that every student should create a PR on this page: 
- to add his/her name to the project
- maybe add additional info or links to the project, to the blog post.
@rtyler @oleg-nenashev @martinda can you please have a look?
> Additional info on the EWM abstract

- content/projects/blueocean.adoc
Trimmed some of the wording that came over from the blog copy, which didn't make sense. 
Links are also to the real repos now. 
cc @daniel-beck @rtyler
> Clarify the wording for project and use jenkinsci owned repos

- content/projects/gsoc.adoc
I have added some info about the EWM weekly meetings that I am having with my mentors, so if anyone is interested, they should know when and where to join.
CC @rtyler @oleg-nenashev @martinda
> Add info about the ewm weekly meetings

- content/changelog-stable/index.html
> Add changelog for LTS RC

- content/download.html.haml
how it is typed:... Jenkins 2.0 begins with a setup wizard asking the user to choose the intial plugins to be installed...
proposed: ... Jenkins 2.0 begins with a setup wizard asking the user to choose the **initial** plugins to be installed...
> Sorry, but just "i" is missed in word "intial".

- content/friend/index.adoc
https://wiki.jenkins-ci.org/display/JENKINS/Donation#Donation-FriendofJenkins
> Add /friend redirect for the Friend of Jenkins plugin

- content/blog/2016/2016-06-16-parallel-test-executor-plugin.adoc
@rtyler - Where possible we should be avoiding the "step (...)" method.
> Update artifact archive step

- content/press.adoc
> Fix the press contact

- content/changelog-stable/index.html
@rtyler @olivergondza @oleg-nenashev Review would be appreciated.
> Add changelog for 2.7.1

- content/blog/2016/2016-07-01-html-publisher-plugin.adoc
- content/blog/2016/2016-07-18-pipline-notifications.adoc
@rtyler 
Fix links, roles,  and one phrase that got by me.
> Link fixes

- content/_data/events/bangalore-jam-1.adoc
- content/_data/events/boston-devops-dojo.adoc
- content/_data/events/dfw-jam-5.adoc
- content/_data/events/jenkins-world-contributor-summit.adoc
- content/_data/events/lima-august-jam.adoc
- content/_data/events/singapore-august-jam.adoc
> Add a lot of the recently posted/planned JAMs

- content/doc/book/appendix/chapter.yml
- content/doc/book/appendix/index.adoc
- content/doc/book/appendix/installing.adoc
- content/doc/book/getting-started/installing.adoc
> Installing Jenkins

- content/projects/blueocean.adoc
> add a note on how to install blue ocean from experimental UC

- content/blog/2016/2016-06-16-parallel-test-executor-plugin.adoc
- content/blog/2016/2016-07-01-html-publisher-plugin.adoc
- content/blog/2016/2016-07-18-pipline-notifications.adoc
@rtyler 
Per discussion with Harpreet, adding notes on `checkout` step for stand-alone.
> Added note to blog posts to use long checkout

- content/blog/2016/2016-08-01-st-petersburg-jam-3-4-report.adoc
- content/blog/2016/2016-08-03-st-petersburg-jam-3-4-report.adoc
Just a blogpost with a bunch of links
CC @lanwen, @aatarasoff and @jenkins-infra/copy-editors
> Blogpost: St. Petersburg Jenkins meetup reports

- content/changelog-stable/index.html
To be merged after the release tomorrow.
> Changelog 2.7.2

- Gemfile
- content/css/jenkins.css
- content/doc/index.html.haml
- content/doc/pipeline/examples.html.haml
- scripts/fetch-examples
> Incorporate pipeline-examples into the /doc/ structure

- content/_data/events/2016-08-25-online-jam-gsoc.adoc
- content/_data/events/2016-09-06-online-jam-plugin-dev-2.adoc
> Add Jenkins Online Meetups to the event list

- content/projects/gsoc.adoc
Reference the completed work summary for the External Workspace Manager Plugin
CC @rtyler @oleg-nenashev @martinda
> Update on GSoC page

- content/blog/2016/2016-08-22-ewm-stable-release.adoc
This is a blog post announcing the External Workspace Manager Plugin release
@rtyler @oleg-nenashev @martinda please have a look
> Blog post about the External Workspace Manager Plugin release

- content/blog/2016/2016-08-26-ask-the-experts-jenkins-world.adoc
see also [experts](https://www.youtube.com/watch?v=yghFBt-fXmw)
sudo summon @jenkins-infra/copy-editors
> Add an overview of the experts who I know will available in the Ask the Experts booth

- content/blog/2016/2016-08-26-ask-the-experts-jenkins-world.adoc
Good thing we proof-read this.
@rtyler
> Add some missing words to JW experts post.

- content/blog/2016/2016-07-26-join-me-at-jenkinsworld.adoc
- content/blog/2016/2016-08-11-speaker-blog-edx-jenkins-world.adoc
- content/blog/2016/2016-08-17-jenkins-world-speaker-blog-aquilent.adoc
- content/blog/2016/2016-08-24-jenkins-world-2016-festivities.adoc
- content/blog/2016/2016-08-26-ask-the-experts-jenkins-world.adoc
This also means that the next 20 people to register with this code will actually
get 30% off :smile:
> Consolidate Jenkins World discount codes across speaker and activity blogs

- content/blog/2016/2016-08-30-ask-experts-demos.adoc
> Add a schedule for the Jenkins World demos in the Open Source Hub

- content/changelog-stable/index.html
> Changelog for 2.7.3

- content/blog/2016/2016-09-01-jenkins-world-contributor-summit.adoc
@jenkins-infra/copy-editors 
This one is fairly short and sweet, I don't think I fubared grammer to much.
> Highlight the contributor summit agenda for Jenkins World

- content/infra/ci-redirects.adoc
References [INFRA-917](https://issues.jenkins-ci.org/browse/INFRA-917)
> Add a brief informational page for redirects of abusive traffic

- content/blog/2016/2016-09-08-continuous-delivery-of-infra.adoc
@jenkins-infra/copy-editors assemble!
> Add a speaker blog for my session on continuous Delivery of Infrastructure

- content/changelog-stable/index.html
Released already, this can be merged immediately.
> What's new in 2.7.4

- content/blog/2016/2016-09-09-take-the-2016-jenkins-survey-blog.adoc
I added a disclaimer on CloudBees use of personal information and bolded that and the prize descriptions.
> Formatting and disclaimer on Survey blog post

- content/blog/2016/2016-09-27-jenkins-world-2016-wrap-up-scaling.adoc
@rtyler 
Lead-in not done (obviously).  
The rest is ready to be raked over.
> Added Jenkins World wrap up - Scaling

- content/blog/2015/2015-09-01-take-the-2015-jenkins-survey.md
- content/blog/2016/2016-06-16-parallel-test-executor-plugin.adoc
- content/blog/2016/2016-07-01-html-publisher-plugin.adoc
- content/blog/2016/2016-07-18-pipline-notifications.adoc
- content/blog/2016/2016-08-29-sauce-pipeline.adoc
- content/blog/2016/2016-09-09-take-the-2016-jenkins-survey-blog.adoc
- content/blog/2016/2016-09-21-jenkins-world-2016-wrap-up.adoc
Also added link in my guest post header.
@rtyler
> Changed Cloudbees to CloudBees

- content/doc/book/getting-started/index.adoc
> Updated Getting started Overview

- content/_partials/downloadlist.html.haml
- content/doc/index.html.haml
- content/doc/upgrade-guide.html.haml
- content/doc/upgrade-guide/2.19.adoc
- content/doc/upgrade-guide/2.7.adoc
@olivergondza @oleg-nenashev A review would be appreciated.
Also, how do we tell users about this? Adding a link to this on every version in the LTS changelog seems clunky.
> Add LTS upgrade guide

- content/doc/book/appendix/index.adoc
- content/doc/book/best-practices/index.adoc
- content/doc/book/contributing/index.adoc
- content/doc/book/getting-started/index.adoc
- content/doc/book/managing/index.adoc
- content/doc/book/operating/index.adoc
@rtyler - 
First pass at adding abstracts.  Feedback?
> Added overviews of chapters

- content/changelog-stable/index.html
To be released tomorrow.
@daniel-beck
> Changelog for 2.19.1

- content/doc/book/managing/index.adoc
- content/doc/book/operating/index.adoc
- content/doc/book/pipeline/index.adoc
- content/doc/book/scaling/index.adoc
- content/doc/book/use-case/index.adoc
- content/doc/book/using/index.adoc
> Added overviews to remaining chapters

- content/doc/book/appendix/index.adoc
- content/doc/book/pipeline/index.adoc
- content/doc/book/scaling/index.adoc
- content/doc/book/using/index.adoc
@rtyler 
After this, I'll open a pull request from chapters to master with review by copy-editors.  Sound good?
> Fix asciidoc errors

- content/blog/2016/2016-06-16-parallel-test-executor-plugin.adoc
- content/blog/2016/2016-07-01-html-publisher-plugin.adoc
- content/blog/2016/2016-07-18-pipline-notifications.adoc
- content/blog/2016/2016-08-10-rails-cd-with-pipeline.adoc
- content/blog/2016/2016-08-29-sauce-pipeline.adoc
Added tutorial tag and updated based on edits from publishing to CB.
> Tweaks to existing blog posts

- content/blog/2016/2016-09-24-jenkins-world-2016-wrap-up-pipeline.adoc
- content/blog/2016/2016-09-27-jenkins-world-2016-wrap-up-scaling.adoc
- content/blog/2016/2016-09-29-jenkins-world-2016-wrap-up-experts-demos.adoc
- content/blog/2016/2016-10-18-jenkins-world-2016-videos.adoc
> Added videos to Jenkins World Posts

- content/content/mailing-lists/index.md
> Add entry for jenkinsci-docs

- content/_data/events/moscow-jam-1.adoc
> Create an event for Moscow JAM on Nov 2

- content/changelog-stable/index.html
https://issues.jenkins-ci.org/issues/?jql=labels%20%3D%202.19.2-fixed
The release date needs to be adjusted before merging.
> Changelog for 2.19.2

- content/doc/upgrade-guide/2.19.adoc
Nothing else relevant I could find. @oleg-nenashev ?
> Add upgrade guide to 2.19.2

- content/_data/events/2016-seattle-jam-dec-07.adoc
- content/_data/events/2016-seattle-jam-nov-11.adoc
> Added Seatttle JAM Nov and Dec

- content/_config/site.yml
- content/_ext/pipeline.rb
- content/blog/2015/2015-12-03-pipeline-as-code-with-multibranch-workflows-in-jenkins.md
- content/blog/2016/2016-04-07-pipeline-for-runs-on-hardware.adoc
- content/blog/2016/2016-05-23-external-workspace-manager-plugin.adoc
- content/doc/book/architecting-for-scale.adoc
- content/doc/book/pipeline/overview.adoc
- content/pipeline/getting-started-pipelines.adoc
@rtyler 
This fixes WEBSITE-196.  Still a few warnings left but they are in external content.
> Fixed asciidoc warnings

- scripts/fetch-external-resources
> Fetch the generator pipeline steps documentation from ci.jenkins.io

- content/blog/2016/2016-11-16-security-updates-addressing-zero-day.md
- content/changelog-stable/index.html
- content/doc/upgrade-guide/2.19.adoc
> Add changelog, upgrade guide and blog post on 2.19.3

- README.adoc
Testing [INFRA-981](https://issues.jenkins-ci.org/browse/INFRA-981)
> Minor README update

- content/css/jenkins.css
> Added space to the bottom of the blog post

- content/blog/2016/2016-11-22-what-jvm-versions-are-running-jenkins-the-return.adoc
Cannot reproduce locally with asciidoctor.
I checked with a locally generated site using Gradle, but I'm
surprised jenkins.io may not actually asciidoctor when both use
Ruby...
@rtyler
> Fix weird rendering

- content/blog/2016/2016-11-21-gc-tuning.adoc
@svanoort, as an author of the great article, please have a look.
> Minor gc-tuning blog fixes

- content/changelog-stable/index.html
Release date might need tweaking based on the actual date.
> Changelog for 2.19.4

- .awestruct_ignore
- .gitignore
- CONTRIBUTING.adoc
- build.gradle
- content/_config/site.yml
- content/_ext/activenav.rb
- content/_layouts/default.html.haml
- content/_layouts/frame.html.haml
- content/_partials/scriptlinks.html.haml
- content/_partials/toptoolbar.html.haml
These are some commits to allow for a, mostly functional, version of the static site to be published to GitHub Pages with awestruct.
> Add rudimentary support for publishing demos to GitHub Pages

- lib/asciidoctor/extensions/pipeline-block.rb
For example, the following blocks will not log warnings but will also only
display a single rendered block of code
```asscidoc
[pipeline]
----
// Script //
node {
}
// Declarative not yet implemented //
----
[pipeline]
----
// Declarative //
node {
}
// Script not yet implemented //
----
```
> Add support to [pipeline] blocks for empty Script or Declarative sections

- content/projects/blueocean.adoc
Fixes a typographical error discovered by Igor Ganapolsky.
> [FIX JENKINS-40208] fix typographical error

- content/doc/upgrade-guide/2.19.adoc
Not sure whether some of these are relevant enough.
@olivergondza @oleg-nenashev WDYT?
> Add upgrade guide for 2.19.4

- content/_partials/toptoolbar.html.haml
- content/participate/code.adoc
- content/participate/index.html.haml
PR to get feedback from @rtyler @jenkins-infra/copy-editors
> Add standalone 'participate' page

- content/_partials/toptoolbar.html.haml
Move mailing lists and chat to 'Resources'
> Make 'Participate' into a regular link

- STYLEGUIDE.adoc
- content/doc/book/pipeline/getting-started.adoc
- content/doc/book/pipeline/jenkinsfile.adoc
- content/doc/book/pipeline/shared-libraries.adoc
- lib/asciidoctor/extensions/pipeline-block.rb
FYI @HRMPW 
* [WEBSITE-272](https://issues.jenkins-ci.org/browse/WEBSITE-272)
* [WEBSITE-273](https://issues.jenkins-ci.org/browse/WEBSITE-273)
* [WEBSITE-274](https://issues.jenkins-ci.org/browse/WEBSITE-274)
> Update references to Scripted Pipeline

- content/changelog-stable/index.html
- content/doc/upgrade-guide/2.32.adoc
Changelog for upcoming release with Upgrade Guide stub. As discussed with Daniel, I will populate the upgrade guide with what I think is worth mentioning or submit an empty stub. People are suggested to reformulate/amend/update where they feel it is needed.
> 2.32.1 changelog and upgrade guide

- content/changelog-stable/index.html
> Fix release date for 2.32.1

- Gemfile
- build.gradle
Fixes [WEBSITE-276](https://issues.jenkins-ci.org/browse/WEBSITE-276)
> Upgrade to the latest awestruct-ibeams

- content/projects/blueocean.adoc
More info on how to join the user community
> Add info on how to join the blueocean community

- content/redirect/security-144.adoc
In the near future this redirect will point to somewhere in /doc/book
> Add a redirect file for the SECURITY-144 redirect

- content/redirect/securing-jenkins.adoc
In the future I expect this to live in the Handbook
> Add a redirect handler for the Securing Jenkins content

- content/blog/2016/2016-12-19-declarative-pipeline-beta.adoc
> build agents aren't a thing, they're just called agents

- content/blog/2017/2017-01-17-scm-api-2.0-release.adoc
This commit should be reverted when the fixes hit the update center
> Advise against upgrading plugins until JENKINS-41121 is resolved

- content/changelog-stable/index.html
- content/doc/upgrade-guide/2.32.adoc
Unfortunately @oleg-nenashev isn't around to verify what I'm writing here.
Maybe @aheritier can confirm?
> [JENKINS-40810] Mention effect of Remoting 3 on Maven builds

- content/doc/pipeline/tour/deployment.adoc
- content/doc/pipeline/tour/hello-world.adoc
- content/doc/pipeline/tour/post.adoc
- content/doc/pipeline/tour/running-multiple-steps.adoc
- content/doc/pipeline/tour/tests-and-artifacts.adoc
Fixes [WEBSITE-297](https://issues.jenkins-ci.org/browse/WEBSITE-297)
FYI @HRMPW
> Add steps directives to all the Declarative Pipeline examples

- content/doc/pipeline/tour/deployment.adoc
Fixes [WEBSITE-300](https://issues.jenkins-ci.org/browse/WEBSITE-300)
> Simply omit Build/Test stages for brevity

- content/blog/2017/2017-02-01-pipeline-scalability-best-practice.adoc
Amends #566 and fixes issues introduced when addressing review comments.
> Fix 2 small but irritating typos that were missed in review of scalability post

- content/projects/gsoc.adoc
I expect this branch to get updated once @oleg-nenashev and I get some more stuff done.
> Placeholder for GSoC 2017 content

- content/projects/gsoc.adoc
Just a small patch, which addresses expectations regarding the sponsored travel (ideally we should add the "benefits" section later)
@rtyler @batmat @christ88 @rsandell
> [WEBSITE-306] - Finalize the incomplete sentence noticed by @rsandell

- content/blog/2017/2017-02-07-declarative-maven-project.adoc
> Added anchor for post section

- content/blog/2016/2016-12-20-jenkins-puppet-enterprise-plugin.adoc
- content/blog/2017/2017-01-10-jenkins-lifx-notifier-plugin.adoc
- content/blog/2017/2017-01-12-declarative-pipeline-beta-2.adoc
- content/blog/2017/2017-01-17-scm-api-2.0-release.adoc
- content/blog/2017/2017-01-19-converting-conditional-to-pipeline.adoc
- content/blog/2017/2017-02-03-declarative-pipeline-ga.adoc
- content/blog/2017/2017-02-06-scm-api-2-take2.adoc
- content/blog/2017/2017-02-07-declarative-maven-project.adoc
- content/blog/2017/2017-02-08-jenkins-datadog-plugin.adoc
- content/doc/book/glossary/index.adoc
- content/doc/book/managing/plugins.adoc
- content/doc/book/managing/security.adoc
- content/doc/book/pipeline/index.adoc
- content/doc/book/pipeline/jenkinsfile.adoc
- content/doc/book/pipeline/multibranch.adoc
- content/doc/book/pipeline/shared-libraries.adoc
- content/doc/upgrade-guide/2.32.adoc
@rtyler @daniel-beck 
I'm not bored.  5 minute sed to get us started using the macro.
> Switched to use new plugin macro

- content/blog/2017/2017-01-17-scm-api-2.0-release.adoc
`[INFO]` apparently isn't a thing.
> Fix admonition style

- content/doc/pipeline/tour/environment.adoc
> Nice and simple, fixing a typo.

- content/security/index.adoc
@jenkins-infra/copy-editors assemble!
> Update /security page

- content/chat/index.adoc
- content/content/chat/index.md
- content/project/governance.adoc
Replaces https://wiki.jenkins-ci.org/display/JENKINS/IRC+Channel
> Update IRC chat page

- content/_layouts/documentation.html.haml
https://en.wikipedia.org/wiki/Javadoc#cite_note-1
> JavaDoc → Javadoc

- content/changelog-old.html
Adding 1.546…1.656 to the archived changelog.
To be followed by a corresponding change to https://github.com/jenkinsci/jenkins/blob/master/changelog.html
> Archive pre-2.0 changelogs

- content/doc/book/pipeline/syntax.adoc
[JENKINS-41985](https://issues.jenkins-ci.org/browse/JENKINS-41985)
cc @rtyler @bitwiseman
> [FIXED JENKINS-41985] Fix when expression syntax

- content/_partials/downloadbanner.html.haml
- content/_partials/toptoolbar.html.haml
- content/css/jenkins.css
> [WEBSITE-145] Fix download popup in menu bar

- content/blog/2017/2017-02-15-declarative-notifications.adoc
> Fix first image URL in declarative notifications post.

- content/_layouts/frame.html.haml
- content/css/jenkins.css
- content/events/index.html.haml
> ![screen shot](https://cloud.githubusercontent.com/assets/1831569/22991600/1eb74564-f3bd-11e6-935b-58e26e86499a.png)
> Add /events page

- content/index.html.haml
It should say continuous [delivery] and not continous.
> Typo in intro block

- content/changelog-old.html
- content/security/advisory/2010-07-05.adoc
Importing http://web.archive.org/web/20100708085218/http://infradna.com/content/security-advisory-2010-07-05 (just updated the URL in the last section).
CC @kohsuke who presumably wrote this advisory.
> Add 2010-07-05 security advisory

- content/_data/changelogs/weekly.yml
I messed up the date for the upcoming weekly.
Also adding new notable changes.
I'll update this as applicable, to be merged when the release is out.
> Update changelog for 2.47

- content/css/jenkins.css
Before:
> ![screen shot](https://cloud.githubusercontent.com/assets/1831569/23185651/6a55fdf0-f884-11e6-98a7-b3731de8c206.png)
After:
> ![screen shot](https://cloud.githubusercontent.com/assets/1831569/23185653/6be57182-f884-11e6-9466-0e3271032b91.png)
> Limit top offset for anchors to headers

- content/projects/gsoc.adoc
CC @kzantow @michaelneale and @i386
> [GSoC2017] - Add the BlueOcean project idea

- content/redirect/cli-command-requires-channel.adoc
- content/redirect/log-levels.adoc
- content/redirect/log-recorders.adoc
Existing URLs were too generic, so add more specific ones.
Will be added to https://github.com/jenkinsci/jenkins/pull/2756
> More specific redirect URLs

- content/_data/changelogs/weekly.yml
- content/_partials/changes.html.haml
[JENKINS-42189](https://issues.jenkins-ci.org/browse/JENKINS-42189)
@reviewbybees esp. @oleg-nenashev, @daniel-beck
> [JENKINS-42189] Warn people against using 2.47

- content/_layouts/simplepage.html.haml
Good:
> ![screen shot](https://cloud.githubusercontent.com/assets/1831569/23344120/0ad1d45c-fc77-11e6-9559-493f4d6383b2.png)
Bad:
> ![screen shot](https://cloud.githubusercontent.com/assets/1831569/23344126/24a3a1da-fc77-11e6-907a-a46bfb835eee.png)
Fixed:
> ![screen shot](https://cloud.githubusercontent.com/assets/1831569/23344139/5b21ed34-fc77-11e6-8bd5-6430b7f5efc2.png)
> Limit additional margin on simplepage to main body

- STYLEGUIDE.adoc
- lib/asciidoctor/extensions/javadoc-link.rb
CC @jglick who recently suggested this feature.
> Add support for plugin Javadoc to jenkinsdoc macro

- content/security/advisory/2017-03-07.adoc
Also remove redundant links, use plugin: macro, and simplify severity list
> Add attribution for 2017-03-07 advisory

- content/_data/events/austin-jam-apr17.adoc
- content/_data/events/austin-jam-mar17.adoc
- content/_data/events/boston-jam-apr2017.adoc
- content/_data/events/boston-jam-may2017.adoc
- content/_data/events/boston.2-jam-apr2017.adoc
- content/_data/events/boston.2-jam-may2017.adoc
- content/_data/events/chicago_jam_may17.adoc
- content/_data/events/guadalajara-jam-mar2017.adoc
- content/_data/events/la-jam-mar17.adoc
- content/_data/events/sf-jam-mar17.adoc
- content/_data/events/split,croatia_jam_apr2017.adoc
Closes #727, #728, #729, #730, #731, #732, #733, #734, #735, #737, #738
> New JAMs collated into one big PR

- content/doc/book/pipeline/syntax.adoc
Depends on https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/107 being merged and released.
cc @rtyler @bitwiseman
> [JENKINS-41668] Add "dir" option for Dockerfile declarative agent

- content/_data/changelogs/weekly.yml
> Changelog: Reference the JENKINS-42724 regression in Jenkins 2.50

- content/doc/book/pipeline/shared-libraries.adoc
Documentation for https://github.com/jenkinsci/workflow-cps-global-lib-plugin/pull/14. Do not merge until 2.7 is visible on the update center.
@reviewbybees esp. @HRMPW
> [JENKINS-39450] Documenting library step

- content/project/governance.adoc
Per today's project meeting:
<http://meetings.jenkins-ci.org/jenkins-meeting/2017/jenkins-meeting.2017-03-15-18.00.html>
> Add a useful section on  trademark attribution

- content/doc/book/pipeline/jenkinsfile.adoc
Code example in Parameters section had minor mistakes that have been corrected.
> Fix code errors in Parameters section

- content/_data/changelogs/lts.yml
- content/_data/changelogs/weekly.yml
- content/changelog-stable.html.haml
- Typo in weekly changelog
- Move the comment to the source not the data
> Minor tweaks

- content/_data/changelogs/lts.yml
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>
> Fix 2.46.1 release date

- content/_layouts/frame.html.haml
- content/css/footer.css
- content/css/jenkins.css
- content/events.html.haml
- content/projects/blueocean/index.html.haml
This makes the header navbar collapse properly on lower resolutions, fixes the footer on the Blue Ocean page up, and tidies the events page which I noticed was wonky
> Correct minor CSS issues

- content/blog/2017/2017-04-05-say-hello-blueocean-1-0.adoc
A very good blog for all to enjoy and cherish.
PTAL @rtyler @bitwiseman
> A Blue Ocean blog

- content/_layouts/frame.html.haml
- content/_layouts/post.html.haml
- content/projects/blueocean/index.html.haml
* JQuery needs to be included before content, because landing page content includes JS that needs it.
* `no-margin` was throwing every blog post off. Its removed.
* There was some undocumented magic javascript that was throwing a javascript error. Probably never worked ever.
PTAL @rtyler
> Some minor touches that make things not look broken

- content/blog/2017/2017-04-05-welcome-to-blue-ocean-editor.adoc
- content/blog/2017/2017-04-06-welcome-to-blue-ocean-editor.adoc
> Added Getting Started for Blue Ocean Editor

- content/css/jenkins.css
Fix styling issues for media card in solution pages 😊
> Fix media card styling issue

- content/_data/changelogs/weekly.yml
- content/blog/2017/2017-04-10-jenkins-has-upgraded-to-java-8.adoc
> Article for Jenkins 2.54 Java 8 bump

- content/_data/changelogs/weekly.yml
> Add link to CLI announcement blog post from changelog

- content/doc/book/pipeline/index.adoc
In this context, link on keyword is more useful if it gives more informations on the keyword.
> Make keywords to point to proper syntax section

- content/blog/2017/04/2017-04-11-new-cli.adoc
> Minor fixup in recent blog

- content/mailing-lists.adoc
https://groups.google.com/d/msg/jenkinsci-dev/i8s9TQJc4Ug/EvktN8A4AgAJ
> Add note on first post moderation

- content/doc/book/appendix/index.adoc
> Fix a dead link in the handbook appendix

- content/projects/blueocean/roadmap/data.json
* Reformatted
* Added category for "Declarative Pipeline"
> Add declarative roadmap

- content/doc/book/pipeline/development.adoc
FYI @bitwiseman, lists are a little wacky in asciidoctor when you need to add more markup
> Add list continuations so the Replay screenshots render properly

- content/doc/book/pipeline/development.adoc
All of these caught by @MarkEWaite
> Fix some minor typos in the Pipeline Development Tooling section

- content/security/advisory/2017-02-01.adoc
Context:
https://github.com/distributedweaknessfiling/DWF-CVE-2017-1000000/blob/master/CVE-2017-1000362.json
> Change CVE of SECURITY-376

- content/blog/2016/2016-06-29-from-freestyle-to-pipeline.adoc
Fixed broken links to @rtyler and ci.jenkins.io Infrastructure job
> Fixed broken links

- content/_data/changelogs/weekly.yml
> Add 2.61 changelog

- content/doc/book/pipeline/getting-started.adoc
Also fix broken link to Wikipedia
> Use correct Groovy shebang line

- content/_data/events/oslo-jam-1.adoc
- content/projects/jam.adoc
This meetup has not been added to the Org on meetup.com, but AFAIK it is not a blocker. There will be also an event on June 01 (http://www.code-conf.com/doj/doj-osl/), but I am not sure if it is correct to add it since it is not a free event.
CC @alyssat , @rtyler
> Add Oslo JAM to the list & schedule the first meetup

- content/_layouts/frame.html.haml
- content/merchandise.adoc
I'm not certain that adding this page is a good idea, but these stores exist, so they should be discoverable.
Also clean up some links in the footer to use the site base URL.
> Add merchandise page

- content/_layouts/developer.html.haml
Better late than never.
@olivergondza Do you have some sort of checklist for new baselines? If so, could you add this?
> Add link to 2.46 Javadoc

- content/chat.adoc
> Add a note about irc logs for #jenkins-commuity

- content/download/index.html.haml
- content/download/lts.adoc
Replaces https://wiki.jenkins-ci.org/display/JENKINS/LTS+Release+Line (from which most content is copied)
@olivergondza
> Add LTS page

- content/merchandise.adoc
> Fix link to Cafepress store

- .gitignore
- content/_layouts/developer.html.haml
- scripts/fetch-external-resources
> [INFRA-1193] Get LTS baselines from Artifactory for Javadoc links

- content/_data/changelogs/weekly.yml
> Add missing changelog entries for JENKINS-23273 and JENKINS-40693

- content/projects/blueocean/roadmap/data.json
Update the status of the Bitbucket work and the fact Fast Search shipped in 1.1
PTAL @rtyler
> Update the status of some WIP and late 1.1 entries

- content/doc/book/pipeline/syntax.adoc
@rtyler just realized that this was missing. Oops. `anyOf`, `allOf` and `not` were added in 1.1. Feel free to flesh this out further - I just wanted to get something up to start from.
cc @reviewbybees
> Initial documentation for when anyOf/allOf/not.

- content/projects/blueocean/roadmap/data.json
Historical trends for tests and code coverage
Please merge at will.
> Add roadmap item for Blue Ocean

- content/blog/2017/06/2017-06-13-blueocean-1-1.adoc
> currentBuild property is displayName (not name)

- content/solutions/java.adoc
> fix image is not being inserted on page

- content/doc/book/pipeline/syntax.adoc
@abayer @rtyler 
I believe talked about this a while back.  Just making it happen.
> Agent should be a section not a directive

- content/projects/blueocean/roadmap/data.json
> Update blue ocean roadmap status

- content/doc/book/pipeline/shared-libraries.adoc
Fix a small typo in the Shared Libraries page.
> Fix small typo in the Shared Libraries page

- content/doc/book/pipeline/syntax.adoc
Prompted by [JENKINS-43104](https://issues.jenkins-ci.org/browse/JENKINS-43104)
> [JENKINS-43104] Clarify that when->branch only works on multibranch

- content/security/advisory/2017-07-10.adoc
@andresrc @jglick @oleg-nenashev
> Add note on regression in workflow-cps

- content/security/advisory/2017-07-10.adoc
> Poll SCM is only version 1.3.1

- content/projects/blueocean/roadmap/data.json
> Blue Ocean roadmap updates

- content/_data/events/belarus_jam_july2017.adoc
- content/_data/events/moscow_jam_jul2017.adoc
- content/_data/events/st.petersburg_russia_jam_jul2017.adoc
Add 3 meetups scheduled to the next week
CC @alyssat @rtyler
> Add Jenkins RU meetups in July

- content/_layouts/simplepage.html.haml
- content/doc/developer/.htaccess
- content/doc/developer/404.html.haml
> Add 404 page for developer documentation

- content/doc/book/getting-started/installing.adoc
in replacement for deprecated "jenkins" docker image
> document use of jenkins/jenkins

- content/download/index.html.haml
> Add a nice little tooltip icon to denote third-party maintained packages

- content/_data/changelogs/weekly.yml
> Clarify 2.71 changelog

- scripts/groovy
- scripts/node
- scripts/ruby
> Handle properly invoking docker containers when the tree has a file path with spaces

- content/doc/book/pipeline/syntax.adoc
[JENKINS-45646](https://issues.jenkins-ci.org/browse/JENKINS-45646)
> [FIXED JENKINS-45646] Add docs on post aborted.

- content/doc/book/pipeline/shared-libraries.adoc
> Update the plugin reference for Automatic Shared Libraries now that the org folder plugin is dead

- content/projects/blueocean/roadmap/data.json
> Update Blue Ocean roadmap

- content/doc/book/getting-started/installing.adoc
- content/download/index.html.haml
> Correct spelling of "OpenIndiana Hipster"

- content/_data/authors/markewaite.adoc
- content/blog/2017/08/2017-08-07-intro-to-plugin-development.adoc
Links to many useful and interesting pages and videos related to plugin development.
> Intro to Plugin Development blog

- content/projects/blueocean/roadmap/data.json
> Add JENKINS-45455 to declarative roadmap

- content/security/advisory/2017-08-08.adoc
> Add 2017-08-08 security advisory

- content/projects/blueocean/roadmap/data.json
> Add JENKINS-40616 to Blue Ocean roadmap

- content/projects/blueocean/roadmap/data.json
> Update roadmap status for publishHTML

- Makefile
- content/.gitignore
> Make sure the PDF is generated in the right order inside the build

- content/solutions/python.adoc
pytest also generates JUnitXML compatible reports out of the box.
> Mention pytest as possible runner in Python docs

- content/_layouts/frame.html.haml
> Fix card descriptions for twitter and other OpenGraph consumers

- content/projects/blueocean/roadmap/data.json
> Update ANSI color status on blue roadmap

- content/projects/blueocean/roadmap/data.json
> Update roadmap based on feedback

- content/blog/2017/08/2017-08-18-declarative-pipelines-at-jenkinsworld.adoc
Fixed formatting.
See before:
After:
> Fixed formatting for monospace text in one occurence

- content/_layouts/documentation.html.haml
> Expand the chapter sections in the side-nav for easier navigation

- content/_data/changelogs/lts.yml
Probably it got omitted because the issue was not JIRA-tagged.
https://issues.jenkins-ci.org/browse/JENKINS-45516?focusedCommentId=311425&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-311425
> Noting JENKINS-45516

- content/security/advisory/2017-04-27.adoc
- content/security/advisory/2017-06-06.adoc
- content/security/advisory/2017-07-10.adoc
Received today from Kurt Seifried via email.
> Add CVE IDs for past advisories

- content/blog/2017/08/2017-08-23-pull-requests-and-more.adoc
Special thanks to Reinhold Füreder - XORTEX eBusiness GmbH for detecting
that mistake.
> Point weekly changelog links to weekly changelog

- content/blog/2017/08/2017-08-29-2017-community-survey.adoc
> Add @brianvdawson's blog post by itself

- CONTRIBUTING.adoc
The purpose of this commit is really for me to experience how pull requests work in GitHub. My experience with GitHub has been limited - I've worked mainly with Bitbucket in the past.
> Initial commit - minor fix to a broken link.

- content/download/lts.adoc
1) add link to the update center URL
2) explain how to update the site metadata, either by hitting "Check now" or the jenkins checkupdates url.
> add link to the update center and explain how to update site metadata

- content/_data/changelogs/weekly.yml
Warning about https://github.com/jenkinsci/jenkins/pull/2996
@rtyler @oleg-nenashev @orrc
> Add note about the recent JRE requirement

- content/_data/changelogs/weekly.yml
Oops.
Yay Docker still isn't working for me, so no local builds and test runs.
> Close tags in 2.78 changelog

- content/_data/events/st_petersburg_russia_jam_sep2017.adoc
We are almost packed, but I am working on getting more space.
> [St. Petersburg JAM] - Add event for the September JAM

- content/doc/book/pipeline/shared-libraries.adoc
Clarify what is meant by set of steps is by using `this` passed to the constructor.
> Clarify steps

- content/_data/changelogs/lts.yml
- content/doc/upgrade-guide/2.73.adoc
> Add changelog and upgrade guide for 2.73.1

- content/_data/changelogs/lts.yml
- content/doc/upgrade-guide/2.73.adoc
> Note details on JENKINS-46754

- Makefile
If you want to get yelled at by Jim Dume, mess with the man's fonts
> The Blue Ocean page was missing some fonts

- content/doc/book/getting-started/installing.adoc
Passing the notice from 2.77 changelog.
> Note minimal JRE version compatible with Lets Encrypt

- Jenkinsfile
> Make sure the Jenkinsfile rethrows caught exceptions

- content/security/advisory/2017-09-27.adoc
Related to https://github.com/jenkins-infra/jenkins.io/pull/1149
Still undecided whether we need this. Feedback appreciated.
Please don't merge, I'd like to do that myself.
> Add security advisory 2017-09-27

- content/doc/book/pipeline/syntax.adoc
See https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/201 and [JENKINS-47109](https://issues.jenkins-ci.org/browse/JENKINS-47109)
> Add failFast for parallel stages

- content/blog/2017/10/2017-10-02-pipeline-templates-with-shared-libraries.adoc
@rtyler - just a minor fix in the blog post. I removed the duplicated file name.
> Minor fix in blog post 

- content/doc/tutorials/_download-and-run-jenkins-in-docker.adoc
- content/doc/tutorials/_prerequisites.adoc
- content/doc/tutorials/using-jenkins-to-build-a-java-maven-project.adoc
FYI @gilesgas, each commit is a distinct change to the tutorial :smile:
> Minor additions/changes to the Maven tutorial

- content/doc/tutorials/using-jenkins-to-build-a-java-maven-project.adoc
The unit tests are important part of java culture :)
> Unit test report is missing from the tutorial

- content/doc/developer/plugin-development/pipeline-integration.adoc
Fixes some formatting issues from #1190.
@reviewbybees + @lanwen
> Fix Markdown → AsciiDoc conversion

- content/_data/events/2017-11-01-philadelphia.adoc
- content/_data/events/2017-11-07-dfw.adoc
- content/_data/events/2017-11-07-online.adoc
- content/_data/events/2017-11-08-tokyo-1.adoc
- content/_data/events/2017-11-08-tokyo.adoc
- content/_data/events/2017-11-08-triangle.adoc
- content/_data/events/2017-11-11-bangalore.adoc
- content/_data/events/2017-11-16-guadalajara.adoc
@MaxArbuckle
Took your PRs and created a single PR.  Fixed file names and event times.
> Events November

- CONTRIBUTING.adoc
> Added event creation section

- content/_data/events/moscow_jam_nov2017.adoc
- content/_data/events/st_petersburg_russia_jam_nov2017.adoc
@jenkins-infra/copy-editors @MaxArbuckle
> Add Moscow and St. Petersburg JAMs in November.

- content/doc/book/installing/index.adoc
- content/doc/tutorials/_run-jenkins-in-docker.adoc
- content/doc/tutorials/building-a-java-app-with-maven.adoc
- content/doc/tutorials/building-a-node-js-and-react-app-with-npm.adoc
- content/doc/tutorials/creating-a-pipeline-in-blue-ocean.adoc
* Also make http link references consistent.
* Tweaked a comment.
> Fix broken links and typos in tutorials and installation docs.

- content/_data/changelogs/weekly.yml
> Fix unbalanced HTML tags in 2.90 changelog data.

- content/security/advisory/2017-10-11.adoc
- content/security/advisory/2017-10-23.adoc
- content/security/advisory/2017-11-08.adoc
- content/security/advisory/2017-11-16.adoc
As of today we're now up to date.
> Add CVE IDs as provided by Kurt Seifried

- content/doc/book/system-administration/security.adoc
Changes include 
1. "set up" to "setup"
1. correct spelling to programmatically (2 m's)
1. extra text for CSRF
1. extra text in "Disabling Security" section
> Fixed a few typos, and added some additional information on CSRF Protection

- content/blog/2016/2016-06-29-from-freestyle-to-pipeline.adoc
Links were pointing to old Jenkins site
> Fixing dead links

- Jenkinsfile
It lives IN THE CLOUD
Fixes INFRA-1418
> We're no longer publishing to eggplant.jenkins.io for the site.

- Jenkinsfile
- docker/Dockerfile
- docker/Makefile
- docker/README.adoc
- docker/default.conf
In order to test this PR, you can go to the docker directory and run `make build run`
Then In your browser go to http://localhost/why which must redirect to https://wiki.jenkins.io/pages/viewpage.action?pageId=53608972
> [INFRA-1411] Create jenkins.io docker image

- content/doc/book/installing/index.adoc
This change is needed to be able to connect to docker daemon(host).
> Addition of -u root for 'docker run'

- docker/default.conf
http -> https redirection is handle in the proxy in front of this container
> [INFRA-1411] Disable https redirection from docker container

- content/_data/changelogs/weekly.yml
@oleg-nenashev, please, take a look.
> Add jira links for lts-candidate changes

- content/security/advisory/2017-11-16.adoc
- content/security/advisory/2017-12-06.adoc
I should probably add more specific metadata (artifactIds) in the future, but for now, this is how this works.
> These advisories are single plugin only

- content/doc/book/blueocean/pipeline-editor.adoc
Corrected some typos, added in some improvements and properly escaped the + symbol.
> Pipeline editor documentation corrections and improvements

- content/participate/index.html.haml
> Switch links on the participate page to wiki.jenkins.io

- Gemfile.lock
> Update dependency: parallel

- content/blog/2018/01/2018-01-03-fosdem-2018.adoc
For [EVENTS-48](https://cloudbees.atlassian.net/browse/EVENTS-48)  - update links to meetup URL
Review from @rtyler ?
> Use meetup for FOSDEM Hackfest invite URL

- content/mailing-lists.adoc
People aren't going to actually read this warning, but it'll make me feel a tiny bit better.
> Ask people to stop sending duplicate mails to the moderation queues.

- content/blog/2017/02/2017-02-07-gsoc2017-announcement.adoc
- content/blog/2018/01/2018-01-06-gsoc2018-call-for-mentors.adoc
subj. Never use dashes and underscores in your user IDs...
> Fix @oleg-nenashev’s author ID in 2 blogposts

- content/js/feedback-form-functionality.js
* Based on feedback (through the written feedback form) from a reader who found these quotation marks confusing.
> Remove quotation marks from numbers to be added upon feedback form submission

- content/doc/developer/tutorial/create.adoc
- content/doc/developer/tutorial/extend.adoc
- content/doc/developer/tutorial/prepare.adoc
- content/doc/developer/tutorial/run.adoc
Minimal changes needed to make things work with the archetype.
> Update the tutorial to use the hello-world-plugin archetype

- content/_partials/downloadbanner.html.haml
- content/_partials/projectjumbotron.html.haml
- content/index.html.haml
Revert the Christmas Jumbotron
Rejected JEP-200 one:
@reviewbybees @jglick @jenkins-infra/copy-editors
> Revert the NY theme 

- content/projects/gsoc/gsoc2018-project-ideas.adoc
> [GSoC2018] - Update project ideas

- content/projects/gsoc.adoc
- content/projects/gsoc/students.adoc
> [GSoC2018] - page updates

- STYLEGUIDE.adoc
I would like to propose a couple of spelling corrections.  Could the "outtro" be closing or summary ?
> Propose a couple of spelling corrections

- content/doc/book/pipeline/_chapter.yml
- content/doc/book/pipeline/scaling-pipeline.adoc
Adds documentation for the Pipeline Speed/Durability Settings and other scaling tips to improve performance.
> Pipeline Scaling & Durability Setting Documentation

- content/security/advisory/2017-12-06.adoc
- content/security/advisory/2017-12-14.adoc
https://github.com/distributedweaknessfiling/cvelist/commit/5c2d8d29f192b9787bc1935f99f2281666a423ae
> Add CVEs assigned on Jan 24

- content/projects/gsoc/gsoc2018-project-ideas.adoc
Some minor updates for the page
@jenkins-infra/copy-editors
> [GSoC 2018] - Update the project ideas page

- content/_layouts/advisory.html.haml
- content/security/advisory/2018-01-22.adoc
- Jesse lost attribution for SECURITY-675
- Add space between introductory paragraph and components list
----
Followup to #1335
> Fixes to advisory

- content/projects/gsoc/students.adoc
@jenkins-infra/copy-editors @christ66 @martinda
> [GSoC 2018] - Add First contributions to the student guide

- CONTRIBUTING.adoc
- Makefile
- content/_config/site.yml
- content/index.html.haml
- scripts/user-site-deploy.sh
@gilesgas - per our discussion
This target will push a built site to origin/gh-pages
letting any user demo a change.
> Added user-site target

- content/doc/developer/tutorial/run.adoc
This was a bit too compressed.
@skrzyneckik
> Clarify steps needed to configure the project initially

- content/_layouts/developerguide.html.haml
- content/doc/developer/guides.html.haml
> Add sidebar to guide-related pages, and link from guides to index

- content/doc/developer/tutorial/create.adoc
- content/doc/developer/tutorial/extend.adoc
- content/doc/developer/tutorial/prepare.adoc
- content/doc/developer/tutorial/run.adoc
[WEBSITE-465](https://issues.jenkins-ci.org/browse/WEBSITE-465)
> [WEBSITE-465] Address feedback for plugin tutorial

- content/projects/gsoc/gsoc2018-project-ideas.adoc
> [GSoC 2018] - More copy-edits

- content/_data/changelogs/lts.yml
- content/_data/changelogs/weekly.yml
Consistently uppercase 'Remoting' as proper name
> Add changelog for 2.106

- content/doc/developer/tutorial/create.adoc
- content/doc/developer/tutorial/extend.adoc
- content/doc/developer/tutorial/run.adoc
Downstream of https://github.com/jenkinsci/archetypes/pull/33.
@reviewbybees esp. @daniel-beck
> Updates to plugin creation tutorial, esp. to reflect archetypes-1.3

- content/security/advisory/2018-02-14.adoc
> Fix blog link in Security Advisory 2018-02-14.

- content/projects/gsoc.adoc
- content/projects/gsoc/students.adoc
> Update Office hours info, fix the call for mentors link

- content/doc/book/pipeline/syntax.adoc
Only grammatical fixes have been done.
> syntax.adoc

- content/projects/gsoc/students.adoc
Just noticed that the formatting is messed up. Also added info about message thread names. I think we still need to do something about collisions.
> [GSoC 2018] - Fix/update First email guidelines

- content/_data/changelogs/weekly.yml
> Add changelog for 2.108

- content/projects/gsoc/gsoc2018-project-ideas.adoc
@oleg-nenashev WDYT? No problem if you think this idea is not ready for publication.
> Discard Builds Step Plugin proposal

- content/blog/2018/01/2018-01-06-gsoc2018-call-for-mentors.adoc
- content/blog/2018/02/2018-02-19-gsoc2018-announcement.adoc
- content/projects/gsoc/gsoc2018-project-ideas.adoc
I have finally finished the announcement blogpost for GSoC, targets Monday.
> [GSoC 2018] - Announcement blogpost + some edits

- content/projects/gsoc/gsoc2018-project-ideas.adoc
> [GSoC 2018] - Add @Supun94 and @suryagaddipati to projects

- content/security/advisory/2017-10-11.adoc
Missed this issue originally 😞
> Add attribution for SECURITY-514

- content/_layouts/advisory.html.haml
So far no demo case but seems to be straightforward enough.
> Support other CVSS versions than 3.0 with generic label

- content/_data/changelogs/weekly.yml
> ![screen shot](https://user-images.githubusercontent.com/1831569/36634702-c0297fe0-19a8-11e8-8132-1b4973ceef3b.png)
> Add changelog for 2.109

- content/security/advisory/2018-02-26.adoc
Minor tweak to add my company, since I found this at work.
> Add Fix SECURITY-248 attribution company

- content/projects/infrastructure.adoc
> Fix minor typo: instead -> instance

- content/doc/book/system-administration/security.adoc
I've written a wiki page describing the permissions of JENKINS_HOME, and I think it's worth linking to in the docs.
> Add a discussion of JENKINS_HOME permissions

- content/events.html.haml
- content/projects/gsoc.adoc
- content/projects/gsoc/students.adoc
> [GSoC 2018] - Add Public office hours events + clarify contacts

- content/_data/changelogs/weekly.yml
> ![screen shot](https://user-images.githubusercontent.com/1831569/36954778-8fee6c14-2024-11e8-8298-bbc8daeba21e.png)
> Add changelog for 2.110

- content/_data/changelogs/weekly.yml
February -> March
@daniel-beck @oleg-nenashev
> Fix release date for 2.110

- content/_data/changelogs/weekly.yml
Work in progress: https://github.com/jenkinsci/jenkins/pull/3339 might still be merged. Indicated by TODOs.
> ![screen shot](https://user-images.githubusercontent.com/1831569/37252993-e61f33be-252b-11e8-9570-b9f71135e5eb.png)
> Add changelog for 2.111

- content/security/advisory/2018-02-14.adoc
> ![screen shot](https://user-images.githubusercontent.com/1831569/37357551-084ed386-26e9-11e8-9ce9-beed03d8fe45.png)
> New CVE IDs for 2018-02-14 advisory

- content/projects/infrastructure/ircbot.adoc
https://github.com/jenkins-infra/ircbot/pull/56
> Adapt to ircbot#39

- content/doc/upgrade-guide/2.107.adoc
Just missed one link in the upgrade guide
@jenkins-infra/copy-editors @daniel-beck @rtyler
> [JEP-200] - Link the new blogpost in the LTS upgrade guide header

- content/_data/changelogs/weekly.yml
> ![screen shot](https://user-images.githubusercontent.com/1831569/37561497-20be694e-2a50-11e8-8b9b-bbefb0138819.png)
> Add changelog for 2.112

- content/blog/2018/03/2018-03-16-password-audit.adoc
- content/blog/2018/03/2018-03-19-password-audit.adoc
> Add blog post on Jenkins developer password audit

- content/blog/2018/03/2018-03-20-evolving-mission-of-jenkins.adoc
Putting Jenkins Essentials and Jenkins X in context.
> Blog post that puts Jenkins Essentials and Jenkins X in context.

- content/_data/changelogs/weekly.yml
> ![screen shot](https://user-images.githubusercontent.com/1831569/37879158-28508492-3074-11e8-9ea8-7dab072cc1f7.png)
> Add changelog for 2.113

- content/doc/book/pipeline/syntax.adoc
`respective` -> `respectively`
> docs: grammar

- content/_data/logo/jenkins-x.yml
@dduportal can you confirm it was a typo?
> Fix name for Jenkins-X logo

- content/_data/changelogs/weekly.yml
> ![screen shot](https://user-images.githubusercontent.com/1831569/38472580-2bfbf3d8-3b82-11e8-903e-cc756ee8b181.png)
> Add changelog for 2.115

- scripts/crushinator.sh
Use built-in facility to not overwrite existing file if it is already optimized.
> Further tune crushinator.sh

- content/doc/book/pipeline/syntax.adoc
Missing these details cost me a lot of time. The behavior makes sense once you know about it, but is non-obvious to newcomers.
> Adding details to "when"

- content/security/advisory/2018-04-11.adoc
Add CVE IDs from https://github.com/CVEProject/cvelist/pull/426
> Add 2018-04-11 advisory CVE IDs

- content/_data/changelogs/weekly.yml
> ![screen shot](https://user-images.githubusercontent.com/1831569/38778853-cab36564-40bf-11e8-9d17-ae9d9f5f8e92.png)
> Add changelog for 2.117

- content/blog/2018/04/2018-04-16-jenkins-x-explained-part1.adoc
Just 2 small improvements to make it look better.
> Fixed typos in Jenkins X Explained Part 1  blog post

- content/doc/book/pipeline/syntax.adoc
This was just released in Declarative 1.2.9 so this should be ready to
go whenever works for you.
> [JENKINS-41239] Add doc for new cleanup post condition.

- content/doc/book/architecting-for-scale.adoc
Fix https://jenkins.io/doc/book/architecting-for-scale/
> Fix missing image

- content/_data/events/2018-04-25-swiss-jam.adoc
Forgot to add the entry.
Better late than never I'd guess
> Add GenevaJUG on April 25

- content/projects/infrastructure/ircbot.adoc
Add simple doc for host command.
cc @jglick
> Add documentation for "host" command

- content/security/advisory/2018-04-16.adoc
https://github.com/CVEProject/cvelist/pull/472
FYI @varyvol
> Add CVE IDs assigned on 2018-05-01

- content/doc/developer/security/_chapter.yml
- content/doc/developer/security/form-validation.adoc
- content/doc/developer/security/index.adoc
- content/doc/developer/security/xss-prevention.adoc
Add two guides for basic security problems that showed up recently:
- XSS in ancient tooling situations
- Unsecured form validation
The latter applies to any web methods (so could be generalized), but it's especially obvious in form validation code (which seems the most common as well).
> Add some security-related developer documentation

- content/projects/gsoc/2018/remoting-over-message-bus.adoc
This PR is to resolve the JIRA task https://issues.jenkins-ci.org/browse/WEBSITE-486
> [WEBSITE-486][GSoC-2018] Update Remoting over Message Bus project info on jenkins.io

- content/doc/developer/security/form-validation.adoc
> Add note on checkMethod to implement CSRF safe web methods

- content/_partials/toptoolbar.html.haml
- content/event-calendar.html.haml
- content/events.html.haml
Rewrite to use haml and layout
Dynamically detect time zone using JSTZ
Allow selection of alternate time zone from list
Remove dead links
Add text from wiki page
Add events link to resources in navbar
Make link to events calendar more not
> Fix Event Calendar

- content/doc/book/pipeline/scaling-pipeline.adoc
Added the section about @NonCPS from [Sam’s Blog post](https://jenkins.io/blog/2017/02/01/pipeline-scalability-best-practice/) along with the
suggestion to add a try/catch block to the non transformed code
@reviewbybees
> Updated the core pipeline docs with @NonCPS

- content/projects/gsoc/2018/remoting-over-message-bus.adoc
This PR is to solve the task https://issues.jenkins-ci.org/browse/JENKINS-51342
> [JENKINS-51342] Link Google Drive and Timeline from the project page on jenkins.io

- CONTRIBUTING.adoc
Highligh the fork-based workflow
> Tweaks to contributing

- content/_ext/pipeline.rb
@olblak requested this so he could have a machine-readable history of all the
things
> Add a full RSS feed with a lot more content

- content/doc/book/pipeline/syntax.adoc
> Minor grammatical correction

- content/doc/developer/plugin-development/build-process.adoc
Does not impact output, but still wrong.
> Fix version in TODO comment for future reference

- content/security/advisory/2018-06-04.adoc
See https://github.com/CVEProject/cvelist/pull/570
> Add CVE IDs for 2018-06-04 advisory

- content/_data/events/2018-06-14-gsoc-phase1-demos.adoc
- content/projects/gsoc/index.adoc
Follow-up to https://groups.google.com/forum/#!topic/jenkinsci-dev/0o_OYtYjraM
Screenshots:
> [GSoC 2018] - Announce Phase 1 demos and add event for it

- content/security/advisory/2017-12-05.adoc
> ![screen shot](https://user-images.githubusercontent.com/1831569/41736744-aa30ccd4-758d-11e8-9e25-b655ccce9261.png)
> Reference 2018-01-22 update in 2017-12-05 advisory

- content/security/advisory/2018-06-25.adoc
https://github.com/CVEProject/cvelist/pull/645
> Add CVE IDs for 2018-06-25 security advisory

- Gemfile.lock
- package-lock.json
- scripts/docker-env
> Update dependencies and docker script

- content/_partials/projectjumbotron.html.haml
- content/index.html.haml
@rtyler @svanalstine 
Proposed Jumbotron for Jenkins X.  Thoughts?
> Jenkins X Jumbotron

- content/projects/jenkins-x/index.adoc
* Fix broken link in Jenkins-X project page
* Fix typo
> Fix Jenkins-X blog broken link

- content/_data/events/moscow_jam_2018_07.adoc
- content/_data/events/st_petersburg_russia_jam_2018_07.adoc
- content/_data/events/st_petersburg_russia_jam_sep2017.adoc
- content/_data/events/yaroslavl_jam_2018_07.adoc
Adds 3 JAMs in Russia, which will happen in July.
@jenkins-infra/copy-editors
> Add Jenkins RU meetups, July 2018

- content/_layouts/sig.html.haml
- content/sigs/index.html.haml
Just noticed that mailing list links are broken
> [JEP-4] - Fix mailing list links in SIG layouts

- content/_data/changelogs/weekly.yml
I messed up in my PR ... jenkinsci/jenkins#3536
> Correct issue number for 64 bit zip support

- content/blog/2018/07/2018-07-10-jenkins-essentials-on-aws.adoc
Update to inform community about https://github.com/jenkins-infra/evergreen/pull/128
@jenkins-infra/copy-editors cc @rtyler @mandie722
> [JENKINS-52426] Blog about Essentials AWS flavor

- content/_data/sigs/cloud-native.adoc
- content/sigs/cloud-native/index.adoc
See https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/jenkinsci-dev/CEeQwqQaGLo/qBoTYqW0AQAJ
As discussed with @bitwiseman , the list of participants needs to be updated if we want to keep it in metadata. Alternative suggestion is to just have a public team on GitHub or a link to mailing list members to simplify management.
@bitwiseman @tracymiranda @carlossg
> Add Cloud Native SIG Page and Metadata

- content/_data/authors/oleg_nenashev.adoc
TL;DR: I do not want EnvInject to be listed in the Bio :)
> Update @oleg-nenashev’s Bio

- content/doc/developer/publishing/source-code-hosting.adoc
Tested locally in Chrome with `--disable-web-security`, works.
> Fix data processing for permissions table

- content/security/advisory/2018-07-18.adoc
Reference: https://github.com/CVEProject/cvelist/pull/727
FYI @v1v @bmunozm
> Add CVEs for 2018-07-18 security advisory

- content/doc/developer/publishing/source-code-hosting.adoc
Perhaps we could do the same for github users 😊
> render as hyperlink 😅

- content/doc/developer/publishing/source-code-hosting.adoc
Also add a note on how to test changes locally
> Fix JavaScript

- content/_data/events/2018-07-31-cloud-native-sig-ext-logging.adoc
CC @jglick @bitwiseman @tracymiranda
> Add event for the Cloud Native SIG Meeting

- content/blog/2018/07/2018-07-30-introducing-cloud-native-sig.adoc
I have created a write-up to describe my vision of Cloud Native SIG and its future. This blog references the tomorrow's SIG meeting, and it would be great to get some initial feedback.
@jglick @carlossg @tracymiranda @bitwiseman
> Blogpost about Cloud Native SIG

- content/security/advisory/2018-07-30.adoc
https://github.com/CVEProject/cvelist/pull/876 assigns CVEs for 11 out of the 17 fixes here. WIP for now in case the others get assigned soon.
> Add CVEs for the 2018-07-30 security advisory (11/17)

- content/sigs/cloud-native/index.adoc
I am adding notes to the first public meeting we had on Tuesday.
Later we will need to move meeting links somewhere else, but it should do the job for now
CC @carlossg @jglick
> Cloud Native SIG: Add links to the first meeting & tags

- Makefile
In my first time to run 'make run', get error information about lack scripts permission.
> handle scripts permission

- content/_data/events/2018-08-13-online-jam-gsoc.adoc
- content/events.html.haml
- content/projects/gsoc/index.adoc
- content/sigs/gsoc/index.adoc
> Update GSoC pages & add GSoC SIG

- content/_data/events/2018-08-15-platform-sig-meeting1.adoc
- content/_data/events/2018-08-16-cloud-native-sig-meeting2.adoc
- content/sigs/cloud-native/index.adoc
- content/sigs/platform/index.adoc
> Add Cloud Native and Platform SIG events

- content/projects/gsoc/2018/remoting-over-message-bus.adoc
JIRA task: [WEBSITE-510](https://issues.jenkins-ci.org/browse/WEBSITE-510)
@oleg-nenashev @Supun94 @dwnusbaum @jeffret-b
> [WEBSITE-510] Update jenkins.io about remoting kafka project for final submission

- content/doc/book/pipeline/syntax.adoc
Add examples for text, choice, password, and file parameters.
See: https://github.com/jenkinsci/pipeline-model-definition-plugin/wiki/Parametrized-pipelines
for list of parameters
> Update parameters section with more examples

- content/projects/gsoc/2018/code-coverage-api-plugin.adoc
CC @oleg-nenashev 
Add a link to the PR of releasing blogpost
> Update Code Coverage API plugin project page

- content/projects/gsoc/2018/simple-pull-request-job-plugin.adoc
SEE [JENKINS-52917](https://issues.jenkins-ci.org/browse/JENKINS-52917)
> SPRP project page updated

- content/projects/gsoc/2018/simple-pull-request-job-plugin.adoc
I wanted to clarify an implementation detail for posterity.
CC @gautamabhishek46 @kwhetstone @oleg-nenashev @grandvizier
> Clarify implementation

- content/blog/2018/08/2018-08-14-simple-pull-request-plugin-final-evaluation.adoc
The video presentation was not rendering. Resolved now. @oleg-nenashev @martinda @kwhetstone @grandvizier
> Rendering issue of the presentation video resolved.

- content/projects/gsoc/2018/simple-pull-request-job-plugin.adoc
@oleg-nenashev as the blog post for phase 3 is published, link to pull request of phase 3 blog post is removed and the actual link has been added.
> Link to Phase 3 blog post added.

- content/redirect/troubleshooting/broken-reverse-proxy.adoc
Upstream from https://github.com/jenkinsci/jenkins/pull/3595
> Add redirect for broken reserve proxy documentation

- content/security/advisory/2018-08-15.adoc
https://github.com/CVEProject/cvelist/pull/944
> Add CVE IDs for 2018-08-15 advisory

- content/_data/events/2018-08-23-online-jam-openj9.adoc
- content/sigs/platform/index.adoc
FYI @tracymiranda 
Front page:
Events:
SIG page:
> Add Event and Platform SIG meeting for the Eclipse OpenJ9

- content/blog/2018/08/2018-08-29-day-of-jenkins-and-other-chances-to-meet-jcasc.adoc
Hi!
My first blogpost at jenkins.io, please have a look and share your feedback
Oleg suggested to put an agenda in it but I don't want to duplicate too much - it's all on the event page. Let me know if you still prefer me to put more details in the blogpost
cc @oleg-nenashev @bitwiseman @tracymiranda
> Blogpost - Day of Jenkins (jcasc event)

- content/blog/2018/08/2018-08-29-day-of-jenkins-and-other-chances-to-meet-jcasc.adoc
@bitwiseman can you have a look again? our communication manager had some minor comments to my text :)
> Day of Jenkins blogpost: typo and wording fixed

- content/sigs/cloud-native/index.adoc
Signed-off-by: David Currie <dcurrie@cloudbees.com>
> Add David Currie to Cloud Native SIG

- content/_data/events/2018-10-19-day-of-jenkins-as-code.adoc
> Add event: Day of Jenkins [as code]

- content/_data/events/2018-09-12-dublin-jam.adoc
- content/_data/events/2018-09-17-contributor-summit-san-francisco.adoc
- content/_data/events/2018-09-17-dfw-jam.adoc
- content/_data/events/2018-09-17-san-francisco-jam.adoc
- content/_data/events/2018-09-19-raleigh-jam.adoc
- content/_data/events/2018-10-23-contributor-summit-nice.adoc
- content/_data/events/21018-08-22-london-jam.adoc
Just a bulk change with fixes and copy-edits. All meetups now follow #1749 from @bitwiseman 
Also CC @svanalstine @tracymiranda
> Cleanup JAM and contributor summit announcements, add DW|JW Nice meeting

- content/_data/events/2018-09-18-stockholm-jam.adoc
> Stockholm JAM - fix the name

- content/sigs/platform/index.adoc
> Platform SIG: Add Aug 29 meeting to jenkins.io

- content/_data/events/2018-09-11-swiss-jam.adoc
- content/_data/events/2018-10-09-swiss-jam.adoc
Just adding 2 events which we have announced today.
> Add Swiss Jenkins Meetups to events

- content/blog/2018/08/2018-08-31-shifting-gears.adoc
> Adding the "Shifting Gears" post

- content/blog/2018/08/2018-08-31-shifting-gears.adoc
A newline was missing.
See https://jenkins.io/blog/2018/08/31/shifting-gears/ :
cc @kohsuke @jenkins-infra/copy-editors
> Fix rendering issue because of missing line

- content/_data/changelogs/lts.yml
- content/_data/changelogs/weekly.yml
- content/doc/upgrade-guide/2.138.adoc
> ![screen shot](https://user-images.githubusercontent.com/1831569/45438606-e01bf880-b6b7-11e8-9ae3-9795ef8bdba7.png)
> Add changelog and upgrade guide for 2.138.1

- content/blog/2018/09/2018-09-12-2018-community-survey.adoc
This PR contains commits to correct an issue with the image links, and other typos
> Survey Blog Update

- content/blog/2018/09/2018-09-12-2018-community-survey.adoc
Updated image link to remove duplicate image introduced due to copy and paste error.  Third time is a charm.
> Updated image link to remove duplicate image

- content/blog/2018/09/2018-09-13-speaker-blog-evergreen-safely-upgrading.adoc
Covering both @rtyler and mine.
@jenkins-infra/copy-editors thanks!
> Jenkins World 2018 Evergreen speaker blog post

- content/blog/2018/09/2018-09-14-speaker-blog-jenkins-builds-jenkins.adoc
This is a preview for Olivier and Brian's talk. Posting on behalf of them.
> Add in speaker blog post for Infrastructure talk

- content/blog/2018/09/2018-09-18-automatically-upgrading-with-evergreen.adoc
> Add a half-speaker half announcement blog post about Jenkins Evergreen

- content/blog/2017/01/2017-01-19-converting-conditional-to-pipeline.adoc
- content/doc/book/pipeline/syntax.adoc
Fixed in https://github.com/jenkinsci/jenkins/commit/6de571632c3873689981c27902ae8269fdf094eb in Jenkins-2.112
>  Change choices example from parameter string to list

- docker/default.conf
> INFRA-1647: adding redirect for jep

- content/blog/2018/03/2018-03-20-evolving-mission-of-jenkins.adoc
- content/blog/2018/04/2018-04-06-jenkins-essentials.adoc
- content/blog/2018/04/2018-04-27-essentials-versions-are-numbered.adoc
- content/blog/2018/05/2018-05-15-incremental-deployment.adoc
- content/blog/2018/06/2018-06-26-jenkins-essentials-at-eclipsecon-france.adoc
- content/blog/2018/07/2018-07-10-jenkins-essentials-on-aws.adoc
- content/projects/evergreen/index.adoc
https://issues.jenkins-ci.org/browse/WEBSITE-519
> [WEBSITE-519] Rename tags from *essentials* to *evergreen*

- content/_layouts/advisory.html.haml
> <img width="208" alt="screen shot" src="https://user-images.githubusercontent.com/1831569/45924493-1d516900-beb6-11e8-968d-e988bf421f1e.png">
> <img width="212" alt="screen shot" src="https://user-images.githubusercontent.com/1831569/45924492-1591c480-beb6-11e8-9110-f5442d13f8e4.png">
> Sort issues in severity list by ID

- content/_layouts/advisory.html.haml
Continuation of https://github.com/jenkins-infra/jenkins.io/pull/1792
> ![screen shot](https://user-images.githubusercontent.com/1831569/45983991-5aa52a80-c05f-11e8-9701-267e58224e85.png)
> ![screen shot](https://user-images.githubusercontent.com/1831569/45984000-62fd6580-c05f-11e8-8d72-b4ffa396ce7f.png)
> Sort issues in credits section

- content/blog/2018/10/2018-10-01-hacktoberfest.adoc
CC @MarkEWaite . As discussed in the chat yesterday
> Add Java 11 to the Hacktoberfest scope

- content/sigs/cloud-native/index.adoc
Signed-off-by: Dominic Gunn dgunn@cloudbees.com
> Add Dominic Gunn to Cloud Native SIG

- content/blog/2018/10/2018-10-01-hacktoberfest.adoc
> Hacktoberfest: Fix the Chinese Localization SIG in the announcement

- content/_data/solutions/pipeline.yml
- content/blog/2015/2015-07-25-bay-area-jenkins-area-meet-up-is-looking-for-you.html
> Remove links to unsafe domain

- content/projects/jcasc/index.adoc
- content/projects/jenkins-x/index.adoc
> Fix 'mailing' typo

- content/blog/2018/10/2018-10-09-telemetry.adoc
> Minor tweaks of the last blog post

- content/doc/upgrade-guide/2.138.adoc
[JENKINS-53998](https://issues.jenkins-ci.org/browse/JENKINS-53998)
> [JENKINS-53998] Noting

- content/projects/gsoc/2018/index.adoc
- content/projects/gsoc/gsoc2016.adoc
- content/projects/gsoc/gsoc2017.adoc
- content/projects/gsoc/index.adoc
GSoC 2019 is coming soon, let's park the 2018 content.
@martinda @jeffpearce
> GSoC 2018 : Archive GSoC 2018 content

- content/blog/2018/06/2018-06-13-code-coverage-api-plugin.adoc
> GSoC 2018: Add missing label in the code coverage intro blogpost

- content/sigs/chinese-localization/index.adoc
I am node on Github with real name Yang Zhentao (Chris) . I hosted the first JAM in China (https://www.meetup.com/Shenzhen-Jenkins-Area-Meetup/)  and also participanted to translate many articles and pages about Jenkins and cn.jenkins.io . I am an active supporter and fan.
@LinuxSuRen cloud  u pls help to review ?
> add participant to sig: Chinese-localization 

- content/_data/events/2018-10-22-nice-hacktoberfest.adoc
- content/_data/events/2018-10-27-beijing-hacktoberfest.adoc
- content/_data/events/2018-10-30-swiss-hacktoberfest.adoc
@jenkins-infra/copy-editors @LinuxSuRen
> Add Jenkins Hactoberfest events to the calendar

- content/doc/upgrade-guide/2.138.adoc
https://issues.jenkins-ci.org/browse/JENKINS-54031
Please hold merge until we get user confirmation in issue comments.
> [JENKINS-54031] Another system property is needed too.

- content/doc/pipeline/tour/hello-world.adoc
Many Go teams use Jenkins.  It's nice to include this on the front page of the tutorials.
> Add Go to hello world.

- content/sigs/pipeline-authoring/index.adoc
Proposal: https://groups.google.com/forum/#!topic/jenkinsci-dev/nJ1XWyzBMSw
Needs to be more fleshed out, particularly with additional participants.
> Add Jenkins Pipeline Authoring SIG

- content/event-calendar.html.haml
> Remove redundant timezone item

- content/_data/events/2018-11-08-st-petersburg.adoc
- content/_data/events/2018-11-15-moscow.adoc
> Add Jenkins RU meetups in November

- content/doc/book/pipeline/syntax.adoc
See [WEBSITE-518](https://issues.jenkins-ci.org/browse/WEBSITE-518)
Based on the snippets explained in the ticket [JENKINS-39684](https://issues.jenkins-ci.org/browse/JENKINS-39684)
> [WEBSITE-518] Update syntax docs for internal docker registry parameters

- content/doc/book/pipeline/development.adoc
some info about how to validate Jenkinsfiles in Atom
> Atom linter-jenkins package

- content/_data/changelogs/lts.yml
> Fix 2.138.3 date

- content/sigs/pipeline-authoring/index.adoc
> Add psftw to Pipeline Authoring SIG.

- content/_data/events/2018-11-14-lausanne-jug.adoc
Also listed on https://www.meetup.com/Swiss-Jenkins-Area-Meetup/events/255914568/, 
@jenkins-infra/copy-editors
> Add Jenkins talk at Lausanne JUG on Nov 14

- content/blog/2018/11/2018-11-12-inspecting-binaries-with-jenkins.adoc
Looks almost like @jglick forgot how to file a PR for a moment, so doing it for him. 😄 
https://twitter.com/tyvole/status/1062332627145932800
@michaelhuettermann
> File does not work sandboxed, or on agents

- content/blog/2018/10/2018-11-13-martinda-gsoc-mentor-summit-experience.adoc
@oleg-nenashev  @bitwiseman I changed the image sizes, they were way too big.
> Fix the image size in blog post

- content/doc/book/pipeline/syntax.adoc
See https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/285
[JENKINS-52114](https://issues.jenkins-ci.org/browse/JENKINS-52114)
cc @kshultzCB @dwnusbaum
> [JENKINS-52114] Clarify stage post failure with manual set of result

- content/projects/gsoc/2019/index.adoc
- content/projects/gsoc/2019/schedule.adoc
Cc @martinda @jeffpearce @oleg-nenashev
> [JENKINS-54289] Create year-round GSoC schedule

- content/_data/changelogs/weekly.yml
Correct the system properties for checking update sites.
> [JENKINS-54459] Correct system properties for checking for updates

- content/_data/events/2018-11-29-swiss-jam-luzern.adoc
- content/_data/events/2018-12-05-swiss-jam-luzern.adoc
CC @paolocarta @bygui86 @gmuecke
> [Events] - Add JUG Switzerland events on Nov 29 and Dec 05 to the website

- content/doc/developer/tutorial/create.adoc
https://issues.jenkins-ci.org/browse/WEBSITE-528
The instruction at https://jenkins.io/doc/developer/tutorial/create/ is out-of-date and NOT Newbie-friendly, need to be upated.
> [WEBSITE-528] Update content/doc/developer/tutorial/create.adoc

- content/_data/events/2018-11-02-denver-jam.adoc
- content/_data/events/2018-12-04-denver-jam.adoc
@oleg-nenashev @svanalstine 
Removed incorrect file
Fixed up the newer file
> Fixup Denver JAM

- content/participate/index.html.haml
- content/projects/gsoc/proposing-project-ideas.adoc
- content/projects/gsoc/students.adoc
Initial updates to student guidelines [JENKINS-54287](https://issues.jenkins-ci.org/browse/JENKINS-54287)
Uploading what I have so far. Will probably push more commits.
CC @oleg-nenashev @lloydchang @kwhetstone @jeffpearce @tracymiranda
> [JENKINS-54287] GSoC student guideline update

- content/projects/gsoc/mentors.adoc
Just fixes according on the page
> [GSoC 2019] - Fix mailing lists on the Mentor page

- content/doc/upgrade-guide/2.138.adoc
Per https://github.com/jenkinsci/jobConfigHistory-plugin/pull/78#issuecomment-444435677
> JCH 2.19 should fix the warnings on startup

- content/projects/gsoc/roles-and-responsibilities.adoc
to Roles and Responsibilities page
> [GSoC] add Potential Mentors and Contact org admin

- content/sigs/gsoc/index.adoc
Just added participants who joined the SIG meetings at least once this year. Also added the logo so that the page looks better
> GSoC - Update the SIG leader and participants lists

- content/projects/gsoc/2019/project-ideas/artifact-promotion-plugin-for-jenkins-pipeline.adoc
> add Artifact Promotion plugin for Jenkins Pipeline

- content/projects/gsoc/proposing-project-ideas.adoc
@bitwiseman @oleg-nenashev 
I decluttered the first paragraph of on [how to propose new GSoC ideas](https://jenkins.io/projects/gsoc/proposing-project-ideas/), and added to the list of project types.
> Declutter first paragraph, add projects types

- content/sigs/chinese-localization/index.adoc
change the logo for current sig
> Add alauda as an organization

- content/_data/events/2018-12-18-jenkins-online-meetup.adoc
CC @batmat @alecharp @MRamonLeon
> [Events] - Add Jenkins Online Meetup on Dec 18

- content/redirect/java11-developer-guidelines.adoc
@alecharp @oleg-nenashev @MRamonLeon @MarkEWaite
> Java 11 Developer guidelines redirect

- content/blog/2018/12/2018-12-10-the-official-Docker-image.adoc
Originally just tweeted as https://twitter.com/bmathus/status/1071053314618548224 and @rtyler hinted to make this a full blown blog entry for more visibility :), so here it is.
Thanks!
> Blog about the right Docker Hub repo to use for running Jenkins

- content/doc/developer/handling-requests/stapler-accessible-type.adoc
https://github.com/jenkinsci/lib-jenkins-stapler-support/blob/0e32a5f368b140735af1b4ad12e3e1e28e0bcadb/pom.xml#L11...L12
> Fix library name

- content/security/advisory/2018-10-29.adoc
- content/security/advisory/2018-12-05.adoc
https://github.com/CVEProject/cvelist/pull/1352
https://github.com/CVEProject/cvelist/pull/1353
> Add CVEs assigned on 2018-12-09

- content/blog/2018/12/2018-12-10-outreachy-audit-log-plugin.adoc
See https://issues.jenkins-ci.org/browse/JENKINS-55112
@tracymiranda @reviewbybees @jeffret-b @bitwiseman
> [JENKINS-55112] Author Outreachy audit log post

- content/projects/gsoc/2019/project-ideas.html.haml
on project ideas page, as discussed during
GSoC SIG meeting on December 5th
> [GSoC] change Mentor(s) to Potential Mentor(s)

- content/doc/book/pipeline/syntax.adoc
Depends on https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/292
> [JENKINS-53734] Update syntax docs for parallel-in-sequential

- content/projects/gsoc/2019/project-ideas/ext-workspace-manager-cloud-features.adoc
@bitwiseman @oleg-nenashev 
Added Patrick Hynes to the mentors for the [exwm cloud features GSoC project](https://jenkins.io/projects/gsoc/2019/project-ideas/ext-workspace-manager-cloud-features/).
> Add hynespm to mentor of exwm cloud features

- content/projects/gsoc/2019/project-ideas/role-strategy-performance.adoc
- content/projects/gsoc/2019/project-ideas/role-strategy-ux.adoc
> [GSoC 2019] - Role Strategy projects. Add @runzexia and @Supun94 as potential mentors + Gitter link

- content/projects/gsoc/proposing-project-ideas.adoc
Adds a quick start section to help potential champions get started without needing to understand the full process.
> Add proposal quickstart

- content/blog/2018/12/2018-12-14-java11-preview-availability.adoc
Staging the current draft for the Java 11 preview announcement blogpost. I will likely apply some fixes (see TODOs), but any feedback will be appreciated.
@batmat @alecharp @MRamonLeon @KevinEarls @MarkEWaite @jenkins-infra/copy-editors
> [JEP-211] - Draft the preview announcement blogpost

- content/sigs/platform/index.adoc
Added some tags to link more blogposts + added JEP-217 and Dec 04 meeeting notes
@MarkEWaite @batmat
> [Platform SIG] - Add Dec 04 meeting notes + more labels

- content/doc/administration/requirements/java.adoc
CC @jenkins-infra/copy-editors @batmat @alecharp @MRamonLeon
> [JEP-211] - Update the support policy to reflect the current Java support state

- content/doc/book/using/using-credentials.adoc
s/crendential/credential/
Signed-off-by: Gianpaolo Macario <gmacario@gmail.com>
> using-credentials.adoc: Fix a couple of typos

- content/projects/blueocean/roadmap/data.json
Reordering of steps has been released in 1.5.0
> BlueOcean roadmap is updated.

- content/doc/book/pipeline/jenkinsfile.adoc
A small improvement in User Document.
The link is https://jenkins.io/doc/book/pipeline/jenkinsfile/#creating-a-jenkinsfile
Click "Toggle Scripted Pipeline" to expand the snippet, in "stage('Test')", it's better echo 'Testing....' than echo 'Building....'.
> change "Building" to "Testing"

- content/_data/changelogs/weekly.yml
@jenkins-infra/copy-editors @batmat @alecharp @MRamonLeon
> Changelog: Add Java 11 Preview Availability to the 2.155 changelog

- content/sigs/platform/index.adoc
> [Platform SIG] - Explicitly reference the Platform SIG meeting agenda from the SIG page

- content/projects/gsoc/2019/project-ideas/eda-coverage-adapters.adoc
@oleg-nenashev @lloydchang 
CC: @jeffpearce @olofk @wallento
I would like to publish the EDA Coverage Adapter GSoC proposal as DRAFT.
> GSoC Draft: eda coverage adapters

- content/projects/gsoc/2019/project-ideas/ath-improvements.adoc
> [GSoC 2019] - Add Gitter link to the ATH proposal

- content/projects/gsoc/proposing-project-ideas.adoc
Simple fix of bullets and indentation.
> Fix bullets and indentations

- content/projects/remoting/index.adoc
Subj. It adds the Chat link to the subproject page. Needed for the GSoC project idea reference
CC @jeffret-b
> Remoting - add Gitter link to the subproject metadata

- content/projects/gsoc/2019/project-ideas/eda-coverage-adapters.adoc
> [GSoC 2019] - Add @cizezsy and @udara28 as potential mentors of the EDA Coverage project

- content/projects/gsoc/2019/project-ideas/ath-improvements.adoc
- content/projects/gsoc/2019/project-ideas/bitbucket-rest-plugin.adoc
- content/projects/gsoc/2019/project-ideas/ext-workspace-manager-cloud-features.adoc
- content/projects/gsoc/2019/project-ideas/role-strategy-performance.adoc
Bulk change according to Gitter discussions and Google Docs
CC @jenkins-infra/gsoc  @olivergondza @pvtuan10 @cizezsy and @linuxsuren
> [GSoC 2019] - Add @olivergondza @pvtuan10 @cizezsy and @linuxsuren as mentors

- content/projects/gsoc/2019/project-ideas/gitlab-support-for-multibranch-pipeline.adoc
Follow-up to the meeting we had in December
CC @jeffpearce
> [GSoC 2019] - Add @jeffpearce as a potential mentor of the GitLab MultiBranch project idea

- content/projects/gsoc/2019/project-ideas/ext-workspace-manager-cloud-features.adoc
> [GSoC 2019] - Add @alexsomai as a mentor to the External Workspace Manager project

- content/projects/gsoc/2019/project-ideas/ath-improvements.adoc
As discussed at the weekly GSoC meeting, I'd like to move this proposal the published state.
CC: @jenkins-infra/gsoc
> Move ATH proposal to published status

- content/projects/gsoc/2019/project-ideas/eda-coverage-adapters.adoc
As discussed in the weekly GSoC meeting, I'd like to move this proposal to the published state.
CC @jenkins-infra/gsoc
> Move EDA Coverage GSOC proposal to published state

- content/projects/gsoc/2019/project-ideas.html.haml
Just a follow-up to the discussion at the last GSoC meeting
> [GSoC 2019] - Be explicit that it is OK to apply to the draft project ideas

- content/projects/gsoc/2019/project-ideas/remoting-monitoring.adoc
CC @pvtuan10 @jenkins-infra/gsoc
> [GSoC 2019] - Publish the Remoting Monitoring project idea draft

- content/chat.adoc
- content/sigs/advocacy-and-outreach/index.adoc
@tracymiranda 
This is just a skeleton for this SIG page. 
Please add yourself to the the list of members via github suggestion feature or via PR to this PR's branch.  
The topic of selecting leads is also still open.
> Add Advocacy and Outreach SIG

- content/sigs/hw-and-eda/index.adoc
Follow-up to https://groups.google.com/forum/#!topic/jenkinsci-dev/a69DXm6qQms
CC @martinda
> Create Hardware and EDA SIG

- content/_data/events/2019-02-01-pre-fosdem-jenkins-pipeline-fundamentals-training.adoc
- content/_data/events/2019-02-01-pre-fosdem-workshop-continuous-deployment-with-jenkins-x-kubernetes-and-friends.adoc
When these are longer the events page become unreadable.
> Shorter event description

- content/projects/gsoc/2019/application.md
I made few patches during the submission in order to fit form sizes. Tags have been also updated a bit to ensure more technology coverage.
> [GSoC 2019] - Update the application (reflect changes during the submission)

- content/doc/upgrade-guide/2.150.adoc
> ![screen shot](https://user-images.githubusercontent.com/1831569/51384439-a69f4200-1b1c-11e9-8a96-d53174366b49.png)
@Wadeck Please confirm.
> Add upgrade advice for SECURITY-901 related problems

- content/doc/upgrade-guide/2.150.adoc
> Fix user seed property

- content/projects/gsoc/index.adoc
I have updated the status and also modified the layout to make it more readable by students and potential mentors. No more wall of links
> [GSoC 2019] - Polish/update the landing page

- content/chat.adoc
Add link to the GSoC chat.
CC @bitwiseman @oleg-nenashev
> Add link to GSoC Gitter Chat

- content/sigs/cloud-native/pluggable-storage.adoc
> [Cloud Native SIG] - Reference the GSoC 2019 project ideas on the Pluggable Storage Page

- content/projects/gsoc/2019/project-ideas/remoting-over-apache-kafka-docker-k8s-features.adoc
Promoting to the published state.
CC @oleg-nenashev @supun94 @jeffpearce @jeffret-b @pvtuan10
> Promote remoting over kafka gsoc to published

- content/projects/gsoc/2019/project-ideas/configuration-as-code-compatibility.adoc
Publishing the Configuration as Code Proposal.
CC @ewelinawilkosz  @oleg-nenashev @jonbrohauge @timja
> Publish config as code compat GSoC proposal

- content/projects/gsoc/2019/project-ideas/winsw-yaml-config-support.adoc
Adding the WinSW: YAML Configuration support
CC @oleg-nenashev
> Add winsw yaml config support gsoc proposal

- content/projects/gsoc/2019/project-ideas/external-fingerprint-storage-for-jenkins.adoc
CC @lloydchang @pvtuan10 . I feel that the project idea is ready to be published, WDYT?
> [GSoC 2019] - Publish the External Fingerprint Storage project idea
