- content/projects/gsoc/2019/project-ideas/pipeline-step-documentation-generator.adoc
> [GSoC 2019] - Publish the Pipeline Step Documentation Generator improvements idea as a draft

- content/sigs/cloud-native/index.adoc
https://groups.google.com/forum/#!topic/jenkinsci-dev/GmnXsHduQfU
> add jenkins kuberenetes operator

- content/security/advisory/2018-10-10.adoc
https://github.com/CVEProject/cvelist/pull/1484
> Add CVE for SECURITY-867

- content/projects/gsoc/mentors.adoc
Credits to @arnab1896 for reporting the broken mailing list
> [GSoC 2019] - Fix the mentor mailing list link

- content/_partials/toptoolbar.html.haml
Add Chinese site menu siwtcher
> Add language menu

- content/projects/gsoc/2019/project-ideas/machine-learning.adoc
@Darthholi and @jenkins-infra/gsoc
Please review for your approvals
> publish draft of Jenkins and Machine Learning Plugins for Data Science

- content/projects/gsoc/2019/project-ideas/advanced-build-discard-strategy-plugin.adoc
I have re-written the proposal on build discard. It addresses the issues in the reviews done by the community. It is a complete rewrite because modifying the other docs was too complex.
This new proposal simply aims to create an extension point to the existing "Discard old builds" feature. This is much simpler than the initial proposals.
CC @jenkins-infra/gsoc @arnab1896
> Draft for Advanced Build Discard Strategy Plugin

- content/projects/gsoc/2019/project-ideas/plugin-installation-manager-tool-cli.adoc
> [GSoC 2019] - Publish the Plugin Installation Manager project idea

- content/doc/book/pipeline/syntax.adoc
See https://github.com/jenkinsci/pipeline-model-definition-plugin/blob/055e1651c7c39b46c9d2e633594836984d7219b8/pipeline-model-definition/src/main/resources/org/jenkinsci/plugins/pipeline/modeldefinition/when/impl/TriggeredByConditional/help-compare.html
> document `when { triggeredBy ...}`

- content/blog/2019/01/2019-01-08-mpl-modular-pipeline-library.adoc
Just a small typo fix with correction
> Typo fix & small correction

- content/projects/gsoc/2019/project-ideas/freestyle-to-pipeline-converter.adoc
CC @rodrigc @jenkins-infra/gsoc
> [GSoC 2019] - Publish the Freestyle => Pipeline converter project idea as a draft

- content/projects/gsoc/2019/project-ideas/bitbucket-rest-plugin.adoc
Add skill to Bitbucket rest proposal
CC @cdancy @oleg-nenashev
> Add skills to bitbucket rest proposal

- content/projects/gsoc/2019/project-ideas/jenkins-rest-plugin.adoc
Adding skills.
CC @cdancy @oleg-nenashev
> Add skills to jenkins rest api proposal

- content/blog/2019/02/2019-02-05-jenkins-new-year-in-china.adoc
@batmat Thanks for your earnest review.
Fixes expression for #2084
> Fixes expression

- content/security/advisory/2019-01-28.adoc
To be merged only after https://github.com/CVEProject/cvelist/pull/1563 is merged.
> Add CVE IDs for 2019-01-28 advisory

- content/projects/gsoc/2019/project-ideas/advanced-build-discard-strategy-plugin.adoc
- content/projects/gsoc/2019/project-ideas/gitlab-support-for-multibranch-pipeline.adoc
- content/projects/gsoc/2019/project-ideas/jenkins-rest-plugin.adoc
- content/projects/gsoc/2019/project-ideas/plugin-installation-manager-tool-cli.adoc
- content/projects/gsoc/2019/project-ideas/winsw-yaml-config-support.adoc
As discussed at the weekly call, I am publishing the project ideas we confirmed.
> [GSoC 2019] - Publish project ideas which are ready to go.

- content/projects/gsoc/2019/project-ideas/artifact-promotion-plugin-for-jenkins-pipeline.adoc
- content/projects/gsoc/2019/project-ideas/external-fingerprint-storage-for-jenkins.adoc
@meekrosoft @jenkins-infra/gsoc
> [GSoC 2019] - Add @meekrosoft as a potential mentor to 2 GSoC projects

- content/projects/gsoc/2019/application.md
We have one unused tag, so it is nice to actually utilize it
> [GSoC 2019] - Add “Automation” tag to the organization profile

- content/projects/gsoc/2019/project-ideas/artifactory-rest-plugin.adoc
I am ready to publish the artifactory-rest proposal as draft.
CC @cdancy @jenkins-infra/gsoc
> Draft of artifactory rest plugin proposal

- content/doc/book/getting-started/index.adoc
Suggested by a random email landed on my inbox.
> Grammar fix

- content/projects/gsoc/2019/project-ideas/machine-learning.adoc
CC @jenkins-infra/gsoc @Darthholi
> Remove non-existent project name

- content/projects/gsoc/2019/project-ideas/remoting-monitoring.adoc
> Promote remoting monitoring gsoc to published

- content/projects/gsoc/2019/project-ideas/pipeline-step-documentation-generator.adoc
Move the pipeline steps generator to the published ideas.  If there are additional comments, please leave them here or in the doc.  Thanks!
> Publish the pipeline steps generator project idea

- content/projects/gsoc/2019/project-ideas/artifactory-rest-plugin.adoc
CC @jenkins-infra/gsoc @cdancy
> Publish artifactory-rest proposal

- content/security/advisory/2019-02-19.adoc
Not to be merged before https://github.com/CVEProject/cvelist/pull/1614
> Add CVEs for 2019-02-19 advisory

- content/projects/gsoc/2019/project-ideas/freestyle-to-pipeline-converter.adoc
Publish the freestyle to pipeline gsoc idea.
CC @rodrigc @jenkins-infra/gsoc
> publish freestyle to pipeline gsoc idea

- content/projects/gsoc/2019/project-ideas/machine-learning.adoc
As proposed in the Google Doc draft
> [GSoC 2019] - Add @denisj44 to the Machine Learning project idea

- content/projects/gsoc/2019/project-ideas/code-coverage-api-improvements.adoc
> [GSoC 2019] - Publish Code Coverage API project idea as a draft

- content/doc/book/pipeline/running-pipelines.adoc
@NicuPascu added support for restarting stages in Blue Ocean here:
https://github.com/jenkinsci/blueocean-plugin/pull/1769
> [JENKINS-48643] Update docs for restarting stages from Blue Ocean UI

- content/projects/gsoc/2019/project-ideas/advanced-build-discard-strategy-plugin.adoc
As discussed in the office hours, a new gitter chat room for the build discarder proposal
@jenkins-infra/gsoc @arnab1896
> Add link to new chat room for build discarder

- content/doc/book/system-administration/security.adoc
- content/doc/book/system-administration/security/build-authorization.adoc
- content/redirect/queue-item-security.adoc
Documentation corresponding to https://github.com/jenkinsci/jenkins/pull/3919
> Add documentation on access control for builds

- content/press.adoc
Changed 1,400 to 1,500 to reflect more accurate number of Jenkins plugins.
> Update number of plugins to 1,500

- content/_data/events/2019-03-05-st-petersburg.adoc
We were full in few hours, but it still makes sense to post it here for visibility purposes
@jenkins-infra/copy-editors
> Create a SPb JAM on Mar 05

- content/projects/gsoc/2019/project-ideas/docker-registries-polling-plugin.adoc
- content/projects/gsoc/2019/project-ideas/machine-learning.adoc
- content/projects/gsoc/2019/project-ideas/remoting-monitoring.adoc
CC @ankitjain28may @imoutsatsos @kinow @markyjackson-taulia
> [GSoC 2019] - Update mentor lists and channels

- content/blog/2019/03/2019-03-04-gsoc2019-announcement.adoc
Finally got to it. My apologies for the delay.
CC @jenkins-infra/gsoc @jenkins-infra/copy-editors
> [GSoC 2019] - Announcement blogpost (Mar 04, 2018)

- content/projects/gsoc/2019/project-ideas/advanced-build-discard-strategy-plugin.adoc
- content/projects/gsoc/2019/project-ideas/gitlab-support-for-multibranch-pipeline.adoc
Now, chat link refers to the branch specific gitter channel.
> Updated the gitter chat link

- content/projects/gsoc/2019/project-ideas/automatic-spec-generator-for-jenkins-rest-api.adoc
Add Stapler as a skill to develop for the student
CC @jenkins-infra/gsoc @cliffano
> Add stapler as a skill to automatic spec generator

- content/doc/book/pipeline/index.adoc
- content/doc/pipeline/tour/deployment.adoc
- content/doc/pipeline/tour/tests-and-artifacts.adoc
- content/doc/tutorials/build-a-java-app-with-maven.adoc
- content/doc/tutorials/build-a-python-app-with-pyinstaller.adoc
Based on a conversation with @abayer.
> Reminding readers to use skipStagesAfterUnstable to gate deployment stages

- content/security/advisory/2019-03-06.adoc
To be merged only once https://github.com/CVEProject/cvelist/pull/1665 is merged.
> Add CVEs for 2019-03-06 advisory

- content/projects/gsoc/2019/project-ideas/code-coverage-api-improvements.adoc
> GSoC 2019 - Publish the Code Coverage API project idea

- content/doc/book/pipeline/development.adoc
This repository was moved under the jenkinsci GitHub organization after Jenkins World 2017.
> Use updated link for Pipeline Unit

- content/projects/gsoc/2019/project-ideas/gitlab-support-for-multibranch-pipeline.adoc
I'd like to join as a mentor for GitLab support for multibranch pipeline GSOC
> add @casz as mentors

- content/security/advisory/2019-03-25.adoc
> Fix description of SECURITY-976

- content/css/jenkins.css
Incorrect cursor on menu item is really confusable.
Change it from default on pointer
> Make pointer cursor on menu items

- content/security/advisory/2019-03-25.adoc
https://github.com/CVEProject/cvelist/pull/1775
> Add CVEs for 2019-03-25 security advisory

- content/project/conduct.adoc
* office hours is dead
* use https
* follow redirects
> update links / content

- content/projects/gsoc/students.adoc
I added some details about what we expect from students, from the discussion in the gsoc gitter chat and from a previous hangout.
> Detail what's expected from students in the student info page

- content/security/advisory/2019-04-03.adoc
To be merged only once https://github.com/CVEProject/cvelist/pull/1826 is merged.
> Add CVEs for 2019-04-03 advisory

- content/_data/events/2019-03-05-st-petersburg.adoc
- content/_data/events/2019-04-18-st-petersburg.adoc
- content/_data/events/2019-04-20-nizhny-novgorod.adoc
It also fixes the bogus date in the previous St. Petersburg JAM
> Add Jenkins RU events in April

- content/blog/2019/03/2019-03-12-cdf-launch.adoc
my-first-ever-commit-on-github!
Suggestions are most welcome. :)
Thanks!
> Fixed some grammatical issues with documentation - Jenkins is joining the Continuous Delivery Foundation

- content/doc/developer/security/secrets.adoc
> Document f:secretTextarea and standalone library

- content/projects/gsoc/index.adoc
> [GSoC] Add instruction for project proposal review to GSoC page

- content/doc/developer/testing/index.adoc
> Add info about verifying log messages

- content/_data/changelogs/weekly.yml
https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/changelogs/_STYLEGUIDE.adoc#order-of-entries-regular
> Reorder, minor grammar

- Jenkinsfile
> ![Screen Shot](https://user-images.githubusercontent.com/1831569/56535790-d49d8380-655c-11e9-9c32-434a5e2f8faa.png)
> Disable concurrent builds on trusted.ci

- content/redirect/filepath-serialization.adoc
For https://github.com/jenkinsci/jenkins/pull/4011 as suggested by @daniel-beck.
> [JENKINS-57244] Creating jenkins.io/redirect/filepath-serialization

- content/doc/tutorials/build-a-java-app-with-maven.adoc
> Small typo

- content/projects/gsoc/2019/role-strategy-performance.adoc
Update the project page for Google Summer of Code 2019.
> [JENKINS-57437] Update Role Strategy Plugin GSoC 2019 Project Page

- content/sigs/docs/index.adoc
Thanks to Radek Antoniuk for creating the Jira bashboard for the
Docs special interest group!
> Link to Docs SIG Jira dashboard

- content/_data/authors/jonbrohauge.adoc
> Add jonbrohauge.adoc

- content/doc/book/installing/_docker.adoc
I don't like executing things as root without knowing why, so did an investigation and added my conclusion to the docs. I hope it is correct and helpful to others.
> Add explanation for why using root is needed

- content/projects/gsoc/2019/plugin-installation-manager-tool-cli.adoc
Updated basic project page info for Plugin Management Library and CLI GSoC project.
> Update basic info for GSoC plugin management project page

- content/_data/authors/yufei_zhang.adoc
- content/projects/gsoc/2019/ext-workspace-manager-cloud-features.adoc
Some personal information update and a design document link in the page.
CC @hynespm @martinda @alexsomai
> [GSoC 2019 Cloud Features for EWM] author info and project page update

- CONTRIBUTING.adoc
Follow-up to the Docs SIG meeting
CC @MarkEWaite
> CONTRIBUTING: Add a section about reviewing changes

- content/redirect/pipeline-cps-method-mismatches.adoc
Needed for https://github.com/jenkinsci/workflow-cps-plugin/pull/211. @dwnusbaum
> [JENKINS-31314] Defining a redirect for a wiki page

- content/_data/changelogs/weekly.yml
This is what happens when I forget to update the screen shot 😢
> This is not Markdown, use plain name

- content/projects/gsoc/2019/gitlab-support-for-multibranch-pipeline.adoc
I have added some information at the end of Community Bonding Period, will keep adding information as the development proceeds.
@markyjackson-taulia @oleg-nenashev
> Removed runxezia as mentor, blog links, evaluation 1 information, other links

- content/participate/index.html.haml
Clarified link which already goes to /r/jenkinsci
> Tiny correction to link text

- content/_data/events/2019-06-11-swiss-jam-zurich.adoc
- content/_data/events/2019-06-12-swiss-jam-lausanne.adoc
> Add Swiss JAM events in June

- content/blog/2019/05/2019-05-22-outreachy-audit-log-project.adoc
This adds a blog post welcoming our two new Outreachy interns and giving
an overview of our plans for the project this summer.
Internal id: FNDJEN-1137
@reviewbybees @aarthira @gayathrirajendar @tracymiranda
> Add Outreachy audit log project overview blog

- content/projects/gsoc/2019/artifact-promotion-plugin-for-jenkins-pipeline.adoc
Update project page with a link to the project epic, and a link to the project dashboard
> Add project links to the epic and dashboard

- content/_data/changelogs/lts.yml
- content/doc/upgrade-guide/2.176.adoc
Looks really long, but OTOH a lot of nontrivial changes made it in. Thoughts?
> ![Screen Shot](https://user-images.githubusercontent.com/1831569/59272547-8f412c80-8c56-11e9-86c5-937ea3e9d27b.png)
> Add 2.176.1 changelog and upgrade guide

- content/_data/changelogs/lts.yml
Accidentally removed wrong duplicate entry 😞
> Move entry to the earlier LTS release it was in

- content/_data/authors/stopalopa.adoc
- content/projects/gsoc/2019/plugin-installation-manager-tool-cli.adoc
Added more details for GSoC plugin management project and a few more details for bio.
> Update plugin management page to include meeting notes

- content/projects/gsoc/2019/artifact-promotion-plugin-for-jenkins-pipeline.adoc
As part of the new changes and updates in the project, this PR relates to the latest developments in the Project.
CC: @oleg-nenashev @bicschneider @jonbrohauge @MadsNielsen
> Update the Project Page

- content/css/blueocean-style.css
- content/projects/blueocean/index.html.haml
See [WEBSITE-402](https://issues.jenkins-ci.org/browse/WEBSITE-402)
This makes sure the same stylesheet is used for the main site and for BO hompepage, allowing to delete some duplicate code. BO content format restricted to the content.
Fixes problem both with the footer (described in the ticket) and the navigation (went wrong in #2317)
> [WEBSITE-402] fix styles of the Blue Ocean page

- content/projects/gsoc/2019/project-ideas/artifact-promotion-plugin-for-jenkins-pipeline.adoc
> Update mentor list to reflect the correct mentors

- content/blog/2019/06/2019-06-21-performance-testing-jenkins.adoc
Quick fix, CC @AbhyudayaSharma
> Fix the slides link in the Plugin Performance Benchmarking post

- content/_data/authors/casz.adoc
> fix typo of author name

- content/projects/gsoc/2019/role-strategy-performance.adoc
Update the page with link to the blog post and releases of Jenkins Test Harness
@oleg-nenashev @runzexia @supun94
> GSoC: Update project page for Role Strategy

- content/doc/developer/testing/index.adoc
Add links to documentation for running benchmarks.
@oleg-nenashev @supun94 @runzexia
> Add documentation for running benchmarks to developer docs

- content/doc/book/pipeline/syntax.adoc
> Minor typo and formatting fix (Follow up to #2352)

- content/_data/events/2019-07-10-swiss-jam-zurich.adoc
> Add Swiss JAM on Jul 10

- content/sigs/advocacy-and-outreach/index.adoc
> Adding link for advocacy-and-outreach youtube channel to sig page

- content/_data/authors/abhishek_gautam.adoc
- content/_data/authors/bicschneider.adoc
- content/_data/authors/cizezsy.adoc
- content/_data/authors/dernDren161.adoc
- content/_data/authors/dnusbaum.adoc
- content/_data/authors/dwnusbaum.adoc
- content/_data/authors/jamesdumay.adoc
- content/_data/authors/jeffpearce.adoc
- content/_data/authors/shenyu_zheng.adoc
- content/_ext/validator.rb
- content/_layouts/gsocproject.html.haml
- content/_partials/social-media-buttons.html.haml
- content/blog/2017/02/2017-02-15-pipeline-editor-preview.adoc
- content/projects/gsoc/2018/code-coverage-api-plugin.adoc
- content/projects/gsoc/2018/eda-plugins.adoc
- content/projects/gsoc/2018/remoting-over-message-bus.adoc
- content/projects/gsoc/2018/simple-pull-request-job-plugin.adoc
- content/projects/gsoc/2019/artifact-promotion-plugin-for-jenkins-pipeline.adoc
- content/projects/gsoc/2019/ext-workspace-manager-cloud-features.adoc
- content/projects/gsoc/2019/gitlab-support-for-multibranch-pipeline.adoc
- content/projects/gsoc/2019/plugin-installation-manager-tool-cli.adoc
- content/projects/gsoc/2019/project-ideas/bitbucket-rest-plugin.adoc
- content/projects/gsoc/2019/project-ideas/code-coverage-api-improvements.adoc
- content/projects/gsoc/2019/project-ideas/eda-coverage-adapters.adoc
- content/projects/gsoc/2019/remoting-over-apache-kafka-docker-k8s-features.adoc
- content/projects/gsoc/2019/role-strategy-performance.adoc
- content/projects/gsoc/2019/working-hours-improvements.adoc
- content/sigs/chinese-localization/index.adoc
- content/sigs/pipeline-authoring/index.adoc
- content/sigs/platform/index.adoc
1) removes some duplicate author pages
2) links to author pages also for GSoC students
3) fixes LinkedIn links from author pages
4) adds validation for 1) and 3)
@oleg-nenashev I hope 2) is OK
> Deduplicate author pages, fix linkedin links

- content/user-handbook.pdf/index.adoc
We replaced a file with a directory, that fails the upload and ultimately the build.
> The Azure publishing script cannot handle this

- content/blog/2019/07/2019-07-17-DevOps-World-Jenkins-World-2019-San-Francisco-Lunch-Demos.adoc
Adjusting the title and the abstract to better reflect the content.
@alyssat @MarckK
> Adjust title and abstract for Martin's presentation

- content/projects/gsoc/2019/schedule.adoc
[GSoC 2019] add Post GSoC TODO List
[GSoC 2019] correct location of mentor summit
> [GSoC 2019] add Post GSoC TODO List, correct location of mentor summit

- content/doc/book/pipeline/syntax.adoc
Removed file parameter from document because file upload with file parameter does not work in jenkinsfile.
https://issues.jenkins-ci.org/browse/JENKINS-47333
> delete file parameter.

- content/_data/authors/sladyn98.adoc
- content/projects/jcasc/dev-tools.adoc
- content/projects/jcasc/index.adoc
Added the inital draft for the JCasc Dev-Tools community Bridge project.
> Added community bridge JCasc Dev-Tools project page.

- content/projects/advocacy-and-outreach/outreach-programs.adoc
It should fix the issues with the QR code on the Outreach Programs poster.
CC @martinda @alyssat
> Add a redirect for outreach programs

- content/blog/2019/07/2019-07-17-DevOps-World-Jenkins-World-2019-San-Francisco-Lunch-Demos.adoc
Adding the demo for the plugin installation manager CLI tool, by Natasha Stopa.
@stopalopa @alyssat @bitwiseman @oleg-nenashev
> Add plugin cli tool demo

- content/blog/2019/08/2019-08-16-folder-auth-plugin.adoc
Move the image to above the 'Performance Improvements over Role Strategy Plugin' section as suggested by @oleg-nenashev in https://gitter.im/jenkinsci/role-strategy-plugin?at=5d56c295beba830fffa3a565
@oleg-nenashev @supun94 @runzexia
> Folder Auth Blog: Move configuration image

- content/doc/book/blueocean/creating-pipelines.adoc
Local repository works for certain specific cases, but does not lead the user to as generally useful a solution as a remote repository.
> Recommend remote repository with Blue Ocean tutorial

- content/doc/tutorials/build-a-multibranch-pipeline-project.adoc
A user reported this spelling error on Aug 15, 2019 through page feedback.
> Fix spelling error reported thru page feedback

- content/blog/2019/08/2019-08-16-folder-auth-plugin.adoc
- content/projects/gsoc/2019/role-strategy-performance.adoc
@oleg-nenashev @runzexia @supun94
> GSoC Role Strategy: Add demo link to blog and project page

- content/sigs/advocacy-and-outreach/index.adoc
- content/sigs/advocacy-and-outreach/outreach-programs/index.adoc
subj. I have been unable to find a good logo image, so I am I just put some text for now.
Also removed Google Code-In, because there is no entry for it. We were not accepted last year, and I believe we won't apply this year, no capacity.
> Add information about Community Bridge to Advocacy & Outreach resources

- content/projects/gsoc/2019/plugin-installation-manager-tool-cli.adoc
https://issues.jenkins-ci.org/browse/JENKINS-59038
Unless there's additional feedback you want to add, I think the only thing it's currently missing is a link to the presentation video from the Jenkins Online Meetup earlier today.
> [JENKINS-59038] Add final eval presentation slides

- content/blog/2019/08/2019-08-23-introducing-gitlab-branch-source-plugin.adoc
Adding thumbnail to blog and description.
@oleg-nenashev @markyjackson-taulia
> Update blog thumbnail

- content/projects/gsoc/2019/role-strategy-performance.adoc
@oleg-nenashev 	@runzexia 	@supun94
> GSoC: Update project for Role Strategy

- content/press.adoc
include jenkinsci-cert for security press issues.
> security and press

- content/doc/book/pipeline/syntax.adoc
Reverts jenkins-infra/jenkins.io#2450
> Revert "[JENKINS-59115] Documentation for branch when condition with comparator"

- content/_data/events/2019-09-11-triangle-jam.adoc
- content/_data/events/2019-09-25-jamsterdam.adoc
- content/_data/events/2019-10-03-codeconf-aarhus.adoc
CC @MadsNielsen @pkthunda @tracymiranda @alyssat
> Add incoming Jenkins meetups to the website

- content/_data/events/2019-09-05-jom-summer-projects-3.adoc
> Add an event page for the third GSoC/Outreachy demos JOM

- content/blog/2019/08/2019-08-23-introducing-gitlab-branch-source-plugin.adoc
Change pull request to merge request, Because the context is GitLab.
> change pull request to merge request

- content/_layouts/developerbook.html.haml
- content/doc/developer/development-environment/_chapter.yml
- content/doc/developer/development-environment/ide-configuration.adoc
- content/doc/developer/development-environment/index.adoc
- content/doc/developer/development-environment/taglibs.adoc
- content/doc/developer/forms/_chapter.yml
- content/doc/developer/forms/adding-tool-tips.adoc
- content/doc/developer/forms/form-validation.adoc
- content/doc/developer/forms/index.adoc
- content/doc/developer/forms/jelly-form-controls.adoc
- content/doc/developer/forms/structured-form-submission.adoc
- content/doc/developer/internationalization/prepare-a-java-source-file.adoc
- content/doc/developer/views/index.adoc
All feedback welcomed, happy to swap anything back to wip if needed but the goal was to fill out the whole chapter.
It's mostly came from the WIKI with removals and additions here and there
> Fill out forms chapter

- .github/CODEOWNERS
Let's add some automation for documentation and site content reviews.
CC @MarkEWaite
> Automatically request copy-editors to review all content pull requests

- content/_data/changelogs/lts.yml
- content/_data/upgrades/2-190-1.adoc
> <img width="1688" alt="Screenshot 2019-09-13 at 10 09 31" src="https://user-images.githubusercontent.com/1831569/64847203-c7b62500-d60e-11e9-8c32-b440e970f0e6.png">
> Add changelog for 2.190.1

- content/doc/developer/security/secrets.adoc
> More details on Secret use

- content/_data/upgrades/2-190-1.adoc
Follow-up to the discussion in #2473 .
The entry basically repeats the changelog entry, but I believe it worth keeping it in the upgrade guide
> Add JENKINS-37862 to the 2.190.1 upgrade guide

- content/projects/gsoc/2018/code-coverage-api-plugin.adoc
- content/projects/gsoc/2018/eda-plugins.adoc
- content/projects/gsoc/2018/remoting-over-message-bus.adoc
- content/projects/gsoc/2018/simple-pull-request-job-plugin.adoc
- content/projects/gsoc/2019/artifact-promotion-plugin-for-jenkins-pipeline.adoc
- content/projects/gsoc/2019/ext-workspace-manager-cloud-features.adoc
- content/projects/gsoc/2019/gitlab-support-for-multibranch-pipeline.adoc
- content/projects/gsoc/2019/plugin-installation-manager-tool-cli.adoc
- content/projects/gsoc/2019/remoting-over-apache-kafka-docker-k8s-features.adoc
- content/projects/gsoc/2019/role-strategy-performance.adoc
- content/projects/gsoc/2019/working-hours-improvements.adoc
- content/projects/gsoc/index.adoc
All the projects are completed, so it makes sense to update the status
> GSoC 2019 - Update statuses of projects

- content/_layouts/post.html.haml
- content/_partials/author.html.haml
Follow-up to #2479 . CC @zbynek
> Improve layout for blogposts with multiple authors

- content/events/hacktoberfest.adoc
Cleans up the documentation levels and the obsolete text from the previous years
> Hacktoberfest 2019 - Cleanup the text a bit

- .github/CODEOWNERS
subj. Just to save our time in future iterations
> GSoC - Automatically request reviews from the GSoC team for the GSoC content

- content/doc/developer/publishing/removing-from-distribution.adoc
Following https://github.com/jenkins-infra/update-center2/pull/299 it might be easier to point directly to the file that needs editing.
CC @daniel-beck
> Direct link to plugin removal

- content/events/hacktoberfest.adoc
Get more details from https://jenkins.io/blog/2019/08/30/jenkins-cli/ or just read the [GitHub project](https://github.com/jenkins-zh/jenkins-cli).
> Add Jenkins-CLI written which written in go into hackathon project list

- content/events/hacktoberfest.adoc
- content/events/hacktoberfest/event-kit.adoc
CC @markyjackson-taulia @MarkEWaite
> Hacktorfest 2019: Add listing of events and a Jenkins-specific Event kit

- content/events/hacktoberfest.adoc
- content/events/hacktoberfest/faq.adoc
> Hacktoberfest 2019 - Move FAQ to a separate page

- content/_data/events/2019-10-10-Hacktoberfest-in-Neuchâtel: Jenkins & Friends.adoc
- content/_data/events/2019-10-10-swissjam-neuchatel..adoc
Fixing the Data file for Swiss JAM on Oct 10. It includes special symbols in the path, and the master branch does not even check out on my local machine correctly.
CC @alyssat @MarkEWaite
> Update and rename 2019-10-10-Hacktoberfest-in-Neuchâtel

- LICENSE.adoc
Fix missing broken image link and code block style.
> Fix Asciidoc syntax in License

- content/blog/2019/09/2019-09-25-board-elections.adoc
- content/index.html.haml
Follow-up on https://groups.google.com/forum/#!msg/jenkinsci-dev/v8kmEQMT0ts/l8yQ43WNAwAJ and the discussion in advocacy and outreach SIG.
> 2019 Elections - Add an announcement blogpost and Jumbotron

- content/_data/events/2019-10-03-jom-hacktoberfest-1.adoc
- content/_data/events/2019-10-03-jom-hacktoberfest-2.adoc
- content/events/hacktoberfest.adoc
> Hacktoberfest 2019 - Add Jenkins Online Meetups to the event list

- Makefile
- content/blog/2010/2010-02-11-spotlight-on-ita-software.md
- content/blog/2010/2010-02-14-thanks-for-the-help.md
- content/blog/2010/2010-02-17-getting-started-building-android-apps-with-hudson.md
- content/blog/2010/2010-02-18-spotlight-on-visfleet.md
- content/blog/2010/2010-02-25-spotlight-on-springsource.md
- content/blog/2013/2013-07-24-jenkins-user-event-in-copenhagen-on-september-6.html
- content/blog/2017/04/2017-04-05-welcome-to-blue-ocean.adoc
- content/blog/2018/06/2018-06-21-jenkins-x-devpods.adoc
- content/blog/2019/07/2019-07-30-plugin-management-tool-phase2-updates.adoc
- content/changelog-old.html
- package-lock.json
- package.json
- scripts/check-broken-links
This allows you to run `blc` by running `make check-broken-links`. Not included in Jenkinsfile so far. 
Also all missing decorative images and are removed together with outdated links, some recent links are fixed.
CC @vkotovv
> Add task for checking broken links

- content/events/hacktoberfest.adoc
some text improvements + using the Jenkins X blog as a source of Jenkins X information. CC @MarkEWaite @MarckK
> Hacktoberfest 2019 - Copy-edit the featured Project descriptions

- content/events/hacktoberfest.adoc
CC @markyjackson-taulia @baymac
> Hacktoberfest 2019 - Add Gitlab and Prometheus plugins as featured projects, move Jenkins website to the top

- content/events/hacktoberfest.adoc
Also modifies the space character used in one of the paragraphs to be consistent with the rest of the paragraphs.
Modifies layout of the Hacktoberfest table so that keywords each appear on their own line for easier reading in the table layout.
> Add platformlabeler as a featured Hacktoberfest project

- content/doc/book/installing/_docker.adoc
Hello,
In this PR, I fix **accessing-the-jenkins-blue-ocean-docker-container** link.
Thank you for your review.
> #hacktoberfest 2019 -  Fix accessing-the-jenkins-blue-ocean-docker-container link

- .github/CODEOWNERS
> Automatically request reviews from the Hacktoberfest team for the Hactoberfest page changes

- content/events/hacktoberfest.adoc
- content/events/hacktoberfest/event-kit.adoc
subj. I will add links to the video later once it is processed
> Hacktoberfest 2019 - Add links to the introductory slides

- content/doc/book/blueocean/creating-pipelines.adoc
Hello,
In this PR, I fix **choose-your-github-account-organization-and-repository** doc links.
Thank you for your review
> #hacktoberfest 2019 - Fix choose-your-github-account-organization-and-repository doc links

- CONTRIBUTING.adoc
Creating guidelines as it was discussed in the Documentation SIG.
> Contributing: Document how to move documentation from Wiki using Pandoc

- content/events/hacktoberfest/faq.adoc
Subj. This FAQ documents the current ways to get statistics about Hacktoberfest
I think some CDF metrics are really helpful for such event. FYI @tracymiranda @MarckK
> Hacktoberfest 2019 - Add FAQ for maintainers and event organizers

- content/participate/index.html.haml
I have merged help and discuss sections with the links like discuss.
> Merge help and discuss sections

- content/participate/design.adoc
- content/participate/index.html.haml
My proposition for improvement https://issues.jenkins-ci.org/browse/WEBSITE-665
I've kept the link to the jenkins website being put twice (once for the artwork, once for the website itself) as in the input slides.
Happy merging!
> Added a participate/design page

- content/_data/authors/sladyn98.adoc
- content/blog/2016/2016-03-15-jenkins-certification.adoc
- content/blog/2016/2016-08-08-docker-pipeline-environments.adoc
As for Sladyn, refer to:
https://github.com/sladyn98
https://twitter.com/SladynN
> Fix some invalid Github profile links in blog posts (Hacktoberfest 2019)

- content/doc/developer/forms/structured-form-submission.adoc
The sample starts with `option` and is replaced my `optin`
> Fix misprint

- content/security/advisory/2019-09-25.adoc
https://groups.google.com/d/msg/jenkinsci-dev/py4Q5FDTRUI/sVDZyx8wCAAJ
> Mention both versions released on the day of the advisory

- content/blog/2019/10/2019-10-21-plugin-docs-on-github.adoc
> Fix the Plugin Migration guide link in the blogpost

- content/participate/index.html.haml
- content/participate/test.adoc
Contributing to this issue: 
https://issues.jenkins-ci.org/browse/WEBSITE-664
> [WEBSITE-664] Add testing.adoc in participate content

- content/events/index.html.haml
- content/sigs/platform/index.adoc
The Platform Sig changed the meeting time, but forgot to update the site.
Hacktoberfest
> Make Platform Sig meeting time 12:00 UTC

- CONTRIBUTING.adoc
Just extended guidelines a bit to follow-up on issues experienced by submitters during Hacktoberfest
> Contributing: Extend guidelines for adding new logos

- content/_data/events/2019-12-02-devops-world-jenkins-world-lisbon.adoc
- content/_partials/events.html.haml
- content/css/jenkins.css
I've added the possibility to display events which span multiple days. 
Here is a screenshot which shows how multi day events look like.
In order to fit the range in one line i had to increase the width of the event by .3em.
> [WEBSITE-661] Add support of multi-day events

- content/participate/index.html.haml
- content/participate/test.adoc
I have separated manual and automated testing.
> Separate sections for manual and automated testing

- content/_data/events/2019-12-02-dw-jw-hackfest.adoc
> Create an event for the DW_JW Hackfest on Dec 02

- content/_data/events/2019-11-05-st-petersburg.adoc
> Create an event for St. Petersburg JAM on Nov 05

- content/participate/index.html.haml
- content/participate/review-changes.adoc
ISSUE: https://issues.jenkins-ci.org/browse/WEBSITE-667
> Updated Review Changes Section in content/participate

- content/index.html.haml
The dates are updated based on https://jenkins.io/blog/2019/11/08/board-elections/
> Update election anouncement Jumbotron

- content/doc/book/pipeline/syntax.adoc
Documentation for https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/356
> [JENKINS-51865] Document new beforeOptions in 'when'

- content/participate/meet.adoc
> Improve the participate/meet page: add content, fix blogpost listing

- content/mailing-lists/index.html.haml
Follow-up to the Gitter discussion, CC @MarkEWaite @sladyn98 @zbynek
> Add a Jenkins UX mailing list to the listing

- content/_data/events/2019-11-20-jom-poet-pipeline-lib.adoc
- content/_data/events/2019-11-22-jom-plugin-docs.adoc
> Add Jenkins Online Meetups on Nov 20 and 22

- content/_data/logo/yaroslavl.yml
The author of the Yaroslavl meetup logo is incorrectly specified. Fixed that.
> Fixed the author of the Yaroslavl meetup logo

- content/blog/2019/10/2019-10-21-plugin-docs-on-github.adoc
- content/doc/developer/publishing/wiki-page.adoc
- content/projects/infrastructure/index.adoc
> Cleanup the Jenkins Wiki exporter links after publishing the service on jenkins.io

- content/_data/changelogs/weekly.yml
See https://github.com/jenkins-infra/jenkins.io/pull/2619#discussion_r348505043
See https://github.com/jenkins-infra/jenkins.io/pull/2636#discussion_r344865667
> Fix changelog errors and improve formatting

- content/projects/infrastructure/index.adoc
> [WEBSITE-679] - Document INFRA team meetings and add metadata for sub-project pages

- content/doc/administration/requirements/web-browsers.adoc
Implements the discussion in https://groups.google.com/forum/#!topic/jenkinsci-dev/TV_pLEah9B4
After:
Before:
> Document browser support policy as discussed in the mailing list

- content/blog/2019/11/2019-11-22-jenkins-health-advisor-by-cloudbees.adoc
Enhancement proposed by jgbiii. Thanks James
> Title update

- content/blog/2019/11/2019-11-22-jenkins-health-advisor-by-cloudbees.adoc
I just discovered the "free as in beer" vs "free as in speech". thanks @oleg-nenashev
> Clarify the "free" wording

- content/participate/review-changes.adoc
I don't think `retrospective` was intended here 🤷‍♂
> Fix typo on review changes page

- content/doc/developer/plugin-development/writing-an-scm-plugin.adoc
- content/projects/gsoc/2020/project-ideas.html.haml
- content/projects/gsoc/2020/project-ideas/artifactory-rest-plugin copy.adoc
- content/projects/gsoc/2020/project-ideas/artifactory-rest-plugin.adoc
- content/projects/gsoc/2020/project-ideas/automatic-spec-generator-for-jenkins-rest-api.adoc
- content/projects/gsoc/2020/project-ideas/bitbucket-rest-plugin.adoc
- content/projects/gsoc/2020/project-ideas/code-coverage-api-improvements.adoc
- content/projects/gsoc/2020/project-ideas/eda-coverage-adapters.adoc
- content/projects/gsoc/2020/project-ideas/eda-plugins.adoc
- content/projects/gsoc/2020/project-ideas/external-fingerprint-storage-for-jenkins.adoc
- content/projects/gsoc/2020/project-ideas/jenkins-rest-plugin.adoc
- content/projects/gsoc/2020/project-ideas/machine-learning.adoc
- content/projects/gsoc/2020/project-ideas/pipeline-step-documentation-generator.adoc
- content/projects/gsoc/2020/project-ideas/remoting-monitoring.adoc
- content/projects/gsoc/2020/project-ideas/winsw-yaml-config-support.adoc
I have copied the GSoC 2019 project ideas which could be taken in 2020. List of mentors has been partially cleaned up, but all ideas are listed as draft for now. CC @kwhetstone @cizezsy @markyjackson-taulia @kwhetstone @LinuxSuRen  @darthholi @imoutsatsos @jeffret-b @kinow , please let me know whether you want to remain on the list.
> [GSoC 2020] - Copy viable GSoC 2019 project ideas to GSoC 2020

- content/projects/gsoc/2020/application.md
- content/projects/gsoc/2020/index.adoc
- content/projects/gsoc/index.adoc
- content/projects/gsoc/mentors.adoc
- content/projects/gsoc/students.adoc
Creating the initial resources for GSoC 2020. Depends on #2684 which copies some content removed in this pull request
CC @arnab1896
> [GSoC 2020] - Rework landing for 2020 + update the application and mailing list links

- content/projects/gsoc/2018/index.adoc
> Fix typo in GSoC 2018 index page

- content/sigs/docs/index.adoc
While I was around, made some content adjustments
> Minor cleanup for the Docs SIG page

- content/doc/book/pipeline/syntax.adoc
See [JENKINS-60217](https://issues.jenkins-ci.org/browse/JENKINS-60217).
Documentation for the `changeset` when condition with comparator. Similar to:
- https://github.com/jenkins-infra/jenkins.io/pull/2450
Downstream of https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/366
> Documentation for changeset when condition with comparator

- content/participate/document.adoc
I could have added more links, but it already looks like a good start for the newcomers.
Before:
After:
> [WEBSITE-680] - Add actual content to /participate/document

- content/projects/jcasc/index.adoc
@daniel-beck 's PR + @MarkEWaite 's suggestion.
Replaces #2627
> Expand info about mailing lists for JCasC

- content/index.html.haml
the event is over 🤷‍♂ 
CC @alyssat
> Remove the DevOps World | Jenkins World jumbotron

- content/blog/2019/12/2019-12-14-generic-webhook-trigger-plugin.adoc
Should fix the CI failure, not sure why it was not detected before #2701 was merged.
> Fix asciidoc formatting

- content/participate/index.html.haml
I have Aligned the "Read More" button in each grid on bottom left corner
> Fixed alignment "Read More" button in jenkins.io/participate

- content/_data/changelogs/lts.yml
- content/_data/upgrades/2-204-1.adoc
> Add 2.204.1 changelog and upgrade guide

- content/_data/changelogs/lts.yml
- content/_data/upgrades/2-204-1.adoc
> Fix several errors in the 2.204.1 changelog and upgrade guide

- content/_data/changelogs/lts.yml
- content/_data/upgrades/2-204-1.adoc
Updates based on @daniel-beck feedback on part 2 of the changelog for 2.204.1
> Changelog 2.204.1 part3

- content/projects/infrastructure/index.adoc
Adds a service + some links
CC @TobiX
> [WEBSITE-678] - Add a mirrors.jenkins.io to the services list

- content/css/jenkins.css
the ! and the space makes this very invalid
https://github.com/jenkins-infra/jenkins.io/blob/f35aca63be3a6e899559f1516c77b93fd6ced778/content/css/jenkins.css#L195-L197
And then i couldn't find it in use anywhere doing an org wide search - https://github.com/search?q=org%3Ajenkins-infra+ji-home-carousel&type=Code
then did a build and grep
So i think its safe to delete.
> Remove some dead old css which isn't actually used

- content/doc/developer/development-environment/ide-configuration.adoc
> Add Visual Studio Code debugging notes to ide-configuration.adoc

- content/project/governance.adoc
Leftover after the recent elections and the process change
> Fix the number of board members in the Governance doc

- content/blog/2019/12/2019-12-20-call-for-mentors.adoc
This is a trivial PR for typos.
> Fix typos in gsoc call for mentors 2020

- content/projects/gsoc/proposing-project-ideas.adoc
Based on the [mailing list suggestion](https://groups.google.com/forum/#!topic/jenkinsci-gsoc-all-public/-9aKO9hncKQ)
> Improve GSoC idea submission process

- content/_data/authors/oleg_nenashev.adoc
I should do int more often....
> Update @oleg-nenashev's bio

- content/_data/authors/jphartley.adoc
- content/sigs/ux/index.adoc
Created UX SIG section for https://jenkins.io/sigs/ for the new Jenkins UX SIG
I created this by copying the docs section. 
Please let me know if I missed anything. I am new to AsciiDoc
> Create UX SIG section

- content/_data/changelogs/weekly.yml
Fixes the regressions version as noticed by @jglick + adds another reported regression
> Changelog: Amend the 2.213 entry

- content/_data/events/2020-01-15-Denver-NADOG.adoc
Talk will be Jan 15, 2020 in Denver, Colorado, USA.
> Add Denver NADOG event

- content/projects/gsoc/2020/application.md
Just few minor updates to reflect minor form changes. Also, added TODOs for sections we need to review/update
> GSoC 2020 - update the doc according to 2020 application forms

- content/projects/gsoc/2020/project-ideas/eda-plugins.adoc
This change adds the missing sections to the EDA Plugin integration GSoC idea
> [GSoC 2020] - Finalize the EDA Plugin project idea and move it to the published state

- content/projects/gsoc/2020/project-ideas/git-plugin-caching.adoc
> Add URL for pull request 502

- content/sigs/docs/index.adoc
Also replaces some UTF-8 multi-byte space characters with ASCII spaces.
> Replace wiki links with jenkins.io links

- content/projects/gsoc/2020/project-ideas/git-plugin-performance.adoc
Also adds another Quickstart suggestion; increase test coverage.
> Publish git plugin performance idea for GSoC 2020

- content/redirect/crumb-cannot-be-used-for-script.md
Companion of https://github.com/jenkinsci/jenkins/pull/4443
> Add redirection for SEC-626 log improvement

- content/projects/gsoc/2020/project-ideas/docker-registries-polling-plugin.adoc
Added this project to a list of potential Project ideas for 2020
> Added docker polling project

- content/_data/changelogs/weekly.yml
> Improve the 2.217 changelog

- content/projects/gsoc/mentors.adoc
This is a major update to the mentor document as discussed during the weekly GSoC meeting.
Please review carefully. I think this is the last major GSoC documentation update for 2020 year.
> Update the GSoC mentor expectations

- content/_ext/authorship.rb
- content/projects/gsoc/2020/project-ideas.html.haml
- content/projects/gsoc/2020/project-ideas/artifactory-rest-plugin.adoc
- content/projects/gsoc/2020/project-ideas/automatic-spec-generator-for-jenkins-rest-api.adoc
- content/projects/gsoc/2020/project-ideas/bitbucket-rest-plugin.adoc
- content/projects/gsoc/2020/project-ideas/eda-coverage-adapters.adoc
- content/projects/gsoc/2020/project-ideas/eda-plugins.adoc
- content/projects/gsoc/2020/project-ideas/jenkins-rest-plugin.adoc
- content/projects/gsoc/2020/project-ideas/pipeline-step-documentation-generator.adoc
Reverts jenkins-infra/jenkins.io#2800 , because it failed CI
CC @martinda @timja
> Revert "Withdrawing my name from GSoC projects"

- content/_ext/authorship.rb
- content/_layouts/gsocproject.html.haml
- content/_layouts/gsocprojectidea.html.haml
- content/projects/gsoc/2020/project-ideas.html.haml
- content/projects/gsoc/2020/project-ideas/artifactory-rest-plugin.adoc
- content/projects/gsoc/2020/project-ideas/automatic-spec-generator-for-jenkins-rest-api.adoc
- content/projects/gsoc/2020/project-ideas/bitbucket-rest-plugin.adoc
- content/projects/gsoc/2020/project-ideas/eda-coverage-adapters.adoc
- content/projects/gsoc/2020/project-ideas/eda-plugins.adoc
- content/projects/gsoc/2020/project-ideas/jenkins-rest-plugin.adoc
- content/projects/gsoc/2020/project-ideas/pipeline-step-documentation-generator.adoc
Reattempting #2800 with a fix for failing haml files.
> Gsoc withdraw martinda

- content/projects/gsoc/2020/project-ideas/machine-learning.adoc
> Converting draft to published asic doc

- content/projects/gsoc/2019/index.adoc
> [GSoC 2019] - link the project report from the 2019 page

- content/projects/gsoc/2020/application.md
Minor copy-editing and detalization in the text
> GSoC 2020 - Update the application

- content/projects/gsoc/2020/application.md
Minor typo fixes. I checked in the application form on the GSoC website and those typos are not there. So we only need to fix this document.
> GSoC 2020 application typo fixes

- content/projects/gsoc/2020/project-ideas/github-checks.adoc
See discussion in [mailing list](https://groups.google.com/d/msg/jenkinsci-dev/UGhDM5lcz8Y/P9W4i_B5BAAJ)
> Convert draft of GitHub Checks API for Jenkins Plugins to AsciiDoc

- content/projects/gsoc/2020/project-ideas/automatic-spec-generator-for-jenkins-rest-api.adoc
- content/projects/gsoc/2020/project-ideas/pipeline-step-documentation-generator.adoc
@jenkins-infra/gsoc 
Added the asciidoc to the proposal pages for the 2 documentation project ideas.  I've posted the drafts in the documentation gitter channel to gauge additional interest in mentoring.  The proposals have been updated with the changes from work done over the past year, and some general updates in technology.  I left them in draft state until given the thumbs up by the admins.  Pending review
> Update proposals with asciidoc

- content/projects/gsoc/2020/application.md
Reflecting changes I did during the submission
> GSoC 2020 - More application updates

- content/projects/gsoc/2018/index.adoc
- content/projects/gsoc/2019/index.adoc
- content/projects/gsoc/2020/project-ideas.html.haml
- content/projects/gsoc/gsoc2016.adoc
> GSoC - clarify the project idea states, add links to GSoC retrospectives

- content/doc/developer/plugin-development/writing-an-scm-plugin.adoc
While I'm learning this how-to, I fixed some typos and added some missed links to improve the reading experience according to [the original page](https://wiki.jenkins.io/display/JENKINS/Writing+an+SCM+plugin).
> improved writing-an-scm-plugin.adoc

- content/projects/infrastructure/ircbot.adoc
Requires https://github.com/jenkins-infra/ircbot/pull/75
> Document new ircbot commands

- content/sigs/ux/index.adoc
Removed all references to the CDF Slack and added a link and references to the Gitter room jenkinsci/ux-sig
> Remove Slack references. Add Gitter References

- content/projects/gsoc/2020/project-ideas/jenkins-rest-plugin.adoc
As discussed at the SIG meeting, I would like to move this project to the discussion status. I started a discussion on the mailing list for adoption of this idea: https://groups.google.com/forum/#!topic/jenkinsci-gsoc-all-public/elEudjY_09w
> Move jenkins-rest gsoc idea to discussion status

- content/projects/gsoc/2020/project-ideas/artifactory-rest-plugin.adoc
As discussed at the SIG meeting, I'd like to move this idea to the discussion status. I started an email thread for its adoption: https://groups.google.com/forum/#!topic/jenkinsci-gsoc-all-public/L-bmNWNxHGg
> Move artifactory-rest gsoc idea to discussion status

- content/projects/gsoc/2020/project-ideas/pipeline-as-yaml-experiment.adoc
Submitting a draft for the discussion. Will start a mailing list thread and reference the pull request from it.
Discussion: https://groups.google.com/forum/#!topic/jenkins-pipeline-authoring-sig/Ko8KTEcK_vY
> GSoC Project Idea Draft - Experimental Pipeline as YAML plugin

- Jenkinsfile
- content/_partials/mailing-lists/group.html.haml
- content/_partials/mailing-lists/jenkins-infra.adoc
- content/download/mirrors.adoc
- content/mailing-lists/index.html.haml
- content/projects/infrastructure/index.adoc
https://issues.jenkins-ci.org/browse/INFRA-2474
> INFRA-2474 - Moved infra mailing list

- content/projects/gsoc/2020/project-ideas/git-plugin-performance.adoc
> GSoC 2020 - Add tags to the Git plugin performance project idea, add @oleg-nenashev as a potential mentor

- content/projects/gsoc/2020/project-ideas/docker-registries-polling-plugin.adoc
Just a minor fix to get it published. CC @sladyn98 @afalko @justinharringa
> GSoC 2020 - Polling Docker Registries: fix Jira query and publish the idea

- content/projects/gsoc/2020/project-ideas/jenkins-x-boot-apps.adoc
This change slightly improves the look&feel for the project idea
CC @MarckK @jstrachan @markyjackson-taulia 
I have another action item to link communication channels properly
> GSoC 2020: Minor updates for the JX Boot Apps project idea

- Jenkinsfile
Any build failing here is causing an email to go to the infra mailing list, annoying people...
I don't think we need this?
> Stop spamming infra mailing list

- content/projects/gsoc/2020/project-ideas/jenkins-x-apps-consolidation.adoc
- content/projects/gsoc/2020/project-ideas/jenkins-x-boot-apps.adoc
I updated the JX project ideas to explicitly refer the Quick Start sections . It should be enough to get this idea published IMHO. Along with newbie-friendly issue, the guide should provide enough information
CC @MarckK @jstrachan @MarckK @nehagup
> GSoC 2020 - Publish the JX project ideas

- content/doc/developer/plugin-governance/_chapter.yml
- content/doc/developer/plugin-governance/adopt-a-plugin.adoc
- content/doc/developer/plugin-governance/deprecating-or-removing-plugin.adoc
Follow-up to https://groups.google.com/forum/#!topic/jenkinsci-dev/UoEqG5AaWJU and to the recent changes in the update center which made it possible
> Rework the plugin adoption process, document the plugin deprecation and removal

- content/_data/authors/mikecirioli.adoc
- content/projects/gsoc/2020/project-ideas/artifactory-rest-plugin.adoc
- content/projects/gsoc/2020/project-ideas/docker-registries-polling-plugin.adoc
- content/projects/gsoc/2020/project-ideas/external-fingerprint-storage-for-jenkins.adoc
- content/projects/gsoc/2020/project-ideas/jenkins-x-apps-consolidation.adoc
- content/projects/gsoc/2020/project-ideas/pipeline-step-documentation-generator.adoc
- content/projects/gsoc/2020/project-ideas/remoting-monitoring.adoc
- content/projects/gsoc/2020/project-ideas/winsw-yaml-config-support.adoc
I am also opening to mentoring other projects if there is a need
https://groups.google.com/d/msg/jenkinsci-gsoc-all-public/NP8pYlLTZds/g0NBOSBbCAAJ
> Add mike cirioli to projects he is interested in mentoring

- content/doc/book/installing/_docker-for-tutorials.adoc
- content/doc/book/installing/_docker.adoc
Tutorial docker images are not available for Windows containers.
See #2883 for the start of the conversation
> Windows containers not supported, use Linux

- content/projects/gsoc/index.adoc
Change the intro lines since we've been accepted.
> GSoC 2020 accepted

- content/doc/developer/views/_chapter.yml
- content/doc/developer/views/read-only.adoc
Ref:
https://github.com/jenkinsci/jenkins/pull/4479
https://github.com/jenkinsci/jenkins/pull/4149
https://github.com/jenkinsci/jenkins/compare/master...timja:jep-224
> Add read-only view docs

- content/sigs/gsoc/index.adoc
Perhaps these lists need a refresh. I am sure I have forgotten people...
> Update list of gsoc participants

- content/projects/gsoc/2020/project-ideas/plugin-installation-manager-tool.adoc
> GSoC 2020 - Fix rendering of Quickstart in the Plugin Installation Manager project

- content/projects/gsoc/2020/project-ideas/pipeline-as-yaml-experiment.adoc
See https://groups.google.com/forum/#!topic/jenkinsci-dev/6ieyOlLQX0I for the context
> Move the Pipeline as YAML project idea back to drafts

- content/blog/2020/03/2020-03-02-pipeline-authoring-sig-update.adoc
> Amending blog post with a new `contact us` section

- content/projects/gsoc/index.adoc
Adds links which might be useful during the application phase
> GSoC 2020 - polish landing

- content/projects/gsoc/2020/application.md
Improves look&feel and searchability a bit + Continuous Delivery Foundation reference in the long description
> GSoC 2020 - minor profile updates

- content/press.adoc
> Fix the CDF projects link on the /press page

- content/project/team-leads.adoc
> Update events officer role

- content/doc/book/architecting-for-scale.adoc
There are some additional places, but they reference things that still may have "slave" in the name.
> Reword using correct term

- content/solutions/pipeline.adoc
Some links were outdated, others no longer functional or contained irrelevant information.
Also adds link to "Declarative Pipeline with Jenkins" video recorded by Kohsuke Kawaguchi, Mark Waite, and Tyler Johnson.
> Refresh Pipeline solutions links

- content/projects/gsoc/2020/project-ideas/jenkins-rest-plugin.adoc
Updating jenkins-rest-plugin state from discussion to draft and Adding details about the project.
> Updating jenkins-rest-plugin state

- content/_data/authors/nextturn.adoc
- content/projects/gsoc/2020/project-ideas/winsw-yaml-config-support.adoc
My application is in the Jenkins Platform SIG mailing list:
https://groups.google.com/forum/#!topic/jenkins-platform-sig/5HqNXgza9LI
> Add NextTurn to mentors

- content/projects/jcasc/dev-tools.adoc
> Changed status to completed

- content/doc/book/pipeline/syntax.adoc
> Spelling fix

- content/projects/gsoc/2020/project-ideas/jenkins-x-openwrt-ppa.adoc
add jenkins-x-openwrt-ppa.adoc
> add jenkins-x-openwrt-ppa.adoc

- content/_data/authors/zoobab.adoc
- content/projects/gsoc/2020/project-ideas/remoting-monitoring.adoc
CC @zoobab @pvtuan10 @jeffret-b
> GSoC 2020 - Update project mentors for Remoting Monitoring and Jenkins X

- content/_data/authors/aytuncbeken.adoc
- content/projects/gsoc/2020/project-ideas/pipeline-as-yaml-experiment.adoc
CC @aytuncbeken . Taking the discussion in the mailing list, I believe we can publish it again for now. https://github.com/aytuncbeken/pipeline-as-yaml is referenced in the text now
> GSoC 2020 - Add @aytuncbeken as mentor, mark the Pipeline as YAML project idea as accepted

- content/projects/gsoc/index.adoc
> GSoC 2020 - Add Jenkins Online Meetup Materials, reorder content

- content/_data/changelogs/lts.yml
- content/_data/changelogs/weekly.yml
- content/_data/upgrades/2-138-2.adoc
- content/_data/upgrades/2-150-2.adoc
- content/_data/upgrades/2-32-1.adoc
- content/_data/upgrades/2-32-2.adoc
- content/_data/upgrades/2-7-1.adoc
- content/_partials/changelog-old.html
- content/_partials/changelog-stable.html
- content/blog/2018/10/2018-10-10-security-updates.adoc
- content/doc/book/architecting-for-scale.adoc
- content/doc/book/installing/_jenkins-command-parameters.adoc
- content/doc/book/managing/system-properties.adoc
- content/redirect/setting-system-properties.adoc
- content/security/advisory/2016-06-20.adoc
- content/security/advisory/2017-02-01.adoc
- content/security/advisory/2017-08-07.adoc
- content/security/advisory/2018-12-05.adoc
- content/security/advisory/2019-07-17.adoc
- content/security/advisory/2019-09-25.adoc
Just a hyperlink cleanup after #2992
> Replace Wiki Page links for Managing System Properties

- content/projects/gsoc/2020/project-ideas/automatic-spec-generator-for-jenkins-rest-api.adoc
Better late than never, I'd guess
> GSoC 2020 - Add Quick start and Newbie friendly issues to the REST API Spec generator idea, publish it

- content/_data/changelogs/lts.yml
- content/_data/upgrades/2-222-1.adoc
> Describe JENKINS-61688 in 2.222.1 upgrade guide and changelog

- content/_data/changelogs/lts.yml
https://github.com/jenkins-infra/jenkins.io/pull/3005#issuecomment-604462085
Untested.
> Reduce changelog yellowness

- content/projects/gsoc/mentors.adoc
- content/projects/gsoc/roles-and-responsibilities.adoc
Updating the Roles and Responsibilities document.
The intent is to merge #2996 first, then this one. I made the updates in different PRs in case one takes longer than the other to review.
> Gsoc roles and responsibilities update

- content/projects/gsoc/2020/project-ideas/jenkins-x-apps-consolidation.adoc
- content/projects/gsoc/2020/project-ideas/jenkins-x-boot-apps.adoc
> Removing myself from GSoC jx mentors project list

- content/_data/authors/sahilrkalra.adoc
@markyjackson-taulia I've Fixed linkedin url for sahil in mentor list, please review it.
> Fixed linkedin url for sahil in mentor list

- content/projects/gsoc/mentors.adoc
Before this pull request, [Community Bonding](http://localhost:4242/projects/gsoc/mentors/#community_bonding_phase) looks like this:
After this pull request, it will look like this:
> Make community bonding list render as a list

- content/projects/gsoc/mentors.adoc
Document how mentor teams are formed and when.
> Forming gsoc mentor teams

- content/_layouts/advisory.html.haml
- content/_layouts/security.html.haml
- content/security/advisories.html.haml
- content/security/cna.adoc
- content/security/fixing.adoc
- content/security/for-administrators.adoc
- content/security/for-maintainers.adoc
- content/security/improvements.adoc
- content/security/index.adoc
- content/security/plugins.adoc
- content/security/reporting.adoc
- content/security/scheduling.adoc
- content/security/team.adoc
<details>
<summary>Screenshots of some of the pages</summary>
</details>
Note for the security team: The initial commit in this PR corresponds to b728ab4535e214335242fc1f1e1127621dec7fd1 in the private PR.
> Overhaul security section

- content/project/roadmap/index.html.haml
Fixes tooltip visualization in the roadmap items
> [JEP-14] - Add description tooltips to roadmap items

- .github/autolabeler.yml
> Confgure Autolabeler for the roadmap changes

- content/css/roadmap.css
Danger - no knowledge of CSS, just used Chrome Inspect
> Center roadamp text in last cell

- content/_data/authors/linuxsuren.adoc
Here is the link https://twitter.com/LinuxSuRen
> Change my twitter ID

- content/sigs/pipeline-authoring/index.adoc
> Removing EMEA ref, minor changes & corrections

- content/sigs/pipeline-authoring/index.adoc
> Adding Anchore as an org

- content/sigs/pipeline-authoring/index.adoc
Reordering the orgs alphabetically
> Reordering the orgs alphabetically

- content/_data/roadmap/roadmap.yml
Some extra data, will be used for visualization later
> Roadmap: Add category links

- content/_data/events/2020-04-17-jom-kubernetes-getting-started.adoc
https://www.meetup.com/Jenkins-online-meetup/events/269888701/
> Events: Add entry for the Jenkins online meetup on April 17

- content/projects/gsoc/2020/project-ideas/remoting-monitoring.adoc
> Adding myself to the mentor list

- content/_data/authors/nikhildarocha.adoc
- content/projects/gsoc/2020/project-ideas/jenkins-x-apps-consolidation.adoc
- content/projects/gsoc/2020/project-ideas/jenkins-x-boot-apps.adoc
- content/projects/gsoc/2020/project-ideas/jenkins-x-openwrt-ppa.adoc
Would like to be a mentor for gsoc 2020.
> @nikhildarocha mentor for gsoc

- content/_data/roadmap/roadmap.yml
Better wording of what the changes target. We do not really limit this work by mere CSS changes
> Roadmap: reword the UX SIG entries

- content/_data/roadmap/roadmap.yml
As Discusses in Advocacy&Outreach Gitter channel
> Add Agent terminology cleanup to the Jenkins roadmap

- content/_data/roadmap/roadmap.yml
See https://groups.google.com/forum/#!topic/jenkinsci-dev/oK8pBCzPPpo
> Add new Windows Support Policy to the Platform SIG roadmap

- content/doc/book/securing-jenkins.html.haml
Thanks to @olblak for catching it
> Fix the securing Jenkins redirect

- content/participate/help.adoc
This pull request is to address the following issue:
https://issues.jenkins-ci.org/browse/WEBSITE-681
> Improving https://jenkins.io/participate/help/

- content/projects/gsoc/2020/project-ideas/jenkins-x-apps-consolidation.adoc
@MarckK / @oleg-nenashev : It seems my name was missing for this project and hence it didn't appear in the excel sheet too.
> Adding sahilkalra to mentor list

- content/_data/changelogs/weekly.yml
subj, downloads do not work at the moment, so I suggest to highlight a workaround.
CC @MarkEWaite @markyjackson-taulia @olblak @timja
> [INFRA-910] - Reference get.jenkins.o as an alternative source of updates

- content/_data/roadmap/roadmap.yml
Creates a number of entries for Jenkins developer tools, based on the  current stories and JEPs.
> JEP-14 - Initialize roadmap for Jenkins developer tools

- content/doc/developer/plugin-development/dependency-management.adoc
> Update bom instructions

- content/_data/roadmap/roadmap.yml
- content/sigs/docs/index.adoc
* Add descriptions to existing docs items
* Add Jenkins on Kubernetes
* Add Administrator Guide
* Add User Guide improvements
Also add Jenkins on Kubernetes to the Docs SIG page with links to interesting resources for Jenkins on Kubernetes.
> Add Docs roadmap items

- content/_data/roadmap/roadmap.yml
Adds some extra items which we have in progress or in JEPs.
> Roadmap: Add more items for developer tools

- content/_config/site.yml
https://github.com/jenkins-infra/jenkins.io/issues/3108
> Switch base_url to www.jenkins.io

- content/events/online-meetup/index.adoc
- content/projects/jam/index.adoc
Since we have an official Zoom account now, we can finally document our meetup platform and to offer it to speakers and meetup organizers.
> Document the online meetup platform and the CFP process

- content/download/thank-you-downloading-windows-installer.html.haml
CC @olblak @timja . Not sure it is still needed
> Downloads: Fix the Windows MSI redirect to use the new weekly

- content/sigs/docs/index.adoc
Make "How-To Guides" text a clickable link
> Make How-To Guides a clickable link

- content/project/index.adoc
- content/project/teams/hosting.adoc
Initial pull request for the the Hosting team. See https://groups.google.com/forum/#!topic/jenkinsci-dev/ljwhniI-T3U for more info
* Overview
* Some documentation, including contributing, onboarding process, tools, etc.
Preview:
> Create a landing page for the Hosting Team

- content/sigs/docs/gsod/index.adoc
Added another project. Rendering could be better, but this is what we get with default styles. Maybe we should drop the table layout at all
> GSoC 2020" Add project idea for solution pages

- content/index.html.haml
- content/projects/gsoc/index.adoc
> GSoC 2020: Update jumbotron, update org admins list

- content/blog/2020/05/2020-05-06-docker-agent-image-renaming.adoc
> Fix the ssh-agent image name in the blogpost

- content/_data/authors/loghijiaha.adoc
- content/projects/gsoc/2020/projects/machine-learning.adoc
Update for jenkins.io on the project page and profile
> Update for jenkins.io

- content/_data/roadmap/roadmap.yml
> Jenkins Roadmap: Add 2020 elections and the Core Infrastructure Initiative compliance items

- content/projects/gsoc/2020/projects/custom-jenkins-distribution-build-service.adoc
Updating the new communication channel  for the GSoC Custom Jenkins Distribution Service Project.
> Custom Jenkins Distribution Service gitter link 

- content/blog/2020/05/2020-05-06-docker-agent-image-renaming.adoc
Thanks to @vaceletm for catching it
> Fix DockerHub links in the blog

- content/_data/events/2020-05-11-jom-kubernetes-operator copy.adoc
- content/_data/events/2020-05-15-jom-anchore.adoc
> Add Jenkins Online Meetups to the event calendar

- content/index.html.haml
Promote the "Jenkins is the Way" collection of Jenkins case studies.  We want to highlight the many different ways that Jenkins is used worldwide.
> Add Jenkins is the Way case studies to the Jumbotron

- content/doc/book/managing/system-properties.adoc
Updated url of Jenkins in footer and added option new UX feature https://issues.jenkins-ci.org/browse/JENKINS-60920
> Update value of url in footer and added option new UX feature

- content/projects/gsoc/2020/projects/git-plugin-performance.adoc
- content/sigs/platform/index.adoc
Would also welcome optional review from the Git Plugin Performance mentors:
* @fcojfernandez 
* @justinharringa 
* @baymac
> Add Git Plugin Performance project office hours

- content/doc/developer/building/intellij.adoc
Concerning the fork and clone instruction, to provide clarity and align this document closer to the main contributing document: https://github.com/jenkinsci/jenkins/blob/master/CONTRIBUTING.md
> Clarify fork and clone instruction

- content/merchandise.adoc
Adding CDF Store to [https://www.jenkins.io/merchandise/](https://www.jenkins.io/merchandise/)
> Fixing issue 3236

- content/projects/gsoc/2020/projects/custom-jenkins-distribution-build-service.adoc
This PR:
a) Adds Project meeting timings
b) Adds Project design docs.
c) Adds Project Daily Notes
> Custom Distribution Service: Updated meeting timings and project notes

- content/doc/developer/handling-requests/stapler-accessible-type.adoc
In meeting right now, sorry for the origin branch. Please delete once merged
> Fix reference to library name

- content/blog/2020/05/2020-05-12-uiux-hackfest-announcement.adoc
- content/events/online-hackfest/2020-uiux/index.adoc
> UI/UX hackfest: add more links

- content/_data/roadmap/roadmap.yml
- content/events/online-hackfest/2020-uiux/index.adoc
- content/sigs/ux/index.adoc
Just an update while I was around (for UI/UX hackfest). CC @jphartley @fqueiruga 
P.S: @fqueiruga it would be great if you could create a user profile on jenkins.io so that I add you to the SIG
> UX SIG: add current project from the roadmap and more SIG members

- .github/ISSUE_TEMPLATE/1-documentation.yml
- .github/ISSUE_TEMPLATE/2-wiki-migration.yml
- .github/ISSUE_TEMPLATE/3-enhancement.yml
- .github/ISSUE_TEMPLATE/4-bug.yml
- .github/ISSUE_TEMPLATE/config.yml
Adding issue templates:
* New Documentation
* Wiki Migration
* Website enhancement
* Bug
> [WEBSITE-748] - Add issue templates to jenkins.io

- content/blog/2020/05/2020-05-12-uiux-hackfest-announcement.adoc
- content/events/online-hackfest/2020-uiux/index.adoc
As discussed yesterday, we would like to add https://github.com/jenkinsci/jenkins/pull/3895 testing and/or fix follow-ups to the list of the hackfest projects. CC @timja @jsoref @fqueiruga
> UI/UX hackfest: Add UX testing and Table-to-divs migration to the projects list

- content/events/online-hackfest/2020-uiux/index.adoc
This PR adds a number of confirmed and semi-confirmed online events
CC @timja @uhafner @MarkEWaite @alyssat
> UI/UX Hackfest - Initialize the online events section

- content/projects/gsoc/2020/projects/github-checks.adoc
> Add meeting schedule and notes to the github checks project page

- content/_data/events/2020-05-18-job-plugin-pom-4.adoc
- content/_data/events/2020-05-19-job-dsl.adoc
> Add May 18 and 19 events

- content/css/jenkins.css
https://issues.jenkins-ci.org/browse/WEBSITE-656
> Add CSS for table borders

- content/blog/2020/04/2020-04-16-github-app-authentication.adoc
Just a minor update to the blogpost which reflects the GA status.
@timja would it make sense to also update the roadmap? Or are there any other changes planned as a part of this initiative as a part of the Checks APi project? CC @XiongKezhi @uhafner @aagarwal1012
> Update the GitHub App Authentication post: Now in GA

- content/events/online-hackfest/2020-uiux/faq.adoc
- content/events/online-hackfest/2020-uiux/index.adoc
This PR updates the hackfest landing page a bit. we still need to update projects, but I will do it later as a follow-up
> UI/UX Hackfest: Event updates, Getting started guidelines and FAQ

- content/sigs/cloud-native/pluggable-storage.adoc
> Update Fingerprint Status on Cloud Native SIG Page

- content/projects/gsoc/2020/projects/external-fingerprint-storage.adoc
- MongoDB -> Redis
- Add Design Doc and Daily Progress Links
- Minor changes for phase 1 deliverables
CC @oleg-nenashev
> Update External Fingerprint Storage Project Page

- content/doc/developer/views/_chapter.yml
- content/doc/developer/views/table-to-div-migration.adoc
On hold till https://github.com/jenkinsci/jenkins/pull/3895 is merged but please review so we can co-ordinate the merge
cc @jsoref @fqueiruga
> Add how to guide for table => div migration

- CONTRIBUTING.adoc
- content/doc/book/architecting-for-scale.adoc
Unfortunately I was not able to generate the site and double check the changes.
If you prefer to have two pull request for the two unrelated changes, let me know.
Thank you for your effort, Matthias
> Small fixes

- content/index.html.haml
> Add UI/UX hackfest to the Jumbotron

- content/events/online-hackfest/2020-uiux/faq.adoc
- content/events/online-hackfest/2020-uiux/index.adoc
Extends FAQ, adds some notes from the welcome email: https://docs.google.com/document/d/12P3skTnyzg2tpr169pnQ-kctaQuzSKvBF8LhM3jwpOM/edit?usp=sharing
> UI/UX Hackfest - update the website

- content/events/online-hackfest/2020-uiux/index.adoc
More links, etc. Have not touched UI yet
> UI/UX Hackfest - Improve Docs and Outreach project ideas

- content/events/online-hackfest/2020-uiux/index.adoc
Finalizes the ideas cleanup... at least for now
> UI/UX Hackfest - Move UI ideas from the hackfest proposals

- content/events/online-hackfest/2020-uiux/index.adoc
> Link the opening session and YouTube channel + TabsToDivs link updates

- content/projects/gsoc/2020/project-ideas/pipeline-as-yaml-experiment.adoc
fixes link to pipeline as yaml plugin
> fixes link to pipeline as yaml plugin

- content/doc/book/using/_chapter.yml
- content/doc/book/using/fingerprints.adoc
> Migrate fingerprints from wiki

- content/doc/developer/plugin-governance/adopt-a-plugin.adoc
Origin branch as I don't have a checkout at the moment, please delete on merge.
> Fix unnecessarily brittle link directly to resource file

- content/doc/book/managing/system-properties.adoc
A couple of cosmetic changes when the table was moved to a list.
> cosmetic: no more a table but a list

- content/doc/developer/publishing/releasing.adoc
Origin branch as I don't have a checkout at the moment, please delete on merge.
> Add the 2nd common reason for 403: The release already exists

- content/blog/2020/05/2020-05-12-uiux-hackfest-announcement.adoc
> UI/UX Hackfest - Fix the link to Advocacy&Outreach SIG

- content/download/lts/index.adoc
This may _not_ be the best wording, but I found myself having to re-read that sentence 2 or 3 times to get the intended meaning. Open to suggestions, forgive my nitpicking.
> Changing wording for switching LTS to Weekly

- content/doc/book/installing/index.adoc
Issue #2889 - Item: Add Java version note similar to the note we have for Debian and Ubuntu.
> Issue #2889 - Item: Add Java version

- content/doc/book/managing/nodes.adoc
Fixes #3322 
I've migrated the content from the old wiki. I have not been able to simplify it though, any help provided will be extremely beneficial.
> Migrated 'Monitor and restart offline slaves' from wiki

- content/doc/developer/plugin-governance/adopt-a-plugin.adoc
Followup to #3358 which wasn't complete.
Origin branch since my local copy is a mess due to #3396, please delete after merge.
> Fix another unnecessarily brittle link into another repo

- content/_data/events/2020-06-04-jom-keptn.adoc
> Events: Add June 04 online meetup to the events list

- content/doc/book/glossary/index.adoc
- content/doc/pipeline/tour/post.adoc
- content/doc/pipeline/tour/tests-and-artifacts.adoc
Added build status definitions to the Glossary
Added reference to glossary in pipeline tour
https://github.com/jenkins-infra/jenkins.io/issues/3305
> Added build status definitions to the Glossary

- content/blog/2020/05/2020-05-12-uiux-hackfest-announcement.adoc
- content/events/online-hackfest/2020-uiux/index.adoc
- content/index.html.haml
This is an initial pull request which archives the hackfest pages
> UI/UX Hackfest: remove Jumbotron, add results and update the event status

- content/_layouts/systemproperties.html.haml
- content/doc/book/managing/system-properties.adoc
Also some minor cleanup, e.g. this was migrated from the wiki without s-word cleanup 😞 👎
> Add tags to system properties

- content/sigs/advocacy-and-outreach/outreach-programs/index.adoc
> Fixing GSoD in outreach program

- content/security/advisory/2020-06-03.adoc
https://github.com/jenkins-infra/update-center2/pull/384 will otherwise remove the display name.
> Provide display name of play-autotest-plugin

- content/projects/gsoc/2020/projects/machine-learning.adoc
Small fix. Changed the date of publishing.
> Fix for the link to blog page to project page

- content/doc/administration/requirements/windows.adoc
- content/doc/book/installing/index.adoc
This change defines the initial Windows support policy in Jenkins. See this thread in the developer mailing list for more details: https://groups.google.com/forum/#!msg/jenkinsci-dev/oK8pBCzPPpo/1Ue1DI4TAQAJ . Versions in support tiers are subject to change during the review.
CC @MarkEWaite @slide @NextTurn @buddhikac96
> Document the Windows Support policy in Jenkins

- content/doc/book/installing/index.adoc
link:doc/administration/requirements/java/ changed to link:/doc/administration/requirements/java/
> link:/doc/administration/requirements/java/

- content/_layouts/developer.html.haml
- content/_layouts/developerbook.html.haml
- content/_layouts/developerextension.html.haml
- content/_layouts/documentation.html.haml
- content/_layouts/post.html.haml
- content/_layouts/project.html.haml
- content/_layouts/security.html.haml
- content/_layouts/simplepage.html.haml
- content/_partials/anchors.html.haml
Follow up for https://github.com/jenkins-infra/jenkins.io/pull/3393#issuecomment-636510512
Should fix the anchor links for e.g. the mailing lists.
CC @daniel-beck @halkeye
> Add anchors on DOMContentLoaded

- content/_data/roadmap/roadmap.yml
This change reflects the recent changes in the project
> Jenkins roadmap status update

- content/project/team-leads.adoc
> fixing link under Release section

- content/doc/administration/requirements/windows.adoc
Should reduce the vertical size of the table on wide screens
> Windows support policy - adjust column widths to improve look and feel of the table

- content/sigs/cloud-native/pluggable-storage.adoc
> Update status of fingerprints on Pluggable Storage Page

- content/projects/gsoc/2020/projects/external-fingerprint-storage.adoc
> Add JEP link to External Fingerprint Storage Project Page

- content/doc/book/managing/nodes.adoc
This page amends https://github.com/jenkins-infra/jenkins.io/pull/3324 was merged without full terminology cleanup,
CC @MarkEWaite @markyjackson-taulia @krharsh17
> Cleanup the agent terminology in nodes.adoc

- content/_data/roadmap/roadmap.yml
> [JEP-14] - Roadmap updates for user experience

- content/js/roadmap.js
- content/project/roadmap/index.html.haml
> [JEP-14] - Hide Roadmap categories when there is no initiatives after filtering

- content/_data/roadmap/roadmap.yml
> Add JEP number and link to external fingerprint storage in Roadmap

- content/blog/2020/06/2020-06-18-terminology-update.adoc
> Terminology Update Blog Post

- content/awards.html.haml
- content/doc/book/managing/script-console.adoc
- content/doc/book/system-administration/security/configuring-content-security-policy.adoc
- content/doc/book/using/aborting-a-build.adoc
Fix a few more instances of the outdated terminology
> Update agent terminology

- content/_data/upgrades/2-60-1.adoc
- content/_partials/changelog-stable.html
- content/doc/book/architecting-for-manageability.adoc
- content/doc/book/pipeline/syntax.adoc
- content/doc/developer/plugin-development/pipeline-integration.adoc
- content/doc/developer/plugin-development/writing-an-scm-plugin.adoc
Fixes LTS changelog and a couple of places in the documentation.
> More agent terminology fixes

- content/blog/2020/06/2020-06-26-ui-ux-hackfest-ui-track.adoc
i deleted the wrong image before squash-merge
> Fix the UI/UX Hackfest report: wrong Dark theme image

- content/blog/2020/06/2020-06-30-machine-learning-plugin-coding-phase1.adoc
- content/projects/gsoc/2020/projects/machine-learning.adoc
This is a blog post regarding coding phase 1 of GSoC 2020.
@markyjackson-taulia 
@oleg-nenashev
> Blog phase1

- content/blog/2020/06/2020-06-30-machine-learning-plugin-coding-phase1.adoc
- content/projects/gsoc/2020/projects/machine-learning.adoc
Fixed image issue on the blogpost
@markyjackson-taulia @oleg-nenashev
> Fix for images in blog and page

- content/_data/roadmap/roadmap.yml
FYI @timja @stellargo @Loghijiaha . Updating statuses of the projects which are ready for evaluation
> Jenkins Roadmap - Update statuses of the projects which are now in preview

- content/_data/roadmap/roadmap.yml
Follow-up to my action item in https://groups.google.com/forum/#!topic/jenkinsci-dev/CLR55wMZwZ8
> Add terminology updates to the roadmap

- content/security/advisory/2020-07-02.adoc
https://github.com/jenkins-infra/update-center2/pull/395
> Support jenkins-infra/update-center2#395

- content/projects/gsoc/2020/projects/winsw-yaml-configs.adoc
Add GSoC 2020 Phase 01 updates blog post into project page.
> Update GSoC 2020 - WinSW : YAML Support Project Page

- content/_data/roadmap/roadmap.yml
Updates statuses/descriptions of existing stories, adds Code of Conduct update and CDF Graduation
> Jenkins Roadmap: Update the project governance roadmap

- content/sigs/advocacy-and-outreach/index.adoc
- content/sigs/cloud-native/index.adoc
- content/sigs/pipeline-authoring/index.adoc
> Removing myself from sig listings

- content/doc/book/installing/_setup-wizard.adoc
Add a new hint to get the admin password without get inside of the container.
> item note added

- content/blog/2020/07/2020-07-15-xss-severity.adoc
Wording is timing sensitive, needs slight rewording if merged after today.
> <img width="1568" alt="Screenshot" src="https://user-images.githubusercontent.com/1831569/87574727-16b96480-c6cf-11ea-96da-41c7ab59d781.png">
> Add 2020-07-15 blog post on XSS severity

- content/blog/2020/07/2020-07-15-xss-severity.adoc
> Add the announcement tag to the Jul 15 security blogpost

- content/download/index.html.haml
Just a minor improvement to have shorter text
> Download page: optimize the "Download Jenkins" text

- content/_data/roadmap/roadmap.yml
- content/sigs/ux/index.adoc
This initiative aims to improve plugin management UI for Jenkins administrators so that they can easily discover plugins and make decisions about plugin upgrades. Scope: Plugin Manager in the Jenkins core, plugins.jenkins.io, Jenkins Update Center and other services.
CC @daniel-beck @timja @halkeye who are the main contributors to this initiative. Also, CC @jphartley as a SIG leader
> UX Roadmap - Add the Plugin management UI improvements initiative details

- content/blog/2020/04/2020-04-16-github-app-authentication.adoc
ref: https://twitter.com/rjacksonm1/status/1285521704291368960
> Fix typo in github app blog

- content/_data/changelogs/weekly.yml
- content/changelog/index.html.haml
> Add changelog for 2.246, 2.247, 2.248

- content/blog/2020/07/2020-07-23-windows-support-updates.adoc
Follow up to the comments from @NextTurn in https://github.com/jenkins-infra/jenkins.io/pull/3555 after the merge
> Windows Support Policy blog: Fix typo and wording

- content/blog/2020/07/2020-07-27-machine-learning-plugin-coding-phase2.adoc
- content/projects/gsoc/2020/projects/machine-learning.adoc
A blog post for coding phase 2 of machine learning plugin
@oleg-nenashev
> Phase 2 blog post

- content/doc/developer/publishing/documentation.adoc
- content/doc/developer/publishing/plugin-site.adoc
> Fix broke link to plugin label allowlist

- content/doc/developer/security/secrets.adoc
Origin branch, please delete once done.
> Fix code reference to match description

- content/download/index.html.haml
- content/download/verify.adoc
Slightly related to https://github.com/jenkinsci/packaging/pull/192 and https://github.com/jenkins-infra/jenkins.io/pull/3533
> Add page on verifying downloads

- content/download/verify.adoc
Per request from @daniel-beck in #3582
> Add more detail on verifying downloads

- content/_data/roadmap/roadmap.yml
Updates the Cloud Native Jenkins roadmap items based on the recent discussions in the SIG
> Update Cloud Native platforms roadmap items

- content/_data/roadmap/roadmap.yml
Uodates the initiative statuses and fixes a few links
> Roadmap - Update the initiative statuses and links

- content/doc/book/installing/_jenkins-command-parameters.adoc
> Enabling new 'inbound agent' terminology

- content/projects/index.adoc
- content/projects/jenkins-x.adoc
Closes https://github.com/jenkins-infra/jenkins.io/issues/3597 . CC @MarckK
> Add redirect for the Jenkins X sub-project and remove the sub-project

- content/projects/infrastructure/index.adoc
List many more infrastructure providers, services, and components.
> Link to more infrastructure documentation

- content/blog/2020/08/2020-08-09-custom-distribution-service-phase-2.adoc
FYI, bug in the original pull request
> Fix the OpenGraph link in the Custom Jenkins Distribution build service blogpost

- content/blog/2020/08/2020-08-12-windows-installers-upgrade.adoc
As discussed in the Docs SIG chat, I believe a lot of content and screenshots came from https://www.jenkins.io/blog/2019/02/01/windows-installers/ . I think it would be great to add @slide to this blog post.
> Add @slide to the authors list of the new Windows installer blog

- content/doc/book/installing/index.adoc
Providing more details and valid links for installing Jenkins on Windows
> Adding privilege reqs to Jenkins installer for win

- content/projects/gsoc/2020/projects/custom-jenkins-distribution-build-service.adoc
This PR updates the Custom Jenkins Distribution Project GSoC 2020 as part of my report to Google and final phase evaluations.
> WIP: Update Project page for GSoC Custom Jenkins Distribution Service

- content/sigs/cloud-native/pluggable-storage.adoc
See https://github.com/jenkinsci/junit-plugin/issues/142. @timja
> Updated link to status of test result storage

- content/projects/gsoc/2020/projects/winsw-yaml-configs.adoc
Update current state of the project
> Update windows service wrapper - YAML configuration support project page

- content/download/lts/index.adoc
Resolves #3658
I'm not convinced having the URL even makes any sense here, but 🤷 This seems like the simplest possible fix, more or less, plus a new reference to more details.
@andreasbenzing @MarkEWaite 
Origin branch, please delete after merge.
> Fix linked update center URL

- content/projects/gsoc/2020/projects/github-checks.adoc
It seems time is still enough, so I'll still write another phase-3 blog post, maybe later also another one for the whole project after we release 1.0.0?
cc @timja @uhafner @oleg-nenashev
> Update GitHub checks api project page

- content/projects/gsoc/2020/projects/custom-jenkins-distribution-build-service.adoc
* Added Slides Links
* Added Completed Features
* Added Roadmap Link
> Update Custom Distribution Service Project page

- content/projects/gsoc/2020/projects/github-checks.adoc
> Fix broke internal blog links and add phase 3 demo link

- content/projects/gsoc/2020/projects/machine-learning.adoc
Updated project page with a final demo video and presentaion slides @oleg-nenashev
> Added final demo video

- content/blog/2020/08/2020-08-25-external-fingerprint-storage-phase-3.adoc
> Add demo to phase-3 blog

- content/blog/2020/08/2020-08-27-winsw-yaml-support.adoc
- Link the phase 3 demo in phase 3 blog post.
> WinSW : Update phase 3 blog

- content/projects/gsoc/2020/projects/external-fingerprint-storage.adoc
> Add demo to external fingerprint storage project

- content/projects/gsoc/2020/projects/winsw-yaml-configs.adoc
- Update description of open pull requests
> Update WinSW project page

- content/projects/gsoc/2020/projects/winsw-yaml-configs.adoc
- Fix typos
- Add remaining task
> WinSW : Update project page

- content/security/advisory/2020-09-01.adoc
Prepare for https://github.com/jenkins-infra/update-center2/pull/438
> Prepare for suspension of JSGames plugin

- content/_data/changelogs/lts.yml
- content/_data/changelogs/weekly.yml
- content/_data/upgrades/2-249-1.adoc
> Changelog and upgrade guide for 2.249.1

- content/doc/book/glossary/index.adoc
Based on the board meeting decision to change the master terminology to controller.
> Update glossary with controller terminology

- content/sigs/cloud-native/pluggable-storage.adoc
Update status of the pluggable storage stories. FYI @timja @jglick @stellargo . I plan to tweak the roadmap in a separate pull request.
Table preview:
> Cloud Native SIG - Update Pluggable Storage story statuses

- content/security/advisory/2020-09-16.adoc
We messed this up a bit 😞 
> ![Screenshot](https://user-images.githubusercontent.com/1831569/93366611-b324f200-f84b-11ea-9c52-746ca512cdd1.png)
> [SECURITY-1961] Fix description

- content/_data/authors/markyjackson-taulia.adoc
> Updating bio

- content/_data/roadmap/archive.yml
- content/_data/roadmap/roadmap.yml
Updates statuses of the existing roadmap items as we discussed at the Jenkins Governance meeting yesterday. More updates to follow. FTR https://groups.google.com/g/jenkinsci-dev/c/cc18SAHXr-4
> Jenkins roadmap: Update statuses of the Roadmap items

- content/blog/2016/2016-05-10-jenkins-20-vjam.adoc
- content/blog/2016/2016-12-20-jenkins-puppet-enterprise-plugin.adoc
- content/blog/2018/07/2018-07-30-introducing-cloud-native-sig.adoc
- content/blog/2020/05/2020-05-11-docker-windows-agents.adoc
Corrections to comments from pr #3678
> Terminology corrections

- content/project/board-election-process.adoc
This update finalizes the elections process description:
> Update the elections process page

- content/download/thank-you-downloading-windows-installer-stable.html.haml
- content/download/thank-you-downloading-windows-installer.html.haml
> Change Windows to get.jenkins.io

- content/_data/events/2020-10-07-cdcon.adoc
Looks like this expanded:
Looks like this on initial opening of the full page.
> Add cdCon to the Jenkins events list

- content/blog/2020/09/2020-09-24-board-elections.adoc
- content/project/board-election-process.adoc
Follow-up on the announcement by @slide in https://groups.google.com/g/jenkinsci-dev/c/i42q3hhcx3I
> 2020 Elections: Increment the number of elected governance board members

- content/events/hacktoberfest.adoc
@oleg-nenashev I hope it's not to late to join ;-)
> Propose jenkinsci/helm-charts for hacktoberfest

- content/events/hacktoberfest.adoc
Adding the Prometheus plugin to Jenkins Hacktoberfest
> Prometheus Plugin for HacktoberFest

- Makefile
While preparing for adding my employer as an adopter, I found some grammar stuff, that I'd like to fix.
> Fix minor grammar stuff

- content/_data/roadmap/roadmap.yml
- content/projects/index.adoc
- content/projects/jcasc/index.adoc
- content/projects/remoting/index.adoc
- content/sigs/cloud-native/pluggable-storage.adoc
- content/sigs/platform/index.adoc
Use controller rather than master
> Fix roadmap terminology references

- content/redirect/groovy-string-interpolation.adoc
adding groovy string interpolation redirect for https://github.com/jenkinsci/workflow-cps-plugin/pull/370
> add redirect URL for groovy string interpolation

- content/pipeline/getting-started-pipelines.adoc
Fixes https://github.com/jenkins-infra/jenkins.io/issues/3837
> Fix terminology in pipeline getting started

- content/doc/administration/requirements/java.adoc
- content/doc/administration/requirements/upgrade-java-guidelines.adoc
- content/doc/administration/requirements/windows.adoc
closes #3840 
I double checked to ensure there were no changed references to other **master* references that were not in scope to change as part of this issue.
> Changed instances of "master" to "controller" in "Administration" chapter.

- content/doc/book/pipeline/development.adoc
- content/doc/book/pipeline/index.adoc
- content/doc/book/pipeline/jenkinsfile.adoc
- content/doc/book/pipeline/pipeline-best-practices.adoc
- content/doc/book/pipeline/scaling-pipeline.adoc
- content/doc/book/pipeline/shared-libraries.adoc
- content/doc/book/pipeline/syntax.adoc
@MarkEWaite - I went through the documentation, the issue request in detail, and have done required changes.  Let me know if you find any issues with my work. Am quite new to contributing to the open source world. Hope there are not many issues.
> Fix terminology in "Pipeline" chapter #3836 - Changed references of master to controller

- content/css/jenkins.css
> Improve contrast for accessibility

- content/index.html.haml
> Fix the elections link on the Jumbotron

- content/doc/book/system-administration/security.adoc
- content/doc/book/system-administration/security/configuring-content-security-policy.adoc
> Fixing terminology in System Administration

- content/doc/developer/security/_chapter.yml
- content/doc/developer/security/misc.adoc
- content/doc/developer/security/rendering-user-content.adoc
> More security advice for plugin developers

- content/doc/developer/plugin-development/optional-dependencies.adoc
It is correct in other places in the same document... :confounded:
> Fix exception name in "optional-dependencies"

- content/index.html.haml
> Remove the cdCon Jumbotron (conference is over)

- content/events/hacktoberfest.adoc
Add Tekton client plugin to hacktoberfest.
> Update hacktoberfest doc with tekton-client-plugin

- content/doc/book/system-administration/monitoring.adoc
Addresses https://github.com/jenkins-infra/jenkins.io/issues/3779
> [jenkins.io/3779] migrate Ping Thread

- content/doc/developer/tutorial/prepare.adoc
@oleg-nenashev FYI -  In this pull request I've applied small changes to improve readability
- Replaced some words with their synonyms to make the text easier for non-native EN speakers and to facilitate translation.
- Removed unnecessary, irrelevant information to declutter text.
- Replacements with more descriptive words or labels (on links).
- Removed duplication .
- Fixed typos.
- Replaced latin abbreviations (for accessibility and  facilitate translation).
If I got something wrong in my review, feel free to edit my text.
Can you please label/classify this for #hacktoberfest?
> Preparing for Plugin Development - changes to improve readability

- content/_data/changelogs/weekly.yml
modify some punctuation discription error
> modify some punctuation discription error in weekly changelog 2.261

- content/press.adoc
I'm still fielding ~1 every other week for folks, so good to go to a current address
> Update my email for press inquiries

- content/artwork/index.html.haml
> Artwork: Add responsive breakpoints for mobile devices

- content/blog/2020/09/2020-09-24-board-elections.adoc
- content/project/board-election-process.adoc
Follow up to the announcement n the mailing list about the date change
> 2020 - Update the candidates list publishing date

- content/doc/book/system-administration/diagnosing-errors.adoc
This is a follow-up to https://github.com/jenkins-infra/jenkins-infra/pull/1588 from @kaltepeter
> Diagnosing Errors: Add a section for Out Of memory Errors

- content/blog/2019/08/2019-08-26-role-strategy-performance.adoc
- content/blog/2019/12/2019-12-16-board-election-results.adoc
- content/blog/2020/08/2020-08-25-external-fingerprint-storage-phase-3.adoc
- content/participate/document.adoc
- content/projects/gsoc/2020/projects/external-fingerprint-storage.adoc
Several links included no link destination.  When clicked, they seem to jump to the top of the page.  Other links were not showing as links.
> Fix some broken and empty links

- content/sigs/chinese-localization/index.adoc
Reverts jenkins-infra/jenkins.io#3906
> Revert "Update participants of Chinese Localization SIG, remove alauda as a org"

- content/projects/gsoc/2021/index.adoc
- content/projects/gsoc/2021/project-ideas.html.haml
- content/projects/gsoc/2021/project-ideas/automatic-spec-generator-for-jenkins-rest-api.adoc
- content/projects/gsoc/2021/project-ideas/plugin-installation-manager-tool.adoc
- content/projects/gsoc/2021/project-ideas/remoting-monitoring.adoc
- content/projects/gsoc/index.adoc
Initializes the GSoC 2021 content.
FYI @timja @kwhetstone @LinuxSuRen @markyjackson-taulia @mikecirioli I have added a few project ideas from GSoC 2020 that I would be interested to mentor. If you are interested in being GSoC 2021 mentors, please feel free to uncomment your names. New project ideas are always welcome!
> [GSoC 2021] - Initialize the GSoC 2021 project ideas, update landing

- content/_data/authors/zhaoying818.adoc
New one  as the participants of Chinese Localization SIG.
for 
https://github.com/jenkins-infra/jenkins.io/pull/3906
https://github.com/jenkins-infra/jenkins.io/pull/3909
> add zhaoying818.adoc

- content/blog/2020/09/2020-09-24-board-elections.adoc
- content/blog/2020/10/2020-10-28-election-candidates.adoc
- content/index.html.haml
Jumbotron: 
Blogpost with a button:
> [2020 Elections] - Update jumbotron, add register buttons

- content/_data/authors/markyjackson-taulia.adoc
- content/sigs/advocacy-and-outreach/index.adoc
- content/sigs/cloud-native/index.adoc
Adding myself to Advocacy and Cloud-Native SIG
> Adding myself to SIG listing 

- content/blog/2020/11/2020-11-04-codeql.adoc
Would prefer active copy-editing over a quick merge 😃 
@Wadeck PTAL
> Add blog post on first code scanning results

- content/_data/roadmap/roadmap.yml
Well, 2.264+ weekly releases are rather a preview as well then, until the stuff is stabilized
CC @timja @fqueiruga
> Roadmap: Tables to Divs migration is now in preview

- content/doc/book/installing/_setup-wizard.adoc
> Fix Mng-Jenkins and Mng-Plugins links

- content/doc/book/pipeline/jenkinsfile.adoc
expanding on string interpolation issues. Related to https://github.com/jenkinsci/workflow-cps-plugin/pull/370
cc @dwnusbaum @mehtasona
> add warning to string interpolation section

- content/_data/authors/sparshev.adoc
- content/blog/2019/01/2019-01-08-mpl-modular-pipeline-library.adoc
Related to: https://github.com/griddynamics/mpl/issues/82 - the original videos was removed, so reuploaded them.
> Blog Post: Fixed the video links for the MPL - Modular Pipeline Library

- content/template.html.haml
Makes it easier to insert content into the template: won't make a difference for plugin site, will make https://github.com/jenkins-infra/update-center2/pull/469 slightly nicer.
> Add a placeholder to the template

- content/doc/book/managing/cli.adoc
wiki-migration, new section about ssh and cli advantages. issue #3323.
After merged i will update the redirect in vhost file.
> wiki-migration, new section to cli page

- content/blog/2020/10/2020-10-28-election-candidates.adoc
FYI @v1v @timja @steven-terrana
> Fix text for GitHub links, incorrectly labeled as Twitter

- content/doc/developer/views/table-to-div-migration.adoc
https://github.com/jenkinsci/jenkins/pull/5075#issuecomment-735230242
> Add warning about divBasedFormLayout not always being set

- content/doc/developer/views/table-to-div-migration.adoc
> Add a troubleshooting section for tables-to-divs

- content/_data/changelogs/lts.yml
- content/_data/changelogs/weekly.yml
- content/_data/upgrades/2-263-1.adoc
> Changelog and upgrade guide for 2.263.1 LTS

- content/doc/book/managing/security.adoc
- content/doc/book/system-administration/security.adoc
- content/doc/book/system-administration/security/configuring-content-security-policy.adoc
- content/redirect/security-144.adoc
- content/security/advisory/2018-05-09.adoc
Do not need to rely on the wiki for this page
> Refer to agent to controller content on www.jenkins.io

- content/blog/2020/10/2020-10-28-election-candidates.adoc
This PR is to remove my previous employer and add my new employer
> Removing previous workplace

- content/_data/authors/halkeye.adoc
- content/_data/roadmap/roadmap.yml
- content/blog/2020/09/2020-09-24-board-elections.adoc
- content/blog/2020/10/2020-10-28-election-candidates.adoc
- content/blog/2020/12/2020-12-03-election-results.adoc
- content/index.html.haml
- content/project/board-election-process.adoc
- content/project/board.html.haml
Staging the blogpost for the election results announcement blog.
Would appreciate reviews from all current and former officers and board members.
I am still finishing minor bits (mostly acknowledgements), but the text is ready for review and feedback.
The publishing date may change depending on the reviews, official announcement will go to the mailing list, it is also ready for review: https://docs.google.com/document/d/1xdsfW4GTSfIl6hyLKGql2nGfau3dz0cVyuMa27Xb44k/edit#heading=h.dbo5satp6f7z
> Jenkins 2020 Elections Results announcement

- content/blog/2020/12/2020-12-03-election-results.adoc
I initially read it wrongly thinking it was just about the release officer, but it was about the new officer joiners :)
> Update name for the Release Officer

- content/doc/book/installing/_kubernetes.adoc
Hello @MarkEWaite, @kwhetstone, @markyjackson-taulia, @oleg-nenashev I noticed a few minor fixes while I was preparing for my demo today. Kindly review.
Also, I wasn't able to successfully deploy Jenkins on my local machine using helm, it'll take me more time to be able to figure out what the problem is. So I decided to demo Jenkins operator and since we have the option of using helm to install the Jenkins operator, I figured it would be a good opportunity to show the use of helm and Jenkins operator in one demo using the documentation
> Jenkins operator

- content/security/reporting.adoc
@daniel-beck @MarkEWaite 
This will help new users to file report in SECURITY without using the mailing list.
_(or perhaps I did something wrong when I tried to register a new account)_
> Adding information about how to login to Jira

- content/doc/developer/handling-requests/_chapter.yml
- content/doc/developer/handling-requests/deprecated-reflective-access.adoc
- content/redirect/stapler-reflective-access.adoc
See https://github.com/stapler/stapler/pull/199#discussion_r543287882
@jglick
> Stapler reflective access redirect

- content/blog/2020/12/2020-12-16-call-for-mentors.adoc
Edits suggested by @MarkEWaite on #4029
> add suggested edits :)

- content/_data/roadmap/roadmap.yml
As discussed in the Jenkins governance meeting today﻿
> Modernize mirror infra is done - INFRA-2516

- content/doc/book/managing/system-properties.adoc
New system property `jenkins.install.SetupWizard.adminInitialApiToken` is added to the list of "Jenkins Features Controlled with System Properties"
> JENKINS-57484 - Admin's Initial API token is documented.

- content/doc/book/managing/system-properties.adoc
Documentation PR for https://github.com/jenkinsci/jenkins/pull/4965
> [JENKINS-63833] Make the groovy script source customizable

- content/_data/authors/nextturn.adoc
- content/doc/book/managing/system-properties.adoc
GitHub does not handle account renaming well
> Fix GitHub ID of @nxtn

- content/doc/book/managing/system-properties.adoc
This will be follow up, after https://github.com/jenkinsci/jenkins/pull/4962 is released.
> Added Removed since on removed hudson properties

- content/blog/2019/05/2019-05-09-templating-engine.adoc
> Fix Broken Links in Blog Post

- content/doc/book/pipeline/syntax.adoc
- Added sample code;
- Remove duplicated sentences.
> Timeout option explained

- content/doc/developer/security/secrets.adoc
We get asked about this a lot, and it's not super obvious without reading the source code (and knowing a little bit about cryptosystems). I've tried to add useful info without getting too technical, though I can always add more details if desired.
@jeffret-b @Wadeck @daniel-beck @jglick
> Add info about encryption of secrets

- content/blog/2021/01/2021-01-12-new-year-report.adoc
This pull request incorporates the current state of the New Year 2020 blogpost.
It does not look very solid, but I am not sure we have capacity to polish it more. 
CC @markyjackson-taulia @MarkEWaite @alyssat
> 2020 New year blogpost

- content/projects/gsoc/2021/project-ideas/git-credentials-binding-for-pipeline.adoc
- content/projects/remoting/index.adoc
- content/sigs/cloud-native/index.adoc
- content/sigs/docs/index.adoc
- package-lock.json
Found several good choices while reviewing git plugin bug reports.
> add quickstart idea

- content/_data/roadmap/roadmap.yml
- content/sigs/docs/gsod/index.adoc
- Google Season of Docs 2020 is complete
- Hacktoberfest 2020 is complete
> Update docs roadmap items

- content/_data/changelogs/lts.yml
Missed this date when I created the original changelog for 2.263.3.
> Fix 2.263.3 release date - 25 Jan 2021

- content/css/jenkins.css
- content/participate/index.html.haml
See [WEBSITE-682](https://issues.jenkins.io/browse/WEBSITE-682)
Added the screenshot for before and after
Before
After
> Improving Jenkins Participate page

- content/_data/authors/mattzand.adoc
I like to join as an Outreach participant
https://www.jenkins.io/sigs/advocacy-and-outreach/
> Join Outreach group

- content/doc/book/system-administration/reverse-proxy-configuration-nginx.adoc
fix at Linux command 'useradd' for 'usermod'. Also added another linux command in case of 'nginx' user not found. Updated the nginx code comments and formatting.
> Added improvements in reverse-proxy-configuration-nginx documentation

- content/doc/developer/views/table-to-div-migration.adoc
https://github.com/jenkinsci/dockerhub-notification-plugin/pull/25
> Update groovy tables to div guide with change in 2.271

- content/doc/tutorials/kubernetes/installing-jenkins-on-kubernetes/jenkins-deployment.yaml
- content/doc/tutorials/kubernetes/installing-jenkins-on-kubernetes/jenkins-sa.yaml
- content/doc/tutorials/kubernetes/installing-jenkins-on-kubernetes/jenkins-service.yaml
- content/doc/tutorials/kubernetes/installing-jenkins-on-kubernetes/jenkins-volume.yaml
* fixed ClusterRole API group improperly indented
* removed illegal 'apply' verb
* fixed codestyle
> Fixed Kubernetes manifests

- content/blog/2021/02/2021-02-16-contributor-summit-online.adoc
> Spelling fix in Contributor Summit blog post

- content/projects/gsoc/2021/project-ideas/git-credentials-binding-for-pipeline.adoc
Email received by Mark Waite.  Don't merge this pull request until Rishabh approves it.
> Add Rishabh Budhouliya as git project mentor

- content/doc/developer/publishing/releasing.adoc
- content/doc/developer/publishing/requesting-hosting.adoc
With https://github.com/jenkins-infra/jenkins-maven-cd-action/issues/1 I have completed the work I think is needed to make JEP-229 attractive.
> [JEP-229] Noting possibility of CD in hosting guides

- content/projects/gsoc/2021/project-ideas/git-credentials-binding-for-pipeline.adoc
Agreed to mentor in an email reply.  Do not merge until Jeff approves this pull request.
> Add Jeff Pearce as GSoC mentor

- content/projects/gsoc/2021/project-ideas/automatic-spec-generator-for-jenkins-rest-api.adoc
- content/projects/gsoc/2021/project-ideas/jenkins-custom-distribution-service-updates.adoc
Adding a project proposal for enhancements to the custom distribution service project.  Mostly focusing on making it a locally running tool.  Feel free to make suggestions and additions.  Thanks!
> Add custom distribution service project idea

- content/_data/events/2021-02-23-contributor-summit.adoc
- content/_data/events/2021-02-25-contributor-summit-closing.adoc
- content/events/contributor-summit/index.adoc
- Add contributor summit as a major event
- Add contributor summit event page
> Add Contributor Summit to events

- content/projects/gsoc/2021/project-ideas/jenkins-custom-distribution-service-updates.adoc
- content/projects/gsoc/2021/project-ideas/plugin-installation-manager-tool.adoc
- content/projects/gsoc/2021/project-ideas/remoting-monitoring.adoc
I would like to propose my name for the mentoring of certain GsoC project ideas.
> Add sladyn98 as a mentor for gsoc projects

- content/redirect/pipeline-snippet-generator.adoc
For use in https://github.com/jenkinsci/workflow-scm-step-plugin/pull/42. CC @MarkEWaite
> Add redirect link for Pipeline Snippet Generator

- content/projects/gsoc/2021/project-ideas/pipeline-step-documentation-generator.adoc
- Add Oleg Nenashev as pipeline steps idea mentor
- Fix broken link in pipeline steps project idea
> Add mentor and fix a link

- content/projects/gsoc/2021/project-ideas/automatic-spec-generator-for-jenkins-rest-api.adoc
- content/projects/gsoc/2021/project-ideas/jenkins-custom-distribution-service-updates.adoc
- content/projects/gsoc/2021/project-ideas/plugin-installation-manager-tool.adoc
- content/projects/gsoc/2021/project-ideas/remoting-monitoring.adoc
CC @MarckK @MarkEWaite @sladyn98
> GSoC 2021 - Update plugin installation manager idea description, fix year metadata in project ideas

- content/security/for-maintainers.adoc
Origin branch because I'm lazy, please delete on merge.
> Clarify that the security team provides this information

- content/projects/gsoc/2021/project-ideas/automatic-spec-generator-for-jenkins-rest-api.adoc
- content/projects/gsoc/2021/project-ideas/remoting-monitoring.adoc
Would like to request to add my name to a few of the projects I would love to mentor.
> Add stellargo as mentor

- content/_data/changelogs/weekly.yml
Nice improvements arriving all the time.  Thanks very much!
> Add more items to 2.283 changelog

- content/_data/authors/salaboy.adoc
Hi there here is my Bio, 
I wanted to propose myself as a GSoC Mentor.
> Adding Salaboy Bio

- content/doc/book/installing/_installation_requirements.adoc
- content/doc/pipeline/tour/getting-started.adoc
- content/doc/tutorials/_prerequisites.adoc
- content/doc/tutorials/build-a-labview-app.adoc
Running in 256 MB RAM is not a recipe for success
> Recommend 1 GB minimum RAM

- content/projects/gsoc/2021/project-ideas/cloudevents-plugin.adoc
I am also adding Go as a possible skill that will be useful for this.
> Propose salaboy as a possible mentor

- content/sigs/advocacy-and-outreach/outreach-programs/index.adoc
- content/sigs/docs/gsod/2021/application.md
- content/sigs/docs/gsod/2021/organization-proposal.adoc
- content/sigs/docs/gsod/ideas.adoc
- content/sigs/docs/gsod/index.adoc
- Update the outreach programs description of GSoD
- Reorder GSoD project ideas by priority
- Add GSoD 2021 draft application & organization proposal
Currently assumes Jenkins on Kubernetes is the preferred project.
> Update GSoD info

- content/doc/book/installing/_docker-for-tutorials.adoc
- content/doc/book/installing/_docker.adoc
> Use blueocean 1.24.5 in docker install guide

- content/projects/gsoc/2021/project-ideas/tekton-client-plugin.adoc
- Updated project details based on past discussion on not having a hard dependency on `tkn` cli tool
- Updated quickstart to help students directly start with pipelines
> update: tekton client plugin gsoc 2021 proposal

- content/blog/2021/03/2021-03-22-governance-updates.adoc
> Fix a link from a blog post
