- content/events/index.html.haml
- content/sigs/docs/index.adoc
Meeting is on the fourth Friday of each month.
> Docs SIG now meets on fourth Friday of each month

- content/_layouts/frame.html.haml
Do we still need the page history link? Do people actually use it?
Can add it back, but was worried about links getting too cluttered
Fixes #2894
> Add report a problem link

- content/projects/gsoc/mentors.adoc
I added some very important links at the top of the mentor information page to the Google mentor responsibilities and mentor participant agreement.
> Add links for mentors

- content/_data/changelogs/weekly.yml
I need help on the phrasing of the changelog entry for [PR-4365](https://github.com/jenkinsci/jenkins/pull/4365).  The proposed changelog entry says:
> The permissions Overall/RunScripts, Overall/UploadPlugins, and Overall/ConfigureUpdateCenter permissions are now deprecated. Custom authorization strategy implementations that grant Overall/Administer without implying one or more of these three permissions and as configurations that grant any of these permissions to users without Overall/Administer will will no longer work as expected.
I don't understand the last sentence in that proposed changelog entry.  I rephrased it as:
> The permissions <code>Overall/RunScripts</code>, <code>Overall/UploadPlugins</code>, and <code>Overall/ConfigureUpdateCenter</code> are now deprecated.  Custom …
> Add changelog 2.222

- content/projects/gsoc/proposing-project-ideas.adoc
Otherwise the ToC gets duplicated, because Jenkins uses a different approach to ToC generation.
> GSoC 2020: Remove Table of Contents tag from the project ideas guide

- content/projects/gsoc/2020/project-ideas/jenkins-distribution-customize-service.adoc
- [:heavy_check_mark:  ] Added a quick start guide
**TO-DO**
I am not sure whether it would be a good idea to include all newbie friendly issues with the `component` war package manager plugin or just to have the applicant solve the general newbie friendly issues.
> Make the distribution-customize-service proposal publishable

- content/blog/2020/02/2020-02-25-vscode-caseStudy.adoc
The screenshots in the Case Study are not separated clearly and it looks a bit cluttered.
> Separating the screenshots in the VSCode Case Study.

- content/projects/gsoc/students.adoc
> GSoC 2020 - Adjust headers in the student guide so that the Project Proposal requirements are visible in ToC

- content/doc/book/architecting-for-scale.adoc
In addition to AWS and JCloud, users can also spin up slaves on Azure with a plugin maintained by the Azure DevOps team.
> Add reference and link to Azure VM Agents plugin

- content/project/team-leads.adoc
Reverts jenkins-infra/jenkins.io#2939
As a Governance Board member, I request a formal process for changing officer role description. IMO it should be discussed in the community
> Revert "Update events officer role"

- .github/CODEOWNERS
I suggest to explicitly mark Governance documents in the CODEOWNERS file. It is partially a folllow-up to #2939 which was merged without enough reviews. Right now such pull requests are automatically labeled, but it has low visibility. jenkins.io copy editors might miss it and handle a change as common documentation update, so highlightning the special case would be a good step IMHO. I think a clear distinction will be useful there to
CC @jenkins-infra/board
> CODEOWNERS - Explicitly mark the Governance Board as an owner for Governance-related pages

- content/_data/changelogs/weekly.yml
I broke the weekly changelog rendering with #2946  .  This fixes it.
Always provide screenshots of the proposed changelog page.  Helps the submitter see their proposal accurately and helps reviewers see the proposal also.
> End quoted string to fix weekly changelog rendering

- content/index.html.haml
Cleans up old announcements
* CDF Announcement will be one year tomorrow. There is another jumbotron entry for CDF in general
* Board Elections jumbotron is 3 months old, and the image is not good. Would be better to kill it
> Jumbotron - Remove the board elections and CDF announcement jumbotrons

- content/index.html.haml
We have completely reworked https://jenkins.io/participate/ since Hacktoberfest 2019 started. Now the page is quite fancy, and I believe we could promote it to highlight contributing opportunities to the website visitors.
> Add a permanent jumbotron for /participate

- content/_layouts/pipelinesteps.html.haml
- content/css/jenkins.css
*Before:*
the first step in https://jenkins.io/doc/pipeline/steps/workflow-cps-global-lib/ is 300,000 pixels long
*After:*
the step description is <1,000px long, you can expand the individual options recursively
To get a list of plugins with HUGE docs, please check: https://bl.ocks.org/zbynek/raw/16108faa00a11d6570a48126fc382ebc/?a
(that graph illustrates https://github.com/jenkins-infra/pipeline-steps-doc-generator/pull/18 )
CC @kwhetstone @uhafner @MarkEWaite
> Make pipeline steps collapsible

- content/_data/changelogs/weekly.yml
Thanks to @daniel-beck  for catching that mistake.
> Jenkins 2.226 jelly enum tag change fixes JENKINS-61385

- content/doc/tutorials/build-a-python-app-with-pyinstaller.adoc
The manual page for `docker run` says:
> By default a container’s file system persists even after the container exits. This makes debugging a lot easier (since you can inspect the final state) and you retain all your data by default. But if you are running short-term foreground processes, these container file systems can really pile up. If instead you’d like Docker to automatically clean up the container and remove the file system when the container exits, you can add the --rm flag
Thanks to @jglick for detecting that mistake!
> Remove docker image after use in the build

- content/projects/gsoc/2020/project-ideas/git-plugin-caching.adoc
Bobby's schedule has changed. He is unavailable for this year's Google Summer of Code.
@rsandell as reviewer to confirm yesterday's conversation.
> Remove rsandell as potential GSoC mentor

- content/projects/gsoc/2020/project-ideas/jenkins-x-openwrt-ppa.adoc
fix spelling of OpenWrt project, not OpenWRT
Under the request of some OpenWrt developer
> fix spelling of OpenWrt project, not OpenWRT

- content/doc/book/managing/_chapter.yml
- content/doc/book/managing/system-properties.adoc
This change moves https://wiki.jenkins.io/display/JENKINS/Features+controlled+by+system+properties to jenkins.io. I will setup a redirect later.
Eventually I would like to automate generation of the page, but it should be good enough for now
Screenshots:
> Migrate System Properties documentation from Wiki to jenkins.io

- content/projects/gsoc/mentors.adoc
Updating the mentor info page to match the updates made to the [official GSOC 2020 Timeline](https://summerofcode.withgoogle.com/how-it-works/#timeline).
> GSoC2020 Timeline update (remove absolute time references)

- content/projects/gsoc/2020/project-ideas/github-checks.adoc
Unfortunately I cannot longer be a mentor in this project due to the reasons outside my control. I wish the team good luck with the applications and the project, and I will be happy to help the project to succeed as a GSoC org admin. Have a great GSoC!
I do not stand down as a potential mentor in other projects, this is an exceptional case. FYI and sorry @uhafner @timja @jeffpearce @jonbrohauge @aagarwal1012
> Remove @oleg-nenashev from the GitHub Checks API project idea

- content/security/advisory/2020-03-25.adoc
https://github.com/jenkins-infra/jenkins.io/pull/2811 all over, because I don't learn.
> Remove 'LTS' prefix from LTS versions again

- content/doc/book/pipeline/multibranch.adoc
Updates the list of multibranch pipeline and organization folder implementations based on March 31, 2020 review of the [SCMNavigator implementations](https://jenkins.io/doc/developer/extensions/scm-api/#scmnavigator).
> Update multibranch and organization folder lists

- content/doc/book/pipeline/syntax.adoc
It is my understanding, from other sources (and inferred from classic build configurations), that label conditions can be used which should definitely be documented in this official syntax reference documentation but is completely missing atm.
> Document label condition configurability

- content/download/lts/index.adoc
As agreed on 2.204.* LTS line retrospective[1], I am proposing to adjust LTS schedule so that next LTS baseline will be selected in week 10 when .3 RC is published. It used to be in week 12 when .3 is released. There ware 2 reasons for this:
- Lately, we slowly shifted towards choosing too new baselines effectively shortening the core soak time. Making the call 2 weeks sooner (no matter how new the core) will create the time buffer for more issues to be discovered and fixed before the LTS is published.
- Core developers/reviewers tend to be busy testing during RC testing periods and preparing weeklies that are likely to be chosen an LTS baseline (LTS week 10-12). Making the call 2 weeks sooner will prevent the two to overlap.
[1] …
> Move the LTS baseline selection to take place 2 weeks earlier in the cycle

- content/_data/roadmap/roadmap.yml
New Windows Installer initiative was missing a link. I was unable to find an Jira ticket for it, so I referenced the blogpost for now.
@MarkEWaite @slide would it make sense to create a EPIC for it? If it exists, I would like to create items like switching the Installer to a .NET Core native WinSW executable as we discussed before.
> JEP-14 - Link the Windows Installer initiative

- content/_data/roadmap/roadmap.yml
JEP-14 presumes that the roadmap is mostly user-focused. So I went ahead and tried to restructure it accordingly. Also added some stories including GitHub Apps authentication, Checks API and Plugin manager UX updates. FY @uhafner @timja @daniel-beck
> JEP-14 - recategorize roadmap to focus on use-cases, not on components

- content/_data/roadmap/roadmap.yml
Add the IBM s390x, PowerPC 64 LE, and ARM 64 platform support items to the Jenkins roadmap.
I've created Jira epics for each of those three items and connected related bug reports into those epics.  We may want to consider finer grained phases in a discussion with Jim Crowley and others in the Platform SIG.  For example, I think that Jenkins agents on s390x would likely be more important than Jenkins masters, and would be more likely to be used.
> Add s390x, ppc64, and ARM to roadmap

- content/security/gift.adoc
- content/security/index.adoc
- content/security/reporting.adoc
Migrate https://wiki.jenkins.io/display/JENKINS/Rewards+for+reporting+security+issues from the wiki.
Some minor rephrasings, including two nontrivial updates:
* Extended the list of examples of people not eligible after changes to the Jenkins project. Not really a change as it's just examples, but since we now have SIGs and more substantial teams, it felt right to do that now.
* The issue needs to have been announced in a security advisory, not merely fixed. I think back when this was introduced, we didn't grant maintainers access to issues, so there never were "uncoordinated" releases (i.e. a fix that is published long before the advisory would be out), and this was implied. Today, it's not.
I would appreciate more eyes on the changes from the wiki page to ensure I didn't accidentally …
> Migrate rewards/gifts for reporters from wiki

- content/solutions/pipeline.adoc
Updated in March 2020 to match current declarative pipeline.
> Link to updated DZone pipeline reference card

- content/sigs/docs/index.adoc
Provide basic description as an umbrella for large scale topics to be
included in the Docs SIG roadmap.
> Add Admin Guide and User Guide as Docs Projects

- content/css/roadmap.css
- content/project/roadmap/index.html.haml
Blatant copy of https://css-tricks.com/responsive-data-tables/ + some padding tweaks. Also header color slightly changed to meet the 4.5 contrast requirement.
Apparently some media queries were already overriding the `table-cell` display, but it seemed easier to remove the conflicting implementation than to fix it.
Fixes #3051
> Responsive roadmap style

- content/_data/roadmap/roadmap.yml
As a maintainer of the Promoted Builds Plugin, I would like to add Promotion support story to the Jenkins long-term roadmap. [JENKINS-36089](https://issues.jenkins-ci.org/browse/JENKINS-36089) is the second most-voted Pipeline RFE, so I believe it is reasonable. CC @markyjackson-taulia @jonbrohauge @bicschneider who were interested in this story.
I also changed status of Pipeline as YAML to near-term, because @aytuncbeken is working on that at the moment. Maybe we could even change it to `current`
> Jenkins Roadmap: Add Promotion support for Pipeline, change Pipeline as YAML status to near-term

- content/doc/developer/views/index.adoc
Really not happy how this is the start of recreating wiki pages with bits of information lacking an overall concept, OTOH this information is so obscure that having it documented at all seems worthwhile. AFAICT, this has never been documented anywhere, and I've never come across it before today.
> Mention EMIT_LOCATION in docs on views

- content/doc/developer/publishing/releasing-experimental-updates.adoc
We just rolled out a GitHub App Authentication support in GitHub Branch Source Beta. This feature is released to the experimental update center. Unfrtunately our guidelines are slightly obsolete, and they do not include new ways to manage plugins in Jenkins. Tried to fix that.
Contributes to #2988 
CC @timja @bitwiseman
> Document how to use the Experimental update center from JCasC and Docker images

- content/redirect/distributed-builds.adoc
- content/redirects/distributed-builds.adoc
Due to a typo in the original Jenkins change, the URL linked there
currently is invalid. So add it temporarily, once everyone is on a
newer release we can delete it again.
----
[JENKINS-61932](https://issues.jenkins-ci.org/browse/JENKINS-61932) because https://github.com/jenkinsci/jenkins/pull/4633 got merged earlier than expected and I then lost track of it.
> [JENKINS-61932] Add redirect URLs for new empty page

- content/_data/changelogs/weekly.yml
Follow-up to the comment from @olblak 
> this service can be deleted at any moment it's still experimental, regarding packages they can be downloaded from mirror.jenkins-ci.org, archives.jenkins-ci.org
> Use mirrors.jenkins-ci.org/ instead of get.jenkins.io in the banner

- content/security/advisory/2018-02-05.adoc
Broke in https://github.com/jenkins-infra/jenkins.io/pull/1648 -- my best guess is that @bitwiseman wanted to be helpful and fix a typo, but it's not.
> Fix description of SECURITY-698

- content/download/index.html.haml
- content/download/thank-you-downloading-windows-installer.html.haml
This is a temporary fix until we fully deploy the new downloads site and fix the issues there.  After the fix Downloads at least ships recent releases as expected.
Windows link is hardcoded, because the "latest" symbolic link link is broken in the update center generator after MSI unpacking by defaul.
> [INFRA-910] - Use http://mirrors.jenkins-ci.org as a source of weekly releases, hardcode 2/232

- content/_data/roadmap/roadmap.yml
This pull request initializes roadmap items for the "Jenkins on cloud platforms" section. Roadmap items are yet to be formally discussed in the community, but at least it provides some overview of the current stories 
Open questions:
* Add Pluggable storage to the `future` section? might be too wide
* Adjust the Jenkins Kubernetes Operator status/wording? Will need feedback from @tomaszsek
Current look&feel:
> JEP-14: Initialize the "Jenkins on cloud platforms" roadmap section

- CONTRIBUTING.adoc
- README.adoc
Was following-up on https://twitter.com/wololock/status/1251837164599554048 and discovered that it might be difficult to discover the communication channels for the website
> Highlight Documentation SIG channels as contact points for the website contributions

- content/_data/roadmap/roadmap.yml
- content/sigs/platform/index.adoc
This PR updates the SIG page to list the ongoing/perspective projects, and it also adds roadmap items we discussed at previous SIG meetings. Roadmap is now a bit packed, but we will soon move two items to released (Windows Installer and Docker images).
SIG page is also updated to show items in ToC:
Roadmap:
SIG page:
ToC:
> Platform SIG - Add project descriptions and roadmap items

- content/_data/roadmap/roadmap.yml
- content/sigs/docs/index.adoc
Cleanup of the mock JCasc roadmap items which had no description/links. Addresses comments from @MarkEWaite about the Plugin management tool, and also fixes typo in #3090 while I was around
CC @timja @jetersen
> Roadmap: Add descriptions and links for JCasC-related entries

- content/_data/roadmap/roadmap.yml
Follow-up to #3091 from @markyjackson-taulia . That pull request was submitted from the master branch, so I cannot suggest a PR against it. 
Summary of changer:
* A new roadmap category is introduced specifically for Pipeline authoring
* Tool and Service integrations are moved to a separate category
* Text is slightly edited
Current layout:
> Roadmap pipeline

- content/participate/document.adoc
- content/sigs/advocacy-and-outreach/outreach-programs/index.adoc
- content/sigs/docs/gsod/index.adoc
- content/sigs/docs/index.adoc
This pull request initializes the GSoD landing page, including 3 initial project ideas and quick-start/overview documentation for technical writers. I did not follow the GSoC multi-page structure and put everything on a single page for now.
GSoD landing:
Docs SIG page:
Docs SIG ToC:
CC @sladyn98 @markyjackson-taulia @kwhetstone @MarkEWaite
> Google Season of Docs: Initialize landing and link it from other pages

- content/projects/gsoc/mentors.adoc
This changes clarifies and extends some items for the community bonding period. Also, I fixed some spelling entries while I was around.
> GSoC 2020: Extend and detail the expectations from mentors during the community bonding

- content/sigs/advocacy-and-outreach/index.adoc
This change adds some topics which are being actively worked on by the SIG. The list is not extensive, but I believe it would be a good start.
* Change indenting so that ToC is generated properly
* Add project descriptions for Outreach programs, online and offline events, social media outreach
Preview: 
Depends on #3105
> Advoacy&Outreach SIG: Extend the project descriptions

- content/solutions/index.html.haml
Accessing hash properties as methods seems unreliable (see comments in #3118), this should fix it.
CC @oleg-nenashev @MarkEWaite
> Avoid missing method error

- content/_partials/toptoolbar.html.haml
This change removes references to dated solution pages  and instead of that emphasizes sections of the User Guide which might be more relevant to users. I also added links to the contributor Guidelines, because why not?
I deliberately skipped the following Jenkins Handbook sections:
- https://www.jenkins.io/doc/book/using/ . This section is nearly empty 😢 
- https://www.jenkins.io/doc/book/blueocean/ . Maintenance state concerns
- "Tutorial Blog Posts" - should be refactored and just added to Tutorials as links
Before:
After:
> Revamp the Documentation menu in the toolbar

- content/index.html.haml
Google Summer of Code will announce accepted student projects May 4, 2020.
> Adjust GSoC jumbotron for May 4 announcement

- content/sigs/pipeline-authoring/index.adoc
As detailed in the [mailing list](https://groups.google.com/forum/#!topic/jenkins-pipeline-authoring-sig/3c4_ahmlYic), this update will move the last Friday of the months pipeline-authoring SIG meeting to roadmap discussions and statuses.
There has been no objection in the mailing list and the recording where this was discussed and approved by members of the sig is [here](https://www.youtube.com/watch?v=I6E5zAKjobo&list=PLN7ajX_VdyaOKKLBXek6iG8wTS24Ac7Y3&index=15&t=2s).
Once this PR is merged, I will update the Jenkins events calendar.
Thanks kindly 😺
> Updating end of month regular status meeting

- content/_data/changelogs/lts.yml
- content/_data/upgrades/2-222-2.adoc
- content/_data/upgrades/2-222-3.adoc
Correct the entries for Jenkins 2.222.2.  Jenkins 2.222.2 was not released to the artifact repository or the downloads site.
> Add changelog and upgrade guide for 2.222.3, edit 2.222.2

- content/artwork/index.html.haml
When migrating the Wiki, we forgot about this 3D model. It was still there but due to the redirection, it wasn't easy to access. Thanks to @kohsuke, we got the link to the archive file.
This is to make sure the model is now listed on the artwork page.
Screenshot:
> Jenkins 3D model was not migrated from Wiki

- content/projects/infrastructure/index.adoc
Removes the link to Azure sponsorship, minor cleanup for the rest
> Update the infrastructure provisioning section

- content/solutions/index.html.haml
Output of YAML.load actually uses strings rather than symbols as keys. Converting hash into AStruct makes them available using either string or symbol or method:
https://github.com/awestruct/awestruct/blob/master/lib/awestruct/astruct_mixin.rb#L19
https://github.com/awestruct/awestruct/blob/master/lib/awestruct/astruct_mixin.rb#L39
As identified in #3120 the hash->AStruct conversion sometimes doesn't happen. Using symbols instead of methods has only hidden the problem. Hopefully, this is the actual fix.
> Use quoted strings for YAML keys

- content/_data/authors/jonbrohauge.adoc
Apparantly made a "under the head" typo last year.
> Update author info: Fix erroneous twitter handle

- CONTRIBUTING.adoc
we use authors not only for blogposts, but also for some other use-cases. 
Having a hyperlink would not hurt.
> Contributing: Move author metadata guide to a separate section

- .github/CODEOWNERS
- CONTRIBUTING.adoc
This pull request...
* Introduces a new "maintainer guide" section in CONTRIBUTING
* Documents the Triage Team as discussed in https://groups.google.com/forum/#!topic/jenkinsci-docs/aunhIJbOvbc
* Document ownership for "special areas" so that prevent collisions between @jenkins-infra/copy-editors and owners of these areas. We had very few cases of that, but I think it makes sense to make it explicit since we onboard more contributors
* Extend the review and process documentation
* Add some commented-out ownership sections to `CODEOWNERS` in areas where we do not have GitHub Teams at the moment
FYI @MarkEWaite @timja @vsilverman @sladyn98 @daniel-beck @markyjackson-taulia
> Contributing: Introduce a Triage team and Maintainer Guide, define ownership areas

- content/projects/gsoc/2020/application.md
- content/sigs/docs/gsod/2020/application.md
- content/sigs/docs/gsod/index.adoc
Moves https://docs.google.com/document/d/1dioogEr7KUbzbIXeGRws84VZokFoJNGXRpGv1K6Qs3s/edit?usp=sharing to the website. The document  has passed through several cycles of review, so I consider it as a release-candidate version. Let's use this pull request and the page for future comments
> GSoD 2020: Publish the application draft on the website

- content/index.html.haml
Company is Red Hat, Inc., not RedHat, Inc.
> Fix Red Hat company name in sponsors hover text

- content/_data/upgrades/2-204-1.adoc
https://www.jenkins.io/doc/upgrade-guide/2.204/#global-configuration-save-and-configuration-as-code-plugin is broken otherwise.
Sorry for the origin branch, my local copy is a mess right now I cannot just stash away…
> Properly format as Asciidoc

- content/doc/book/installing/index.adoc
- content/download/index.html.haml
Describe LTS and weekly separately for Debian so that users retrieve the correct package signing key for the distribution they are using.  [Install page feedback (row 859)](https://docs.google.com/spreadsheets/d/1nA8xVOkyKmZ8oTYSLdwjborT0w-BpBNNZT0nxR9deZ8/edit#gid=1087292709) noted that we were providing inconsistent and incorrect instructions for the Debian package signing keys.
This uses https://pkg.jenkins.io for Debian package installation to match with the [existing weekly instructions](http://mirrors.jenkins-ci.org/debian/) and [existing LTS instructions](https://pkg.jenkins.io/debian-stable/).
* https://pkg.jenkins.io/debian-stable/
* http://pkg.jenkins-ci.org/debian-stable/ (note, this URL is HTTP, not HTTPS)
* https://pkg.jenkins.io/debian/
* http://pkg.jenkins-ci.org/debian/ …
> Fix Debian install instructions, add Red Hat & CentOS

- content/blog/2016/2016-05-25-update-plugin-for-pipeline.adoc
- content/blog/2018/08/2018-08-17-code-coverage-api-plugin-1.0-release.adoc
- content/blog/2019/06/2019-06-21-performance-testing-jenkins.adoc
- content/doc/developer/extensibility/action-for-all-projects.adoc
- content/doc/developer/plugin-development/pipeline-integration.adoc
Refer to [PR-4604](https://github.com/jenkinsci/jenkins/pull/4604) and [JENKINS-55973](https://issues.jenkins-ci.org/browse/JENKINS-55973) for the rationale.
Replaces the deprecated javax.annotations references with non-deprecated references to the spotbugs annotations package.
The deprecated javax.annotations were removed from Jenkins 2.231 and later.
> Use NonNull annotation instead of deprecated Nonnull

- content/events/index.html.haml
- content/events/online-meetup/index.adoc
Out events page is slightly dated, and it looks pretty bad when there is no upcoming events (like now). I suggest putting some text there sot that we could at least link users to other event listings.
> Add online and local meetup references to the events page

- content/_data/authors/Sagar2366.adoc
- content/_data/authors/afalko.adoc
- content/_data/authors/ayush_agarwal.adoc
- content/_data/authors/baymac.adoc
- content/_data/authors/buddhikac96.adoc
- content/_data/authors/fcojfernandez.adoc
- content/_data/authors/imoutsatsos.adoc
- content/_data/authors/kwhetstone.adoc
- content/_data/authors/linuxsuren.adoc
- content/_data/authors/loghijiaha.adoc
- content/_data/authors/marckk.adoc
- content/_data/authors/markyjackson-taulia.adoc
- content/_data/authors/mikecirioli.adoc
- content/_data/authors/nextturn.adoc
- content/_data/authors/nikhildarocha.adoc
- content/_data/authors/nodece.adoc
- content/_data/authors/oleg_nenashev.adoc
- content/_data/authors/rishabhbudhouliya.adoc
- content/_data/authors/sharepointoscar.adoc
- content/_data/authors/timja.adoc
- content/_layouts/gsocproject.html.haml
- content/projects/gsoc/2020/project-ideas/github-checks.adoc
- content/projects/gsoc/2020/projects/custom-jenkins-distribution-build-service.adoc
- content/projects/gsoc/2020/projects/external-fingerprint-storage.adoc
- content/projects/gsoc/2020/projects/git-plugin-performance.adoc
- content/projects/gsoc/2020/projects/github-checks.adoc
- content/projects/gsoc/2020/projects/jenkins-x-apps-consolidation.adoc
- content/projects/gsoc/2020/projects/machine-learning.adoc
- content/projects/gsoc/2020/projects/winsw-yaml-configs.adoc
- content/projects/gsoc/index.adoc
This pull request initializes the GSoC 2020 pages. I will update the jumbotron later once the blogpost is ready, and once students update their projects.
Landing:
Project page with embedded Google Doc (for now):
> GSoC 2020: Publish the accepted projects

- content/_partials/toptoolbar.html.haml
GSoC 2020 projects are grouped under https://www.jenkins.io/projects/gsoc/2020/projects/ . Yes, with two 'projects' in the path... It as confused regexps, so I also added a layout type check.
Before:
After:
> Fix rendering of the subprojects nav menu

- content/_data/roadmap/roadmap.yml
This change adds some ongoing outreach programs to the Jenkins roadmap
> Roadmap: Add more ongoing and planned Advocacy and Outreach stories

- content/projects/gsoc/2020/project-ideas/automatic-spec-generator-for-jenkins-rest-api.adoc
I am about linking this project idea from the roadmap, so an explicit OpenAPI link would not hurt
> GSoC 2020: Add a OpenAPI link to the Open API specification project idea

- content/_data/roadmap/roadmap.yml
This change...
* Adds all accepted project ideas to the roadmap, makes them `current`. https://www.jenkins.io/projects/gsoc/#projects
* Adds well defined project ideas to the `future` category. I added only ideas which have strong consensus and enough specifics in their descriptions. https://www.jenkins.io/projects/gsoc/2020/project-ideas/
> Jenkins Roadmap: Add GSoC 2020 projects and project ideas

- content/projects/gsoc/2020/projects/external-fingerprint-storage.adoc
Fixes the Gitter link and applies a few extra patches. CC @stellargo 
Current layout on the website:
> GSoC 2020 External Storage: Fix the Gitter link, add meetings section and merge sentences in the first paragraph

- content/_layouts/documentation.html.haml
- content/doc/tutorials/index.adoc
Currently the navigation bar takes about two pages full pages, and it is barely usable. Tutorial listing takes a lot of space, but at the same time it does not include recent tutorials. This pull request:
* Reworks the user docs nav bar as suggested in #3127
* Updates the documentation page to reference the tutorial blogs and other tutorials on a page instead of the navbar
Fixes #3127
> User documentation: rework the navigation bar and tutorials page

- content/doc/book/managing/system-properties.adoc
The table just doesn't work well for this, so use a definition list instead.
Very minor content updates. Sorted entries alphabetically.
> <img width="1196" alt="Screenshot" src="https://user-images.githubusercontent.com/1831569/81475584-8877bc80-920d-11ea-87ef-e436519840f6.png">
> <img width="843" alt="Screenshot" src="https://user-images.githubusercontent.com/1831569/81475739-48650980-920e-11ea-9500-e988a8a12da4.png">
> Use definition list instead of table for system properties

- content/_data/roadmap/roadmap.yml
Per @oleg-nenashev's advice, updating the link corresponding to the roadmap item Jenkins Templating Engine 2.0 to reference a [document](https://github.com/jenkinsci/templating-engine-plugin/blob/2.0/Version_2.adoc) outlining the scope of the 2.0 release.
> Update JTE 2.0 link on roadmap

- content/event-calendar.html.haml
Just a minor layout improvements for the event calendar. I am still not a big fan of the layout, but after the switch to weekly layout it is at least comprehensible on the screen. Maybe we could use an agenda view instead
> Event Calendar: Switch the default mode to weeks, make the calendar wider

- content/sigs/docs/gsod/index.adoc
- content/sigs/docs/index.adoc
> Docs SIG: Replace User Guide rework by a GitHub project, link the UI/UX hackfest from GSoD

- content/project/board-election-process.adoc
While working on https://github.com/jenkins-infra/jenkins.io/pull/3164 I noticed that this page could be improved significantly. 
* The page text is updated to reference the current state of the process
* History of decisions and changes is moved to the bottom
* 2019 decisions summary is explicitly added to the list 
There is no other substantial changes though "4 members are elected. If link:/blog/authors/kohsuke[Kohsuke] decides to resign, all 5 members will be elected" might benefit from additional feedback.
CC @jenkins-infra/board
> Jenkins Board Election Process: restructure the page

- content/_data/events/2020-05-15-jom-anchore.adoc
- content/events/index.html.haml
- content/sigs/docs/gsod/index.adoc
- content/sigs/docs/index.adoc
Google Season of Docs technical writers and user experience Hackfest contributors may benefit from an hour dedicated to answering questions and helping new contributors.
Also makes minor fixes to two other recurring events and removes the Securing Pipelines event that has been cancelled.
> Add Docs office hours

- content/_data/upgrades/2-121-1.adoc
- content/blog/2018/12/2018-12-14-java11-preview-availability.adoc
- content/projects/remoting/index.adoc
Stages documentation updates for https://issues.jenkins-ci.org/browse/INFRA-1105 . Should not be merged until the images are actually renamed
> [INFRA-1105] - Rename agent Docker image names

- .github/ISSUE_TEMPLATE/4-bug.md
- content/_layouts/frame.html.haml
GitHub does not really allow to append a description to a template, so I just put the entire template into URL...
> Improve the "Report a problem" button so that it uses the issue template

- content/projects/gsoc/2020/project-ideas/jenkins-distribution-customize-service.adoc
The link in question is on a gsoc(Google Summer of Code) project idea details page. That link was stated there as an example but to avoid confusion and in order to make it non-clickable I have backslashed it.
Closes https://github.com/jenkins-infra/jenkins.io/issues/3114
> Fixed distribution link that is not clickable

- content/doc/book/installing/index.adoc
A disclaimer is included to note that the FreeBSD packaging of Jenkins is maintained by the FreeBSD project.  That is similar to the OpenIndiana packaging that is also documented in the installation guide.
> Add FreeBSD install instructions

- content/_layouts/gsocproject.html.haml
- content/projects/gsoc/2020/projects.adoc
- content/projects/gsoc/2020/projects/custom-jenkins-distribution-build-service.adoc
- content/projects/gsoc/2020/projects/github-checks.adoc
This change modifies the mentor lists in GitHub Checks API and Custom Jenkins Distribution Build Service after the recent announcements. It also adds official support for the "advisor" role which we did not have on the website before.
I also added redirect for the https://www.jenkins.io/projects/gsoc/2020/projects/ link which currently leads to 404 if used directly
Sample layout:
> GSoC 2020 - Update the list of mentors and advisors + redirect for the projects link

- CONTRIBUTING.adoc
First time contributors are sometimes hesitant to start on an issue without being confident it is reserved for them.  This describes our using a comment in the issue to reserve the issue.
> Clarify issue assignment process for wiki migration

- content/events/online-hackfest/2020-uiux/index.adoc
The change improves rendering of project ideas and groups them together into domains. I have not moved ideas from Google Doc yet, but I will do i tafter this PR.
Sample:
> UI/UX Hackfest - Group ideas into projects

- content/events/online-hackfest/2020-uiux/index.adoc
For some reason `/#!` gets converted to `/<mark>!` and therefore the links are broken
> fix: mailing lists links are broken in the online-hackfest/2020-uiux

- content/projects/gsoc/2020/projects/custom-jenkins-distribution-build-service.adoc
This section adds the github project link to the Custom Distribution Service.
Closes: https://github.com/jenkinsci/custom-distribution-service/issues/1
> Add Custom Distribution Service github project link

- content/doc/book/pipeline/_chapter.yml
- content/doc/book/pipeline/cps-method-mismatches.adoc
- content/redirect/pipeline-cps-method-mismatches.adoc
Mostly a straight migration of the wiki page, although I removed some of the content in the "False Positives" section that discussed issues that have been fixed since the wiki became read only.
I have not yet built the site locally to check the rendered appearance. I will do that tomorrow. I did a quick check on what "Pipeline CPS Method Mismatches" looked like in the sidebar and it seems ok and is just a bit longer than all of the other page names. We could use "CPS Method Mismatches" in the sidebar instead if desired.
See also https://github.com/jenkins-infra/jenkins-infra/pull/1494 which adds a rewrite rule to redirect the wiki page to the new page.
Fixes #3194
> Migrate 'Pipeline CPS method mismatches' wiki page to jenkins.io

- content/doc/developer/extensibility/_chapter.yml
- content/doc/developer/extensibility/serialization-of-anonymous-classes.adoc
- content/redirect/serialization-of-anonymous-classes.adoc
Closes https://github.com/jenkins-infra/jenkins.io/issues/3214
Location `http://localhost:4242/doc/developer/extensibility/serialization-of-anonymous-classes/` under the `extensibility` section
- Jira issues linked with the description.
- 1st code snippet split in three lines for clarity
- Add JEP-200 link to `<URL>/blog/2018/01/13/jep-200`
Top level menu
Then
> [migrate] Serialization of anonymous classes

- content/css/jenkins.css
- content/projects/gsoc/2019/project-ideas.html.haml
- content/projects/gsoc/2020/project-ideas.html.haml
In asciidoctor you can define different table types (grid-all, grid-column, grid-row), this change makes sure the border styling is tied to the `grid-all` selector and does not depend on classes that are supposed to only change alignment.
Also
* Slightly thicker border for header (inspired by [table-bordered from Bootstrap](https://getbootstrap.com/docs/4.4/content/tables/#bordered-table))
* Minor markup changes on GSoC idea pages to use the same table styles and ensure there is enough space above the table.
CC @urwa
> Use grid-all as selector for tables

- content/doc/book/managing/system-properties.adoc
https://github.com/jenkins-infra/jenkins.io/issues/3273
Added anchors for system properties. IDs is the full system property name with `.` replaced by `_`. 
Added self-link for each property so that the reader can easily bookmark it. See also discussion in the comments below.
> Added anchors for system properties

- content/css/jenkins.css
- content/doc/book/managing/system-properties.adoc
Clean up after #3387 and #3376.
The anchors in plain HTML are compatible with disabled JavaScript, but IMO make editing the page substantially more cumbersome and error-prone: Every system property name needs to be specified three times in two different variants.
Screenshot both demonstrating anchor offset (it's below the header) and the re-indented description for the `buildsDir`, compare to https://www.jenkins.io/doc/book/managing/system-properties/#jenkins_model_Jenkins_buildsDir :
> <img width="2745" alt="Screenshot" src="https://user-images.githubusercontent.com/1831569/83305067-50f2a380-a200-11ea-94a2-1da1258df420.png">
> Cleanup system properties page

- content/doc/book/glossary/index.adoc
For issue https://github.com/jenkins-infra/jenkins.io/issues/3389
- Added anchor for `dt` element script (See https://github.com/jenkins-infra/jenkins.io/issues/3389, requires the change in `jenkins.css`)
- Removed manual anchors. 
- Checked that all generated anchor name are the same as the previous one. Space in a glossary term is replaced by a `-` in the anchor name. So, "Anchor" -> `anchor` and "Jenkins URL" -> `jenkins-url`
Now when the reader hover over a glossary term, a little link icon will appear (see screenshot). The reader can use it to bookmark the link. All previous links in-page or from another page work as the anchors have not changed. 
When clicked on a link to a glossary term, the text is now correctly positioned below the top navbar.
> Fix anchor jump in the Glossary

- content/_layouts/systemproperties.html.haml
- content/doc/book/managing/system-properties.adoc
Based on https://github.com/jenkins-infra/jenkins.io/pull/3396, only the latest commit (as of opening the PR) is new here.
Migrate the System Properties page to a YAML based generated format. Much easier to restructure output when we don't need to re-do all the content every time.
Unfortunately, we need a workaround due to the following constraints:
* Handbook code expects all pages to be adoc, not haml.
* We cannot inline code in adoc as we can in haml (AFAIK).
This is resolved by creating a new layout for this one page. An alternative could be to extract the actual list out of the handbook, but it seems worse structurally even if the internals would be cleaner. I have no interest in revising handbook code to handle haml pages.
We're also reordering the page content a bit, as …
> Make system properties page YAML-based

- content/doc/book/managing/system-properties.adoc
Builds on top of #3393. https://github.com/jenkins-infra/jenkins.io/pull/3396/files/028aae99e95f36ee88966da81afdee78643874bd..57e4bc98e8dd702f8bc9463b3e9a95a2f5ec5676 is the first iteration of content specific to this PR. Individual commits make (some) sense.
I used https://github.com/jenkinsci/jenkins/pull/4680 and clicked around a bit to get Jenkins to tell me which system properties it looked up, plus added a few more I knew about anyway.
Before: 109 system properties
After: 184 system properties
That's 75 more 🎉
> Document more system properties

- content/doc/book/installing/index.adoc
Page to migrate: [Offline+Jenkins+Installation](https://wiki.jenkins.io/display/JENKINS/Offline+Jenkins+Installation)
Destination on jenkins.io: [installing](https://www.jenkins.io/doc/book/installing/)
Migration notes
Create a new section in the "Installing Jenkins page" section called "Offline Jenkins Installation". Migrate the content from the wiki page into that section and confirm that it works as described.
> Migrate 'Offline Jenkins Installation' from wiki

- package-lock.json
- package.json
a small fix on Burguer-menu in small screen related at issue #3404 
Looks like there is some issue compatibility between jquery and bootstrap version. this fix was based on this [stackoverflow item](https://stackoverflow.com/questions/61176484/cannot-convert-object-to-primitive-value-error-in-react-application/61198996#61198996) 
Now we are working with `"jquery": "^3.5.1"`
> Fix to Hamburger Menu to small screens

- content/_data/roadmap/roadmap.yml
- content/css/roadmap.css
- content/js/roadmap.js
- content/project/roadmap/index.html.haml
See the discussion in https://groups.google.com/forum/#!topic/jenkinsci-dev/Ez7nZxlxSWk
Preview status:
Filtering:
> [JEP-14] - Preview status, Initiative labels, Roadmap filtering

- content/_data/roadmap/roadmap.yml
This PR removing pipeline-authoring sig items from the roadmap that are not clearly defined not detailed in JIRA.
> Removing items from roadmap for pipeline-auth sig

- content/project/roadmap/index.html.haml
Just a minor enhancement targeting potential roadmap contributors
> JEP-14: Add a link to documentation about adding roadmap items

- content/security/advisory/2013-01-04.adoc
- content/security/advisory/2014-10-30.adoc
- content/security/advisory/2015-11-11.adoc
- content/security/advisory/2016-04-11.adoc
- content/security/advisory/2017-02-01.adoc
- content/security/advisory/2017-03-20.adoc
- content/security/advisory/2017-04-10.adoc
- content/security/advisory/2017-04-26.adoc
- content/security/advisory/2017-07-10.adoc
- content/security/advisory/2017-08-07.adoc
- content/security/advisory/2018-02-05.adoc
- content/security/advisory/2019-05-31.adoc
- content/security/advisory/2019-07-31.adoc
- content/security/advisory/2019-08-07.adoc
- content/security/advisory/2019-09-25.adoc
- content/security/advisory/2019-10-16.adoc
- content/security/advisory/2020-03-09.adoc
Also quite a few occurrences of `blacklist` and `whitelist` which are pretty clunky now. CC @dwnusbaum to review those, perhaps there's better terms than I chose.
I only applied the changes to `/security/`. Some occurrences are left but those cannot be updated in documentation only:
* System properties
* Plugin artifact IDs and display names (if unchanged)
* class names
* URLs
> Use 'agent' term where possible, stop using 'blacklist' and 'whitelist'

- content/doc/book/installing/index.adoc
Previously it was at the same level as "Creating the first administrator user" and "Customizing Jenkins with plugins".
This change places it at the same level as "Jenkins Parameters and "Configuring HTTP".
> Offline Jenkins Install at correct heading level

- content/donate.adoc
This PR refactors the "Why donate?" text to avoid a long abstract (moved to the bottom). I also removed the "How to donate?" header which does not seem to be very useful in the current state.
> [JEP-15] - Refactor the "Why donate?" text

- content/project/conduct.adoc
See https://groups.google.com/forum/#!topic/jenkinsci-dev/u0T56f9MSZY for the context. The change is on hold until the updates are officially approved by the Jenkins Governance Meeting.
Changes summary:
CC @jenkins-infra/board @markyjackson-taulia @jeffret-b @tracymiranda who actively participated in the initial discussion.
> Jenkins Code of Conduct update

- content/security/advisory/2020-07-02.adoc
This aligns the entry more closely with similar ones.
Additionally, remove the ambiguous "read access to the form", as it seems to refer to System Read.
> Rephrase SECURITY-1632 for consistency

- content/projects/gsoc/2020/projects/github-checks.adoc
This pull request removes @Sagar2366 and @aagarwal1012 from the list of GitHub Checks API project mentors. 
CC @timja @uhafner
> GSoC 2020 - Remove inactive mentors from the GitHub Checks API project

- content/doc/book/pipeline/docker.adoc
- content/doc/pipeline/tour/agents.adoc
**node:7-alpine** tag is not supported any more, see the [Docker Hub](https://hub.docker.com/_/node) for more details.
As of 7 July 2020 the [first example](https://www.jenkins.io/doc/book/pipeline/docker/#execution-environment) of Pipeline execution fails:
```
[Pipeline] sh
+ docker inspect -f . node:7-alpine
Error: No such image or container: node:7-alpine
[Pipeline] sh
+ docker pull node:7-alpine
Pulling repository node
Get https://index.docker.io/v1/repositories/library/node/images: dial tcp 3.220.75.233:443: connection timed out
```
> Updated node docker image version

- content/_partials/thank-you-downloading-windows-installer.html.haml
Fixes: #3206 
I haven't migrated the 'See also' section at the bottom of the page. Let me know if it has to be done too.
EDIT - I just did. I removed the 'What next' section and added 'See also' in its place.
> Migrated 'Thanks for using Windows Installer' wiki page to jenkins.io

- content/changelog-stable/badge.json.haml
- content/changelog/badge.json.haml
This change exposes version metadata which can be also consumed by https://shields.io/endpoint . It is a more production-grade implementation for Jenkins core badges which were reverted in https://github.com/jenkinsci/jenkins/pull/4703 due to the high download traffic. CC @daniel-beck 
Sample JSON:
```json
{
"schemaVersion": 1,
"label": "Jenkins Weekly",
"message": "2.243",
"color": "blue",
"version": "2.243",
"date": "2020-06-30",
"changelogUrl": "https://www.jenkins.io/changelog/#2.243"
}
```
> Add JSON metadata for shields.io badges

- content/download/index.html.haml
- content/download/weekly/index.adoc
The CDF Graduation criteria requires us to document the release cycle ([checklist](https://docs.google.com/document/d/1Ldmtny6OfEtQlCqdFWqq9Z25cxkZFX6yNiRqOOxo77c/edit?usp=sharing)). At the moment there is no official documentation for the weekly releases, and I suggest to add one.
Once merged, I will also add the release lines documentation to the Jenkins core documentation and to the maintainer guide.
> Document the Weekly Release Line

- .github/workflows/compress-images-in-PRs.yml
- content/download/index.html.haml
This pull request restructures the Downloads page. Changes summary:
* Remove the big Jenkins banner on the top (consumes 1/3 of the page in the top)
* Simplify layouts, fix #3516 which impacts the mobile screens
* Move deployments to public clouds into a separate section. It was briefly discussed with @rtyler and other @jenkins-infra/board members before
* Reorder downloads: Push 3rd-party distributions to the bottom of the list, move WAR and Docker to the top
> Restructure the Downloads page

- content/_data/roadmap/roadmap.yml
- content/project/roadmap/index.html.haml
This patch slightly improves UX of the roadmap by redirecting users to the Pipeline Authoring SIG page referenced in the category metadata. I have also slightly expanded the text based on the SIG discussion notes.
CC @bitwiseman  @steven-terrana
> Pipeline Authoring Roadmap - Use links from initiative metadata, extend descriptions

- content/_data/roadmap/archive.yml
- content/_data/roadmap/roadmap.yml
- content/project/roadmap/index.html.haml
This change adds a "withdrawn" state to the roadmap initiatives and adds new `archive.yml` which will act as an archive for completed and wuthdrawn roadmap items
> JEP-14 - Add support for archiving roadmap items, expand status descriptions

- content/project/governance.adoc
- content/project/roadmap/index.html.haml
Finalizes the roadmap publishing. On-hold until the today;s governance meeting.
> JEP-14 - Add Roadmap reference to the Governance doc, remove work-in-progress disclaimer

- content/download/index.html.haml
We currently have no easily accessible way for people to confirm their manual war downloads are correct.
`update-center.json` has a checksum served via HTTPS, so updates in Jenkins are unaffected, but the initial download doesn't: `http://mirrors.jenkins.io/war/` isn't served via HTTPS, and `https://pkg.jenkins.io/war/` isn't there yet.
So add a sha256 checksum to the downloads page, retrieved via HTTPS from Artifactory during site build. This isn't pretty, but functional. Someone with more UI knowledge than me can figure out how to make this pretty.
Also link to the latest releases advertised on update sites; this way the download link and checksum will always match, and I always thought it was weird to advertise a specific release when that might not be what would be downloaded.
Also …
> Add checksum for war download

- content/redirect/starting-processes.adoc
Supports jenkinsci/jenkins#4683. Not needed without that, so best for merging to be held off given the review hell that PR is in right now.
> Add redirect for use by jenkinsci/jenkins#4683

- content/project/adopters/index.html.haml
Looks like the production build does not guarantee the keys order by default
> Adopters: Ensure that Adopters are always sorted

- content/changelog-stable/badge.json.haml
- content/changelog/badge.json.haml
Apparently shields.io parser does not always handle additional fields, so removing everything except the spec requirements from https://shields.io/endpoint
> Changelog badges: Ensure the shields.io schema is followed

- content/doc/book/installing/index.adoc
The purpose of this change is to make the content of
[Installing docker](https://www.jenkins.io/doc/book/installing/#installing-docker) section of the [Installing Jenkins](https://www.jenkins.io/doc/book/installing/) page compliant with the DRY principle.
Currently the content on the page contradicts with instructions at
https://www.jenkins.io/doc/pipeline/tour/getting-started/#prerequisites
> Updating "Installing Docker" section

- content/_data/changelogs/weekly.yml
Correctly classify 3 entries that were misclassified earlier.
Based on comments from @daniel-beck in https://github.com/jenkins-infra/jenkins.io/pull/3286#pullrequestreview-417682331
> Fix 2.237 changelog entries

- content/participate/code.adoc
- content/project/governance.adoc
This change is a bulk facelift of the Governance doc which is currently very dates. It does not make it perfect, but at least it starts the cleanup process
> Update the Governance document

- content/_data/changelogs/lts.yml
- content/_data/changelogs/weekly.yml
This pull request acts on agreements reached in the https://groups.google.com/forum/#!topic/jenkinsci-dev/CLR55wMZwZ8 thread. We agreed to discourage use of `whitelist/blacklist` and to recommend using `Allowlist/Denylist` or `Allowlist/Blocklist` instead. I believe we should act on this recommendation in the Jenkins core, and hence the changelog update.
AFAICT none of the changes are confusing in the context of the changelog, even if the underlying changes in the Jenkins core and blogposts  have not been made yet
CC @jglick since the changelog entry updates are mostly about JEP-200
> Replace the whitelist/blacklist terminology in the changelogs

- content/doc/book/pipeline/docker.adoc
"While this section will cover the basics of utilizing Docker from with a `Jenkinsfile`"  >>>> "While this section will cover the basics of utilizing Docker from within a `Jenkinsfile`"
> Suggested fix for grammatical typo

- content/_data/changelogs/weekly.yml
Adds links to https://www.jenkins.io/blog/2020/07/23/windows-support-updates/ to the changelog , and adds an explicit changelog link to the https://issues.jenkins-ci.org/browse/JENKINS-12660 fix
CC @NextTurn
> Reference the Windows Support Policy updates blogpost in the 2.248 changelog

- content/_data/upgrades/2-235-3.adoc
Broken blog post link in the upgrade guide for 2.253.3 until this is merged.
> Use correct blog post location

- content/doc/book/pipeline/getting-started.adoc
Removed text that would make one think that `env` is only available to Scripted syntax
> Small doc change

- content/blog/2020/07/2020-07-29-git-performance-improvement-phase2.adoc
The links to blog posts use a slightly different format than on disc path.  The links to other pages do not need the `.adoc` extension.
> Fix issue #3580 - broken links in Git plugin blog post

- content/doc/developer/publishing/source-code-hosting/forks.adoc
I plan to propose a cleanup of fork relationships soon, this is delivering the data for it so we know the scope.
Downstream of https://github.com/jenkins-infra/infra-reports/pull/24
> <img width="893" alt="Screenshot" src="https://user-images.githubusercontent.com/1831569/89183943-5241a300-d598-11ea-84ac-181565438eb3.png">
> <img width="885" alt="Screenshot" src="https://user-images.githubusercontent.com/1831569/89183958-57065700-d598-11ea-8079-795a4a03fb54.png">
> Add report on forked repositories in jenkinsci GitHub org

- content/blog/2020/02/2020-02-10-t-mobile-case-study.adoc
Replace content of case study with a page noting that the case study has been removed.
The URL to the case study will still include the name of the company that provided the case study, but there will be no mention of the company name in the list of blog posts.  The prior author reference to an employee of the company has been removed as well so that the page will be less likely to be associated with the company.
Once we resolve WEBSITE-630, this page can be deleted.
> Avoid WEBSITE-630 non-deletion of removed files

- content/blog/2020/02/2020-02-10-t-mobile-case-study.adoc
The case study has been removed.  Links to it from within the site have been removed as well.  This redirect should only be visible to those who find the page through a search engine.
> Redirect deleted case study to 404

- content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins.adoc
Special thanks to [Karl Palsson](https://github.com/karlp) for [his instructions](https://github.com/jenkins-infra/jenkins.io/issues/3599). I was able to use to confirm that my nginx reverse proxy would not allow a websocket agent to connect before these changes and was able to connect a websocket agent after the changes were applied.
See https://github.com/jenkins-infra/jenkins.io/issues/3599 for the details provided by Karl.
> Add websocket configuration for nginx reverse proxy

- content/redirect/api-token.adoc
- content/redirect/csrf-protection.adoc
- content/redirect/fingerprint.adoc
- content/redirect/installation-wizard.adoc
- content/redirect/offline-installation.adoc
- content/redirect/remote-api.adoc
- content/redirect/report-an-issue.adoc
- content/redirect/securing-jenkins.adoc
- content/redirect/troubleshooting/broken-reverse-proxy.adoc
Redirect to wiki would then redirect to www.jenkins.io in many of these cases.  In other cases, the information in the wiki is much less accurate than the information on www.jenkins.io.
> Remove redundant redirects to wiki

- content/doc/book/managing/cli.adoc
Amending #1164 & #2807 to better reflect https://github.com/jenkinsci/jenkins/pull/4369 as in https://github.com/jenkinsci/jep/blob/master/jep/222/README.adoc#cli and the fact that `-remoting` is long gone. CC @dwnusbaum
> Updates to /doc/book/managing/cli/ esp. w.r.t. -webSocket

- content/_partials/thank-you-downloading-windows-installer.html.haml
The reverse proxy instructions have migrated to www.jenkins.io so we can link to them instead of linking to the wiki page.  Can also include a link to the IIS instructions (though it is not clear if the IIS instructions are still useful for the current version).
> Link Windows install page to www instead of wiki

- content/_partials/thank-you-downloading-windows-installer.html.haml
Missed two single quote characters that broke https://www.jenkins.io/download/thank-you-downloading-windows-installer/
Reminder that I should have attached an image of the page to confirm that I'd shown that the page renders correctly.
> Fix broken windows install page

- CONTRIBUTING.adoc
Includes a link to a video showing the steps.
> Add instructions for creating a redirect

- content/doc/developer/publishing/source-code-hosting/forks.adoc
The report already contains the org on the `jenkinsci` side, so adding this is redundant.
Thanks @aheritier for pointing it out.
> Fix links to jenkinsci repos in table

- content/projects/infrastructure/index.adoc
Link to the GitHub repository for source code and to the update center site from the service name.
> Add update center as a self-hosted service

- content/doc/book/managing/system-properties.adoc
since v2.223 this system property was set, and I could not find any documentation in which I could check what happened to all my truncated description builds since the update. I hope my contribution is helpful
> update system-properties.adoc documentation for historyWidget.descriptionLimit

- content/redirect/serialization-of-anonymous-classes.adoc
#3378 accidentally broke the redirect URL when migrating the corresponding documentation from the wiki to jenkins.io.
The redirect link before this change (404): https://jenkins.io/doc/developer/extensibility/serialization-of-anonymous-classes.adoc
The redirect link after this change: https://jenkins.io/doc/developer/extensibility/serialization-of-anonymous-classes/
> Fix redirect URL for serialization of anonymous classes

- content/events/hacktoberfest.adoc
Last year's Hacktoberfest pull requests resolved the open issues and provided many more platforms in the plugin.
Please delete the branch after the merge
> Remove platformlabeler from Hacktoberfest list

- content/doc/book/installing/index.adoc
_Addition of step to run `sudo systemctl daemon-reload`_ 
This change includes addition of `sudo systemctl daemon-reload`  after `sudo yum install jenkins java-1.8.0-openjdk-devel` .  The `reload` will ask systemd to scan the system units as in this case, the installation of the Jenkins service did not cause systemctl to read the service.This is to fix [issue #3522] (https://github.com/jenkins-infra/jenkins.io/issues/3522)
> Fix for Jenkins install doc issue #3522

- content/projects/gsoc/2020/projects/git-plugin-performance.adoc
Update the GSoC 2020 Git Plugin Performance Improvement Project Page with the latest blog post link.
> [GSoC Project Page] Add phase 3 blog post link to the project page

- content/_layouts/corebaseline.html.haml
- content/doc/developer/plugin-development/choosing-jenkins-baseline.adoc
- content/sigs/cloud-native/pluggable-storage.adoc
- scripts/fetch-external-resources
Alternative to https://github.com/jenkins-infra/jenkins.io/pull/3643 with more aggressive recommendations after @jglick's feedback.
This will now newly recommend the "previous" LTS line (2.222.1 today, 2.235.1 in two weeks) and "previous previous" LTS line (2.204.1 today, 2.222.1 in two weeks) unless a plugin has been recently split from core; in that case, it would (as before) recommend the current and previous lines.
> Recommend specific core versions for the dependency (more aggressive recommendations)

- content/projects/gsoc/2020/projects/custom-jenkins-distribution-build-service.adoc
1. Fixing the link to phase 3 blog post (was pointing to PR instead of blog post itself).
1. Made links to jenkins.io using relative links.
1. Add myself to list of mentors for the record
CC @sladyn98 @kwhetstone
> Custom distro: fix links to blog posts

- content/index.html.haml
- content/projects/gsoc/2020/index.adoc
- content/projects/gsoc/2020/projects/custom-jenkins-distribution-build-service.adoc
- content/projects/gsoc/2020/projects/external-fingerprint-storage.adoc
- content/projects/gsoc/2020/projects/git-plugin-performance.adoc
- content/projects/gsoc/2020/projects/github-checks.adoc
- content/projects/gsoc/2020/projects/jenkins-x-apps-consolidation.adoc
- content/projects/gsoc/2020/projects/machine-learning.adoc
- content/projects/gsoc/2020/projects/winsw-yaml-configs.adoc
- content/projects/gsoc/index.adoc
> [GSoC 2020] - Park GSoC pages and update the project statuses

- content/_data/upgrades/2-249-1.adoc
[JENKINS-63656](https://issues.jenkins-ci.org/browse/JENKINS-63656) reports that agents cannot connect to Jenkins 2.249.1 if they rely on the second URL that was previously provided to inbound agents.  The second URL has been intentionally removed in [PR-4839](https://github.com/jenkinsci/jenkins/pull/4839) for websocket compatibility.  Users will need to change their agent configuration to use the "Tunnel connection through" option in the "Advanced" section of the inbound agent configuration.
[JENKINS-63646](https://issues.jenkins-ci.org/browse/JENKINS-63646) reports that the `statusFilter` key has been removed from the configuration as code definition.  It was removed as part of list view performance improvements in [PR-4466](https://github.com/jenkinsci/jenkins/pull/4466). …
> Add statusFilter and alternate URL to 2.249.1 upgrade guide

- content/sigs/docs/gsod/ideas.adoc
- content/sigs/docs/gsod/index.adoc
- content/sigs/docs/index.adoc
Changes:
* Move Google Season of Docs to top of docs projects
* Refine intro paragraph to show project is in progress
* Update Docs SIG participants list
> Update Google Season of Docs pages inside Docs SIG

- content/_data/upgrades/2-249-1.adoc
I should have used this in the original upgrade guide.  I incorrectly ignored the upgrade guide entry in the original upgrade guide pull request.
@res0nance , sorry that I missed your recommended upgrade guide text from the [pull request](https://github.com/jenkinsci/jenkins/pull/4466)  .  I'll try to not make that mistake in the future.
> Include statusFilter upgrade content provided with pull request

- content/_data/roadmap/roadmap.yml
Follow-up on the Governance Meeting. It splits the Custom Jenkins Build Distribution service to two initiatives, and adds Custom WAR Packager 2.0 as an entry.
> Roadmap: Update the Jenkins packaging stories

- content/_data/roadmap/roadmap.yml
This change updates the roadmap for Jenkins on Cloud Platforms:
> Roadmap: Update/Extend the Jenkins roadmap for Cloud Platforms

- content/project/board-election-process.adoc
This is a follow-up to the Aug 26 and Sep 16 Jenkins governance meetings where we were discussing changes to the Jenkins Board and Officer election process towards the 2020 elections ([meeting notes and recording links](https://docs.google.com/document/d/11Nr8QpqYgBiZjORplL_3Zkwys2qK1vEvK-NYyYa4rzg/edit#heading=h.cgd8zbewht8o)). Developer mailing list thread: https://groups.google.com/g/jenkinsci-dev/c/NQg-_xhrT-0
On hold until Governance board members approve it
> Update the Board and Officer election process doc

- content/index.html.haml
This change replaces the old CDF Announcement jumbotron by the elections announcement. We already have a cdCon announcement, and I believe we can remove the second CDF one until the conference is over
> Add Jumbotron for 2020 Elections

- content/download/mirrors.adoc
Encourage additional mirrors in areas where traffic is increasing, like India, South America, and Africa.
> Remove mirror reference to hudson-labs

- content/events/hacktoberfest.adoc
Spent some time to create more featured project entries and to make the list more technology-diverse
> Add Plugin Site, Jenkinsfile Runner and Terminology cleanup as featured projects

- content/project/governance-meeting/index.adoc
I noticed that the Governance Meeting page still hardcodes IRC while we switched to Zoom by default.  In this patch I updated the description to focus more on the meeting's purpose and on contributing to the meeting.
Needs approval from board members before merging
> Update Governance meeting documentation and add participation guidelines

- content/_data/upgrades/2-249-1.adoc
Avoid null pointer exceptions when Windows agents attempt to connnect to Jenkins 2.248 and later.  See the [changelog](https://github.com/jenkinsci/windows-slaves-plugin/releases/tag/windows-slaves-1.7) and [JENKINS-63223](https://issues.jenkins-ci.org/browse/JENKINS-63223) for more details.
> Add WMI Windows agent plugin ref to 2.249.1 upgrade guide

- content/doc/book/blueocean/creating-pipelines.adoc
- content/doc/book/using/using-credentials.adoc
- content/pipeline/getting-started-pipelines.adoc
Fixed terminology in "Pipeline" tutorials (issue #3837)
> Replaced offensive terminology in documentation ('master' -> 'controller')

- content/events/hacktoberfest.adoc
- content/events/hacktoberfest/faq.adoc
This change updates the guidelines so that they reflect https://hacktoberfest.digitalocean.com/hacktoberfest-update on Oct 03. It is a minimum viable fix, ideally there should be more changes made in maintainer and user guidelines.
CC @MarkEWaite @halkeye @markyjackson-taulia
> Hacktoberfest - Update the page to reflect Hacktoberfest policy updates

- content/doc/book/installing/_docker-for-tutorials.adoc
- content/doc/book/installing/_run-jenkins-in-docker.adoc
- content/doc/book/installing/_setup-wizard-for-tutorials.adoc
There is a long standing set of issues, related to using outdated Jenkins docker image on the Jenkins site.
Switching entire site to official Jenkins Docker image is not a trivial project and IMO it is better to incrementally address all the issues, related to such migration of images.
This PR addresses the issues related to using new official Jenkins docker image in Jenkins Tutorials.
> Use official Jenkins Docker image for tutorials

- content/doc/developer/publishing/releasing-experimental-updates.adoc
- content/participate/report-issue.adoc
> Fixing terminology in 'Developer' documentation

- content/doc/developer/handling-requests/actions.adoc
- content/doc/developer/handling-requests/stapler-accessible-type.adoc
- content/doc/developer/publishing/documentation.adoc
- content/doc/developer/publishing/plugin-site.adoc
Fixes #3862 
The files:
content/doc/developer/extensions/jenkins-core.adoc
content/doc/developer/extensions/script-security.adoc
content/doc/developer/extensions/yaml-project.adoc
are retained, since their change will require modification of code and will break existing links.
> Fixed term in 'Dev' section of docs

- content/projects/index.adoc
> Fix broken image reference to Google Season of Docs

- content/project/board.html.haml
- content/project/governance.adoc
The replacements are adequate for the needs, though in one case they include several links to the wiki.  One step at a time.
> Replace a few wiki links in governance docs

- content/doc/book/system-administration/_chapter.yml
- content/doc/book/system-administration/diagnosing-errors.adoc
Migrate: https://wiki.jenkins.io/display/JENKINS/I%27m+getting+OutOfMemoryError#
to: https://www.jenkins.io/doc/book/system-administration/diagnosing-errors
Fixes #3726
> Hacktoberfest: migrate `Diagnosing Errors` to github

- content/doc/book/managing/_chapter.yml
- content/doc/book/managing/user-content.adoc
Migrate: https://wiki.jenkins.io/display/JENKINS/User+Content
To: https://www.jenkins.io/doc/book/managing/user-content/
Fixes #3778
> Hacktoberfest: Migrated User Content from wiki to doc page

- content/sigs/chinese-localization/index.adoc
Hi @zhaoying818 and @yJunS, thanks you guys for the long contributions. I'm going to add you two as the participants of Chinese Localization SIG.
Others are no longer active for a while. But welcome to join us any time.
> Update participants of Chinese Localization SIG, remove alauda as a org

- content/doc/book/installing/_docker-for-tutorials.adoc
- content/doc/book/installing/_docker.adoc
- content/doc/book/installing/_setup-wizard-for-tutorials.adoc
- content/doc/book/installing/docker.adoc
- content/doc/book/pipeline/docker.adoc
- content/doc/pipeline/tour/agents.adoc
- content/doc/tutorials/build-a-java-app-with-maven.adoc
- content/doc/tutorials/build-a-multibranch-pipeline-project.adoc
- content/doc/tutorials/build-a-node-js-and-react-app-with-npm.adoc
- content/doc/tutorials/build-a-python-app-with-pyinstaller.adoc
The tutorial instructions need to mount the user home directory for easy access to a local fork of a GitHub repository.  They may also need to grant access to port 3000 for the NodeJS tutorial runtime testing.  Currently, the NodeJS runtime testing on port 3000 does not work.  This change does not make it any more broken than it already is.
* Update Dockerhub hyperlinks
* Update node output value in sample
* Use correct Docker name for tutorial stop command
* Fix errors in Docker install instructions
* Sync Docker tutorial with Docker install guide
* Reduce diffs between _docker.adoc & _docker-for-tutorials.adoc
* Remove trailing white space
* Move log and dir access to correct level
* Reduce length of Fork header in tutorial
> match docker tutorials to install instructions

- content/doc/book/installing/_docker-for-tutorials.adoc
- content/doc/book/installing/_docker.adoc
﻿Calling the jar command directly is workable but is not how it is described in the documentation for the Docker image.
> Use jenkins-plugin-cli to install plugins in Docker

- content/index.html.haml
Restores the .participate jumbotron. There is a collision with the Elections jumbotron image we need to resolve, but it can be done as a follow-up
> Remove the Hacktoberfest Jumbotron, use the Participate one

- STYLEGUIDE.adoc
Don't refer to Pipeline as beta in the contributing guide.﻿
> Pipeline has released

- STYLEGUIDE.adoc
- content/doc/book/installing/_kubernetes.adoc
- content/doc/book/installing/kubernetes.adoc
- content/doc/book/installing/linux.adoc
- content/doc/pipeline/tour/hello-world.adoc
The Kubernetes and Linux sections included an extra heading and were using a different heading depth than the other install sections.  Top level topics should be placed at the left of the contents so that it is obvious they 
are top level topics.
- Indent Kubernetes table of contents
- Fix Linux install indent
> Use consistent layout in install sections

- content/doc/book/installing/initial-settings.adoc
- content/doc/book/installing/macos.adoc
- content/doc/book/installing/offline.adoc
- content/doc/book/installing/other.adoc
- content/doc/book/installing/war-file.adoc
Heading is already provided by the title of the page, no need for an additional opening heading
> Remove duplicate install section headings

- content/blog/2020/09/2020-09-24-board-elections.adoc
- content/blog/2020/10/2020-10-28-election-candidates.adoc
- content/index.html.haml
- content/project/board-election-process.adoc
As it was discovered today and verified with @MarkEWaite @slide @uhafner , CIVS allows adding new voters in the current usage mode. It allows to extend the voter registration beyond Nov 08. Taking the low voting period duration and the relatively low registrations number at the moment, I see no reason to not extend the registration period.
Needs approval from @slide @uhafner before merging
> [2020 Elections] - Extend the voting sign-up until Nov 24

- content/_data/changelogs/weekly.yml
* Fixes categorization of https://github.com/jenkinsci/jenkins/pull/4517
* Adds changelog references in https://github.com/jenkinsci/jenkins/pull/4951 , highlights removal of deprecated protocols
> Amend changelogs based on 2.249.3 backporting review

- content/_data/events/2020-11-17-kubecon.adoc
- content/_data/events/2020-11-24-jenkins-elections.adoc
- content/_data/events/2020-11-25-swiss-devwednesday.adoc
- content/_data/events/2020-12-04-jenkins-day-japan.adoc
- content/_data/events/2021-02-06-fosdem.adoc
- content/events/fosdem/archive/2020.adoc
- content/events/fosdem/archive/2021.adoc
- content/events/fosdem/index.adoc
Adds calendar events for known Jenkins events and meetups. It also updates the FOSDEM page and archives the 2020 content
> Add Jenkins events: Elections, Kubecon, Jenkins Day Japan, Dev.Wednesday, and FOSDEM

- Gemfile
- Gemfile.lock
﻿Previous version used https://issues.jenkins-ci.org/ while the new version uses https://issues.jenkins.io/
See https://github.com/jenkins-infra/asciidoctor-jenkins-extensions/releases/tag/v0.8.0
> Use asciidoctor extension 0.8.0

- content/_data/changelogs/lts.yml
- content/_data/changelogs/weekly.yml
- content/download/index.html.haml
A Microsoft Azure storage issue (timeout and failure to mount) has broken the Jenkins mirror system.  This announces the issue in downloads page, weekly changelog, and LTS changelog.
> Add banner noting downloads are unavailable

- content/blog/2020/10/2020-10-21-a-sustainable-pattern-with-shared-library.adoc
Resolve https://github.com/jenkins-infra/jenkins.io/issues/3971 that reports the bad link.
`doGenerateSubmoduleConfigurations: false` is the default.
`doGenerateSubmoduleConfigurations: true` is untested and unlikely to work.
We hope in a future release of the git plugin to stop suggesting it as an option in the pipeline syntax generator without breaking backwards compatibility.
submoduleCfg: [] is the default.
It is only honored if `doGenerateSubmoduleConfigurations: true` is set.
> Fix pipeline library blog link

- content/projects/infrastructure/index.adoc
﻿* Mirrors - get.jenkins.io - geographic distribution
* Downloads - pkg.jenkins.io - downloads site
* Updates - updates.jenkins.io - update center
> Include more self-hosted entries

- content/doc/book/installing/_docker-for-tutorials.adoc
This PR does the following:
- Fixes [Issue #31](https://github.com/jenkins-docs/simple-node-js-react-npm-app/issues/31) in Jenkins tutorials
- Enables creating more node js tutorials with default settings
Current PR affects only Jenkins in Docker installation for Tutorials without touching general Jenkins in Docker install instructions.
> Opened dind port 3000 to enable more tutorials

- content/doc/developer/views/table-to-div-migration.adoc
Clarify that the first LTS to transition from table based form layout to div based form layout is expected to be March 2021﻿, not the "next" LTS.
Would like review from @jtnord and @timja to confirm the phrasing works for them
> March 2021 expected to be first LTS with table to div

- content/doc/book/managing/script-approval.adoc
"In-process Script Approval" is not visible if no approvals were made or pending. This is explicitly stated in the introduction now.
> Script Security introduction is reworded.

- content/sigs/platform/index.adoc
Doodle poll had responses that were OK with either this time or with the current time.
Since the new time is a little easier on me personally, I chose the new time,
Friday at 13:00 UTC.﻿
> Moved platform SIG meetings to Fridays 13:00 UTC

- content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins.adoc
Reported by gitter user @DaGeRe
﻿Also avoid converting the example URL into a clickable URL and don't use bold text for the examples.
> Fix --prefix arg usage in reverse proxy doc

- content/doc/book/installing/_kubernetes.adoc
zsh uses the path variable to store parts of PATH, so the commands listed on the kubernetes install page will break the environment in zsh by changing PATH, e.g.:
```
$ echo $SHELL
/bin/zsh
$ echo $path
usr/local/bin /usr/bin /bin /usr/sbin /sbin
$ echo $PATH # built dynamically from the parts of $path
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
$ # enter example commands from the kubernetes installation page
$ path="{.data.jenkins-admin-password}"
secret=$(kubectl get secret -n jenkins jenkins -o jsonpath=$path)
echo $(echo $secret | base64 --decode)
zsh: command not found: kubectl
zsh: command not found: base64
$ echo $PATH
{.data.jenkins-admin-password}
```
Replacing path with jsonpath in these commands eliminates this possibility while keeping the structure of the commands the same.
> zsh-friendly kubernetes install commands

- content/doc/book/system-administration/_chapter.yml
- content/doc/book/system-administration/reverse-proxy-configuration-troubleshooting.adoc
- content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins.adoc
- content/redirect/troubleshooting/broken-reverse-proxy.adoc
The redirect from inside Jenkins core uses https://www.jenkins.io/redirect/troubleshooting/broken-reverse-proxy to provide diagnostic hints to the user.  Without this fix, that redirect is broken.
This change also splits the reverse proxy configuration page into two pages, one with the general introduction and navigation links and the other with the troubleshooting section. It includes additional redirects in case there are pages that link from internal page references to the original page.
Thanks to @DaGeRe for reporting the issue
> Fix redirect to "Jenkins says my reverse proxy setup is broken"

- content/_layouts/advisory.html.haml
Forgot to do this as part of https://github.com/jenkins-infra/jenkins.io/commit/58ceb03b30a604b7adab1c8d4238ff8aa2fff016 and so https://www.jenkins.io/security/advisory/2020-12-03/? doesn't list PIMT on top.
This PR fixes the problem.
> List components on top of the advisory

- content/doc/developer/security/index.adoc
Relates to recent changes made in LDAP plugin and subsequently also being introduced in Active Directory plugin.
@jeffret-b @Wadeck @daniel-beck @jglick
> [JENKINS-55813] Document support for user validity

- content/participate/review-changes.adoc
Resolve issue #4018
[Dead links report](https://github.com/jenkins-infra/jenkins.io/issues/4018)
> Explain why GitHub team links seem broken

- content/_partials/video.html.haml
- content/index.html.haml
The Jenkins Governance Board meeting Oct 21, 2020 approved that the video may be placed on the root page of https://jenkins.io below the Jumbotron.
The video is intentionally placed below the features segment and above the events calendar.  It is "edge to edge" to match the Jumbotron layout and provide visual separation for the calendar and blog content that follows the video.
See the [meeting notes](https://docs.google.com/document/d/11Nr8QpqYgBiZjORplL_3Zkwys2qK1vEvK-NYyYa4rzg/edit#) and [video recording of the meeting](https://youtu.be/zBOwRubg7FE?list=PLN7ajX_VdyaMsOs5pRWGByvIcuJOpHpC6&t=1034) for more details.
CC: @alyssat , @slide , @uhafner , @halkeye , @markyjackson-taulia , @oleg-nenashev 
Also corrects an error in the name of macOS.
> Add "Jenkins is the Way" video to root page

- content/doc/book/installing/_kubernetes.adoc
Link points to the wrong location in deployed site.  See the "section" reference in the [Create Jenkins deployment file](https://www.jenkins.io/doc/book/installing/kubernetes/#create-jenkins-deployment-file) page.
> Fix link to k8s namespace creation instructions

- content/doc/developer/views/table-to-div-migration.adoc
Linked to example at https://github.com/jenkinsci/notification-plugin/pull/40/files with more blockWrapper style variants provided in additional files.
> Update table-to-div-migration.adoc - link to more blockWrapper examples, and note compatibility with older Jenkins core versions

- content/_partials/plugins.html.haml
Thanks to @rcrocomb for the suggestion that it would be enough to remove the plugin icons.  Removing the icons makes the content readable again.
> Fix #4036 - icon overlays plugin text on solutions page

- content/doc/book/installing/_docker-for-tutorials.adoc
- content/doc/book/installing/_docker.adoc
- content/doc/book/installing/_kubernetes.adoc
- content/doc/book/installing/linux.adoc
- content/doc/tutorials/kubernetes/installing-jenkins-on-kubernetes/jenkins-deployment.yaml
﻿JDK 11 is the most recent Java long term support release and the most recent Java release supported by Jenkins.  Let's encourage people to use it rather than remaining with JDK 8.  JDK 11 support is better than JDK 8 on ARM and other specialized platforms and it is also well supported on the more common platforms like 64 bit Linux and 64 bit Windows.
Resolves #4050 
Resolves #4048
> Use JDK 11, not JDK 8 for install & examples

- content/_data/changelogs/weekly.yml
﻿The 2.274 MSI installer is now available.  Packaging script changes in https://github.com/jenkinsci/packaging/pull/205 and https://github.com/jenkinsci/packaging/pull/206.  Those packaging changes have been merged to the stable-2.263 branch as well.
> Remove MSI banner from 2.274 changelog

- content/projects/gsoc/2021/project-ideas/git-credentials-binding-for-pipeline.adoc
Allow Jenkins Pipeline users to run authenticated git commands in sh, bat, and powershell.
Propose to implement https://issues.jenkins.io/browse/JENKINS-28335, one of the top 5 most voted Jenkins issues.
> Propose git credentials pipeline step as GSoC project idea

- content/doc/book/installing/_docker-for-tutorials.adoc
- content/doc/book/installing/_docker.adoc
Use Jenkins 2.263.2 in the Docker install instructions instead of Jenkins 2.263.1
CC: @vsilverman﻿
> Use Jenkins 2.263.2 in Docker install instructions

- content/doc/book/installing/_kubernetes.adoc
I found [here](https://www.jenkins.io/doc/book/installing/kubernetes/) some mistakes.
Added missed links.
Fixed typo in port number.
P.S.: I hope I used correct AsciiDoc syntax.
> Documentation: Installing Jenkins in Kubernetes: added missed links

- content/doc/book/system-administration/_chapter.yml
- content/doc/book/system-administration/obtaining-a-thread-dump.adoc
See  #3760
`install Jenkins as a Windows service` documentation is in it's earlier form but I did found a updated version of it [here](https://jenkins-le-guide-complet.github.io/html/sect-windows-service.html), probably change the url after the documentation is migrated
And www.latenighthacking.com/projects/2003/sendsignal/ from `a tool like this` is no longer working so I replaced it with Java Mission Control  from oracle [here](https://docs.oracle.com/javacomponents/jmc-5-5/jmc-user-guide/toc.htm/) 
Also changed master to controller as mentioned in issue,
> Migrate obtaing a thread dump documentation

- content/_data/changelogs/weekly.yml
I missed the https://github.com/jenkinsci/jenkins/pull/5191 entry in the changelog because it was merged after the initial draft was completed and I did not reconstruct the changelog entry.
> Include external storage fix in 2.276 changelog

- content/doc/book/installing/_docker-for-tutorials.adoc
- content/doc/book/installing/_docker.adoc
Blue Ocean 1.24.4 was released to remove the explicit depdendency on the Blue Ocean Jira plugin.
@vsilverman I checked that the instructions work as expected on my Linux computer running Docker.  There was a comment in the [docs feedback page](https://docs.google.com/spreadsheets/d/1nA8xVOkyKmZ8oTYSLdwjborT0w-BpBNNZT0nxR9deZ8/edit#gid=1087292709) yesterday that reported failure to download a plugin while the docker image was being built.  I don't see that failure.  However, if a mirror is misbehaving, that might be the result to the user.
> Use blue ocean 1.24.4 in Docker install guide

- content/doc/book/scaling/architecting-for-scale.adoc
Hello,
I noticed that while reading the [Architecting for Scale](https://www.jenkins.io/doc/book/scaling/architecting-for-scale/) page, the "Agent communications" header was not properly being recognized. I've added a carriage return which seems to do the trick.
> Fix minor carriage return issue on Architecting for Scale page

- content/doc/book/installing/_docker-for-tutorials.adoc
- content/doc/book/installing/_docker.adoc
Jenkins 2.263.3 released today.  Let's use it in the docker install.
CC: @vsilverman, @StackScribe
> Use Jenkins 2.263.3 in docker install instructions

- content/blog/2021/02/2021-02-08-docker-base-os-upgrade.adoc
The phrasing for the JDK change from OpenJDK to AdoptOpenJDK was not clear enough.  We've already switched from OpenJDK to AdoptOpenJDK for JDK 11.  This change is making JDK 8 consistent with JDK 11.
Does not mention the additional benefit from updating package versions in the operating system.  For example, there are valuable performance improvements in the transition from command line git 2.11 (Debian 9) to command line git 2.20 (Debian 10).
> Better phrasing of JDK change and fix a typo

- content/_data/upgrades/2-263-4.adoc
See https://www.jenkins.io/blog/2021/02/08/docker-base-os-upgrade/ for details.
> Add Docker image upgrade to Jenkins 2.263.4 guide

- content/doc/book/managing/system-properties.adoc
Deleted as of https://github.com/jenkinsci/jenkins/pull/5047.
There must be some more maintainable way to generate this list so that it stays in synch with reality automatically. An annotation processor?
> Removing mention of system properties related to ZFSInstaller

- content/doc/administration/requirements/upgrade-java-guidelines.adoc
- content/doc/book/managing/nodes.adoc
- content/projects/gsoc/2018/remoting-over-message-bus.adoc
- Replace slave term with agent in nodes.adoc groovy
- SSH build agents, not SSH slaves
> Improve terminology

- content/blog/2021/02/2021-02-16-contributor-summit-online.adoc
Still an early morning hour for the U.S. west coast, but not as painful as 13:00 UTC.
> Correct the summit start time 15:00 UTC

- content/_data/changelogs/weekly.yml
> <img width="1310" alt="Screenshot 2021-02-19 at 18 05 51" src="https://user-images.githubusercontent.com/1831569/108536777-1e805d80-72dd-11eb-8c60-713a3dafe77c.png">
> Reference 2021-02-19 security advisory in 2.280 changelog

- content/_data/solutions/android.yml
- content/blog/2018/01/2018-01-08-moving-from-buddybuild-for-android.adoc
Fixes https://github.com/jenkins-infra/jenkins.io/issues/4128
> Android lint plugin superseded by warnings-ng

- content/_data/changelogs/weekly.yml
- content/security/advisory/2021-02-19.adoc
- only specify the advisory date when it's different from the release
- discuss older releases' behavior in present tense
Untested.
> Minor fixes in changelog and advisory for 2.280

- content/chat.adoc
- content/project/governance-meeting/index.adoc
They are not actually used anymore, so lets not direct people there.
> Remove some of the old irc webchat links from the governance pages

- content/_data/changelogs/weekly.yml
> Include LDAP 2.3 upgrade in 2.279 changelog

- content/_layouts/frame.html.haml
- content/_partials/legacy/navbar.html.haml
- content/_partials/legacy/resources.html.haml
- content/_partials/toptoolbar.html.haml
@StackScribe and @halkeye this was one of the ideas discussed in the Docs track of the Contributor Summit
> Add more links to roadmap

- content/doc/book/blueocean/pipeline-editor.adoc
Docs feedback asked for more clear instructions
These instructions already exist and show step by step how to create a Pipeline in less than 2 minutes.
@bitwiseman are we allowed to use this video in the Jenkins documentation?
> Include Jenkins Minute video in Pipeline Editor page

- content/projects/gsoc/2021/project-ideas/pipeline-step-documentation-generator.adoc
Good ideas for improvements and the doc generator code has received several improvements through @zbynek and @MarkEWaite since this idea was proposed in 2020.
Might fit very well in the 175 hour estimate of time for the Google Summer of Code contributions this year.
Assumed that @kwhetstone is willing to be a mentor for this project (with the assumption that we would not ask her to mentor more than one project).
> Add pipeline steps doc generator improvement idea

- content/doc/book/installing/war-file.adoc
No need for a directory relative link when a site local link provides the same simple navigation and works as expected.
> Fix #4136 with site local link

- content/_data/roadmap/roadmap.yml
- content/sigs/docs/gsod/2021/application.md
- content/sigs/docs/gsod/ideas.adoc
- content/sigs/docs/gsod/index.adoc
- content/sigs/docs/index.adoc
- Add GSoD 2021 to roadmap
- Redirect 2020 GSoD project to dedicated page
- Move GSoD 2020 to archive section
- Update GSoD ideas for 2021
> Archive GSoD 2020, prepare for GSoD 2021

- content/doc/book/installing/_docker-for-tutorials.adoc
- content/doc/book/installing/_docker.adoc
Need to automate this in the future.
> Use Jenkins 2.277.1 for install

- content/_data/upgrades/2-263-4.adoc
[JENKINS-65069](https://issues.jenkins.io/browse/JENKINS-65069) reports that the user was unable to register a custom certificate authority in the Docker image beginning with Jenkins 2.263.4.
The issue is known to AdoptOpenJDK and a fix is in progress.  See [Adoptium issue 105](https://github.com/AdoptOpenJDK/openjdk-installer/issues/105) for the latest status.
A workaround is provided in [issue 8243](https://github.com/jitsi/jitsi-meet/issues/8243#issuecomment-744181944) of the jitsi-meet project.
Special thanks to Oleg Nenashev for locating the work around and to Hashim for reporting the issue and investigating it so effectively.
> [JENKINS-65069] Refer to AdoptOpenJDK CA issue for Debian 10 Docker image

- content/redirect/building-on-controller.adoc
Redirect from building-on-controller to old page Security+implication+of+building+on+master. For now. The page needs to be rewritten and moved elsewhere and then the redirect target link updated.
See jenkinsci/jenkins#5337. This is intended to be used as additional information for two new admin monitors warning people against building on the controller.
> Add a redirect for info about building on controller.

- content/doc/administration/requirements/jenkins-on-java-11.adoc
- Fix #4170 Add backslash to Java 11 docker command
- Use current weekly instead of old weekly
- Correct the Java 11 issue tracker links
- Remove note about outdated Jenkins versions
> Fix Java 11 docker syntax #4170

- content/doc/book/installing/index.adoc
- content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins.adoc
The Javascript that redirects references from inside one page (like installing#windows) to another page (like installing/windows) will redirect the user to a page "undefined" (ike installing/undefined).  This is an experiment that hopes to redirect the search result to the same page.
Works in my local test environment, but won't be 100% confident until I've seen it work on the jenkins.io site.
> Fix #4167 Redirect Algolia search id into same page

- content/doc/book/installing/_docker-for-tutorials.adoc
- content/doc/book/installing/_docker.adoc
The Docker Pipeline plugin dependency was intentionally removed from blue ocean 1.24.5 so that users would be able to install blue ocean without requiring the Docker Pipeline plugin. We need the Docker Pipeline plugin for the tutorial, so we'll include it explicitly.
Still an issue: 4184 - mount point does not exist
> Install docker-workflow plugin for tutorial use

- content/_data/upgrades/2-277-1.adoc
> Fix images in upgrade guide

- content/doc/book/using/remote-access-api.adoc
Hi there!
I am maintainer of aiojenkins and wish to add it package to documentation
https://github.com/pbelskiy/aiojenkins
PS: it's would be quite good to rewrite this four packages to a new one which will support both sync and async adapters.
> add aiojenkins (async python client) to documentation

- content/doc/book/system-administration/security.adoc
This is just a proposal, I can see two ways of doing this:
* the one I documented.
* simply modifying the Groovy init script/JCasc configuration to push the Unsecure realm.
Not sure which one is the best one, but I think we should at least mention one as the current approach seems misleading for some people.
> Explain how to deactivate security with JCasc

- content/doc/book/system-administration/authenticating-scripted-clients.adoc
Reader recommended that we make the username more explicit.
Switched to RFC compliant example hostnames in the same change.
Branch on the jenkins.io repository, please remove the PR branch after merging.
> Clarify example based on user feedback

- content/index.html.haml
Short term addition to the Jumbotron.  Event starts April 1, 2021 and concludes April 30, 2021.
> Add SheCodeAfrica Contributhon to Jumbotron

- content/_data/upgrades/2-263-2.adoc
Mention the specific [security advisory](https://www.jenkins.io/security/advisory/2021-01-13/#SECURITY-2021) in the upgrade guide.
> [JENKINS-65169] Add section for agent name security fix

- content/doc/book/pipeline/syntax.adoc
this pr updates the declarative pipeline docs to warn users about the pipeline limit documented here: https://issues.jenkins.io/browse/JENKINS-37984
> Warn users about declarative pipeline loc limit

- content/project/trademark/index.adoc
We are working on the EasyCLA adoption with the Linux Foundation Team, and they suggested changes in the first paragraph wording for the trademark. No changelog update needed for the page, it is a minor update
> Trademark: Update the intro text as suggested by the LF legal team

- content/doc/book/installing/_docker-for-tutorials.adoc
- content/doc/book/installing/_docker.adoc
this PR adds the --storage-driver overlay2 in the default command for Linux installation. The description points to the docker documentation for available driver options. 
ping @dduportal
> add --storage-driver option for linux build

- content/doc/book/system-administration/diagnosing-errors.adoc
Explicitly tell Groovy not to return the last statement
Also harmonize the style throughout the script (that was mixing string interpolation and concatenation).
> Tidy up instance info reporting

- content/project/governance-meeting/index.adoc
Changing the governance meeting time as agreed yesterday.
Maybe we should remove explicit time from the documentation ad refer the event calendar.
> Change the Governance meeting time to 7PM UTC

- content/doc/book/blueocean/pipeline-run-details.adoc
Refer to https://www.jenkins.io/doc/pipeline/steps/workflow-basic-steps/#archive-archive-artifacts
archive: Archive artifacts
Archives build output artifacts for later use. As of Jenkins 2.x, this step is deprecated in favor of the more configurable archiveArtifacts.
> Use archiveArtifacts instead of deprecated archive

- content/_data/upgrades/2-277-1.adoc
Note in the 2.277.1 upgrade guide passwords encoded with Jenkins before 1.480.1 are no longer supported.  Users with passwords that have not been changed since that time will need to update their passwords before they upgrade to Jenkins 2.277.1.
See [JENKINS-65107](https://issues.jenkins.io/browse/JENKINS-65107) for more details.
CC: @jglick for review if available
> [JENKINS-65107] old password encoding support removed

- content/doc/pipeline/tour/hello-world.adoc
https://www.jenkins.io/doc/book/pipeline/getting-started/#through-the-classic-ui
Caution: Jenkins uses this item name to create directories on disk. It is recommended to avoid using spaces in item names, since doing so may uncover bugs in scripts that do not properly handle spaces in directory paths.
> Avoid space in item name

- content/doc/book/installing/_docker-for-tutorials.adoc
- content/doc/book/installing/_docker.adoc
- content/doc/book/pipeline/docker.adoc
- content/doc/book/pipeline/syntax.adoc
- content/doc/tutorials/build-a-java-app-with-maven.adoc
Blue Ocean 1.24.6 released a week or two ago.  I've been using it since shortly after release.  Good to update the install guide so that users don't immediately see warnings about plugin updates.
> Use blue ocean 1.24.6 in Docker install

- content/doc/book/pipeline/docker.adoc
- content/doc/book/pipeline/syntax.adoc
- content/doc/tutorials/build-a-java-app-with-maven.adoc
- content/doc/tutorials/build-a-node-js-and-react-app-with-npm.adoc
- Use Docker image from a supported maven tag (broken by me in #4261)
- Use supported nodeJS docker image instead of nodeJS 6
> Fix maven and nodeJS tutorials

- content/doc/developer/index.html.haml
The page https://plugins.jenkins.io/ says there're over 1500 plugins
> Using consistent number of the plugin count

- content/project/index.adoc
https://github.com/jenkinsci/jenkins/blob/master/docs/MAINTAINERS.adoc#team should be a good link for that for now, no need to create a jenkins.io entry right away IMHO
> Add the Release team to the list of teams in /project

- content/index.html.haml
- content/projects/gsoc/index.adoc
Just a quick update of the landing to update the status
> GSoC 2021: Update the main page to reflect the current status, add org admin links, remove jumbotron

- content/blog/2021/04/2021-04-21-tekton-plugin.adoc
The plugin is in alpha, so the `plugin` macro does not work. Sorry for misleading you @jstrachan
> Fix the Tekton Client plugin links

- content/doc/book/using/using-agents.adoc
In section "Creating your Docker agent", the regex used by egrep should be in single-quotes, or it causes syntax error.
> Fix the incorrect command-line instruction

- content/doc/developer/views/_chapter.yml
- content/doc/developer/views/exposing-bundled-resources.adoc
Content partially taken from https://github.com/jenkinsci/localization-support-plugin/blob/master/README.md
We probably should add `.svg` to resource suffixes we allow 😁 
TBD a section when to use which is probably useful, perhaps a comparison table, but this is better than the nothing we had before.
> ![Screenshot](https://user-images.githubusercontent.com/1831569/115953333-2205b000-a4eb-11eb-887d-a9c2c7e0b17e.png)
> Add help explaining how to use bundled resource files on the UI

- content/index.html.haml
Promotes the nominations a bit more + fixes the blog link in SheCodeAfrica. CC @MarkEWaite
> Add 2021 contributor awards to the Jumbotron + fix SheCodeAfrica and cdCon

- content/doc/book/security/build-authorization.adoc
- content/doc/book/security/configuring-content-security-policy.adoc
Amends #4283: I linked these in the sidebar, but forgot to change the page type accordingly.
> Make these documentation pages proper 'sections' of the doc

- content/doc/developer/views/exposing-bundled-resources.adoc
Turns out there's another way to serve static files that I missed before. 😒 
> <img width="1430" alt="Screenshot" src="https://user-images.githubusercontent.com/1831569/116094047-7f466080-a6a7-11eb-9d59-95536fc3b062.png">
> Document AssetManager

- content/security/fixing.adoc
- content/security/for-maintainers.adoc
Since many more repos now have a non-`master` default branch (usually `main`, GitHub's new default), use a more general term here.
> Properly reference the default branch

- content/templates/downloads.html.haml
To make the download index pages a bit nicer (see https://github.com/jenkins-infra/update-center2/pull/469 ) we'd need to have a template in this repository. Per @daniel-beck 's suggestion this PR adds a specific template so that the download pages and plugin site templates are independent.
> Template for download pages

- content/doc/book/security/_chapter.yml
- content/doc/book/security/managing-security.adoc
- content/doc/book/security/markup-formatter.adoc
- content/doc/book/security/securing-jenkins.adoc
<details>
> <img width="853" alt="Screenshot" src="https://user-images.githubusercontent.com/1831569/116238121-48348580-a761-11eb-8505-006a9f33cad5.png">
</details>
> Migrate Markup Formatter documentation to its own page

- content/projects/infrastructure/ircbot.adoc
The new feature was added by @slide in https://github.com/jenkins-infra/ircbot/pull/86 , but it has never been documented on the website. Added some basic docs and a backlink to the Hosting team documentation.
> Document the Hosting check command in the IRCBot

- content/_data/changelogs/lts.yml
- content/_data/changelogs/weekly.yml
- content/_partials/changelog-old.html
Rules mostly adhered to:
* Change "master" to "controller" when in scope of the mid 2020 decision (i.e. exclude the "master node", which is what has a launcher, labels, retention policy, can be offline, runs flyweight tasks, etc.), unless specifically referring to a UI label, error message, class or field name, system property, or file name that wasn't "agent" as of the changelog entry (some recent `slave.jar` references got changed, many others did not).
* Change "slave" or "slave agent" to "agent" 
* Change Hudson to Jenkins when referring to the application in entries for 1.396 and newer.
* Replace references to the plugins ssh-slaves and windows-slaves with their new labels SSH Build Agents and WMI Windows Agents; perhaps change surroundings for label consistency.
> Replace obsolete terminology in changelog

- content/doc/tutorials/kubernetes/installing-jenkins-on-kubernetes/jenkins-sa.yaml
Add namespace `jenkins` for ServiceAccount, then the ServiceAccount will be created in `jenkins` namespace, or it maybe creted in other namespace.
Reference:
https://www.jenkins.io/doc/book/installing/kubernetes/#create-a-service-account
> Add namespace for ServiceAccount

- content/doc/book/security/_chapter.yml
- content/doc/book/security/access-control.adoc
Intended to replace https://www.jenkins.io/doc/book/security/securing-jenkins/#access-control 
<details>
</details>
This may be slightly in conflict with the existing docs, especially those referencing obsolete wiki pages; I plan to clean those "legacy" pages up once we have some more new content.
> Add Access Control chapter

- content/doc/book/pipeline/docker.adoc
Update for this documentation: https://www.jenkins.io/doc/book/pipeline/docker/
Background: I spent almost whole day trying to find: how is it better to synchronize workspace inside container with workspace for another stages without container.
I think it is very important to include into the Handbook information about how docker agent workspace synchronized (or not) with workspace out of container.
Please check before merge:
* English grammar
* text style
* AsciiDoc syntax
* code logic: for example, I'm not sure this section will work for `agent: none`.
Maybe this new documentation section is connected with [JENKINS-41118](https://issues.jenkins.io/browse/JENKINS-41118).
Thanks for idea: https://stackoverflow.com/a/64249727/5287257
P.S.: this is my second contribution in Jenkins …
> Documentation: Handbook: Using Docker with Pipeline: Keep workspace synchronized (reuseNode)

- content/doc/book/installing/linux.adoc
See https://github.com/jenkins-infra/jenkins.io/pull/4308#issuecomment-829607890
- Use https for Fedora pkg repo in weekly
- Install chkconfig and java-devel before Jenkins
- Reload before launching Jenkins service
@mabuze does this look better?  Can you confirm that it works?
> Fix Fedora install guide

- content/_ext/handbook.rb
I've long wondered by handbook chapters proliferate while running the local `make run` development server and editing `_chapter.yml` files, and it seems to be this (unnecessary?) retention of state across handbook generator runs. This has been in there from the beginning, and I'm unsure why, perhaps @rtyler remembers why he did it like this in https://github.com/jenkins-infra/jenkins.io/pull/330?
<details>
<summary>Screenshot of the unexpected effect that is resolved by this change</summary>
</details>
> Reset the handbook chapters when initializing the handbook

- content/doc/book/security/index.adoc
Also renames it to "Securing Jenkins", which is kind of weird with the legacy subsection, but that'll be gone soon enough.
<details>
</details>
> Add an overview of the sections of the security chapter to the index

- content/doc/developer/plugin-development/pipeline-integration.adoc
If a plugin is wanting an optional field to be null if it's not set, it
will need to use Util.fixEmpty (which will coerce a null or empty
string to null) instead of Util.fixNull (which will coerce a null string
to an empty string). Fix the example so it works properly.
> Use correct method in example @DataBoundSetter

- content/doc/book/security/_chapter.yml
- content/doc/book/security/build-authorization.adoc
- content/doc/book/security/configuring-content-security-policy.adoc
- content/doc/book/security/index.adoc
- content/doc/book/security/user-content.adoc
Retain the existing page on CSP but replace it in the top-level structure with a more general "Rendering User Content" page that covers primarily the resource root URL.
Changes some of the CSP documentation introduction as it is no longer "standalone". Also, remove the content that made sense when it was new and instead say it's retained only for rare circumstances.
This and #4310 have a slight dependency: Merging this will slightly invalidate the summaries added there, but both can be merged as is and would just need a bit of followup.
<details>
<summary>Screenshots</summary>
> ![Screenshot](https://user-images.githubusercontent.com/1831569/116578947-334b2400-a912-11eb-8f15-c0f6d4c156ed.png)
> ![Screenshot](https://user-images.githubusercontent.com/1831569/116578963-36461480-a912-11eb-9e6 …
> Generalize CSP page to document serving user content

- content/templates/downloads.html.haml
Follow-up for #4286 , a CSS class name got lost when I translated HTML to haml.
> Add classname for download list

- content/participate/index.html.haml
Discovered while working on #4323: https://www.jenkins.io/participate/ does not disable anchors for headers, which looks really weird on that page.
> Remove anchors from /participate

- content/participate/report-issue/redirect.html.haml
It's a bit off center (should be 4 cards wide), but still looks reasonable.
Colors are from https://www.jenkins.io/changelog/ entry type colors and as such a lot brighter than https://www.jenkins.io/participate/ upstream's more muted colors. I think it's fine but feedback is welcome.
This is deliberately not linked from elsewhere on the site. The idea is to use this as the URL that gets referenced from [issue tracker metadata](https://github.com/jenkins-infra/repository-permissions-updater#managing-issue-trackers) and is linked from Jenkins (https://github.com/jenkinsci/jenkins/pull/5358) and the plugins site for plugins that track their issues in Jira. This will give plugins that track issues in Jira to have a landing page similar to …
> Add redirect page to report issues in plugins

- content/security/reporting.adoc
While writing https://www.jenkins.io/participate/report-issue/redirect/ I was confused about the advice on https://www.jenkins.io/security/reporting/ -- turns out https://github.com/jenkins-infra/jenkins.io/pull/4012 was merged despite my negative feedback.
I fixed Jira to add a reference to the account app on the login form, and made this part of the page less broken looking.
> <img width="860" alt="Screenshot 2021-05-04 at 10 12 57" src="https://user-images.githubusercontent.com/1831569/116976381-5898b300-acc1-11eb-8a06-d66d454216d2.png">
> <img width="853" alt="Screenshot 2021-05-04 at 10 13 04" src="https://user-images.githubusercontent.com/1831569/116976443-7108cd80-acc1-11eb-9ff3-f36ebc770df3.png">
> Update reporting/account signup info after Jira change

- content/doc/pipeline/steps/contents.json.haml
Adds a JSON file at jenkins.io/doc/pipeline/steps/contents.json that can be consumed by the plugin site so that each plugin page can link to the list of pipeline steps provided by the plugin.
> Add JSON list of contents for the pipeline reference

- content/doc/book/installing/_docker-for-tutorials.adoc
- content/doc/book/installing/_docker.adoc
- content/doc/book/installing/linux.adoc
- Install Jenkins 2.277.4 in Docker instructions
- Use Java 11 on Red Hat Linux
Fixes https://github.com/jenkins-infra/jenkins.io/issues/4336
> Use JDK 11 and current Jenkins in install guides

- content/doc/developer/plugin-development/build-process.adoc
Fixed the link to the changelog, since it is moved to GitHub releases.
> Fixed link to plugin POM releases

- content/_layouts/documentation.html.haml
This came up in #4357: The check in the handbook sidebar whether we're currently in a chapter makes assumptions about file hierarchy that aren't necessarily true. This makes it more flexible by using the same approach `active_href` is using (when fuzzy) to determine whether to mark a link as active.
Related to #4357 in that this is probably only effective on that PR's newly added page so far, and improves that PR's presentation, but they can be merged independently.
<details>
<summary>Screenshots</summary>
</details>
> Match how 'active_href' checks the current URL

- content/security/advisory/2017-04-10.adoc
Minor spelling fix in security advisory.  Found while reviewing #4359
> Sybversion -> Subversion in body text

- content/security/plugins.adoc
As discussed with @zbynek in https://github.com/jenkins-infra/update-center2/pull/522 we needed a good reference for suspended plugins.
Review of content for completeness/correctness and whether the introduction makes sense would be very welcome here 🙏 
<details>
> ![Handling Vulnerabilities in Plugins](https://user-images.githubusercontent.com/1831569/118331468-00578180-b509-11eb-9dba-1ee72a29838b.png)
</details>
> Document suspended plugins

- docker/default.conf
- Redirect to issues.jenkins.io, not issues.jenkins-ci.org
- Redirect /why to root of jenkins.io
- Avoid extra levels of redirection through wiki
> Update some URL rewrites

- content/doc/developer/plugin-development/incrementals.adoc
- content/doc/developer/publishing/_chapter.yml
- content/doc/developer/publishing/releasing-cd.adoc
- content/doc/developer/publishing/releasing-manually.adoc
- content/doc/developer/publishing/releasing.adoc
- content/redirect/continuous-delivery-of-plugins.md
Mostly an import of content from https://github.com/jenkinsci/incrementals-tools
> Add CD guide for releasing plugins

- content/css/jenkins.css
* `gutter` class is used by plugins site, but is styled there. The `!important` style here makes it harder to style it properly.
* `gutter-box` and `gutter` IDs are unused and related styles can be safely removed
> Remove unused CSS

- content/projects/gsoc/2021/projects/conventional-commits-plugin.adoc
This patch updates the conventional commits project page with the following information:
- link to the gitter channel
- link to the proposal
- link to the project repository 
- link of the original project-idea
Signed-off-by: Aditya Srivastava <adityasrivastava301199@gmail.com>
> Update GSOC 2021 Conventional Commits Project Page

- content/_data/changelogs/lts.yml
- content/_data/upgrades/2-289-1.adoc
> Changelog and upgrade guide 2.289.1

- content/_data/roadmap/roadmap.yml
Per @oleg-nenashev's comment in https://github.com/jenkins-infra/jenkins.io/pull/4372, updating the status to `released` for JTE 2.0
> Update JTE 2.0 to released on the roadmap

- content/_data/authors/cyrille-leclerc.adoc
- content/projects/gsoc/2021/projects/remoting-monitoring.adoc
- Welcome new mentor! @cyrille-leclerc 
- Link to OpenTelemetry
Target page
https://www.jenkins.io/projects/gsoc/2021/projects/remoting-monitoring/
@cyrille-leclerc 
I've created your page like [this](https://www.jenkins.io/blog/authors/aki-7/) with empty contents.
Please check it!
> GSoC21 Remoting page: Add a new mentor and link

- content/blog/2021/06/2021-06-04-digester-removal.adoc
Followup for the digester blog. I think listing also the plugins that were not served too will avoid people missing this...
> Also list plugins that was not served anymore already

- content/doc/book/pipeline/index.adoc
Fix DSL footnote (reference to existing footnote) on [Pipeline](https://www.jenkins.io/doc/book/pipeline/#why) page.
> Fix DSL footnote

- content/doc/book/installing/other.adoc
ZFS support in Jenkins was ripped out in jenkinsci/jenkins#5047, so any references to the old `libzfs`-related workarounds in the documentation are no longer necessary and can be removed.
> Updating documentation to reflect jenkinsci/jenkins#5047.

- content/css/jenkins.css
- content/templates/downloads.html.haml
Follow-up for https://github.com/jenkins-infra/update-center2/pull/469#issuecomment-860071693 (same style change as in UC repo, just a different breakpoint) + add `:before` element to artifacts to compensate for fixed header when linking to a specific version via location hash.
CC @daniel-beck
> Responsive layout for download template

- content/doc/book/installing/_docker-for-tutorials.adoc
- content/doc/book/installing/_docker.adoc
Feedback from a reader noted that step 4 in the Windows instructions for Docker was relying on the reader to page backwards in the document to find step 4 in the Linux/macOS instructions.  That's unclear to readers and makes the experience difficult.
Better to include the content directly in the text so that the user consistently scrolls through the instructions rather than needing to backtrack into a section for a platform that may not be interesting to them.
Same change has been made in the Docker tutorials.  I confirmed that the instructions work on my Windows 10 computer running the latest Docker Desktop for Windows.
> Include Docker instructions for Windows

- content/_layouts/post.html.haml
- content/_layouts/project.html.haml
- content/_partials/discuss.html.haml
- content/blog/2021/06/2021-06-10-jenkins-is-the-way-ebook-2.adoc
- content/events/contributor-summit/index.adoc
- content/projects/gsoc/2021/projects/remoting-monitoring.adoc
This change allows embedding Discourse discussions. This approach does not auto-create stories, but nstead embeds the existing threads which should be created by users. See the discussion with @halkeye in https://community.jenkins.io/t/category-for-blogs-books-discussions/111/6
The implementation uses standard styling at the moment
> Support for embedding Discourse topics in blogposts and project pages

- content/projects/gsoc/2021/projects/cloudevents-plugin.adoc
Make changes to the CloudEvents Project documentation on Jenkins.io
- Enter info on the meeting hours
- Zoom Link
- Meeting Docs
- Enter chat information (Slack)
- Add project-implementation details
- Add supplementary reference links
> CloudEvents Plugin Doc Update

- content/doc/book/managing/nodes.adoc
- content/doc/book/using/using-agents.adoc
@darinPope has been creating video segments on various Jenkins capabilities.  He's granted us permission to use his videos on the www.jenkins.io site.
- Add tutorial video on agent creation
- Include 'What is a Jenkins Agent?' video
Pages look like this:
> Add agent tutorial videos to agent docs

- content/_data/roadmap/roadmap.yml
- content/events/hacktoberfest.adoc
- content/sigs/advocacy-and-outreach/index.adoc
This change updates the terminology cleanup initiative.
> Reference Terminology Cleanup project in the Advocacy&Outreach SIG

- content/download/index.html.haml
Site build fails at the moment because these URLs are 404.
Origin branch, delete on merge.
> Work around 2021-06-30 Artifactory issues

- content/doc/book/managing/system-properties.adoc
Obsoleted in jenkinsci/jenkins#5320.
> Marking `hudson.util.Digester2.UNSAFE` as obsolete

- content/doc/book/managing/system-properties.adoc
Obsoleted in jenkinsci/jenkins#5526.
> Marking `hudson.ClassicPluginStrategy.noBytecodeTransformer` as obsolete

- content/doc/book/pipeline/index.adoc
I am not a native speaker, but I am pretty confident, that the `a` is wrong/not needed there :)
> Remove superflous `a`

- content/download/index.html.haml
This reverts the workaround from #4448.
**DO NOT MERGE** until 2.300 and 2.289.2 are in `releases` (or no longer the newest releases 😅 ).
> Revert "Work around 2021-06-30 Artifactory issues (#4448)"

- content/_data/roadmap/roadmap.yml
- content/sigs/platform/index.adoc
The hotspot JVM is available for JDK 11 on all the platforms currently of interest to the Jenkins Platform SIG.  It is available for:
* AMD64/Intel64
* Arm64
* PowerPC64
* s390x
The prototype OpenJ9 image generation has been removed from the Jenkins Docker images.  Work is now proceeding to create multi-architecture Docker images using `docker bake`.
See https://github.com/jenkinsci/docker/pull/1134 for details.
No further progress is expected on support of the OpenJ9 virtual machine in the Jenkins project.  Let's remove the entry from the roadmap.
> Remove OpenJ9 JVM support from roadmap

- Gemfile
- Gemfile.lock
- content/blog/2015/2015-09-19-office-hour-on-form-handling-in-jenkins.md
- content/blog/2016/2016-09-20-jom-plugin-development.adoc
- content/blog/2019/08/2019-08-23-introduce-react-plugin-template.adoc
- content/blog/2020/03/2020-03-17-ui-plugins.adoc
- content/doc/book/using/referencing-another-project-by-name.adoc
- content/doc/developer/architecture/web.adoc
- content/doc/developer/development-environment/taglibs.adoc
- content/doc/developer/handling-requests/index.adoc
- content/doc/developer/handling-requests/responses.adoc
- content/doc/developer/handling-requests/routing.adoc
- content/doc/developer/internationalization/i18n-jelly-views.adoc
- content/doc/developer/javadoc.html.haml
- content/doc/developer/plugin-development/pipeline-integration.adoc
- content/projects/gsoc/2020/project-ideas/automatic-spec-generator-for-jenkins-rest-api.adoc
- content/projects/gsoc/2021/project-ideas/automatic-spec-generator-for-jenkins-rest-api.adoc
Previous version used https://stapler.kohsuke.org/apidocs/ while the new version uses https://javadoc.jenkins.io/component/stapler/
See https://github.com/jenkins-infra/asciidoctor-jenkins-extensions/releases/tag/v0.9.0
Fixes https://github.com/jenkins-infra/jenkins.io/issues/4410
> Use extension 0.9.0 for Stapler javadoc URL creation

- content/doc/book/security/securing-jenkins.adoc
Original link for `Handling Environment Variables` resulted in a 404.
Link before went to: https://www.jenkins.io/doc/book/security/securing-jenkins/environment-variables
Link now goes to: https://www.jenkins.io/doc/book/security/environment-variables/
> Fixed link for "Handling Environment Variables"

- content/blog/2021/07/2021-07-27-git-credentials-binding-phase-1.adoc
4.8.0 released with incorrect symbol capitalization for GitUsernamePassword
4.8.1 corrected the mistake and shows it as gitUsernamePassword
> Use correct caps for example

- content/_data/changelogs/weekly.yml
Requested in https://github.com/jenkinsci/jenkins/pull/5607#issuecomment-889563263
Remoting has been included in previous changelog entries.  Should have
ignored the `skip-changelog` label that was applied to the pull request.
> Add remoting 4.10 to 2.302 changelog

- content/doc/book/managing/system-properties.adoc
Matches https://github.com/jenkinsci/jenkins/pull/5628
> [JENKINS-66177] JavaVersionRecommendationAdminMonitor.disable

- content/redirect/cli-command-requires-channel.adoc
- content/redirect/cli-http-connection-mode.adoc
- content/redirect/contribute.adoc
- content/redirect/crumb-cannot-be-used-for-script.md
- content/redirect/find-jenkins-logs.adoc
- content/redirect/log-levels.adoc
- content/redirect/log-recorders.adoc
- content/redirect/logging.adoc
- content/redirect/rekey.adoc
- content/redirect/serialization-of-anonymous-classes.adoc
- content/redirect/setting-system-properties.adoc
- content/redirect/troubleshooting/executor-starvation.adoc
- content/redirect/user-content-directory.adoc
Some redirects point to Wiki pages that have been moved to jennkins.io, some others use absolute URLs without www which also causes  extra redirect.
> Avoid double redirects

- content/security/advisories.html.haml
- content/security/advisories/rss.xml.haml
- content/security/for-administrators.adoc
- content/security/index.adoc
The Google-provided RSS feed for the jenkinsci-advisories Google Group (and probably all Google Groups per https://support.google.com/groups/thread/118690869/when-will-googlegroups-rss-feed-be-back-online?hl=en) no longer exists.
This PR adds an RSS feed to `/security/advisories/rss.xml` and links it from the the advisories overview as well as from documentation that previously linked to the Google Groups RSS feed.
The RSS code is largely copied from the corresponding feed code for the changelog, adapted to security advisory content (largely copied from the advisories overview page).
As feed readers tend to cache items, I decided against inlining entire advisories, instead limiting descriptions to affected components (which do not change after publication).
Entry publication times are at …
> Add RSS feed for security advisories

- scripts/ruby
Ruby 2.6 through docker on my mac m1 is currently seg faulting.
Can we add this or something similar to skip using it?
Saves me hacking around it locally
cc @zbynek
It would be good to update ruby to at least 2.7 if not 3.0 but I think awestruct needs some dependency updates. I tried 3.0 briefly but it didn't work
> Add ability to use ruby without docker

- content/doc/book/installing/linux.adoc
Jenkins 2.306 weekly uses the `daemonize` program from EPEL to simplify the rpm based installation and process administration code.
Add the epel-release repository so that the rpm can be installed.
@basil this is the proposed documentation update.  Does not correct the downloads page, but does correct the install instructions page.
See jenkinsci/packaging#207
> Include epel-release repo in CentOS instructions

- content/doc/book/managing/built-in-node-migration.adoc
- content/redirect/built-in-node-migration.adoc
Add redirect and docs page for the built-in node name and label migration, corresponds to https://github.com/jenkinsci/jenkins/pull/5425.
Deliberately not linked from the menu as this is basically "ephemeral" documentation -- it won't have much value in a year or two. The entry point is the admin monitor in Jenkins.
> Terminology cleanup: Docs for built-in node migration

- content/projects/gsoc/2021/projects/conventional-commits-plugin.adoc
This PR updates the project page of the "Conventional Commits Plugin for Jenkins" GSoC project.
Following changes have been made:
* Updated description of the project
* Add links to demo and blogs
* Add roadmap
PS: Not the 2nd blog :)
Signed-off-by: Aditya Srivastava <adityasrivastava301199@gmail.com>
> GSOC-21 update conventional commits project page

- content/blog/2021/08/2021-08-19-git-credentials-binding-work-report.adoc
Updating GSOC-2021 work report for Git Credentials Binding project
1. Included
- Project link update
- Last GSOC-21 commit update for SSH Binding
> Gsoc 21 work report update for Git Credentials Binding project

- content/_data/upgrades/2-303-1.adoc
The `daemonize` program is required by the Jenkins rpm package.  It is available from the `epel-release` repository.  The `epel-release` repository is enabled by default with Fedora but is not enabled by default with Red Hat Enterprise Linux or with CentOS.  
Enable the `epel-release` repository with the command:
```
```
> [JENKINS-66490] Note rpm dependency added in 2.303.1 installer

- content/_data/upgrades/2-303-1.adoc
* Add Debian upgrade note to upgrade guide
* Update multi-arch support list
> Add bullseye to 2.303.1 upgrade guide

- content/doc/book/system-administration/diagnosing-errors.adoc
- content/participate/report-issue.adoc
Previously a:
```
Result: [Plugin:workflow-job, Plugin:translation, Plugin:bootstrap4-api, Plugin:branch-api, Plugin:junit-attachments, Plugin:variant, Plugin:beer, Plugin:handlebars, Plugin:build-timeout, Plugin:forensics-api, Plugin:display-url-api, Plugin:pipeline-utility-steps, Plugin:script-security, Plugin:pipeline-stage-view, Plugin:basic-branch-build-strategies, Plugin:lockable-resources, Plugin:azure-vm-agents, Plugin:pipeline-github-lib, Plugin:blueocean-personalization, Plugin:matrix-auth, Plugin:jaxb, Plugin:git-forensics, Plugin:mercurial, Plugin:credentials-binding, Plugin:external-monitor-job, Plugin:pipeline-model-extensions, Plugin:jacoco, Plugin:warnings-ng, Plugin:data-tables-api, Plugin:cloud-stats, Plugin:jdk-tool, Plugin:azure-credentials, Plugin:blueocean-jwt, …
```
> Sort plugins and don't return the list of plugins

- content/_partials/discuss.html.haml
- content/blog/2021/09/2021-09-04-wiki-attacked.adoc
* Allow simple "True" mode for discourse embedding, for those that want comments but don't want to pre-create topics
* Enable (as example) comments on new wiki attacked page
> Add simple discourse support

- content/_partials/discuss.html.haml
@MarkEWaite Just realized it that windows.location.toString() will be the entire url, so any anchors or query string will make it a new url (maybe).
Just make it explicit that its only the url part (is there an awestruct way of getting the cannonical url? i couldn't get absolute_link(page.url) to output anything)
> Make sure we use just the url, no anchors or query string for comments

- content/security/index.adoc
Update the security advisories link to https://www.jenkins.io/security/advisories/rss.xml
> Update Security Advisory Link

- content/doc/book/installing/_kubernetes.adoc
I was struggling with following the documentation until I got my system into a state where I could figure out how to get the proper logs from the containers. I discovered permissions error that lead me to https://stackoverflow.com/questions/65072209/jenkins-on-kubernetes-permission-denied which pointed out two possible work arounds. I have updated the documentation to match the latest answer present at this time.
> Add a note about minikube permissions for persistent data.

- content/doc/book/managing/built-in-node-migration.adoc
This documents that Pipelines don't get the new `NODE_NAME` (yet).
Calling it "incompatible" may be a bit much, but it kinda makes sense?
See https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/168 for the PR aiming to change the behavior.
> Add notes about the behavior of Pipeline: Nodes and Processes

- content/doc/developer/forms/jelly-form-controls.adoc
The `ListBoxModel#add` method takes two parameters: `String displayName` and `String value`. The example was passing values in an incorrect order - `value, displayName` instead of `displayName, value`. This commit uses correct order.
> Pass values to ListBoxModel#add in correct order

- content/_data/changelogs/weekly.yml
Add a 2.310 entry to the weekly changelog that notes 2.310 was not delivered.
> Note that 2.310 release was not delivered

- content/doc/administration/requirements/upgrade-java-guidelines.adoc
* Upgrade Jenkins to the most recent version (no benefit saying that 2.164 is the first version to support Java 11 because that is over two years ago and is not a maintained release)
* Docker images are Java 11 by default
* Upgrade plugins because upgrades improve compatibility
* Hide the comment about workflow support plugin 3.0.  It was released 3 years ago and has 8 following releases that supersede it
I removed the wiki link because the wayback machine copy of the page showed that it contained no information that would be useful to a current user.
> Adapt Java upgrade instructions to recent changes

- content/doc/book/installing/_docker-for-tutorials.adoc
- content/doc/book/installing/_docker.adoc
Blue Ocean 1.25.0 was released 3 days ago with a fix for a downstream build link.  I've been running it successfully on my instance for the last several days without any issue.  Let's use the latest release so that tutorial users do not have so many warnings for plugin upgrades.
https://github.com/jenkinsci/blueocean-plugin/releases/tag/blueocean-parent-1.25.0 provides more details of the content of the release.
https://issues.jenkins.io/browse/JENKINS-60995 is the issue that was fixed by the release.
> Use blue ocean 1.25.0 instead of 1.24.7

- content/doc/developer/handling-requests/actions.adoc
- content/doc/developer/handling-requests/stapler-accessible-type.adoc
#3866 rewrote messages in log output provided as example, which makes no sense without a corresponding change to Jenkins. It's like changing UI label references without the UI changing, it just makes content more difficult to use.
#3113 rewrote URLs to Asciidoc syntax in blocks that aren't rendered in Asciidoc.
> Undo failed cleanups

- content/download/lts/index.adoc
note that the label can be applied to anything but only small well contained bug fixes are acceptable, along with a dependency bump should the library have a public CVE.
> clarify backporting criteria and eligibility.

- content/events/hacktoberfest.adoc
- content/projects/infrastructure/index.adoc
With the upcoming hacktoberfest, the Infrastructure team want to expose some "first good issues".
This PR:
- Fixes the links and language of the "Contribution" section of the Infrastucture's project page
- Adds the infrastructure as one of the projects for hacktoberfest
> fix [jenkins-infra] correct link and sentences for the first good issues

- content/index.html.haml
DevOps World completed September 30, 2021.  Let's use the Jumbotron space to highlight the Contributor Summit.
> Replace DevOps World with Contributor Summit

- content/events/contributor-summit/index.adoc
Include "Register Here" button to encourage readers to register for the events.  Include agenda text from the online meetup announcements.
See https://www.meetup.com/Jenkins-online-meetup/events/281083403/ to register for Part I.
See https://community.jenkins.io/t/hacktoberfest-2021-join-us/375 for discussions of Hacktoberfest in Jenkins.
See https://www.meetup.com/Jenkins-online-meetup/events/281089570/ to register for Part II.
See https://community.jenkins.io/t/jenkins-contributor-summit-oct-02-and-oct-09-2021-apac-emea/203 for discussions of the Contributor Summit.
> Update contributor summit for part I/part II

- content/events/hacktoberfest.adoc
Given the inclusiveness of the first entry it seemed to make sense to add this topic directly to its description. @MarkEWaite signed off on the use of the board and chat for this topic.
> <img width="848" alt="Screenshot" src="https://user-images.githubusercontent.com/1831569/135591767-2be748cb-6335-4352-92e5-947610a8da0b.png">
FYI @megathaum
> Add developer documentation topic to Website feature

- content/_data/events/2021-10-09-contributor-summit-part-2.adoc
https://www.meetup.com/Jenkins-online-meetup/events/281089570/ shows the same start time as contributor summit part 1.  Make them match in the event view as well.
> Update time for contributor summit part 2

- content/doc/book/using/remote-access-api.adoc
Reported in the [docs feedback sheet](https://docs.google.com/spreadsheets/d/1nA8xVOkyKmZ8oTYSLdwjborT0w-BpBNNZT0nxR9deZ8/edit#gid=1087292709) row 1191
> Fix broken link in remote-access-api page

- content/_partials/legacy/navbar.html.haml
- content/_partials/toptoolbar.html.haml
- content/participate/help.adoc
* Add Forum to Community dropdown menu
* Add Forum to legacy menu just in case it is used
* Add Forum to 'Help other users' page
Menu now looks like this:
> Add forum to community menu

- content/blog/2015/2015-02-09-jenkins-celebration-day-is-february-26.adoc
It seems like the old one had a bit of messy html which is probably why the auto conversion failed.
http://web.archive.org/web/20200813205301/https://www.jenkins.io/blog/2015/02/09/jenkins-celebration-day-is-february-26/
The github preview page looks good now
> Fix 100k page.

- content/doc/book/installing/_docker.adoc
Line break escapes changed from ^ to backtick (`) in the case of long commands, because PowerShell is able to interpret only that. Now these commands are really copy-paste compatibles.
> Docker for Windows installation commands updated

- content/doc/book/installing/_jenkins-command-parameters.adoc
- content/doc/book/system-administration/reverse-proxy-configuration-apache.adoc
Jenkins hasn't supported AJP since 2.0, so remove documentation leftovers.
The Apache documentation could actually be useful, if someone goes all the way to run Jenkins inside Tomcat. If any reviewer thinks this is still valuable, I would be willing to rework the documentation for that usecase instead of outright removing it...
> Remove AJP documentation

- content/doc/book/installing/_docker-for-tutorials.adoc
- content/doc/book/installing/_docker.adoc
There were some improvements made to https://docs.docker.com/engine/install/debian/ since those instructions were uses to write these docker files:
- Stops using apt-key
- Replaces fixed amd64 with a call to dpkg
And it seems some improvements are still ongoing: https://github.com/docker/docker.github.io/pull/12331
Additionally:
- this avoids using gpg, since apt knows how to use ASCII keyrings since apt 1.4 (2016)
- installs less packages (apt-transport-https, gnupg2 and software-properties-common are obsolete now and curl is already installed by the parent container)
This fixes #4560
> Update Docker installation in Dockerfiles

- content/doc/book/managing/nodes.adoc
This adds a link to the "Distributed Builds Architecture" documentation and gives a brief definition of controller, node, agent, and executor as background to Darin's excellent video about creating and attaching an agent.  Currently, one opens the "Managing Nodes" page and is presented with a video about "Creating Agents", which is a bit confusing for the uninitiated.
I originally developed this for the "Distributed Builds" page in the Security section but it belongs on the "Managing Nodes" page.  After this PR is merged, I will pare the description in the Security chapter way down and reference this list.
> Define controller, node, agent, executor

- content/redirect/remoting-security-workaround.adoc
Link to GitHub repo now that it is live.
Once update site is live, link there instead.
> Update redirect URL

- content/100k.adoc
- content/_layouts/refresh.html.haml
- content/account.adoc
- content/blog/2015/2015-11-04-jenkins-and-docker.adoc
- content/blog/2016/2016-08-17-jenkins-world-speaker-blog-aquient.adoc
- content/blog/index.adoc
- content/blog/take-2015-jenkins-survey.adoc
- content/conduct.adoc
- content/doc/book/pipeline/overview.adoc
- content/doc/book/securing-jenkins.html.haml
- content/doc/pipeline/index.adoc
- content/friend.adoc
- content/welcome.adoc
```
ag 'layout: refresh' | awk -F: '{print $1}' | xargs perl -pi -e 's/refresh_to_post_id:/redirect_url:/g; s/layout: refresh/layout: redirect/g'
```
Then went and cleaned up a few :layout to layout:
No need for two templates that do the same thing.
> Replace all the refresh layouts with redirect

- content/_config/sitemap.yml
- content/_ext/pipeline.rb
- content/_ext/sitemap.rb
```
ag 'layout:.*redirect' content | awk -F: '{print $1}' | xargs sed -i '/^layout:.*redirect/i sitemap_exclude: true'
```
Confirmed undesired behavior via
http://www.thesempost.com/google-avoid-including-redirected-urls-sitemaps/
(Also I just don't want them there)
based on #4698
> Make sure redirects are not included in sitemap

- content/doc/book/installing/linux.adoc
Switch to explicitly using signed-by in sources.list.
Let's try to get the discussion going: This seems to represent the current best practice, see for example
- https://unix.stackexchange.com/a/463140/498490
- https://wiki.debian.org/DebianRepository/UseThirdParty
I'm personally not convinced that specifying "signed-by" in the sources.list file adds much in terms of security over just adding the key in trusted.gpg.d (see also the warning block at the top of the Debian wiki page)
(This should fix the warning noted in #4237)
> Replace deprecated apt-key usage

- content/doc/book/installing/linux.adoc
Sorry that I missed correcting the repository name in my update proposal.  Thanks for the contribution @TobiX!
> Use correct repo for Debian weekly instructions

- content/sigs/ux/index.adoc
Remove several sections and update the current list of topics:
- Removed the obsolete lead section, we have no lead anymore
- Removed the participants section, everybody is welcome to contribute and it makes no sense to update this web page every time the group sets changes
- Rephrased several sections since the information was outdated.
- Removed some projects since nobody is actually working on them
> Update UX SIG starting page

- content/_data/upgrades/2-303-3.adoc
https://github.com/jenkinsci/cobertura-plugin/pull/130#discussion_r743133431 identified that this integration has never worked, so it could not have been affected by this change in practice (even though the code looked like it was).
> Cobertura plugin was never actually affected

- content/_data/changelogs/weekly.yml
[JENKINS-36779](https://issues.jenkins.io/browse/JENKINS-36779) is the issue that tracked the Guava upgrade.  Record it in the changelog for reference
> Reference JENKINS-36779 in guava update changelog entry

- content/events/fosdem/archive/2016.adoc
- content/events/fosdem/archive/2017.adoc
- content/events/fosdem/archive/2018.adoc
- content/events/fosdem/archive/2019.adoc
- content/project/governance-meeting/archives/2011.adoc
- content/project/governance-meeting/archives/2012.adoc
- content/project/governance-meeting/archives/2013.adoc
- content/project/governance-meeting/archives/2014.adoc
- content/project/governance-meeting/archives/2015.adoc
- content/project/governance-meeting/archives/2016.adoc
- content/project/governance-meeting/archives/2017.adoc
- content/project/governance-meeting/archives/2018.adoc
- content/project/governance-meeting/archives/2019.adoc
* Fix dev list URL reference
* Update link to rtyler bio
* Update link to kohsuke bio
* Update link to oleg_nenashev bio
* Update link to daniel-beck bio
* Use blog author links instead of broken wiki author links
* Use Liam Newman author page
* Update more blog authors
* Remove unhelpful 'Unknwon User' text
* Remove some confluence remnants
* Remove the easy cases of '[ (username)]'
* Remove user references to wiki
> Fix some broken wiki refs

- content/participate/index.html.haml
When I click the "DONATE" button on the [community overview page](https://www.jenkins.io/projects/), it redirects to https://wiki.jenkins-ci.org/display/JENKINS/Donation even though we haave a much better donate page at https://www.jenkins.io/donate/
> Fix broken link to donate page

- content/_data/changelogs/weekly.yml
- Move developer entry to end of changelog
- Split fix and rfe to separate entries
> Revise 2.322 changelog

- content/redirect/permitted-agent-to-controller-file-access.adoc
When https://github.com/jenkinsci/jenkins/pull/5890 emits a warning, users are directed here.
On hold: To be merged once the core PR is merged.
> Add redirect URL for jenkinsci/jenkins#5890

- content/doc/book/managing/script-console.adoc
A couple of additional notes:
* I originally authored the majority of the content from the original confluence page.  Happy to review content and own this page for jenkins.io going forward.
* Most of the changes in this diff are for setting the line width to 80 characters.
* Contributing new sections for reading and writing files to the Jenkins controller and agent.  Similar to when I contributed executing scripts through the agent channel, I found it non-trivial for reading and writing files.  A use case for this is a job executing a system groovy script step in a freestyle job but you wish to access a file in the workspace on an agent.
> Add reading and writing files to script console doc

- content/css/jenkins.css
```
hervelemeur: I don't understand why the links in the docker plugin main page aren't working (like the one pointing to the plugin doc): https://plugins.jenkins.io/docker-workflow/
timja: the h2 has a position relative style on it which expands over the text copy preventing you interacting with the text
```
this lead me to finding the h1[id]:before statements that were doing
massive padding
I can't find any pages that are not rendered correctly: https://jenkins-io-halkeye.netlify.app/blog/2021/12/08/containers-as-build-agents/#using-containers-as-build-agents-for-greater-pipeline-flexibility
cc @lemeurherve @timja @MarkEWaite
> Remove css from 2014 that makes the box for headers with IDs just HUGE

- content/css/jenkins.css
Previously removed because headers were made huge, so some other css was
conflicting. The plugins site's hover link only worked after the header,
and was making some links hard to click, and lots of other tiny
things.
The fix in #4758 fixed the issue, but direct linking to anchors will
now be under the header. This css will still fix the under the header
issue in modern browsers, without making the h1 like 200px tall.
Test: http://odin:5000/blog/2021/12/08/containers-as-build-agents/#thanks-to-our-sponsor
> Modern fix for #4758

- STYLEGUIDE.adoc
- content/doc/book/installing/_docker-for-tutorials.adoc
- content/doc/book/installing/_docker.adoc
- content/doc/book/pipeline/docker.adoc
- content/doc/pipeline/tour/agents.adoc
- content/doc/pipeline/tour/hello-world.adoc
Use the most recent version of Blue Ocean in the tutorial.
Use specific versions of the tools to show the good practice of exact definition of tool version.  Reduce download size by using the Alpine Linux version of tools when available.
Apache Maven is specifically configured to use JDK 11 because that is our primary supported platform.  It is configured to use Debian slim rather than Alpine because the Maven docker images do not include an Alpine image.
* Use Blue Ocean 1.25.2
* Use Apache Maven 3.8.4, not 3.3.3
* Use Ruby 3.0.3 alpine
* Use NodeJS 16.13.1 alpine
* Use Python 3.10.1 alpine
* Use PHP 8.1.0 alpine
* Use golang 1.17.5 alpine
@lemeurherve and @smerle33 this is a small but useful step towards improving the guided tour.  It doesn't fix the clarity and completeness issues but …
> Update tool versions

- content/doc/book/installing/_kubernetes.adoc
- content/doc/book/installing/_setup-wizard.adoc
* modified /doc/book/installing/kubernetes/#install-jenkins-with-jenkins-operator - deleted instructions on installing Jenkins with Jenkins Operator and instead added link those instructions in Jenkins Operator project's docs - to avoid having to document installation process on 2 separate repos and confusing users with outdated documentation
* modified doc/book/installing/kubernetes/#setup-wizard to state that it doesn't apply to installation with Jenkins Operator
> Documentation on installing Jenkins with Jenkins Operator

- content/_layouts/frame.html.haml
- content/_partials/discuss.html.haml
Noticed on forums that year/month/day//post and year/month/day/post were
both created
This adds canonical link (helps with seo, and probably should always be
jenkins/path so if we start deploying forks, it doesnt break hurt us
in search engines. But leave it for now)
Tell disourse to use the canonical url not just the current url
> Make single discourse link

- content/blog/2021/12/2021-12-10-log4j2-rce-CVE-2021-44228.adoc
Currently the Jira query just list a subset of the plugins, the ones that manage their task in Jira. But half of the affected components are using GitHub.
Using https://issues.jenkins.io/browse/JENKINS-67353 instead of https://issues.jenkins.io/issues/?jql=labels%20%3D%20CVE-2021-44228
> Update Log4j blog post to also cover the GH issues

- content/doc/book/pipeline/development.adoc
I recently created https://github.com/ckipp01/nvim-jenkinsfile-linter in order to get the same support for linting Jenkinsfiles like the other editors listed here. This pr just adds a link to it letting people know there is Neovim support.
> Add reference to nvim-jenkinsfile-linter plugin

- content/doc/book/managing/system-properties.adoc
Looks like I missed this one when setting up the initial list.
> Document agent-to-controller security bypass

- content/doc/developer/publishing/requesting-hosting.adoc
- content/project/teams/hosting.adoc
- content/projects/infrastructure/ircbot.adoc
Requires https://github.com/jenkins-infra/repository-permissions-updater/pull/2287
and enabling issues on https://github.com/jenkins-infra/repository-permissions-updater/
> Switch hosting project to GitHub issues

- content/doc/administration/requirements/java.adoc
Just a minor documentation improvement, simplifying the description of the required JREs.
Somewhat related to #3474. Mentioning it here in case someone started working on that one.
> Simplify JRE requirements description for better readability.

- content/files/rate.js
https://issues.jenkins.io/browse/INFRA-3170
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/push
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#see_also
both push and sort have been in since ie 5.5 (didn't know it was a version), chrome 1 and firefox 1 so I think its safe to use.
I haven't tested it locally as I've been busy with helping fix infra.ci, but should be testable on preview
> INFRA-3170 - Sort issues by frequency

- Jenkinsfile_k8s
Right now when one PR deploys, the previous deploy gets marked as inactive since they are the same env. So make env separate for each PR.
> Have one github preview environment per PR

- .gitpod.yml
Gitpod simplifies the development and preview environment setup by providing a standardised cloud based  setup.
> add required configuration to enable gitpod

- Jenkinsfile_k8s
production replaces previous url, everything else is transient. Not that we're deploying via these scripts (yet).
Sorry @MarkEWaite for flip flopping
> Go back to single preview env

- docker/default.conf
Adding "_" to catch all requests invalid hosts
See http://nginx.org/en/docs/http/server_names.html (search for "strange" in this page)
> fix(docker): catch invalid host names in the default vhost

- content/doc/book/managing/_chapter.yml
- content/doc/book/managing/about-jenkins.adoc
- content/doc/book/managing/index.adoc
- content/doc/book/managing/script-approval.adoc
- content/doc/book/managing/system-info.adoc
- content/doc/book/managing/users.adoc
The original concept was to list the items from the "Manage Jenkins" screen in the index.adoc file, in order, with links to the sections that discuss each.  We may need to refine that concept.  For now, I started that and linked to relevant files, wherever they are.  I did not move any files.
At issue is what belongs in "Managing Jenkins" versus "System Administration".  We posited having "Manage Jenkins" be for the "basic" information that is on the "Manage Jenkins" screen and then have "System Administration" go into more advanced topics but a couple of the items on "Manage Jenkins" are kind of advanced.
If anyone has any opinions, I would love to hear them.  Meanwhile, I think that this piece is better than the stub file we did have.
I added a couple files for topics that were …
> Add overview of pages in Managing Jenkins chapter

- content/participate/report-issue.adoc
Since all INFRA issues have been migrated from Jira to Github, mention the new helpdesk url to open an issue related to infrastructure. (See https://github.com/jenkins-infra/helpdesk/issues/9)
Part of https://github.com/jenkins-infra/helpdesk/issues/2730
> fix: mention of jenkins-infra/helpdesk for Infrastructure project issues

- content/doc/book/security/controller-isolation.adoc
- content/doc/book/security/controller-isolation/agent-to-controller.adoc
- content/doc/book/security/controller-isolation/jep-235.adoc
- content/redirect/AdminWhitelistRule.adoc
Documentation for jenkinsci/jenkins#5885 and https://github.com/jenkinsci/jep/tree/master/jep/235
The new page's URL is a bit weird, but making it related to JEP-235 seems preferable to make it related to the weekly version number -- and I couldn't think of a better URL.
> Add documentation for JEP-235

- content/doc/developer/handling-requests/_chapter.yml
- content/doc/developer/handling-requests/json.adoc
Starting something about HTTP/Json, feel free to tell me if this doc exist somewhere else.
Done in regard of https://github.com/jenkinsci/jenkins-test-harness/pull/378, so the PR on jenkins-test-harness must but merged first for the doc to be accurate.
Also I haven't time to run it locally to verify the format, I will do it (my Internet connection is very bad).
> Adding dev doc for managing HTTP/Json API

- content/doc/book/installing/_docker-for-tutorials.adoc
- content/doc/book/installing/_docker.adoc
- content/doc/tutorials/build-a-node-js-and-react-app-with-npm.adoc
Fix #4825 - React app does not open based on Windows tutorial steps.
- Use Debian bullseye, not buster in React tutorial - use Debian stable, not oldstable
- Use docker-workflow:1.27 in tutorial, not 1.26 - use latest release
- Publish port 3000 on Windows and Linux tutorial
- Fix #4825 
- Reduce differences between tutorial and installing
- Use bat line continuation, not powershell - more widely used
- Use Jenkins version in sample docker image tag - healthier pattern to use a tag related to image content
- Remove CI environment variable - included in Jenkins LTS since 2.289.1
> Update NodeJS tutorial

- .gitpod.yml
The Gitpod configuration is adapted to automatically install the Streetside Software code spell checker extension.
> Add spell checker to Gitpod configuration

- content/_data/changelogs/weekly.yml
Also update the Groovy upgrade changelog to include links to all the relevant Groovy release changelogs.
> Remove markdown from weekly changelog

- content/projects/gsoc/2022/project-ideas/jenkinsfile-runner-action-for-github-actions.adoc
@alyssat and @MarkEWaite 
**To follow up on our previous communication**: This is to add the Jenkinsfile Runner Action for GitHub Actions project originally proposed and will be co-led by @oleg-nenashev. I have tried my best to come up with a draft with as much essential detail as possible. Hopefully both of you and Oleg will get the chance to take a look and provide any comments or feedback before this can be approved and merged to the repo after some modifications. I expect since I am new to / not known on Jenkins.io so my tag as a co-mentor may not get properly rendered.
> Add GSoC 2022 project idea for Jenkinsfile Runner Action

- content/projects/gsoc/2022/project-ideas/automatic-spec-generator-for-jenkins-rest-api.adoc
- content/projects/gsoc/2022/project-ideas/jenkinsfile-runner-action-for-github-actions.adoc
Have been checking the latest batch of GSoC 2022 docs for typos. Found two and fixed both. These are minor but thought it be better handled earlier for better presentation and consistency.
> Fix typos in GSoC 2022 docs

- content/doc/developer/plugin-governance/adopt-a-plugin.adoc
The existing documentation became a little dated and did not reflect the current practice. This is a proposal for a documentation update (unless the current adoption practice should be ironed out).
> refresh the documentation of the plugin adoption process

- content/doc/developer/publishing/releasing-cd.adoc
The INFRA issue tracker has moved to GitHub and is no longer in use on Jira.
> Update CD troubleshooting INFRA issue link

- content/doc/administration/requirements/web-browsers.adoc
see https://groups.google.com/g/jenkinsci-dev/c/piANoeohdik
Will leave in draft for a week or two, but suggested time for merge is after new LTS baseline (week of 24th January).
> Drop IE 11 support in browser policy, promote edge to L1

- content/doc/developer/views/_chapter.yml
- content/doc/developer/views/icon-path-to-icon-class-migration.adoc
This guide complements https://github.com/jenkinsci/jenkins/pull/5778 and should help plugin developers to update their plugins, if they are working with icons, according to the latest changes in core.
> Propose developer guide for icon removal from core

- content/_data/changelogs/weekly.yml
Docs office hours noted that the developer section needs to move to the end and that the reference links need to be added as references rather than inlined as markdown links.
> Update 2.333 changelog

- content/sigs/gsoc/index.adoc
Remove references to a weekly specific meeting and point to the "Advocacy & Outreach" meeting.
> update GSoC SIG page

- content/sigs/advocacy-and-outreach/index.adoc
Removed people from the list not attending meetings or contributing anymore while reviewing the page for accuracy.
> update Advocacy SIG members

- content/_data/roadmap/roadmap.yml
Over 100 plugins are using the JEP-229 continuous delivery technique.  I think that is enough to call it a "current" project on the roadmap.
> JEP-221 is now current as JEP-229

- content/sigs/docs/index.adoc
Last meeting of Docs office hours (US West and Asia) agreed that it would be OK to move the meeting to the same time, but 3 days later in the week.  That alllows the meeting to immediately precede Google Summer of Code office hours (Asia)
> Move Docs office hours to Friday

- content/sigs/docs/index.adoc
Link to the current office hours notes for both the office hours and the SIG meetings, since they are the same meeting.
Add changelog and upgrade guide reviews as common topics.
> Update Docs office hours participants and details

- content/_data/changelogs/weekly.yml
Interactive editing did not apply the same formatting rules as the automated formatter applies.
> Fix changelog 2.333 formatting

- content/doc/book/system-administration/viewing-logs.adoc
It's not that easy to fill the logging property file when you are not used to this logging system (but more used to log4J or Slf4J or logback).
So I propose to give a full working example (tested locally)
> [doc] add a full content of logging.properties

- content/doc/developer/plugin-governance/adopt-a-plugin.adoc
For plugin adoption, it is required to be member of the jenkinsci
Github org. This requirement is clarified in this contribution.
> add note about jenkinsci membership in plugin adoption explanation

- content/projects/gsoc/2022/application.adoc
- content/projects/gsoc/index.adoc
Jenkins GSoC 2022 Application form
Modified pages can be previewed at:
- (main GSoC page): https://deploy-preview-4913--jenkins-io-site-pr.netlify.app/projects/gsoc/
- (application): https://deploy-preview-4913--jenkins-io-site-pr.netlify.app/projects/gsoc/2022/application/
> GSoC2022 application document

- content/doc/book/installing/linux.adoc
> Direct `systemd` users to appropriate log location

- content/project/team-leads.adoc
Clarification of responsabilities between Security officer and Infra officer concerning the security of the infrastructure. As it could generate confusion as it's related to both security and infra, we agreed that it's better that it belongs to the Infra officer. Otherwise, the security officer would need to be aware of any changes in the infra, which is counter productive and overlapping with the infra officer role.
Discussed with @dduportal before, but still expecting his review/approval :-)
(great to have the board review being automated, nice!)
> Clarification of responsabilities

- content/doc/book/installing/linux.adoc
The fontconfig package is already a dependency of the operating system Java installer.  It is only needed when using a JDK that is not provided as an operating system packages (like Eclipse Adoptium).
LTS 2.319.3 requires the `daemonize` package on Red Hat and its derivatives, but is provided by EPEL.  EPEL instructions are different depending on the operating system version.  Stop trying to describe EPEL installation, point the reader to the EPEL installation instructions.
> Adapt Linux install docs to current status

- content/projects/gsoc/2022/project-ideas/jenkinsfile-runner-action-for-github-actions.adoc
- content/projects/gsoc/2022/project-ideas/screenshot-automation.adoc
As discussed during the Jenkins GSoC Office Hour on February 24th, 2022 at 2PM UTC, it was brought to our attention that a Jenkins Docs Screenshot Automation project idea has been discussed previously in the Jenkins Docs Office Hour on February 11th, 2022. We intend to formalise the discussion into a proper project idea for GSoC 2022, hence the follow-up with this write-up. No mentor has committed to this project yet thus detail has been intentionally left out for now. At least one GSoC contributor has expressed interest in pursuing this idea as of the time of this PR's submission.
> Add GSoC 2022 Screenshot Automation project idea

- content/projects/gsoc/2022/project-ideas/JCasC-drift-detector.adoc
- content/projects/gsoc/2022/project-ideas/automating-plugin-buildmetadata-updates.adoc
They have a description, mentors identified, and general concepts.
They were described in the Jenkins Online Meetup as well.
> Promote two projects ideas to draft

- content/blog/2019/12/2019-12-16-board-election-results.adoc
- content/blog/2020/12/2020-12-03-election-results.adoc
- content/project/board.html.haml
In this current state, someone clicking on the link will create an email to "//jenkinsci-board@googlegroups.com" instead of the intended "jenkinsci-board@googlegroups.com"
> Remove incorrect // in mailto links

- content/_layouts/developerguide.html.haml
- content/css/jenkins.css
- content/doc/developer/views/symbols.adoc
Accidentally broken due to a global class addition in #4900.
This PR pulls out that CSS and moves it to the `developersguide.html.haml` file with a less generic name.
> Fix updates versions list appearance

- content/doc/book/security/controller-isolation/jep-235.adoc
https://github.com/jenkinsci/configuration-as-code-plugin/pull/90 created a custom configurator so neither the current stack trace nor the current help page gives you any clue as to what you actually need to it. @jetersen @daniel-beck
> Note concrete change for JCasC

- content/doc/developer/publishing/releasing-cd.adoc
I was surprised to see that the config that needs changing is part of the archetype.
> Note when people may have gotten a bad release-drafter config

- content/doc/book/installing/linux.adoc
- content/doc/tutorials/tutorial-for-installing-jenkins-on-AWS.adoc
Describe LTS installation with `systemd` instead of System V `init`.
* Fix broken links in AWS install doc
* Debian LTS installer now uses systemd
* Remove reference to daemonize program
> Use systemd for LTS

- content/projects/gsoc/index.adoc
* link to the GSoC 2022 JOM video and slides
* link to the Google official page for Jenkins
* Setting the project list in bold
preview available at https://deploy-preview-4980--jenkins-io-site-pr.netlify.app/projects/gsoc/
> Update GSoC links

- content/_data/indexpage/carousel.yml
Image URL taken from the opengraph image used on the CDF site at https://events.linuxfoundation.org/cdcon/
> Use cdCon 2022 image, not cdCon 2021

- content/sigs/platform/index.adoc
IBM Java support has been dropped due to lack of investment from anyone in the project.
OpenIndiana packaging has not been an active discussion topic in the Platform SIG since the SIG was formed.
> Correct platform SIG examples

- CONTRIBUTING.adoc
1. Things Done
- Removed ` /images/ ` prefix from contributing guidelines 
See the Changes Requested here #4991 by @MarkEWaite
> Don't need the /images/ prefix

- content/doc/developer/architecture/_chapter.yml
- content/doc/developer/architecture/security.adoc
Keeps the green, removes the red (which was just empty):
> Remove duplicate security entry from dev docs

- content/blog/2022/03/2022-03-22-jenkins-contributor-awards.adoc
The previous ones were pointing to the 2021 edition issues
> fix(blogpost): correct links for cdf Jenkins awards 2022

- content/_data/changelogs/weekly.yml
The packaging fix for MSI was not included in the 2.338 changelog.
> Add MSI parameters packaging fix to 2.338 changelog

- content/_data/changelogs/lts.yml
- content/_data/changelogs/weekly.yml
- content/_data/upgrades/2-332-1.adoc
Automated changelog generator missed the `remove` label in previous releases.  Include them.
See https://github.com/jenkins-infra/jenkins.io/pull/4960#issuecomment-1070519721 for more details.
- Include core PR #6111 in changelog and upgrade guide
- Add 2.333 changelog entry for JRuby removal
- Add JNR removal to 2.338 changelog
> Include `remove` label in changelogs

- content/doc/developer/persistence/_chapter.yml
- content/doc/developer/persistence/backward-compatibility.adoc
- content/doc/developer/persistence/custom-converter.adoc
- content/doc/developer/persistence/incompatible-releases.adoc
- content/doc/developer/persistence/index.adoc
One of the more tricky parts of Jenkins development, and a consistent source of confusion for newcomers, is object persistence. The XML-based object persistence framework used in Jenkins is dated, and many aspects of its implementation are not obvious to beginners. This particularly includes backward compatibility, which is a core value of the Jenkins project.
Most of the existing content was written by Kohsuke and lives on these outdated wiki pages:
- https://wiki.jenkins.io/JENKINS/XStream+Tips
- https://wiki.jenkins.io/JENKINS/Hint-on-retaining-backward-compatibility
- https://wiki.jenkins.io/JENKINS/Marking-a-new-plugin-version-as-incompatible-with-older-versions
Since I had to refer to this content recently, I decided to migrate it to the official developer documentation on …
> Migrate object persistence documentation from old wiki

- content/_data/upgrades/2-332-1.adoc
Improves the 2.332.1 LTS upgrade guide to cover complaints from users about stuff I broke.
See [JENKINS-67602](https://issues.jenkins.io/browse/JENKINS-67602) for context.
> Improve 2.332.1 LTS upgrade guide

- content/doc/book/installing/_jenkins-command-parameters.adoc
https://issues.jenkins.io/browse/JENKINS-68107
> Document key store config when enabling HTTP/2

- content/doc/book/managing/system-properties.adoc
While working on [JENKINS-68080](https://issues.jenkins.io/browse/JENKINS-68080) I noticed that most of the tunables for the [Pipeline: Nodes and Processes](https://plugins.jenkins.io/workflow-durable-task-step/) plugin were undocumented. So I decided to fix that.
This plugin seems to have nonexistent plugin documentation, so for now I am including this documentation on the main [Jenkins Features Controlled with System Properties](https://www.jenkins.io/doc/book/managing/system-properties/) page. Perhaps once this plugin gets its own documentation these could be moved to a different page, but it seemed awkward to create brand new plugin documentation with nothing other than tunable information.
CC'ing @jglick as the author of many of these tunables to make sure I described them accurately …
> Document Pipeline: Nodes and Processes tunables

- content/doc/book/pipeline/syntax.adoc
Bringing this closer to https://github.com/jenkinsci/kubernetes-plugin/blob/85e0d7e61db337abfbf46eb42af205ae159c65ab/examples/kaniko-declarative.groovy#L16-L43.
> Fixups to `agent kubernetes` example

- content/blog/2022/03/2022-03-29-jenkins-contributor-awards.adoc
The Jenkins Awards that will be presented at cdCon 2022 in June are accepting nominations until April 11, 2022.  Voting will start April 14, 2022.
> Jenkins Award nominations extended to April 11, 2022

- content/doc/developer/internationalization/i18n-jelly-views.adoc
Asciidoc does not know about Jelly syntax highlighting, exchanging it with xml does render the snippet properly.
> Exchange jelly with xml syntax highlighting

- content/doc/developer/internationalization/i18n-groovy-views.adoc
In Groovy, you can work with the same key-like values you use in Jelly or Java for localization.
Aligning the Groovy documentation helps hardening existing standards.
> Align Groovy i18n documentation with Jelly

- Makefile
- content/_layouts/frame.html.haml
- package-lock.json
- package.json
plugins.jenkins.io (and stories next rebuild) are getting javascript +cors issues loading the ionicons.
Options:
1) Setup cors headers on jenkins.io
2) Load ionicons from somewhere with cdn
I chose CDN as it means it can cache between sites, and less work for us (don't have to configure and maintain cors).
> Move ionicons to cdn

- content/_data/adopters/Anchore.adoc
- content/_data/adopters/Avoris-Travel.adoc
- content/_data/adopters/CERN.adoc
- content/_data/adopters/JDcom.adoc
- content/_data/adopters/KP-Labs.adoc
- content/_data/adopters/Preply.adoc
- content/_data/adopters/Topdanmark.adoc
- content/_data/adopters/Tymit.adoc
- content/_data/adopters/Wright.adoc
- content/_data/indexpage/carousel.yml
- content/_data/logo/jenkins-is-the-way.yml
- content/project/adopters/index.html.haml
Link to https://stories.jenkins.io where the story is available.
Fix links to https://jenkinsistheway.io when story is not yet available on https://stories.jenkins.io
Remove one adopter because the story can't be found in either location
- Move Jumbotron from jenkinsistheway.io to stories.jenkins.io
- Replace non-existent Anchore story link with their blog post
- Replace Avoris Travel link with working link
- Use stories.jenkins.io for CERN story
- Use stories.jenkins.io for jd.com destination URL
- Use stories.jenkins.io for the Preply story
- Use stories.jenkins.io for Topdanmark story
- Use stories.jenkins.io for the Tymit story
- Correct the URL to KP Labs story
- Remove Wright Medical adopter page
- Update root adopter page
Would like reviews from either @alyssat or @halkeye …
> Update Jenkins is the Way links

- content/_data/changelogs/weekly.yml
- Move major bug fixes to top of changelog
- Remove PR-6101 from 2.343 changelog, was already included in 2.341
> Reorder changelog entries, remove spurious entry

- content/doc/book/pipeline/jenkinsfile.adoc
There are better ways, including what I recently documented in https://github.com/jenkinsci/oidc-provider-plugin/pull/10.
Noticed this because https://github.com/dagger/dagger/pull/2102 copies the questionable advice.
> Noting that storing AWS credentials is sketchy

- content/doc/developer/views/icon-path-to-icon-class-migration.adoc
The examples are now aligned to prevent confusion.
Additionally, I added a table of all path-sizes with their corresponding icon size provided by the API.
> Align icon path -> icon class transition examples

- content/participate/report-issue.adoc
Add a link from the ”Issue Reporting” page to the <https://community.jenkins.io/> forum, as another way to post support requests that don’t belong in Jira.
I considered linking directly to the [Ask a question](https://community.jenkins.io/c/using-jenkins/support/8) category, but I’m not sure how stable that URI will be.
> Link from ”Issue Reporting” to forum

- content/doc/book/pipeline/jenkinsfile.adoc
Fixes https://github.com/jenkins-infra/jenkins.io/issues/5072 by using
the same variable in the good example as was used in the bad example.
Thanks @AlexandreFenyo for the bug report
> Fix Jenkinsfile Windows example with '%' character

- content/_data/changelogs/weekly.yml
Saying "Spring Framework changelog" and then linking to the jackson2
api changelog is confusing and not helpful.
> Use spring framework changelog link

- content/_data/changelogs/weekly.yml
Upgrading from 5.6.2 (Feb 2022) to 5.6.2 (Apr 2022) does not make sense.
Upgrade is from 5.6.2 to 5.6.3
> Use correct destination version in changelog

- content/_data/changelogs/weekly.yml
Pull request was incorrectly flagged as `skip-changelog`.
@basil does this phrasing work for you or would you prefer the original phrasing from the pull request?
> Add JENKINS-67237 to 2.346 changelog

- content/_data/upgrades/2-332-1.adoc
- content/_data/upgrades/2-332-3.adoc
A number of users have expressed confusion about this change on various GitHub pull requests and Jira tickets, so I think an update to the documentation is warranted.
> Add log message change to upgrade guide

- content/_data/changelogs/weekly.yml
https://github.com/jenkins-infra/jenkins.io/pull/5108#discussion_r870231019~
notes that the example tag is not displayed in the changelog HTML page
> Make example jelly tag visible in changelog

- CONTRIBUTING.adoc
Adding open in Gitpod button to Contributing doc to make it easier for contributors to work on Gitpod
> Add Open in Gitpod button

- content/projects/infrastructure/index.adoc
Add[ the rating metric service](https://github.com/jenkins-infra/rating) to the list of services self-hosted on Kubernetes in [the Infrastructure project page](https://www.jenkins.io/projects/infrastructure/#self-hosted-services-in-kubernetes).
Part of https://github.com/jenkins-infra/helpdesk/issues/1627
> chore(rating): add rating within the kubernetes self hosted services

- content/doc/book/managing/system-properties.adoc
Since it is [proposed to be included](https://github.com/jenkinsci/jenkins/pull/4579) in the Jenkins 2.346.1 upgrade guide as part of [JENKINS-50211](https://issues.jenkins.io/browse/JENKINS-50211), I think that it should be included in the list of system properties.
Propoerty first introduced in Jenkins 2.343
https://www.jenkins.io/changelog/#v2.343
> Document allowUnsupportedRemotingVersions escape hatch

- content/doc/developer/publishing/releasing-cd.adoc
Still struggling to get people to read instructions. https://github.com/jenkinsci/lightstep-incident-response-plugin/pull/1#issuecomment-1132113366
> Emphasizing that `.mvn/` must already exist for a plugin to be considered incrementalified

- content/_partials/toptoolbar.html.haml
- content/css/jenkins.css
Currently, the navbar in the mobile is not scrollable. As a result of this, if we expand any section (for example `Community`), the navbar clips after the boundaries, and the user can not select the options that are present below the line. 
Also, the dropdowns of the navbars do not have scrolling and exceed the screen's height in some cases (`Community` dropdown). This pull request addresses both these issues.
Before:
After:
Before: 
After:  (independent scrolling)
I have tested both the changes thoroughly in both desktop and mobile views.
> fix: scroll overflow of navbar and dropdown

- content/images/jenkins-logo-title-dark.svg
- content/images/jenkins-logo-title.svg
Addresses https://github.com/jenkinsci/jenkins/pull/6610#pullrequestreview-988663998
The colors chosen are part of GH's dark theme color palette:
cc @timja I agree, the white is quite aggressive compared to the regular, darker, white.
> Adjust jenkins-logo-dark.svg colors

- content/doc/administration/requirements/java.adoc
updated java requirements page to reflect upcoming weekly release line Java support (11 or 17), set expectations that Java 8 will be supported in the LTS until it eventually mirrors the weekly release line at a later time
> [DOCS-5646] adding Java 11 requirement info

- content/_layouts/advisory.html.haml
This makes admonitions in security advisories consistent with the rest of the site.
> Use icon admonitions for security advisories

- content/projects/gsoc/2022/projects/jenkinsfile-runner-action-for-github-actions.adoc
Update the weekly Zoom meeting url for Jenkinsfile-runner-action-for-github-actions project in GSoC2022.
> add the meeting url for weekly project-specific office hours

- content/_data/changelogs/weekly.yml
Upgrade was part of the inbound cooke key fix for connection state.
Thanks to Konstantin Bulanov for reporting it as part of [JENKINS-68739](https://issues.jenkins.io/browse/JENKINS-68739)
> Include remoting 3025.vf64a_a_3da_6b_55 in 2.354 changelog

- content/projects/gsoc/index.adoc
Changing the URL of the linked runbook to a cloned version of the document as the previous one was not 
writable anymore.
> Make GSoC Org Admin runbook writable again

- content/doc/developer/plugin-development/choosing-jenkins-baseline.adoc
following these recommendations for API plugins would be wrong.  The reasons provided in the original PRs for doing so are ~all~ mostly completely moot with an API plugin, and would lock out of any older version getting API fixes - esp security related ones or at least make it much more effort than would be required to deliver it.
> ignore recommendations for API plugins

- content/doc/book/installing/_docker-for-tutorials.adoc
- content/doc/book/installing/_docker.adoc
Short term fix for https://github.com/jenkins-infra/jenkins.io/issues/5222 until the tutorials can be reworked to use docker compose to provide a better solution than checkout from a local file system.
Also updates Blue Ocean plugins from 1.25.3 to 1.25.5.
Also updates the restart behavior to match latest Docker packaging per https://www.jenkins.io/blog/2022/05/27/docker-image-new-lifecycle/
Confirmed multibranch pipeline tutorial works on Windows with these changes and confirmed that without these changes, the tutorial fails with various problems, like:
* https://github.com/jenkins-infra/jenkins.io/issues/5222 - no local checkout
* Docker process now correctly restarts after plugin updates
* [multibranch pipeline](https://deploy-preview-5223--jenkins-io-site-pr.netlify.app/doc/tutorials/b …
> Fix multibranch pipeline tutorial

- content/doc/book/managing/system-properties.adoc
Thanks to @daniel-beck for reporting it in
https://github.com/jenkins-infra/jenkins.io/pull/5150#discussion_r900040013
> Correctly tag allowUnsupportedRemotingVersions escape hatch

- content/_data/indexpage/carousel.yml
Replacing the cdCon announcement by the DevOps World one on the Jenkins "Jumbotron"
> Add announcement of DevOps World to jumbotron

- content/download/index.html.haml
Possible solution for https://github.com/jenkins-infra/jenkins.io/issues/5238
The gear icon has been replaced with a library icon, but the text still refers to "the gear icon"
> Update text and icon pertaining to the gear-icon

- content/_layouts/documentation.html.haml
- content/css/jenkins.css
This pull request closes task https://issues.jenkins.io/browse/WEBSITE-799.
It introduces independent scrolling in the documentation sidebar, which is also made collapsible to facilitate the mobile experience. 
Upon expanding the sidebar, the main content gets pushed rightwards, and the footer is shrunk adequately. 
Upon expanding, we can overlap the sidebar on the content. This will make the toggling much faster for pages with large content.
Tagging the mentors - @kwhetstone @arpoch
> Add: Independent scrolling in documentation sidebar

- content/doc/book/installing/_jenkins-command-parameters.adoc
It's been warned against since 2016
see also https://github.com/jenkinsci/winstone/pull/232
> Remove suggestion for PEM encoded certs

- content/press.adoc
Follow-up of https://github.com/jenkinsci/packaging/pull/320
[As noted](https://github.com/jenkinsci/packaging/pull/320#discussion_r904687776) by @daniel-beck :
> We recently went over 300k: http://stats.jenkins.io/jenkins-stats/svg/total-jenkins.svg
> 
> > If we want to change the "official" description of Jenkins, we should start there.
> 
> still applies.
> 
> "more than 1,800 plugins" would also be a current number per [updates.jenkins.io/current/pluginCount.txt](https://updates.jenkins.io/current/pluginCount.txt)
> chore(`/press`): update installations and plugins numbers

- content/doc/book/installing/_jenkins-command-parameters.adoc
I tested with a PFX file and:
```
java -jar war/target/jenkins.war --httpsKeyStore=/tmp/certificate.pfx --httpsKeyStorePassword=Password12 --httpsPort=8443
```
Using this guide:
https://gist.github.com/mrcunninghamz/4f4ebbeeb4cfa9667870b8af4db24dc6
noticed during https://github.com/jenkinsci/winstone/pull/232
> Remove incorrect documentation about certificates

- content/doc/book/installing/_jenkins-command-parameters.adoc
added note informing users that Java 11 will be required on the weekly release line starting 2.353 and eventually the LTS in september
> [DOCS-5691] update jenkins parameters

- content/_data/changelogs/lts.yml
cf. https://github.com/jenkinsci/jenkins/pull/6618/commits/b86bfab1358f78bd9aa878cd2c94044e0a9eff71
I'm not really familiar with the usual process to update changelog, feel free to enlight me.
> Fix remoting reference for LTS

- content/doc/administration/requirements/java.adoc
- content/doc/administration/requirements/upgrade-java-guidelines.adoc
- content/doc/book/installing/_jenkins-command-parameters.adoc
- content/doc/pipeline/tour/getting-started.adoc
- Weekly release 2.357 requires Java 11
- Use Java 11 or Java 17 in guided tour
- Jenkins 2.357 requires Java 11 (not 2.353)
- Remove ALPN instructions for JDK 8u242 and earlier
- Use Java 11 or Java 17 in guided tour
> more java 8 removal

- content/doc/pipeline/steps/index.html.haml
Follow up of #5245 
This PR adds a search filter on the top of the pipeline steps reference page, which can be used to enter keywords and filter out the results shown on the page. A user can use this page to view specific material of interest amongst the large data present. 
**Direct link** - https://deploy-preview-5277--jenkins-io-site-pr.netlify.app/doc/pipeline/steps/
Tagging the mentors: @kwhetstone @arpoch
> Add: search for steps reference

- content/security/reporting.adoc
Currently the Jenkins X issues are tracked inside the SECURITY tracker of Jenkins CI, which I want to keep focus on Jenkins CI.
@rawlingsj related to our discussion
> Moving Jenkins X to their own security tracker

- content/doc/developer/tutorial/create.adoc
https://issues.apache.org/jira/browse/ARCHETYPE-539?focusedCommentId=17227010&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17227010
IIUC https://github.com/apache/maven-archetype/pull/109 was about this. Not sure about https://github.com/jenkinsci/archetypes/pull/42.
> Noting that `archetype:generate` can hang depending on mirror settings

- CONTRIBUTING.adoc
- content/_data/authors/halkeye.adoc
- content/doc/developer/publishing/wiki-page.adoc
- content/events/hacktoberfest.adoc
- content/events/online-hackfest/2020-uiux/index.adoc
- content/projects/infrastructure/index.adoc
See https://github.com/jenkins-infra/helpdesk/issues/3059 for the help
desk ticket to retire the wiki exporter service.
> Retire wiki-exporter from docs

- content/doc/book/blueocean/_blue-ocean-status.adoc
- content/doc/book/blueocean/activity.adoc
- content/doc/book/blueocean/blue-ocean-status.adoc
- content/doc/book/blueocean/creating-pipelines.adoc
- content/doc/book/blueocean/dashboard.adoc
- content/doc/book/blueocean/getting-started.adoc
- content/doc/book/blueocean/index.adoc
- content/doc/book/blueocean/pipeline-editor.adoc
- content/doc/book/blueocean/pipeline-run-details.adoc
creating a new page for a statement on the status of Blue Ocean. Once approved, it will be added to existing Blue Ocean documentation using the `include:` call
@halkeye does this meet a portion of your concerns if we embed this text in each of the Blue Ocean pages?
> [DOCS-5843] Adding Blue Ocean statement

- content/_layouts/advisory.html.haml
- content/security/advisory/2022-01-12.adoc
- content/security/advisory/2022-02-15.adoc
- content/security/advisory/2022-03-15.adoc
- content/security/advisory/2022-03-29.adoc
- content/security/advisory/2022-04-12.adoc
- content/security/advisory/2022-05-17.adoc
- content/security/advisory/2022-06-22.adoc
- content/security/advisory/2022-06-30.adoc
- content/security/plugins.adoc
Some "journalists" think it's newsworthy when we announce for the 8th time this year that some plugins don't get their vulnerabilities fixed due to being abandoned, calling it "announcing 0 days". So let's make our policy on this even more discoverable.
Thoughts on phrasing etc?
> Rephrase the section on unresolved vulnerabilities, link from advisory

- content/_layouts/corebaseline.html.haml
- scripts/fetch-external-resources
Fixes #5316.
I couldn't quite reuse the existing resource we downloaded (only .1) and was too lazy to adapt https://www.jenkins.io/doc/developer/javadoc/ , so this adds a resource download.
> More quickly pick up new LTS releases in version recommendations

- content/doc/developer/security/_chapter.yml
- content/doc/developer/security/csp.adoc
Better than nothing I guess?
Preview: https://deploy-preview-5301--jenkins-io-site-pr.netlify.app/doc/developer/security/csp/
> [JENKINS-60866] Add initial guidelines how to make code compatible with CSP

- content/doc/book/blueocean/_blue-ocean-status.adoc
- content/doc/book/blueocean/activity.adoc
- content/doc/book/blueocean/creating-pipelines.adoc
- content/doc/book/blueocean/dashboard.adoc
- content/doc/book/blueocean/getting-started.adoc
- content/doc/book/blueocean/index.adoc
- content/doc/book/blueocean/pipeline-editor.adoc
- content/doc/book/blueocean/pipeline-run-details.adoc
- content/doc/book/pipeline/development.adoc
- content/doc/book/pipeline/getting-started.adoc
- content/doc/book/pipeline/running-pipelines.adoc
Show selected portions of the Blue Ocean admonition based on the context.  If the page refers to Blue Ocean in general terms, use only the first paragraph of the admonition.  If the page refers to Blue Ocean Pipeline visualization, then include the portion of the admonition for Pipeline visualization.  If the page refers to Blue Ocean Pipeline creation, then include the portion of the admonition for Pipeline creation.
Thanks to the Docs office hours (Asia) for the suggestion to make the admonition content based on context.
Thanks to Gavin Mogan for the request to make it clear that Blue Ocean is not being actively developed.
Thanks to Kevin Martens for the original Blue Ocean admonition pull request.
> Use a 3 part Blue ocean admonition

- content/_ext/id_generator.rb
- content/_ext/pipeline.rb
- content/artwork/index.html.haml
I had a discussion come into the press email at one point and I wanted to direct link to a certain logo.
This will make it easier.
> Add anchors to artwork page's artwork so they can be direct linked to

- content/doc/book/pipeline/syntax.adoc
#1267 incorrectly (and very optimistically) provided incorrect documentation on how post works.
the post conditions are not always working at the stage level - success and failure can and do look at the stage, but others (unstable) look at the build results not the stage result.
the original was written before https://issues.jenkins.io/browse/JENKINS-52114?focusedCommentId=341713&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-341713 from @abayer that said as much, and whilst some work has gone into making the posts work at a stage level this has not been completed and now people are complaining about it https://issues.jenkins.io/browse/JENKINS-57801
Whilst it would be nice to get this fixed so the code does behave like the documentation, until that happens …
> fix the documention of post

- content/doc/book/installing/_docker-for-tutorials.adoc
- content/doc/book/installing/_docker.adoc
Tutorial users are better served by the most recent releases than by installing an older version.
- Use blue ocean 1.25.6 instead of 1.25.5
- Use docker workflow 1.29 instead of 1.28
> Use latest blue ocean and docker workflow plugins

- content/doc/developer/plugin-development/mark-a-plugin-incompatible.adoc
- content/doc/developer/publishing/releasing-cd.adoc
https://community.jenkins.io/t/indicating-breaking-changes-in-plugins-with-automated-releases/3285
Also https://github.com/jenkins-infra/jenkins.io/pull/4933#pullrequestreview-891196282
> Describing `hpi.compatibleSinceVersion` in CD-enabled plugins

- content/_layouts/advisory.html.haml
It's not super nice (e.g. core entries do not say they're about core, there's no specification of affected/fixed versions), but it's a start and does not require changes to the advisory data format.
Some examples from preview deployment:
* [Simple core entry](https://deploy-preview-5313--jenkins-io-site-pr.netlify.app/security/advisory/2022-06-22/#SECURITY-2566)
* [Complex core entry](https://deploy-preview-5313--jenkins-io-site-pr.netlify.app/security/advisory/2022-06-22/#SECURITY-2781)
* [Simple plugin entry](https://deploy-preview-5313--jenkins-io-site-pr.netlify.app/security/advisory/2022-06-22/#SECURITY-2760)
* [Multiple plugins entry](https://deploy-preview-5313--jenkins-io-site-pr.netlify.app/security/advisory/2022-02-15/#SECURITY-2613)
* [Silly plugins …
> Improve advisory layout to provide plugin ID(s) and severity inline

- content/_data/changelogs/weekly.yml
Add references for Jetty 10 upgrade and more text for the removal of support for PEM-encoded private keys.  Place the Jetty 10 upgrade at the top of the list.
> Revise 2.363 changelog

- content/doc/book/system-administration/reverse-proxy-configuration-apache.adoc
The reverse proxy check in Jenkins uses URL-encoded slashes, which Apache URL-encodes by default. This change adds the "NoEscape" flag on the rewrite rule to prevent that. It also adds a small reminder of the HTTPS options.
> Correct the Apache reverse proxy configuration with mod_rewrite

- content/templates/downloads.html.haml
There's new content on these pages since https://github.com/jenkins-infra/update-center2/pull/612 that needs a CSS update to look OK.
See e.g. https://updates.jenkins.io/download/plugins/matrix-auth/
> Update downloads template for new content

- content/verifications/matrix-1660367039.txt
Working to recover #jenkins-admin:matrix.org (currently mapped to freenode channel), support wants us to validate. This will make a simple text file that shows we own things.
> Need to validate for matrix support

- content/participate/report-issue/redirect.html.haml
Having "report a problem" link for reporting a problem with the "report a problem" page is confusing, IIRC https://github.com/jenkins-infra/jenkins.io/issues/5364 is not the first case where a user clicked the wrong link.
Preview: https://deploy-preview-5365--jenkins-io-site-pr.netlify.app/participate/report-issue/redirect/
> No error report link in footer of error report page

- content/doc/developer/publishing/preparation.adoc
See https://deploy-preview-5368--jenkins-io-site-pr.netlify.app/doc/developer/publishing/preparation/#signup-required
> Explain why Jira is needed despite GH issue tracking

- content/doc/developer/views/symbols.adoc
Documentation was only meant to be temporary here, until ui-samples turned into design-library, which happened months ago.
> docs: Update design library documentation

- content/blog/2022/06/2022-06-28-require-java-11.adoc
Addresses the feedback provided in [JENKINS-68866](https://issues.jenkins.io/browse/JENKINS-68866) by moving the information about agents to earlier in the document and providing explicit guidance about order of operations.
Also goes out of the way to emphasize that Java 8 can still be used for individual builds, as we have received several questions about whether that will still be possible (it will be!), including whether Global Tool Configuration can still be used to install Java 8 for application builds (it still can!).
CC @kmartens27 @MarkEWaite
> Improvements to "Require Java 11 or newer" blog post

- .gitignore
Adds `params` folder created inside `content/doc/pipeline/steps/` to `.gitignore` corresponding to the changes made under https://github.com/jenkins-infra/pipeline-steps-doc-generator/pull/211. This would keep local testing clean by keeping the asciidocs associated with Pipeline steps documentation (which are fetched as external resources) out of git's tracking.
> Add params folder to gitignore

- content/_partials/community-role-holder.html.haml
- content/project/board.html.haml
- content/stylesheets/components/_author.scss
As reported by Tim in https://github.com/jenkins-infra/jenkins.io/issues/5413, the board and officers page got a little messed up with the blog post redesign. This PR fixes that by using the same markup as the author component.
Fixes https://github.com/jenkins-infra/jenkins.io/issues/5413
**Before**
**After**
> Fix the Jenkins Board and Officers page

- content/doc/developer/persistence/incompatible-releases.adoc
- content/doc/developer/plugin-development/mark-a-plugin-incompatible.adoc
The `java.level` property is deprecated and will be removed from a future plugin parent pom.
See https://github.com/jenkinsci/plugin-pom/pull/522 for the plugin pom deprecation of `java.level`.
See the following additional references:
* https://github.com/jenkinsci/plugin-pom/pull/478#discussion_r809561384
* https://github.com/jenkinsci/plugin-pom/pull/478#issuecomment-1082144103
* https://github.com/jenkinsci/plugin-pom/pull/522#issuecomment-1083320869
Also uses newer Jenkins version in the example.  Would have liked to use the automatic replacement as is done in the "Choosing a Jenkins version" baseline page, but that was a larger change than I'm ready to make in this pull request.
> Remove java.level property from examples

- content/doc/book/system-administration/backing-up.adoc
I think using words instead of special symbols increases readability.
Fixes #5433
> More verbose description of finding backup plugins

- content/_data/changelogs/weekly.yml
Mistakenly included a leading "dash" character in the 2.368 changelog
> Remove leading dash from changelog entry

- content/doc/developer/development-environment/ide-configuration.adoc
- content/doc/developer/tutorial/prepare.adoc
https://github.com/jenkinsci/idea-stapler-plugin/issues/43 was completed which involved moving the repo from stapler to jenkinsci org and renaming of the plugin.
> Update references to the recently renamed IntelliJ IDEA plugin

- content/blog/2022/09/2022-09-14-create-iOS-unity-build-pipelines-on-AWS-with-Jenkins-and-EC2-Mac-instances.adoc
When we embed a link to https://www.jenkins.io in the site, we hinder local development of the site because clicked links jump away from the local development copy to the www.jenkins.io site.
> Use site local links

- content/doc/book/glossary/index.adoc
As requested in issue #5456, added an entry in glossary for Kubernetes, including a link to the related installation page.
> Resolves #5456 - Add a "Kubernetes" entry to the glossary

- content/doc/book/glossary/index.adoc
Adding the two links mentioned in #5455 into the "Step" glossary entry.
> Resolves #5455 - Link from "Step" glossary entry to Pipeline pages

- content/doc/book/installing/_docker-for-tutorials.adoc
- content/doc/tutorials/build-a-multibranch-pipeline-project.adoc
- Use LTS version of NodeJS, not NodeJS 6
- Export port 5000 for multibranch pipeline tutorial
Further improvements to the tutorial are now included in
https://github.com/jenkins-docs/building-a-multibranch-pipeline-project
> Use node:lts-alpine in tutorial

- content/project/governance.adoc
The Jenkins wiki has been decommissioned.  Current information is stored in other locations.  Update the governance document to refer to those other locations rather than providing a link to outdated pages.
> [WEBSITE-728] Remove wiki references from governance document

- content/doc/book/installing/_jenkins-command-parameters.adoc
As of https://github.com/jenkinsci/winstone/pull/282, which I am planning to release in 2.369, `jetty-alpn-java-server` is included by default, and there is no need for a special `--extraLibFolder` option. See also https://github.com/jenkinsci/winstone/pull/285.
> [JENKINS-69638] Update HTTP/2 documentation

- content/doc/book/installing/windows.adoc
This adds information on performing a silent install using the MSI installer on Windows. It gives an overview of the properties that can be used to override default values during the installation and some examples of how to use them on the command line.
> Add information about silent install on Windows

- content/events/hacktoberfest.adoc
removing the inclusive naming project as it requires direct coaching/more resources, in favor of projects that can be completed within the timeline
> Hacktoberfest - Remove project from list

- content/events/hacktoberfest.adoc
- content/events/hacktoberfest/faq.adoc
The change proposed
- fixes a few broken URLs
- uses up-to-date metrics, provided by the CDF (mostly empty at the time of submitting this PR, given the timeframe for 2022 didn't take place yet)
- adds proper links to our GH organizations taking part
- removes the stapler org from the search query. There's no repository, that opted-in hacktoberfest, nor is the org much of use nowadays.
- adds a few more languages to the entry of core, it's not all about Java ;)
- uses the official metric of 1,800 plugins, as known from other sources (see press page)
> Misc Hacktoberfest fixes

- content/doc/developer/tutorial-improve/add-more-spotbugs-checks.adoc
Reduce the risk of a horizontal scroll bar on the sample file and remove
a duplicated word in the description text.
> Shorten the example exclusion

- content/doc/book/managing/system-properties.adoc
References: https://github.com/jenkinsci/jenkins/pull/5698 and https://github.com/jenkinsci/jenkins/pull/6571
CC @basil
> Document `hudson.ClassicPluginStrategy.useAntClassLoader`

- content/_partials/changelog-old.html
Since we use `font-weight: bolder` for `<strong>` (thanks bootstrap), some old entries looked wrong.
This cleans them up a bit without substantially changing content:
* Move security fix entries from `(major) bug` to `security`.
* Remove `<strong>` tags from them.
* Link to the advisory if one was published.
* Change one instance of `<strike>…</strike>` to `<s>…</s>`.
Some entries older than 1.97 were left alone, as they don't use the colored list entry type indicators, so that would have been a larger change.
> Fix formatting of old security changelog entries, link advisories

- content/doc/developer/tutorial-improve/add-a-contributing-guide.adoc
The default guide is available as a hyperlink during pull request creation for all repositories in the jenkinsci GitHub organization.  A separate top level contributing guide can be more readily discovered, but if it is only a copy of the default, that is probably not enough justification to create a separate contributing guide in each plugin.
> Link to GitHub org default contrib guide

- CONTRIBUTING.adoc
Daniele Procida’s blog post on "What nobody tells you about documentation" is no longer available. Seems like it is replaced by Michael Nicholson’s blog post "Beginner’s Guide to Documentation: Here’s What You Need to Know" on the same website (link: https://www.divio.com/blog/beginners_guide_to_documentation/). All the links directing to the first blog post are replaced by the new one.
> Fix: Broken links to documentation model

- content/doc/book/glossary/index.adoc
I have added hyperlinks to Agent, Cloud and Node in Glossary.
Extend agent and related glossary entries with links to documentation sections #5454
> Extend agent and related glossary entries with links to documentation sections 
