- content/projects/index.adoc
Use a small image on the overview page.
> Add Jenkins Operator sub-project - small image

- content/_data/upgrades/2-277-1.adoc
- content/doc/developer/views/table-to-div-migration.adoc
While helping some users on Jira, I noticed that some users were confused about how to go about debugging and reporting configuration form modernization issues. Perhaps clarifying the documentation with these explicit instructions will help.
> Improve table-to-div migration documentation

- content/participate/code.adoc
- content/participate/document.adoc
- content/participate/index.html.haml
Also embeds three of the videos from the playlist into their respective pages.
> Link to Contributing to Jenkins YouTube playlist

- content/doc/developer/publishing/releasing.adoc
- content/doc/developer/publishing/requesting-hosting.adoc
- content/redirect/continuous-delivery-of-plugins.md
https://github.com/jenkinsci/.github/pull/48/files#r602241120
> Add redirect for CD of plugins

- content/_data/events/2021-06-22-cdcon.adoc
- content/_data/events/2021-06-25-contributor-summit.adoc
- content/_data/events/2021-09-29-devops-world.adoc
- content/events/contributor-summit/index.adoc
> Add Jenkins Contributor Summit, cdCon and DevOps World to the events

- content/sigs/docs/index.adoc
No attendance at the monthly meeting, all the work is being done in the office hours twice a week.
> Docs SIG meetings twice a week in office hours

- content/_data/events/2021-04-02-online-meetup.adoc
> Add event for the Jenkins Online Meetup on April 02

- content/_data/changelogs/weekly.yml
> Include additional 2.286 changelog items

- content/chat.adoc
subj. More documentation never hurts
> Reference channels for newcomer contributors, #jenkins-release and Slack in the /chat page

- content/projects/jenkins-operator/index.adoc
> Reference chats from the Jenkins Operator Project page

- content/projects/gsoc/2021/project-ideas/jenkins-operator-security.adoc
> GSoC 2021 - Fix chat and mailing list links in the Jenkins Operator project idea

- content/projects/gsoc/2021/project-ideas/tekton-client-plugin.adoc
FYI @waveywaves @garethjevans @MarckK
> Fix the SIG reference in the Tekton Pipelines project idea

- Dockerfile
Signed-off-by: Olivier Vernin <olivier@vernin.me>
> Fix hadolint warnings && remake make

- content/chat.adoc
> Remove the #jenkins archive reference from /chat

- content/doc/book/system-administration/security.adoc
- content/doc/book/system-administration/security/environment-variables.adoc
- content/redirect/environment-variables-security.adoc
> <img width="1260" alt="Screenshot" src="https://user-images.githubusercontent.com/1831569/114778436-21477e00-9d75-11eb-9285-4da09d1eb6c3.png">
> Document security considerations for environment variables

- content/_data/events/2021-04-29-redhat-webinar.adoc
- content/_data/events/2021-05-12-cdf-jte.adoc
> Add upcoming webinars to the Jenkins calendar

- content/blog/2021/02/2021-02-16-contributor-summit-online.adoc
Test deployment process has reverted as expected
> Fix blog post spelling error

- content/projects/gsoc/index.adoc
add missing "s"
project -> projects
> docs(index.adoc): fix "contact us" link

- content/projects/gsoc/2020/project-ideas/git-plugin-performance.adoc
- content/projects/gsoc/2021/project-ideas/git-credentials-binding-for-pipeline.adoc
Also added a leftover change on my laptop from last year.
> +justinharringa 2021 git credential binding mentor

- content/blog/2021/04/2021-04-07-contributhon-participants.adoc
@Queen-esther01 can you confirm this is your correct GitHub ID?
> Correct Esther Ejidike GitHub ID

- content/doc/book/pipeline/multibranch.adoc
Plugin: https://plugins.jenkins.io/dagshub-branch-source/
> Add DAGsHub branch source plugin to the multibranch doc

- content/participate/meet.adoc
> Add information about organizing events to /participate/meet

- content/project/teams/hosting.adoc
> Add IRC Chat and references to the Hosting Team page

- content/projects/infrastructure/ircbot.adoc
> Fix typo in the IRC Bot documentation

- content/doc/tutorials/kubernetes/installing-jenkins-on-kubernetes/jenkins-volume.yaml
The name of namespace can be found in follow file, which is `jenkins`:
https://www.jenkins.io/doc/book/installing/kubernetes/#create-a-namespace
> Update namespace to jenkins

- content/doc/book/installing/linux.adoc
See the [report from Horst Kronstorfer](https://groups.google.com/g/jenkinsci-users/c/4Hil7wsBb3Y/m/uCVsXz8ZAQAJ).
> Add chkconfig package to Fedora install

- content/blog/2021/04/2021-04-23-jenkins-contributor-awards.adoc
- content/index.html.haml
> cdCon Jenkins Contributor Awards - update the nominations deadline

- content/doc/book/installing/_kubernetes.adoc
Update the link of official minikube doc, because previous link is invalid.
> Update the link of official minikube doc

- content/donate.adoc
Follow-up to the discussion in https://groups.google.com/u/1/g/jenkinsci-dev/c/bIgDEM2E7hY
Needs approval from the @jenkins-infra/board
> Tear down the Friend of Jenkins program, document how to get recognition for donations

- content/sigs/advocacy-and-outreach/outreach-programs/index.adoc
This PR adds SheCodeAfrica to the outreach programs page. 
#4293 
@MarkEWaite @oleg-nenashev
> Added SheCodeAfrica to the outreach programs page

- content/mailing-lists/index.html.haml
I didn't test this change locally but I am not expecting to fail considering the other lines.
> Adding jenkinsci-board mailing information

- content/_data/roadmap/roadmap.yml
- Add SheCodeAfrica Contributhon to roadmap
- Move Jenkins on Kubernetes to near-term
* Continue 2020 roadmap work
*  Plugins docs migration to GitHub - already on the roadmap
* Wiki docs migration to www.jenkins.io - already on the roadmap
* Terminology cleanup - already on the roadmap
* Increase outreach
* Mentor SheCodeAfrica Jenkins projects in April - added by this pull request
* Mentor a 2021 Google Season of Docs writer - not accepted to GSoD but already on roadmap as outreach project
* Improve onboarding experience and add contributors - already on roadmap
* Improve our documentation sites
* Needs further work in the Docs office hours
* Wiki migration plan
* Needs an epic to track the replacement process.  Under discussion in Jenkins infra meeting
* Continue 2020 roadmap work
* …
> Docs & Platform roadmap updates from Feb Contributor Summit

- content/blog/2021/03/2021-03-19-SheCodeAfrica-announcement.adoc
- content/blog/2021/04/2021-04-07-contributhon-participants.adoc
- content/index.html.haml
- content/sigs/advocacy-and-outreach/outreach-programs/index.adoc
This PR changes the SheCodeAfrica text to She Code Africa
@MarkEWaite
> Modified the SheCodeAfrica text

- content/_data/roadmap/roadmap.yml
This happened some time ago and I forgot to update the project roadmap.
> Update JTE 2.0 on the Roadmap to current

- content/projects/infrastructure/ircbot.adoc
This adds information about setting the channel topic via the bot
> Add info about setting the channel topic

- content/chat.adoc
- content/doc/developer/publishing/releasing-cd.adoc
- content/project/teams/hosting.adoc
- content/projects/infrastructure/index.adoc
- content/projects/infrastructure/ircbot.adoc
- content/security/team.adoc
See [the mailing list thread](https://groups.google.com/g/jenkinsci-dev/c/pEcun5ZSfgo/m/ztRg03VNAgAJ).
> Migrate from Freenode to Libera Chat

- content/projects/gsoc/2021/projects/remoting-monitoring.adoc
This PR updates the GSoC 2021 Remoting Monitoring project page with
- Appropriate project links
- Office hours info
> Update GSoC 2021 Remoting Monitoring project page

- content/blog/2018/09/2018-09-14-kubernetes-and-secret-agents.adoc
This PR solves a bug raised in this issue [here](https://github.com/jenkins-infra/jenkins.io/issues/4315)
Fixes https://github.com/jenkins-infra/jenkins.io/issues/4315
@MarkEWaite
> Jenkins and Kubernetes - Secret Agents in the Clouds page - Correct a typo in the example

- content/_data/upgrades/2-289-1.adoc
Just a few minor improvements
CC @res0nance
> Add SSHD module unbundling, extend the new icons guide

- content/chat.adoc
Follow-up to the discussion in #4425 . This change simplifies the rendering and updates info to reflect the actual state
> Update IRC chats documentation, add the missing hosting channel

- content/events/contributor-summit/index.adoc
Updates for the agenda and for the event plan. Needs some alignment with @olblak .
Based on the current state of the planning doc: https://docs.google.com/document/d/1JVbWudREipEF5UJn-bBRU5QIjKf8mzFP9iFdwWbgFB0/edit?usp=sharing
> Update agenda, reference chats and discussion channels

- content/events/contributor-summit/index.adoc
Spelign checkrs is fir noobz :(
> Contributor Summit: Add anchors + More typo fixes

- content/_data/changelogs/weekly.yml
Required so it can be generated automatically, no other diff occurs other than a one-off change
See https://github.com/jenkinsci/core-changelog-generator/pull/14
> Indent file by one

- content/security/plugins.adoc
Downstream from https://github.com/jenkins-infra/update-center2/pull/526
> [INFRA-2997] Restore zap-pipeline

- content/blog/2021/06/2021-06-21-student-luminy-project-security.adoc
> Add a Discourse reference to the Jenkins Security post

- content/doc/book/system-administration/reverse-proxy-configuration-iis.adoc
I fixed the mistake.
nginx -> IIS.
> docs: nginx to IIS

- .github/CODEOWNERS
> Request reviews from the Jenkins Governance board in roadmap item changes

- content/doc/book/security/access-control.adoc
- content/doc/book/security/build-authorization.adoc
- content/doc/book/security/environment-variables.adoc
- content/doc/book/security/services.adoc
I changed the layout to a section.
> docs: change layout to section

- content/security/advisory/2021-06-30.adoc
Otherwise nothing would have changed 😄 
Thanks @KalleOlaviNiemitalo!
> <img width="1283" alt="Screenshot 2021-07-02 at 13 56 28" src="https://user-images.githubusercontent.com/1831569/124271203-75c0f500-db3d-11eb-90f2-67df5c1902d7.png">
> Fix fix description for SECURITY-1995 in 2021-06-30 advisory

- content/doc/developer/security/form-validation.adoc
Untested.
Please delete origin branch on merge.
> Clarify the version-dependent default behavior

- content/doc/developer/plugin-development/dependencies-and-class-loading.adoc
https://github.com/jenkins-infra/jenkins.io/pull/1130#issuecomment-873628174
> Updates to `/doc/developer/plugin-development/dependencies-and-class-loading/`

- content/doc/developer/publishing/releasing-manually.adoc
> <img width="1269" alt="Screenshot 2021-07-16 at 11 09 41" src="https://user-images.githubusercontent.com/1831569/125923510-40d553f5-3a4e-4c9e-a4f9-9ab687ea0802.png">
> Add instructions for the encrypted password from Artifactory

- content/doc/book/managing/system-properties.adoc
Obsoleted in jenkinsci/jenkins#5603.
> Marking `hudson.TreeView` as obsolete

- content/doc/book/security/access-control.adoc
- content/doc/book/security/access-control/permissions.adoc
> <img width="1283" alt="Screenshot 2021-07-06 at 17 27 40" src="https://user-images.githubusercontent.com/1831569/124627211-a7102c80-de7f-11eb-99d5-4c82237c79d5.png">
> Add section on common mistakes when configuring authentication and authorization

- content/blog/2021/07/2021-07-30-introducing-conventional-commits-plugin-for-jenkins.adoc
Update the youtube video URL as shorten URLs won't render properly.
Signed-off-by: Aditya Srivastava <adityasrivastava301199@gmail.com>
> fix: update video url

- content/blog/2021/07/2021-07-30-introducing-conventional-commits-plugin-for-jenkins.adoc
Signed-off-by: Aditya Srivastava <adityasrivastava301199@gmail.com>
> Update conventional commits blog video URL

- content/doc/book/using/aborting-a-build.adoc
Instead of "can by" it should be "can be"
> Fixed Typo

- content/doc/book/blueocean/dashboard.adoc
- content/doc/book/blueocean/getting-started.adoc
Updated two documentation articles: dashboard.adoc and getting-started.adoc
> grammar and punctuation fixes

- content/index.html.haml
> Add discourse sponsorship

- content/projects/infrastructure/index.adoc
Update this page as we recently changed the meeting time
> Update Jenkins infrastructure meeting information

- content/_data/changelogs/weekly.yml
@StackScribe and @dheerajodha these are my proposed changes to edit for consistency
> Update 2.308 changelog for consistency

- content/events/hacktoberfest.adoc
- content/events/hacktoberfest/event-kit.adoc
- content/events/hacktoberfest/faq.adoc
Just preparation for Hacktoberfest 2021 so that we can reference the page from CDF announcements
> Update Hacktoberfest pages towards the 2021 edition

- content/doc/book/installing/_docker-for-tutorials.adoc
- content/doc/book/installing/_docker.adoc
Thanks to @ryanhankins for catching the problem and submitting the original fix!
> Replace obsolete docker tags with current tags

- content/blog/2021/09/2021-09-04-wiki-attacked.adoc
Summarize our response to the wiki attack that was detected this week.
Looks like this:
> Add blog describing response to wiki attack

- content/blog/2021/09/2021-09-21-jenkins-at-devops-world.adoc
> Announce DevOps World 2021

- content/blog/2021/09/2021-09-23-jenkins-health-advisor-by-cloudbees.adoc
Tool Makes Life Easier for Jenkins Administrators
This blog post is cowritten with @darinpope, thanks to @alyssat
> New blog post: Jenkins Health Advisor by CloudBees 

- content/doc/book/managing/built-in-node-migration.adoc
https://github.com/jenkinsci/workflow-durable-task-step-plugin/releases/tag/workflow-durable-task-step-2.40
https://github.com/jenkinsci/workflow-durable-task-step-plugin/pull/168
https://groups.google.com/g/jenkinsci-users/c/R7AUrb6nq5k/m/j_Omo1f3BQAJ
Untested.
> Update for Pipeline: Nodes and Processes 2.40

- content/events/hacktoberfest.adoc
Proposition for a translation topic for hacktoberfest.
I had request by DM to do other languages, so I adding it but personally I can only review French contribution :)
> Proposing a french localization topic for hacktober fest 2021

- content/_data/changelogs/lts.yml
- content/_data/changelogs/weekly.yml
- content/_data/upgrades/2-289-1.adoc
> Hudson was renamed Jenkins in 1.396

- content/doc/book/using/remote-access-api.adoc
This updates the link from the wiki to the new location on jenkins.io
> Update link to the correct location on jenkins.io

- content/events/hacktoberfest.adoc
> Add CSP as feature topic for Hacktoberfest 2021

- content/_partials/toptoolbar.html.haml
- content/css/jenkins.css
**Feature:Enhancement - Improving navbar for mobile resolutions. (#4595)**
- Moved "Search Bar" to be top of "Download" Button.
- Made search result's dropdown to take full width for better alignment and better space usage.
- Centered menu items.
- Removed left margins available in Search and Download elements.
**Relevant Issues/PullReqs :** #4595, #4154
> Feature:Enhancement - Improving navbar for mobile resolutions. (#4595)

- content/doc/book/pipeline/syntax.adoc
Fix https://github.com/jenkins-infra/jenkins.io/issues/4681
> UpstreamCause should be BuildUpstreamCause

- content/doc/book/installing/_docker-for-tutorials.adoc
- content/doc/book/installing/_docker.adoc
No reason to install an older plugin version
> Use blue ocean 1.25.1 - latest

- content/redirect/remoting-security-workaround.adoc
> Update redirect to final location at plugins.jenkins.io

- content/_data/changelogs/lts.yml
- content/_data/changelogs/weekly.yml
- authors not array
- single version not string
> Data Fixes: changelogs

- content/doc/book/pipeline/development.adoc
Access Control of Replay is explained.
> Two extra points are added to Replay features

- content/_data/changelogs/lts.yml
- content/_data/changelogs/weekly.yml
* Make sure all issues are numbers
* Added regression key to keep the data (can delete if desired)
> Cleanup changelog.yaml data

- content/_data/changelogs/weekly.yml
> Revise and reorder 2.320 changelog

- content/security/advisory/2021-11-12.adoc
The reporter informed us too late how they want to be credited.
> Add credit for SECURITY-2488

- content/security/plugins.adoc
Requested by maintainer in https://github.com/jenkins-infra/update-center2/pull/552
Origin branch, please delete on merge.
(It's annoying that GH doesn't let me create a branch in my fork just because I have write access…)
> Note that squashtm-publisher is not suspended for security

- content/slides.yaml
As the 2021 edition is finished.
> chore: remove hacktoberfest slide

- content/_data/changelogs/weekly.yml
Based on review comments from Docs Office Hours.
Thanks to @stackscribe and @kwhetstone
> Update 2.323 changelog

- content/blog/2021/12/2021-12-03-election-results.adoc
Thanks @wadeckfollonier for catching that!
> Term ends Dec 2023 for new board members

- content/_data/changelogs/weekly.yml
Also move hyperlinks into the references section of the changelog entry
> Move developer items to end of 2.324 changelog

- content/doc/book/installing/linux.adoc
- content/doc/book/installing/windows.adoc
- Embed Windows install tutorial video
- Embed CentOS install video tutorial
> Embed install tutorial videos

- content/blog/2021/12/2021-12-08-containers-as-build-agents.adoc
Elections image is the wrong image
> Use correct opengraph image

- content/blog/2021/12/2021-12-10-log4j2-rce-CVE-2021-44228.adoc
Authors: Daniel Beck, Wadeck Follonier, Herve Le Meur, Mark Waite
> CVE-2021-44228 blog post

- content/_data/changelogs/weekly.yml
> Reorder 2.325 changelog entries

- content/doc/book/security/environment-variables.adoc
Noting https://plugins.jenkins.io/safe-batch-environment-filter/
> Note safe-batch-environment-filter plugin

- content/doc/developer/publishing/releasing-cd.adoc
> Expanded JEP-229 instructions

- content/blog/2022/01/2022-01-06-gsoc-2022.adoc
- content/projects/gsoc/proposing-project-ideas.adoc
Blog post for soliciting GSoC 2022 projects and mentors
> GSoC 2022 Blog post

- content/blog/2022/01/2022-01-07-gsoc-2022.adoc
Made a suggestion a little too late on the last PR https://github.com/jenkins-infra/jenkins.io/pull/4808#discussion_r780577740
> Fix the lower case of last blog title

- content/blog/2014/2014-05-30-adopt-a-plugin.adoc
fix https://www.jenkins.io/blog/2014/05/30/adopt-a-plugin/#content-top
> Fix blog page

- content/doc/book/managing/index.adoc
> Fix spelling error #4831

- content/doc/developer/handling-requests/json.adoc
Fixing some mistakes I did on the first PR, this one is addressing https://github.com/jenkins-infra/jenkins.io/pull/4812/files#r787770281
> [documentation] Update dev doc with after merge feedbacks.

- content/_data/authors/krisstern.adoc
Updating the placeholder user page under my name created recently to add:
1. GH username
2. LinkedIn username
3. A brief bio
> Make user changes for Kris Stern (krisstern)

- content/projects/gsoc/students.adoc
Updated doc to reflect current terms, links, dates, and communication channels
> Update doc to reflect current terms

- content/_data/changelogs/weekly.yml
* Move developer entry to end of list
* Move "form width" fix to the top of the list
> Revise 2.331 changelog

- content/projects/gsoc/2022/project-ideas.html.haml
Changed terminology - students to GSoC contributors
> Update project ideas page

- content/projects/gsoc/roles-and-responsibilities.adoc
Update page to include current terminology
> roles-and-responsibilities.adoc

- content/doc/developer/publishing/wiki-page.adoc
> Update plugin documentation migration steps in Plugin Wiki Pages page

- content/projects/gsoc/2022/project-ideas/JCasC-drift-detector.adoc
Updated the discussion thread link as well as the proposed project objective and description.
> Update JCasC Drift detector project

- content/projects/gsoc/mentors.adoc
- Changed "student" to "GSoC Contributor"
- First refactoring iteration on the communication channels.
> GSoC mentor page update

- content/doc/developer/handling-requests/json.adoc
The lastest version has changed methods are from WebClient and not JenkinsRule, so this documentation requires some last updates.
https://github.com/jenkinsci/jenkins-test-harness/pull/378 is merged, so this one can be merged when you want.
> [doc]Updating json examples with the final version.

- content/_data/roadmap/roadmap.yml
- JEP-221 is now current as JEP-229
- Hacktoberfest 2021 is complete
> Hacktoberfest 2021 is done

- content/projects/gsoc/index.adoc
> fixed typo in index.adoc

- content/projects/gsoc/index.adoc
To view the page being worked on in the preview environment: https://deploy-preview-4867--jenkins-io-site-pr.netlify.app/projects/gsoc/
> Corrections to GSoC main page

- content/doc/book/installing/_docker-for-tutorials.adoc
- content/doc/book/installing/_docker.adoc
> Use docker workflow plugin 1.28 in tutorial

- content/doc/book/managing/index.adoc
Untested. Clearly nobody has ever clicked any of these links so I can't be making it any worse 😄 
Lazy branch, please delete on merge.
> Fix links (hopefully)

- content/projects/gsoc/2022/project-ideas/automatic-git-cache-maintenance.adoc
Kris shared that he's willing to mentor during Google Summer of Code office hours.
Rishabh shared that he's willing to mentor through email messages with Mark Waite.
@rishabhBudhouliya and @krisstern this is the pull request I promised to create.
> Kris Stern & Rishabh Budhouliya mentoring git cache maintenance idea

- content/_data/changelogs/weekly.yml
> Update weekly changelog with formatting fixes

- content/projects/gsoc/2022/project-ideas/plugin-health-scoring-system.adoc
Proposing additional details for this GSoC project.
Preview: https://deploy-preview-4919--jenkins-io-site-pr.netlify.app/projects/gsoc/2022/project-ideas/plugin-health-scoring-system/
> add substance to the plugin-health-score GSoC project

- content/_data/changelogs/weekly.yml
- JENKINS-67487, not JENKINS-674487
- JENKINS-67000 remoting bug fix
> Fix 2.335 changelog issues

- content/doc/book/security/controller-isolation/agent-to-controller.adoc
- content/doc/book/security/controller-isolation/required-role-check.adoc
Fix #4928 - broken image in agent to controller subsection
Broken image at https://www.jenkins.io/doc/book/security/controller-isolation/agent-to-controller/
Working image at https://deploy-preview-4934--jenkins-io-site-pr.netlify.app/doc/book/security/controller-isolation/agent-to-controller/
> Images in lower directory need parent one higher

- content/doc/developer/security/scan.adoc
- content/redirect/jenkins-security-scan.adoc
Documentation for https://github.com/jenkinsci/.github/pull/68
> Add documentation for Jenkins Security Scan

- content/security/plugins.adoc
Companion of https://github.com/jenkins-infra/update-center2/pull/572
> Unsuspend publish-over-ssh

- content/doc/book/installing/_docker-for-tutorials.adoc
- content/doc/book/installing/_docker.adoc
Allows pipeline editor to work with pipelines in folders - [JENKINS-53291](https://issues.jenkins.io/browse/JENKINS-53291)
> Use blue ocean 1.25.3 - latest release

- content/_data/indexpage/supporters.yml
Part of https://github.com/jenkins-infra/helpdesk/issues/2651
cc @MarkEWaite
> Add Digital Ocean to the sponsors list

- content/doc/developer/publishing/releasing-cd.adoc
Split the step into 2 so that each step applies to exactly one file.
> Clarify release drafter configuration changes

- content/doc/developer/publishing/releasing-cd.adoc
Probably not obvious if you have not done this before!
also https://github.com/jenkins-infra/helpdesk/issues/2799#issuecomment-1054588241
> Link to config page for RD App

- content/doc/developer/publishing/preparation.adoc
- content/doc/developer/publishing/releasing-manually.adoc
Also remove a mention of the wiki, which doesn't exist anymore.
> Add instructions how to obtain your encrypted Artifactory password using curl

- content/doc/developer/publishing/releasing-cd.adoc
> Note usage of `mvn validate`

- content/_data/upgrades/2-332-1.adoc
- Move Guava ahead of other changes
- Add systemd section to upgrade guide
> Add systemd upgrade guide

- content/_data/changelogs/lts.yml
Thanks to Cathy Chan for detecting the mistake
> Add a missing 2.332.1 backport changelog entry

- content/_data/indexpage/carousel.yml
Adding announcement of cdCon 2022 to the TurboTron.
> Adding cdCon-2022 announcement to turbotron

- content/projects/gsoc/2022/project-ideas/automatic-spec-generator-for-jenkins-rest-api.adoc
FYI @kwhetstone @AbhyudayaSharma I am not ready to mentor this project this year. We have a lot of documentation focused project in Keptn, and I would prefer to focus on them
> Remove @oleg-nenashev from the "Automatic Specification Generator for Jenkins REST API" project idea

- content/_data/authors/koushartasneem.adoc
- content/projects/gsoc/2022/project-ideas/pipeline-step-documentation-generator.adoc
- About Me:
- I am Tasneem Koushar and I have worked at Chromium under Google Summer of Code 2021 and Successfully created automated documentation of Puppeteer.
- I want to help contributors at Jenkins and am interested in becoming one of the mentors for the project: [Pipeline Step Documentation Generator improvements](https://www.jenkins.io/projects/gsoc/2022/project-ideas/pipeline-step-documentation-generator/)
- My Picture:
- https://drive.google.com/file/d/1x95WwaOb_DVhymjleOD3vGXvH5STq9AN/view?usp=sharing
> add Tasneem Koushar as GSOC Mentor

- content/doc/developer/publishing/documentation.adoc
Origin branch, please delete on merge.
> Update how we determine who to show as maintainer

- content/doc/developer/security/scan.adoc
Preview site: https://deploy-preview-5003--jenkins-io-site-pr.netlify.app/doc/developer/security/scan/
> Add troubleshooting information for Jenkins Security Scan

- content/doc/developer/security/scan.adoc
https://github.com/jenkins-infra/jenkins-security-scan/commit/2c05970ec4b57079c7bd44e16c026fa824ca719b
> Update description after repository restructuring

- content/doc/developer/security/scan.adoc
Sort of experimental: I rephrased this page a bit to make it easier to understand (mostly based on advice from https://hemingwayapp.com/).
Is this useful? Thoughts?
CC @jmMeessen
> Rephrase to make this easier to understand

- content/doc/book/managing/system-properties.adoc
- content/doc/developer/security/remoting-callables.adoc
Adapt to https://github.com/jenkinsci/remoting/pull/490 and https://github.com/jenkinsci/jenkins/pull/5901
> Adapt documentation to jenkinsci/remoting#490

- content/_data/upgrades/2-332-1.adoc
Ref: https://github.com/jenkins-infra/helpdesk/issues/2851#issuecomment-1079127129
> fix: correct link to the systemd-migration blog post

- content/_partials/downloadbanner.html.haml
See the meeting notes from governance meeting March 23, 2022 and March 9, 2022 for the approvals of the message.
https://docs.google.com/document/d/11Nr8QpqYgBiZjORplL_3Zkwys2qK1vEvK-NYyYa4rzg/edit?usp=sharing
> Add CDF statement on support of the people of Ukraine

- content/security/advisory/2022-03-29.adoc
- content/security/plugins.adoc
https://github.com/jenkins-infra/update-center2/pull/583
> Suspend phoenix-autotest

- content/doc/developer/index.html.haml
- content/participate/code.adoc
At present, there are more than 1800 plugins in the official link below
* https://github.com/jenkinsci/.github/blob/master/profile/README.md
* https://plugins.jenkins.io/
So create this PR to modify the number of plugins to be consistent.
> Using consistent number of the plugin count

- content/doc/developer/security/scan.adoc
Someone (don't remember who) asked me about this a while back. I found the setting to customize behavior today, so here's some documentation for it.
> Add explanation for checks unexpectedly passing

- content/_data/authors/kmartens27.adoc
changed bio to be more informative of my role
> Updated author bio

- content/doc/administration/requirements/upgrade-java-guidelines.adoc
embedded Darin Pope's video on upgrading from Java 8 to Java 11
> add Darin Pope video to java upgrade guide

- content/doc/book/system-administration/systemd-services.adoc
adding Darin Pope's video on managing systemd services into the systemd services page
> adding video on managing systemd

- content/doc/book/pipeline/multibranch.adoc
adding in multibranch video from youtube
> [Docs 5375] - Adding Multibranch Video to Jenkins Docs

- content/doc/book/using/using-credentials.adoc
adding Credentials best practice video from youtube
> [DOCS-5375] adding credentials youtube video to page

- content/download/index.html.haml
this problem occur on mobile screen
> SHA 256 text on mobile screen solved

- content/doc/book/managing/system-properties.adoc
- content/doc/developer/handling-requests/routing.adoc
- content/doc/developer/views/index.adoc
For system properties page, some misc cleanup and addition of some Stapler-related escape hatches that were missing.
https://deploy-preview-5087--jenkins-io-site-pr.netlify.app/doc/book/managing/system-properties/
https://deploy-preview-5087--jenkins-io-site-pr.netlify.app/doc/developer/handling-requests/routing/#debugging-hints
https://deploy-preview-5087--jenkins-io-site-pr.netlify.app/doc/developer/views/
> Add information about Stapler debugging flags

- content/security/cna.adoc
- content/security/index.adoc
(At least not about stupid shit.)
For @Wadeck's consideration.
> Ask people to not contact the security team

- content/doc/book/pipeline/shared-libraries.adoc
added video, title ends up in unwanted spot so no title is placed, other changes are strictly trailing spaces being removed, no other content is being updated at this time.
> [DOCS-5376] Add Getting started with shared libraries video

- content/doc/book/managing/nodes.adoc
Added new section header, short description, and link to video for creating a macOS agent in Jenkins.
> [DOCS-5547] adding video on creating macOS agent in Jenkins

- content/doc/book/pipeline/index.adoc
Fix https://github.com/jenkins-infra/jenkins.io/issues/5119
Thanks @KES777 for the issue report
> Use correct callout for Pipeline example

- content/doc/book/managing/change-system-timezone.adoc
adding the recently added video on how to configure the time zone
> [DOCS-5547] adding time zone video to jenkins page

- content/doc/book/using/using-agents.adoc
added youtube video for How to restart a Jenkins agent, ensured previous section was closed and new one started
> [DOCS-5547] add restarting jenkins agent video

- content/doc/book/managing/plugins.adoc
adding youtube video tutorial for uninstalling plugin to existing "uninstalling a plugin" section
See the preview at https://deploy-preview-5123--jenkins-io-site-pr.netlify.app/doc/book/managing/plugins/#uninstalling-a-plugin
> [DOCS-5547] adding plugin uninstalltion video

- content/doc/book/pipeline/getting-started.adoc
added basic intro of writing Jenkins pipeline scripts video & short intro to getting started doc,
> [DOCS-5544] adding pipeline script creation video

- content/doc/book/pipeline/pipeline-best-practices.adoc
added shell script section to pipeline best practices documentation, lines 38 - 45
all other updates are just trailing spaces that have been removed, and other text/content would be outside of the scope of this request
> [DOCS-5544] adding shell script section & video

- content/doc/book/pipeline/shared-libraries.adoc
added
- embedded video on page
- short description before
- direct link to video page for access to example repository
> [DOCS-5544] adding shared libraries usage video

- .gitpod.yml
This will open a preview window once the live server is ready.
> Open preview on opening Gitpod workspace

- content/doc/developer/crowdin/translating-plugins.adoc
- content/doc/developer/views/index.adoc
Additionally, I've added the link to the online meetup.
> Exchange ui samples URL and add Crowdin to views page

- content/doc/book/pipeline/pipeline-best-practices.adoc
added section header, context, and embedded video for "Cleaning up old Jenkins builds"
> [DOCS-5544] adding clean up old Jenkins build video

- content/blog/2022/05/2022-05-13-mirrors.jenkins.io-HTTPS.adoc
Ref. https://github.com/jenkins-infra/helpdesk/issues/2888
Ping @MarkEWaite @olblak @lemeurherve @timja @smerle33 this is a first draft, any feedback welcome (on both content and language) !
> blog: add a new post about HTTPS /consolidation for mirrors.jenkins.io

- .typos.toml
- content/doc/developer/persistence/backward-compatibility.adoc
- Fix a spelling error
- Exclude YouTube URL 4UmY4dDAlo0 from typo check
> Fix 2 typos

- content/doc/book/security/build-authorization.adoc
https://github.com/jenkinsci/jenkins/pull/6222 https://issues.jenkins.io/browse/JENKINS-61990 etc.
> Do not recommend `authorize-project`

- content/doc/book/pipeline/running-pipelines.adoc
added section for scheduling job info, and embedded video reviewing the function & its various configuration options
> [DOCS-5545] adding scheduling jobs in Jenkins video

- content/doc/book/pipeline/getting-started.adoc
Added video reviewing currentBuild in pipeline and how that helps provide further insight to the build itself
> [DOCS 5545] adding currentBuild video

- content/_data/changelogs/weekly.yml
Moved link to Design library to references so that the link is clickable.
> Moved link to Design library to references so that the link is clickable

- content/doc/book/managing/nodes.adoc
added intro and video from youtube to Jenkins documentation
> [DOCS-5546] adding installation of agent on windows vid

- content/doc/book/pipeline/index.adoc
added video to pipeline landing page, goes over freestyle vs pipeline jobs in Jenkins, seems like a natural fit in documentation
> [DOCS-5545] adding freestyle vs pipeline video

- .typos.toml
- content/doc/pipeline/tour/running-multiple-steps.adoc
added content & text to "running multiple steps" page of guided tour
> [DOCS-5545] adding timeout video

- content/_layouts/gsocproject2.html.haml
- content/blog/2022/05/2022-05-20-gsoc2022-projects-announcement.adoc
- content/projects/gsoc/2022/projects/automatic-git-cache-maintenance.adoc
- content/projects/gsoc/2022/projects/blank_project.adoc
- content/projects/gsoc/2022/projects/jenkinsfile-runner-action-for-github-actions.adoc
- content/projects/gsoc/2022/projects/pipeline-step-documentation-generator.adoc
- content/projects/gsoc/2022/projects/plugin-health-scoring-system.adoc
- content/projects/gsoc/index.adoc
Blog post to announce GSoC 2022 nominees
> Announcing GSoC 2022 nominees

- content/sigs/docs/index.adoc
Corrected the timing for the Thursday Docs office hours.
> Correct docs office hours meeting time

- content/doc/book/security/controller-isolation.adoc
It's been long enough now I think
> Terminology update

- content/_data/authors/Cr1t-GYM.adoc
- content/_data/authors/krisstern.adoc
- content/projects/gsoc/2022/projects/jenkinsfile-runner-action-for-github-actions.adoc
To complete the details for the Jenkins GSoC 2022 Jenkinsfile Runner project mainly using info provided GSoC contributor. Added details to the following sections:
Also updated are the details regarding prolect mentors, communications channel to be dedicated to the project on Slack, and the spelling of the contributor's name.
> Add details to GSoC 2022 Jenkinsfile Runner project

- content/security/plugins.adoc
Upstream of https://github.com/jenkins-infra/update-center2/pull/592
> Note suspensions after 2022-05-17 security advisory

- content/doc/administration/requirements/upgrade-java-guidelines.adoc
- content/doc/pipeline/tour/getting-started.adoc
added context for java 11 requirement based on LTS vs weekly release line
> [DOCS-5646] adding in java 11 requirement text

- content/projects/gsoc/2022/projects/automatic-git-cache-maintenance.adoc
Updated the Ascii Doc for Git Cache Maintenance Project GSoC2022.
> Added details for Git Cache Maintenance Project

- content/doc/book/managing/script-approval.adoc
> add note about context of script approval

- content/_data/changelogs/lts.yml
- content/_data/upgrades/2-346-1.adoc
Also including several other copyedits while I was here.
CC @kmartens27 @MarkEWaite
> Update changelog to describe packaging changes

- content/doc/developer/plugin-development/dependencies-and-class-loading.adoc
Cleanup. https://github.com/jenkinsci/jep/pull/391
> [JEP-230] Modules now of historical interest only

- content/doc/pipeline/steps/index.html.haml
Increase search box width and remove logging message from #5277.
https://deploy-preview-5279--jenkins-io-site-pr.netlify.app/doc/pipeline/steps/
> Increase searchbox width

- content/doc/tutorials/create-a-pipeline-in-blue-ocean.adoc
Reviewed and updated text for "create a pipeline" tutorial
> [DOCS-5813] "create a pipeline" text update

- content/doc/book/glossary/index.adoc
Reported by user feedback on the page
> Use controller, not master in glossary

- content/doc/book/managing/ui-themes.adoc
Adds more theme plugins to the list, including:
* Dark theme
* Material theme
* Solarized theme
Additions based on user feedback from the "Improve this page" form.
> Include more plugins in the themes page

- content/projects/gsoc/2022/projects/jenkinsfile-runner-action-for-github-actions.adoc
* Add midterm presentation ppt link so people can see the demo and watch some demo details.
> Add midterm presentation link

- content/doc/book/blueocean/getting-started.adoc
Reviewed and updated "Getting started in Blue Ocean" page, updated lines/spacing for single line sentences and reformatted text as needed. Most screenshots did not need replacing as Blue Ocean UI has not changed, but Manage Plugins screen was (previously) updated accordingly.
> [DOCS-5905] Updating getting started in blue ocean doc

- content/security/advisory/2022-07-27.adoc
Origin lazy branch, please delete on merge.
@Kevin-CB
> Add credit for SECURITY-2413

- scripts/release.rss.rb
> Fix self href for releases.rss, add www where needed

- content/_data/changelogs/weekly.yml
Move links to references
Move developer items to end
> Revise 2.362 changelog

- content/doc/book/blueocean/index.adoc
Updated index page to set proper expectations and bring it up to date with Blue Ocean's current status (existing status statement)
> [DOCS-5944] Updating Blue Ocean index page

- content/css/jenkins.css
Fixes https://github.com/jenkins-infra/jenkins.io/issues/5334
(the header height is not constant so this is not perfect for all resolutions, but with the previous header design there was the same problem)
> Make anchor offset match header height

- content/pipeline/getting-started-pipelines.adoc
Change the spelling of "Word" to "World" and make a few minor English language improvements to that section.
> Correct spelling of "Hello Word"

- CONTRIBUTING.adoc
The sentence beginning with the following does not make sense: 
These files represent structured around ...
So, I changed it to:
These files represent the structure around the date the original stories were written in Drupal.
The English is now correct (or at least better), but I am not sure if this is the intended meaning.
> Correct English language and clarify some phrases

- content/doc/book/blueocean/_blue-ocean-status.adoc
- content/projects/blueocean/about/index.adoc
- content/projects/index.adoc
See https://github.com/jenkinsci/blueocean-plugin/pull/2325 and the notes of the Jenkins Governance meeting for more details.
> Add Blue Ocean admonition to more locations

- content/doc/book/pipeline/shared-libraries.adoc
lower-case should be lowercase as established by #5345
> Remove hyphen from lowercase

- content/_partials/toptoolbar.html.haml
https://github.com/jenkins-infra/jenkins.io/pull/5347#issuecomment-1209616278
> Actually fix active_link indicator for 'Blog' menu item

- content/_data/authors/jleon.adoc
- content/blog/2022/08/2022-08-11-plugin-health-scoring.adoc
Plugin health Scoring 
* @alecharp @adi10hero @dheerajodha @ryecb
> [blog] DevOps World talk on Plugin Health Scoring project

- content/_data/upgrades/2-346-3.adoc
> Noting jenkinsci/workflow-cps-plugin#543 in the upgrade guide

- content/_data/upgrades/2-346-3.adoc
> Update release notes with OpenJDK issues

- content/doc/tutorials/create-a-pipeline-in-blue-ocean.adoc
added Blue Ocean status statement to tutorial page
> add blue ocean status to create a pipeline in Blue Ocean tutorial

- content/_data/changelogs/weekly.yml
Move developer entries to end of the list
Add links to changelog entries
> Reorder 2.365 changelog entries

- content/doc/book/installing/_docker.adoc
The code was not separated from the text, so I added a space.
> Added a space between code and text

- content/blog/2022/08/2022-08-31-DW_java11_performance.adoc
Announcing a DevOps World 2022 talk about moving Jenkins to a New Frontier of Performance with Java 11.
> Announcing DW2022 talk about Jenkins Performance with Java 11

- CONTRIBUTING.adoc
- README.adoc
Small pull request to test Pipeline steps doc generator.
> Minor phrasing and formatting improvements

- content/doc/administration/requirements/java.adoc
Attempt at making this clearer, unsure how successful I was.
I also removed explicit mention of swarm and docker-workflow plugins as documented in comments.
> Rephrase Java version requirements for Maven Plugin etc.

- content/projects/gsoc/2022/projects/pipeline-step-documentation-generator.adoc
> Update Pipeline steps project page

- content/doc/developer/testing/index.adoc
website change from https://htmlunit.sourceforge.net/ to https://htmlunit.sourceforge.io/
> changed .net to .io for https://htmlunit.sourceforge.io/

- content/blog/2022/09/2022-09-14-create-iOS-unity-build-pipelines-on-AWS-with-Jenkins-and-EC2-Mac-instances.adoc
This is my attempt at getting a blog post with a collapsible source code part.
That's the very same post as the PR #5445 .
This is for the sake of clarity.
> fix(blog) First try at getting collapsible source code.

- content/blog/2022/09/2022-09-14-create-iOS-unity-build-pipelines-on-AWS-with-Jenkins-and-EC2-Mac-instances.adoc
Added links to the contributor summit and DevOps World
> Added links

- content/doc/book/blueocean/dashboard.adoc
Review and update the blue ocean dashboard page for better readability
> [DOCS-5907] Updating blue ocean dashboard page

- content/doc/book/installing/_docker-for-tutorials.adoc
- content/doc/book/installing/_docker.adoc
Blue ocean and docker workflow plugins have been updated.
> Use latest blue ocean and docker workflow plugins in tutorial

- content/blog/2022/09/2022-09-15-preptember.adoc
Correct GitHub capitalization in Hacktoberfest blog
> Fix GitHub capitalization

- content/doc/administration/requirements/java.adoc
Updating title case based on latest comments here https://github.com/jenkins-infra/jenkins.io/pull/5409
> Java 8 - fixed case for admonition title

- content/doc/developer/tutorial-improve/move-description-to-index.adoc
* one paragraph landed here from the translation conversion => deleted
* I think it's useful to briefly explain why should maintainers add a description
* link to https://issues.jenkins.io/browse/JENKINS-68300 which collects description related issues
> Add information re plugin description moving

- .gitpod.yml
This pull request fine tunes the Gitpod configuration by clearly differentiating the "init" command and the "run" command.
> Gitpod configuration update

- content/_data/indexpage/carousel.yml
- content/events/devops-world/index.adoc
Fixup of https://github.com/jenkins-infra/jenkins.io/pull/5482
> fix: correct DW banner filename

- content/security/plugins.adoc
Downstream of https://github.com/jenkins-infra/update-center2/pull/644
> Note newly suspended plugins

- content/doc/book/scaling/_chapter.yml
This change was made to help solve the issue #5434
> Move hardware recommendations after architecting for scale

- content/doc/book/managing/system-properties.adoc
https://github.com/jenkinsci/jenkins/pull/5606
> Document removal of `hudson.Util.useNativeChmodAndMode`

- content/stylesheets/abstracts/_theme.scss
Fixes #5516 and #5466
CC @janfaracik @daniel-beck @MarkEWaite
> Revert background to white

- content/doc/book/installing/kubernetes.adoc
just tried to make it user friendly! :)
> Guide minikube users to community forum for issues

- content/_layouts/post.html.haml
> Fix anchor selector for blog posts

- content/doc/developer/tutorial/create.adoc
Fixes https://github.com/jenkins-infra/jenkins.io/issues/5467
> Update create a plugin tutorial to use latest archetype version

- Gemfile
- Gemfile.lock
- content/_config/site.yml
- content/doc/pipeline/examples.html.haml
- content/stylesheets/components/_all.scss
- content/stylesheets/components/_code-highlight.scss
- content/stylesheets/pages/_post.scss
Rouge is more up-to-date and more popular than Coderay. The CSS colors come from [the github theme](https://github.com/rouge-ruby/rouge/blob/master/lib/rouge/themes/github.rb).
Fixes #3665
> Use Rouge as syntax highlighter

- content/_ext/activenav.rb
> Do not add / to anchor links

- content/doc/tutorials/build-a-python-app-with-pyinstaller.adoc
This fix was made in reference to #3251
> Fixed a text in build-a-python-app-with-pyinstaller.adoc

- content/doc/developer/publishing/documentation.adoc
Keep consistent with the preceding and following lines.
> typo fix: Load --> Loads

- content/doc/administration/requirements/linux.adoc
This is a possible solution for solving #5561
> Changed the redirect link in linux.adoc

- content/doc/developer/security/csp.adoc
- content/doc/developer/views/index.adoc
https://deploy-preview-5556--jenkins-io-site-pr.netlify.app/doc/developer/security/csp/
https://deploy-preview-5556--jenkins-io-site-pr.netlify.app/doc/developer/views/
> Improve CSP docs

- content/doc/developer/publishing/requesting-hosting.adoc
> Changed the redirect link for `plugins site` in requesting-hosting.adoc

- content/doc/book/pipeline/jenkinsfile.adoc
#5490 Added  a youtube link after the "Using Credentials" page link in "Using JenkinsFile" page
@MarkEWaite . Please review this change.
> Added youtube link

- content/doc/book/installing/windows.adoc
> Add troubleshooting steps for missing Local Security Policy on Windows Home

- content/blog/2020/03/2020-03-17-ui-plugins.adoc
> Updated broken link

- content/blog/2019/12/2019-12-16-board-election-results.adoc
https://github.com/olivergondza is the right github user
> Updated broken link for github olivergondza

- content/blog/2016/2016-05-12-sf-jam-jenkins-and-azure.adoc
https://developer.microsoft.com/en-us/reactor/ is the right link
> updated link to microsoft reactor space

- content/doc/developer/publishing/releasing-cd.adoc
More example commands instead of prose.
Tested on https://github.com/jenkinsci/pipeline-build-step-plugin/pull/100.
> Updated CD setup instructions

- content/doc/developer/tutorial-improve/automate-dependency-update-checks.adoc
add information on the maintainer.
> chore(reviewers): use github handle as reviewer name

- content/doc/book/pipeline/syntax.adoc
From https://github.com/jenkins-infra/jenkins.io/issues/4123.
> Pipeline syntax page -- correct options description

- content/doc/developer/building/intellij.adoc
to address https://github.com/jenkins-infra/jenkins.io/issues/4777 and https://github.com/jenkins-infra/jenkins.io/issues/4407
> add minimum apache maven info to IntelliJ setup

- content/security/reporting.adoc
To ease https://github.com/jenkins-infra/.github/pull/21
@dduportal WDYT? :)
> Adding details about infra vulnerabilities

- content/_data/changelogs/weekly.yml
Updating weekly release changelog to correct list order and issue types
> Jenkins 2.374 - updating weekly changelog

- content/projects/gsoc/2022/projects/automatic-git-cache-maintenance.adoc
> Update Git Cache Maintenance Blog page

- content/doc/developer/architecture/extensions.adoc
I have put links to other extension documentation. The text is mostly copied from the first link.
> Updated the extensions section

- content/project/board-election-process.adoc
This is a pull request specifically for updating some of the formatting in the Election Process page. Content will be updated in a separate pull.
> Jenkins- Update formatting for election process page

- content/doc/book/blueocean/index.adoc
Fixes #5432.
1. Edited the Intro to Blue Ocean to reflect its new status. 
2. Also, rewrote the text which implied that Blue Ocean is the gateway to the future.
3. Removed all references to the Classic UI which is considered deprecated. 
This PR is intended to be for Hacktoberfest which will conclude towards the end of October. If this PR is accepted, please add the `hacktoberfest-accepted` label after reviewing.
> Edit intro to Blue Ocean to reflect new status

- content/projects/infrastructure/ircbot.adoc
cc @timja 
Context https://github.com/jenkins-infra/ircbot/pull/152/
> Document IRC bot team removal

- content/blog/2016/2016-02-06-scale14x-conference-report.adoc
> Update link to artwork

- content/security/cna.adoc
> Update link to Log4J blog

- content/doc/book/blueocean/creating-pipelines.adoc
updated text to be more in line with Ascii formatting, and cleaned up overall content of page
> Jenkins - updating Blue Ocean "Creating Pipelines"  text

- content/project/governance.adoc
When I read it I was a bit surprised by the example :)
> More inclusive wording

- Jenkinsfile_k8s
Will avoid failing all builds while waiting for  https://github.com/jenkins-infra/pipeline-library/pull/510 to be merged
> chore: temporary remove `Deploy to preview site` stage

- content/projects/gsoc/2022/project-ideas/automating-plugin-buildmetadata-updates.adoc
Initial heading was preceded by a space character
> Make headings visible in project idea

- content/doc/developer/tutorial/prepare.adoc
Link for downloading Maven is updated from Welcome page to Download page of Apache Maven
> Link Updated: Apache Maven Website

- content/doc/pipeline/tour/running-multiple-steps.adoc
Adding the video about using the retry call in to the pipeline tour
> Jenkins - Add retry video to "Running Multiple Steps" tour page

- content/security/plugins.adoc
Anticipating https://github.com/jenkins-infra/update-center2/pull/658 in the commented out part.
> Document 2022-11-15 suspensions (advisory and otherwise)

- content/_data/indexpage/carousel.yml
The intro needs improvements, feedbacks are welcome!
> Add Jenkins Elections 2022 to jumbotron

- content/doc/developer/tutorial/create.adoc
https://github.com/jenkinsci/archetypes/releases/tag/archetypes-1.15 is the recent release.
> Use archteype 1.15 in new plugin tutorial

- content/projects/gsoc/2023/project-ideas.html.haml
- content/projects/gsoc/index.adoc
This Pull Request proposes the changes to the main GSoC page that are required to start a new year.
> Update GSoC main page for 2023

- content/projects/gsoc/index.adoc
updated number of weeks of program and including students as candidates
> Clarify GSoC duration and participation rules

- content/events/hacktoberfest.adoc
We can add the block again next year when it starts again
> Remove info block because Hacktoberfest is complete

- content/security/advisory/2022-10-19.adoc
There's only one vulnerability (probably bad copy & paste from earlier entries of this nature that had multiple plugins).
> Fix grammar

- content/_data/changelogs/weekly.yml
There was an entry in the weekly changelog with the incorrect formatting for an author, so this PR is to update the author correctly
> Jenkins 2.379 - update author info

- content/blog/2022/11/2022-11-23-get-prepared-for-gsoc.adoc
Advise for potential GSoC candidates.
> Blog post on efficient GSoC preparation

- content/css/jenkins.css
Fixes #5727 
@daniel-beck thanks for reporting this!
> Right-align changelog legend

- content/doc/developer/publishing/continuous-integration.adoc
- content/doc/developer/tutorial-improve/add-a-jenkinsfile.adoc
Reverts jenkins-infra/jenkins.io#5731
> Revert "Default to k8s for agent selection in tutorials"

- content/doc/book/managing/script-console.adoc
since JEP-223 the permision isued is Administer not RUN_SCRIPTS,
https://github.com/jenkinsci/jenkins/blob/ad5ad25998bae0fae512c083479cc354dd0bb136/core/src/main/java/jenkins/model/Jenkins.java#L4724
> RUN_SCRIPTS is no longer used

- content/_data/changelogs/lts.yml
Describe the null pointer exception fix in user terms rather than developer terms.
> Minor 2.375.1 changelog phrasing improvement

- content/doc/developer/testing/index.adoc
Something I lacked recently, so adding some tips
> Document how to use agents in tests

- content/_data/changelogs/lts.yml
https://issues.jenkins.io/browse/JENKINS-70020
https://issues.jenkins.io/browse/JENKINS-69509
> Add Winstone 6.5 and 6.6 to 2.375.1 changelog

- content/_data/authors/gsoc.adoc
- content/projects/gsoc/2022/index.adoc
- content/projects/gsoc/2023/project-ideas/JCasC-drift-detector.adoc
- content/projects/gsoc/2023/project-ideas/add-probes-to-plugin-health-score.adoc
- content/projects/gsoc/2023/project-ideas/alternative-jenkinsio-build-tool.adoc
- content/projects/gsoc/2023/project-ideas/automating-plugin-buildmetadata-updates.adoc
- content/projects/gsoc/2023/project-ideas/buiilding-android-app.adoc
- content/projects/gsoc/2023/project-ideas/buiilding-ios-app.adoc
- content/projects/gsoc/2023/project-ideas/docker-compose-build.adoc
- content/projects/gsoc/2023/project-ideas/screenshot-automation.adoc
- content/projects/gsoc/index.adoc
- content/projects/gsoc/proposing-project-ideas.adoc
Pull request with
- miscellaneous corrections
- addition of project ideas
> Update GSoC project ideas for 2023

- content/doc/developer/publishing/continuous-integration.adoc
- content/doc/developer/tutorial-improve/add-a-jenkinsfile.adoc
follow up from [https://github.com/jenkins-infra/jenkins.io/issues/5773](issue 5773) where the `Jenkinsfile` configuration text needs to be updated to be aligned with the pom-4.52 release.
> Jenkins - Updating Jenkinsfile configuration sample

- content/blog/2022/11/2022-11-24-jenkins-sponsor-appreciation.adoc
This is a small update to reduce the size of the cloudbees logo present in the blog post, to make sure that it is closer to the same proportions of the other logos.
> Jenkins - Update to CloudBees logo in thanksgiving blog post

- content/blog/2020/01/2020-01-29-gsoc-report.adoc
- content/doc/book/system-administration/backing-up.adoc
Links to previous.cloudbees.com do not work.  Point to links that seem reasonable.
> Fix 3 broken links

- content/doc/developer/crowdin/crowdin-integration.adoc
Ref: https://github.com/jenkins-infra/helpdesk/pull/3236
cc @daniel-beck
> fix: correct helpdesk issue link in crowdin-integration.adoc

- content/doc/developer/plugin-governance/managing-permissions.adoc
Ref: https://github.com/jenkins-infra/helpdesk/pull/3236
cc @daniel-beck
> fix: correct helpdesk issue link in managing-permissions.adoc

- content/_data/roadmap/roadmap.yml
- content/events/hacktoberfest.adoc
Also adds this year's recap post to the event page, the year's almost over ;)
> Move Hacktoberfest 2022 to completed on roadmap

- renovate.json
Let renovate maintain and manage dependency updates. I requested the installation of renovate on this repository.
Closes https://github.com/jenkins-infra/jenkins.io/pull/5797
> Manage dependencies with renovate

- content/projects/gsoc/2023/project-ideas/add-probes-to-plugin-health-score.adoc
First draft of the Plugin Health Score.
@alecharp please have a look at the file and make changes if needed.
> feat(documentation) Moves Plugin Health Score to "Published"

- content/security/advisory/2019-01-28.adoc
Modification after an email from "Man Shum" in the CERT ML.
> Change Man Shum credit as requested

- content/projects/gsoc/2023/project-ideas/agent_reconnections_exponential_backoff.adoc
Promoting GSoC project idea from discussion to draft status.
> Adding agent_reconnection_exponential_backoff project as draft

- content/projects/gsoc/2023/project-ideas/buiilding-android-app.adoc
- content/projects/gsoc/2023/project-ideas/buiilding-ios-app.adoc
Promoting "building andoid/IOS applications with Jenkins" GSoC Project Ideas from `discussion` to `draft`.
> Promoting GSoC project from "discussion" to "draft"

- content/doc/developer/publishing/continuous-integration.adoc
> updated the title for better search results

- content/_data/authors/lovakush.adoc
> Add lovakush.adoc

- content/_partials/connect-links.html.haml
- content/sigs/index.html.haml
Fixup to https://github.com/jenkins-infra/jenkins.io/pull/5868, I used to the wrong URL.
> Fix mailing list linking

- content/solutions/php.adoc
A further update to the PHP solution to fix the introduction paragraphs I left in from the previous guide, which upon re-reading didn't actually make sense.
> PHP Solution: Fix non-sensical introduction paragraph

- content/doc/tutorials/kubernetes/installing-jenkins-on-kubernetes/jenkins-volume.yaml
Here miss the definition of "jenkins-pv" storageClass
> Define jenkins-pv storageClass

- content/doc/book/installing/windows.adoc
Fix #5901 
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
> fix: image and text disposition on https://www.jenkins.io/doc/book/installing/windows/

- content/doc/book/pipeline/docker.adoc
> Fix example node version from docker agent docs

- content/doc/developer/security/xss-prevention.adoc
Code was missing a end bracket
> Missing a close bracket

- content/_data/indexpage/supporters.yml
> Remove Dead link in sponsors block

- content/projects/gsoc/2023/project-ideas/displaying_plugin_health_scores.adoc
Adding a GSoC project idea as a discussion in the GSoC 2023 project list.
> add "plugin health score display" GSoC project idea

- content/projects/gsoc/2023/project-ideas/add-probes-to-plugin-health-score.adoc
- content/projects/gsoc/2023/project-ideas/displaying_plugin_health_scores.adoc
There are currently two ideas around the Plugin Health Scoring project which I would like to be listed as mentor.
> Adds myself as mentor on Plugin Health Scoring related GSoC idea

- content/projects/gsoc/2023/project-ideas/alternative-jenkinsio-build-tool.adoc
I know there is already a lot of interest in this project, but was hoping to add myself as a mentor on this project. I would like to help as much as I can and provide guidance. I would also like to increase my site development skills.
> Adding myself as a mentor for Alternative build options for Jenkins project

- content/doc/book/pipeline/syntax.adoc
> Pipeline Syntax page - Document that parameters become environment variables

- content/_data/authors/markewaite.adoc
Included some items purely as comments because I want to highlight the "Improve a Plugin" tutorial as a way to invite new contributors.
> Update markewaite bio

- content/projects/gsoc/2023/project-ideas/agent_reconnections_exponential_backoff.adoc
This PR fixes the announced project size to a more realistic one seen the complexity (as mentioned in the text).
> [GSoC] fix project size of "exponential" project idea

- content/doc/developer/tutorial/create.adoc
- fix the list of available versions
- fix the selected version
> Update plugin archetype version

- content/sigs/platform/index.adoc
Also other minor updates
@gounthar I'd like your review on the updates
> Update Platform SIG meeting date/time

- content/_data/authors/sbostandoust.adoc
- content/projects/gsoc/2023/project-ideas/JCasC-drift-detector.adoc
- content/projects/gsoc/2023/project-ideas/add-probes-to-plugin-health-score.adoc
- content/projects/gsoc/2023/project-ideas/alternative-jenkinsio-build-tool.adoc
- content/projects/gsoc/2023/project-ideas/buiilding-android-app.adoc
- content/projects/gsoc/2023/project-ideas/buiilding-ios-app.adoc
- content/projects/gsoc/2023/project-ideas/docker-compose-build.adoc
- content/projects/gsoc/2023/project-ideas/gitlab-plugin-modernization.adoc
This PR updates GSoC project ideas with the names of those that volunteered or mentioned an interest in mentoring a project
> [GSoC] Mentor volunteers update

- content/doc/developer/plugin-governance/adopt-a-plugin.adoc
The acronym is used further down without being introduced before, so I think this is useful (even not considering widespread use across the project).
Lazy branch, please delete on merge.
> Introduce RPU acronym

- content/blog/2023/02/2023-02-01-gsoc-update.adoc
This PR creates a new blog post to explain the next GSoC phase: the proposal redaction phase.
> [Blog] GSoC new phase announcement

- content/projects/gsoc/2023/project-ideas/plugin-installation-manager-tool.adoc
Mark Waite and Kris Stern worked this during Docs Office Hours (Asia)
> Improve plugin install mgr tool idea

- content/chat.adoc
https://github.com/jenkins-infra/jenkins.io/pull/6028/files#r1103879526
> Restore jenkins-ci.org on chat page

- content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-nginx.adoc
- Remove duplicated line (mistake in previous commit)
- Add nginx reverse proxy video
> Add Nginx reverse proxy video

- content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-haproxy.adoc
Also removes a horizontal scroll bar from the example
- Add HAproxy reverse proxy video
- Format example without horizontal scrolling
> Add HAproxy reverse proxy video

- content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-apache.adoc
Video shows the configuration of a reverse proxy with mod_proxy, the first section of the page.
> Add Apache reverse proxy video

- content/blog/2019/05/2019-05-11-docs-sig-announcement.adoc
corrected this item from the list:  Jenkins X documentation site
> fixing broken link #12 from issue #3335

- content/blog/2022/06/2022-06-28-require-java-11.adoc
> Fix link syntax

- CONTRIBUTING.adoc
- Makefile
`pdfs` is not a `make` target, but it is still mentioned in [CONTRIBUTING.md](https://github.com/jenkins-infra/jenkins.io/blob/master/CONTRIBUTING.adoc#make-targets).
> pdfs is not a make target

- content/_data/authors/aheritier.adoc
- content/blog/2010/2010-07-12-updated-chrome-extension.adoc
- content/blog/2010/2010-07-13-monitor-hudson-from-your-android.adoc
- content/blog/2010/2010-07-28-hosting-your-hudson-plugin-at-github.adoc
- content/blog/2010/2010-08-16-hudsonmobi-2-0-hits-the-android-market.adoc
- content/blog/2010/2010-09-05-hudsonmobi-dons-a-black-turtleneck-and-jumps-to-ios4.adoc
- content/blog/2010/2010-09-09-lets-talk-about-hudson-at-javaone.adoc
- content/blog/2018/04/2018-04-18-blueocean-1-5-0.adoc
- content/blog/2019/02/2019-02-06-ssh-steps-for-jenkins-pipeline.adoc
- content/blog/2019/08/2019-08-25-jenkinsworld-contrib-summit-ask-the-expert-booth.adoc
- content/blog/2022/12/2022-12-09-jfrog-maintenance.adoc
- content/doc/book/pipeline/multibranch.adoc
- content/doc/developer/security/remoting-callables.adoc
- content/merchandise.adoc
- content/project/governance-meeting/archives/2017.adoc
- content/security/advisory/2015-11-11.adoc
This is a follow-up to https://github.com/jenkins-infra/jenkins.io/pull/6084 with the manual fixes mentioned.
> Manual fixup of hard link cleanup

- content/_data/indexpage/carousel.yml
Removes outdated information from the carousel (aka jumbotron)
> Removing election notification from carousel

- content/doc/administration/requirements/java.adoc
This is a draft change prepared to help solve #6016 
I hope this is something similar to what is expected. Please guide me through any changes needed. I can add links where required
> Describe Temurin preference of the Jenkins project

- content/doc/developer/plugin-development/plugin-release-tips.adoc
This PR fixes an invalid link to the CD for plugins
> fix(Developer Documentation - Plugin Release Tips) correct invalid link to CD

- content/doc/developer/internationalization/i18n-jelly-views.adoc
Extend the documentation to html files
> Extend the documentation to html files

- content/_data/changelogs/lts.yml
- content/_data/changelogs/weekly.yml
- content/blog/2021/12/2021-12-22-deprecated-ruby-runtime.adoc
- content/blog/2022/10/2022-10-03-scaling-out-iOS-builds-on-AWS-with-EC2-mac.adoc
- content/doc/book/managing/spawning-processes.adoc
Related to #3335 
Description:
This PR fixes some of the broken links on https://jenkins.io page
> [Bug] - Fixed Broken Links

- content/templates/updates.adoc
Downstream of https://github.com/jenkins-infra/update-center2/pull/690.
> Change link title

- content/press.adoc
We do have a SPoC left. Hence I recommend we reword the header of the page.
> Reword press page header

- content/_data/authors/BlueDragn.adoc
- content/press.adoc
Making changes to the file "press.adoc" in About section . Although it is not as exactly as asked for but in my opinion better than the current version.I Will try to improve it more.
Fixes https://github.com/jenkins-infra/jenkins.io/issues/6148
> adding blockqoute inside About section

- content/projects/gsoc/2023/project-ideas/alternative-jenkinsio-build-tool.adoc
I am submitting this pull request to remove myself from the list of mentors on this project. I have already discussed this decision with @jmMeessen and @MarkEWaite, and plan to still be available to assist with GSoC in any way that I can.
> GSoC alternative build tools for jenkins.io - removing myself from mentors

- content/doc/administration/requirements/upgrade-java-guidelines.adoc
- content/doc/book/blueocean/creating-pipelines.adoc
**This PR makes the following changes**
* Fixes #6145
Changes in the page's contents have been made but the embedded video may contain different steps.
> Made changes to 'Upgrading Jenkins' documentation

- content/stylesheets/pages/_blog.scss
Fixes #6192 
I just added flex-wrap to the authors class
and it's responsive according to the div size which makes it responsive on phones
@zbynek
> adding flex-wrap to the attrs class

- content/download/verify.adoc
Ref https://github.com/jenkins-infra/helpdesk/issues/3457
> Update GPG key on verification page

- content/_partials/pagination.html.haml
- content/stylesheets/core/_link.scss
Closes #6190 
This should close those, the old PR, and the issue
@NotMyFault Thanks for the help
> Remove pagination links from blog entry of same page

- content/_data/changelogs/lts.yml
Thanks to FredG for reporting it at https://groups.google.com/g/jenkinsci-dev/c/PmZw-7jISZE/m/1oSfpwF-CQAJ
> Fix 2.387.2 release date

- content/_data/authors/oleg_nenashev.adoc
Subj, as announced at the governance meeting on April 03
> Update Bio and affiliation of @oleg-nenashev

- content/_data/changelogs/_STYLEGUIDE.adoc
https://github.com/jenkins-infra/jenkins.io/pull/6274#discussion_r1162145566
See also https://github.com/jenkinsci/jenkins/pull/6313
> Clarify verb usage in style guide

- content/security/for-maintainers.adoc
> Add missing punctuation

- content/security/for-maintainers.adoc
> Backticks are deadkeys on my keyboard :-(

- content/artwork/index.html.haml
- content/merchandise.adoc
Using the HeroForge website, I defined a 3D model for Mr. Jenkins.
I hope you approve.
> HeroForge 3D model

- content/projects/gsoc/2023/project-ideas/plugin-installation-manager-tool.adoc
Email to Mark Waite, Freyam Mehta, and Mostafa Ashraf
> abhyudayasharma not available as GSoC 2023 mentor

- content/_partials/toptoolbar.html.haml
- content/css/jenkins.css
- content/stylesheets/base/_display.scss
- content/stylesheets/core/_base.scss
Reverts jenkins-infra/jenkins.io#6217
Fixes https://github.com/jenkins-infra/plugin-site/issues/1338
Before merging let's make sure it works with all websites.
> Revert "Revert "fixing footer, to resides at the end of the page""

- content/events/hacktoberfest.adoc
> Update core languages on Hacktoberfest page

- content/stylesheets/abstracts/_breakpoints.scss
Closes #6317. 
Added some media queries for the `.app-avatar` class.
> Fix aspect ratio of avatars for mobile

- content/stylesheets/abstracts/_breakpoints.scss
Reverts jenkins-infra/jenkins.io#6324 based on discussion in comments
> Revert "Fix aspect ratio of avatars for mobile"

- CONTRIBUTING.adoc
Fixes https://github.com/jenkins-infra/jenkins.io/issues/6292
> Fix gitter URLs in contributing.adoc

- STYLEGUIDE.adoc
- content/doc/book/pipeline/docker.adoc
- content/doc/pipeline/tour/agents.adoc
- content/doc/pipeline/tour/hello-world.adoc
NodeJS 18 is the current LTS version
> Use node:18.16.0-alpine in examples

- content/css/jenkins.css
Fixes the aspect ratio of images in the carousel and images in blog posts 
Fixes issue #6316
> Fix aspect ratio of images

- content/doc/developer/publishing/requesting-hosting.adoc
Minor change rewording who reviews new hosting requests, there's a dedicated team for that.
> Reword plugin hosting request reviewers

- content/_partials/projectcarousel.html.haml
A small QoL improvement to make images clickable. This is beneficial for mobile users and everyone who is used to big images to click on :)
> Make carousel image clickable

- content/doc/book/scaling/architecting-for-manageability.adoc
Updated number of plugins to be consistent with https://plugins.jenkins.io/
> Updated number of plugins to be consistent

- content/blog/2023/05/18/2023-05-18-harsh-ps-2003-introduction-blog-post.adoc
Adding GSoC 2023 contributor introduction blog post for "GitLab Plugin Modernization" project.
> Add GSoC contributor blog post

- LICENSE.adoc
Atribution-ShareAlike 4.0 -> Attribution-ShareAlike 4.0
> Fix typo in license and update by-sa banner

- content/doc/administration/requirements/windows.adoc
We don't support Windows versions that are not supported by Microsoft
Mention Windows 11, it is my primary OS and is the primary OS shipped on many desktop computers
> Clarify Windows support policy

- content/doc/book/blueocean/dashboard.adoc
> Fix minor typo in blueocean/dashboard.adoc

- content/download/index.html.haml
Fix archlinux distribution URL.
> Fix archlinux distribution URL

- content/doc/developer/publishing/releasing-cd.adoc
Complements https://github.com/jenkins-infra/repository-permissions-updater/pull/3356
> Document CD PR part

- .github/workflows/label-conflicting-prs.yml
https://github.com/jenkins-infra/jenkins.io/pull/6458 didn't work, sorry
> Fix changelog updating bot name

- content/security/advisory/2023-06-14.adoc
One bypasses protections, not the vulnerability.
> Rephrase for clarity

- content/blog/2023/06/22/2023-06-22-mirrors-jenkins-new-IP.adoc
Related to https://github.com/jenkins-infra/helpdesk/issues/3351#issuecomment-1603086577
> Add a blog post for Jenkins Mirrors IP change

- .typos.toml
Fixes https://github.com/jenkins-infra/jenkins.io/issues/6467
> Fix check-typos false positive

- content/doc/book/system-administration/backing-up.adoc
> Fix error in command line example

- content/security/for-maintainers.adoc
Noticed random end bracket whilst reading. Documentation only change.
> Remove random end bracket

- content/_partials/downloadbanner.html.haml
#6584 recommends that we change from the International Committee of the Red Cross to the Ukrainian Red Cross.
Governance board meeting 21 Aug 2023 agreed with the proposal and assigned Mark Waite the action item to submit a pull request making the change.
Board members will be mentioned in the pull request so that they can comment on the pull request.
Oleg has already stated his approval in the [GitHub issue](https://github.com/jenkins-infra/jenkins.io/issues/6584#issuecomment-1672697329).  Mark Waite and Alexander Brandes approved in the board meeting 21 Aug 2023.
> Recommend Ukrainian Red Cross for relief donations

- content/blog/2023/08/24/2023-08-24-gitlab-plugin-modernization-report.adoc
Added missing link to Pull Request
> Added missing link to Pull Request

- content/blog/2022/11/2022-11-24-jenkins-sponsor-appreciation.adoc
> Correct a single spelling error for fastly

- content/_data/indexpage/carousel.yml
- content/blog/2023/09/18/2023-09-18-board-officer-election-announcement.adoc
- content/images/governance/elections/2023/2023-announcement-opengraph.svg
🚫 **Don't merge this PR.**
I'm looking for some feedback before publishing the post next week :)
> Publish election announcement 2023

- content/events/hacktoberfest.adoc
A typo prevented correct rendering of deatured project.
> Fix small typo in Hacktoberfest event page

- content/blog/2023/09/20/2023-09-20-Hacktoberfest-2023.adoc
This PR is to add punctuation to one line of the Hacktoberfest blog post, and adjust phrasing on another line. These are both minor fixes to ensure consistency across the blog post  and documentation.
> jenkins.io - two small fixes in hacktoberfest blog

- content/sigs/docs/gsod/index.adoc
- content/sigs/docs/index.adoc
> Move Asia docs office hours 30 minutes earlier

- content/doc/book/managing/system-properties.adoc
Introduced but undocumented in https://github.com/jenkinsci/branch-api-plugin/pull/249
> Document a Branch API plugin flag.

- content/security/reporting.adoc
> Add infra-related non-issues that should not be reported

- content/security/reporting.adoc
Sometimes there's just no need to
> Clarify that we don't always forward these

- content/blog/2023/05/12/2023-05-12-removing-prototype-from-jenkins.adoc
During working on prototype js removal we identified several script misses and want let you know about them.
It might be worth including updated script to the article.
> script update for prototype js removal

- content/security/advisory/2022-07-27.adoc
The token authorizes, it does not authenticate.
> Rephrase fix for SECURITY-284

- content/doc/developer/security/misc.adoc
As mentioned in https://github.com/jenkins-infra/jenkins.io/pull/6689#pullrequestreview-1643763451, I'm adding documentation to explain how secrets should be logged.
> Add documentation regarding logging secrets

- content/doc/book/pipeline/index.adoc
Howdy!
I'm a technical editor by education, so I figured as I learn how to use Jenkins, I'd send in some suggestions.
Thanks!
> Improve Pipeline landing page

- Jenkinsfile
Reverts jenkins-infra/jenkins.io#6677
See https://github.com/jenkins-infra/helpdesk/issues/3360#issuecomment-1790899357
> Revert "Delete obsolete files on deploy"

- content/blog/2023/11/2023-11-06-introducing-2-2-2-java-support-plan.adoc
It occurs to me that the last time I wrote a blog post about this, some people were confused about this point. So might as well add a clarification so that this is absolutely clear.
> Add clarification to Java platform blog post

- content/doc/developer/tutorial/create.adoc
The example shows the selected version very well,  no need to keep it in the preceding paragraph\
Closes #6834
> Remove version specific detail from text

- content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-nginx.adoc
> Remove clear of proxy set header connection

- content/doc/book/managing/system-properties.adoc
https://github.com/jenkinsci/jenkins/pull/3838/files#diff-af42eaf048ba2879a2344c356cb7fb342a52011d199e859befcd6b29898ac9f9L34-L35
Untested, origin lazy-branch.
> Document obsolescence of jenkins.CLI.disabled flag

- content/security/advisory/2023-09-06.adoc
> Note CVE-2023-4777 for SECURITY-3018

- content/_data/upgrades/2-426-1.adoc
Prototype.js linked to the wrong issue.
> Fix link to Prototype epic, update plugins with known issues

- content/security/plugins.adoc
SECURITY-1025 was fixed, plugin was released. Suspension PR was merged.
> Update plugins.adoc - remove batch-task

- content/doc/book/security/controller-isolation.adoc
- content/redirect/distributed-builds.adoc
> Redirect distributed-builds to "Architecting for Scale"

- content/_data/authors/jonesbusy.adoc
- content/projects/gsoc/2024/project-ideas/adding-additional-probes-to-plugin-health-score.adoc
- content/projects/gsoc/2024/project-ideas/plugin-installation-manager-tool.adoc
- content/projects/gsoc/2024/project-ideas/using-bearer-token-authentication-for-the-git-plugin-and-git-client-plugin.adoc
- content/projects/gsoc/2024/project-ideas/using-openrewrite-recipes-for-plugin-modernization-or-automation-plugin-build-metadata-updates.adoc
As mentioned on discourse by @krisstern
> Add myself as possible mentor

- content/projects/gsoc/2024/project-ideas/implementing-ui-for-jenkins-infra-statistics.adoc
- content/projects/gsoc/2024/project-ideas/using-opentelemetry-for-jenkins-jobs-on-ci_jenkins_io.adoc
Adding myself as a potential mentor for the following projects
- [Implementing UI for Jenkins Infra Statistics](https://www.jenkins.io/projects/gsoc/2024/project-ideas/implementing-ui-for-jenkins-infra-statistics/)
- [Using OpenTelemetry for Jenkins Jobs on ci.jenkins.io](https://www.jenkins.io/projects/gsoc/2024/project-ideas/using-opentelemetry-for-jenkins-jobs-on-ci_jenkins_io/)
Thank You for considering me!
> Add myself as a potential mentor

- content/doc/book/pipeline/jenkinsfile.adoc
- content/doc/developer/plugin-development/build-process.adoc
- Render footnote correctly
- Minor grammar fix
> fix minor grammar error

- content/security/cna.adoc
@Kevin-CB @yaroslavafenkin @daniel-beck Review desired to ensure it's aligned with reality :)
> Add details for CNA in terms of coordination

- content/doc/book/managing/plugins.adoc
Issue: #6623 
Added a method to list installed plugins and their version.
> Describe how to list installed plugins and their versions

- Gemfile
- Gemfile.lock
Fixes #6695 via https://github.com/awestruct/awestruct/pull/568
> Update awestruct to 0.6.7

- content/security/for-administrators.adoc
We updated the model we use for scoring since several months, the doc was forgotten
> Update doc for CVSS 3.0 => 3.1

- content/projects/gsoc/2024/project-ideas/using-opentelemetry-for-jenkins-jobs-on-ci_jenkins_io.adoc
Adding myself as a mentor to help with the infrastructure part inherent to this project.
> Adding myself as a mentor for OpenTelemetry GSoC project

- content/doc/developer/plugin-governance/deprecating-or-removing-plugin.adoc
The change proposed outlines how to archive a repository if a plugin is end of life or considered superseded.
> Update plugin deprecation page

- content/blog/2024/01/25/2024-01-25-jenkins-2023-recap.adoc
> Remove 2022 recap link from 2023 recap blog post

- content/doc/book/security/managing-security.adoc
crowd2 is not available anymore
> Update managing-security.adoc / remove crowd2

- content/_layouts/simplepage.html.haml
- content/participate/index.html.haml
- content/stylesheets/abstracts/_theme.scss
- content/stylesheets/core/_all.scss
- content/stylesheets/core/_container.scss
- content/stylesheets/core/_typography.scss
- content/stylesheets/pages/_all.scss
- content/stylesheets/pages/_contribute.scss
Refresh to the design of the contribute page, making it a bit more colourful and more consistent with Jenkins CI - using the same theme colours and animations etc.
**Before**
**After**
**What's changed**
* More colourful design - uses the colours from Jenkins CI
* More responsive - works better on smaller viewports
* Hit boxes are much larger now - they're the entire card
> Update the appearance of the 'Participate and contribute' page

- Jenkinsfile
Fix up for https://github.com/jenkins-infra/jenkins.io/pull/7073
-x specifies a proxy
-X specifies the request method we want to use :)
> Fix purging styles.css

- content/_layouts/simplepage.html.haml
> Add anchor to each pipeline example title

- content/doc/book/system-administration/_chapter.yml
- content/doc/book/system-administration/admin-password-reset-instructions.adoc
Closes https://github.com/jenkins-infra/jenkins.io/issues/5740.
Initiated here https://github.com/jenkins-infra/jenkins.io/pull/6242
Feel free to close this if the previous PR has been updated.
> Add Password Reset for Administrators Guide

- content/blog/2023/12/2023-12-06-jenkins-to-github.adoc
- content/blog/2023/12/2023-12-08-basil-crow-board-announcement.adoc
Fixed 2 broken links related to #3335
> Fix broken links

- content/projects/gsoc/2024/project-ideas/using-openrewrite-recipes-for-plugin-modernization-or-automation-plugin-build-metadata-updates.adoc
> feat: update GSoC 2024 OpenRewrite project idea

- Jenkinsfile
Addresses https://github.com/jenkins-infra/jenkins.io/pull/7079#discussion_r1491144950 
Write out -X in cURL in Jenkinsfile
> Write out 'curl -X' in Jenkinsfile

- content/projects/gsoc/2024/project-ideas/buiilding-ios-app.adoc
- content/projects/gsoc/2024/project-ideas/enhancing-an-existing-llm-model-with-domain-specific-jenkins-knowledge.adoc
- content/projects/gsoc/2024/project-ideas/plugin-installation-manager-tool.adoc
- content/projects/gsoc/2024/project-ideas/using-openrewrite-recipes-for-plugin-modernization-or-automation-plugin-build-metadata-updates.adoc
I think I could help as a co-mentor for a few of the projects. 🤔
> fix(documentation): Adding Bruno Verachten as a co-mentor

- content/download/index.html.haml
Fix the misaligned paragraphs in #7158 
Before: 
After:
> Fix Download page paragraphs

- content/doc/book/installing/kubernetes.adoc
> Fix YAML Indentation in Kubernetes Jenkins Deployment

- content/doc/developer/publishing/releasing-cd.adoc
Addressing https://groups.google.com/g/jenkinsci-dev/c/EqBm9AuAm-k/m/OWrHg1E3AgAJ
Downstream of https://github.com/jenkins-infra/repository-permissions-updater/pull/3852
> Document exclusive JEP-229 CD mode

- content/_data/indexpage/carousel.yml
> Remove CD Award voting banner

- content/doc/developer/publishing/continuous-integration.adoc
- content/doc/developer/security/index.adoc
- content/doc/developer/tutorial/create.adoc
- content/participate/report-issue.adoc
The change proposed fixes up some code formats I've spotted to ensure code blocks are highlighted properly.
> Apply and fixup some code block languages

- content/doc/book/installing/linux.adoc
Issue: https://github.com/jenkinsci/packaging/issues/458
> Quote to prevent glob expansion

- content/blog/2024/04/2024-04-04-gsoc-2024-contributor-application-period-concludes.adoc
Added blog post for GSoC 2024, to conclude the contributor application period.
> feat: add blog post for post google summer of code application period

- content/blog/2024/04/2024-04-04-gsoc-2024-contributor-application-period-concludes.adoc
There were a few things that I had noticed in the GSoC blog post from yesterday that I was unable to submit prior to it being merged. 
It was mostly stuff like making sure the numbers are spelled out [since they are below 10](https://learn.microsoft.com/en-us/style-guide/numbers) and a couple other small suggestions. Everything else looks good, but please let me know if there are any questions or concerns!
> Jenkins.io Blog - suggestions and updates for GSoC blog post

- content/project/governance-meeting/index.adoc
Thanks to @daniel-beck for the pointer that this needed an update.
> Link to governance meeting GitHub repository

- content/doc/developer/publishing/releasing-cd.adoc
Companion PR to jenkinsci/incrementals-tools#104, which should only be merged after that PR is merged.
> Docs changes for jenkinsci/incrementals-tools#104

- content/doc/developer/testing/index.adoc
Added examples how to run individual tests and test classes with maven on the command line
> Added examples how to run individual tests and test classes

- content/_data/changelogs/weekly.yml
Add missing entry to changelog
> Update 2.456 changelog

- .github/ISSUE_TEMPLATE/1-documentation.yml
- .github/ISSUE_TEMPLATE/3-enhancement.yml
- .github/ISSUE_TEMPLATE/4-bug.yml
This PR adds a contributing proposal field in the issue templates.
Similar to:
- https://github.com/jenkinsci/.github/pull/131
> Add a contributing nudge field in issue templates

- content/projects/gsoc/2024/projects/using-openrewrite-recipes-for-plugin-modernization-or-automation-plugin-build-metadata-updates.adoc
Add the 2024 GsoC OpenRewrite project page
Still missing some details about office hours
> Add GSoC 2024 OpenRewrite project page

- content/projects/gsoc/2024/projects/using-openrewrite-recipes-for-plugin-modernization-or-automation-plugin-build-metadata-updates.adoc
Updated the office hour timings in the project page
cc: @jonesbusy
> Update Office hours

- content/doc/book/system-administration/authenticating-scripted-clients.adoc
added typescript example to use api token
> [Update authenticating-scripted-clients.adoc] add typescript example

- content/projects/gsoc/2024/projects/using-openrewrite-recipes-for-plugin-modernization-or-automation-plugin-build-metadata-updates.adoc
Add direct link to the meeting for GSoC OpenRewrite 2024
> Add direct link to the meeting for GSoC OpenRewrite 2024

- content/doc/book/pipeline/development.adoc
From a private conversation, adding a note about the label of "Replay" which can be switched to "Rebuild".
> Add a note about the label "Replay" switched to "Rebuild" in some cases

- content/_data/roadmap/roadmap.yml
This was a due update: this PR proposes a set of changes to map to the Jenkins Infra SIG most important topic.
> feat(roadmap) Update Infrastructure top level projects

- content/security/reporting.adoc
Let's try to explicit the situation in order to reduce noise
> Explicit that external web applications are not in Jenkins scope

- content/doc/book/platform-information/support-policy-java.adoc
We don't test weekly with Java 11 any longer
> Java 11 no longer has a full test flow

- Jenkinsfile
Ref. https://github.com/jenkins-infra/helpdesk/issues/4192#issuecomment-2248366826
> chore(Jenkinsfile) increase DockerHub rate limit with authentication

- content/_data/changelogs/weekly.yml
One line is incorrectly wrapped and appears in the diffs for weekly changelog
> Fix weekly changelog entry format

- content/blog/2024/08/26/2024-08-26-gsoc-using-openrewrite-for-plugin-modernization.adoc
Final blog post for GSoC'24 project [Using OpenRewrite Recipes for Plugin Modernization](https://www.jenkins.io/projects/gsoc/2024/projects/using-openrewrite-recipes-for-plugin-modernization-or-automation-plugin-build-metadata-updates/)
cc: @jonesbusy, @gounthar, @iamrajiv, @berviantoleo
> GSoC: Add blog for Plugin Modernizer Tool

- content/blog/2024/08/25/2024-08-25-gsoc-enhancing-llm.adoc
This PR is to adjust some of the grammar, punctuation, and formatting in the LLM blog post. I have updated a few words to fit better in the context and also adjusted some case for proper nouns. There was also some trailing spaces that needed removing, so they have been taken care of as well.
> Update grammar in LLM blog post

- content/blog/2024/08/26/2024-08-26-gsoc-using-openrewrite-for-plugin-modernization.adoc
This PR is to adjust and update some of the formatting/grammar within the blog post. I also added a link to the plugin health score github repo since it is mentioned towards the end.
> Some grammar and punctuation fixes for Plugin Modernization GSoC blog

- content/blog/2024/09/04/2024-09-04-update-center-brownouts.adoc
> fix(blog) typo + add a detail about the 2 brownouts for `2024-09-04-update-center-brownouts`

- content/blog/2024/09/04/2024-09-04-update-center-brownouts.adoc
This PR is to adjust some of the grammar and punctuation of the blog post. Information has not been changed, but some grammar may have adjusted the placement of some words in the post.
> Update center brown out blog - adjusting some grammar and punctuation

- content/_data/changelogs/weekly.yml
Previous formatting does not match the automated formatting in 2 cases.
> Format weekly changelog to match automation

- content/blog/2024/09/10/2024-09-10-update-center-brownouts-3.adoc
related to https://github.com/jenkins-infra/helpdesk/issues/2649
> feat(blog): new blogpost for the uc-brownout-3

- content/doc/book/installing/_docker.adoc
- content/doc/book/installing/windows.adoc
This PR is to update a few uses of "instance" in the installing documentation. Just a few small changes to update the wording as described in https://github.com/jenkins-infra/jenkins.io/issues/7291.
> Update Installing docs usage of "instance"

- content/_data/indexpage/carousel.yml
- content/blog/2024/09/25/2024-09-25-board-officer-election-announcement.adoc
- content/images/governance/elections/2024/2024-registrations-opengraph.svg
Nominations are complete.  6 candidates are vying for 3 open positions on the Jenkins Governance Board.  2 candidates have been nominated for the Release Officers position.
> Announce Jenkins 2024 voter registration

- content/blog/2024/09/25/2024-09-25-update-center-brownouts-4.adoc
Related to https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2364054995
This PR adds a new post related to the fourth Update Center brownout.
Could you merge it as soon as possible (do not hesitate to add your own suggestions!)
> feat(blog) add a post for the 4th Update Center brownout

- content/download/index.html.haml
- content/download/lts/index.adoc
- content/events/hacktoberfest.adoc
- content/project/governance.adoc
This PR is to adjust more pages' usage of the word "instance" to be more accurate about what they are describing. There were only a few examples that needed adjustment, so I have combined a few of them in this PR. As with the others, this is part of the work to address https://github.com/jenkins-infra/jenkins.io/issues/7291
> Update Governance, Download, and Hacktoberfest use of "instance"

- content/doc/developer/blueocean-plugin-development/index.adoc
Updated the status of Blue Ocean, because it is not a new Plugin but actually deprecated.
> Updated the status of Blue Ocean

- content/_data/upgrades/2-462-3.adoc
Per https://github.com/jenkinsci/jenkins/pull/9644#issuecomment-2389232859
cc @kmartens27
> Fix 2.462.3 upgrade guide

- .github/workflows/compress-images.yaml
Automates PRs like https://github.com/jenkins-infra/jenkins.io/pull/7607, to compress images right on the PR, once added.
> Compress images on PRs

- content/_partials/downloadbanner.html.haml
See the meeting notes from the governance meeting on October 14, 2024 for the approvals of the removal.
Fixes #7544
> Remove Ukraine messaging

- content/doc/book/pipeline/index.adoc
This PR builds upon the work done in https://github.com/jenkins-infra/jenkins.io/pull/7611 to update and adjust the code examples so that they match the text/callouts outlined underneath.
> Update pipeline index code example

- content/doc/developer/forms/jelly-form-controls.adoc
Update `jelly-form-controls.adoc` to add possibility for localized help files.
> Update jelly-form-controls.adoc to add possibility for localized help files

- content/doc/developer/security/csp.adoc
Document [JENKINS-71728](https://issues.jenkins.io/browse/JENKINS-71728).
> Document FormApply#applyResponse/#showNotification

- content/_data/changelogs/weekly.yml
Changelog generator removes all dashes
> Add dashes into the formatted date of bug description

- content/doc/developer/extensibility/action-for-all-projects.adoc
- content/doc/developer/handling-requests/actions.adoc
- content/doc/developer/handling-requests/stapler-accessible-type.adoc
Use asciidoc headings instead of Markdown. Just noticed it, should not change anything
> Use asciidoc headings

- content/doc/developer/testing/index.adoc
Slightly reworked the SCM part
* moved it where I think it belongs
* adjusted the motivation a little bit with removing the freestyle reference
* at least linked to the source of the `GitSampleRepoRule`
Do you think it is useful to extend the `GitSampleRepoRule` with an example?
> Slightly reworked the SCM part

- content/doc/book/installing/offline.adoc
Previous fragment was removed in https://github.com/jenkinsci/docker/pull/1302
> Update Link fragment in offline.adoc

- content/projects/gsoc/2025/project-ideas/revamping-jenkins-io-website-success-stories-feature.adoc
Fixed typo from "accepted" to "published".
> fix(gosc): fix ravamping success stories gsoc project typo

- content/_data/indexpage/carousel.yml
This PR is to update the carousel voter tile to indicate to users that voting is now open until November 31 and change the message a bit to better fit this.
> Update voting jumbotron

- content/doc/developer/extensibility/serialization-of-anonymous-classes.adoc
As of https://github.com/jenkinsci/jenkins/pull/9921.
Also adding a missing `public` modifier to examples.
> Suggesting `ControllerToAgentFileCallable`

- content/doc/developer/publishing/releasing-cd.adoc
Follow-up of:
- https://github.com/jenkins-infra/helpdesk/issues/4387#issuecomment-2475909412
> Add a mention about interesting labels in CD troubleshooting section

- content/doc/developer/publishing/releasing-cd.adoc
Follow-up of:
- #7685 
Ref:
- https://github.com/jenkins-infra/jenkins.io/pull/7685#pullrequestreview-2435753541
> Improve the interesting label troubleshooting section of CD doc

- content/blog/2024/11/16/2024-11-16-new-update-center.adoc
Monday is 18 Nov 2024, not 17 Nov 2024
Would like review from
* @dduportal
* @gounthar
though will merge without reviews, since change is minor
> Minor correction in date mentioned in blog post

- content/projects/gsoc/2025/project-ideas/complete-alternative-jenkins-io-build-retooling.adoc
- content/projects/gsoc/2025/project-ideas/domain-specific-LLM-based-on-jenkins-usage-using-ci.jenkins.io-data.adoc
Updated the content for the "Complete build retooling of jenkins.io" project idea.
> feat(gsoc): update gsoc 2025 project ideas

- content/404.html.haml
- content/css/jenkins.css
> Fix footer position of the 404 page

- content/projects/gsoc/2025/project-ideas/complete-alternative-jenkins-io-build-retooling.adoc
This pr is to add myself as a co-mentor for the jenkins.io retooling GSoC project. I have already confirmed with @alyssat that I wish to join the project and help with the documentation content.
> Adding Kevin as co-mentor to site retooling project

- content/doc/developer/testing/index.adoc
Add section about operating system specific tests, 
after reading the old [Wiki Unit+Test+on+Windows](https://wiki.jenkins.io/display/JENKINS/Unit+Test+on+Windows)
> Add section about operating system specific tests

- content/projects/gsoc/2025/project-ideas/android-or-ios-tutorial-pages.adoc
- content/projects/gsoc/2025/project-ideas/backend-code-refactoring-for-infra-stats.adoc
- content/projects/gsoc/2025/project-ideas/complete-alternative-jenkins-io-build-retooling.adoc
- content/projects/gsoc/2025/project-ideas/domain-specific-LLM-based-on-jenkins-usage-using-ci.jenkins.io-data.adoc
- content/projects/gsoc/2025/project-ideas/further-pipeline-documentation-improvements.adoc
- content/projects/gsoc/2025/project-ideas/improving-jenkinsfile-runner-abilities-and-github-actions.adoc
- content/projects/gsoc/2025/project-ideas/plugin-modernizer-improvements.adoc
- content/projects/gsoc/2025/project-ideas/revamping-jenkins-io-website-success-stories-feature.adoc
- content/projects/gsoc/2025/project-ideas/swagger-openapi-for-jenkins-rest-api.adoc
Fixed typoes and added details to GSoC project ideas
> feat(gsoc): polish up gsoc 2025 project ideas

- content/doc/developer/building/intellij.adoc
https://github.com/jenkins-infra/jenkins.io/pull/7791#issuecomment-2567135419
> Update minimum required Maven version

- content/sigs/platform/index.adoc
Many of the topics mentioned in the SIG page as future topics have already been completed and are being actively maintained.
> Update platform SIG with latest information

- content/projects/gsoc/2025/project-ideas/plugin-modernizer-improvements.adoc
Hi,
I am interested in mentoring the project [Improving Plugin Modernizer](https://www.jenkins.io/projects/gsoc/2025/project-ideas/plugin-modernizer-improvements/) for GSoC 2025
I believe that my past GSoC contributing experience in building the [Plugin Modernizer tool](https://github.com/jenkins-infra/plugin-modernizer-tool) in GSoC 2024, along with OpenRewrite Knowledge can be a valuable addition to this project
Availability:
I am available throughout the phase of GSoC 2025
Regards,
Sridhar Sivakumar
cc: @jonesbusy, @gounthar
> Add sridamul as a potential mentor for GSoC 2025

- content/security/advisory/2025-01-22.adoc
Minor precision to the security advisory.
> Fix 2025-01-22 security advisory

- content/doc/book/scaling/architecting-for-manageability.adoc
- content/doc/developer/index.html.haml
- content/press.adoc
> Update plugin count

- content/projects/gsoc/2025/project-ideas/ai-powered-chatbot-for-quick-access-to-jenkins-resources.adoc
- content/projects/gsoc/2025/project-ideas/backend-code-refactoring-for-infra-stats.adoc
1. Moved the [Backend code refactoring for Infra Statistics](http://localhost:4242/projects/gsoc/2025/project-ideas/backend-code-refactoring-for-infra-stats/) from `draft` list to `published` list.
2. Added more details to the [AI-Powered Chatbot for Quick Access to Jenkins Resources](http://localhost:4242/projects/gsoc/2025/project-ideas/ai-powered-chatbot-for-quick-access-to-jenkins-resources/) project idea.
> feat(gsoc): update gsoc 2025 project ideas before org application

- content/doc/book/managing/system-properties.adoc
Replace old wiki links in system properties
> Replace old wiki links in system properties

- content/_data/changelogs/weekly.yml
Minor formatting change from earlier submission
> Fix formatting of earlier changelog

- content/doc/book/pipeline/multibranch.adoc
Thanks to report from the documentation feedback page.
See row 1635 of the [spreadsheet](https://docs.google.com/spreadsheets/d/1nA8xVOkyKmZ8oTYSLdwjborT0w-BpBNNZT0nxR9deZ8/edit?usp=sharing)
> Fix hyperlink to global variable reference

- content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/_section.yml
> Added missing lighttpd entry for left menu

- content/events/index.html.haml
Added custom width to the iframe of the calendar to make it accessible for mobile devices
Fixes #7956
> add responsiveness to calendar iframe to work for mobile devices

- content/merchandise.adoc
Three of these links pointed to empty or out of business shopfronts
Left the one still working since it was kind of cool
> Update merchandise.adoc - remove broken shops

- content/merchandise.adoc
Fix issue #7961 
As mentioned by @clintonsteiner in [PR](https://github.com/jenkins-infra/jenkins.io/pull/7960) about broken shops & providing active links by @MarkEWaite in [comment](https://github.com/jenkins-infra/jenkins.io/pull/7960#pullrequestreview-2666105610). I have added the respective links on merchandise.adoc
Tested Locally :
Final look of UI is like below -
Please suggest changes, if needed
> Update merchandise.adoc - Added materials to the page

- content/projects/gsoc/2025/project-ideas/domain-specific-LLM-based-on-jenkins-usage-using-ci.jenkins.io-data.adoc
Added @cnu1812 as co-mentor of the GSoC 2025 Domain-specific LLM project.
> feat(gsoc): add cnu1812 as co-mentor to GSoC 2025 domain specific LLM project

- content/doc/book/installing/kubernetes.adoc
...and suggest a way to atomically restart containers (accepting a few seconds of downtime)
Follow-up for #7958
> content/doc/book/installing/kubernetes.adoc: elaborate about file system access

- content/doc/tutorials/tutorial-for-installing-jenkins-on-AWS.adoc
Updated the documentation to clarify the way package manager usage (`yum` vs `dnf`) is described across Amazon Linux versions. The revised note provides a clearer explanation of the relationship between `yum` and `dnf` on Amazon Linux 2023, while keeping instructions consistent.
> feat: update tutorial-for-installing-jenkins-on-AWS.adoc

- content/doc/book/pipeline/pipeline-as-code.adoc
Related to https://github.com/jenkins-infra/jenkins.io/pull/8008#discussion_r2018416458
> Combine unnecessary line breaks

- content/security/advisory/2025-03-19.adoc
To ease their presentation, the students would like to have their university displayed after their name in that credit
> Add credit details for 2025-03-19 advisory

- content/security/advisory/2025-03-19.adoc
Amends #8015.
We mention the organization after every name.
> Fix credit

- content/doc/book/pipeline/jenkinsfile.adoc
- content/doc/book/using/best-practices.adoc
- Fixed minor typos like `deleted`, `warnnings`.
- Combined unnecessary line breaks.
> Fix typos and combine unnecessary line breaks

- content/_data/changelogs/weekly.yml
Developer entries should be at the end of the list
> Split developer entry from other changelog entries

- content/doc/book/managing/system-configuration.adoc
> Fix link to reverse proxy config page

- content/doc/book/pipeline/index.adoc
This is a small PR to make some text adjustments to the pipeline index page. Updates include formatting the intro text and updating "see" to "refer to" where applicable.
> Formatting & syntax updates to Pipeline index

- content/_partials/changelog-old.html
Suggested by Daniel Beck(https://github.com/jenkins-infra/jenkins.io/pull/8110#discussion_r2096331280) 
Thanks to him
> fix: grammatical correction

- content/doc/book/managing/system-properties.adoc
Document https://github.com/jenkinsci/jenkins/pull/10630
> Document jenkins.security.JettySameSiteCookieSetup.sameSiteDefault

- content/_data/solutions/android.yml
- I have removed an outdated blog link from android solution which I found while updating in docs.jenkins.io repo
- I have added two new articles links in the android page
> feat: new article links to android solution page

- content/blog/2025/06/11/2025-06-11-chirag-gupta-gsoc-community-bonding-blog-post.adoc
Thanks to Guillem Serra Cazorla for reporting the issue.
> Fix broken link in Chirag Gupta blog post

- content/projects/infrastructure/index.adoc
Noticed that it was not up to date
> fix(infrastructure) correct weekly team meeting time

- content/doc/book/using/using-agents.adoc
> fix: small grammar correction

- Jenkinsfile
The goal is to use the same kind of Fastly CDN purge technique as the Jenkins Core release (which is for `pkg`): https://github.com/jenkins-infra/release/blob/master/utils/release.bash#L292
Note: we use the endpoint `purge_all` instead of only 2 targeted CSSes (These CSS where uncached to ensure any visual change was detected). It will have an impact on the backend origin service hosted by the Jenkins infrastructure team as we'll fully purge fastly on each deployment. It should be a minor impact, but still worth mentioning (particularly if I'm wrong).
- Credential created and inserted (more details later in an issue) in trusted.ci.jenkins.io
- Tested with success on a replay of trusted.ci.jenkins.io deployment job (private link: https://trusted.ci.jenkins.io:1443/job/jenkins.io/157455/)
> chore(Jenkinsfile) use Fastly API with authentication for CDN purge

- content/doc/developer/security/index.adoc
- content/doc/developer/security/resources/cli_flow.svg
This PR is to add the updated SVG file that was provided in https://github.com/jenkins-infra/jenkins.io/pull/8192. The errant `logged in` text was removed, and needed to be scaled for the page width.
> Update CLI Flow SVG
