content/doc/book/glossary/index.adoc
Link to Pipelines / Getting Started is updated with the correct one
=> Fix: Broken Link Pipelines/ Getting Started

content/doc/book/managing/groovy-hook-scripts.adoc
It wasn't immediately clear that "HOOK.groovy.d" really meant one of 'init.groovy.d' or 'boot-failure.groovy.d'. It is made clear by mentioning it at the bullet list "The following events use this mechanism:"
This will resolve the issue #3945
=> Clarified allowed HOOK values

content/events/hacktoberfest.adoc
Thge 2021 Hacktoberfest link was missing and the 2020 link was pointing to a mailing list thread.  No summary blog post was created for Hacktoberfest 2021, but a summary was provided in the 2021 "Happy New Year" post.  Use that "Happy New Year" summary post as the link for 2020, since it is a reasonable summary of the results.
=> Add 2021 Hacktoberfest link, update 2020 link

content/doc/pipeline/tour/hello-world.adoc
Also remove trailing punctuation from the list items.
Thanks to https://github.com/jenkins-infra/jenkins.io/pull/5540#issuecomment-1266007580 for realizing that the `docker` label was only used by the scripted Pipeline variants in the tutorial and that it is not needed there any more than it is needed for the declarative variants.
=> Remove requirement for docker label

content/doc/developer/publishing/continuous-integration.adoc
- Remove `configurations: buildPlugin.recommendedConfigurations()`, because it was deprecated.  see: https://github.com/jenkins-infra/pipeline-library/blob/master/vars/buildPlugin.groovy#L336 .
- Add build step for Gradle. see: https://github.com/jenkins-infra/pipeline-library#buildplugin .
=> update plugin build step

content/doc/book/managing/ui-themes.adoc
Related to https://github.com/jenkins-infra/jenkins.io/issues/4678
I think it makes little sense to list all theme-related plugins by popularity. Since all themes referenced by Simple Theme plugin were either converted to plugins or abandoned, the roles of Simple Theme and Theme Manager became quite independent: one allows people to create their own theme, the other lets them use community-maintained themes, so each of them deserves their own section. 
CC @timja
=> Update documentation on themes

content/doc/developer/publishing/releasing-cd.adoc
I have found some issues about `403 Forbidden` on `helpdesk/issues` and `repository-permissions-updater/issues`.
such as:
- https://github.com/jenkins-infra/helpdesk/issues/3076
- https://github.com/jenkins-infra/helpdesk/issues/3069
- https://github.com/jenkins-infra/repository-permissions-updater/issues/2592
So I think this PR is valuable.
And the content from https://github.com/jenkins-infra/jenkins.io/blob/master/content/doc/developer/publishing/releasing-manually.adoc.
=> add explanations for `403 Forbidden`

content/chat.adoc
Adding in a small section to inform users that the IRC, Matrix, and Gitter channels for Infra & Release are now interconnected
=> Update to chat page channels

content/css/jenkins.css
Fixes #5555
@janfaracik alternatively we can just remove the Jumbotron overlay (`.jumbotron:before`)-- why did you introduce it in #5415?
=> Jumbotron overlay should not steal mouse events

content/_data/roadmap/roadmap.yml, content/doc/administration/requirements/linux.adoc
IBM no longer provides the ppc64le agents that we used for verification testing.  Without those agents, we cannot reasonably claim to support ppc64le.
=> Remove ppc64le from roadmap and example platforms

content/doc/book/pipeline/shared-libraries.adoc
Fixes #4772 -- also there was information about fields that contradicts the stateless restriction that we impose later.
@jglick I hope this makes sense (?) Thanks for your input in the issue comments.
=> Extend description of global vars in pipeline

content/doc/book/installing/_jenkins-command-parameters.adoc
This was previously only documented in the `extras-executable-war` README, but that repository has now been archived.
=> Document `--paramsFromStdIn`

content/blog/2016/2016-08-10-rails-cd-with-pipeline.adoc
The same article on https://www.cloudbees.com/blog/continuous-security-rails-apps-pipeline-and-brakeman has had the link removed. There are no appropriate links to replace this link with (other than https://www.cloudbees.com/newsroom/steve-wozniak-2021-devops-world-keynote which I think is largely irrelevant)
=> Removed broken link to community tracks

content/_data/changelogs/weekly.yml
The change proposed removes the dashes from the recent weekly changelog. No idea where they are coming from, but they don't match the past design scheme.
**Current**:
**Proposed change**:
=> Remove dashes from changelog entries of 2.373

content/redirect/semicolons-in-urls.adoc
Oversight when preparing https://github.com/jenkins-infra/jenkins.io/commit/bdc8944b41911c1470c207ce0cf001c07434e2a2
=> Add `semicolons-in-urls` redirect for SECURITY-1774 in Jenkins 2.222.1

content/doc/tutorials/tutorial-for-installing-jenkins-on-AWS.adoc
addendum to https://github.com/jenkins-infra/jenkins.io/pull/5574
added anchor so step 4 could refer back to 1 in the "security group" section
=> Add anchor for ip address step in AWS tutorial

content/doc/developer/publishing/releasing-cd.adoc
Minor change, that updates the CD samples with an up-to-date baseline, rather of one, that is outdated by years and no longer supported by the update center.
=> chore: Use a modern baseline for CD sample

content/blog/2022/10/2022-10-13-jenkins-newsletter.adoc
This is to remove the extra text after the image used in the september newsletter post
=> Jenkins Blog: remove unnecessary text

content/doc/book/managing/system-properties.adoc
The feature was removed, so the system property description has to be updated to not confuse people trying to use it.
Related to https://github.com/jenkinsci/jenkins/pull/4463
=> Updating "jenkins.ui.refresh" due to removal

content/doc/developer/tutorial-improve/update-base-jenkins-version.adoc
as per https://www.jenkins.io/doc/developer/plugin-development/dependency-management/#jenkins-plugin-bom the <version> tag need to get upgrade too.
=> chore(version dependency): some may need to upgrade the version too

content/doc/book/managing/script-console.adoc
Fixing a link to Groovy Remote Control Plugin page.
https://www.jenkins.io - Broken Links #3335
=> [WEBSITE-751] Issue #3335 Groovy Remote Control

content/doc/developer/extensibility/index.adoc
Extension link now goes to https://javadoc.jenkins.io/hudson/Extension.html
=> Fixed broken extension link

content/events/devops-world/index.adoc
The previous register link was still pointing to the original (no longer applicable) DevOps world page, so this has been updated to coincide with the virtual event.
=> DevOps World 2022: update registration link for virtual edition

content/events/devops-world/index.adoc
updating URL again, as basic DevOps World link (http://www.devopsworld.com/) leads to the ideal landing page
=> Jenkins Events: update DevOps World URL

content/project/conduct.adoc
The previous link was broken, leading to a 404 in GitHub
💡 Could be interesting to have some dead links detection tooling
=> Correct CoC link

content/_data/changelogs/weekly.yml
Supersedes https://github.com/jenkins-infra/jenkins.io/pull/5627, by addressing syntax issues
cc @timja 
Kevin is a bit off my timezone, but I'd like to see this published soonish, given it's a possible LTS candidate.
Closes https://github.com/jenkins-infra/jenkins.io/pull/5627
=> Publish changelog for 2.375

content/security/plugins.adoc
Distribution is restored in https://github.com/jenkins-infra/update-center2/pull/652, warning is updated in https://github.com/jenkins-infra/update-center2/pull/653
=> Remove neuvector-vulnerability-scanner from suspensions list

content/security/plugins.adoc
SECURITY-1737 was released in advisory one day later, clearly just a typo
=> Fix advisory link

content/project/board-election-process.adoc
This is the second of two PRs to update the election process page, [formatting update](https://github.com/jenkins-infra/jenkins.io/pull/5635). It contains the same content updates that existed in the closed request, but will have docs team review as well to be sure.
This was merged first so that the content could be updated appropriately after that.
Closing [this PR](https://github.com/jenkins-infra/jenkins.io/pull/5633) as it contains merge conflicts and was made prior to the formatting changes.
=> Jenkins - Update election process content for 2022

content/_data/indexpage/carousel.yml
Hacktoberfest 2022 is done. This PR removes the event announcement from the Jumbotron. 
(reverts PR #5526)
=> Remove Hacktoberfest 2022 from Jumbotron

content/doc/developer/javadoc.html.haml
The LTS Javadoc links on https://www.jenkins.io/doc/developer/javadoc/ are broken.  They state that they point to the LTS baseline Javadoc when it would be better if they pointed to the LTS Javadoc.  The most recent release of the LTS Javadoc is computed in the new layout and the link is pointed to that most recent release of the LTS Javadoc.  Only provides Javadoc links to the most recent five LTS baselines because update center stops providing updates after about 12 months.
Link to the page that describes how plugin maintainers can best choose a minimum Jenkins version rather than offering an overly simplified recommendation for minimum Jenkins version.
Links to modules Javadoc are broken because there are no more modules in Jenkins core.  Removes the modules section.
Link to the weekly …
=> Fix javadoc links for LTS versions

content/doc/book/pipeline/syntax.adoc
This is to add the recently created video https://www.youtube.com/watch?v=GJBlskiaRrI which shows differences between the two syntax options.
=> Jenkins - Add Declarative vs Scripted syntax video

content/doc/developer/tutorial-improve/add-more-spotbugs-checks.adoc
The spotbugs excludes filter file is now enabled automatically if a file with the correct name is found.  There is no longer any need to add the entry into the pom.xml file.
See https://github.com/jenkinsci/pom/releases/tag/jenkins-1.91 and https://github.com/jenkinsci/pom/pull/333
=> Use most recent spotbugs improvements in tutorial

content/blog/2022/10/2022-10-20-jenkins-election-announcement.adoc, content/project/board-election-process.adoc
As @jmMeessen noted, previous participants would need to join the new group for the 2022 election, and I wanted to make sure that it is made clear in the blog post & election process page.
=> Jenkins voter registration group update

scripts/fetch-external-resources
This PR is related to https://github.com/jenkins-infra/helpdesk/issues/3087.
Tested locally with a `make && make run` command: the page http://localhost:4242/doc/pipeline/steps/ show the steps as expected.
I would like at least 2 technical approvals on this one to make sure that I did not break anything. Ping @MarkEWaite @timja @halkeye @lemeurherve @daniel-beck
=> chore(helpdesk-3087) switch URL of the pipeline generated steps to reports.jenkins.io

content/doc/developer/publishing/releasing-cd.adoc
Context: https://github.com/jenkins-infra/jenkins.io/pull/5676/files#r1015153359
- Using long flags helps developer to understand "what is the command doing"
- Adding the `--show-error / -S` flag to show errors to user if there is a network issue (HTTP proxy, GitHub outage, etc.)
- Adding the flag `--location / -L` to ensure that any redirection is followed (repository/organisation renaming, GitHub service name changes, etc.)
=> fix(developer docs) use long flags for `curl` commands in releasing-cd

content/_data/changelogs/weekly.yml
This is to update the 2.377 changelog entries, as they are currently still in the original format submitted by dependabot.
=> Jenkins - Update 2.377 changelog entries

content/security/advisory/2022-11-15.adoc
We generally group advisory entries by resolved, then unresolved.
The fix version for two entries of https://plugins.jenkins.io/cavisson-ns-nd-integration/ arrived unexpectedly this morning, after we had intended to announce them as unresolved. We forgot to reorder to keep the grouping when adapting the advisory. This doesn't change the content, just the order in which the entries appear. Anchors are generated for issue IDs and remain the same.
@yaroslavafenkin
=> Reorder entries in 2022-11-15 security advisory

content/blog/2022/11/2022-11-16-gsoc-2023.adoc, content/projects/gsoc/2023/index.adoc, content/projects/gsoc/2023/project-ideas.html.haml, content/projects/gsoc/2023/project-ideas/plugin-installation-manager-tool.adoc, content/projects/gsoc/2023/project-ideas/prj-idea-template.adoc_text
Blog post to announce GSoC 2023, especially calling for mentors and project ideas.
This PR is the first iteration to create the GSoC 2023 file structure so that project ideas can be submitted.
=> GSoC 2023 blog post

content/blog/2022/11/2022-11-17-jenkins-election-candidates.adoc, content/security/advisory/2022-11-15.adoc
This is a pull request to add a blog post for the Jenkins election candidate announcements. It also includes information pertaining to the election process this year.
=> Jenkins - adding candidate announcement blog post

.typos.toml, content/blog/2022/11/2022-11-17-hacktoberfest-recap.adoc, content/doc/book/managing/ui-themes.adoc, content/project/board-election-process.adoc, content/security/advisory/2022-10-19.adoc
Spelling errors have crept into the documentation even though `typos` is flagging them for us.
@kmartens27 does this look OK to you?
- Fix spelling error Buit -> Built
- Another YouTube URL that is not a typo
- Spelling fix for architect
- Spelling fix of singular
- Spelling fix updates
- Spelling fix for vulnerabilities
- Allow testng for testng-plugin in advisory
Squash merge this (individual commits were used to assure that I was removing one issue at a time).
=> Fix spelling errors

Makefile, content/_layouts/chapter.html.haml, content/_layouts/frame.html.haml, content/_layouts/section.html.haml, content/_partials/_feedback-footer.html, content/_partials/downloadbanner.html.haml, content/_partials/dropdown.html.haml, content/_partials/media.html.haml, content/_partials/steps.html.haml, content/_partials/toptoolbar.html.haml, content/css/jenkins.css, content/css/roadmap.css, content/download/index.html.haml, content/js/blueocean-landing-script.js, content/js/roadmap.js, content/project/roadmap/index.html.haml, content/projects/blueocean/index.html.haml, package-lock.json, package.json
Drop-down menus were not appearing when I clicked the button at the top of the page for "Documentation", "Community", "Subprojects", and "About".
This reverts commit 8cfb4a85dcbd4d6e781d5f60fd5fe2f04c1ddb86.
@zbynek my apologies, but I don't understand why my menus no longer dropdown on any of the machines that I've tested.  Attempting this revert to see if I can duplicate the issue anywhere other than on the production site.
=> Revert "Update Bootstrap to 5.2, replace Tether with Popper (#5436)"

content/doc/developer/publishing/continuous-integration.adoc, content/doc/developer/tutorial-improve/add-a-jenkinsfile.adoc
This aligns with the default Jenkinsfile generated by archetypes for newly created plugins, and what is used widely for components and plugins already.
Also, Kubernetes are usually faster to spin up and generate less cost than a VM.
=> Default to k8s for agent selection in tutorials

content/_data/upgrades/2-375-1.adoc
2.375.1 bundles winstone 6.6, not 6.4.
This PR also documents flag removals between 6.4 and 6.6, plus fixes the version 2.361.4 includes, which is 6.1.
I've added a few linebreaks to improve readibility.
=> Document Winstone 6.6 changes in 2.375.1 upgrade guide

content/doc/developer/publishing/releasing-cd.adoc, content/doc/developer/tutorial-improve/update-base-jenkins-version.adoc, content/doc/developer/tutorial-improve/use-plugin-bill-of-materials.adoc
https://github.com/jenkinsci/archetypes/pull/546 has switched the default baseline for new plugins to 2.361.4.
https://www.jenkins.io/doc/developer/plugin-development/choosing-jenkins-baseline/ recommends either 2.346.3 or 2.361.4 as the core dependency.
Jenkins plugin development tools are switching to require Java 11 as well.
=> Use 2.361.4 as jenkins.version in tutorials and guides

content/_partials/toptoolbar.html.haml
Let's use the up-to-date website URL of tekton, found in various tekton docs itself.
=> Update tekton URL in header

content/doc/developer/tutorial-improve/automate-dependency-update-checks.adoc
This PR wants to give more details on how to configure the auto-labeling feature of dependabot and what are the pitfalls to use this technique rather then the default behavior.
=> Add details on dependabot auto labeling config

content/doc/developer/tutorial-improve/automate-dependency-update-checks.adoc
The auto-tagging comments were correct when the example contained tagging configuration. As it has been removed, the comments are not relevant anymore.
=> Remove irrelevant auto-tagging comments

content/doc/developer/publishing/continuous-integration.adoc, content/doc/developer/tutorial-improve/add-a-jenkinsfile.adoc
The goal is to help plugin maintainer to get a better understanding at "how to use docker in ci.jenkins.io for plugins dockerized tests".
It is a minor update, amending https://github.com/jenkins-infra/jenkins.io/pull/5774 that pre-dates the upstream change https://github.com/jenkinsci/archetypes/pull/552.
=> feat(developers doc) clarify how to use 'docker' for plugin tests

content/doc/book/system-administration/backing-up.adoc
Clarify that the thin-backup plugin is being maintained and only the backup plugin is not, but I kept the plural if other plugins I'm unaware of are also available but unmaintained.
=> Clarify that the thin-backup plugin is being maintained

.typos.toml, Jenkinsfile, content/blog/2022/11/2022-11-23-get-prepared-for-gsoc.adoc, content/projects/gsoc/2023/project-ideas/add-probes-to-plugin-health-score.adoc, content/security/reporting.adoc
Also shifted the quality gate from a green tick to a higher severity, to no longer return a successful status if a PR introduces typos, this is misleading.
The change proposed to the Jenkinsfile changes the state accordingly:
=> Fix a few typos highlighted by the typo checker

Gemfile, Gemfile.lock
The recent ruby upgrades allow us to use an up-to-date version of this gem.
=> Bump asciidoc to 2.0.18

Gemfile, Gemfile.lock
There are no changes between 2.3.0 and 2.3.2, but deprecation annotations, outlining what will change in 3.x
=> Bump rubyzip to 2.3.2

content/doc/book/installing/_docker-for-tutorials.adoc, content/doc/book/installing/_docker.adoc, content/doc/book/pipeline/docker.adoc, content/doc/book/pipeline/syntax.adoc, content/doc/tutorials/build-a-java-app-with-maven.adoc
- Use latest blueocean and docker-workflow plugins
- Use Apache Maven 3.8.6, not 3.8.1
https://github.com/jenkins-docs/simple-java-maven-app/issues/503 reports
the issue with Maven 3.8.1.  Jenkins developers use Maven 3.8.6 almost
exclusively now.
=> Update Blue Ocean, Pipeline Groovy, and Maven in tutorials

content/doc/book/scaling/architecting-for-scale.adoc
closes #5489 
if i need to add more reference links throughout the [Architecting for scale](https://www.jenkins.io/doc/book/scaling/architecting-for-scale/) ,please let me know
=> added reference link to docs about agents

content/_data/changelogs/weekly.yml
The logic itself is long gone and the removal of the flag is considered code cleanup, however, not removing the flag from your Jenkins startup flags causes Jenkins to not start at all.
=> Document removal of '--daemon' flag

content/doc/pipeline/tour/hello-world.adoc
The hello world tutorial was using a different maven container than the
other locations in the documentation.  Use the same maven container in
this location as is used in the other locations.
=> Use same maven in tutorial as is used elsewhere

content/sigs/advocacy-and-outreach/index.adoc
Add particpant name to Advocacy and Outreach SIG index/home page.
=> Add participant name to Advoacy and Outreach SIG index page

content/doc/book/pipeline/docker.adoc, content/doc/book/pipeline/syntax.adoc, content/doc/pipeline/tour/hello-world.adoc, content/doc/tutorials/build-a-java-app-with-maven.adoc
Recently released and has been confirmed that it works with Jenkins core and with many Jenkins plugins.
=> Use Apache Maven 3.8.7 for examples, not 3.8.6

content/doc/book/installing/_docker-for-tutorials.adoc, content/doc/book/installing/_docker.adoc
The version specifiers like `blueocean:1.26.0` were originally added because it is a strongly preferred practice to precisely define the versions of plugins that are being installed.  However, the default behavior of the plugin installation manager is to install the most recent release of the plugin, even if a plugin version is specified.
If a user wants to install an older version, the `--latest false` argument is used.  However, that installs outdated versions of many plugins when the plugins and their versions are not fully specified.
Using `blueocean` is better than `blueocean:1.26.0` in this case because it avoid a precise version specification that is then ignored by the plugin installation manager and instead relies on the plugin installation manager to choose the most recent …
=> Remove version specifier from demo plugin installs

content/_partials/connect-links.html.haml, content/projects/infrastructure/index.adoc, content/sigs/advocacy-and-outreach/index.adoc, content/sigs/gsoc/index.adoc, content/sigs/index.html.haml, content/sigs/ux/index.adoc
This PR removes the link to the UX/SIG mailing list in favor of a link to the forums on community.jenkins.io and lists active sig members.
Additionally, I added a placeholder to link to community forums in the sidebar and added it to a few active sigs, which use the forums.
I also fixed the link redirection to google groups.
=> Revise UX SIG page and add forum link

content/security/reporting.adoc
This is irrelevant to the audience of this page and duplicates part of https://www.jenkins.io/project/team-leads/#infrastructure
If the intention is to document the "forwarding" of reports, that could be added to https://www.jenkins.io/project/team-leads/#security as a team lead responsibility.
=> Remove internal process details

content/project/board.html.haml
Match the results from the November 2022 election.
https://github.com/jenkins-infra/jenkins.io/issues/5870 is fixed by this pull request
=> Update board and officers page

content/css/jenkins.css
* Yesterday I visited the website on mobile and noticed that it was possible to scroll horizontally on the website.
* The screenshot below shows that the menu icon isn't completely visible on screen. 
* As you can see here, there is still some overflow to the right, which enables horizontal scroll. (I changed the background to red to make it easier to spot). 
* The CSS that I added fixes this issue.
=> Fixed horizontal scroll issue on mobile

content/_layouts/corebaseline.html.haml, content/_partials/changelog-changes.xml.haml, content/download/index.html.haml, content/security/advisories/rss.xml.haml
This PR addresses the removal of `Kernel#open` in favor of `URI.open` in ruby 3 and migrates legacy syntax to supported syntax.
Taking a look over the generated feeds and xml structured texts reveal no difference between the current layout.
=> Address ruby deprecations

content/css/jenkins.css
Reverts jenkins-infra/jenkins.io#5726 this breaks independent scrolling
i'll add a patch for it in this PR
=> Patch "Fixed horizontal scroll issue on mobile"

content/sigs/docs/index.adoc
No longer used, see community.jenkins.io and https://gitter.im/jenkinsci/docs
=> Remove Docs sig mailing list

content/_data/changelogs/lts.yml
It seems incrementing the year was accidentally omitted during <https://github.com/jenkins-infra/jenkins.io/pull/5793>.
=> Correct publication year of 2.375.2

content/sigs/platform/index.adoc
Avoid a conflict with another meeting
@gounthar this matches with the change I made in the Jenkins calendar.
=> Move Platform SIG meeting 1 hour later

content/_layouts/frame.html.haml, content/_partials/projectcarousel.html.haml, content/css/jenkins.css
Fix #5911 by using Bootstrap 5 attribute names; z-index needed changing to allow navigating carousel by clicking the indicators.
Also fixes the console error related to docsearch being loaded by the site -- no longer needed since it's loaded by the header component instead.
=> Fix carousel, remove redundant docsearch

content/projects/gsoc/2023/project-ideas/prj-idea-template.adoc_text
Update the project idea template with comments to avoid misunderstandings for contributors and reviewers.
For full guidance see projects/gsoc/proposing-project-ideas/
=> Update GSoC project idea template

CONTRIBUTING.adoc
Historically, assigning newbies to issues didn't have a much positive impact on the issue, in terms of delivering an acceptable solution; hence we typically don't assign people to issues. Anyone is welcome to contribute anything they feel comfortable with.
This PR adds this state to the contributing documentation.
=> Clarify state on issue assignees

content/doc/developer/tutorial-improve/automate-dependency-update-checks.adoc
The [plugin archetype](https://www.jenkins.io/doc/developer/tutorial/create/) now includes dependabot checks once a month. That is sufficient for a plugin that is maintained less frequently and avoids the distraction of dependabot pull requests every week.
Also removes the "insert maintainers here" because there have been several cases where a new contributor did not replace that text with the name of a maintainer.
@jmMeessen, @gounthar, and @dheerajodha were involved with this file previously and may want to comment on it.
=> Only check dependencies once a month

content/projects/gsoc/2023/project-ideas/gitlab-plugin-modernization.adoc
Putting the "GitLab Plugin Modernization" back to discussion status in order to solve the comments made in https://github.com/jenkins-infra/jenkins.io/pull/5836#discussion_r1087096858 and https://github.com/jenkins-infra/jenkins.io/pull/5836#issuecomment-1404202964
=> [GSoC] reverting gitlab plugin modernization to discussion

Gemfile, Gemfile.lock, content/_ext/activenav.rb, content/_ext/get_plugins.rb, content/_ext/pipeline.rb, content/download/index.html.haml, content/project/roadmap/index.html.haml, content/security/advisories.html.haml, content/security/advisories/rss.xml.haml
Since tilt changed the scope used for compiling ruby code inlined in haml, this moves bits of code out of haml to make things compile.
=> Update haml and tilt

content/projects/gsoc/2023/project-ideas/plugin-installation-manager-tool.adoc
Plugin installation manager tool project idea needed more details.  Those details are now included in the page, along with an embedded video from 2021 discussing enhancement ideas.
=> Extend plugin install mgr project idea

content/projects/gsoc/2023/project-ideas/gitlab-plugin-modernization.adoc
Cleans up this project proposal so that it can be ready for draft state, addressing previous concerns. Reduced the scope of the project to be consistent with a 175-hour project size and clarified the difficulty level: the project is "easy" in one sense but long and tedious in another. Clarified the expected outcome, documented known challenges, and provided links to other examples of this migration.
CC @jmMeessen
=> Promote GitLab plugin modernization project to draft state

content/doc/developer/handling-requests/json.adoc
It's me again with the improvements to the same page.
- Make code examples with tests and curl working
- Improve imports
- Modernize to JUnit 5 and use Hamcrest Matchers to make it more readable (personally I prefer AssertJ, but Hamcrest is available out-of-the-box by jenkins-test-harness)
- Fix typos and grammar
=> [doc/developer/handling-requests] Modernize JSON HTTP API documentation

content/projects/gsoc/2023/project-ideas/gitlab-plugin-modernization.adoc
Also adds links to good first issues so that candidates have some
initial areas that they can investigate.
=> Add markewaite as GitLab plugin project mentor

Gemfile, Gemfile.lock
The upgrade from webrick 1.7.0 to 1.8.0 causes `make run` to report that it cannot modify frozen strings.  Page generation fails for the top level page and for the changelog page that I was trying to check.
Exact failure message was:
```
[2023-01-31 13:24:07] INFO  WEBrick 1.8.0
[2023-01-31 13:24:07] INFO  ruby 3.2.0 (2022-12-25) [x86_64-linux]
[2023-01-31 13:24:07] INFO  WEBrick::HTTPServer#start: pid=1 port=4242
Regenerate /home/mwaite/git/jenkins/jenkins.io/content/index.html.haml
[2023-01-31 13:24:11] ERROR FrozenError: can't modify frozen String: ""
/home/mwaite/git/jenkins/jenkins.io/vendor/gems/ruby/3.2.0/gems/rack-2.2.6.2/lib/rack/handler/webrick.rb:120:in `block in service'
/home/mwaite/git/jenkins/jenkins.io/vendor/gems/ruby/3.2.0/gems/rack-2.2.6.2/lib/rack/handler/webrick.rb:119 …
```
=> Fix regression in `make run` from webrick 1.8.0

content/projects/gsoc/2023/project-ideas/JCasC-drift-detector.adoc, content/projects/gsoc/2023/project-ideas/add-probes-to-plugin-health-score.adoc, content/projects/gsoc/2023/project-ideas/agent_reconnections_exponential_backoff.adoc, content/projects/gsoc/2023/project-ideas/alternative-jenkinsio-build-tool.adoc, content/projects/gsoc/2023/project-ideas/buiilding-android-app.adoc, content/projects/gsoc/2023/project-ideas/displaying_plugin_health_scores.adoc, content/projects/gsoc/2023/project-ideas/docker-compose-build.adoc, content/projects/gsoc/2023/project-ideas/gitlab-plugin-modernization.adoc, content/projects/gsoc/2023/project-ideas/screenshot-automation.adoc
Project idea discussions are now stabilized. Time to mark most of the GSoC 2023 project ideas as "published".
=> GSoC: Promote most project ideas to "published" status

content/doc/administration/requirements/java.adoc
OpenJ9 is not tested
ZeroVM is too slow to be usable
=> Clarify that HotSpot JVM is required

content/projects/gsoc/2023/project-ideas/alternative-jenkinsio-build-tool.adoc, content/projects/gsoc/2023/project-ideas/plugin-installation-manager-tool.adoc
To add context and details to the "Alternative jenkins.io build tool" documentation for GSoC 2023, expecially the division of tasks into backend and frontend web development, as well as into documentation and blog.
=> Edit Alternative jenkins.io build tool doc for GSoC 2023

content/participate/code.adoc
We transferred everything of use from stapler to jenkinsci and the chinese org is inactive for years; hence this PR removes both organizations from the code page. Let's focus on organizations that are active and guide people's contributions here.
=> Remove stapler and chinese org from code page

content/mailing-lists/index.html.haml
This PR follows up my previous PR (https://github.com/jenkins-infra/jenkins.io/pull/5897/) to remove the chinese mailing list, which is full of ads, and we are in the process to retire the chinese website, which used this mailing list.
=> Remove chinese mailing list

content/chat.adoc
The removal of the couple of lines follows up the current and past board and office terms, where this wasn't the case.
I think we can safely drop this requirement, given the IRC channels don't quire as much moderation as other parts of the Jenkins project because many people use Gitter/Matrix these days.
Currently, Tim and Gavin are OP on all IRC channels, which is a strong yet sufficient choice, in case we need to get something sorted.
=> Revise IRC part on chat page

content/project/trademark/index.adoc
The wayback machine revealed the new target destination of the broken redirects, which I put in place. This PR ensures there are no broken redirects left on this page.
=> Fix broken links on attribution page

content/doc/book/troubleshooting/diagnosing-errors.adoc, content/participate/report-issue.adoc
The change proposed adds the Java version output to the copy/paste snippet, to provide helpful insights in what people are using, given plugins and core can behave differently between Java 11, 17 or newer.
=> Include Java version and vendor in bug report snippet

content/_partials/legacy/download.html.haml, content/doc/book/installing/linux.adoc, content/doc/book/managing/casc.adoc, content/doc/book/pipeline/docker.adoc, content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-iptables.adoc, content/download/index.html.haml, content/download/verify.adoc
The platform SIG, infrastructure team, and security team have all noted that CentOS 7 is approaching its end of life.  Container images for CentOS 7 are unmaintained.  Versions of crucial programs (like ssh and git) are badly outdated on CentOS 7 and provide a poorer user experience than more modern systems like Red Hat Enterprise Linux 8 and Red Hat Enterprise Linux 9.
CentOS 8 is already unmaintained and unsupported by the CentOS project.
- Include Alma and Rocky when referencing Red Hat
- Replace CentOS 7 video with Rocky 9 video
- Remove CentOS 7 title reference
- Use Oracle Linux 9 and MySQL 8 in example
=> Include Alma and Rocky, reduce CentOS references

content/participate/report-issue/redirect.html.haml
We've seen a few issues reported that lack any kind of information about the identity of the affected plugin. Our guess is that they were submitted through this form, with submitters not realizing that, unlike in JENKINS, there's no component identifying the plugin.
This adds a fixed placeholder to the summary as a first step, let's see how well this works.
=> Add placeholder to indicate additional information is needed

content/chat.adoc, content/project/conduct.adoc
As of yesterday, Gitter runs exclusively on Matrix, the web ui changed from Gitter's custom one, to the default element.io concept.
This transition broke our "home" URL used to list all channels: https://gitter.im/jenkinsci/home
The new URL, available on https://app.gitter.im/#/room/#jenkins-ci:matrix.org, is a drop-in replacement listing all Gitter channels, plus bridged IRC <-> Matrix channels.
=> Exchange Gitter namespace URL with matrix home

content/projects/gsoc/2022/index.adoc, content/projects/gsoc/index.adoc
- updating status (Application sent)
- added link to application data
- mention kick-off Office Hours
- link to recordings of Student webinar and Mentor webinar
- corrected broken link in GSoC2022 archive
=> Update GSoC page with current status

content/projects/gsoc/2023/project-ideas/alternative-jenkinsio-build-tool.adoc
To provide links to the https://github.com/jenkins-infra/jenkins-io-components where the code of the components for the jenkins.io are currently hosted for the GSoC "Alternative jenkins.io build tool(s)" project contributor should decide to work also on improving the UI/UX design of jenkins.io.
=> Add missing detail regarding jenkins.io components

content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-iptables.adoc
Prepare for Ubuntu 18 end of life in Apr 2023
=> Remove Ubuntu 18 reference

content/doc/book/pipeline/syntax.adoc
In [User Handbook](https://www.jenkins.io/doc/book/), there's no introduction about how to abort previous build when pipeline concurrency occurred by writing Jenkinsfile. I ended up finding it by using [Snippet Generator](https://www.jenkins.io/doc/book/pipeline/getting-started/#snippet-generator).
It would be a bit confusing for Jenkins rookies like me, so I think it would be better to add this example.
=> docs(pipeline): Add a missing intro to abort previous build option

content/projects/gsoc/index.adoc
**WARNING**: 
Please hold merge until Google announced selected 2023 Mentoring Orgs (and if Jenkins is selected) => 22-Feb-2023 18:00 UTC
This PR changes the GSoC welcome page as we are entering a new phase.
=> GSoC 2023 status update

content/security/for-maintainers.adoc
Backports are sometimes needed to make sure LTS instances receive the security fix, so document that.
Also, mention that "safe" unreleased changes do not necessitate a branch off the previous release, but advise caution.
=> Document backporting procedures for security fixes

content/doc/developer/publishing/style-guides.adoc
New hosting requests use `io.jenkins.plugins`, given that's the base archetypes generates and our documentation points to.
The hosting tooling has been updated some time ago to ensure all new hosting requests follow the standard groupId pattern of `io.jenkins.plugins`.
=> Update groupId wording for hosting requests

content/doc/book/managing/script-console.adoc
Fixes  #6071 -- no need to mention a suspended plugin https://plugins.jenkins.io/pipeline-classpath/
=> Remove a link to a suspended plugin

content/download/index.html.haml
I am writing to propose a fix for broken links in the  repository. While reviewing the repository, I noticed that the links on lines 133 and 199 of a particular file were not working. I have since made the necessary changes to update these links and ensure that they are functional.
To make these changes, I forked the  repository and cloned it to my local machine. I then made the necessary updates to the file, testing the changes to ensure that the links were working properly. I have committed the changes to my local Git repository and pushed the changes to my forked repository on GitHub.
I am now creating a pull request to propose these changes to the repository.
=> Replace broken OpenBSD links

content/projects/gsoc/2023/project-ideas/docker-compose-build.adoc
The Kubernetes link led to an error 404. Fixed the link
=> Fix broken URL on docker-based jenkins quickstart examples GSoC page

content/blog/2018/06/2018-06-15-simple-pull-request-plugin.adoc, content/blog/2022/11/2022-11-23-get-prepared-for-gsoc.adoc, content/blog/2022/12/2022-12-09-GSoC-the-gift-of-mentorship.adoc, content/blog/2022/12/2022-12-09-jfrog-maintenance.adoc, content/blog/2023/02/2023-02-21-thoughts-on-FOSDEM-2023.adoc, content/doc/tutorials/using-jenkinsfile-runner-github-action-to-build-jenkins-pipeline.adoc, content/projects/gsoc/2023/project-ideas/buiilding-android-app.adoc, content/security/advisory/2022-04-12.adoc, content/security/advisory/2022-05-17.adoc
This PR picks up my comment on https://github.com/jenkins-infra/jenkins.io/pull/6079#discussion_r1118107550, to break hardlinks to jenkins.io.
This ensures redirections lead to the domain URL, and not jenkins.io. A typical use-case of this scenario is browsing pages locally or on netlify, without redirects to jenkins.io.
=> Break hardlinks to jenkins.io

content/_data/changelogs/lts.yml, content/_data/changelogs/weekly.yml, content/_data/logo/chatterbox.yml, content/_data/roadmap/roadmap.yml, content/blog/2017/04/2017-04-27-columbia.adoc, content/blog/2020/01/2020-01-29-gsoc-report.adoc, content/projects/advocacy-and-outreach/outreach-programs.adoc, content/projects/blueocean/roadmap/index.adoc
Similar to https://github.com/jenkins-infra/jenkins.io/pull/6084, hard links are obsolete in the changelog and roadmap too.
=> Unlink hard links in changelog and roadmap

content/_layouts/frame.html.haml
`relative_source_path` already contains a leading slash, as seen on footers such as https://www.jenkins.io/participate/ linking to https://github.com/jenkins-infra/jenkins.io/edit/master/content//participate/index.html.haml.
With the removal of the trailing slash from `content/`, URLs are no longer invalid: https://github.com/jenkins-infra/jenkins.io/edit/master/content/participate/index.html.haml
=> Don't append leading slash to GH URL

content/blog/2023/02/2023-02-21-thoughts-on-FOSDEM-2023.adoc
This is to update the "outreachy" label on the FOSDEM 2023 recap post, and correct it to "outreach"
=> Jenkins.io blog - fix outreach label on FOSDEM post

.github/workflows/label-conflicting-prs.yml
Similar to core, I would like to notify PR authors and maintainers once a PR conflicts with the target branch.
I have been using the same workflow for about 5 months, and it helped a lot to keep review times short, by notifying people and allowing them to act in a timely manner.
=> Label conflicting PRs

content/_data/indexpage/carousel.yml
This pull request updates the jenkins.io carousel (aka Jumbotron) to announce that voting for the Jenkins Contributor 2023 Awards is now open.
=> Announce that jenkins award voting is now open

CONTRIBUTING.adoc
* the Jira link resulted in empty page
* it would be good to have a bit more clear policy for (not) assigning issues, so I proposed some additions
=> Update instructions for new contributors

content/download/index.html.haml
Let's add our official helm charts distribution to the download page.
This is based on https://github.com/jenkinsci/helm-charts fetching from our chart repo at https://charts.jenkins.io/
There are a plenty of Jenkins helm charts available. Therefore, I'd like to make it obvious from our end which one is the official repository.
=> Add helm distribution to download page

content/press.adoc
A little easier to read when the verb is a single word instead of using two words, like "reach out".
=> Minor rephrase on press contacts page

content/books.html.haml
Currently, the jenkins.io/books page has numbered ordering, which can appear as though we are recommending books in a specific order/ranking. We want to make sure that everything is impartial and that the perception is any of these books could be number 1, depending on what the user needs/is looking for.
This suggestion is to remove the index+1 line in the file so that there is no numbered ordering.
=> Jenkins.io - Remove number ordering on "Books" page

content/doc/developer/publishing/preparation.adoc, content/doc/developer/publishing/source-code-hosting.adoc, content/project/governance.adoc
In case the term is unclear, and regarding ongoing tasks, I propose to add links to the OSI listing all approved licenses, to avoid any possible confusion.
=> Linkify 'osi-approved'

content/security/advisory/2023-03-21.adoc
`convert -> conversion` is supposed to be meant here, I assume.
=> Fix typo in today's security advisory

content/doc/developer/publishing/source-code-hosting.adoc, content/doc/developer/publishing/source-code-hosting/forks.adoc
Updates datatables and switches to the new repository, from where it's distributed.
=> Update datatables to 1.13.4

content/doc/developer/publishing/releasing-manually.adoc
Fail fast in a common (at least for me) error condition.
=> Advise users to test their SSH connection before performing a release

content/_partials/toptoolbar.html.haml, content/css/jenkins.css, content/stylesheets/base/_display.scss
Reverts jenkins-infra/jenkins.io#6197
This broke the account app, see:
https://github.com/jenkins-infra/account-app/issues/257
https://github.com/jenkins-infra/account-app/pull/251
https://github.com/jenkins-infra/account-app/issues/250
Changing the body's display seems a bit drastic =/
=> Revert "fixing footer, to resides at the end of the page"

content/projects/gsoc/2023/project-ideas/add-probes-to-plugin-health-score.adoc, content/projects/gsoc/2023/project-ideas/buiilding-android-app.adoc, content/projects/gsoc/2023/project-ideas/docker-compose-build.adoc, content/projects/gsoc/2023/project-ideas/gitlab-plugin-modernization.adoc
This pull request cleans/updates the mentors for the 2023 GSoC project ideas.
Also adding the Gitter channel for some project ideas, when available.
=> Updating GSoC mentors

content/doc/developer/security/remoting-callables.adoc, content/security/reporting.adoc
Since Jenkins 2.319 and LTS 2.303.3 empty roles checks are not a danger.
We've decided to not treat them as a vulnerability anymore
=> Don't consider empty checkRoles as a vulnerability

Jenkinsfile
7 years ago this archive was used for the deployment via FTP. This isn't the case since a long time ago.
These archives currently occupy ~36GB on `ci.jenkins.io` for nothing as there are now PR previews on Netlify.
Ref: https://github.com/jenkins-infra/helpdesk/issues/3492
=> Remove "archive site" stage

content/doc/tutorials/tutorial-for-installing-jenkins-on-AWS.adoc
Amazon Linux 2023 no longer includes an OpenJDK 11 package, so recommend Corretto instead. Tested as part of https://github.com/jenkinsci/packaging/pull/388.
=> Add instructions for Amazon Linux 2023

content/_data/events/2023-05-08-cdcon.adoc, content/_data/events/2023-10-01-hacktoberfest.adoc
cdCon includes link to the web site.
Hacktoberfest 2023 has not been announced yet, but DigitalOcean has been consistent for many years.
=> Add cdCon and Hacktoberfest events

CONTRIBUTING.adoc
This pull request is to add some image guidelines for contributing to Jenkins. These are some general ideas meant to help clarify how screenshots/images can be used and added to the documentation. It also provides guidelines on adding alt text, to improve the SEO score and provide further accessibility for users.
I have also updated a fair amount of the sentence/page formatting to use single sentence per line (in a lot of areas). I know this is not complete throughout the documentation, but plan on making further edits when adding additional guideline suggestions (documentation formatting and book submissions).
=> Jenkins.io - add image guidelines to contributing.adoc

content/_data/changelogs/lts.yml, content/_data/upgrades/2-387-2.adoc
The LTS upgrade guide is specific to the LTS release and reduces the risk of LTS users inadvertently choosing the wrong text to cut and paste.
Thanks to @cybersa for detecting the problem in the blog post and fixing it there with 
* https://github.com/jenkins-infra/jenkins.io/pull/6249
=> Link from LTS changelog to LTS upgrade guide, not blog post

CONTRIBUTING.adoc
This is a pull request to add another guideline to the image section just implemented in the contributing guide.
Compression is integral to the image process, as this helps reduce the size/page load.
=> Jenkins.io - adding compression guideline

CONTRIBUTING.adoc
Follow up to https://github.com/jenkins-infra/jenkins.io/pull/6253
`image:` is a keyword in asciidoc. The current usage breaks the entire page layout below the paragraph:
How does my proposal of words sound to you? Should warrant the context while restoring the layout.
=> Reword image compression paragraph to fix page layout

.github/CODEOWNERS
The CODEOWNERS file doesn't work for people or teams without write permissions. The `jenkins-infra/hacktoberfest` team has no individual write permissions on this repository. Hence, the file errors every time you open it.
I recommend dropping the clause, given it didn't work in the first place. The team members are still welcome to review PRs affecting their area <3
=> Fix CODEOWNERS scope

content/doc/developer/blueocean-plugin-development/index.adoc, content/doc/developer/views/icon-path-to-icon-class-migration.adoc, content/doc/developer/views/table-to-div-migration.adoc
We don't use any mailing list. I removed it from the blue ocean page too, let's not guide people here.
=> Remove UX SIG mailing list entry from table to div page

content/index.html.haml
Closes #6230 
Video inserted in container and section, so its size remains equal to other section below it.
=> Video frame size fixed

content/_partials/projectcarousel.html.haml, content/css/jenkins.css, content/solutions/index.html.haml, content/stylesheets/core/_all.scss, content/stylesheets/core/_base.scss, content/stylesheets/core/_headings.scss, content/stylesheets/pages/_all.scss, content/stylesheets/pages/_use-cases.scss
This PR restores the changes made in #5415 which intended to modularise the CSS classes and increase the usage of CSS variables in the codebase. 
See https://github.com/jenkins-infra/jenkins.io/pull/5415
---
The initial PR was rightfully reverted as it tweaked the heading sizes in a way which could confuse the hierarchy of the page. This PR fixes that regression by tweaking the sizings of the headings so that they're inline with the current jenkins.io design. The only changes you should see are mild colour tweaks and weight changes.
e.g.
Before
After
Thanks
=> Restore 'Modularise more classes + increase usage of CSS variables (#5415)'

content/doc/developer/plugin-development/dependency-management.adoc, content/doc/developer/tutorial-improve/update-base-jenkins-version.adoc, content/doc/developer/tutorial-improve/use-plugin-bill-of-materials.adoc
No reason to include outdated version numbers in the examples.  Eventually it would be nice to generate those version numbers and include the version number of the most recent release in the documentation set.
=> Use latest bom-2.375.x in examples

.gitpod.yml
Install the AsciiDoc plugin if you open the repository through GitPod in IJ and adds a badge to PRs, similar to core, to allow checking out PRs.
=> Add gitpod badge to PRs and install AsciiDoc plugin for IJ

content/_data/roadmap/roadmap.yml, content/blog/2018/07/2018-07-25-contributor-summit.adoc, content/events/hacktoberfest.adoc, content/projects/gsoc/2020/project-ideas/jenkins-distribution-customize-service.adoc, content/projects/infrastructure/index.adoc, content/sigs/cloud-native/pluggable-storage.adoc, content/sigs/docs/index.adoc
Inactive SIG links will redirect to the SIG parent page.  That won't help users that click a link to reach a page specific to a SIG.  Remove or replace links so that they lead to reasonable locations
=> Remove more references to inactive SIGs

CONTRIBUTING.adoc, Makefile
The change proposed revises the Makefile to add a goal called `help`. The goal intents to list all goal comments prefixed with two hashtags. This layout represents a comment in make.
Dependencies of a goals or single hashtags are not considered, to allow differentiation between top-level goals and dependencies.
The rationale behind this change is to provide a command line friendly overview of the most useful goals including a brief description, without the need to repetitively check the contributing file to view the goals you want to run.
Bonus points:
The `help` goal aggregates an alphabetically sorted list of goals to get up the site, given make doesn't provide such a functionality by default.
=> Revise Makefile and add 'help' goal

content/events/hacktoberfest/faq.adoc
The `hacktoberfest-accepted` label may also be used to label already accepted PRs, before they are approved by a maintainer and merged at a later point.
=> Recognize 'hacktoberfest-accepted' label

content/doc/book/pipeline/syntax.adoc
Updates the allowed location of `stages` from only once.  See: sequential/parallel stages.
Resolves #6318
=> Updates stages allowed location

.github/renovate.json
We don't need to run renovate that frequently, monthly is totally fine for our dependencies.
=> Turn down renovate

content/doc/book/pipeline/jenkinsfile.adoc
Hi!
The existing wiki page uses a non-existent reference in the "Parallel Execution" section, which refers to a "node" instead of an "agent" when describing the usage of multiple agents in one pipeline. I'm guessing some changes were made to this document, and the wording was changed from node to an agent which is why this reference is not working at the moment.
=> Updated jenkinsfile.adoc, incorrect referral fixed

content/doc/tutorials/tutorials-for-installing-jenkins-on-Google-Cloud.adoc
https://cloud.google.com/solutions/managing-infrastructure-as-code-with-terraform-jenkins-and-gitops redirects to https://cloud.google.com/docs/terraform/resource-management/managing-infrastructure-as-code
We don't need to link to a Cloud Build tutorial.
=> Remove link to Google cloud build tutorial

content/redirect/operating-system-end-of-life.adoc
https://github.com/jenkinsci/jenkins/pull/7913 proposes operating system end of life administrative monitors and proposes an early end of life for RHEL 7, CentOS 7, Scientific Linux 7, and Oracle Linux 7.
This redirect is used in that code to provide administrators with more details about the Linux support policy of the Jenkins project/files.
=> Provide OS end of life redirect

content/images/jenkins-logo-title-dark.svg
When I added this logo some time ago, I made it "darkmode only". The change proposed alters the logic to a theme-agnostic version allowing me to use it on more occasions without handling darkmode logic, given this logic is now handled right inside the SVG via `prefers-color-scheme`.
=> Inline text in darkmode logo to support several styles

content/css/jenkins.css
Reverts jenkins-infra/jenkins.io#6329 so that the changelog page returns to looking like this:
=> Revert "Fix aspect ratio of images"

content/project/teams/hosting.adoc
Given, teams are accessible to organization members only, this PR improves on that topic, by shining more transparency on the individuals involved in the hosting process, for non-organization members and everyone interested.
=> List members of the hosting team

content/download/lts/index.adoc
A small wording change to note that backporting candidates should be tested on weeklys before landing in LTS lines.
This principle isn't new and already complied by in recent LTS lines, this PR just documents it.
=> Reword backporting eligibility

content/blog/2023/05/04/2023-05-04-gsoc2023-projects-announcement.adoc
The change proposed escapes the hashtags in the URLs to make the URLs valid.
It is unclear to me why they are broken on this page, given they work on other pages.
But for now, let's fix them.
=> Fix broken URLs on GSoC blog post

content/security/for-maintainers.adoc
By using 3.0.0, we include https://github.com/apache/maven-release/pull/62 which improve the end of line support for the pom.xml.
This could be necessary for (at least) Windows developpers when their plugin has configured spotless (perhaps also depending on their git checkout setup). In my case the pom.xml got its end of line rewritten as /r/n while I had /n due to core.autocrlf=input. As the default is "source", it should work for everyone without any changes.
<details><summary>Example of stacktrace related to this problem</summary>
```
[INFO] [INFO] BUILD FAILURE
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] Total time:  7.315 s
[INFO] [INFO] Finished at: 2023-05-06T16:46:28+02:00
[INFO] [INFO] …
```
=> Correct spotless issue during release

content/_layouts/gsocproject3.html.haml, content/projects/gsoc/2023/projects/docker-compose-build.adoc
I have added a new layout `gsocproject3` to use instead of `gsocproject2` since the links in `gsocproject2` were not easily editable. 
I don't know much about how `.haml` files work yet, so I have just removed the links section from the end of `gsocproject2` and tested it on a Gitpod instance.
=> Add new layout for GSoC projects

content/blog/2023/05/22/2023-05-22-jagruti-introduction-blog-post.adoc
Fixed `adoc`  syntax for subheading "What will I do during this GSoC period?"
=> Fixed adoc syntax in Add GSoC 2023 contributor introductory blog for Plugin Health Scoring System project blog

content/_layouts/gsocproject.html.haml, content/_layouts/gsocproject2.html.haml, content/_partials/connect-links.html.haml, content/projects/gsoc/2023/projects/add-probes-to-plugin-health-score.adoc, content/projects/gsoc/2023/projects/alternative-jenkinsio-build-tool.adoc, content/projects/gsoc/2023/projects/docker-compose-build.adoc, content/projects/gsoc/2023/projects/gitlab-plugin-modernization.adoc
Updated GSoC weekly project meeting time on "Building jenkins.io with alternative tools" project page.
=> Update GSoC weekly project meeting time

content/_data/changelogs/lts.yml, content/_data/changelogs/weekly.yml, content/_data/upgrades/2-401-1.adoc
Also fixes a markup error in the weekly changelog
=> 2.401.1 changelog and upgrade guide

content/doc/book/pipeline/syntax.adoc
Make sure users know the default value.
=> Mention the default value for the choice parameter

content/doc/book/pipeline/shared-libraries.adoc
The reference to `github-branch-source` was misleading since that is not a prerequisite for using `pipeline-github-lib` to load an untrusted library from a public GitHub repository. Perhaps the intent was to say that if you are doing Pipeline-as-code generally, you can minimize the amount of configuration in Jenkins to a simple org folder definition by using this trick, but even that does not make much sense since you _would_ still need to define the org folder (and you could if you wished define untrusted libraries with any SCM including authentication on that folder).
https://github.com/fabric8io/kubernetes-client/blob/231aafb89340f901eb2619bb4c646f1b200b7e12/Jenkinsfile#L17 is an example but I was reluctant to put that here since it would really belong below under **Using libraries**.
=> Update reference to `pipeline-github-lib`

content/redirect/operating-system-end-of-life.adoc
During the latest Docs Office Hours meeting ([link](https://docs.google.com/document/d/1ygRZnVtoIvuEKpwNeF_oVRVCV5NKcZD1_HMtWlUZguo/edit#heading=h.gatcmisfay0r)), @MarkEWaite and I discussed the issue of redirection. The current link we are using is not bad, but for the upcoming weeks, we could consider using the link to the blog post, which is much better suited for the situation.
=> fix(redirect): The "End of life operating systems" redirect should point to the blog post.

CONTRIBUTING.adoc, content/redirect/operating-system-end-of-life.adoc
We regularly have PRs from the fork's master to Jenkins' master.
The last one is #6409 .
This can be handled easily, but isn't it better to create PRs from another branch?
=> fix(documentation): Emphasizes on the necessity to create a branch before contributing

content/doc/developer/publishing/releasing-cd.adoc
cf. https://github.com/jenkins-infra/jenkins-maven-cd-action/blob/master/run.sh#L8
=> Get the fallback release command closer to what the GH release action does

.github/workflows/label-conflicting-prs.yml
Comments like https://github.com/jenkins-infra/jenkins.io/pull/6449#issuecomment-1579306692 just clutter the notifications, the bot will resolve conflicts on next run anyway.
=> Don't warn about conflicts in changelog PRs

content/doc/book/managing/ui-themes.adoc
Actively maintained themes are linked in the top section of the page and do not provide detailed compatibility statements.  They work because they are actively maintained, not because someone reads a compatibility statement.
=> Remove detailed theme compatibility recommendation

content/_data/roadmap/roadmap.yml
This project is discontinued.
Related: https://github.com/jenkins-infra/helpdesk/issues/3351#issuecomment-1591316525
=> cleanup(roadmap): remove `customize.jenkins.io` and "Custom Jenkins distribution build service"

content/doc/book/managing/index.adoc
We're now in 2023 and the transition from table tags to div tags is far behind us.  No need to describe that change in this page any longer.
Before the change, the page has a large disruptive gap that precedes the note about the table to div transition.  That makes the page hard to read.
After the change, the page no longer has a large disruptive gap.  That makes the page easier to read.
=> Remove 2020 tables to divs disclaimer

content/blog/2023/05/25/2023-05-25-github-sponsors-jenkinsci-org.adoc, content/doc/developer/publishing/requesting-hosting.adoc
Given the unlikely case, your commit message contains the string `jenkins-` without further numbers, you get a link to Jira, even if you don't want one.
The change proposed advises to use numeric references, to get a Jira link only if `jenkins-` is followed by numbers.
=> Advise to use numeric autolink references

content/doc/developer/tutorial-improve/update-base-jenkins-version.adoc
Hello folks :wave:
While following the [Improve a Plugin Tutorial](https://www.jenkins.io/doc/developer/tutorial-improve/) guidance, in the [Update Jenkins version](https://www.jenkins.io/doc/developer/tutorial-improve/update-base-jenkins-version/) I noticed a small inconsistency:
The `jenkins.version` that is suggested is `2.387.3`, but the bom version is `bom-2.375.x` which is inconsistent.
This small PR proposes to recommend the `bom-2.387.x` instead, with the latest version available at the time of submitting the PR.
Let me know if that makes sense to you.
Have a great day!
=> Updating bom version in tutorial-improve to current latest version

content/_partials/mailing-lists/jenkinsci-board.adoc, content/mailing-lists/index.html.haml
This PR adds a note for jenkinsci-board mailing list on https://www.jenkins.io/mailing-lists/ and a link to the Jenkins board members page.
Here is an extract of the mail response received when trying to subscribe to this mailing list:
> jenkinsci-board requires owner approval for join requests.
=> Add a note about the subscription to jenkinsci-board mailing list reserved to Jenkins board members

content/doc/book/installing/linux.adoc
This pull request is to update the installation guide for Jenkins on Linux. With the recent release of Debian 12, OpenJDK 11 is no longer delivered, so the instructions we have must be updated for OpenJDK 17.
I have tested these instructions using Parallels on my Mac, and everything appears to work properly when changing the `openjdk-11-jre` to `openjdk-17-jre`
I've also added a note at the top of the page, under the "Debian/Ubuntu" header, indicating that with the Bookworm release, this is the change/why this has changed.
=> Update Linux installation for Java 17

.typos.toml
Amends #6486.
This is more restrictive in what it allows, allowing `ede` everywhere seems risky.
Also, remove "Jenkins CNA" given "CNA" is allowed, and move "Hashi" to "HashiCorp".
`make check` passes locally for me with these changes.
=> Be more restrictive about the allowed terms in the typo check

content/blog/2023/05/30/2023-05-30-operating-system-end-of-life.adoc
We accelerated the release of the end of life administrative monitor into 2.401.2 so that administrators would be alerted 8 weeks earlier than if we waited for the release of the next LTS baseline.
Thanks to Darin Pope for catching the correction.
=> Fix dates in operating system end of life blog post

content/doc/book/installing/_docker-for-tutorials.adoc, content/doc/book/installing/_docker.adoc, content/doc/book/installing/docker.adoc, content/doc/book/scaling/scaling-jenkins-on-kubernetes.adoc
This documentation is being updated as a part of the Java 17 transition.
The Docker installation guide does not contain any specific Java version text, but I have gone through to update some of the syntax and the page formatting. Previously, the text was composed with a line limit for text, but has been updated to be more in line with Asciidoc best practices.
This is for the Docker installation and Docker installation instruction pages. The later is an include file that is part of the overall docker.adoc page.
Most of the existing text was left as is, so there is room for further improvement/updates
=> Jenkins.io - Updating Docker installation guide

content/doc/book/pipeline/docker.adoc
This pull request is to update the using Docker in Pipeline documentation for Java 17. 
Currently, the image examples used in various code blocks refer to Java 11/Temurin 11. They have been updated to reflect Java 17 usage, and have the correct versions in the respective example. This includes [maven:3.9.3-eclipse-temurin-17](https://github.com/carlossg/docker-maven/blob/51eeb2469d11acbafd4a3be13f8339ff556292fc/eclipse-temurin-17/Dockerfile) and [gradle 7.3,](https://docs.gradle.org/current/userguide/compatibility.html) as they are compatible with/support Java 17.
I have also updated some of the text to read properly and match documentation guidelines for formatting.
=> Jenkins.io - update Docker documentation for Java 17

content/doc/book/system-administration/viewing-logs.adoc
This PR is to update the link used in the code block at the bottom of the page, as it is currently using Java 11. It has been updated to use 17 and the updated link has been tested and verified.
Additionally some updates to formatting and syntax.
=> Jenkins.io - Update "Viewing Logs" to use java 17

content/doc/book/pipeline/syntax.adoc
This PR is to update the examples used in the Pipeline Syntax documentation to align with the usage of Java 17. There were several examples of either temurin-11 or jdk11 which needed to be changed accordingly.
I have also updated any use of "see" to "refer to" for inclusion and accessibility.
I have updated the document formatting to be in line with Asciidoc/our guidelines, without changing any of the code blocks/examples so as to not create any issues. There may need to be updates to the text as well, depending on accuracy/relevancy, but would need someone with more expertise to share insight on that.
=> Jenkins.io - updating Pipeline Syntax for Java 17

content/doc/book/system-administration/systemd-services.adoc
This PR is to update the "Managing systemd services page" so that it is using Java 17, to be in line with the rest of the Jenkins documentation.
The only mention that I found on this page, is in the ["Overriding service configurations"](https://www.jenkins.io/doc/book/system-administration/systemd-services/#overriding-service-configurations) section where jdk-11 is used.
This has been updated to jdk-17 accordingly.
=> Jenkins.io - Update "Managing systemd services" to use java17

content/doc/book/scaling/architecting-for-manageability.adoc, content/doc/book/system-administration/systemd-services.adoc
This PR is to update the "Architecting for Manageability" page with a Java 17 supported image.
In the [configuring a test instance section ](https://www.jenkins.io/doc/book/scaling/architecting-for-manageability/#setting-up-a-test-instance), the current example uses eclipse-temurin:11-jdk-jammy.
I have updated this to use eclipse-temurin:17-jdk-jammy instead, to align with the transition to using Java 17. There are other versions such as [17.0.3_7](https://hub.docker.com/layers/library/eclipse-temurin/17.0.3_7-jdk-jammy/images/sha256-f7b969d455abeefb9cad0280477e067d8340c22a081347a94c6fe22d0c67d420), but wasn't certain that it should be this over the base 17 version.
=> Jenkins.io - Update "Architecting for Manageability" with Java17

content/blog/2023/06/22/2023-06-22-mirrors-jenkins-new-IP.adoc, content/blog/2023/07/10/2023-07-12-jenkins-mirrors-postmortem-outage.adoc
Related to https://github.com/jenkins-infra/helpdesk/issues/3582#issuecomment-1629210833, this PR adds a new article describing the post mortem of the infrastructure outage which happenned the 7th of July 2023.
Please note that I also updated the article from June with the new IPv4 for `get.jenkins.io` as the fixes we did for the outage involved changing this IP and leading to distrurbance for end users such as https://github.com/jenkins-infra/helpdesk/issues/3661
=> blog: add an article about the 2023-07-07 outage

content/_partials/osx-brew-installer.html.haml, content/blog/2019/11/2019-11-25-macos-native-installer-deprecation.adoc
Fixes https://github.com/jenkins-infra/jenkins.io/issues/6540
The formula maintainers chose to support the latest version only, and don't maintain an archive of pinned versions, disallowing selective installations using the `@version` syntax.
If you want to use an outdated version, you'll have to package it yourself, modifying the homebrew formula.
=> Revise brew installation

content/doc/book/security/configuring-content-security-policy.adoc
Seems to work fine on https://deploy-preview-6544--jenkins-io-site-pr.netlify.app/doc/book/security/configuring-content-security-policy/
=> Add reference to system property docs to CSP page

README.adoc
The Awestruct link inside README was pointing to the Awestruct Repository page, now it points to the homepage as mentioned in the Awestruct README.
=> Fix README, Awestruct points to website instead of Awestruct Git repo

content/_data/indexpage/supporters.yml
No response from the https://spinup.com/ URL that is linked for this sponsor.
No mention of spinup.com in any of the meeting notes that I searched.
Not in https://github.com/jenkins-infra/governance-meetings-archives governance meeting archive.
Not in https://github.com/jenkins-infra/docker-confluence-data wiki data.
Not in https://github.com/jenkins-infra/helpdesk help desk tickets.
https://www.prnewswire.com/news-releases/introducing-spinup-a-simple-cloud-that-grows-with-you-301004549.html announced their existence and @olblak added them as a sponsor in April 2020
https://www.prnewswire.com/news-releases/spinup-commits-20-million-in-hosting-capacity-for-remote-learning-amid-covid-19-outbreak-301026950.html was another press release from them.
=> Remove spinup.com as a sponsor

content/_data/upgrades/2-375-1.adoc
#5370 got this right, but somehow #5721 mangled it. Unfortunately both OpenJDK and Jenkins use the _JEP_ acronym, leading to this sort of confusion. CC @kmartens27
=> Fixing “JEP 229” link

content/doc/developer/publishing/releasing-cd.adoc
I recently added CD to a plugin repo and this walkthrough and linked 'incrementals' page do not show every change needed. I wanted to include some example PRs here to help others in future.
=> Add examples of PRs for adding CD to repos

content/project/board-election-process.adoc
The change proposed documents how to create a poll in CIVS and how to create a discourse group.
Additionally, it adds the results to the 2022 election and makes contributions clickable.
I chose to remove the dates from the 2021 election without replacement, to reference this document in every year's election announcement, without the need to duplicate data.
=> Document how to create a poll in CIVS

content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/_section.yml, content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/index.adoc, content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-pomerium.adoc
Adding a link to Pomerium proxy's guide on securing Jenkins. Let me know if the guide should be fully imported instead and I will make further changes, but this will eventually result in two guides needing updates.
=> Add Pomerium reverse proxy guide

updatecli/updatecli.d/maven.yaml, updatecli/updatecli.d/node.yaml
Apologies for the first generated PR by updatecli (#6577 and #6576).
The errors were only my fault, not the tool's fault.
=> fix(updatecli): No more blog nor `.node-version` update 

content/doc/book/pipeline/shared-libraries.adoc
This PR adds an explicit example how to test in situ a shared pipeline library change.
Follow-up of https://github.com/jenkins-infra/pipeline-library/pull/718
=> Add an example how to test shared pipeline library changes

updatecli/updatecli.d/maven.yaml, updatecli/updatecli.d/node.yaml
[My previous PR](#6455) was updating `nodejs` to its latest version (current), which could represent way too much work for maintainers to test.
This PR fixes it by updating it to the latest `LTS`  version.
Please have a look at the [generated PR](https://github.com/gounthar/jenkins.io/pull/25) on my fork.
=> feature(updatecli): Updates `nodejs` to the latest `LTS` version

content/_data/changelogs/weekly.yml
Per @basil's message in https://github.com/jenkinsci/packaging/pull/409#issuecomment-1652321738, I am adding an entry to the 2.417 changelog to include the RPM/System V removal.
I have added the text as provided, and have set up the entry to be as accurate as possible, although the `pull: 409` may be unnecessary as the pull request is used for the reference link as well.
=> Jenkins.io - 2.417 changelog adding entry from packaging

content/_data/changelogs/lts.yml, content/_data/changelogs/weekly.yml
https://issues.jenkins.io/browse/JENKINS-71787 noted that the System V based initalization of Amazon Linux AMI (AL1) does not support systemd and thus cannot upgrade past Jenkins 2.416.
Amazon Linux AMI (AL1) reached end of regular support in 2020.  Extended maintenance support ends Dec 31, 2023.
- Format packaging changelog references consistently
- Explicitly note removal of System V init scripts
=> Explicitly note removal of System V init scripts

content/doc/developer/javadoc.html.haml
Minor change to align the number of items in the bullet list of LTS javadocs with the baseline recommendations.  The baseline recommendation presents the most recent LTS baseline and two baselines before it.  This change causes the Javadoc list to show the most recent LTS baseline and two baselines before it.
=> Align LTS javadoc list with baseline recommendations

content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-nginx.adoc
The `proxy_buffering off` directive was migrated from the old Jenkins wiki here, so I'm not sure why it was enabled initially. However, its use is strongly discouraged by the nginx developers in most use cases. Remove its use from the suggested nginx configuration.
See [this nginx blog post](https://www.nginx.com/blog/avoiding-top-10-nginx-configuration-mistakes/#proxy_buffering) for more details about why `proxy_buffering off` is discouraged from use. I ran across this because I attempted to set up caching of certain static files on our Jenkins server and the cache kept getting missed until I removed this.
=> Remove proxy_buffering directive from nginx config

content/_data/changelogs/weekly.yml
This PR is to adjust the weekly changelog so that the unnecessary entries are removed.
=> Jenkins.io - Update weekly.yml entries for 2.419

content/_data/changelogs/weekly.yml
Based on the [github release notes](https://github.com/jenkinsci/jenkins/releases/tag/jenkins-2.419), the changelog on jenkins.io is missing several entries. For some reason, these were not captured by the automated changelog generator, and need to be added.
@NotMyFault brought this to my attention [here](https://github.com/jenkins-infra/jenkins.io/pull/6614#issuecomment-1679179031), so I am adding these to align the changelog/release notes.
=> Jenkins.io - weekly 2.419 changelog adding entries based on github release notes

content/project/conduct.adoc
This PR is a small updated for our CoC, adapting version 2.1's changes to add several more words to the preamble: https://github.com/EthicalSource/contributor_covenant/releases/tag/2.1
Additionally, I have added a link to translations of the Contributor Covenant part.
=> Minor updated to the CoC

content/doc/book/pipeline/index.adoc
Thanks to a report in the [docs feedback form](https://docs.google.com/spreadsheets/d/1nA8xVOkyKmZ8oTYSLdwjborT0w-BpBNNZT0nxR9deZ8/edit#gid=1087292709) noting that the previous link points to a deprecated plugin.  Organization folders have been implemented in the GitHub branch source plugin for many years.
=> Footnote to GitHub branch source, not deprecated plugin

content/security/advisory/index.adoc
https://www.jenkins.io/security/advisories/ is the nicer URL for this, but in case someone's a URL editor, this makes it easier to get there.
=> Add redirect to /security/advisory/ for URL editors

content/blog/2023/09/06/2023-09-06-artifactory-bandwidth-reduction.adoc
Replace "the" with "they" in one location
=> Fix minor blog post error

content/press.adoc
The correct text had been inserted into the press page but it was above the "Trademark" heading with the incorrect SPI text under the heading.
Corrected by deleting the SPI text and moving the "Trademark" heading above the correct text that was already in the page.
=> Remove incorrect reference to SPI

content/blog/2019/02/2019-02-06-ssh-steps-for-jenkins-pipeline.adoc, content/blog/2020/03/2020-03-02-pipeline-authoring-sig-update.adoc, content/blog/2023/02/2023-02-28-build-msi-locally.adoc, content/blog/2023/04/12/2023-04-12-jenkins-march-newsletter.adoc, content/blog/2023/05/04/2023-05-04-gsoc2023-projects-announcement.adoc, content/blog/2023/07/22/2023-07-22-gsoc-2023-midterm.adoc, content/doc/book/scaling/architecting-for-scale.adoc, content/merchandise.adoc
The change proposed breaks new introduced hard links in the source files. Ideally, source files should use relative URLs inside the jenkins.io domain only, to not break linking in local development.
=> Break new hard links

content/doc/book/pipeline/syntax.adoc
AsciiDoc list formatting is broken - lists should have empty lines before and after them;
Not having them causes lists not be rendered correctly.
Fix that.
=> doc: book: pipeline: syntax: Fix 'when' directive list formatting

content/doc/book/scaling/architecting-for-scale.adoc
The WMI Windows Agent plugin no longer works and is deprecated.  It does not help users to mention a technique that cannot work.
=> Remove WMI Windows Agent reference

content/doc/developer/tutorial-improve/add-a-jenkinsfile.adoc
The [create a plugin tutorial](https://www.jenkins.io/doc/developer/publishing/new-plugin/) uses the plugin archetype to generate a Jenkinsfile that tests with Java 21 on Linux and Java 17 on Windows.  A discussion
of the reasons for that configuration is available in https://github.com/jenkinsci/archetypes/pull/651
Let's have the documentation use the same technique as is used in the plugin archetype.
=> Test with Java 17 and Java 21

content/_ext/pipeline.rb, content/_ext/security_issue.html.haml, content/_ext/security_issues.rb, content/_layouts/security.html.haml, content/security/issues/index.html.haml
This will also allow [autolinks from GitHub](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/configuring-autolinks-to-reference-external-resources).
See https://deploy-preview-6693--jenkins-io-site-pr.netlify.app/security/issues/ for the index.
It links to permalinkable URLs like https://deploy-preview-6693--jenkins-io-site-pr.netlify.app/security/issue/SECURITY-3228 that redirect to the corresponding advisory entry.
Issues that are split into two advisory entries, like https://deploy-preview-6693--jenkins-io-site-pr.netlify.app/security/issue/SECURITY-2772, link to the first (the second usually follows immediately after).
(Ideally we could do the same with CVEs, but we don't have those as cleanly in the current …
=> Add index of all published security issues

content/download/index.html.haml
Point to a Google Cloud page that is not archived.  The archived page has a scary warning that it may harm the kubernetes cluster.  The new page describes current techniques.
Use more recent Oracle Cloud destination link.  The previous page is an implementation guide, while the new link describes the architecture and provides some implementation.
=> Update links to Google Cloud and Oracle Cloud on home page

content/_data/indexpage/carousel.yml
GSoC 2023 is reaching its final days. Time to remove the annoucement from the main page carousel (aka Jumbotron)
=> Removing GSoC 2023 announcement from carousel/jumbotron

content/security/reporting.adoc
New clarification to define more precisely what the Jenkins Security team considers a vulnerability.
Secrets present in logs should not appear in the default Jenkins log recorders, but could appear in specifically configured log recorders for debugging purposes.
The log recorder description has also been adapted to be more explicit with this definition, see https://github.com/jenkinsci/jenkins/pull/8509
=> Define the level of logs containing secrets considered vulnerable

content/security/for-administrators.adoc, content/security/index.adoc
This list is not a discussion group, so is not mentioned in https://www.jenkins.io/mailing-lists/ with the associated partial.
=> Add (un)subscribe instructions for the jenkinsci-advisories list

content/security/advisory/2019-03-25.adoc, content/security/advisory/2019-08-28.adoc
At the time, we did not assign CVEs for plugins with a very low install count. These should not have been marked "CVE pending" for that reason.
The other I just forgot to add to the advisory.
=> Update 'CVE pending' from 2019

content/doc/book/installing/linux.adoc
Make the installation instructions more consistent with the packages that we include in the UBI 8, UBI 9, and AlmaLinux container images.
Make the installation instructions more consistent with the packages that are tested in the packaging repository.  https://github.com/search?q=repo%3Ajenkinsci%2Fpackaging%20fontconfig&type=code shows the current uses of fontconfig in the packaging repository.  It is used for RHEL and Debian and SUSE tests.
=> Include fontconfig in RHEL and Fedora Linux installs

content/doc/book/installing/linux.adoc
Avoid runtime warning messages from Jenkins core when Java attempts to access font definitions.
Increase consistency with the container images that install either `fontconfig`  or `libfontconfig1` in order to avoid warning messages from Jenkins core when Java attempts to access font definitions.
Increase consistency with the configuration tested in the Jenkins packaging repository.  The packaging repository tests with `fontconfig`.
Detected in https://github.com/jenkinsci/packaging/pull/431 code review by @basil.  Thanks @basil for detecting the error!
=> Include fontconfig in Debian Linux install

README.adoc
https://github.com/jenkins-infra/jenkins.io/pull/6715 added an image without proper scaling and using a wrong syntax attempting to link to jenkins.io, but linking to the image itself.
The change proposed corrects both issues.
=> Fix README image dimensions and URL

content/events/hacktoberfest.adoc
The organizers of the 2021 Hacktoberfest project to localize in French are not participating in HAcktoberfest 2023 in Jenkins.  The thread in community.jenkins.io was made private at the end of the 2021 effort.
The remaining links are useful and the French localization effort is still a good effort to continue.
=> Remove link to private topic in community

content/doc/developer/plugin-development/choosing-jenkins-baseline.adoc
Removing the placeholder processing left placeholder text in the final page.
Fixes #6748
=> Restore placeholder calculation for version selection page

content/_layouts/corebaseline.html.haml
Attempting to rectify the errors I introduced recently.
When I introduced the use of updatecli in #6717, I also removed `content/_layouts/corebaseline.html.haml`. This `Ruby` script calculates the various LTS versions that we can find in different parts of the documentation. It's also responsible for determining various weekly versions mentioned in other sections of the documentation, which I regrettably overlooked. 🤦
This is why we need to retain it until we address the other usages with `updatecli`.
@MarkEWaite spotted my mistake in #6749 and corrected it in #6751. However, because the `Ruby` script was still missing, it didn't work.
Consequently, I'm proposing this PR to reintegrate the original script so that the website can once again generate references for Jenkins weekly versions …
=> fix(documentation): corebaseline is also used for other versions than LTS.

content/_data/changelogs/weekly.yml
When viewing the Weekly release changelog, I noticed that the date is currently set as  (2023-10-09) when it should be (2023-10-10).
This PR is to update the date and correct it to today (10/10)
=> Update release date for 2.427

content/_data/changelogs/lts.yml
This PR is to add an entry to the 2.414.3 changelog for the upgrade of Winstone from 6.12 to 6.14 & Jetty from 10.0.15 to 10.0.17.
This is related to https://github.com/jenkinsci/jenkins/pull/8592 as this upgrade is being backported for the next LTS release (2.414.3)
=> Jenkins.io - LTS 2.414.3 add winstone & jetty upgrade entry

content/doc/book/installing/linux.adoc
When I set up a new Ubuntu container and install Jenkins, the installation instructions so far don't work directly because you still have to install `curl` (in addition to Java), which is unnecessary since `wget` is already pre-installed. So the command is now similar to the Fedora script.
=> Download the Debian/Ubuntu repository signature with wget, not curl

content/_data/changelogs/lts.yml
Format the link to match other CVE references in the changelog.
=> Link from changelog to CVE-2023-44487

content/doc/developer/publishing/releasing-manually.adoc
Restore a note explaining the host name that was deleted as part of #6396 (only appeared in the block removed there).
Revert improper change to sample output from #6398.
Untested.
=> Restore note on hostname, fix formatting

content/_layouts/frame.html.haml
Fixes #6785. 
Updated the `meta` tag to have the proper `property` value instead of `name` value as in the example given in the LinkedIn recommended format at https://www.linkedin.com/help/linkedin/answer/a521928.
=> Fix: Update meta tag name to property for description and og image

content/doc/book/security/access-control.adoc
**ISSUE**
Some headlines in the page are unnecessarily written in italic style.
See the issue at this link https://www.jenkins.io/doc/book/security/access-control/#common-configuration-mistakes
**WHY TO REMOVE ITALIC STYLE?**
To maintain uniformity in the documentation writing style. It will improve clarity and readability.
=>  Improved Section Headline Clarity by Removing Italic Style

content/_data/changelogs/lts.yml
This PR adds a note to https://www.jenkins.io/changelog-stable/ to warn users that short tags (without "jdk" in them) are Java 17 ones now, not Java 11, and that they have to add "jdk11" to continue using Java 11.
Related: https://github.com/jenkinsci/docker/issues/1754#issuecomment-1776772387
=> Add a note to LTS 2.414.3 changelog to warn about short tags and Java 17

content/projects/gsoc/2024/application.adoc, content/projects/gsoc/2024/index.adoc, content/projects/gsoc/2024/project-ideas.html.haml, content/projects/gsoc/2024/project-ideas/buiilding-android-app.adoc, content/projects/gsoc/2024/project-ideas/buiilding-ios-app.adoc, content/projects/gsoc/2024/project-ideas/plugin-installation-manager-tool.adoc, content/projects/gsoc/2024/project-ideas/prj-idea-template.adoc_text, content/projects/gsoc/2024/project-ideas/screenshot-automation.adoc, content/projects/gsoc/index.adoc
This PR proposes the changes to the main GSoC page for 2024 that are required to start a new iteration in the new year.
=> Update GSoC main page for 2024

content/doc/book/index.html.haml
Fixes https://github.com/jenkins-infra/jenkins.io/issues/6259
Title of the link changed from _Up to all documentation_ into `> Back to User Documentation Home`. 
_Up_ keyword was not correctly used previously, as user is sent to different page and not on top of the page.
`>` sign in front differentiates title from the table of contents and aligns with what is on top of the left side menu.
=> #6259 Improve link title

content/blog/2023/10/31/2023-10-31-marc-s-napkin-upgrade-guide.adoc
In the latest blog post that was published, there is an `author` link with a ":" that leads to a `404` error.
=> fix(documentation): Misprint.

content/_data/changelogs/lts.yml, content/_data/changelogs/weekly.yml
This PR adds a banner note to the LTS changelog about the new short `-jdk17` Docker image tags which don't contain any change but have a datetime creation a week later than the one of the initial set of tags.
Ref:
- https://github.com/jenkinsci/docker/issues/1754#issuecomment-1777733751
=> chore(changelog): add a note about the addition of short `-jdk17` LTS Docker image tags

Jenkinsfile
Reverts jenkins-infra/jenkins.io#6808 to restore #6677 
Status: https://status.jenkins.io/issues/2023-11-02-activate-delete-option-on-jenkins-io-build/
Ref: https://github.com/jenkins-infra/helpdesk/issues/3360#issuecomment-1792076471
=> Revert "Revert "Delete obsolete files on deploy""

content/redirects/distributed-builds.adoc
Follow-up of https://github.com/jenkins-infra/jenkins.io/pull/3075 from 3 years ago, this folder containing a single redirection was added temporarily.
This PR deletes it, keeping only one folder for them: https://github.com/jenkins-infra/jenkins.io/tree/master/content/redirect
=> Delete content/redirects directory

content/doc/developer/tutorial/create.adoc
I found that the quotation marks in the samples do not work in some cases (e.g. IntelliJ "Run Anything" tries to escape them) 
The result is no archetype being found:
```
[INFO] --- archetype:3.2.1:generate (default-cli) @ my-jenkins-plugin ---
[INFO] Generating project in Interactive mode
[INFO] Your filter doesn't match any archetype, so try again with another value.
````
There is no harm in removing them, the Troubleshooting section does not use them either.
=> Remove quotation marks in archetype filters

content/_data/changelogs/weekly.yml
This PR adds a banner warning about the fact the Windows image is now using Java 17 by default. (No Java 11 for this release)
Follow-up of:
- https://github.com/jenkinsci/docker/pull/1773
=> Add a banner in weekly changelog about Java 17 by default for the Windows image

content/doc/book/using/using-agents.adoc
I've worked with a few people to debug docker ssh agents, one of the main issues they have had is not including the full public SSH key information. They often leave off the ssh-XXX prefix and just have the key data itself. This adds a note to make sure people understand what information to include.
=> Add note about including the ssh-XXX prefix

content/doc/developer/tutorial-improve/automate-dependency-update-checks.adoc
I propose we add a section about GitHub Actions to the Dependabot configuration in our 'Improve a Plugin' tutorial.
This addition will provide a more comprehensive example for plugin maintainers on how to keep their plugins up-to-date.
The proposed section will cover the 'github-actions' package ecosystem in the 'dependabot.yml' file.
This is important to me because GitHub Actions are sometimes used in our repositories for various tasks.
These actions, like any other dependencies, need to be kept up-to-date to ensure we are using the most secure, efficient, and bug-free versions.
By incorporating this section, we will instruct Dependabot to check for updates to these actions on a regular basis (monthly). When Dependabot finds updates, it will automatically open pull requests to update the …
=> feat(documentation): Adds a github-actions section in the dependabot sample file.

content/projects/gsoc/2023/index.adoc
Fixed a link on the current /gsoc/index page for the year 2023. 
Retained contents from 2023.
=> feat: Replace gsoc redirection with actual contents for 2023

content/projects/gsoc/2022/index.adoc, content/projects/gsoc/2023/index.adoc
Prior to 2022, the page titles for the GSoC summaries were using a slightly different form than the most recent two page titles.  Adjust the page titles to match the previous years.
Adjust the page descriptions to include the year of the GSoC project.
=> Use consistent page titles for GSoC summaries

content/projects/gsoc/students.adoc
The 2023 ideas are good reference material as well, but those project ideas that are still viable from 2023 should be copied into the 2024 project ideas.
=> Link to GSoC 2024 ideas

content/_data/changelogs/lts.yml
This PR adds a note about the change of base image and tag naming, similar to the notes added to the 2.432 weekly changelog and the controller image release: https://github.com/jenkinsci/docker/releases/tag/2.432
Ref:
- https://github.com/jenkinsci/docker/pull/1770
- https://github.com/jenkins-infra/jenkins.io/pull/6843
=> Add a banner in 2.426.1 LTS changelog about noticeable changes for the Windows images

content/_data/changelogs/lts.yml
[Illegal base64 character](https://issues.jenkins.io/browse/JENKINS-61452) was fixed in 2.414.2, remove it from the 2.426.1 changelog
=> Remove extra entry from 2.426.1 changelog

content/_data/changelogs/lts.yml, content/_data/upgrades/2-426-1.adoc
The [blog post](https://www.jenkins.io/blog/2023/11/06/introducing-2-2-2-java-support-plan/) announces the support and our social media feeds include it.  We should also include it in the changelog.
=> Add Java 21 support to changelog and upgrade guide

content/doc/developer/architecture/remoting.adoc
The adoc has formatted the symbols and substituted the < = > to include arrows, so currently this text is harder to follow. I have removed the symbol substitution. (See how it is rendered [here](https://www.jenkins.io/doc/developer/architecture/remoting/))
See https://github.com/jenkinsci/remoting for original text, and https://docs.asciidoctor.org/asciidoc/latest/subs/prevent/ for adoc editing.
=> Prevent symbol substitution

content/_data/changelogs/weekly.yml
There was a [PR from the packaging repo](https://github.com/jenkinsci/packaging/pull/442#event-11080547837) that was merged earlier today that should have been included in the weekly changelog.
This pull request is to add the entry to the changelog so that it is properly represented.
=> jenkins.io - add packaging entry to weekly 2.434 changelog

content/doc/book/managing/system-properties.adoc, content/doc/developer/initialization/embedded-container.adoc, content/doc/developer/initialization/index.adoc
This repository was archived about a year ago and inlined into Jenkins core.
=> Remove references to archived `executable-war` GitHub repository

content/_data/roadmap/roadmap.yml
[JENKINS-63286](https://issues.jenkins.io/browse/JENKINS-63286) was completed in February but never marked as released in the public roadmap.
=> Mark JENKINS-63286 as released

content/doc/developer/plugin-development/_chapter.yml, content/doc/developer/plugin-development/split-plugin-from-core.adoc
Apparently this content was neither migrated from https://wiki.jenkins.io/display/JENKINS/Split-plugin-from-core.html nor was there a ticket filed for its migration.
=> Migrate documentation about splitting a plugin from the old wiki

content/_data/changelogs/lts.yml
Hi,
I noticed looking at the changelog-lts that the first mention of Guice 6.x (and `jakarta.inject`) was in Jenkins 2.414.1.
The first LTS release using Guice 6.x was in 2.401.2 (https://github.com/jenkinsci/jenkins/pull/8121 | [discussion](https://groups.google.com/g/jenkinsci-dev/c/jPh07uaqv1o/m/sVhT7GCpAgAJ)).
Interested in updating this because I'd like to link to it while sending PRs from the OpenRewrite Jenkins modernization recipe: https://github.com/openrewrite/rewrite-jenkins/pull/53
=> Move Guice 6.x Upgrade to 2.401.2

content/_data/changelogs/lts.yml
https://github.com/jenkinsci/jenkins/pull/8065 was first included in 2.408 and was not backported to any of the 2.401.x releases.
https://github.com/jenkinsci/jenkins/pull/8121 was backported to 2.401.2.
=> Restore javax.inject to jakarta.inject to 2.414.1

content/_data/changelogs/weekly.yml
Found while working through a history question
=> Fix 2.428 release date in changelog

content/doc/book/scaling/architecting-for-scale.adoc
Original: Jenkins should have its "our" LVM setup
New: Jenkins should have its own LVM setup
=> Update architecting-for-scale.adoc. Fix typo

content/_layouts/post.html.haml
The aspect ratio of iframes aren't preserved when browsing jenkins.io from a mobile:
Works perfectly on all pages with both mobile resolution and desktop resolution.
**Apologies for recreating the pull request, but I have adjusted the PR as per @zbynek  suggestions.[comment ](https://github.com/jenkins-infra/jenkins.io/pull/6870#issuecomment-1826833974)**
=> preserve the aspect ratio of iframe on mobile #6869

content/_data/authors/harsh-ps-2003.adoc, content/projects/gsoc/2024/project-ideas/enhancing-an-existing-llm-model-with-domain-specific-jenkins-knowledge.adoc, content/projects/gsoc/2024/project-ideas/using-opentelemetry-for-jenkins-jobs-on-ci_jenkins_io.adoc
Hey,
I would also like to be the mentor for GSoC 2024 for the following projects:
1. [enhancing-an-existing-llm-model-with-domain-specific-jenkins-knowledge 2](https://www.jenkins.io/projects/gsoc/2024/project-ideas/enhancing-an-existing-llm-model-with-domain-specific-jenkins-knowledge/)
2. [using-opentelemetry-for-jenkins-jobs-on-ci_jenkins_io 1](https://www.jenkins.io/projects/gsoc/2024/project-ideas/using-opentelemetry-for-jenkins-jobs-on-ci_jenkins_io/)
I believe my Jenkins plugin development and Infrastructure knowledge can be a valuable addition to the projects!
Thanking you in Anticipation
Warm Regards
=> adding myself as potential mentor for GSoC 2024

content/_data/changelogs/lts.yml
Fix link to end of Java support changelog entry for 2.426.2.  Was included in:
* https://github.com/jenkinsci/jenkins/pull/8661
=> Fix link to end of Java support changelog entry for 2.426.2

Jenkinsfile
As suggested by @zbynek in https://github.com/jenkins-infra/jenkins.io/issues/6316#issuecomment-1854576801, this PR adds a step to purge the cached CSS from Fastly.
=> chore: add a step to purge cached CSS

content/_layouts/changelog.html.haml
This PR sets the height as CSS style instead of HTML attribute.
Fixes #6951
=> fix: correct RSS icon height in /changelog

updatecli/scripts/jenkins-lts-baseline.sh, updatecli/updatecli.d/jenkins-lts.yaml
In #6945, [@MarkEWaite pointed out](https://github.com/jenkins-infra/jenkins.io/pull/6945#pullrequestreview-1780165327) that the change proposed by my updatecli manifest was incorrect.
> In this case, we want to recommend the initial release of the most recent LTS baseline (for example, 2.426.1) , not the most recent release of the most recent LTS baseline (for example 2.426.2 or 2.426.3). We rarely allow backporting of a new feature to later releases of an LTS line.
My initial implementation was naive, and I hadn't captured the full complexity of variations within LTS versions for Jenkins.
I am now proposing this change, which adds another Jenkins source (the latest baseline) and incorporates it into the `content/doc/developer/plugin-development/choosing-jenkins-baseline.adoc` file.
=> chore(dependencies): Now finds the latest baseline.

content/doc/developer/plugin-development/build-process.adoc
Asciidoc documentation says that the footnote macro should be immediately after the item it is annotating, just as this footnote is.  I assume that means the footnote text was the problem because it contains a punctuation character.  When I remove that punctuation character, the footnote renders correctly.
Fixes #6940
=> Render footnote correctly

content/doc/developer/plugin-development/dependencies-and-class-loading.adoc
I am removing this "feature" in https://github.com/jenkinsci/jenkins/pull/8785 and https://github.com/jenkinsci/maven-hpi-plugin/pull/563.
=> Remove reference to `globalMaskClasses`

content/doc/developer/publishing/releasing-cd.adoc
Outlines that the first syntax is our default syntax for CD.
=> Outline which CD format is the standard

content/doc/tutorials/build-a-python-app-with-pyinstaller.adoc
We use Python 3, not Python 2, since Python 2 is no longer supported.
=> Remove reference to Python 2

.github/workflows/label-conflicting-prs.yml, .github/workflows/updatecli.yaml
Recently, GH disabled actions for new forks by default, however, this change does not affect existing contributors, causing workflows to run on your forks too, e.g. https://github.com/NotMyFault/jenkins.io/actions
If you don't opt-out email notifications, you end up with numerous mails notifying you that a workflow failed on your fork.
I'd propose to run our internal workflows in this repository only, given you don't need these on your fork when contributing.
=> Restrict internal workflows to 'jenkins-infra'

content/doc/book/managing/system-properties.adoc
Document the escape hatch introduced in jenkinsci/jenkins#8815.
=> Document `REQUIRES_DIR_FSYNC` escape hatch

content/_data/indexpage/supporters.yml
Due to recent changes in the Continuous Delivery Foundation, Red Hat is no longer a member of the foundation, and therefore would not be considered a sponsor of Jenkins.
This PR is to remove the logo & link from the supporters carousel at the bottom of the top level page, so that there is no misinformation being shared.
=> Jenkins.io - Remove Red Hat as a sponsor

content/projects/remoting/index.adoc, content/redirect/project/remoting/changelog.adoc, content/redirect/project/remoting/protocols/jnlp2-errata.adoc, content/redirect/project/remoting/protocols/jnlp3-errata.adoc
Inspired by the question from @lemeurherve in https://github.com/jenkinsci/jenkins/pull/8836#issuecomment-1881741506
- Improve remoting redirects
- Redirect to current remoting changelog
- Minor phrasing improvements
=> Improve remoting documentation

content/doc/book/using/best-practices.adoc
The link of Throttle Concurrent Build Plugin was set wrong. Link was set to [here](https://plugins.jenkins.io/throttle-concurrent-builds)
I updated to proper [link](https://plugins.jenkins.io/throttle-concurrents/)
=>  Fix Throttle Concurrent Build plugins's link

content/blog/2023/05/30/2023-05-30-operating-system-end-of-life.adoc
[JENKINS-72546](https://issues.jenkins.io/browse/JENKINS-72546) is a recent request that shows OpenSSH versions before 7.6 are still being used.  Assure that readers know that Amazon Linux 2 is no longer supported because it is a derivative of Red Hat Enterprine Linux 7.
Usually we don't revise blog posts, but this blog post is frequently referenced.  I think it is better to revise the blog post than to post repeated additions to the phrasing of the blog post.
=> [JENKINS-72546] Include Amazon Linux 2 in RHEL 7 derivatives

content/blog/2024/01/2024-01-17-jenkins-contributor-summit-update.adoc
This proposed blog post gives additional details about the coming Jenkins Contributor Summit.
=> blog - contributor summit update

content/doc/developer/plugin-development/dependency-management.adoc, content/doc/developer/tutorial/prepare.adoc
When not set `~/.m2/settings.xml`, will return `Project does not have a parent` error when execute `mvn versions:update-parent` command.
=> add content for set maven settings.xml

content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/_context_path.adoc, content/projects/gsoc/2024/project-ideas/adding-additional-probes-to-plugin-health-score.adoc, content/projects/gsoc/2024/project-ideas/automatic-specification-generator-for-jenkins-rest-api.adoc, content/projects/gsoc/2024/project-ideas/automating-rpu-for-jenkinsci-organization.adoc, content/projects/gsoc/2024/project-ideas/cloudevents-plugin.adoc, content/projects/gsoc/2024/project-ideas/enhancing-an-existing-llm-model-with-domain-specific-jenkins-knowledge.adoc, content/projects/gsoc/2024/project-ideas/fixing-backend-extension-indexer-tool.adoc, content/projects/gsoc/2024/project-ideas/implementing-ui-for-jenkins-infra-statistics.adoc, content/projects/gsoc/2024/project-ideas/plugin-installation-manager-tool.adoc, content/projects/gsoc/2024/project-ideas/screenshot-automation.adoc, content/projects/gsoc/2024/project-ideas/using-bearer-token-authentication-for-the-git-plugin-and-git-client-plugin.adoc, content/projects/gsoc/2024/project-ideas/using-openrewrite-recipes-for-plugin-modernization-or-automation-plugin-build-metadata-updates.adoc, content/projects/gsoc/2024/project-ideas/using-opentelemetry-for-jenkins-jobs-on-ci_jenkins_io.adoc
Moving some projects from "draft" to "published" in preparation for the GSoC 2024 org applications to take place over the next few days, as well as adding details such as project size and difficulty, and adding a new project idea for the backend-extension-indexer as @MarkEWaite suggested.
=> Get GSoC 2024 projects ready for org application

content/projects/index.adoc
The change proposed fixes the JCasC logo scaling on https://www.jenkins.io/projects/. The variable to set should be the width and not the height.
Before:
After:
=> Fix scaling of JCasC on projects page

Jenkinsfile
This PR adds another CSS to purge on publication.
Ref:
- https://github.com/jenkins-infra/jenkins.io/pull/7066#issuecomment-1943540449
=> chore: purge `stylesheets/styles.css` on publication

content/blog/2024/01/2024-01-29-nominate-someone-2024-jenkins-contributor-awards.adoc
This PR is to add the voting deadline to the 2024 Community Awards post. @lemeurherve rightfully noticed and shared, so that this can be adjusted accordingly.
=> Add voting deadline to Community Awards blog post

content/stylesheets/components/_avatar.scss
Fixes #7082
Updated CSS so that the images for avatars work in safari.
=> fix avatar img on safari browser for GSoC project ideas page

content/artwork/index.html.haml
Corrected link on the Jenkins Artwork page that credits Frontside for artwork of original Jenkins logo.
=> Correct link to Frontside

content/doc/developer/forms/form-validation.adoc
I recently reworked an old plugin and there someone always used a more meaningful name for the variable as just `value`. I think this helps writing cleaner code.
=> Update form-validation.adoc to include possibility to change variable

content/_partials/anchors.html.haml, content/css/jenkins.css
Problem with:
Any documentation page
Eg. https://www.jenkins.io/doc/book/installing/
Existing Issue:
As mentioned by @lemeurherve in this [comment](https://github.com/jenkins-infra/jenkins.io/pull/7077#issuecomment-1947330743), the anchor only displays when hovered on the right side.
This PR offers a swift solution to address the issue and ensures the anchor is displayed when hovering over the title. However, it should have analyzed the underlying cause because I have tested it with various projects where the hover effect occurs without necessitating these alterations.
=> Display anchor when hovering over the title

content/css/jenkins.css
This increases the distance to the top slightly when jumping to an anchor, so that the text is not directly below the menu bar.
Example: https://www.jenkins.io/security/#advisories
=> Increase anchor distance to menu bar

updatecli/updatecli.d/docker-workflow.yaml
The regex used in my updatecli manifest was quite off, and it was removing everything after docker-workflow:. This change should fix it (at least, it does on my machine 🤷 ).
=> fix(updatecli): Fixes #7093.

updatecli/updatecli.d/blueocean.yaml
The regex used in my updatecli manifest was quite off, and it was removing everything after `blueocean:`:. This change should fix it (at least, it does on my machine 🤷 ).
=> fix(updatecli): Fixes #7086.

content/doc/developer/publishing/releasing-cd.adoc
The change proposed updates the default branch matching your defined default branch, when copy/pasting the sample to cut a manual release, in case it's not `master`.
=> Update default branch checkout for manual CD

content/_data/changelogs/lts.yml, content/security/advisory/2024-01-24.adoc
Do not merge this PR before LTS 2.440.1 is published.
=> Include 2.440.1 in list of releases with fix for 2024-01-24 core vulnerabilities

content/projects/gsoc/2024/project-ideas/adding-additional-probes-to-plugin-health-score.adoc
I won't be able to mentor this year finally. 
I'll still be able to do code reviews as normally I should still have time to work on plugin-health-scoring.
=> Removes alecharp from mentor list on GSOC 2024

content/projects/jcasc/index.adoc
This PR is to fix Gitter broken format of JCasC on projects page.  Might related to #3335 
**Page URL:** https://www.jenkins.io/projects/jcasc/#time-and-location
**Current format was broken:**
**Resolution:**
- Adding `++` around the URL with special characters would help
- Asciidoctor Documentation: https://docs.asciidoctor.org/asciidoc/latest/macros/link-macro/#when-to-use-the-link-macro
- Something like: `link:++https://example.org/now_this__link_works.html++[]`
=> jcasc: Fix Gitter broken format of JCasC on projects page

Jenkinsfile
This PR uses the correct `./build/_site` local path cf https://github.com/jenkins-infra/jenkins.io/blob/2cf0d355d01da358cfe0b836e69695160ca2ccbd/scripts/blobxfer#L24
Tested via a replay of the primary branch job on trusted.ci.jenkins.io
Fixup of:
- #7123 
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/3414
=> fixup: correct local path passed to `azcopy`

content/_data/changelogs/weekly.yml
The weekly changelog contains a developer entry, but I forgot to remove the extra * at the beginning of the Developer text.
This is to remove the extra character
=> Removing character from weekly 2.447 changelog entry

content/doc/book/pipeline/development.adoc
The current instructions seemed to be written for a configuration we should not support by writing dedicated documentation for it.
=> Update declarative-linter HTTP API instructions for authenticated use

content/projects/gsoc/2023/index.adoc, content/projects/gsoc/2024/project-ideas/cloudevents-plugin.adoc, content/projects/gsoc/index.adoc
1. Added some new reference links for GSoC 2024
2. Fixed / added some reference links for GSoC 2023
3. Edited the GSoC 2024 CloudEvents plugin project idea page
=> Fix/add links and edit CloudEvents plugin project idea page

Makefile
Always annoyed me, when I hit `make run` 😄
=> Remove obsolete space in 'make run'

content/blog/2018/02/2018-02-19-gsoc2018-announcement.adoc, content/blog/2019/03/2019-03-04-gsoc2019-announcement.adoc, content/blog/2020/01/2020-01-29-gsoc-report.adoc, content/blog/2021/03/2021-03-17-gsoc2021-announcement.adoc, content/blog/2022/03/2022-03-08-gsoc2022-announcement.adoc, content/blog/2022/11/2022-11-23-get-prepared-for-gsoc.adoc, content/blog/2023/02/2023-02-01-gsoc-update.adoc, content/blog/2023/02/2023-02-23-gsoc2023-announcement.adoc, content/blog/2024/02/2024-02-23-gsoc2024-announcement.adoc, content/projects/gsoc/2022/application.adoc, content/projects/gsoc/2022/index.adoc, content/projects/gsoc/2023/index.adoc, content/projects/gsoc/2024/application.adoc, content/projects/gsoc/2024/project-ideas/cloudevents-plugin.adoc, content/projects/gsoc/2024/project-ideas/enhancing-an-existing-llm-model-with-domain-specific-jenkins-knowledge.adoc, content/projects/gsoc/contributors.adoc, content/projects/gsoc/index.adoc, content/projects/gsoc/mentors.adoc, content/projects/gsoc/roles-and-responsibilities.adoc, content/projects/gsoc/students.adoc
Fixes #7157
1. Corrected / expanded content of some GSoC 2024 project idea pages.
2. Updated the URL for contributor-dedicated contents.
=> Fix: Make some GSoC 2024-related changes

content/doc/developer/plugin-development/_chapter.yml, content/doc/developer/plugin-development/usage-in-plugins.adoc
Following up on the Jenkins Contributor Summit, retain the content of my presentation about usage in plugins by improving the developer documentation.
To test this, I ran `make run` and visually inspected the new page. I also ensured the navigation was updated so the new page was reachable.
=> Add developer documentation about usage in plugins

content/download/verify.adoc
The signature algorithm used for the Jenkins war file has been strengthened with the most recent update of the Jenkins war signing ceritifcate.  Use the current string in the sample output.
The plugins site no longer has a tab called "Archives".  It is now the "Releases" tab and does not include the checksums for the plugin releases.  Link to the update center page that includes the checksums for plugins.
=> Update the download verification instructions

content/doc/book/security/controller-isolation.adoc
This seems out of place here. It's an important issue to consider, but mentioning here in this manner and then never picking it up again seems wrong.
=> Remove mention of supply chain attacks

content/project/governance-meeting/index.adoc
The change proposed replaces the embedded google doc with hackmd, what we are using now to take notes.
=> Replace embedded google doc with hackmd in governance meeting page

content/project/teams/hosting.adoc
The repository linked does no longer exist.
=> Remove outdated URL from hosting team page

content/_data/changelogs/lts.yml
Just a small typo in the date (always a challenge remembering the new year, isn't it? :) )
=> Update lts.yml: fix typo in 2.440.2

content/_data/changelogs/weekly.yml
This PR is to add an entry to the 2.451 changelog stating that Debian 10 and Ubuntu 20.04 are the new minimum required versions. I have included the packaging pull request as expected, and added the Debian 10/Ubuntu 20.04 release notes as additional resources for the changelog.
=> Jenkins weekly 2.451 - add entry for Debian 10 & Ubuntu 20.04 requirement

content/_ext/solutionpage.rb, content/_ext/upgrade_guide.rb
<details>
<summary>Before</summary>
```
$ make run
LISTEN=true ./scripts/awestruct --dev --bind 0.0.0.0 --source-dir=content --output-dir=build/_site
Using profile: development
Generating site: http://localhost:4242/
Executing pipeline...
Loading solution pages
= Imported solution /Users/danielbeck/Repositories/github.com/daniel-beck/jenkins.io/content/solutions/android.adoc as /s/android/index.html
= Imported solution /Users/danielbeck/Repositories/github.com/daniel-beck/jenkins.io/content/solutions/bitbucketserver.adoc as /s/bitbucketserver/index.html
= Imported solution /Users/danielbeck/Repositories/github.com/daniel-beck/jenkins.io/content/solutions/c.adoc as /s/c/index.html
= Imported solution /Users/danielbeck/Repositories/github.com/daniel-beck/jenkins.io/content/solutions/docker.a …
```
=> Remove unnecessary debug output

content/sigs/docs/index.adoc
As pointed out by @halkeye in the [docs gitter channel](https://matrix.to/#/!MWIrtxEAtbSRBOpnfE:matrix.org/$CkyxbzCAed89DpAYIVyGypEzrO6ID9GRXmTNHIDthjY?via=g4v.dev&via=gitter.im&via=matrix.org), the existing Docs SIG page is a bit out of date. The members do not reflect current activity and the projects listed are presented as current, where most of them have been completed in one sense or another.
This PR is to update the Docs SIG members, format some of the headers, add syntax/content where needed to clarify that projects are either completed or not being done anymore.
For example, we are not currently participating in Google Season of Docs, and do not have plans to apply any time soon, so we should not be presenting it as though it is a possibility. Similarly, we are no longer looking …
=> Updating Docs SIG page members and content to be current

content/security/advisories/rss.xml.haml
Untested.
This should take care of
> [line 20](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.jenkins.io%2Fsecurity%2Fadvisories%2Frss.xml#l20), column 0: Undefined item element: date (74 occurrences) [[help](https://validator.w3.org/feed/docs/error/UndefinedElement.html)]
>
>     <date>
Addresses part of https://github.com/jenkins-infra/jenkins.io/issues/7219.
How this even happened in the first place? No clue. Tolerant RSS readers?
=> Fix RSS error, it's `pubDate` and not `date`

content/security/advisories/rss.xml.haml
Untested.
This should take care of 
> [line 417](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.jenkins.io%2Fsecurity%2Fadvisories%2Frss.xml#l417), column 0: Undefined description element: li (3 occurrences) [[help](https://validator.w3.org/feed/docs/error/UndefinedElement.html)]
> 
>        <li>Affects update-center2</li>
Addresses part of #7219.
=> Correctly encode other components in advisories RSS feed

content/doc/developer/forms/jelly-form-controls.adoc
Update `jelly-form-controls.adoc` to link to design-library-plugin. It anyhow redirects there, but I guess mentioning the deployed version on weekly might also be useful for others.
=> Update jelly-form-controls.adoc to link to design-library-plugin

content/doc/book/pipeline/syntax.adoc
Declarative pipelines need a plugin to actually run. Without it, they will seemingly succeed as there are no errors or warnings, but actually nothing happens and no pipeline code is executed. This results in a bad user experience:
> The evil part about it is that the job just runs silently without complaing about the DSL  – 
[Kutzi](https://stackoverflow.com/questions/71218985/jenkins-pipeline-script-not-running#comment130432822_71247427)
The only hint to this plugin I could find wasn't in the Jenkins docs but in [this StackOverflow answer](https://stackoverflow.com/a/71247427), so I added a notice.
=> Add installation notice for required declarative pipeline plugin

content/doc/book/installing/_docker.adoc
Fix the ordering of the list in the docker install instructions, previously the note was displayed under the 12th bullet point which is not intended behaviour (i assume)
before:
after:
=> Improve layout of list in docker install instruction

content/doc/book/pipeline/running-pipelines.adoc
There was an ambiguity regarding the maximum number of build stashes allowed, eighter 50 or 5. I changed it to 5
=> fix: typo on webpage running-pipelines

content/doc/developer/publishing/releasing-cd.adoc
Companion PR to https://github.com/jenkins-infra/repository-permissions-updater/pull/3879, which should only be merged after that PR is merged.
=> Docs changes for jenkins-infra/repository-permissions-updater#3879

content/doc/developer/tutorial-improve/update-base-jenkins-version.adoc
The Jenkins version is maintained by the updatecli scripts but this diff seems to have become outdated.  Make it match the text in the body of the document.
=> Use same Jenkins version in sample diff as in body text

content/project/governance-meeting/index.adoc
Readers that need the archived copies of the agenda should not look for them in HackMD.  We use HackMD as a real-time editing facility for markdown of the upcoming meeting.  During the meeting, we use it to take notes for the current meeting.  After the meeting, the notes are copied to the archive locations.
I think this may address a concern that was expressed by @daniel-beck.  Even if it fails to address that concern, I think this is a worthwhile change.
=> Remove date dependent phrase from governance agenda link

content/doc/book/using/best-practices.adoc
The current documentation shows these characters normally, whereas I believe the intent was to format them using the code span ``.
I have adjusted the characters so that they are enclosed with parenthesis but still capture the alphanumeric characters as entry text.
Current:
Updated:
=> Pipeline Best Practices - small update to format characters

content/doc/developer/publishing/wiki-page.adoc
This PR is to update the text on the wiki-page docs page, for punctuation and some grammar. The other major change was adding an anchor to the "Reviewing the documentation" so that step 6 links to the section instead of just saying it is "below".
This also includes the suggested updates from https://github.com/jenkins-infra/jenkins.io/pull/7204 so it should not be merged until that is approved and merged.
=> Developer Documentation - update for wiki migration page

content/security/reporting.adoc
Unsure about the wording here given the `xz` situation, but I'd still like to cut down the noise. I don't want to claim that these tools would _never_ identify anything of value, but so far their specificity seems to be pretty terrible.
=> Snake oil be snake oiling

content/_layouts/post.html.haml
Small fix following https://github.com/jenkins-infra/jenkins.io/pull/7173. Currently clicking the 'Back to blog' link redirects to `/node` which results in a redirect page, this PR fixes that by taking the user directly to `/blog`.
=> Fix 'Back to blog' link redirecting to `/node`

content/_data/changelogs/weekly.yml
- **Fix typo in 2.445 changelog** -- "matrixbased" -> "matrix-based"
- **Fix typo in 2.448 changelog** -- "NonPipeline" -> "Non-Pipeline"
- **Insert missing space in 2.449 changelog**
=> Fix minor typos in weekly changelog

content/_data/indexpage/carousel.yml
This PR is to update the main page carousel so that the previous GSoC item is replaced with the accepted projects announcement. It utilizes the image used for the blog post's opengraph image.
=> GSoC 2024 - Update carousel for accepted proposal announcement 

CONTRIBUTING.adoc
When reviewing the blog posting guidelines in the contributing guide, the date of January 1st 1970 could appear a bit misleading when formatted as `1970-01-01`. Since EU and US dates are formatted differently, this 01/01 does not portray a clear usage, so the suggested change to `1970-01-15` is so that it is clear which is the month and which is the day.
=> Contributing guide - small change to make the date formatting more obvious

content/_data/changelogs/weekly.yml
This PR is to adjust the message for the changelog entry regarding tooltips. The current message includes the JIRA ticket number and does not have correct punctuation.
=> Jenkins 2.457 - adjust message for changelog entry

content/project/governance-meeting/index.adoc, content/project/governance.adoc
As agreed in governance meeting today.  Switch to the meeting pace that we use in the UX SIG, every four weeks, with the option to meet more often whenever needed.
=> Governance meeting happens every 4 weeks

content/project/governance.adoc
Governance meeting is only a video call, not an IRC meet as in the past.
Governance meeting is the same as the project meeting.  Remove the references to project meeting.
Link to community.jenkins.io and the GitHub repository and the YouTube playlist.
=> Minor improvements to governance docs

content/projects/gsoc/2024/projects/automating-rpu-for-jenkinsci-organization.adoc, content/projects/gsoc/index.adoc
Added GSoC 2024 Manage Jenkinsci GitHub Permissions as Code project page.
=> Update GSoC project list with RPU

content/projects/gsoc/2024/projects/automating-rpu-for-jenkinsci-organization.adoc
Added Rajiv Singh as co-mentor for the GSoC 2024 [Improve Maintainability for the Repository Permission Updater](https://www.jenkins.io/projects/gsoc/2024/projects/improving-maintainability-of-rpu) project. 
c.c. @NotMyFault
=> feat: add rajiv as co-mentor for gsoc 2024 automating rpu project

content/blog/2024/05/2024-05-01-google-summer-of-code-congrats-and-welcome.adoc
Incorrectly included the same link for GSoC project 1 and GSoC project 5.
Now uses the correct link for GSoC project 5.
Also removes trailing spaces from other lines in the blog post.
=> Use correct link to GSoC project 5

content/doc/developer/plugin-development/build-process.adoc
Since the build process document is describing an update to the parent pom, let's include a link to the "Improve a plugin" tutorial topic that addresses it.  Some readers might benefot from seeiong the steps in text and others might benefit from the tutorial video.
=> Link from plugin build process doc to tutorial

content/doc/tutorials/build-a-java-app-with-maven.adoc
Line 313:  The command 'docker compose down -v --remove-orphans' will not shut down all the running containers. Noticed this bug and proposed a fix with the replaced command 'docker compose --profile maven down -v --remove-orphans' .
=> docker compose down fix

content/participate/report-issue.adoc
The document has all the information bout Jira and GitHub issues, but the first mention of plugin issues only mentions GitHub which is confusing (see #7337)
Preview: https://deploy-preview-7338--jenkins-io-site-pr.netlify.app/participate/report-issue/#Howtoreportanissue-Beforecreatinganissue
=> Mention Jira x GitHub distinction in issue reporting

content/doc/developer/publishing/releasing-cd.adoc
see https://github.com/jenkins-infra/repository-permissions-updater/pull/3970#issuecomment-2163312089
It asks you to create it before you've done the plugin changes, I think that has tripped a couple of people up recently
=> Re-order cd releasing page

content/_data/indexpage/supporters.yml, content/blog/2024/06/2024-06-13-thanks-mirror-sponsors.adoc, content/download/mirrors.adoc
Related to https://github.com/jenkins-infra/helpdesk/issues/3976
This PR adds a blog post to thanks our mirror providers in particular the new one (and also @C-Otto from the RTWH Aachen for his help - https://github.com/jenkins-infra/helpdesk/issues/4128).
It also updates the mirrors page and the supporters list.
Reviewers: do not hesitate to amend this PR if you feel like it is needed. My goal is to publish visible things for our supporters!
=> Update mirrors page, supporters and add a blog post to announce hostico

content/doc/book/platform-information/support-policy-java.adoc
This PR is to add another line to the Java Support policy documentation that includes the upcoming requirement for Java 17. Since this will be part of the weekly release for 2.463, the LTS piece was filled in with N/A for now, but can always be updated. If that should be changed to October 2024 (based on Basil's blog post information), that can be done so that it is more clearly outlined ahead of time.
=> Platform Information - add line for Java 17 requirement in weekly to support table

content/doc/pipeline/tour/hello-world.adoc
It is not clear to me why the updatecli process did not propose changes for these containers.  It is especially curious that some cases remained very far out of date on older Alpine versions and at least one case had an update in the declarative Pipeline example that was not matched in the scripted Pipeline example.
Switches the Maven example to use Java 21.
=> Update container images versions in hello-world tutorial

STYLEGUIDE.adoc, content/doc/book/pipeline/docker.adoc, content/doc/pipeline/tour/agents.adoc
<Actions>
<action id="651f9b43b3cb77399a9a3a2acf5f7cb4b5cbafd0c8a53ccf4e8e1ec8b505fbf6">
<h3>Bumps the node docker images versions</h3>
<details id="a89e17342ac4ddd5b3c9b824f0828de21e441607273b89928439cdb7b3952431">
<summary>Update the value of the node docker image in the &#39;Using Docker with Pipeline&#39; documentation</summary>
<p>1 file(s) updated with &#34;${1}node:20.14.0-alpine3.20${3}&#34;:&#xA;&#x9;* content/doc/book/pipeline/docker.adoc&#xA;</p>
<details>
<summary>20.14.0</summary>
<pre>&#xA;Release published on the 2024-05-28 16:55:37 +0000 UTC at the url https://github.com/nodejs/node/releases/tag/v20.14.0&#xA;&#xA;### Notable Changes&#xD;&#xA;&#xD;&#xA;* \[[`28d2baa17c`](https://github.com/nodejs/node/commit/28d2baa17c)] - **src,permission**: throw async errors on async …
=> [Tutorials and Agents Docs] Bump node LTS alpine docker image version to 20.14.0-alpine3.20

updatecli/updatecli.d/maven.yaml, updatecli/updatecli.d/node.yaml, updatecli/updatecli.d/python.yaml
As @MarkEWaite mentioned in #7364, some of the container references were no longer being updated.
This issue arose due to a refactoring of certain tutorial files, which involved removing Docker image references.
This PR aims to rectify the problem.
Mark also moved some image references to [JDK21](https://github.com/jenkins-infra/jenkins.io/pull/7364/files#diff-aa16972264f9707580a69bb0482bff4a81968c46ae2adaaf495c34e0986fb60cL59), so I'm following his path, and proposing to use JDK21 too in the `updatecli` manifests.
=> fix(updatecli): Manifest no longer reflects the status of the repository.

content/doc/developer/publishing/releasing-cd.adoc
I had a question from someone new to Jenkins why they could not see the `incrementalified.pom.xml`   The reason was obvious to me, but looking at the docs it was easy to see how this confusion arose.
This makes it more obvious that the `pom.xml` is in a different sentence by starting the sentence with a word
=> Make it more obvious that this is a new sentence

content/doc/developer/plugin-development/optional-dependencies.adoc
Use `Jenkins.get()` instead of deprecated `getInstance()` method
=> Use `Jenkins.get()` instead of deprecated method

content/_data/donors/donors.json
- Major sponsors are listed on the jenkins.io home page.
- Recent discussions in [Advocacy and Outreach meetings](https://docs.google.com/document/d/1K5dTSqe56chFhDSGNfg_MCy-LmseUs_S3ys_tg60sTs) with @krisstern and @alyssat highlighted a lack of information about financial contributions to the Jenkins project.
- There have been discussions, [PRs](https://github.com/jenkins-infra/jenkins.io/pull/6882), and [issues](https://github.com/jenkins-infra/jenkins.io/issues/6861) about new ways to recognize various types of contributions.
We suggest adding information about financial contributions:
1. Display this information on the sponsors' page.
2. Keep it up to date regularly.
Note: This PR is not intended to implement the full solution, but rather to host the initial list of known donors.
1. …
=> feat(sponsors): Create donors.json

content/_data/changelogs/weekly.yml
Clarify that the breaking change failed the 2.465 build and the solution for 2.466 was to downgrade to the release without the breaking change.
Add references to the 2.466 changelog entry so that others can easily see the related issue and its pull requests.
=> Add refs to 2.466 changelog

content/_data/changelogs/weekly.yml
Release was today, 9 Jul 2024, not yesterday 8 Jul 2024
=> Fix 2.467 changelog date

content/doc/book/pipeline/scaling-pipeline.adoc
I have made a change [here](https://github.com/jenkinsci/workflow-api-plugin/pull/343) to adapt the wording of the durability setting to make it clearer to users. This PR is to keep the documentation aligned with that.
Keeping this pull request in draft until https://github.com/jenkinsci/workflow-api-plugin/pull/343 has been reviewed and merged :slightly_smiling_face:
=> Update durability wording

content/doc/tutorials/build-a-java-app-with-maven.adoc, content/doc/tutorials/build-a-multibranch-pipeline-project.adoc, content/doc/tutorials/build-a-node-js-and-react-app-with-npm.adoc, content/doc/tutorials/build-a-python-app-with-pyinstaller.adoc
This PR is a follow-up to the fix provided by Jay in #7335.
Another user [encountered issues](https://github.com/jenkins-docs/quickstart-tutorials/issues/454) last week, highlighting the need for a comprehensive solution to prevent problems when users chain tutorials together.
- Enhanced cleanup instructions to ensure a clean environment between tutorials
- Added an explanation for the `--remove-orphans` option
- Provided clear guidance to prevent issues with lingering containers or volumes
These improvements should effectively prevent deployment problems in subsequent tutorials caused by remnants from previous setups.
=> fix(tutorials): Improve cleanup instructions and add explanation for --remove-orphans option

content/_data/upgrades/2-440-2.adoc
[JENKINS-72665](https://issues.jenkins.io/browse/JENKINS-72665) has more details for readers that need to better understand the root of the issue and the reason that they must restart the Java process when the Java runtime is upgraded.
Segmentation violation or segfault is reported by Java when Java tries to spawn a new process after an upgrade from a Java 11 version before 11.0.22 to a Java 11 version 11.0.22 or later.  Same failure when they upgrade Java from a Java 17 version before 17.0.10 to a Java version 17.0.10 or later.
The segfault is only reported when the previous version of the JDK is trying to use the spawnhelper of the new version.  If the user stops the Java process and restarts it, the problem will not occur.
Reported by Daniel Beck in:
* …
=> Link to the OpenJDK upgrade issue in Jira

content/_data/indexpage/carousel.yml, content/blog/2024/08/01/2024-08-01-board-officer-election-announcement.adoc, content/images/governance/elections/2024/2024-announcement-opengraph.svg
Nominating for positions on the governing board and for officers.
https://www.jenkins.io/project/election-walkthrough/ provides the detailed calendar and steps I used to modify last year's election announcement:
* https://github.com/jenkins-infra/jenkins.io/pull/6663
=> Announce 2024 elections

Jenkinsfile
Reverts jenkins-infra/jenkins.io#7421 as per https://github.com/jenkins-infra/helpdesk/issues/4192#issuecomment-2270821972 since we now have a DockerHub mirror inside the infrastructure
=> Revert "chore(Jenkinsfile) increase DockerHub rate limit with authentication"

content/doc/book/platform-information/upgrade-java-to-17.adoc
The Java 11 page includes a section that alerts the reader that they must install plugins that are compatible with Java 11.  We don't need the same warning with Java 17 (at least not yet).
=> Remove broken link to upgrading plugins

content/security/advisory/2024-08-07.adoc
Also added two notes about versions of remoting on agents, one of them has popped up a few times already.
=> Mention workaround for SECURITY-3430

content/doc/developer/internationalization/i18n-source-code.adoc
Make use of UTF-8 in example. We shouldn't encourage the escaped variant any longer.
=> Make use of UTF-8 in localization example

content/stylesheets/components/_back-link.scss
Small one to fix the back link icon in dark mode, previously the chevron was white now it follows the background colour + some minor size changes to round to pixels.
**Before**
**After**
=> Update back link icon in dark mode

content/_layouts/changelog.html.haml, content/_layouts/gsocprojectidea.html.haml, content/_partials/changelog-old.html, content/_partials/changelog-stable.html, content/_partials/release-header.html.haml, content/changelog-old/index.html.haml, content/changelog-stable/index.html.haml, content/stylesheets/components/_all.scss, content/stylesheets/components/_banner.scss
Small one to fix some elements in dark mode, namely the banner and the RSS icon.
[![View comparison](https://raw.githubusercontent.com/janfaracik/janfaracik.github.io/add9a80914c0342ea13e4f8c409c953cd9c6f105/comparison/compare.svg)](https://janfaracik.github.io/comparison?before=https://github.com/user-attachments/assets/67c88d78-65a6-44dd-b2d9-e4f8cecc07e7&after=https://github.com/user-attachments/assets/5c514ba5-bc14-40e7-ae2c-080f05c839f1&github=https://github.com/jenkins-infra/jenkins.io/pull/7457)
=> Fix some elements in dark mode

content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-nginx.adoc
Tricky issue to resolve, mentioned here: 
https://community.jenkins.io/t/reverse-proxy-test-does-not-handle-url-correctly/1294/16
=> reverse-proxy-configuration proxy_pass warning

content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-nginx.adoc
This was something that I caught just before the previous PR was merged, and wasn't quick enough to fix it prior. Just a small adjustment to fix the link formatting/rendering.
=> Reverse proxy configuration - adjust link macro usage

content/doc/book/managing/casc.adoc, content/doc/book/managing/index.adoc, content/doc/book/managing/script-console.adoc, content/doc/book/managing/system-info.adoc
As part of the work to resolve https://github.com/jenkins-infra/jenkins.io/issues/7291, the areas where "Jenkins instance" was used has been updated to use a more accurate terminology (controller).
These are mostly small updates as the content/context does not change when updating from "instance" to "controller".
=> Updating Managing documentation to remove usage of "Jenkins instance"

content/doc/book/installing/_kubernetes.adoc, content/doc/book/installing/_setup-wizard-for-tutorials.adoc, content/doc/book/installing/_setup-wizard.adoc, content/doc/book/installing/other.adoc
As part of the work to resolve https://github.com/jenkins-infra/jenkins.io/issues/7291, the areas where "Jenkins instance" was used has been updated to use a more accurate terminology (controller).
These are mostly small updates as the content/context does not change when updating from "instance" to "controller".
=> Updating Installing documentation to remove use of "Jenkins instance"

content/doc/book/platform-information/upgrade-java-to-11.adoc, content/doc/book/platform-information/upgrade-java-to-17.adoc
As part of the work to resolve https://github.com/jenkins-infra/jenkins.io/issues/7291, the areas where "Jenkins instance" was used has been updated to use a more accurate terminology (controller).
These are mostly small updates as the content/context does not change when updating from "instance" to "controller".
=> Updating Platform Information documentation to remove use of "Jenkins instance"

content/doc/book/blueocean/dashboard.adoc, content/doc/book/blueocean/getting-started.adoc, content/doc/book/blueocean/index.adoc
=> Update to remove usage of "jenkins instance" in Blue Ocean documentation

content/doc/book/pipeline/development.adoc, content/doc/book/pipeline/getting-started.adoc, content/doc/book/pipeline/scaling-pipeline.adoc
=> Update to remove usage of "jenkins instance" in Pipeline documentation 

content/doc/book/scaling/architecting-for-manageability.adoc, content/doc/book/scaling/architecting-for-scale.adoc, content/doc/book/scaling/hardware-recommendations.adoc, content/doc/book/scaling/scaling-jenkins-on-kubernetes.adoc
=> Update to remove usage of "jenkins instance" in Scaling documentation 

content/doc/book/system-administration/admin-password-reset-instructions.adoc, content/doc/book/system-administration/backing-up.adoc, content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-iptables.adoc, content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-pomerium.adoc
=> Update to remove usage of "jenkins instance" in System Adminstration documentation

content/doc/book/using/best-practices.adoc, content/doc/book/using/change-time-zone.adoc, content/doc/book/using/pluggable-storage.adoc, content/doc/book/using/referencing-another-project-by-name.adoc, content/doc/book/using/remote-access-api.adoc, content/doc/book/using/using-credentials.adoc
=> Update to remove usage of "jenkins instance" in Using Jenkins documentation

content/doc/tutorials/build-a-java-app-with-maven.adoc, content/doc/tutorials/build-a-multibranch-pipeline-project.adoc, content/doc/tutorials/build-a-node-js-and-react-app-with-npm.adoc, content/doc/tutorials/build-a-python-app-with-pyinstaller.adoc, content/doc/tutorials/using-jenkinsfile-runner-github-action-to-build-jenkins-pipeline.adoc
=> Update to remove usage of "jenkins instance" in Tutorials

content/download/lts/index.adoc
=> Update to remove usage of "jenkins instance" on LTS download page 

content/doc/developer/plugin-development/build-process.adoc, content/doc/developer/publishing/continuous-integration.adoc, content/doc/developer/publishing/plugin-site.adoc, content/doc/developer/publishing/requesting-hosting.adoc, content/doc/developer/publishing/usage-statistics.adoc, content/doc/developer/security/misc.adoc, content/doc/developer/security/secrets.adoc, content/doc/developer/security/xss-prevention.adoc, content/doc/developer/telemetry/index.adoc, content/doc/developer/testing/index.adoc, content/doc/developer/tutorial/extend.adoc, content/doc/developer/tutorial/run.adoc, content/doc/developer/views/table-to-div-migration.adoc
=> Update to remove usage of "jenkins instance" in Developer documentation

content/_data/changelogs/lts.yml
Amends #6802.
PTAL @kmartens27 since there seems to be a misunderstanding about the purpose of this section.
As a rule of thumb, if it's already listed on https://www.jenkins.io/changelog-stable/ , don't add it to `lts_changes` of a new `.1`.
=> Remove changes from 2.426.1 changelog that weren't new to LTS.

content/blog/2024/08/26/2024-08-26-gsoc-manage-github-permissions.adoc
This PR is to adjust a handful of items in the GSoC Manage Jenkinsci Github Permissions as code blog. There were a couple of things that needed formatting, and pronoun correction for Kris Stern.
=> Adjust content in GSoC GitHub permissions blog

content/css/jenkins.css, content/stylesheets/components/_chips.scss
Small one to fix user avatar sizes. The icons are supposed to be 1x1, however for users with non square pictures they ended up being distorted.
**Before**
**After**
**Before**
**After**
=> Fix size of user avatars

content/stylesheets/components/_pagination.scss
Small one to fix the current, active pagination button missing its background.
**Before**
**After**
=> Fix missing background on pagination button

content/blog/index.html.haml, content/stylesheets/pages/_blog.scss
The `.app-blog-page` class predates the introduction of `.app-container`, it largely does the same thing (albeit with more vertical padding). This PR adds `.app-container` to the blog page and removes the duplicated styling.
=> Remove old blog container style

content/blog/2024/08/25/2024-08-25-gsoc-enhancing-llm.adoc
This PR is to adjust some of the links in one of the 2024 GSoC recap blog posts. There were a few hardlinks to jenkins.io, so they have been updated to use the `link:/doc/book` formatting. There were also links to the author pages of mentors/org-admins, so these have been updated to use the `author:[]` macro.
=> Remove hardlinks to jenkins.io in blog post

content/_partials/changelog-changes.html.haml
The change proposed applies the default pattern for community reported issues:
to the issue or feature description in the changelog:
applying the standard pattern we're using for JIRA issues.
=> Use standard 'JENKINS-' key for issues

content/doc/book/platform-information/support-policy-servlet-containers.adoc
This PR is to update the servlet container policy page in the Platform Information section of documentation.
With the weekly release of 2.475, the Jakarta EE 9 support is now available, so this information needs to be provided accurately. However, this would also remove the "unsupported" versions from the chart, so that would still need to be filled in with what would not be supported.
Fixes #7501
=> Update servlet container policy

content/blog/2024/09/04/2024-09-04-update-center-brownouts.adoc
First post to announce two 1-hour Update Center brownouts (see https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-2330934069).
Note: I hope to have this published as soon as possible.
=> feat(blog) add post for the two 1-hour update center brownouts

content/_data/changelogs/weekly.yml
Update to add the pull request & issue to the references section of the Jakarta EE 9/ Spring Security entry. As @daniel-beck pointed out, since there was a listed reference section for this entry, these two items are not rendering correctly since they are not part of the references section. Now that they have been added accordingly, they should be available from the changelog entry.
=> Weekly 2.475 - adding PR and Issue to references

content/doc/developer/testing/index.adoc
Added a description how to speed up testing with parallel execution and setting this up globally within the maven profile.
Thanks to @MarkEWaite for inspiring me with his PR https://github.com/jenkinsci/job-config-history-plugin/pull/312
=> Added a description how to speed up testing with parallel execution

content/_data/changelogs/weekly.yml
Earlier attempt did not include all the needed changes.  Mistake was in:
* https://github.com/jenkins-infra/jenkins.io/pull/7519
=> Fix changelog formatting (add trailing space)

content/doc/book/pipeline/shared-libraries.adoc, content/doc/book/pipeline/syntax.adoc
This PR is to update the usage of "instance" in the pipeline documentation. There are only a few places where the change was made, and one where I changed the wording to try and better fit the context of what was written.
=> Update Pipeline docs usage of "instance"

content/doc/book/scaling/architecting-for-manageability.adoc, content/doc/book/scaling/architecting-for-scale.adoc, content/doc/book/scaling/hardware-recommendations.adoc, content/doc/book/scaling/index.adoc, content/doc/book/scaling/scaling-jenkins-on-kubernetes.adoc
This PR is to update the usage of instance when referring to Jenkins controllers/agents/deployments. Not every usage of instance has been updated as some are strings/calls that need to remain as is. Grammatical changes have been made as needed as well to ensure that the updates make sense.
=> Update usage of instance in scaling documentation

content/doc/book/managing/_built-in-node-migration.adoc, content/doc/book/managing/plugins.adoc, content/doc/book/managing/script-approval.adoc, content/doc/book/managing/system-properties.adoc
This PR is to update some uses of the word "instance" to be more clear and better defined within the context of Jenkins usage. Other grammatical adjustments are being made as needed as well.
=> Update usage of "instance" in Managing documentation

content/doc/pipeline/tour/getting-started.adoc
This PR is to update the Pipeline Guided Tour tutorial as it currently states that Prerequisites includes "Java 11, 17, or 21" and this will actually cause issues for anyone that decides to follow the guided tour with the weekly release line. Since the existing LTS line also supports Java 17, there is no reason to recommend Java 11 to users following this tutorial.
=> Update Pipeline Guided Tour prerequisites

content/solutions/github.adoc
This PR is to update the usage of the word "instance" as it is found in the page. The wording has been updated to use controller (primarily), controller and agents (where needed), and deployment (intro of page). This is part of the work being done to address https://github.com/jenkins-infra/jenkins.io/issues/7291
=> Update GitHub solution page usage of "instance"

content/doc/developer/plugin-governance/adopt-a-plugin.adoc
https://github.com/jenkins-infra/update-center2/pull/804#issuecomment-2380582157 notes that two ways are offered but only one of the two ways is needed.  Since one of the two ways is preferred due to its scalability, let's state that in the documentation.
=> Clarify that one of two ways mark a plugin for adoption

content/_data/changelogs/weekly.yml
CAS plugin was recently released with Spring Security 6.x support, so mention this in the changelog.
=> Add CAS plugin release to documentation

content/blog/2024/10/03/2024-10-03-jenkins-election-candidates.adoc
Broken because I didn't update it to use the author link.
Confirmed with local site build that the broken link is fixed by this change.
=> Fix broken internal link to Oleg statement

content/_data/changelogs/lts.yml, content/doc/book/platform-information/support-policy-java.adoc
One more place to alert users that Java 11 support is ending.
Also updates the Java support policy page to list 2.479.1 as the first LTS release to require Java 17 or newer.
=> Add banner to 2.462.3 LTS changelog for end of Java 11 support

content/_data/changelogs/weekly.yml
This PR is to adjust the 2.480 changelog so that the entry regarding CSP improvements describes this idea. It also updates the issue that it should be connected to so that it is now correct.
=> Adjust 2.480 changelog entry for correct message & issue

content/doc/developer/tutorial-improve/automate-dependency-update-checks.adoc
The Jenkins plugin archetype is a good example of the preferred configuration of Jenkins plugins.  Let's use its syntax when we have a choice.  If we need additional explanatory comments, let's place them outside the code block rather than embedding them in the code block.
=> Use dependabot syntax from archetype in "Improve a plugin"

.typos.toml, content/doc/tutorials/tutorials-for-installing-jenkins-on-Google-Cloud.adoc, content/download/index.html.haml
Preview page is available [here](https://deploy-preview-7610--jenkins-io-site-pr.netlify.app/doc/tutorials/tutorials-for-installing-jenkins-on-google-cloud/)
The current link to GCP from the downloads page is for an unrelated page.  The original page was a 2018 blog post.  Much newer information is available from other sources.  Rather than link to an unrelated page, let's link to a page that we maintain and that we can update with more content.
The linked blog post from medium.com that is now included in the Jenkins tutorial page is the most thorough Jenkins installation tutorial (that I could fine) for Google Cloud Platform.  It describes the Jenkins controller installation and the configuration of Kubernetes agents for that Jenkins controller using Google Kubernetes Engine.
The video …
=> Replace incorrect GCP link on downloads page, update GCP tutorial

content/_data/changelogs/weekly.yml
Manually generated 2.481 changelog did not use same exact formatting as the automated formatter.  Match the automated formatter.
=> Format 2.481 changelog to match automated formatting

content/_data/changelogs/weekly.yml
This PR is to clarify the message for user created offline reasoning when agents are either connected or disconnected.
=> Weekly 2.481 - adjust ofline agent entry message

content/doc/book/platform-information/upgrade-java-to-17.adoc, content/doc/book/system-administration/index.adoc, content/doc/developer/handling-requests/actions.adoc, content/doc/developer/publishing/usage-statistics.adoc
This PR is for another handful of documentation updates to adjust the usage of instance where controller or deployment would be better suited.
=> Additional updates for instance usage

content/security/for-maintainers.adoc, content/security/reporting.adoc, content/security/team.adoc
This PR is to adjust some uses of the word "instance" to be more clear and utilize "controller" or "controller and agents" where necessary. This is part of the work inspired by https://github.com/jenkins-infra/jenkins.io/issues/7291 to provide more clear and descriptive documentation.
=> Slight wording adjustments for Security pages

content/_data/changelogs/lts.yml
This PR is to add the additional backports to the changelog in the "changes since 2.479" section and update the Spring Security & Framework versions to the latest versions.
=> LTS 2.479.1 - Additional backports and Spring versions

content/blog/2024/10/24/2024-10-24-update-center-brownouts-5.adoc
Related to https://github.com/jenkins-infra/helpdesk/issues/2649, https://github.com/jenkins-infra/helpdesk/issues/4312 and https://github.com/jenkins-infra/helpdesk/issues/4311
This PRs publishes a new blog post to announce the 5th brownout.
I'm short in delays (sorry, I got team member unavailable so late due to overwhelmed): I would want to publish this as soon as posible. As such, do not hesitate to commit or fix the post if you see any mistake or typo (you can push on my PR here: I'll let it in auto merge) but I'll need a quick review + approval at least.
=> feat(blog) add a new post about the Update Center (5th brownout)

content/blog/2024/10/24/2024-10-24-update-center-brownouts-5.adoc
Text shown to user is:
> Starting 12 weeks ago, the Jenkins infrastructure has been using the new Update Center (link:https://azure.updates.jenkins.io)
Replace the link: with a hyperlink
=> Fix link in brownout blog post

updatecli/scripts/jenkins-oldest-supported-version.sh, updatecli/scripts/jenkins-split.sh
The `updatecli` check in #7630 was failing because the `curl` command in the `bash` script wasn't properly following `307` HTTP redirects (which weren't occurring when the script was originally developed).
Question: Is this failure related to the current brownout?
```
updatecli diff --debug --config ./updatecli/updatecli.d/ --values ./updatecli/values.github-action.yaml 2>&1
[...]
Run Summary
===========
Pipeline(s) run:
* Changed:    0
* Failed:     0
* Skipped:    0
* Succeeded:  11
* Total:      11
```
=> fix(updatecli): Handle 307 HTTP redirect

content/changelog-stable/index.html.haml
Amends #7479.
Too little indentation here means the LTS changelog starts with the "Notable changes" for an unreleased version at the moment.
> <img width="1557" alt="Screenshot 2024-10-29 at 16 02 06" src="https://github.com/user-attachments/assets/b4b2817c-9179-469a-bd47-ef86204d979c">
=> Do not show "Notable changes" section for unreleased LTS versions

content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-apache.adoc
Fix https://github.com/jenkins-infra/jenkins.io/issues/7568. 
I have tested the configuration with and without path prefix and validated that it works. I also helped a user to make websocket agent connection happens through 2 Apache server with SSL Bridging based on those rules. That I have talken from https://httpd.apache.org/docs/2.4/mod/mod_proxy_wstunnel.html.
Now I am not an Apache Server expert so a review from peers with. more knowledge would be appreciated.
=> Add websocket configuration for apache reverse proxy

content/doc/book/platform-information/support-policy-servlet-containers.adoc
This PR is to add the latest LTS release to the servlet container policy page.
=> Add LTS 2.479.1 to servlet container support policy

content/doc/developer/testing/index.adoc
Added short section about jcasc which was missing completely. Mainly sending the users to the plugin documentation.
=> Added short section about jcasc in the testing dev docu

content/doc/book/installing/windows.adoc
- Added a brief note in "Step 3: Service logon credentials::" to indicate that the Jenkins service account requires `LogonAsService` permission.
- Slightly adjusted wording in the troubleshooting section.
Reference: [JENKINS-63477](https://issues.jenkins.io/browse/JENKINS-63477).
=> Modified windows.adoc: Added brief LogonAsService Note

content/blog/2024/11/07/2024-11-07-update-center-brownouts-6.adoc
Related to https://github.com/jenkins-infra/helpdesk/issues/2649, https://github.com/jenkins-infra/helpdesk/issues/4312 and https://github.com/jenkins-infra/helpdesk/issues/4311
This PRs publishes a new blog post to announce the 6th brownout.
=> feat(blog) add a new post about the Update Center (6th brownout)

content/_data/changelogs/weekly.yml
This bug was missed by the automated changelog generator, and when I went to go review it there was no indication that it was part of 2.484 (the merged commit did not have the 2.484 tag attached).
This PR is to add the entry to the changelog accordingly.
=> Add bug entry to 2.484 changelog

content/project/election-walkthrough.adoc
The behavior of the CIVS platform changed in the past years; we must enable our account, it is not automatic anymore.
This PR adapt the wording to avoid confusion.
=> fix(election-walkthrough) account activation is now (2024) mandatory

Jenkinsfile
Inspired by https://github.com/jenkins-infra/javadoc/blob/238c39e60a4e2adfb179539ad03f67d24eb39008/Jenkinsfile#L52-L87
=> chore(Jenkinsfile) collect `azcopy` publication logs when failing deployment on trusted.ci.jenkins.io

content/projects/gsoc/2024/index.adoc, content/projects/gsoc/2025/index.adoc, content/projects/gsoc/2025/project-ideas.html.haml, content/projects/gsoc/2025/project-ideas/android-or-ios-tutorial-pages.adoc, content/projects/gsoc/2025/project-ideas/backend-code-refactoring-for-infra-stats.adoc, content/projects/gsoc/2025/project-ideas/complete-alternative-jenkins-io-build-retooling.adoc, content/projects/gsoc/2025/project-ideas/domain-specific-LLM-based-on-jenkins-usage-using-ci.jenkins.io-data.adoc, content/projects/gsoc/2025/project-ideas/further-pipeline-documentation-improvements.adoc, content/projects/gsoc/2025/project-ideas/improving-jenkinsfile-runner-abilities-and-github-actions.adoc, content/projects/gsoc/2025/project-ideas/revamping-jenkins-io-website-success-stories-feature.adoc, content/projects/gsoc/2025/project-ideas/swagger-openapi-for-jenkins-rest-api.adoc, content/projects/gsoc/index.adoc
Added a total of 8 new GSoC project ideas for 2025:
1. Android and/or iOS tutorials in official documentation
2. Backend code refactoring for Infra Statistics
3. Complete build retooling of jenkins.io
4. Domain-specific LLM based on actual Jenkins usage using ci.jenkins.io data
5. Pipeline documentation improvements - Phase 2 and Phase 3
6. Improving Jenkinsfile Runner abilities and GitHub Actions
7. Revamping jenkins.io website Success Stories feature
8. Swagger / OpenAPI standardization for Jenkins REST API
These are as discussed internally among @MarkEWaite the org admins @alyssat @gounthar and @krisstern as well as potential lead mentor @jonesbusy.
=> feat(gsoc): add 2025 proposed project ideas

content/projects/gsoc/2025/project-ideas/domain-specific-LLM-based-on-jenkins-usage-using-ci.jenkins.io-data.adoc
This PR updates the year for the 'Domain-specific LLM based on actual Jenkins usage using ci.jenkins.io data' project idea from 2024 to 2025.
=> Fix GSoC 2025 project idea year

content/doc/developer/security/csp.adoc
@yaroslavafenkin mentioned that this was not specifically documented.
As a common case of code people may not be very familiar with, IMO it makes sense to have this here.
=> Mention `st:bind` in inline JS guidelines

content/_data/changelogs/lts.yml, content/_data/changelogs/weekly.yml, content/_data/upgrades/2-479-1.adoc
[JENKINS-74841](https://issues.jenkins.io/browse/JENKINS-74841) includes a comment that notes the mailer plugin is also required when upgrading to 2.479.1.
=> Add mailer plugin to reverse proxy auth upgrade instructions

content/blog/2024/11/16/2024-11-16-new-update-center.adoc
Related to https://github.com/jenkins-infra/helpdesk/issues/2649
This PR adds a new blog post about the new UC in production for this Monday 18 Nov. 2024 at 09:00am UTC.
You can commit to fix any mistakes or language issues as you want.
You may proceed to publish it as soon as possible, when reviewed of course.
=> feat(blog) add a post for the new UC in production

content/doc/book/pipeline/docker.adoc, content/doc/pipeline/tour/agents.adoc
A recent documentation feedback noted that the incorrect version number string is included in the sample output.  Rather than adjust the example output, let's use example output that is unlikely to change between NodeJS releases.  This example uses `process.platform` and `process.env.CI`.  Those are not likely to change from one version of nodeJS to the next.
The [feedback sheet](https://docs.google.com/spreadsheets/d/1nA8xVOkyKmZ8oTYSLdwjborT0w-BpBNNZT0nxR9deZ8/edit?usp=sharing) includes the note that the NodeJS version number is incorrect in the example output.
=> Do not depend on nodeJS version in example output

content/doc/book/pipeline/jenkinsfile.adoc
Addresses https://github.com/jenkins-infra/jenkins.io/issues/7652
Currently, the "Using a Jenkinsfile" documentation is rendering an odd styling for some parts of the page:
It appears that there are some role attributes in the page causing this inline formatting to take place.
I have removed the role attributes from all but one place, where it was moved to directly affect the scripted pipeline code example (line 123).
After removing the attributes, the page now renders uniformly without the offset:
Role attributes are not used consistently throughout the documentation, so this may be a remnant of previous docsite builds or formatting. This formatting is especially visible when using dark mode:
=> Removing role attributes from Jenkinsfile documentation

content/project/board.html.haml
This PR is to update the governance board page to include the new governance board members and update the terms to reflect the correct time frame that everyone will be serving.
=> Update governance board page

content/doc/tutorials/index.adoc
This PR is to move the Blue Ocean tutorial section toward the bottom of the page and add a note indicating the status of Blue Ocean and its eventual deprecation
=> Move Blue Ocean tutorial section towards bottom of page

content/doc/developer/plugin-development/dependency-management.adoc
To address the [comment made in this issue](https://github.com/jenkins-infra/helpdesk/issues/4426#issuecomment-2514730359) I have added an extra line to the Dependency Management documentation to indicate that version range is not something we should encourage.
=> Warn against version range usage

content/doc/pipeline/tour/post.adoc, content/pipeline/getting-started-pipelines.adoc
https://en.wikipedia.org/wiki/HipChat notes that HipChat is no longer available.  No reason to leave it in our documentation.
=> Remove HipChat from Pipeline examples

content/doc/book/managing/groovy-hook-scripts.adoc
Fixes #7051
Issue description:Mention that if using docker the user should use /usr/share/jenkins/ref/init.groovy.d and not $JENKINS_HOME/init.groovy.d/
Changes made:
1.Added a note in the "Post initialization script (init hook)" section.
2.The note clarifies that when using the Jenkins Docker image, the $JENKINS_HOME/init.groovy.d/ directory does not exist. Instead, users should place their Groovy script files in /usr/share/jenkins/ref/init.groovy.d/ since this directory is copied when the Docker container starts.
This change aims to improve the clarity of the documentation and help users running Jenkins in Docker environments correctly place their initialization scripts.
i hope this solves the issue  @tzachs @kmartens27
=> Update documentation for Docker Groovy script path

content/_data/changelogs/weekly.yml
Link is https://plugins.jenkins.io/commons-compress-api/
=> Link to `commons-compress-api` API plugin is incorrect

content/doc/book/pipeline/docker.adoc
Some docker step options are described on this page, others are defined here: https://www.jenkins.io/doc/book/pipeline/syntax/#agent-parameters. So it makes sense to link them, to help users find what they're looking for.
Edit: preview link: https://deploy-preview-7725--jenkins-io-site-pr.netlify.app/doc/book/pipeline/docker/
=> Add link to pipeline syntax parameters

content/doc/developer/testing/index.adoc
Added short section about `ClassRule` for `JenkinsRule`
=> Added short section about ClassRule for JenkinsRule

content/doc/developer/testing/index.adoc
Documented the `RestartableJenkinsRule` also created a very small example to showcase how it can be used.
=> Documented the `RestartableJenkinsRule`

content/_data/authors/harsh-ps-2003.adoc, content/projects/gsoc/2025/project-ideas/domain-specific-LLM-based-on-jenkins-usage-using-ci.jenkins.io-data.adoc
Hey,
 I would also like to be the mentor for GSoC 2025 for the project [Domain-specific LLM based on actual Jenkins usage using ci.jenkins.io data](https://www.jenkins.io/projects/gsoc/2025/project-ideas/domain-specific-LLM-based-on-jenkins-usage-using-ci.jenkins.io-data/)
 
I believe that my past mentoring experience in GSoC 2024 and contributing experience in GSoC 2023, along with Jenkins plugin development and Infrastructure knowledge, can be a valuable addition to the project!
Thanking you in Anticipation 
Warm Regards
=> adding harsh-ps-2003 as a potential mentor for GSoC 2025

content/_data/changelogs/weekly.yml
This PR is to add an entry to the 2.491 changelog for https://github.com/jenkinsci/jenkins/pull/10058
The pr originally had the `skip-changelog` label assigned and no changelog entry suggested so it was not included by the automated changelog generator.
=> Add atomicfilewriter entry to 2.491 changelog

content/solutions/python.adoc
Cobertura is deprecated and no longer in support
Same with nosetests and its successor nose2
Instead - steer peoples towards using pytest
=> Update python.adoc due to nosetest and Cobertura EOL statuses

content/projects/gsoc/2025/project-ideas/complete-alternative-jenkins-io-build-retooling.adoc, content/projects/gsoc/2025/project-ideas/swagger-openapi-for-jenkins-rest-api.adoc
Hi, I am interested in mentoring the project [Swagger / OpenAPI standardization for Jenkins REST API](https://www.jenkins.io/projects/gsoc/2025/project-ideas/swagger-openapi-for-jenkins-rest-api/), and [Complete build retooling of jenkins.io ](https://www.jenkins.io/projects/gsoc/2025/project-ideas/complete-alternative-jenkins-io-build-retooling/). As an open-source enthusiast, I have completed the following programs: [GSoC 2022](https://github.com/iamrajiv/GSoC-2022) with Keptn, [LFX Mentorship Fall 2021](https://github.com/iamrajiv/LFX-2021) with moja global, [GSoD 2021](https://github.com/iamrajiv/GSoD-2021) with Wechaty, and [GSoD 2020](https://github.com/iamrajiv/GSoD-2020) with gRPC-Gateway. I have also mentored in the past with Jenkins during GSoC 2023 and GSoC 2024.
Regarding the …
=> Add contributor as a potential mentor for GSoC 2025

content/projects/gsoc/2025/project-ideas/domain-specific-LLM-based-on-jenkins-usage-using-ci.jenkins.io-data.adoc
Hey,
 I would like to mentor for GSoC 2025 for the potential project [Domain-specific LLM based on actual Jenkins usage using ci.jenkins.io data](https://www.jenkins.io/projects/gsoc/2025/project-ideas/domain-specific-LLM-based-on-jenkins-usage-using-ci.jenkins.io-data/)
 
I believe that my past mentoring experience in GSoC 2024 in the LLM project and Jenkins ML Plugin GSoC 2020 project, along with extensive experience with LLMs for log analysis and OpenLLMetry, can be a valuable addition to the project!
With regards
Shivay
=> Add shivaylamba as a potential mentor for GSoC 2025

content/projects/gsoc/2025/project-ideas/domain-specific-LLM-based-on-jenkins-usage-using-ci.jenkins.io-data.adoc
Fixes #7780 
Removed the redundant file extensions `.adoc` from the broken links in the GSoC 2025 LLM project idea page at https://www.jenkins.io/projects/gsoc/2025/project-ideas/domain-specific-LLM-based-on-jenkins-usage-using-ci.jenkins.io-data/.
=> fix(gsoc): patch broken link found in gsoc 2025 llm project idea

content/doc/developer/testing/index.adoc
Added documentation about `FilePath` and 
removed **work in progress** (wip) status since I think we are on a quite solid basis.
I still have a few things in mind to improve, but it is time to remove this scary warning sign, if all agree.
=> Added documentation about `FilePath` and removed wip status

content/doc/developer/forms/adding-tool-tips.adoc, content/doc/developer/views/symbols.adoc
The URL to each of the pages has changed.  Update it in the documentation so that the link works.
- **Fix link to design library symbols page**
- **Fix tooltip hyperlink**
=> Fix 2 weekly.ci.jenkins.io hyperlinks

content/doc/developer/tutorial-improve/_install-apache-maven.adoc
Plugin POM 5.0 requires Maven 3.9.6 or later:
<https://github.com/jenkinsci/plugin-pom/pull/1018>
=> Recommend Maven 3.9.6 or newer

content/doc/developer/tutorial-improve/update-parent-pom.adoc
Small change but was missing on the improve a plugin tutorial
This is even recommended since parent 2.x : https://www.jenkins.io/doc/developer/plugin-development/updating-parent/
SInce I'm starting to run https://github.com/jenkins-infra/plugin-modernizer-tool to fix this on most plugin I would like to link to this page
=> Make it clear that relativePath must be present on the parent pom

Gemfile, Gemfile.lock, scripts/ruby
as per https://github.com/jenkins-infra/helpdesk/issues/4476
`base64` is now required as a dependency in the Gemfile
and I bumped the ruby version to match the infra packer-image version https://github.com/jenkins-infra/packer-images/blob/53dfc01e68aa3c9f9e566131dd4b85a17d638c62/provisioning/tools-versions.yml#L42
=> chore(gemfile): add base64 dependency and bump ruby docker image to 3.4.1

updatecli/updatecli.d/ruby-documentation.yaml, updatecli/updatecli.d/ruby.yaml
following https://github.com/jenkins-infra/helpdesk/issues/4476
we need to track the ruby version to keep current both the CI/CD and the PREVIEW.
this manifest make sure the ./scripts/ruby image version match the packer-image one used in production
=> chore(updatecli/ruby): add a manifest to link the docker image for ruby aligned with packer-image version

content/security/index.adoc, content/security/reporting.adoc
Perhaps this makes it easier for reporters to find where to report issues in Jira if they are unfamiliar with it?
Unlike the link for plugins on e.g. https://www.jenkins.io/participate/report-issue/redirect/#18146 nothing is already filled out, since we don't know what the component will be.
We could also add some quick instructions to the description. Any suggestions?
=> Directly link to Create Issue form instead of just SECURITY project

content/participate/report-issue/redirect.html.haml
Consume https://github.com/jenkins-infra/repository-permissions-updater/pull/4256
=> Add support for plugin ID in security issue template

content/participate/report-issue/redirect.html.haml
Amends https://github.com/jenkins-infra/jenkins.io/pull/7810, restoring backward compatibility with old URLs.
Sorry for the noise 😞
=> Fix JS more

content/_data/authors/dduportal.adoc
I left Twitter and we don't have Bluesky tracking, so let's remove the link in my bio
Same as https://github.com/jenkins-infra/jenkins.io/pull/7835 :)
=> fix(authors) remove dduportal's Twitter

content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-pomerium.adoc
This is just a small update to adjust the Jenkins images being used in this configuration to be the Java 17 supported image.
=> Update reverse proxy instructions for Java 17

content/_data/upgrades/2-492-1.adoc
Configuration as code intentionally cancels Jenkins startup when a deprecated configuration element is detected.  This forces administrators to resolve the deprecations immediateely rather than delyaing the resolution of the deprecation.
Describe the configuration as code setting that will change the default behavior to warn on deprecation rather than canceling startup.  Explain the risks of that choice.
The [pull request comment](https://github.com/jenkinsci/jenkins/pull/9903#issuecomment-2640241966) requests a more detailed description of the behavior.  This is that more detailed comment.
=> Explain the JCasC behavior on deprecated configuration elements

content/projects/gsoc/2025/project-ideas/revamping-jenkins-io-website-success-stories-feature.adoc
Previously we have omitted to update the goal for the revamping jenkins.io website success stories project idea. This PR is to correct that.
=> fix(gsoc): replace goal for revamping jenkins.io website success stories feature

content/sigs/docs/index.adoc
- This PR addresses two key issues in the Jenkins documentation:
1.Fixing Incorrect Sublink Redirections
-Previously, sublinks under /sigs/docs/ were incorrectly redirected to undefined pages or non-existing sections.
-Updated the redirection mechanism to correctly resolve sublinks such as #members, #description, and #topics, ensuring they direct to the correct sections.
2.Improving Algolia Search Functionality
-When a search query had no direct matches, Algolia suggested links that did not exist or led to incorrect redirections.
-Adjusted the search index behavior to exclude invalid links and prevent misleading recommendations.
-Ensured that valid sublinks are properly indexed and accessible through the search results.
- Users can now navigate correctly to sub-sections within /sigs/docs/ …
=> fix: patch incorrect hash link redirect

content/css/jenkins.css
This PR resolves the issue where the "No results for..." text in the Algolia search box was not visible due to the white text color blending into the white background.
- Updated the CSS for `p.DocSearch-Title` within the `DocSearch-NoResults` container to set the text color to more visible color type. 
- Ensured the fix aligns with the overall design consistency and improves user accessibility.
- Tested the website using `make` and `make run` .
Please review and let me know for improvements.
=> fix: ensure "No results for..." text is visible in Algolia search box

content/download/index.html.haml
As the title says, the URL provided is dead.
=> Update dead openbsd on dl page

content/_partials/openbsd-pkg_add-installer.html.haml, content/download/index.html.haml, content/download/lts/openbsd.html.haml, content/download/weekly/openbsd.html.haml
[PR-7885](https://github.com/jenkins-infra/jenkins.io/pull/7885) detected that the OpenBSD download links for weekly and LTS were pointing to a site that is offline.  It corrected that by pointing to the package definitions in the OpenBSD ports.
The package definitions in OpenBSD ports are not helpful for a user that wants to install on OpenBSD.  They need more instructions.
Stuart Henderson recommended that the macOS install pages are a good model to also explain OpenBSD installation.  Refer to the OpenBSD ports [mailing list thread](https://marc.info/?l=openbsd-ports&m=173979027021545&w=2) for more details.
These instructions intentionally do not include a package version number in the pkg_add command line.  The Jenkins install page should not track OpenBSD package versions.
The …
=> Create OpenBSD install instructions like macOS

content/_partials/osx-brew-installer.html.haml, content/download/lts/macos.html.haml, content/download/weekly/macos.html.haml
Homebrew is the only installer described on the page.  The page is describing the macOS Installer for Jenkins, not multiple macOS Installers for Jenkins.
Simplify the phrasing of the disclaimer.
=> Only one macOS package installer, simplify the macOS pages

content/changelog-stable-old/index.html.haml, content/download/index.html.haml
- This PR addresses the issue where the  [LTS changelog archive](https://www.jenkins.io/changelog-stable-old/)  does not fully render changelog entries for `.1` releases. Specifically, entries under `lts_changes` (changes compared to the LTS predecessor) were missing, while only entries under` lts_baseline` (changes compared to the baseline version) were displayed. This fix ensures that both changes and l`ts_changes` are properly rendered for all releases, including `.1` releases.
- Updated the content/changelog-stable-old/index.html.haml file to include logic for rendering lts_changes alongside changes.
- Ensured that the archive page now displays both changes and lts_changes for each release, similar to the main changelog page (changelog-stable).
- Verified the fix by testing the …
=> fix: fully render `.1` release Changelog entries in LTS Changelog archive page

content/sigs/docs/index.adoc
This PR is to update the description of the docs office hours schedule to reflect the current times. Currently, docs office hours are once every two weeks, but the current documentation has the previous cadence of twice a week every week. The time will remain the same, unless there is consensus to move it earlier/later.
=> Update docs office hours schedule

CONTRIBUTING.adoc
This PR is to help address one of the suggestions in https://github.com/jenkins-infra/jenkins.io/issues/7844 by adding links to both the Docker Engine and Docker Desktop installation guides.
=> Add links to Docker installation instructions

content/doc/book/managing/system-properties.adoc
Harmonize since syntax (LTS / weekly) because we used several formats in this document. I had the impression that LTS / weekly was the most used syntax, so I chose that. With that, it is also ordered.
=> Harmonize since syntax (LTS / weekly)

content/_data/roadmap/roadmap.yml, content/projects/index.adoc, content/sigs/docs/gsod/ideas.adoc, content/sigs/docs/gsod/index.adoc
While preparing to create a prototype of the [plugin maintainers project](https://docs.google.com/document/d/1GEI7tQp3UxGCbQQyF1JdujgwkoWcMluvUMFanV2nDGo/edit?usp=sharing) page, I saw that Blue Ocean and Kubernetes documentation were both above Google Summer of Code on the [Jenkins Subprojects overview](https://www.jenkins.io/projects/).  That will mislead readers, since those two projects are no longer active and Google Summer of Code is very active.  Let's highlight the most active projects at the top of the page.
While exploring, I found related areas for minor improvements, including:
- Remove Kubernetes docs from Season of Docs ideas
- Note in roadmap that Kubernetes docs Season of Docs project is complete
- Remove Google Season of Docs office hours, they no longer exist
If this is …
=> Put Google Summer of Code at top of projects list

content/doc/book/installing/linux.adoc
The Red Hat instructions include a similar video.  That video has over 18000 views.
Intentionally uses Ubuntu 24.04 instead of Debian 12 because the Jenkins infrastructure uses Ubuntu.
The video includes installation instructions for Eclipse Temurin Java 21.  Eclipse Temurin Java is the distribution included in the Jenkins container images for the controller and for the agents.
See the [preview site](https://deploy-preview-7912--jenkins-io-site-pr.netlify.app/doc/book/installing/linux/#debianubuntu) to review it.
=> Add Ubuntu 24.04 install video to Debian/Ubuntu instructions

content/projects/gsoc/2025/project-ideas/backend-code-refactoring-for-infra-stats.adoc, content/projects/gsoc/2025/project-ideas/plugin-modernizer-improvements.adoc, content/projects/gsoc/2025/project-ideas/swagger-openapi-for-jenkins-rest-api.adoc, content/projects/gsoc/index.adoc
* Added Phillipp Glanz as potential gsoc 2025 project mentor.
* Updated gsoc landing page after Jenkins has been confirmed to be a gsoc 2025 mentoring org.
=> feat(gsoc): update jenkins status post gsoc 2025 mentoring orgs selection

content/security/reporting.adoc
We're receiving reports for googlegroups.com configuration that are not listed in our documentation.
Let's make this non issue more generic to cover them.
=> Make non issue for googlegroups configuration more generic

content/projects/gsoc/index.adoc
Google has changed our URL on their Google Summer of Code site, so am updating our URL on our GSoC project homepage to reflect this change.
=> fix(gsoc): change Jenkins GSoC 2025 mentoring org URL on GSoC project page

content/projects/gsoc/contributors.adoc, content/projects/gsoc/mentors.adoc, content/projects/gsoc/proposing-project-ideas.adoc, content/projects/gsoc/roles-and-responsibilities.adoc
Updated the rest of the GSoC pages in preparation of GSoC 2025, in advance of the official contributor application period taking place from late March to early April, 2025.
=> feat(gsoc): update rest of gsoc pages in preparation of gsoc 2025

content/projects/gsoc/contributors.adoc
This PR is to adjust some of the text and punctuation on the GSoC contributors page to make sure that things are formatted correctly and grammatically accurate.
=> Update gsoc contributor docs

content/doc/book/installing/_kubernetes.adoc, content/doc/book/installing/kubernetes.adoc, content/doc/tutorials/kubernetes/installing-jenkins-on-kubernetes/jenkins-01-volume.yaml, content/doc/tutorials/kubernetes/installing-jenkins-on-kubernetes/jenkins-02-sa.yaml, content/doc/tutorials/kubernetes/installing-jenkins-on-kubernetes/jenkins-03-deployment.yaml, content/doc/tutorials/kubernetes/installing-jenkins-on-kubernetes/jenkins-04-service.yaml, content/doc/tutorials/kubernetes/installing-jenkins-on-kubernetes/jenkins-deployment.yaml
Update the documentation for Jenkins on Kubernetes setup:
* Clarify that there are actually several different setup scenarios explored here;
* Discuss use of floating-tag (LTS) vs. specific version tagged images, including impact on image pulling (and whether the admin wants it automatic or deterministic)
* Bump image version reference in Helm doc example
* Some suggestions about log watching and access to containers without reliance on ever-randomized pod names
Cross-link to https://github.com/scriptcamp/kubernetes-jenkins/pull/6 : we refer to that repo in text (even if YAML file contents are presented and maintained in text directly), and perhaps this document started from the blog illustrated by that repo. So as we shift to numbered filenames here, that PR proposes to do similarly in …
=> Fix doc for Jenkins on Kubernetes

content/download/index.html.haml, content/index.html.haml
Fixes #7965. 
1. Remove extra words that was repeated unnecessarily. 
2. Remove extra space before each comma in the repos list of each contributor to be thanked. 
3. When multiple repositories are listed, use the plural form "repos" instead of the singular form "repo"
=> fix(ui): patch bug(s) in current thank-you note implementation

content/_partials/thank-you-note.html.haml, content/download/index.html.haml, content/index.html.haml
1. Added logic to make sure when the thank-you note contributor has only one repo there would be no duplicate repo names shown. 
2. Moved the thank-you note code to its own partial.
=> fix(ui): patch potential logical bug when thank-you note contributor only has one repo

content/_partials/thank-you-note.html.haml
Remove redundant logic after trying out on actual single repo case in thank-you note.
=> fix(ui): remove extra comma in thank-you note in single repo case

content/blog/2024/08/29/2024-08-29-jenkins-design.adoc, content/blog/2024/12/02/2024-12-02-pr-titles.adoc, content/blog/2025/01/2025-01-10-design-library.adoc, content/blog/2025/02/2025-02-05-command-palette.adoc, content/sigs/ux/index.adoc
This PR is to update some recent blog posts to include the `ux` tag so that they are displayed in the list of recent blog posts.
It also updates the UX SIG page to include the recently released Jenkins Design Library 3, along with a link to the blog post announcing it.
@janfaracik if there is anything else that should be added to the UX SIG page, just let me know!
=> Update UX SIG page to include Design Library 3

updatecli/updatecli.d/jenkins-lts.yaml
- **Documentation**
- Updated the Docker tutorial to reflect the current Jenkins LTS version, ensuring clearer update instructions.
=> feat(docs): update Jenkins LTS version references in Docker documentation

content/doc/book/installing/_docker.adoc
This commit updates the Jenkins Dockerfile example to align with the latest Docker official recommendations for installing the Docker CLI. The changes aim to enhance security and maintain consistency with modern best practices
I followed come from the official Docker documentation for installing Docker Engine on Debian. You can find the details at:
https://docs.docker.com/engine/install/debian/
Below is the relevant excerpt:
```shell
sudo apt-get update
sudo apt-get install ca-certificates curl
sudo install -m 0755 -d /etc/apt/keyrings
sudo curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
sudo chmod a+r /etc/apt/keyrings/docker.asc
echo \
"deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] …
```
=> chore: Update _docker.adoc

content/_data/indexpage/carousel.yml
This PR is to update the Jumbotron to remove the GSoC involvement item and add the 2025 community awards.
=> Update jumbotron with 2025 Community awards

content/doc/book/pipeline/pipeline-as-code.adoc
Fix minor typos in the "Pipeline as Code" documentation.
- `was developed .` to `was developed.` 
- `A this point,` to `At this point,`
=> Fix typos in pipeline-as-code.adoc

content/doc/book/scaling/scaling-jenkins-on-kubernetes.adoc
- Replaced `docker` with `Docker`, and `dockerfile` with `Dockerfile` to follow Docker naming conventions.
- And minor fixes to improve readability.
=> Improve readability and correct terminology

content/changelog-stable-old/index.html.haml
Fixes #8040. Amends #7746.
It's not pretty, but functional.
=> Restore LTS changelogs before 2.32.1

content/doc/book/installing/linux.adoc, content/doc/book/platform-information/_chapter.yml, content/doc/book/platform-information/index.adoc, content/doc/book/platform-information/upgrade-java-to-11.adoc, content/doc/book/platform-information/upgrade-java-to-17.adoc, content/doc/book/platform-information/upgrade-java-to-21.adoc
This PR is to add instructions on upgrading to Java 21. It includes the video that Darin Pope has recorded, and step by step instructions on how to perform the upgrade for both the controller and agents. It also adjusts some of the section headings to adjust -ing verbs and phrases.
=> Add Java 21 upgrade instructions

content/participate/track-issue.adoc
The note mentions an ongoing epic that has been closed for some time.
=> [chore] Remove note about a closed epic

content/_data/indexpage/carousel.yml
This PR is to update the 2025 Jenkins Community Awards slide on the jumbotron to include the link to the voting form and update the text a bit. The overall slide still links to the blog post, but the link button has been updated to go directly to the form.
=> Update Community Awards jumbotron with voting form

content/doc/book/installing/_docker.adoc
This PR is to update the jdk used in the Docker installation instructions from 17 to 21.
=> Update Docker installation for jdk21

content/doc/book/pipeline/syntax.adoc
The current Pipeline Syntax page has bars spanning the page under section headers. These bars appear in both dark & light mode:
Dark mode:
Light mode:
This PR removes the unnecessary `[role=sytax]` above the Declarative Pipeline header, thus removing the bars from the page:
Dark mode:
Light mode:
=> Update Pipeline Syntax docs to remove role from text

content/doc/book/installing/linux.adoc
As in https://github.com/jenkinsci/packaging/pull/521, update the keyring location. Per [`sources.list(5)`](https://manpages.ubuntu.com/manpages/plucky/en/man5/sources.list.5.html):
> The recommended locations for keyrings are `/usr/share/keyrings` for keyrings managed by packages, and `/etc/apt/keyrings` for keyrings managed by the system operator.
The package does not manage any keyrings, so `/etc/apt/keyrings` is the more appropriate choice here.
Tested this location on my Ubuntu system; it works the same as before.
=> Update keyring location

content/doc/book/installing/_docker-for-tutorials.adoc, content/doc/book/pipeline/shared-libraries.adoc, content/doc/book/pipeline/syntax.adoc, content/doc/book/scaling/architecting-for-manageability.adoc, content/doc/book/scaling/scaling-jenkins-on-kubernetes.adoc, content/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-pomerium.adoc, content/doc/book/system-administration/systemd-services.adoc, content/doc/book/using/using-agents.adoc, content/doc/developer/tutorial/prepare.adoc, updatecli/updatecli.d/jenkins-lts.yaml
These are additional updates for Java 21 throughout various parts of the documentation.
This also matches the shared libraries info with the [jenkins infra test plugin](https://github.com/jenkinsci/jenkins-infra-test-plugin) where linux uses 21, but windows is using 17.
=> Additional updates for Java 21 in documentation

updatecli/updatecli.d/jenkins-lts.yaml
This PR is to update the java version in the jenkins-lts updatecli file so that it is pointing to Java 21 instead of Java 17. Thanks to @gounthar for confirming this update is correct.
=> Update Java version to 21 in jenkins-lts updatecli file

content/doc/book/pipeline/docker.adoc
This PR is to update the image used in the Using Docker with Pipeline documentation to use Java 21. Grabbing the latest image from the Gradle dockerhub shows that it is `8.14.0-jdk21-alpine` and adding the `maven:3.9.9-eclipse-temurin-21`
=> Update Gradle image for docker in pipeline

content/doc/developer/crowdin/crowdin-integration.adoc
This was needed in pipeline graph view for some additional locales that were extracted from translations in Jenkins core.
https://github.com/jenkinsci/pipeline-graph-view-plugin/blob/main/crowdin.yml
I don't think it fully works in that you can edit those translations in crowdin, but it stops them from being uploaded which is worse.
=> Add more crowdin config

content/doc/book/pipeline/docker.adoc
The original gradle command fails with the message:
```
+ gradle --version
FAILURE: Build failed with an exception.
* What went wrong:
Gradle could not start your build.
> Could not initialize native services.
> Failed to load native library 'libnative-platform.so' for Linux amd64.
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
```
A workaround / solution is offered in a [stackoverflow article](https://stackoverflow.com/questions/38519643/failed-to-load-native-library-libnative-platform-so-for-linux-amd64).
Once that change is made, the Pipeline output is:
```
+ gradle -g gradle-user-home --version
Welcome to Gradle 8.14!
Here are …
```
=> Fix reuseNode sample Pipeline

content/_data/changelogs/weekly.yml
Address [concern](https://github.com/jenkins-infra/jenkins.io/pull/8053#issuecomment-2848761005) from Daniel Beck that the spelling fix in the message is not impactful enough to justify an entry in the weekly changelog.
The Jenkins 2.478 changelog has an empty entry that is displayed as "No notable changes in this release".  This will be displayed in the same way.
For comparison, see 2.478 on www.jenkins.io and on the GitHub repository:
* https://www.jenkins.io/changelog/2.478/
* https://github.com/jenkinsci/jenkins/releases/tag/jenkins-2.478
This changelog retains the comments for the skipped entries.  The 2.478 changelog data has not been adjusted to include the skipped entries.
=> Remove low impact bug fix from 2.508 changelog

content/_data/changelogs/weekly.yml
This PR adds a banner to the 2.509 weekly changelog to inform users that the docker images are now using Java 21 as the default JDK. It includes links to both the docker image changelog & the specific PR where this change took place
=> Add banner for docker image Java 21 change

content/_data/changelogs/weekly.yml
This PR adds back a line for the jbcrypt/spring security entry of the 2.509 changelog.
=> Add back Active Directory upgrade instruction for 2.509 changelog

content/_data/changelogs/weekly.yml
This PR is to update the 2.509 changelog with a separate entry for the jbcrypt library removal. Previously, just the message was updated, whereas it should be highlighted more specifically.
=> Add separate entry for jbcrypt library removal

content/_data/indexpage/carousel.yml
This PR is to update the Community Awards slide on the carousel to point to the latest blog post (announcing voting is open) and update the voting period dates to match the updated voting period.
=> Update 2025 Community Awards carousel slide

content/doc/book/installing/_kubernetes.adoc
Description: 
The issue has been discussed in the Jenkins discourse channel via [this](https://community.jenkins.io/t/links-on-site-install-jenkins-on-kubernetes-not-working/31131) 
This PR updates the documentation to point to the correct official YAML files for Jenkins on Kubernetes installation.
I verified the links are working now .
=> fix: yaml links in kubernetes page

content/doc/developer/security/remoting-callables.adoc
Updated after https://github.com/jenkinsci/jenkins/pull/9921.
=> Recommend `ControllerToAgentCallable`

scripts/docker-env
[ATH PR 2032](https://github.com/jenkinsci/acceptance-test-harness/pull/2032) shares what Basil Crow learned about bind mounts on Docker containers using Fedora Linux.
Fedora Linux SELinux requires the ":Z" option when bind-mounting local volumes into the container.
Confirmed that `make run` fails on Fedora Linux 42 before this change and passes after this change.
Confirmed that `make run` succeeds on Ubuntu Linux in both cases.
=> Use ':Z' option to bind mount Docker volumes on SELinux

content/_data/changelogs/weekly.yml
This PR is to update the packaging entry for the 2.512 changelog so that the reference/URL works as expected. Currently it is only showing as white text instead of a clickable link.
=> Update 2.512 packaging entry

content/doc/book/managing/system-properties.adoc
This PR is to document [jenkinsci/jenkins#10630](https://github.com/jenkinsci/jenkins/pull/10630) as originally submitted in https://github.com/jenkins-infra/jenkins.io/pull/8124 by @daniel-beck. Since that PR was merged too early and reverted, this plans to replace the documentation once the associated PR in jenkinsci is merged.
=> Document jenkins.security.JettySameSiteCookieSetup.sameSiteDefault

content/solutions/c.adoc
All other pages has a content in their pages except c/c++. 
I have added some important resources and content to it . 
I have checked the links.
=> feat:add content to c/c++ solution page

content/download/mirrors.adoc
Related to https://github.com/jenkins-infra/helpdesk/issues/2953
Context: With https://github.com/jenkins-infra/helpdesk/issues/4681 and https://github.com/jenkins-infra/helpdesk/issues/4653, it is mandatory to provide a single source of truth to mirror maintainer so they can keep their setup up to date.
This PR provides such documentation on the existing page https://www.jenkins.io/download/mirrors/ as described in https://github.com/jenkins-infra/helpdesk/issues/2953.
Using www.jenkins.io for this information ensure we get enough visibility for future mirror maintainers.
=> fix(download/mirrors) update instructions for mirror maintainers

content/_data/authors/biru-codeastromer.adoc, content/blog/2025/06/03/2025-06-03-birajit-saikia-gsoc-community-bonding-blog-post.adoc
Updated my blog post project to new project page link instead of the old project idea page .
=> fix: birajit blog post project links to latest project page 

content/doc/book/platform-information/support-policy-web-browsers.adoc
Preview: https://deploy-preview-8191--jenkins-io-site-pr.netlify.app/doc/book/platform-information/support-policy-web-browsers/
We don't support any other long term browsers.
The world has moved on from fixed point in time browsers like Internet Explorer and Firefox ESR. In my experience most corporations are using Edge or Chrome these days.
The current ESR version is nearly 2 years old at this point and missing features that Firefox has had for a long time.
-----
The usage of ESR appears to be extremely low as we shipped a feature [breaking color](https://github.com/jenkinsci/jenkins/pull/10078) in it 5 months ago (which has progressed through an entire LTS line) and only had 1 user report about it.
-----
I think level 2 is ok for this, in the example of broken colour its still …
=> Move Firefox ESR to level 2 support

content/_data/adopters/D4Science.adoc, content/blog/2020/10/2020-10-20-Cross-Industry-DevOps-3-Firms-Get-It-Right-with-Jenkins.adoc, content/blog/2020/12/2020-12-05-3-Cases-Jenkins-Success-stories-from-the-community.adoc, content/blog/2021/01/2021-01-26-new-ebook-build-deploy-and-automate-great-stuff-with-jenkins.adoc, content/blog/2021/06/2021-06-10-jenkins-is-the-way-ebook-2.adoc, content/blog/2021/09/2021-09-22-fortune-500-real-world-results.adoc
Ref. https://github.com/jenkins-infra/helpdesk/issues/4709
This PR is a simple "search and replace" of all occurrences of `https://jenkinsistheway.io/` by `https://stories.jenkins.io/`.
The following links are now OK (HTTP/200):
- https://stories.jenkins.io/
- https://stories.jenkins.io/user-story/to-automate-everything/
- https://stories.jenkins.io/user-story/to-experiments-and-eternity/
However the following links are still "Not Found" (HTTP/404) and I have no idea if they should be kept "as it", changed (as part of this PR), removed or other (cc @kmartens27 as docs SIG leader and @alyssat @gounthar as Developer evangelists)?
- https://stories.jenkins.io/case-studies/d4science-amps-up-their-scientific-research-platform-with-ci-cd-powered-by-jenkins/
- …
=> fix: replace links to https://jenkinsistheway.io/ by https://stories.jenkins.io/

content/_data/roadmap/roadmap.yml
This PR updates the Jenkins roadmap (https://www.jenkins.io/project/roadmap/) to ensure Jenkins Infrastructure main tasks ("EPIC"s?) are up to date as per the team discussions.
Preview:
=> feat(roadmap) update jenkins-infra tasks for June 2025

content/projects/gsoc/2025/projects/ai-powered-chatbot-for-quick-access-to-jenkins-resources.adoc, content/projects/gsoc/2025/projects/complete-alternative-jenkins-io-build-retooling.adoc, content/projects/gsoc/2025/projects/domain-specific-LLM-based-on-jenkins-usage-using-ci-jenkins-io-data.adoc, content/projects/gsoc/2025/projects/improving-tekton-client-plugin.adoc
This PR removes the `gitter:` field from the frontmatter of GSoC 2025 project pages that currently include it, aligning them structurally with other project pages like “Improving Plugin Modernizer” which do not use this metadata key.
The `gitter:` field triggers an automatic badge-based rendering on the frontend, which is currently resulting in a broken image icon due to a failed badge load.
=> Remove metadata field for consistent link rendering across GSoC projects pages

content/_data/indexpage/carousel.yml
This PR is to update the jumbotron to remove the Alpha/Omega grant and add the Jenkins redesign with Jan's blog post.
=> Update jumbotron with Jenkins redesign

content/support.adoc
The related links are not of interest to most readers of the support page.
=> Remove the related links section from support page

content/doc/developer/publishing/releasing-cd.adoc
The previous link didn't properly redirect to the cd workflow but to the All workflows page.
=> Fix the cd workflow URL

content/doc/book/pipeline/jenkinsfile.adoc
This PR adds a new error handling section with links to the Pipeline: Basic Steps plugin, for more information about the `catchError`, `error`, `unstable`, and `warnError` steps.
=> Added information and links for pipeline step error handling

content/security/advisory/2025-09-03.adoc
There is two backports of the SECURITY-3590 fix of git-client that were created today.
I'm updating the advisory description to represent that. 
See also https://github.com/jenkins-infra/update-center2/pull/887
=> Update 2025-09-03 security advisory

content/_data/changelogs/weekly.yml
Fixing a small typo, identified while running `make check`.
Before:
```
make check
scripts/check-hard-coded-URL-references
scripts/check-typos
error: `breadcumbs` should be `breadcrumbs`
--> ./content/_data/changelogs/weekly.yml:27570:41
|
27570 |           Only hide the dropdown on the breadcumbs, not on other menus.
|                                         ^^^^^^^^^^
|
make: *** [Makefile:123: check] Error 2
```
After: 
```
make check
scripts/check-hard-coded-URL-references
scripts/check-typos
```
=> Fix typo on JENKINS-75834 description

Jenkinsfile
Since #8283, we purge the cache of the whole website on each deployment, which is quite heavy.
This PR changes back to the old behavior (only purge 2 CSS URLs) now that the associated credential (`FASTLY_API_TOKEN`) has been updated to support partial purge.
Tested with success using a replay on trusted.ci.jenkins.io
=> chore(Jenkinsfile) purge cache of only a few pages instead of the whole website during production deployment

content/support.adoc
Make helpdesk more discoverable. Right now it's only really linked from "Report Issue" and the governance doc (???).
The rest of the page is already in violation of sentence case titles specified in https://github.com/jenkins-infra/jenkins.io/blob/master/STYLEGUIDE.adoc#assorted-comments, so I made the new title consistent with that.
=> Link infra helpdesk on support page
